## Loading data

In [1]:
# Importing the necessary libraries
import pandas as pd
import numpy as np
import kennard_stone as ks
pd.options.plotting.backend = 'plotly'  # setting plotly as the backend for pandas plotting

# Add parent directory to sys.path so local module 'synthetic' (one level up) can be imported
import sys
from pathlib import Path # for path manipulations
parent_dir = Path.cwd().parent.parent.resolve() # move two levels up from current working directory
if str(parent_dir) not in sys.path: # check to avoid duplicates
    sys.path.insert(0, str(parent_dir)) # insert at the start of sys.path to prioritize local modules

# Loading a soil spectral dataset based on X-ray fluorescence (XRF)
data_complete = pd.read_csv(f'{parent_dir}/XRF_databases/forage/plsda/forage.csv', sep=';') # local copy of Toledo 2022 dataset (os ... indica para omitir o caminho longo)
data = data_complete.loc[:, '1.4':'20.81']

# Split dataset by class and create calibration/prediction sets using Kennard-Stone (as in original pipeline)
data_A = data_complete[data_complete['Class'] == 'A'].reset_index(drop=True)
data_B = data_complete[data_complete['Class'] == 'B'].reset_index(drop=True)

# splitting the data into calibration and prediction sets by kennard-stone algorithm
XA_cal, XA_pred = ks.train_test_split(data_A.loc[:, '1.4':'20.81'], test_size=0.30)  # class A
XA_cal = XA_cal.reset_index(drop=True)
XA_pred = XA_pred.reset_index(drop=True)

XB_cal, XB_pred = ks.train_test_split(data_B.loc[:, '1.4':'20.81'], test_size=0.30)  # class B
XB_cal = XB_cal.reset_index(drop=True)
XB_pred = XB_pred.reset_index(drop=True)

Xcalclass = pd.concat([XA_cal, XB_cal], axis=0).reset_index(drop=True)  # concatenating both classes
Xpredclass = pd.concat([XA_pred, XB_pred], axis=0).reset_index(drop=True)
ycalclass = pd.Series(['A']*XA_cal.shape[0] + ['B']*XB_cal.shape[0])  # target for calibration set
ypredclass = pd.Series(['A']*XA_pred.shape[0] + ['B']*XB_pred.shape[0])  # target for prediction set

# preprocessings
import preprocessings as prepr  # preprocessing methods for XRF data

Xcalclass_prep, mean_calclass, mean_calclass_poisson  = prepr.poisson(Xcalclass, mc=True)
Xpredclass_prep = ((Xpredclass/np.sqrt(mean_calclass)) - mean_calclass_poisson)

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-02-02 14:52:07,623 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-02-02 14:52:07,643 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-02-02 14:52:07,700 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-02-02 14:52:07,768 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

In [2]:
# PLS-DA with optimized latent variables
from modeling import pls_optimized

plsda_results = pls_optimized(
    Xcalclass_prep, 
    ycalclass,
    LVmax=3,
    Xpred=Xpredclass_prep,
    ypred=ypredclass,
    aim='classification',
    cv=10
)

# Convenience references used later
pls_model = plsda_results[3]               # fitted PLS model
vip_scores_mat = plsda_results[4]          # VIP scores matrix (features × LV)
y_pred_cont = plsda_results[5].iloc[:, -1] # continuous predictions for Xcalclass (used for MI/Cov)

# plotando o vip scores rapidamente
vip_scores_mat.T.plot()

In [3]:
# calculando a covariancia entre cada variável espectral e a predição do modelo PLS-DA
cov_scores = []
y_pred = plsda_results[5].iloc[:,-1].values # using the continuous predictions from LV=3
for col in Xcalclass_prep.columns:
    x_values = Xcalclass_prep[col].values
    covariance = np.cov(x_values, y_pred)[0, 1] # covariance between x and y
    cov_scores.append(covariance)
cov_scores_df = pd.DataFrame(cov_scores, index=Xcalclass_prep.columns, columns=['Covariance'])
cov_scores_df = np.abs(cov_scores_df)
cov_scores_df.plot()

In [4]:
# establishing spectral cuts based on expert knowledge of XRF spectra
spectral_cuts = [
('Al', 1.40, 1.63),
('Si', 1.63, 1.86),
('P', 1.86, 2.16),
('S', 2.16, 2.44),
('Rh L + Ar', 2.44, 3.10),
('K', 3.10, 3.46),
('Ca ka', 3.46, 3.86),
('Ca kb', 3.86, 4.16),
('background1', 4.14, 4.37),
('Ti ka', 4.37, 4.66),
('Ti kb', 4.66, 5.08),
('background2', 5.08, 5.72),
('Mn', 5.72, 6.10),
('Fe ka', 6.10, 6.76),
('Fe kb', 6.76, 7.20),
('Ni', 7.20, 7.69),
('background3', 7.69, 13.10),
('sum Fe' , 13.10, 13.63),
('background4', 13.63, 18.0),
('Compton scattering', 18.0, 19.70),
('Rayleight scattering', 19.70, 20.80)
]

import explaining as exp
spectral_zones_class = exp.extract_spectral_zones(Xcalclass_prep, spectral_cuts)
zone_sums_df = exp.aggregate_spectral_zones(spectral_zones_class, aggregator='extreme')
predicates_quantiles = exp.predicates_by_quantiles(zone_sums_df, [0.2, 0.4, 0.6, 0.8])
co_occurrence_matrix_df = predicates_quantiles[2]
predicate_info_dict = exp.create_predicate_info_dict(
    predicates_df=predicates_quantiles[0],
    predicate_indicator_df=predicates_quantiles[1],
    zone_aggregated_df=zone_sums_df,
    y_predicted_numeric=y_pred
)

## VIP, Regression Coefficients e SHAP (como no original)

In [5]:
# VIP scores por energia
vip_scores_df = pd.DataFrame({
    'energy': vip_scores_mat.T.index,
    'VIP_Score': vip_scores_mat.T.iloc[:,0].values
})
vip_scores_df = vip_scores_df.sort_values(by='VIP_Score', ascending=False).reset_index(drop=True)
energy_to_zone_vip = {}
for zone_name, start, end in spectral_cuts:
    for e in vip_scores_df['energy']:
        ef = float(e)
        if start <= ef <= end:
            energy_to_zone_vip[e] = zone_name
vip_scores_df['Zone'] = vip_scores_df['energy'].map(energy_to_zone_vip)
vip_scores_unique_df = vip_scores_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
vip_scores_unique_df = vip_scores_unique_df.sort_values(by='VIP_Score', ascending=False).reset_index(drop=True)

# Coeficientes de regressão do PLS
reg_vet = pd.DataFrame(pls_model.coef_, columns=pls_model.feature_names_in_).T
reg_vet.insert(0, 'energy', reg_vet.index)
reg_vet = reg_vet.reset_index(drop=True)
reg_vet.columns = ['energy','Reg_coef']
reg_vet['Abs_Reg_coef'] = reg_vet['Reg_coef'].abs()
reg_vet = reg_vet.sort_values(by='Abs_Reg_coef', ascending=False).reset_index(drop=True)
energy_to_zone_reg = {}
for zone_name, start, end in spectral_cuts:
    for e in reg_vet['energy']:
        ef = float(e)
        if start <= ef <= end:
            energy_to_zone_reg[e] = zone_name
reg_vet['Zone'] = reg_vet['energy'].map(energy_to_zone_reg)
reg_vet_unique_df = reg_vet.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
reg_vet_unique_df = reg_vet_unique_df.sort_values(by='Abs_Reg_coef', ascending=False).reset_index(drop=True)

# **bagging - covariance**

In [6]:
import explaining as exp

# LISTA DE SEMENTES A TESTAR
random_seeds = [0, 1, 2, 3]

all_results_cov = {}
training_samples = len(Xcalclass)

# LOOP: PROCESSAR CADA SEMENTE
y_predicted_numeric = plsda_results[5].iloc[:, -1] # predições numéricas do modelo

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando semente: {seed}")
    print(f"{'='*70}\n")
    # Bagging
    bags_result_seed = exp.bagging_predicates(
        zone_sums_df=zone_sums_df,
        y_predicted_numeric=y_predicted_numeric,
        predicates_df=predicates_quantiles[0],
        n_bags=10,
        #n_predicates_per_bag=40,
        n_samples_per_bag=int(training_samples*0.8), # 80 % da base para amostrar (convertido para int)
        min_samples_per_predicate=int(training_samples*0.2), # 20 % da base para limitar (convertido para int)
        replace=False,
        sample_bagging=True,
        predicate_bagging=False,
        random_seed=seed
    )
    # Inserir classe prevista
    for bag_name, pred_dict in bags_result_seed.items(): # iterando sobre cada bag
        for pred_rule, df_info in pred_dict.items():
            df_info['Class_Predicted'] = np.where(df_info['Predicted_Y'] >= 0.5, 'A', 'B') # binarizando com threshold 0.5, A = eut, B = dist
    # Calcular MI
    cov_results_dict_seed = exp.calculate_predicate_metrics(
        bags_result=bags_result_seed,
        metric='covariance', # covariance ou mutual_information
        threshold=0.01, # threshold para cortar predicados irrelevantes
        n_neighbors=5
    )
    # Salvar no dicionário principal
    all_results_cov[seed] = {
        'bags_result': bags_result_seed,
        'cov_results_dict': cov_results_dict_seed
    }

# CONSTRUÇÃO DE GRAFOS PARA MÚLTIPLAS SEMENTES (LOOP EXTERNO)
# Dicionário para armazenar grafos
graphs_by_seed = {}

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando Grafo - Semente: {seed}")
    print(f"{'='*70}\n")
    # Construir grafo para esta semente
    DG = exp.build_predicate_graphv2(
        bags_result=all_results_cov[seed]['bags_result'],
        predicate_ranking_dict=all_results_cov[seed]['cov_results_dict'],
        metric_column='Covariance',  # ou 'Covariance' se mudar a métrica
        random_state=seed,
        show_details=True
    )
    # Armazenar grafo
    graphs_by_seed[seed] = DG

# Calcular LRC usando a função pronta do explaining.py
lrc_cov_by_seed = {}
for seed in random_seeds:
    DG = graphs_by_seed[seed]
    lrc_cov_df_seed = exp.calculate_lrc_single_graph(DG, predicates_quantiles[0])
    lrc_cov_df_seed['Seed'] = seed  # Adicionar coluna com a semente
    lrc_cov_by_seed[seed] = lrc_cov_df_seed

# junando todas as colunas 'Node' de lrc_by_seed em um único dataframe
lrc_cov_all_seeds_df = pd.DataFrame()
for seed in random_seeds:
    lrc_cov_df_seed = lrc_cov_by_seed[seed].rename(columns={'Node': f'Predicate_Cov_Seed_{seed}'})
    lrc_cov_all_seeds_df = pd.concat([lrc_cov_all_seeds_df, lrc_cov_df_seed[[f'Predicate_Cov_Seed_{seed}']]], axis=1)

# vamos filtrar lrc_by_seed em cada semente para manter apenas as zonas espectrais únicas com maior LRC em um mesmo dataframe
lrc_cov_unique_by_seed = {}
for seed, lrc_df in lrc_cov_by_seed.items():
    lrc_cov_unique_df = lrc_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
    lrc_cov_unique_df = lrc_cov_unique_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
    lrc_cov_unique_by_seed[seed] = lrc_cov_unique_df

lrc_cov_all_seeds_df # exibindo o dataframe consolidado com predicados de todas as sementes

======================================================================
Processando semente: 0
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando semente: 1
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 127 | Descartados: 41
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 127 | Descartados: 41
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 127 | Descartados: 41
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando semente: 2
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 128 | Descartados: 40
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 127 | Descartados: 41
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 127 | Descartados: 41
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando semente: 3
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 127 | Descartados: 41
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 127 | Descartados: 41
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando Grafo - Semente: 0
======================================================================


Total de pares bidirecionais encontrados: 92
Removida aresta Fe ka > -0.89 -> Fe ka > -1.49 (peso 2.9745)
Mantida aresta Fe ka > -1.49 -> Fe ka > -0.89 (peso 6.9380)

======================================================================

Removida aresta Si > -0.73 -> Si > -1.10 (peso 1.0903)
Mantida aresta Si > -1.10 -> Si > -0.73 (peso 3.3628)

======================================================================

Removida aresta Si > -1.10 -> Ca ka <= 1.96 (peso 1.1033)
Mantida aresta Ca ka <= 1.96 -> Si > -1.10 (peso 2.8115)

======================================================================

Removida aresta Si > -0.73 -> Ca ka <= 1.96 (peso 1.0981)
Mantida aresta Ca ka <= 1.96 -> Si > -0.73 (peso 1.1099)

======================================================================

Removida aresta Ca ka <= 1.96 -> K > -2.69 (peso 1.0820)
Mantida aresta K > -2.69 -> Ca ka <= 1.96 (peso 2.2452)

======================================================================

Removida aresta K <= 2.49 -> K > -2.69 (peso 0.4785)
Mantida aresta K > -2.69 -> K <= 2.49 (peso 1.0188)

======================================================================

Removida aresta Ca ka > -2.11 -> K > -2.69 (peso 0.4538)
Mantida aresta K > -2.69 -> Ca ka > -2.11 (peso 0.9527)

======================================================================

Removida aresta Ca ka > -2.11 -> K <= 2.49 (peso 0.4244)
Mantida aresta K <= 2.49 -> Ca ka > -2.11 (peso 1.4243)

======================================================================

Removida aresta Ca ka <= 0.86 -> K <= 2.49 (peso 0.4409)
Mantida aresta K <= 2.49 -> Ca ka <= 0.86 (peso 0.8877)

======================================================================

Removida aresta Ca ka <= 0.86 -> Ca ka > -2.11 (peso 0.8548)
Mantida aresta Ca ka > -2.11 -> Ca ka <= 0.86 (peso 2.1239)

======================================================================

Removida aresta K > -0.94 -> Ca ka > -2.11 (peso 0.4136)
Mantida aresta Ca ka > -2.11 -> K > -0.94 (peso 0.8327)

======================================================================

Removida aresta Ca ka <= 0.86 -> K > -0.94 (peso 0.3962)
Mantida aresta K > -0.94 -> Ca ka <= 0.86 (peso 0.4037)

======================================================================

Removida aresta Si > -0.34 -> K > -0.94 (peso 1.1053)
Mantida aresta K > -0.94 -> Si > -0.34 (peso 1.5297)

======================================================================

Removida aresta Ti ka > -0.26 -> Ti ka > -0.40 (peso 0.2868)
Mantida aresta Ti ka > -0.40 -> Ti ka > -0.26 (peso 0.4843)

======================================================================

Removida aresta Fe kb > -0.23 -> Ca kb <= 0.69 (peso 0.2124)
Mantida aresta Ca kb <= 0.69 -> Fe kb > -0.23 (peso 0.2327)

======================================================================

Removida aresta Ti ka > -0.26 -> Ca kb <= 0.69 (peso 0.2427)
Mantida aresta Ca kb <= 0.69 -> Ti ka > -0.26 (peso 0.4537)

======================================================================

Removida aresta Fe kb > -0.31 -> Ti ka > -0.26 (peso 0.2067)
Mantida aresta Ti ka > -0.26 -> Fe kb > -0.31 (peso 0.4748)

======================================================================

Removida aresta Rh L + Ar > -0.42 -> Fe kb > -0.40 (peso 0.2111)
Mantida aresta Fe kb > -0.40 -> Rh L + Ar > -0.42 (peso 0.2664)

======================================================================

Removida aresta Rh L + Ar > -0.42 -> Fe kb > -0.23 (peso 0.1960)
Mantida aresta Fe kb > -0.23 -> Rh L + Ar > -0.42 (peso 0.2216)

======================================================================

Removida aresta Fe kb > -0.40 -> Fe kb > -0.23 (peso 0.2211)
Mantida aresta Fe kb > -0.23 -> Fe kb > -0.40 (peso 0.2494)

======================================================================

Removida aresta Ti ka > -0.26 -> Fe kb > -0.40 (peso 0.1952)
Mantida aresta Fe kb > -0.40 -> Ti ka > -0.26 (peso 0.2458)

======================================================================

Removida aresta Ca ka > -0.97 -> Ca ka <= -0.97 (peso 0.1711)
Mantida aresta Ca ka <= -0.97 -> Ca ka > -0.97 (peso 0.1831)

======================================================================

Removida aresta Ca ka <= -0.97 -> Fe kb > -0.23 (peso 0.1668)
Mantida aresta Fe kb > -0.23 -> Ca ka <= -0.97 (peso 0.3698)

======================================================================

Removida aresta Ca kb <= 0.31 -> Ca ka <= -0.97 (peso 0.1647)
Mantida aresta Ca ka <= -0.97 -> Ca kb <= 0.31 (peso 0.5392)

======================================================================

Removida aresta Ti ka > -0.26 -> K <= 0.94 (peso 0.1990)
Mantida aresta K <= 0.94 -> Ti ka > -0.26 (peso 0.2472)

======================================================================

Removida aresta Ca ka > -0.97 -> K <= 0.94 (peso 0.1830)
Mantida aresta K <= 0.94 -> Ca ka > -0.97 (peso 0.5731)

======================================================================

Removida aresta Rh L + Ar > -0.13 -> Ca ka > -0.97 (peso 0.1622)
Mantida aresta Ca ka > -0.97 -> Rh L + Ar > -0.13 (peso 0.1949)

======================================================================

Removida aresta Ca kb <= 0.31 -> Ca ka > -0.97 (peso 0.3348)
Mantida aresta Ca ka > -0.97 -> Ca kb <= 0.31 (peso 0.3594)

======================================================================

Removida aresta Ca kb > -0.79 -> Ca ka > -0.97 (peso 0.3146)
Mantida aresta Ca ka > -0.97 -> Ca kb > -0.79 (peso 0.4823)

======================================================================

Removida aresta Rh L + Ar > -0.13 -> Rh L + Ar > -0.78 (peso 0.3536)
Mantida aresta Rh L + Ar > -0.78 -> Rh L + Ar > -0.13 (peso 0.4443)

======================================================================

Removida aresta Rh L + Ar > -0.13 -> Si <= 1.59 (peso 0.3658)
Mantida aresta Si <= 1.59 -> Rh L + Ar > -0.13 (peso 0.3860)

======================================================================

Removida aresta Si <= 1.59 -> Rh L + Ar > -0.78 (peso 0.1520)
Mantida aresta Rh L + Ar > -0.78 -> Si <= 1.59 (peso 0.3678)

======================================================================

Removida aresta Ca kb > -0.79 -> Rh L + Ar > -0.78 (peso 0.1529)
Mantida aresta Rh L + Ar > -0.78 -> Ca kb > -0.79 (peso 0.1559)

======================================================================

Removida aresta Rh L + Ar > -0.78 -> Fe kb > -0.23 (peso 0.2146)
Mantida aresta Fe kb > -0.23 -> Rh L + Ar > -0.78 (peso 0.2226)

======================================================================

Removida aresta Fe kb > -0.23 -> Si <= 1.59 (peso 0.2141)
Mantida aresta Si <= 1.59 -> Fe kb > -0.23 (peso 0.3792)

======================================================================

Removida aresta Ca kb <= 0.31 -> Si <= 1.59 (peso 0.1704)
Mantida aresta Si <= 1.59 -> Ca kb <= 0.31 (peso 0.1796)

======================================================================

Removida aresta Ca kb > -0.79 -> Ca kb <= 0.31 (peso 0.3306)
Mantida aresta Ca kb <= 0.31 -> Ca kb > -0.79 (peso 0.3503)

======================================================================

Removida aresta Ca ka > 0.86 -> K <= -0.94 (peso 0.4183)
Mantida aresta K <= -0.94 -> Ca ka > 0.86 (peso 0.6695)

======================================================================

Removida aresta Fe ka <= 0.50 -> Ca ka > 0.86 (peso 0.0822)
Mantida aresta Ca ka > 0.86 -> Fe ka <= 0.50 (peso 0.2356)

======================================================================

Removida aresta Al > -0.33 -> Ca ka > 0.86 (peso 0.0791)
Mantida aresta Ca ka > 0.86 -> Al > -0.33 (peso 0.0808)

======================================================================

Removida aresta Ca kb <= -0.30 -> Fe ka <= 0.50 (peso 0.0800)
Mantida aresta Fe ka <= 0.50 -> Ca kb <= -0.30 (peso 0.3580)

======================================================================

Removida aresta Fe ka <= 0.50 -> P > 0.26 (peso 0.1416)
Mantida aresta P > 0.26 -> Fe ka <= 0.50 (peso 0.3405)

======================================================================

Removida aresta Fe ka <= 0.50 -> Al > -0.33 (peso 0.0793)
Mantida aresta Al > -0.33 -> Fe ka <= 0.50 (peso 0.1441)

======================================================================

Removida aresta K > 0.94 -> P > 0.26 (peso 0.0745)
Mantida aresta P > 0.26 -> K > 0.94 (peso 0.2368)

======================================================================

Removida aresta Al > -0.33 -> K > 0.94 (peso 0.0761)
Mantida aresta K > 0.94 -> Al > -0.33 (peso 0.0762)

======================================================================

Removida aresta Al <= 0.34 -> Ca kb > -0.30 (peso 0.0589)
Mantida aresta Ca kb > -0.30 -> Al <= 0.34 (peso 0.1242)

======================================================================

Removida aresta Al > -0.17 -> Ca kb > -0.30 (peso 0.0555)
Mantida aresta Ca kb > -0.30 -> Al > -0.17 (peso 0.1216)

======================================================================

Removida aresta Ca kb > -0.30 -> P <= 0.51 (peso 0.0542)
Mantida aresta P <= 0.51 -> Ca kb > -0.30 (peso 0.0564)

======================================================================

Removida aresta Ti kb > -0.13 -> Ca kb > -0.30 (peso 0.0482)
Mantida aresta Ca kb > -0.30 -> Ti kb > -0.13 (peso 0.0491)

======================================================================

Removida aresta Al <= 0.34 -> Compton scattering > -0.17 (peso 0.0583)
Mantida aresta Compton scattering > -0.17 -> Al <= 0.34 (peso 0.2281)

======================================================================

Removida aresta Al > -0.17 -> Al <= 0.34 (peso 0.0622)
Mantida aresta Al <= 0.34 -> Al > -0.17 (peso 0.0682)

======================================================================

Removida aresta Compton scattering > -0.17 -> Al > -0.17 (peso 0.0577)
Mantida aresta Al > -0.17 -> Compton scattering > -0.17 (peso 0.1075)

======================================================================

Removida aresta sum Fe > 0.13 -> Compton scattering > -0.17 (peso 0.0532)
Mantida aresta Compton scattering > -0.17 -> sum Fe > 0.13 (peso 0.0884)

======================================================================

Removida aresta Compton scattering > -0.17 -> P <= 0.51 (peso 0.0522)
Mantida aresta P <= 0.51 -> Compton scattering > -0.17 (peso 0.0540)

======================================================================

Removida aresta Al > -0.17 -> P <= 0.51 (peso 0.0559)
Mantida aresta P <= 0.51 -> Al > -0.17 (peso 0.0630)

======================================================================

Removida aresta Ti kb > -0.16 -> Al > -0.17 (peso 0.1086)
Mantida aresta Al > -0.17 -> Ti kb > -0.16 (peso 0.1256)

======================================================================

Removida aresta Ti kb > -0.16 -> P <= 0.51 (peso 0.0532)
Mantida aresta P <= 0.51 -> Ti kb > -0.16 (peso 0.1043)

======================================================================

Removida aresta Ti kb > -0.13 -> P <= 0.51 (peso 0.0570)
Mantida aresta P <= 0.51 -> Ti kb > -0.13 (peso 0.1019)

======================================================================

Removida aresta Ti kb > 0.11 -> P <= 0.51 (peso 0.0427)
Mantida aresta P <= 0.51 -> Ti kb > 0.11 (peso 0.0471)

======================================================================

Removida aresta Ti kb > -0.16 -> Ti kb > -0.13 (peso 0.0484)
Mantida aresta Ti kb > -0.13 -> Ti kb > -0.16 (peso 0.1024)

======================================================================

Removida aresta Ti kb > -0.13 -> sum Fe > -0.24 (peso 0.0469)
Mantida aresta sum Fe > -0.24 -> Ti kb > -0.13 (peso 0.0543)

======================================================================

Removida aresta sum Fe > -0.15 -> sum Fe > 0.13 (peso 0.0421)
Mantida aresta sum Fe > 0.13 -> sum Fe > -0.15 (peso 0.1166)

======================================================================

Removida aresta sum Fe > -0.15 -> Compton scattering > 0.14 (peso 0.0316)
Mantida aresta Compton scattering > 0.14 -> sum Fe > -0.15 (peso 0.0425)

======================================================================

Removida aresta Compton scattering > 0.14 -> Rayleight scattering > -0.19 (peso 0.0245)
Mantida aresta Rayleight scattering > -0.19 -> Compton scattering > 0.14 (peso 0.0357)

======================================================================

Removida aresta Ca kb > 0.31 -> Compton scattering > 0.14 (peso 0.0390)
Mantida aresta Compton scattering > 0.14 -> Ca kb > 0.31 (peso 0.0433)

======================================================================

Removida aresta Compton scattering > -0.23 -> Compton scattering > 0.14 (peso 0.0385)
Mantida aresta Compton scattering > 0.14 -> Compton scattering > -0.23 (peso 0.0804)

======================================================================

Removida aresta Compton scattering > 0.14 -> Rayleight scattering > -0.14 (peso 0.0369)
Mantida aresta Rayleight scattering > -0.14 -> Compton scattering > 0.14 (peso 0.0439)

======================================================================

Removida aresta Ti kb > 0.11 -> sum Fe > -0.15 (peso 0.0431)
Mantida aresta sum Fe > -0.15 -> Ti kb > 0.11 (peso 0.0865)

======================================================================

Removida aresta Mn > -0.21 -> Fe kb <= 0.29 (peso 0.0238)
Mantida aresta Fe kb <= 0.29 -> Mn > -0.21 (peso 0.0328)

======================================================================

Removida aresta Fe kb <= 0.29 -> S <= 0.29 (peso 0.0301)
Mantida aresta S <= 0.29 -> Fe kb <= 0.29 (peso 0.0347)

======================================================================

Removida aresta Fe kb <= 0.29 -> background4 > -0.17 (peso 0.0292)
Mantida aresta background4 > -0.17 -> Fe kb <= 0.29 (peso 0.0329)

======================================================================

Removida aresta S <= 0.29 -> Rayleight scattering > -0.14 (peso 0.0267)
Mantida aresta Rayleight scattering > -0.14 -> S <= 0.29 (peso 0.0354)

======================================================================

Removida aresta Compton scattering > -0.23 -> Mn > 0.18 (peso 0.0259)
Mantida aresta Mn > 0.18 -> Compton scattering > -0.23 (peso 0.0457)

======================================================================

Removida aresta Rayleight scattering > -0.19 -> Compton scattering > -0.23 (peso 0.0269)
Mantida aresta Compton scattering > -0.23 -> Rayleight scattering > -0.19 (peso 0.1379)

======================================================================

Removida aresta background3 > 0.17 -> Ti ka <= 0.27 (peso 0.0235)
Mantida aresta Ti ka <= 0.27 -> background3 > 0.17 (peso 0.0251)

======================================================================

Removida aresta P <= -0.30 -> Mn <= 0.47 (peso 0.0198)
Mantida aresta Mn <= 0.47 -> P <= -0.30 (peso 0.0331)

======================================================================

Removida aresta Ti kb > 0.11 -> S <= 0.29 (peso 0.0337)
Mantida aresta S <= 0.29 -> Ti kb > 0.11 (peso 0.0355)

======================================================================

Removida aresta Mn > -0.52 -> P <= -0.30 (peso 0.0210)
Mantida aresta P <= -0.30 -> Mn > -0.52 (peso 0.0269)

======================================================================

Removida aresta background4 > 0.16 -> P <= -0.30 (peso 0.0182)
Mantida aresta P <= -0.30 -> background4 > 0.16 (peso 0.0209)

======================================================================

Removida aresta background4 > 0.16 -> Ti kb <= 0.18 (peso 0.0216)

,Predicate_Cov_Seed_0,Predicate_Cov_Seed_1,Predicate_Cov_Seed_2,Predicate_Cov_Seed_3
0,Fe ka > -1.26,Fe ka > -1.26,Fe ka > -1.26,Fe ka > -1.49
1,Fe ka > -1.49,Fe ka > -1.49,Si > -1.10,Fe ka > -1.26
2,Ca ka <= 1.96,Fe ka > -0.89,Fe ka > -0.89,Fe ka > -0.89
3,Si > -1.10,Si > -1.10,Fe ka > -1.49,Ca ka <= 1.96
4,Fe ka > -0.89,Ca ka <= 1.96,Ca ka <= 1.96,K > -2.69
...,...,...,...,...
100,background4 <= -0.17,Ni > 0.17,NaN,background3 <= -0.17
101,Class_A,Class_A,NaN,background1 <= 0.15
102,Class_B,Class_B,NaN,Compton scattering <= 0.14
103,NaN,NaN,NaN,Class_A
104,NaN,NaN,NaN,Class_B

In [7]:
# Somar LRCs de predicados equivalentes entre diferentes seeds
lrc_combined_list = []

for seed in random_seeds:
    lrc_df = lrc_cov_by_seed[seed].copy()
    lrc_combined_list.append(lrc_df) # o append adiciona o dataframe ao final da lista

# Concatenar todos os dataframes
lrc_all_seeds = pd.concat(lrc_combined_list, ignore_index=True) 

# Agrupar por predicado (Node) e somar as LRCs, mantendo Zone, Threshold e Operator
lrc_summed_df = lrc_all_seeds.groupby('Node').agg({ # o .agg pode ser usado para aplicar múltiplas funções de agregação
    'Local_Reaching_Centrality': 'mean', # sum = somando as LRCs, poderia ser média ou outro agregado
    'Zone': 'first',
    'Threshold': 'first',
    'Operator': 'first'
}).reset_index()

# Ordenar pelo valor de LRC somado (maior para menor)
lrc_summed_df = lrc_summed_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
# vamoss pegar so os valore sunicos de lrc_summed_df baseado na zona espectral
lrc_summed_unique_df_cov = lrc_summed_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
lrc_summed_unique_df_cov = lrc_summed_unique_df_cov.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
lrc_summed_unique_df_cov

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator
0,Fe ka > -1.26,9.594434,Fe ka,-1.26,>
1,Ca ka <= 1.96,5.105012,Ca ka,1.96,<=
2,Si > -1.10,5.034995,Si,-1.10,>
3,K > -2.69,4.487589,K,-2.69,>
4,Ti ka > -0.34,1.973659,Ti ka,-0.34,>
5,Fe kb > -0.31,1.450876,Fe kb,-0.31,>
6,Ca kb <= 0.69,1.187452,Ca kb,0.69,<=
7,Rh L + Ar > -0.78,1.110507,Rh L + Ar,-0.78,>
8,P > 0.26,0.576975,P,0.26,>
9,Al > -0.33,0.536210,Al,-0.33,>
10,Ti kb > -0.16,0.471403,Ti kb,-0.16,>
11,Compton scattering > -0.17,0.421110,Compton scattering,-0.17,>
12,sum Fe > 0.13,0.377662,sum Fe,0.13,>
13,Rayleight scattering > -0.14,0.336925,Rayleight scattering,-0.14,>
14,Mn <= 0.47,0.323366,Mn,0.47,<=
15,S <= 0.29,0.316506,S,0.29,<=
16,background4 > -0.17,0.293278,background4,-0.17,>
17,background3 > 0.17,0.266790,background3,0.17,>
18,background2 <= 0.16,0.257149,background2,0.16,<=
19,Ni <= 0.26,0.244952,Ni,0.26,<=
20,background1 > -0.14,0.239787,background1,-0.14,>
21,Class_B,0.000000,None,None,None

# **Perturbation**

In [8]:
import explaining as exp

# LISTA DE SEMENTES A TESTAR
random_seeds = [0, 1, 2, 3]

all_results_pert = {}
training_samples = len(Xcalclass)

# LOOP: PROCESSAR CADA SEMENTE
y_predicted_numeric = plsda_results[5].iloc[:, -1] # predições numéricas do modelo

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando semente: {seed}")
    print(f"{'='*70}\n")
    # Bagging
    bags_result_seed = exp.bagging_predicates(
        zone_sums_df=zone_sums_df,
        y_predicted_numeric=y_predicted_numeric,
        predicates_df=predicates_quantiles[0],
        n_bags=10,
        #n_predicates_per_bag=40,
        n_samples_per_bag=int(training_samples*0.8), # 80 % da base para amostrar (convertido para int)
        min_samples_per_predicate=int(training_samples*0.2), # 20 % da base para limitar (convertido para int)
        replace=False,
        sample_bagging=True,
        predicate_bagging=False,
        random_seed=seed
    )
    # Inserir classe prevista
    for bag_name, pred_dict in bags_result_seed.items(): # iterando sobre cada bag
        for pred_rule, df_info in pred_dict.items():
            df_info['Class_Predicted'] = np.where(df_info['Predicted_Y'] >= 0.5, 'A', 'B') # binarizando com threshold 0.5, A = eut, B = dist

    pert_results_seed = exp.calculate_predicate_perturbation(
        estimator=pls_model,
        Xcalclass_prep=Xcalclass_prep,
        folds_struct=bags_result_seed,
        predicates_df=predicates_quantiles[0],
        spectral_cuts=spectral_cuts,
        #perturbation_value=0,
        perturbation_mode='mean', # valores entre 'mean' ou 'min'
        stats_source='full', # full indica usar todas as amostras para calcular estatísticas enquanto que 'fold' usa apenas as amostras do fold atual
        metric='mean_abs_diff',   # Média com sinal (pode ser negativo)
        verbose=True
    )

    # Remove todos os valores iguais a zero de todos os bags em perm_results[bag]["Permutation"] e salva como perm_results_thresholded
    # pert_results_seed_thresholded = {}
    # for bag, df in perm_results_seed.items():
    #     # Verifica se é um DataFrame e se a coluna 'Permutation' existe
    #     if isinstance(df, pd.DataFrame) and 'Permutation' in df.columns:
    #         filtered_df = df[df['Permutation'] > 0].copy()
    #         pert_results_seed_thresholded[bag] = filtered_df
    #     else:
    #         # Se não for DataFrame esperado, apenas copia
    #         pert_results_seed_thresholded[bag] = df

    # Salvar no dicionário principal
    all_results_pert[seed] = {
        'bags_result': bags_result_seed,
        'pert_results_dict': pert_results_seed
    }

# CONSTRUÇÃO DE GRAFOS PARA MÚLTIPLAS SEMENTES (LOOP EXTERNO)
# Dicionário para armazenar grafos
graphs_pert_by_seed = {}

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando Grafo - Semente: {seed}")
    print(f"{'='*70}\n")
    # Construir grafo para esta semente
    DG = exp.build_predicate_graphv2(
        bags_result=all_results_pert[seed]['bags_result'],
        predicate_ranking_dict=all_results_pert[seed]['pert_results_dict'],
        metric_column='Perturbation',  # ou 'Covariance' se mudar a métrica
        random_state=seed,
        show_details=True
    )
    # Armazenar grafo
    graphs_pert_by_seed[seed] = DG  

# Calcular LRC usando a função pronta do explaining.py
lrc_pert_by_seed = {}
for seed in random_seeds:
    DG = graphs_pert_by_seed[seed]
    lrc_pert_df_seed = exp.calculate_lrc_single_graph(DG, predicates_quantiles[0])
    lrc_pert_df_seed['Seed'] = seed  # Adicionar coluna com a semente
    lrc_pert_by_seed[seed] = lrc_pert_df_seed

# junando todas as colunas 'Node' de lrc_by_seed em um único dataframe
lrc_pert_all_seeds_df = pd.DataFrame()
for seed in random_seeds:
    lrc_pert_df_seed = lrc_pert_by_seed[seed].rename(columns={'Node': f'Predicate_pert_Seed_{seed}'})
    lrc_pert_all_seeds_df = pd.concat([lrc_pert_all_seeds_df, lrc_pert_df_seed[[f'Predicate_pert_Seed_{seed}']]], axis=1)

# vamos filtrar lrc_by_seed em cada semente para manter apenas as zonas espectrais únicas com maior LRC em um mesmo dataframe
lrc_pert_unique_by_seed = {}
for seed, lrc_df in lrc_pert_by_seed.items():
    lrc_pert_unique_df = lrc_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
    lrc_pert_unique_df = lrc_pert_unique_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
    lrc_pert_unique_by_seed[seed] = lrc_pert_unique_df

lrc_pert_all_seeds_df # exibindo o dataframe consolidado com predicados de todas as sementes

======================================================================
Processando semente: 0
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
======================================================================
PERTURBATION IMPORTANCE PARA PREDICADOS
======================================================================
Tipo de tarefa (aim): regression
Modo de perturbação: mean
Fonte das estatísticas: full
Métrica: mean_abs_diff
Total de folds: 10


[Bag_1] Processando 126 predicados...
  Predicado: Al > -0.33 (n=86)
    Zona: 12 colunas
    Importance: 0.000351
  Predicado: Al <= -0.17 (n=44)
    Zona: 12 colunas
    Importance: 0.000434
  Predicado: Al > -0.17 (n=64)
    Zona: 12 colunas
    Importance: 0.000368
  Predicado: Al <= 0.16 (n=65)
    Zona: 12 colunas
    Importance: 0.000347
  Predicado: Al > 0.16 (n=43)
    Zona: 12 colunas
    Importance: 0.000466
  Predicado: Al <= 0.34 (n=87)
    Zona: 12 colunas
    Importance: 0.000341
  Predicado: Si > -1.10 (n=84)
    Zona: 12 colunas
    Importance: 0.200689
  Predicado: Si <= -0.73 (n=45)
    Zona: 12 colunas
    Importance: 0.200304
  Predicado: Si > -0.73 (n=63)
    Zona: 12 colunas
    Importance: 0.213243
  Predicado: Si <= -0.34 (n=65)
    Zona: 12 colunas
    Importance: 0.168748
  Predicado: Si > -0.34 (n=43)
    Zona: 12 colunas
    Importance: 0.266963
  Predicado: Si <= 1.59 (n=85)
    Zona: 12 colunas
    Importance: 0.162301
  Predicado: P > -0.58 (n=90)
    Zona: 16 colunas
    Importance: 0.004787
  Predicado: P <= -0.30 (n=44)
    Zona: 16 colunas
    Importance: 0.005451
  Predicado: P > -0.30 (n=64)
    Zona: 16 colunas
    Importance: 0.005178
  Predicado: P <= 0.26 (n=62)
    Zona: 16 colunas
    Importance: 0.004381
  Predicado: P > 0.26 (n=46)
    Zona: 16 colunas
    Importance: 0.006514
  Predicado: P <= 0.51 (n=84)
    Zona: 16 colunas
    Importance: 0.003948
  Predicado: S > -0.28 (n=86)
    Zona: 15 colunas
    Importance: 0.003595
  Predicado: S <= -0.18 (n=39)
    Zona: 15 colunas
    Importance: 0.004650
  Predicado: S > -0.18 (n=69)
    Zona: 15 colunas
    Importance: 0.003707
  Predicado: S <= 0.14 (n=62)
    Zona: 15 colunas
    Importance: 0.003352
  Predicado: S > 0.14 (n=46)
    Zona: 15 colunas
    Importance: 0.004986
  Predicado: S <= 0.29 (n=85)
    Zona: 15 colunas
    Importance: 0.003123
  Predicado: Rh L + Ar > -0.78 (n=91)
    Zona: 34 colunas
    Importance: 0.021975
  Predicado: Rh L + Ar <= -0.42 (n=36)
    Zona: 34 colunas
    Importance: 0.029009
  Predicado: Rh L + Ar > -0.42 (n=72)
    Zona: 34 colunas
    Importance: 0.022359
  Predicado: Rh L + Ar <= -0.13 (n=63)
    Zona: 34 colunas
    Importance: 0.019815
  Predicado: Rh L + Ar > -0.13 (n=45)
    Zona: 34 colunas
    Importance: 0.031241
  Predicado: Rh L + Ar <= 0.63 (n=89)
    Zona: 34 colunas
    Importance: 0.017157
  Predicado: K > -2.69 (n=87)
    Zona: 19 colunas
    Importance: 0.011051
  Predicado: K <= -0.94 (n=43)
    Zona: 19 colunas
    Importance: 0.015689
  Predicado: K > -0.94 (n=65)
    Zona: 19 colunas
    Importance: 0.011796
  Predicado: K <= 0.94 (n=66)
    Zona: 19 colunas
    Importance: 0.012641
  Predicado: K > 0.94 (n=42)
    Zona: 19 colunas
    Importance: 0.014454
  Predicado: K <= 2.49 (n=86)
    Zona: 19 colunas
    Importance: 0.011754
  Predicado: Ca ka > -2.11 (n=86)
    Zona: 21 colunas
    Importance: 0.140676
  Predicado: Ca ka <= -0.97 (n=45)
    Zona: 21 colunas
    Importance: 0.182087
  Predicado: Ca ka > -0.97 (n=63)
    Zona: 21 colunas
    Importance: 0.147588
  Predicado: Ca ka <= 0.86 (n=67)
    Zona: 21 colunas
    Importance: 0.137806
  Predicado: Ca ka > 0.86 (n=41)
    Zona: 21 colunas
    Importance: 0.201439
  Predicado: Ca ka <= 1.96 (n=87)
    Zona: 21 colunas
    Importance: 0.130717
  Predicado: Ca kb > -0.79 (n=87)
    Zona: 16 colunas
    Importance: 0.022594
  Predicado: Ca kb <= -0.30 (n=44)
    Zona: 16 colunas
    Importance: 0.030936
  Predicado: Ca kb > -0.30 (n=64)
    Zona: 16 colunas
    Importance: 0.023146
  Predicado: Ca kb <= 0.31 (n=67)
    Zona: 16 colunas
    Importance: 0.022295
  Predicado: Ca kb > 0.31 (n=41)
    Zona: 16 colunas
    Importance: 0.032897
  Predicado: Ca kb <= 0.69 (n=86)
    Zona: 16 colunas
    Importance: 0.021112
  Predicado: background1 > -0.14 (n=91)
    Zona: 12 colunas
    Importance: 0.000111
  Predicado: background1 <= -0.09 (n=44)
    Zona: 12 colunas
    Importance: 0.000143
  Predicado: background1 > -0.09 (n=64)
    Zona: 12 colunas
    Importance: 0.000106
  Predicado: background1 <= 0.10 (n=68)
    Zona: 12 colunas
    Importance: 0.000111
  Predicado: background1 > 0.10 (n=40)
    Zona: 12 colunas
    Importance: 0.000138
  Predicado: background1 <= 0.15 (n=89)
    Zona: 12 colunas
    Importance: 0.000113
  Predicado: Ti ka > -0.40 (n=86)
    Zona: 15 colunas
    Importance: 0.004455
  Predicado: Ti ka <= -0.34 (n=43)
    Zona: 15 colunas
    Importance: 0.004148
  Predicado: Ti ka > -0.34 (n=65)
    Zona: 15 colunas
    Importance: 0.004752
  Predicado: Ti ka <= -0.26 (n=65)
    Zona: 15 colunas
    Importance: 0.003644
  Predicado: Ti ka > -0.26 (n=43)
    Zona: 15 colunas
    Importance: 0.005823
  Predicado: Ti ka <= 0.27 (n=87)
    Zona: 15 colunas
    Importance: 0.003075
  Predicado: Ti kb > -0.16 (n=86)
    Zona: 22 colunas
    Importance: 0.000904
  Predicado: Ti kb <= -0.13 (n=43)
    Zona: 22 colunas
    Importance: 0.001212
  Predicado: Ti kb > -0.13 (n=65)
    Zona: 22 colunas
    Importance: 0.000950
  Predicado: Ti kb <= 0.11 (n=66)
    Zona: 22 colunas
    Importance: 0.000937
  Predicado: Ti kb > 0.11 (n=42)
    Zona: 22 colunas
    Importance: 0.001238
  Predicado: Ti kb <= 0.18 (n=89)
    Zona: 22 colunas
    Importance: 0.000844
  Predicado: background2 > -0.15 (n=88)
    Zona: 33 colunas
    Importance: 0.000464
  Predicado: background2 <= -0.11 (n=43)
    Zona: 33 colunas
    Importance: 0.000704
  Predicado: background2 > -0.11 (n=65)
    Zona: 33 colunas
    Importance: 0.000502
  Predicado: background2 <= 0.12 (n=66)
    Zona: 33 colunas
    Importance: 0.000524
  Predicado: background2 > 0.12 (n=42)
    Zona: 33 colunas
    Importance: 0.000675
  Predicado: background2 <= 0.16 (n=91)
    Zona: 33 colunas
    Importance: 0.000500
  Predicado: Mn > -0.52 (n=90)
    Zona: 20 colunas
    Importance: 0.004100
  Predicado: Mn <= -0.21 (n=43)
    Zona: 20 colunas
    Importance: 0.005869
  Predicado: Mn > -0.21 (n=65)
    Zona: 20 colunas
    Importance: 0.004201
  Predicado: Mn <= 0.18 (n=65)
    Zona: 20 colunas
    Importance: 0.004286
  Predicado: Mn > 0.18 (n=43)
    Zona: 20 colunas
    Importance: 0.005742
  Predicado: Mn <= 0.47 (n=89)
    Zona: 20 colunas
    Importance: 0.003942
  Predicado: Fe ka > -1.49 (n=85)
    Zona: 34 colunas
    Importance: 0.014042
  Predicado: Fe ka <= -1.26 (n=42)
    Zona: 34 colunas
    Importance: 0.012732
  Predicado: Fe ka > -1.26 (n=66)
    Zona: 34 colunas
    Importance: 0.014977
  Predicado: Fe ka <= -0.89 (n=63)
    Zona: 34 colunas
    Importance: 0.011411
  Predicado: Fe ka > -0.89 (n=45)
    Zona: 34 colunas
    Importance: 0.017874
  Predicado: Fe ka <= 0.50 (n=87)
    Zona: 34 colunas
    Importance: 0.009451
  Predicado: Fe kb > -0.40 (n=88)
    Zona: 23 colunas
    Importance: 0.000233
  Predicado: Fe kb <= -0.31 (n=41)
    Zona: 23 colunas
    Importance: 0.000230
  Predicado: Fe kb > -0.31 (n=67)
    Zona: 23 colunas
    Importance: 0.000242
  Predicado: Fe kb <= -0.23 (n=67)
    Zona: 23 colunas
    Importance: 0.000199
  Predicado: Fe kb > -0.23 (n=41)
    Zona: 23 colunas
    Importance: 0.000301
  Predicado: Fe kb <= 0.29 (n=87)
    Zona: 23 colunas
    Importance: 0.000179
  Predicado: Ni > -0.26 (n=88)
    Zona: 25 colunas
    Importance: 0.001404
  Predicado: Ni <= -0.19 (n=44)
    Zona: 25 colunas
    Importance: 0.001661
  Predicado: Ni > -0.19 (n=64)
    Zona: 25 colunas
    Importance: 0.001419
  Predicado: Ni <= 0.17 (n=69)
    Zona: 25 colunas
    Importance: 0.001451
  Predicado: Ni > 0.17 (n=39)
    Zona: 25 colunas
    Importance: 0.001635
  Predicado: Ni <= 0.26 (n=92)
    Zona: 25 colunas
    Importance: 0.001453
  Predicado: background3 > -0.24 (n=88)
    Zona: 271 colunas
    Importance: 0.001715
  Predicado: background3 <= -0.17 (n=45)
    Zona: 271 colunas
    Importance: 0.002400
  Predicado: background3 > -0.17 (n=63)
    Zona: 271 colunas
    Importance: 0.001840
  Predicado: background3 <= 0.17 (n=68)
    Zona: 271 colunas
    Importance: 0.001790
  Predicado: background3 > 0.17 (n=40)
    Zona: 271 colunas
    Importance: 0.002556
  Predicado: background3 <= 0.28 (n=88)
    Zona: 271 colunas
    Importance: 0.001692
  Predicado: sum Fe > -0.24 (n=89)
    Zona: 27 colunas
    Importance: 0.000798
  Predicado: sum Fe <= -0.15 (n=45)
    Zona: 27 colunas
    Importance: 0.001058
  Predicado: sum Fe > -0.15 (n=63)
    Zona: 27 colunas
    Importance: 0.000859
  Predicado: sum Fe <= 0.13 (n=70)
    Zona: 27 colunas
    Importance: 0.000772
  Predicado: sum Fe > 0.13 (n=38)
    Zona: 27 colunas
    Importance: 0.001255
  Predicado: sum Fe <= 0.24 (n=88)
    Zona: 27 colunas
    Importance: 0.000687
  Predicado: background4 > -0.23 (n=85)
    Zona: 219 colunas
    Importance: 0.002245
  Predicado: background4 <= -0.17 (n=44)
    Zona: 219 colunas
    Importance: 0.003312
  Predicado: background4 > -0.17 (n=64)
    Zona: 219 colunas
    Importance: 0.002458
  Predicado: background4 <= 0.16 (n=68)
    Zona: 219 colunas
    Importance: 0.002363
  Predicado: background4 > 0.16 (n=40)
    Zona: 219 colunas
    Importance: 0.003558
  Predicado: background4 <= 0.28 (n=90)
    Zona: 219 colunas
    Importance: 0.002191
  Predicado: Compton scattering > -0.23 (n=87)
    Zona: 85 colunas
    Importance: 0.001883
  Predicado: Compton scattering <= -0.17 (n=44)
    Zona: 85 colunas
    Importance: 0.002374
  Predicado: Compton scattering > -0.17 (n=64)
    Zona: 85 colunas
    Importance: 0.001998
  Predicado: Compton scattering <= 0.14 (n=68)
    Zona: 85 colunas
    Importance: 0.001805
  Predicado: Compton scattering > 0.14 (n=40)
    Zona: 85 colunas
    Importance: 0.002740
  Predicado: Compton scattering <= 0.23 (n=87)
    Zona: 85 colunas
    Importance: 0.001737
  Predicado: Rayleight scattering > -0.19 (n=84)
    Zona: 55 colunas
    Importance: 0.000445
  Predicado: Rayleight scattering <= -0.14 (n=41)
    Zona: 55 colunas
    Importance: 0.000581
  Predicado: Rayleight scattering > -0.14 (n=67)
    Zona: 55 colunas
    Importance: 0.000469
  Predicado: Rayleight scattering <= -0.02 (n=68)
    Zona: 55 colunas
    Importance: 0.000435
  Predicado: Rayleight scattering > -0.02 (n=40)
    Zona: 55 colunas
    Importance: 0.000642
  Predicado: Rayleight scattering <= 0.20 (n=89)
    Zona: 55 colunas
    Importance: 0.000397

[Bag_2] Processando 126 predicados...
  Predicado: Al > -0.33 (n=83)
    Zona: 12 colunas
    Importance: 0.000353
  Predicado: Al <= -0.17 (n=46)
    Zona: 12 colunas
    Importance: 0.000442
  Predicado: Al > -0.17 (n=62)
    Zona: 12 colunas
    Importance: 0.000371
  Predicado: Al <= 0.16 (n=63)
    Zona: 12 colunas
    Importance: 0.000357
  Predicado: Al > 0.16 (n=45)
    Zona: 12 colunas
    Importance: 0.000463
  Predicado: Al <= 0.34 (n=86)
    Zona: 12 colunas
    Importance: 0.000349
  Predicado: Si > -1.10 (n=84)
    Zona: 12 colunas
    Importance: 0.195341
  Predicado: Si <= -0.73 (n=47)
    Zona: 12 colunas
    Importance: 0.199555
  Predicado: Si > -0.73 (n=61)
    Zona: 12 colunas
    Importance: 0.207212
  Predicado: Si <= -0.34 (n=68)
    Zona: 12 colunas
    Importance: 0.168476
  Predicado: Si > -0.34 (n=40)
    Zona: 12 colunas
    Importance: 0.264065
  Predicado: Si <= 1.59 (n=87)
    Zona: 12 colunas
    Importance: 0.157614
  Predicado: P > -0.58 (n=87)
    Zona: 16 colunas
    Importance: 0.004621
  Predicado: P <= -0.30 (n=45)
    Zona: 16 colunas
    Importance: 0.005923
  Predicado: P > -0.30 (n=63)
    Zona: 16 colunas
    Importance: 0.004837
  Predicado: P <= 0.26 (n=66)
    Zona: 16 colunas
    Importance: 0.004540
  Predicado: P > 0.26 (n=42)
    Zona: 16 colunas
    Importance: 0.006467
  Predicado: P <= 0.51 (n=87)
    Zona: 16 colunas
    Importance: 0.004070
  Predicado: S > -0.28 (n=87)
    Zona: 15 colunas
    Importance: 0.003350
  Predicado: S <= -0.18 (n=43)
    Zona: 15 colunas
    Importance: 0.004253
  Predicado: S > -0.18 (n=65)
    Zona: 15 colunas
    Importance: 0.003502
  Predicado: S <= 0.14 (n=66)
    Zona: 15 colunas
    Importance: 0.003121
  Predicado: S > 0.14 (n=42)
    Zona: 15 colunas
    Importance: 0.004870
  Predicado: S <= 0.29 (n=87)
    Zona: 15 colunas
    Importance: 0.002958
  Predicado: Rh L + Ar > -0.78 (n=88)
    Zona: 34 colunas
    Importance: 0.020832
  Predicado: Rh L + Ar <= -0.42 (n=42)
    Zona: 34 colunas
    Importance: 0.027799
  Predicado: Rh L + Ar > -0.42 (n=66)
    Zona: 34 colunas
    Importance: 0.021039
  Predicado: Rh L + Ar <= -0.13 (n=66)
    Zona: 34 colunas
    Importance: 0.020577
  Predicado: Rh L + Ar > -0.13 (n=42)
    Zona: 34 colunas
    Importance: 0.028525
  Predicado: Rh L + Ar <= 0.63 (n=90)
    Zona: 34 colunas
    Importance: 0.017976
  Predicado: K > -2.69 (n=84)
    Zona: 19 colunas
    Importance: 0.011538
  Predicado: K <= -0.94 (n=45)
    Zona: 19 colunas
    Importance: 0.016681
  Predicado: K > -0.94 (n=63)
    Zona: 19 colunas
    Importance: 0.012077
  Predicado: K <= 0.94 (n=65)
    Zona: 19 colunas
    Importance: 0.013625
  Predicado: K > 0.94 (n=43)
    Zona: 19 colunas
    Importance: 0.014555
  Predicado: K <= 2.49 (n=87)
    Zona: 19 colunas
    Importance: 0.012086
  Predicado: Ca ka > -2.11 (n=89)
    Zona: 21 colunas
    Importance: 0.133754
  Predicado: Ca ka <= -0.97 (n=40)
    Zona: 21 colunas
    Importance: 0.185448
  Predicado: Ca ka > -0.97 (n=68)
    Zona: 21 colunas
    Importance: 0.135642
  Predicado: Ca ka <= 0.86 (n=66)
    Zona: 21 colunas
    Importance: 0.131924
  Predicado: Ca ka > 0.86 (n=42)
    Zona: 21 colunas
    Importance: 0.188919
  Predicado: Ca ka <= 1.96 (n=87)
    Zona: 21 colunas
    Importance: 0.124730
  Predicado: Ca kb > -0.79 (n=89)
    Zona: 16 colunas
    Importance: 0.021933
  Predicado: Ca kb <= -0.30 (n=41)
    Zona: 16 colunas
    Importance: 0.031014
  Predicado: Ca kb > -0.30 (n=67)
    Zona: 16 colunas
    Importance: 0.022070
  Predicado: Ca kb <= 0.31 (n=67)
    Zona: 16 colunas
    Importance: 0.021350
  Predicado: Ca kb > 0.31 (n=41)
    Zona: 16 colunas
    Importance: 0.032191
  Predicado: Ca kb <= 0.69 (n=86)
    Zona: 16 colunas
    Importance: 0.020448
  Predicado: background1 > -0.14 (n=90)
    Zona: 12 colunas
    Importance: 0.000123
  Predicado: background1 <= -0.09 (n=43)
    Zona: 12 colunas
    Importance: 0.000147
  Predicado: background1 > -0.09 (n=65)
    Zona: 12 colunas
    Importance: 0.000121
  Predicado: background1 <= 0.10 (n=62)
    Zona: 12 colunas
    Importance: 0.000120
  Predicado: background1 > 0.10 (n=46)
    Zona: 12 colunas
    Importance: 0.000146
  Predicado: background1 <= 0.15 (n=85)
    Zona: 12 colunas
    Importance: 0.000120
  Predicado: Ti ka > -0.40 (n=83)
    Zona: 15 colunas
    Importance: 0.004699
  Predicado: Ti ka <= -0.34 (n=43)
    Zona: 15 colunas
    Importance: 0.004210
  Predicado: Ti ka > -0.34 (n=65)
    Zona: 15 colunas
    Importance: 0.005038
  Predicado: Ti ka <= -0.26 (n=70)
    Zona: 15 colunas
    Importance: 0.003618
  Predicado: Ti ka > -0.26 (n=38)
    Zona: 15 colunas
    Importance: 0.006715
  Predicado: Ti ka <= 0.27 (n=88)
    Zona: 15 colunas
    Importance: 0.003153
  Predicado: Ti kb > -0.16 (n=82)
    Zona: 22 colunas
    Importance: 0.000942
  Predicado: Ti kb <= -0.13 (n=45)
    Zona: 22 colunas
    Importance: 0.001273
  Predicado: Ti kb > -0.13 (n=63)
    Zona: 22 colunas
    Importance: 0.001003
  Predicado: Ti kb <= 0.11 (n=63)
    Zona: 22 colunas
    Importance: 0.001034
  Predicado: Ti kb > 0.11 (n=45)
    Zona: 22 colunas
    Importance: 0.001229
  Predicado: Ti kb <= 0.18 (n=85)
    Zona: 22 colunas
    Importance: 0.000900
  Predicado: background2 > -0.15 (n=87)
    Zona: 33 colunas
    Importance: 0.000534
  Predicado: background2 <= -0.11 (n=41)
    Zona: 33 colunas
    Importance: 0.000783
  Predicado: background2 > -0.11 (n=67)
    Zona: 33 colunas
    Importance: 0.000575
  Predicado: background2 <= 0.12 (n=62)
    Zona: 33 colunas
    Importance: 0.000586
  Predicado: background2 > 0.12 (n=46)
    Zona: 33 colunas
    Importance: 0.000744
  Predicado: background2 <= 0.16 (n=83)
    Zona: 33 colunas
    Importance: 0.000549
  Predicado: Mn > -0.52 (n=87)
    Zona: 20 colunas
    Importance: 0.004573
  Predicado: Mn <= -0.21 (n=41)
    Zona: 20 colunas
    Importance: 0.006641
  Predicado: Mn > -0.21 (n=67)
    Zona: 20 colunas
    Importance: 0.004680
  Predicado: Mn <= 0.18 (n=63)
    Zona: 20 colunas
    Importance: 0.004715
  Predicado: Mn > 0.18 (n=45)
    Zona: 20 colunas
    Importance: 0.006418
  Predicado: Mn <= 0.47 (n=86)
    Zona: 20 colunas
    Importance: 0.004272
  Predicado: Fe ka > -1.49 (n=84)
    Zona: 34 colunas
    Importance: 0.014815
  Predicado: Fe ka <= -1.26 (n=45)
    Zona: 34 colunas
    Importance: 0.012686
  Predicado: Fe ka > -1.26 (n=63)
    Zona: 34 colunas
    Importance: 0.016208
  Predicado: Fe ka <= -0.89 (n=66)
    Zona: 34 colunas
    Importance: 0.011461
  Predicado: Fe ka > -0.89 (n=42)
    Zona: 34 colunas
    Importance: 0.019894
  Predicado: Fe ka <= 0.50 (n=89)
    Zona: 34 colunas
    Importance: 0.009655
  Predicado: Fe kb > -0.40 (n=85)
    Zona: 23 colunas
    Importance: 0.000240
  Predicado: Fe kb <= -0.31 (n=44)
    Zona: 23 colunas
    Importance: 0.000221
  Predicado: Fe kb > -0.31 (n=64)
    Zona: 23 colunas
    Importance: 0.000258
  Predicado: Fe kb <= -0.23 (n=67)
    Zona: 23 colunas
    Importance: 0.000198
  Predicado: Fe kb > -0.23 (n=41)
    Zona: 23 colunas
    Importance: 0.000317
  Predicado: Fe kb <= 0.29 (n=85)
    Zona: 23 colunas
    Importance: 0.000176
  Predicado: Ni > -0.26 (n=89)
    Zona: 25 colunas
    Importance: 0.001422
  Predicado: Ni <= -0.19 (n=42)
    Zona: 25 colunas
    Importance: 0.001684
  Predicado: Ni > -0.19 (n=66)
    Zona: 25 colunas
    Importance: 0.001428
  Predicado: Ni <= 0.17 (n=62)
    Zona: 25 colunas
    Importance: 0.001450
  Predicado: Ni > 0.17 (n=46)
    Zona: 25 colunas
    Importance: 0.001632
  Predicado: Ni <= 0.26 (n=87)
    Zona: 25 colunas
    Importance: 0.001447
  Predicado: background3 > -0.24 (n=87)
    Zona: 271 colunas
    Importance: 0.001834
  Predicado: background3 <= -0.17 (n=43)
    Zona: 271 colunas
    Importance: 0.002546
  Predicado: background3 > -0.17 (n=65)
    Zona: 271 colunas
    Importance: 0.001980
  Predicado: background3 <= 0.17 (n=65)
    Zona: 271 colunas
    Importance: 0.001899
  Predicado: background3 > 0.17 (n=43)
    Zona: 271 colunas
    Importance: 0.002669
  Predicado: background3 <= 0.28 (n=88)
    Zona: 271 colunas
    Importance: 0.001790
  Predicado: sum Fe > -0.24 (n=87)
    Zona: 27 colunas
    Importance: 0.000778
  Predicado: sum Fe <= -0.15 (n=41)
    Zona: 27 colunas
    Importance: 0.001128

,Predicate_pert_Seed_0,Predicate_pert_Seed_1,Predicate_pert_Seed_2,Predicate_pert_Seed_3
0,Si > -0.34,Si > -0.34,Si > -0.34,Si > -0.34
1,Si > -0.73,Si <= -0.73,Si > -0.73,Si > -0.73
2,Si > -1.10,Si > -0.73,Si <= -0.73,Ca ka > 0.86
3,Si <= -0.73,Si > -1.10,Si > -1.10,Ca ka <= -0.97
4,Ca ka <= -0.97,Ca ka <= -0.97,Ca ka > 0.86,Si > -1.10
...,...,...,...,...
127,Class_B,Class_A,background1 <= 0.10,background1 <= 0.10
128,NaN,Class_B,background1 > -0.14,Class_A
129,NaN,NaN,background1 > -0.09,Class_B
130,NaN,NaN,Class_A,NaN
131,NaN,NaN,Class_B,NaN

In [9]:
all_results_pert[0]['pert_results_dict']['Bag_9']

                Predicate  Perturbation
0              Si > -0.34      0.253126
1              Si > -0.73      0.200833
2             Si <= -0.73      0.196243
3              Si > -1.10      0.191944
4            Ca ka > 0.86      0.191478
..                    ...           ...
121  background1 <= -0.09      0.000154
122   background1 > -0.14      0.000125
123   background1 <= 0.15      0.000123
124   background1 > -0.09      0.000123
125   background1 <= 0.10      0.000119

[126 rows x 2 columns]

In [10]:
# Somar LRCs de predicados equivalentes entre diferentes seeds
lrc_combined_list = []

for seed in random_seeds:
    lrc_df = lrc_pert_by_seed[seed].copy()
    lrc_combined_list.append(lrc_df) # o append adiciona o dataframe ao final da lista

# Concatenar todos os dataframes
lrc_all_seeds = pd.concat(lrc_combined_list, ignore_index=True) 

# Agrupar por predicado (Node) e somar as LRCs, mantendo Zone, Threshold e Operator
lrc_summed_df = lrc_all_seeds.groupby('Node').agg({ # o .agg pode ser usado para aplicar múltiplas funções de agregação
    'Local_Reaching_Centrality': 'mean', # sum = somando as LRCs, poderia ser média ou outro agregado
    'Zone': 'first',
    'Threshold': 'first',
    'Operator': 'first'
}).reset_index()

# Ordenar pelo valor de LRC somado (maior para menor)
lrc_summed_df = lrc_summed_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
# vamoss pegar so os valore sunicos de lrc_summed_df baseado na zona espectral
lrc_summed_unique_df_pert = lrc_summed_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
lrc_summed_unique_df_pert = lrc_summed_unique_df_pert.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
lrc_summed_unique_df_pert

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator
0,Si > -0.34,7.794134,Si,-0.34,>
1,Ca ka <= -0.97,5.784132,Ca ka,-0.97,<=
2,Ca kb <= -0.30,0.869136,Ca kb,-0.30,<=
3,Rh L + Ar > -0.13,0.840131,Rh L + Ar,-0.13,>
4,Fe ka > -0.89,0.519282,Fe ka,-0.89,>
5,K <= -0.94,0.451526,K,-0.94,<=
6,Ti ka > -0.26,0.154846,Ti ka,-0.26,>
7,P > 0.26,0.139996,P,0.26,>
8,Mn > 0.18,0.136698,Mn,0.18,>
9,S > 0.14,0.103270,S,0.14,>
10,background4 <= -0.23,0.097031,background4,-0.23,<=
11,Compton scattering > 0.14,0.051699,Compton scattering,0.14,>
12,background3 > 0.17,0.045652,background3,0.17,>
13,Ni > 0.17,0.029290,Ni,0.17,>
14,Ti kb <= -0.16,0.027400,Ti kb,-0.16,<=
15,sum Fe > 0.13,0.017785,sum Fe,0.13,>
16,background2 <= -0.11,0.009799,background2,-0.11,<=
17,Rayleight scattering > -0.02,0.007295,Rayleight scattering,-0.02,>
18,Al > 0.16,0.004986,Al,0.16,>
19,Fe kb > -0.23,0.002982,Fe kb,-0.23,>
20,background1 <= -0.09,0.000518,background1,-0.09,<=
21,Class_B,0.000000,None,None,None

In [11]:
shap_unique_df = pd.read_csv('shap_forage.csv', sep=';') # loading previously saved shap_unique_df

In [12]:
import numpy as np

max_len = max(
    len(vip_scores_unique_df['Zone']),
    len(reg_vet_unique_df['Zone']),
    len(shap_unique_df['Zone']),
    len(lrc_summed_unique_df_pert['Zone']),
    len(lrc_summed_unique_df_cov['Zone'])
)

def pad_list(lst, length):
    return list(lst) + [None] * (length - len(lst))

features_importance = pd.DataFrame({
    'Vip': pad_list(vip_scores_unique_df['Zone'], max_len),
    'Reg_coef': pad_list(reg_vet_unique_df['Zone'], max_len),
    'Shap': pad_list(shap_unique_df['Zone'], max_len),
    'LRC_perturbation' : pad_list(lrc_summed_unique_df_pert['Zone'], max_len),
    'LRC_covariance' : pad_list(lrc_summed_unique_df_cov['Zone'], max_len),
})

features_importance.to_csv('feature_importance.csv', index=False, sep=';')
features_importance

,Vip,Reg_coef,Shap,LRC_perturbation,LRC_covariance
0,Fe ka,Si,Si,Si,Fe ka
1,K,Ca ka,Ca ka,Ca ka,Ca ka
2,Si,Rh L + Ar,Rh L + Ar,Ca kb,Si
3,Ca ka,Ca kb,K,Rh L + Ar,K
4,Ca kb,P,Ca kb,Fe ka,Ti ka
5,Ti ka,K,Fe ka,K,Fe kb
6,Fe kb,S,background4,Ti ka,Ca kb
7,Rh L + Ar,Mn,background3,P,Rh L + Ar
8,P,Al,sum Fe,Mn,P
9,Al,Ni,Compton scattering,S,Al
10,Mn,Fe ka,Rayleight scattering,background4,Ti kb
11,S,Ti ka,S,Compton scattering,Compton scattering
12,Ti kb,Ti kb,Al,background3,sum Fe
13,sum Fe,background3,Ti kb,Ni,Rayleight scattering
14,Ni,Compton scattering,background2,Ti kb,Mn
15,Compton scattering,Fe kb,Ti ka,sum Fe,S
16,background3,background2,Mn,background2,background4
17,Rayleight scattering,sum Fe,P,Rayleight scattering,background3
18,background1,background4,background1,Al,background2
19,background4,background1,NaN,Fe kb,Ni
20,NaN,Rayleight scattering,Ni,background1,background1
21,background2,NaN,Fe kb,None,None

In [13]:
import rbo
rbo_comparison = pd.DataFrame(columns=['Method_1', 'Method_2', 'RBO_Score'])
methods = features_importance.columns.tolist()
for i in range(len(methods)):
    for j in range(i + 1, len(methods)):
        method_1 = methods[i]
        method_2 = methods[j]
        # Remove None values from the lists
        list_1 = [x for x in features_importance[method_1].tolist() if x is not None]
        list_2 = [x for x in features_importance[method_2].tolist() if x is not None]
        # Truncate both lists to the same length (minimum of both)
        min_len = min(len(list_1), len(list_2))
        list_1_trunc = list_1[:min_len]
        list_2_trunc = list_2[:min_len]
        rbo_score = rbo.RankingSimilarity(list_1_trunc, list_2_trunc).rbo(p=0.7, k=10)
        rbo_comparison = pd.concat([rbo_comparison, pd.DataFrame({
            'Method_1': [method_1],
            'Method_2': [method_2],
            'RBO_Score': [rbo_score]
        })], ignore_index=True)
rbo_comparison.sort_values(by='RBO_Score', ascending=False, inplace=True)
rbo_comparison.to_csv('rbo_rank.csv', index=False, sep=';')
rbo_comparison

C:\Users\Usuario\AppData\Local\Temp\ipykernel_12164\3097109587.py:16: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

           Method_1          Method_2  RBO_Score
4          Reg_coef              Shap   0.890129
5          Reg_coef  LRC_perturbation   0.877418
7              Shap  LRC_perturbation   0.860796
3               Vip    LRC_covariance   0.794943
8              Shap    LRC_covariance   0.419540
9  LRC_perturbation    LRC_covariance   0.408210
6          Reg_coef    LRC_covariance   0.364086
1               Vip              Shap   0.288350
2               Vip  LRC_perturbation   0.277020
0               Vip          Reg_coef   0.232896