## Loading data

In [1]:
# Importing the necessary libraries
import pandas as pd
import numpy as np
import kennard_stone as ks
pd.options.plotting.backend = 'plotly'  # setting plotly as the backend for pandas plotting

# Add parent directory to sys.path so local module 'synthetic' (one level up) can be imported
import sys
from pathlib import Path # for path manipulations
parent_dir = Path.cwd().parent.parent.resolve() # move two levels up from current working directory
if str(parent_dir) not in sys.path: # check to avoid duplicates
    sys.path.insert(0, str(parent_dir)) # insert at the start of sys.path to prioritize local modules

# Loading a soil spectral dataset based on X-ray fluorescence (XRF)
data_complete = pd.read_csv(f'{parent_dir}/XRF_databases/soil/plsda/soil.csv', sep=';') # local copy of Toledo 2022 dataset (os ... indica para omitir o caminho longo)
data = data_complete.loc[:, '1':'15']

In [2]:
# Split dataset by class and create calibration/prediction sets using Kennard-Stone (as in original pipeline)
data_A = data_complete[data_complete['Class'] == 'A'].reset_index(drop=True)
data_B = data_complete[data_complete['Class'] == 'B'].reset_index(drop=True)

# splitting the data into calibration and prediction sets by kennard-stone algorithm
XA_cal, XA_pred = ks.train_test_split(data_A.loc[:, '1':'15'], test_size=0.30)  # class A
XA_cal = XA_cal.reset_index(drop=True)
XA_pred = XA_pred.reset_index(drop=True)

XB_cal, XB_pred = ks.train_test_split(data_B.loc[:, '1':'15'], test_size=0.30)  # class B
XB_cal = XB_cal.reset_index(drop=True)
XB_pred = XB_pred.reset_index(drop=True)

Xcalclass = pd.concat([XA_cal, XB_cal], axis=0).reset_index(drop=True)  # concatenating both classes
Xpredclass = pd.concat([XA_pred, XB_pred], axis=0).reset_index(drop=True)
ycalclass = pd.Series(['A']*XA_cal.shape[0] + ['B']*XB_cal.shape[0])  # target for calibration set
ypredclass = pd.Series(['A']*XA_pred.shape[0] + ['B']*XB_pred.shape[0])  # target for prediction set

# preprocessings
import preprocessings as prepr  # preprocessing methods for XRF data

Xcalclass_prep, mean_calclass, mean_calclass_poisson  = prepr.poisson(Xcalclass, mc=True)
Xpredclass_prep = ((Xpredclass/np.sqrt(mean_calclass)) - mean_calclass_poisson)

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-01-26 07:07:05,202 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-01-26 07:07:05,217 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-01-26 07:07:05,246 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-01-26 07:07:05,263 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

In [3]:
# PLS-DA with optimized latent variables
from modeling import pls_optimized

plsda_results = pls_optimized(
    Xcalclass_prep, 
    ycalclass,
    LVmax=4,
    Xpred=Xpredclass_prep,
    ypred=ypredclass,
    aim='classification',
    cv=10
)

# Convenience references used later
pls_model = plsda_results[3]               # fitted PLS model
vip_scores_mat = plsda_results[4]          # VIP scores matrix (features × LV)
y_pred_cont = plsda_results[5].iloc[:, -1] # continuous predictions for Xcalclass (used for MI/Cov)

# plotando o vip scores rapidamente
vip_scores_mat.T.plot()

In [4]:
# calculando a covariancia entre cada variável espectral e a predição do modelo PLS-DA
cov_scores = []
y_pred = plsda_results[5].iloc[:,-1].values # using the continuous predictions from LV=3
for col in Xcalclass_prep.columns:
    x_values = Xcalclass_prep[col].values
    covariance = np.cov(x_values, y_pred)[0, 1] # covariance between x and y
    cov_scores.append(covariance)
cov_scores_df = pd.DataFrame(cov_scores, index=Xcalclass_prep.columns, columns=['Covariance'])
cov_scores_df = np.abs(cov_scores_df)
cov_scores_df.plot()

In [5]:
# establishing spectral cuts based on expert knowledge of XRF spectra
spectral_cuts = [
('background1', 1.0, 1.33),
('Al', 1.33, 1.63),
('Si', 1.63, 1.86),
('P', 1.86, 2.10),
('background2', 2.10, 2.19),
('S', 2.19, 2.44),
('background3', 2.44, 2.55),
('Rh L + Ar', 2.55, 3.10),
('background4', 3.10, 3.21),
('K', 3.21, 3.42),
('background5', 3.42, 3.53),
('Ca ka', 3.53, 3.84),
('Ca kb', 3.84, 4.14),
('background6', 4.14, 4.37),
('Ti ka', 4.37, 4.66),
('background7', 4.66, 4.75),
('Ti kb', 4.75, 5.12),
('Cr', 5.12, 5.77),
('Mn', 5.77, 6.02),
('background8', 6.02, 6.13),
('Fe ka', 6.13, 6.68),
('background9', 6.68, 6.80),
('Fe kb', 6.80, 7.30),
('background10', 7.30, 7.91),
('Cu', 7.91, 8.20),
('background11', 8.20, 10.69),
('Fe ka + Ti ka', 10.69, 11.14),
('background12', 11.14, 12.55),
('sum Fe' , 12.55, 13.1),
('background13', 13.1, 15.0)
]

import explaining as exp
spectral_zones_class = exp.extract_spectral_zones(Xcalclass_prep, spectral_cuts)
zone_sums_df = exp.aggregate_spectral_zones(spectral_zones_class, aggregator='extreme')
predicates_quantiles = exp.predicates_by_quantiles(zone_sums_df, [0.2, 0.4, 0.6, 0.8])
co_occurrence_matrix_df = predicates_quantiles[2]
predicate_info_dict = exp.create_predicate_info_dict(
    predicates_df=predicates_quantiles[0],
    predicate_indicator_df=predicates_quantiles[1],
    zone_aggregated_df=zone_sums_df,
    y_predicted_numeric=y_pred_cont
)

## VIP, Regression Coefficients e SHAP (como no original)

In [7]:
# VIP scores por energia
vip_scores_df = pd.DataFrame({
    'energy': vip_scores_mat.T.index,
    'VIP_Score': vip_scores_mat.T.iloc[:,0].values
})
vip_scores_df = vip_scores_df.sort_values(by='VIP_Score', ascending=False).reset_index(drop=True)
energy_to_zone_vip = {}
for zone_name, start, end in spectral_cuts:
    for e in vip_scores_df['energy']:
        ef = float(e)
        if start <= ef <= end:
            energy_to_zone_vip[e] = zone_name
vip_scores_df['Zone'] = vip_scores_df['energy'].map(energy_to_zone_vip)
vip_scores_unique_df = vip_scores_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
vip_scores_unique_df = vip_scores_unique_df.sort_values(by='VIP_Score', ascending=False).reset_index(drop=True)

# Coeficientes de regressão do PLS
reg_vet = pd.DataFrame(pls_model.coef_, columns=pls_model.feature_names_in_).T
reg_vet.insert(0, 'energy', reg_vet.index)
reg_vet = reg_vet.reset_index(drop=True)
reg_vet.columns = ['energy','Reg_coef']
reg_vet['Abs_Reg_coef'] = reg_vet['Reg_coef'].abs()
reg_vet = reg_vet.sort_values(by='Abs_Reg_coef', ascending=False).reset_index(drop=True)
energy_to_zone_reg = {}
for zone_name, start, end in spectral_cuts:
    for e in reg_vet['energy']:
        ef = float(e)
        if start <= ef <= end:
            energy_to_zone_reg[e] = zone_name
reg_vet['Zone'] = reg_vet['energy'].map(energy_to_zone_reg)
reg_vet_unique_df = reg_vet.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
reg_vet_unique_df = reg_vet_unique_df.sort_values(by='Abs_Reg_coef', ascending=False).reset_index(drop=True)
shap_unique_df = pd.read_csv('shap_soil.csv', sep=';') # loading previously saved shap_unique_df

# **bagging - covariance**

In [8]:
import explaining as exp

# LISTA DE SEMENTES A TESTAR
random_seeds = [0, 1, 2, 3]

all_results_cov = {}
training_samples = len(Xcalclass)

# LOOP: PROCESSAR CADA SEMENTE
y_predicted_numeric = plsda_results[5].iloc[:, -1] # predições numéricas do modelo

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando semente: {seed}")
    print(f"{'='*70}\n")
    # Bagging
    bags_result_seed = exp.bagging_predicates(
        zone_sums_df=zone_sums_df,
        y_predicted_numeric=y_predicted_numeric,
        predicates_df=predicates_quantiles[0],
        n_bags=10,
        #n_predicates_per_bag=40,
        n_samples_per_bag=int(training_samples*0.8), # 80 % da base para amostrar (convertido para int)
        min_samples_per_predicate=int(training_samples*0.2), # 20 % da base para limitar (convertido para int)
        replace=False,
        sample_bagging=True,
        predicate_bagging=False,
        random_seed=seed
    )
    # Inserir classe prevista
    for bag_name, pred_dict in bags_result_seed.items(): # iterando sobre cada bag
        for pred_rule, df_info in pred_dict.items():
            df_info['Class_Predicted'] = np.where(df_info['Predicted_Y'] >= 0.5, 'A', 'B') # binarizando com threshold 0.5, A = eut, B = dist
    # Calcular MI
    cov_results_dict_seed = exp.calculate_predicate_metrics(
        bags_result=bags_result_seed,
        metric='covariance', # covariance ou mutual_information
        threshold=0.01, # threshold para cortar predicados irrelevantes
        n_neighbors=5
    )
    # Salvar no dicionário principal
    all_results_cov[seed] = {
        'bags_result': bags_result_seed,
        'cov_results_dict': cov_results_dict_seed
    }

# CONSTRUÇÃO DE GRAFOS PARA MÚLTIPLAS SEMENTES (LOOP EXTERNO)
# Dicionário para armazenar grafos
graphs_by_seed = {}

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando Grafo - Semente: {seed}")
    print(f"{'='*70}\n")
    # Construir grafo para esta semente
    DG = exp.build_predicate_graphv2(
        bags_result=all_results_cov[seed]['bags_result'],
        predicate_ranking_dict=all_results_cov[seed]['cov_results_dict'],
        metric_column='Covariance',  # ou 'Covariance' se mudar a métrica
        random_state=seed,
        show_details=True
    )
    # Armazenar grafo
    graphs_by_seed[seed] = DG

# Calcular LRC usando a função pronta do explaining.py
lrc_cov_by_seed = {}
for seed in random_seeds:
    DG = graphs_by_seed[seed]
    lrc_cov_df_seed = exp.calculate_lrc_single_graph(DG, predicates_quantiles[0])
    lrc_cov_df_seed['Seed'] = seed  # Adicionar coluna com a semente
    lrc_cov_by_seed[seed] = lrc_cov_df_seed

# junando todas as colunas 'Node' de lrc_by_seed em um único dataframe
lrc_cov_all_seeds_df = pd.DataFrame()
for seed in random_seeds:
    lrc_cov_df_seed = lrc_cov_by_seed[seed].rename(columns={'Node': f'Predicate_Cov_Seed_{seed}'})
    lrc_cov_all_seeds_df = pd.concat([lrc_cov_all_seeds_df, lrc_cov_df_seed[[f'Predicate_Cov_Seed_{seed}']]], axis=1)

# vamos filtrar lrc_by_seed em cada semente para manter apenas as zonas espectrais únicas com maior LRC em um mesmo dataframe
lrc_cov_unique_by_seed = {}
for seed, lrc_df in lrc_cov_by_seed.items():
    lrc_cov_unique_df = lrc_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
    lrc_cov_unique_df = lrc_cov_unique_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
    lrc_cov_unique_by_seed[seed] = lrc_cov_unique_df

lrc_cov_all_seeds_df # exibindo o dataframe consolidado com predicados de todas as sementes

======================================================================
Processando semente: 0
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 183 | Descartados: 57
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 182 | Descartados: 58
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 181 | Descartados: 59
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 183 | Descartados: 57
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 183 | Descartados: 57
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 181 | Descartados: 59
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 180 | Descartados: 60
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 181 | Descartados: 59
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 183 | Descartados: 57
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 181 | Descartados: 59
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando semente: 1
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 184 | Descartados: 56
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 183 | Descartados: 57
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 186 | Descartados: 54
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 181 | Descartados: 59
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 181 | Descartados: 59
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 184 | Descartados: 56
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 180 | Descartados: 60
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 182 | Descartados: 58
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 182 | Descartados: 58
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 181 | Descartados: 59
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando semente: 2
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 180 | Descartados: 60
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 183 | Descartados: 57
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 184 | Descartados: 56
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 184 | Descartados: 56
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 184 | Descartados: 56
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 183 | Descartados: 57
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 182 | Descartados: 58
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 183 | Descartados: 57
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 181 | Descartados: 59
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 184 | Descartados: 56
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando semente: 3
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 183 | Descartados: 57
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 180 | Descartados: 60
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 183 | Descartados: 57
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 184 | Descartados: 56
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 182 | Descartados: 58
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 182 | Descartados: 58
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 184 | Descartados: 56
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 181 | Descartados: 59
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 182 | Descartados: 58
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 183 | Descartados: 57
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando Grafo - Semente: 0
======================================================================


Total de pares bidirecionais encontrados: 71
Removida aresta Ca ka > -0.72 -> Ca ka > -0.22 (peso 0.3089)
Mantida aresta Ca ka > -0.22 -> Ca ka > -0.72 (peso 2.6681)

======================================================================

Removida aresta Fe ka > -0.44 -> Fe ka <= 0.86 (peso 0.2218)
Mantida aresta Fe ka <= 0.86 -> Fe ka > -0.44 (peso 0.2381)

======================================================================

Removida aresta Fe ka <= 0.86 -> Fe ka > 0.86 (peso 0.1104)
Mantida aresta Fe ka > 0.86 -> Fe ka <= 0.86 (peso 0.1920)

======================================================================

Removida aresta Mn > -0.35 -> Ti ka > 0.50 (peso 0.0669)
Mantida aresta Ti ka > 0.50 -> Mn > -0.35 (peso 0.1542)

======================================================================

Removida aresta Ti ka > 0.50 -> Fe kb > -0.59 (peso 0.0687)
Mantida aresta Fe kb > -0.59 -> Ti ka > 0.50 (peso 0.0787)

======================================================================

Removida aresta Ti ka > 0.50 -> Ca kb > -0.20 (peso 0.0740)
Mantida aresta Ca kb > -0.20 -> Ti ka > 0.50 (peso 0.1574)

======================================================================

Removida aresta Mn > -0.35 -> Ti ka > -0.80 (peso 0.0751)
Mantida aresta Ti ka > -0.80 -> Mn > -0.35 (peso 0.0789)

======================================================================

Removida aresta Ca ka <= 0.58 -> Mn > -0.35 (peso 0.1430)
Mantida aresta Mn > -0.35 -> Ca ka <= 0.58 (peso 0.1634)

======================================================================

Removida aresta Ca ka <= 0.58 -> Ti ka > -0.80 (peso 0.0677)
Mantida aresta Ti ka > -0.80 -> Ca ka <= 0.58 (peso 0.0732)

======================================================================

Removida aresta Ca ka <= 0.58 -> Ca kb > -0.15 (peso 0.0749)
Mantida aresta Ca kb > -0.15 -> Ca ka <= 0.58 (peso 0.1431)

======================================================================

Removida aresta Fe kb > -0.23 -> Ti ka > -0.37 (peso 0.0527)
Mantida aresta Ti ka > -0.37 -> Fe kb > -0.23 (peso 0.0592)

======================================================================

Removida aresta Ca kb > -0.20 -> Fe kb > -0.59 (peso 0.1417)
Mantida aresta Fe kb > -0.59 -> Ca kb > -0.20 (peso 0.1503)

======================================================================

Removida aresta Fe kb > -0.59 -> Fe kb <= 0.57 (peso 0.0650)
Mantida aresta Fe kb <= 0.57 -> Fe kb > -0.59 (peso 0.0757)

======================================================================

Removida aresta Fe kb > -0.59 -> Ca kb > -0.15 (peso 0.0684)
Mantida aresta Ca kb > -0.15 -> Fe kb > -0.59 (peso 0.0743)

======================================================================

Removida aresta Ca kb > -0.15 -> Ca kb > -0.07 (peso 0.0665)
Mantida aresta Ca kb > -0.07 -> Ca kb > -0.15 (peso 0.2081)

======================================================================

Removida aresta Fe kb <= 0.57 -> Ca kb > -0.07 (peso 0.0711)
Mantida aresta Ca kb > -0.07 -> Fe kb <= 0.57 (peso 0.1309)

======================================================================

Removida aresta Mn > -0.23 -> Si > -0.38 (peso 0.0550)
Mantida aresta Si > -0.38 -> Mn > -0.23 (peso 0.1141)

======================================================================

Removida aresta Si > -0.38 -> Fe kb <= 0.57 (peso 0.0603)
Mantida aresta Fe kb <= 0.57 -> Si > -0.38 (peso 0.1196)

======================================================================

Removida aresta Fe kb > -0.23 -> Mn > -0.23 (peso 0.0582)
Mantida aresta Mn > -0.23 -> Fe kb > -0.23 (peso 0.1686)

======================================================================

Removida aresta Mn > -0.23 -> Mn > -0.14 (peso 0.0829)
Mantida aresta Mn > -0.14 -> Mn > -0.23 (peso 0.1151)

======================================================================

Removida aresta Mn > -0.14 -> Fe kb > -0.23 (peso 0.0525)
Mantida aresta Fe kb > -0.23 -> Mn > -0.14 (peso 0.1143)

======================================================================

Removida aresta Fe kb > -0.23 -> Fe kb <= 0.34 (peso 0.0466)
Mantida aresta Fe kb <= 0.34 -> Fe kb > -0.23 (peso 0.0537)

======================================================================

Removida aresta Mn > -0.14 -> Fe kb <= 0.57 (peso 0.0487)
Mantida aresta Fe kb <= 0.57 -> Mn > -0.14 (peso 0.0542)

======================================================================

Removida aresta Al <= 0.22 -> Ti ka <= -0.37 (peso 0.0390)
Mantida aresta Ti ka <= -0.37 -> Al <= 0.22 (peso 0.0782)

======================================================================

Removida aresta Al <= 0.22 -> K > -0.21 (peso 0.0346)
Mantida aresta K > -0.21 -> Al <= 0.22 (peso 0.1402)

======================================================================

Removida aresta Fe kb > 0.34 -> Al <= 0.22 (peso 0.0356)
Mantida aresta Al <= 0.22 -> Fe kb > 0.34 (peso 0.0796)

======================================================================

Removida aresta K > -0.21 -> Fe kb <= 0.34 (peso 0.0398)
Mantida aresta Fe kb <= 0.34 -> K > -0.21 (peso 0.1283)

======================================================================

Removida aresta K > -0.15 -> Ti ka <= 0.50 (peso 0.0302)
Mantida aresta Ti ka <= 0.50 -> K > -0.15 (peso 0.0643)

======================================================================

Removida aresta Ca ka <= -0.22 -> Ti ka <= 0.50 (peso 0.0302)
Mantida aresta Ti ka <= 0.50 -> Ca ka <= -0.22 (peso 0.0363)

======================================================================

Removida aresta Si > -0.20 -> Ca ka <= -0.22 (peso 0.0317)
Mantida aresta Ca ka <= -0.22 -> Si > -0.20 (peso 0.0948)

======================================================================

Removida aresta Si > -0.20 -> Fe kb > 0.34 (peso 0.0336)
Mantida aresta Fe kb > 0.34 -> Si > -0.20 (peso 0.0417)

======================================================================

Removida aresta Si > -0.20 -> Ti ka <= 0.91 (peso 0.0270)
Mantida aresta Ti ka <= 0.91 -> Si > -0.20 (peso 0.0637)

======================================================================

Removida aresta sum Fe <= 0.20 -> Si > 0.16 (peso 0.0255)
Mantida aresta Si > 0.16 -> sum Fe <= 0.20 (peso 0.0305)

======================================================================

Removida aresta P <= 0.22 -> Si > 0.16 (peso 0.0197)
Mantida aresta Si > 0.16 -> P <= 0.22 (peso 0.0254)

======================================================================

Removida aresta Si > 0.16 -> Mn <= 0.37 (peso 0.0197)
Mantida aresta Mn <= 0.37 -> Si > 0.16 (peso 0.0280)

======================================================================

Removida aresta Si > 0.16 -> Al <= 0.16 (peso 0.0241)
Mantida aresta Al <= 0.16 -> Si > 0.16 (peso 0.0243)

======================================================================

Removida aresta Si > 0.16 -> Al > -0.22 (peso 0.0275)
Mantida aresta Al > -0.22 -> Si > 0.16 (peso 0.0311)

======================================================================

Removida aresta Ca kb <= 0.20 -> Ti kb > -0.18 (peso 0.0224)
Mantida aresta Ti kb > -0.18 -> Ca kb <= 0.20 (peso 0.0428)

======================================================================

Removida aresta Si <= 0.37 -> K > -0.15 (peso 0.0310)
Mantida aresta K > -0.15 -> Si <= 0.37 (peso 0.0581)

======================================================================

Removida aresta P > -0.16 -> K > -0.15 (peso 0.0245)
Mantida aresta K > -0.15 -> P > -0.16 (peso 0.0278)

======================================================================

Removida aresta Al > -0.22 -> Si <= 0.37 (peso 0.0262)
Mantida aresta Si <= 0.37 -> Al > -0.22 (peso 0.0599)

======================================================================

Removida aresta Si <= 0.37 -> Ti kb <= 0.37 (peso 0.0235)
Mantida aresta Ti kb <= 0.37 -> Si <= 0.37 (peso 0.0252)

======================================================================

Removida aresta P <= 0.22 -> Al <= 0.16 (peso 0.0247)
Mantida aresta Al <= 0.16 -> P <= 0.22 (peso 0.0249)

======================================================================

Removida aresta sum Fe > -0.20 -> Al <= 0.16 (peso 0.0225)
Mantida aresta Al <= 0.16 -> sum Fe > -0.20 (peso 0.0232)

======================================================================

Removida aresta Al <= 0.16 -> Ti kb <= 0.37 (peso 0.0258)
Mantida aresta Ti kb <= 0.37 -> Al <= 0.16 (peso 0.0285)

======================================================================

Removida aresta Ti kb <= 0.20 -> background13 > -0.15 (peso 0.0138)
Mantida aresta background13 > -0.15 -> Ti kb <= 0.20 (peso 0.0148)

======================================================================

Removida aresta Al > -0.12 -> Ti kb <= 0.20 (peso 0.0188)
Mantida aresta Ti kb <= 0.20 -> Al > -0.12 (peso 0.0404)

======================================================================

Removida aresta Ti kb <= 0.20 -> Cr <= 0.19 (peso 0.0185)
Mantida aresta Cr <= 0.19 -> Ti kb <= 0.20 (peso 0.0349)

======================================================================

Removida aresta Al > -0.12 -> sum Fe > -0.20 (peso 0.0206)
Mantida aresta sum Fe > -0.20 -> Al > -0.12 (peso 0.0236)

======================================================================

Removida aresta sum Fe > -0.20 -> background13 <= 0.18 (peso 0.0225)
Mantida aresta background13 <= 0.18 -> sum Fe > -0.20 (peso 0.0228)

======================================================================

Removida aresta Ti kb > 0.20 -> Al <= -0.12 (peso 0.0159)
Mantida aresta Al <= -0.12 -> Ti kb > 0.20 (peso 0.0176)

======================================================================

Removida aresta Si <= 0.16 -> Al > -0.12 (peso 0.0172)
Mantida aresta Al > -0.12 -> Si <= 0.16 (peso 0.0181)

======================================================================

Removida aresta background13 <= 0.18 -> Al > -0.12 (peso 0.0208)
Mantida aresta Al > -0.12 -> background13 <= 0.18 (peso 0.0236)

======================================================================

Removida aresta Al > -0.12 -> Fe kb <= -0.23 (peso 0.0193)
Mantida aresta Fe kb <= -0.23 -> Al > -0.12 (peso 0.0206)

======================================================================

Removida aresta K > -0.02 -> Si <= 0.16 (peso 0.0174)
Mantida aresta Si <= 0.16 -> K > -0.02 (peso 0.0179)

======================================================================

Removida aresta background13 <= 0.18 -> Si <= 0.16 (peso 0.0172)
Mantida aresta Si <= 0.16 -> background13 <= 0.18 (peso 0.0173)

======================================================================

Removida aresta Si <= 0.16 -> Cr <= 0.19 (peso 0.0153)
Mantida aresta Cr <= 0.19 -> Si <= 0.16 (peso 0.0187)

======================================================================

Removida aresta K > -0.02 -> background13 <= 0.18 (peso 0.0178)
Mantida aresta background13 <= 0.18 -> K > -0.02 (peso 0.0420)

======================================================================

Removida aresta background9 <= 0.12 -> K > -0.02 (peso 0.0157)
Mantida aresta K > -0.02 -> background9 <= 0.12 (peso 0.0346)

======================================================================

Removida aresta Cr <= 0.19 -> Al <= -0.12 (peso 0.0347)
Mantida aresta Al <= -0.12 -> Cr <= 0.19 (peso 0.0384)

======================================================================

Removida aresta Al <= -0.12 -> P > -0.13 (peso 0.0107)
Mantida aresta P > -0.13 -> Al <= -0.12 (peso 0.0156)

======================================================================

Removida aresta background9 <= 0.12 -> Al <= -0.12 (peso 0.0147)
Mantida aresta Al <= -0.12 -> background9 <= 0.12 (peso 0.0156)

======================================================================

Removida aresta K <= 0.21 -> Al <= -0.12 (peso 0.0134)
Mantida aresta Al <= -0.12 -> K <= 0.21 (peso 0.0138)

======================================================================

Removida aresta background9 <= 0.12 -> Cr > -0.13 (peso 0.0148)
Mantida aresta Cr > -0.13 -> background9 <= 0.12 (peso 0.0408)

======================================================================

Removida aresta K <= 0.21 -> background9 <= 0.12 (peso 0.0159)
Mantida aresta background9 <= 0.12 -> K <= 0.21 (peso 0.0280)

======================================================================

Removida aresta K <= 0.21 -> Ca ka <= -0.47 (peso 0.0104)
Mantida aresta Ca ka <= -0.47 -> K <= 0.21 (peso 0.0133)

======================================================================

Removida aresta sum Fe <= 0.15 -> background13 <= 0.14 (peso 0.0139)
Mantida aresta background13 <= 0.14 -> sum Fe <= 0.15 (peso 0.0169)

======================================================================

Removida aresta background11 <= 0.19 -> sum Fe <= 0.15 (peso 0.0120)
Mantida aresta sum Fe <= 0.15 -> background11 <= 0.19 (peso 0.0123)

======================================================================

Removida aresta background13 > -0.15 -> background13 <= 0.14 (peso 0.0132)
Mantida aresta background13 <= 0.14 -> background13 > -0.15 (peso 0.0152)

======================================================================

Removida aresta background13 > -0.15 -> Ca ka <= -0.47 (peso 0.0109)
Mantida aresta Ca ka <= -0.47 -> background13 > -0.15 (peso 0.0143)

======================================================================

Removida aresta Ti kb <= -0.18 -> background13 <= 0.14 (peso 0.0131)
Mantida aresta background13 <= 0.14 -> Ti kb <= -0.18 (peso 0.0302)

======================================================================


======================================================================
RESUMO DO GRAFO CONSTRUÍDO
======================================================================
Total de arestas iniciais: 506
Total de arestas removidas por bidirecionalidade: 71
Arestas bidirecionais restantes: 0
Total de nós predicados: 76
Total de nós terminais: 2
Métrica utilizada para pesos: Covariance


======================================================================
Processando Grafo - Semente: 1
======================================================================


Total de pares bidirecionais encontrados: 77
Removida aresta Ca ka > -0.47 -> Ca ka > -0.72 (peso 0.3046)
Mantida aresta Ca ka > -0.72 -> Ca ka > -0.47 (peso 1.4592)

======================================================================

Removida aresta Fe ka > -1.50 -> Ca ka > -0.47 (peso 0.1470)
Mantida aresta Ca ka > -0.47 -> Fe ka > -1.50 (peso 1.3663)

======================================================================

Removida aresta Fe ka > -0.44 -> Ca ka > -0.47 (peso 0.1250)
Mantida aresta Ca ka > -0.47 -> Fe ka > -0.44 (peso 0.2559)

======================================================================

Removida aresta Ca ka > -0.47 -> Fe ka <= 1.45 (peso 0.1229)
Mantida aresta Fe ka <= 1.45 -> Ca ka > -0.47 (peso 0.2851)

======================================================================

Removida aresta Fe ka > 0.86 -> Fe ka > -0.44 (peso 0.1941)
Mantida aresta Fe ka > -0.44 -> Fe ka > 0.86 (peso 0.7077)

======================================================================

Removida aresta Ca kb > -0.15 -> Ca kb > -0.07 (peso 0.0707)
Mantida aresta Ca kb > -0.07 -> Ca kb > -0.15 (peso 0.1430)

======================================================================

Removida aresta Fe ka <= 0.86 -> Ca ka <= 0.58 (peso 0.0697)
Mantida aresta Ca ka <= 0.58 -> Fe ka <= 0.86 (peso 0.0730)

======================================================================


,Predicate_Cov_Seed_0,Predicate_Cov_Seed_1,Predicate_Cov_Seed_2,Predicate_Cov_Seed_3
0,Ca ka > -0.22,Ca ka > -0.22,Ca ka > -0.22,Ca ka > -0.22
1,Ca ka > -0.72,Ca ka > -0.47,Ca ka > -0.72,Ca ka > -0.47
2,Ca ka > -0.47,Ca ka > -0.72,Ca ka > -0.47,Ca ka > -0.72
3,Fe ka > -1.50,Fe ka > -1.50,Fe ka > -1.50,Fe ka > -1.50
4,Fe ka > -0.44,Fe ka > -0.44,Fe ka > -0.44,Fe ka <= 1.45
...,...,...,...,...
80,NaN,P > 0.12,Class_A,background6 <= 0.10
81,NaN,background10 <= 0.15,Class_B,Al > 0.16
82,NaN,Class_A,NaN,background9 <= 0.08
83,NaN,Class_B,NaN,Class_A
84,NaN,NaN,NaN,Class_B

In [9]:
# Somar LRCs de predicados equivalentes entre diferentes seeds
lrc_combined_list = []

for seed in random_seeds:
    lrc_df = lrc_cov_by_seed[seed].copy()
    lrc_combined_list.append(lrc_df) # o append adiciona o dataframe ao final da lista

# Concatenar todos os dataframes
lrc_all_seeds = pd.concat(lrc_combined_list, ignore_index=True) 

# Agrupar por predicado (Node) e somar as LRCs, mantendo Zone, Threshold e Operator
lrc_summed_df = lrc_all_seeds.groupby('Node').agg({ # o .agg pode ser usado para aplicar múltiplas funções de agregação
    'Local_Reaching_Centrality': 'mean', # sum = somando as LRCs, poderia ser média ou outro agregado
    'Zone': 'first',
    'Threshold': 'first',
    'Operator': 'first'
}).reset_index()

# Ordenar pelo valor de LRC somado (maior para menor)
lrc_summed_df = lrc_summed_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
# vamoss pegar so os valore sunicos de lrc_summed_df baseado na zona espectral
lrc_summed_unique_df_cov = lrc_summed_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
lrc_summed_unique_df_cov = lrc_summed_unique_df_cov.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
lrc_summed_unique_df_cov

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator
0,Ca ka > -0.22,12.987209,Ca ka,-0.22,>
1,Fe ka > -1.50,5.495435,Fe ka,-1.50,>
2,Mn > -0.35,1.697186,Mn,-0.35,>
3,Fe kb > -0.59,1.689004,Fe kb,-0.59,>
4,Ca kb > -0.20,1.608756,Ca kb,-0.20,>
5,Si > -0.38,1.450655,Si,-0.38,>
6,Ti ka > -0.37,1.445053,Ti ka,-0.37,>
7,K > -0.21,1.221449,K,-0.21,>
8,Al <= 0.22,1.166348,Al,0.22,<=
9,Ti kb > -0.32,1.024835,Ti kb,-0.32,>
10,P <= 0.22,0.997924,P,0.22,<=
11,sum Fe <= 0.20,0.952119,sum Fe,0.20,<=
12,background13 <= 0.18,0.897528,background13,0.18,<=
13,Cr > -0.17,0.819514,Cr,-0.17,>
14,background9 <= 0.12,0.772236,background9,0.12,<=
15,background11 <= 0.19,0.756269,background11,0.19,<=
16,Cu > -0.10,0.750528,Cu,-0.10,>
17,background6 <= 0.14,0.735752,background6,0.14,<=
18,background7 > 0.17,0.733389,background7,0.17,>
19,S > -0.13,0.702753,S,-0.13,>
20,background8 <= 0.09,0.701021,background8,0.09,<=
21,Fe ka + Ti ka <= 0.16,0.661479,Fe ka + Ti ka,0.16,<=
22,background12 <= 0.13,0.650628,background12,0.13,<=
23,Rh L + Ar > -0.15,0.574454,Rh L + Ar,-0.15,>
24,background1 <= 0.11,0.467020,background1,0.11,<=
25,background10 <= 0.15,0.001997,background10,0.15,<=
26,Class_B,0.000000,None,None,None

# **Perturbation**

In [10]:
import explaining as exp

# LISTA DE SEMENTES A TESTAR
random_seeds = [0, 1, 2, 3]

all_results_pert = {}
training_samples = len(Xcalclass)

# LOOP: PROCESSAR CADA SEMENTE
y_predicted_numeric = plsda_results[5].iloc[:, -1] # predições numéricas do modelo

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando semente: {seed}")
    print(f"{'='*70}\n")
    # Bagging
    bags_result_seed = exp.bagging_predicates(
        zone_sums_df=zone_sums_df,
        y_predicted_numeric=y_predicted_numeric,
        predicates_df=predicates_quantiles[0],
        n_bags=10,
        #n_predicates_per_bag=40,
        n_samples_per_bag=int(training_samples*0.8), # 80 % da base para amostrar (convertido para int)
        min_samples_per_predicate=int(training_samples*0.2), # 20 % da base para limitar (convertido para int)
        replace=False,
        sample_bagging=True,
        predicate_bagging=False,
        random_seed=seed
    )
    # Inserir classe prevista
    for bag_name, pred_dict in bags_result_seed.items(): # iterando sobre cada bag
        for pred_rule, df_info in pred_dict.items():
            df_info['Class_Predicted'] = np.where(df_info['Predicted_Y'] >= 0.5, 'A', 'B') # binarizando com threshold 0.5, A = eut, B = dist

    pert_results_seed = exp.calculate_predicate_perturbation(
        estimator=pls_model,
        Xcalclass_prep=Xcalclass_prep,
        folds_struct=bags_result_seed,
        predicates_df=predicates_quantiles[0],
        spectral_cuts=spectral_cuts,
        #perturbation_value=0,
        perturbation_mode='mean', # valores entre 'mean' ou 'min'
        stats_source='full', # full indica usar todas as amostras para calcular estatísticas enquanto que 'fold' usa apenas as amostras do fold atual
        metric='mean_abs_diff',   # Média com sinal (pode ser negativo)
        verbose=True
    )

    # Remove todos os valores iguais a zero de todos os bags em perm_results[bag]["Permutation"] e salva como perm_results_thresholded
    # pert_results_seed_thresholded = {}
    # for bag, df in perm_results_seed.items():
    #     # Verifica se é um DataFrame e se a coluna 'Permutation' existe
    #     if isinstance(df, pd.DataFrame) and 'Permutation' in df.columns:
    #         filtered_df = df[df['Permutation'] > 0].copy()
    #         pert_results_seed_thresholded[bag] = filtered_df
    #     else:
    #         # Se não for DataFrame esperado, apenas copia
    #         pert_results_seed_thresholded[bag] = df

    # Salvar no dicionário principal
    all_results_pert[seed] = {
        'bags_result': bags_result_seed,
        'pert_results_dict': pert_results_seed
    }

# CONSTRUÇÃO DE GRAFOS PARA MÚLTIPLAS SEMENTES (LOOP EXTERNO)
# Dicionário para armazenar grafos
graphs_pert_by_seed = {}

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando Grafo - Semente: {seed}")
    print(f"{'='*70}\n")
    # Construir grafo para esta semente
    DG = exp.build_predicate_graphv2(
        bags_result=all_results_pert[seed]['bags_result'],
        predicate_ranking_dict=all_results_pert[seed]['pert_results_dict'],
        metric_column='Perturbation',  # ou 'Covariance' se mudar a métrica
        random_state=seed,
        show_details=True
    )
    # Armazenar grafo
    graphs_pert_by_seed[seed] = DG  

# Calcular LRC usando a função pronta do explaining.py
lrc_pert_by_seed = {}
for seed in random_seeds:
    DG = graphs_pert_by_seed[seed]
    lrc_pert_df_seed = exp.calculate_lrc_single_graph(DG, predicates_quantiles[0])
    lrc_pert_df_seed['Seed'] = seed  # Adicionar coluna com a semente
    lrc_pert_by_seed[seed] = lrc_pert_df_seed

# junando todas as colunas 'Node' de lrc_by_seed em um único dataframe
lrc_pert_all_seeds_df = pd.DataFrame()
for seed in random_seeds:
    lrc_pert_df_seed = lrc_pert_by_seed[seed].rename(columns={'Node': f'Predicate_pert_Seed_{seed}'})
    lrc_pert_all_seeds_df = pd.concat([lrc_pert_all_seeds_df, lrc_pert_df_seed[[f'Predicate_pert_Seed_{seed}']]], axis=1)

# vamos filtrar lrc_by_seed em cada semente para manter apenas as zonas espectrais únicas com maior LRC em um mesmo dataframe
lrc_pert_unique_by_seed = {}
for seed, lrc_df in lrc_pert_by_seed.items():
    lrc_pert_unique_df = lrc_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
    lrc_pert_unique_df = lrc_pert_unique_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
    lrc_pert_unique_by_seed[seed] = lrc_pert_unique_df

lrc_pert_all_seeds_df # exibindo o dataframe consolidado com predicados de todas as sementes

======================================================================
Processando semente: 0
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 183 | Descartados: 57
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 182 | Descartados: 58
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 181 | Descartados: 59
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 183 | Descartados: 57
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 183 | Descartados: 57
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 181 | Descartados: 59
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 180 | Descartados: 60
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 181 | Descartados: 59
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 183 | Descartados: 57
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 181 | Descartados: 59
======================================================================
PERTURBATION IMPORTANCE PARA PREDICADOS
======================================================================
Modo de perturbação: mean
Fonte das estatísticas: full
Métrica: mean_abs_diff
Total de folds: 10


[Bag_1] Processando 183 predicados...
  Predicado: background1 > -0.11 (n=101)
    Zona: 17 colunas
    Importance: 0.000397
  Predicado: background1 <= -0.07 (n=51)
    Zona: 17 colunas
    Importance: 0.000369
  Predicado: background1 > -0.07 (n=67)
    Zona: 17 colunas
    Importance: 0.000419
  Predicado: background1 <= 0.09 (n=74)
    Zona: 17 colunas
    Importance: 0.000364
  Predicado: background1 > 0.09 (n=44)
    Zona: 17 colunas
    Importance: 0.000454
  Predicado: background1 <= 0.11 (n=89)
    Zona: 17 colunas
    Importance: 0.000395
  Predicado: background1 > 0.11 (n=29)
    Zona: 17 colunas
    Importance: 0.000406
  Predicado: Al > -0.22 (n=94)
    Zona: 15 colunas
    Importance: 0.006558
  Predicado: Al <= -0.12 (n=47)
    Zona: 15 colunas
    Importance: 0.010203
  Predicado: Al > -0.12 (n=71)
    Zona: 15 colunas
    Importance: 0.007192
  Predicado: Al <= 0.16 (n=71)
    Zona: 15 colunas
    Importance: 0.007749
  Predicado: Al > 0.16 (n=47)
    Zona: 15 colunas
    Importance: 0.009360
  Predicado: Al <= 0.22 (n=95)
    Zona: 15 colunas
    Importance: 0.007188
  Predicado: Si > -0.38 (n=94)
    Zona: 12 colunas
    Importance: 0.068665
  Predicado: Si <= -0.20 (n=49)
    Zona: 12 colunas
    Importance: 0.094478
  Predicado: Si > -0.20 (n=69)
    Zona: 12 colunas
    Importance: 0.074215
  Predicado: Si <= 0.16 (n=71)
    Zona: 12 colunas
    Importance: 0.070856
  Predicado: Si > 0.16 (n=47)
    Zona: 12 colunas
    Importance: 0.100415
  Predicado: Si <= 0.37 (n=93)
    Zona: 12 colunas
    Importance: 0.064079
  Predicado: P <= -0.16 (n=30)
    Zona: 13 colunas
    Importance: 0.005217
  Predicado: P > -0.16 (n=88)
    Zona: 13 colunas
    Importance: 0.005229
  Predicado: P <= -0.13 (n=50)
    Zona: 13 colunas
    Importance: 0.004711
  Predicado: P > -0.13 (n=68)
    Zona: 13 colunas
    Importance: 0.005604
  Predicado: P <= 0.12 (n=69)
    Zona: 13 colunas
    Importance: 0.004043
  Predicado: P > 0.12 (n=49)
    Zona: 13 colunas
    Importance: 0.006892
  Predicado: P <= 0.22 (n=93)
    Zona: 13 colunas
    Importance: 0.003877
  Predicado: background2 > -0.09 (n=96)
    Zona: 5 colunas
    Importance: 0.000329
  Predicado: background2 <= -0.06 (n=43)
    Zona: 5 colunas
    Importance: 0.000393
  Predicado: background2 > -0.06 (n=75)
    Zona: 5 colunas
    Importance: 0.000333
  Predicado: background2 <= 0.06 (n=64)
    Zona: 5 colunas
    Importance: 0.000334
  Predicado: background2 > 0.06 (n=54)
    Zona: 5 colunas
    Importance: 0.000380
  Predicado: background2 <= 0.10 (n=94)
    Zona: 5 colunas
    Importance: 0.000316
  Predicado: S > -0.13 (n=98)
    Zona: 13 colunas
    Importance: 0.001972
  Predicado: S <= -0.09 (n=53)
    Zona: 13 colunas
    Importance: 0.002224
  Predicado: S > -0.09 (n=65)
    Zona: 13 colunas
    Importance: 0.002058
  Predicado: S <= 0.09 (n=71)
    Zona: 13 colunas
    Importance: 0.001950
  Predicado: S > 0.09 (n=47)
    Zona: 13 colunas
    Importance: 0.002408
  Predicado: S <= 0.14 (n=98)
    Zona: 13 colunas
    Importance: 0.001787
  Predicado: background3 > -0.09 (n=92)
    Zona: 6 colunas
    Importance: 0.000154
  Predicado: background3 <= -0.06 (n=49)
    Zona: 6 colunas
    Importance: 0.000175
  Predicado: background3 > -0.06 (n=69)
    Zona: 6 colunas
    Importance: 0.000158
  Predicado: background3 <= 0.06 (n=72)
    Zona: 6 colunas
    Importance: 0.000146
  Predicado: background3 > 0.06 (n=46)
    Zona: 6 colunas
    Importance: 0.000194
  Predicado: background3 <= 0.09 (n=97)
    Zona: 6 colunas
    Importance: 0.000155
  Predicado: Rh L + Ar > -0.15 (n=94)
    Zona: 28 colunas
    Importance: 0.002050
  Predicado: Rh L + Ar <= -0.08 (n=50)
    Zona: 28 colunas
    Importance: 0.002405
  Predicado: Rh L + Ar > -0.08 (n=68)
    Zona: 28 colunas
    Importance: 0.002129
  Predicado: Rh L + Ar <= 0.14 (n=76)
    Zona: 28 colunas
    Importance: 0.002106
  Predicado: Rh L + Ar > 0.14 (n=42)
    Zona: 28 colunas
    Importance: 0.002499
  Predicado: Rh L + Ar <= 0.19 (n=99)
    Zona: 28 colunas
    Importance: 0.002094
  Predicado: background4 > -0.10 (n=94)
    Zona: 6 colunas
    Importance: 0.000496
  Predicado: background4 <= -0.06 (n=47)
    Zona: 6 colunas
    Importance: 0.000392
  Predicado: background4 > -0.06 (n=71)
    Zona: 6 colunas
    Importance: 0.000517
  Predicado: background4 <= 0.08 (n=81)
    Zona: 6 colunas
    Importance: 0.000362
  Predicado: background4 > 0.08 (n=37)
    Zona: 6 colunas
    Importance: 0.000700
  Predicado: background4 <= 0.10 (n=98)
    Zona: 6 colunas
    Importance: 0.000401
  Predicado: K > -0.21 (n=92)
    Zona: 11 colunas
    Importance: 0.007078
  Predicado: K <= -0.15 (n=49)
    Zona: 11 colunas
    Importance: 0.008852
  Predicado: K > -0.15 (n=69)
    Zona: 11 colunas
    Importance: 0.007185
  Predicado: K <= -0.02 (n=73)
    Zona: 11 colunas
    Importance: 0.006783
  Predicado: K > -0.02 (n=45)
    Zona: 11 colunas
    Importance: 0.009652
  Predicado: K <= 0.21 (n=96)
    Zona: 11 colunas
    Importance: 0.006140
  Predicado: background5 > -0.10 (n=101)
    Zona: 6 colunas
    Importance: 0.000396
  Predicado: background5 <= -0.05 (n=47)
    Zona: 6 colunas
    Importance: 0.000387
  Predicado: background5 > -0.05 (n=71)
    Zona: 6 colunas
    Importance: 0.000415
  Predicado: background5 <= 0.07 (n=72)
    Zona: 6 colunas
    Importance: 0.000337
  Predicado: background5 > 0.07 (n=46)
    Zona: 6 colunas
    Importance: 0.000508
  Predicado: background5 <= 0.11 (n=98)
    Zona: 6 colunas
    Importance: 0.000358
  Predicado: Ca ka > -0.72 (n=92)
    Zona: 16 colunas
    Importance: 0.130172
  Predicado: Ca ka <= -0.47 (n=49)
    Zona: 16 colunas
    Importance: 0.141367
  Predicado: Ca ka > -0.47 (n=69)
    Zona: 16 colunas
    Importance: 0.135118
  Predicado: Ca ka <= -0.22 (n=72)
    Zona: 16 colunas
    Importance: 0.112802
  Predicado: Ca ka > -0.22 (n=46)
    Zona: 16 colunas
    Importance: 0.176704
  Predicado: Ca ka <= 0.58 (n=94)
    Zona: 16 colunas
    Importance: 0.096560
  Predicado: Ca kb <= -0.20 (n=30)
    Zona: 16 colunas
    Importance: 0.009847
  Predicado: Ca kb > -0.20 (n=88)
    Zona: 16 colunas
    Importance: 0.007741
  Predicado: Ca kb <= -0.15 (n=48)
    Zona: 16 colunas
    Importance: 0.008391
  Predicado: Ca kb > -0.15 (n=70)
    Zona: 16 colunas
    Importance: 0.008198
  Predicado: Ca kb <= -0.07 (n=69)
    Zona: 16 colunas
    Importance: 0.006896
  Predicado: Ca kb > -0.07 (n=49)
    Zona: 16 colunas
    Importance: 0.010220
  Predicado: Ca kb <= 0.20 (n=94)
    Zona: 16 colunas
    Importance: 0.005936
  Predicado: background6 > -0.13 (n=95)
    Zona: 12 colunas
    Importance: 0.000471
  Predicado: background6 <= -0.08 (n=48)
    Zona: 12 colunas
    Importance: 0.000566
  Predicado: background6 > -0.08 (n=70)
    Zona: 12 colunas
    Importance: 0.000446
  Predicado: background6 <= 0.10 (n=69)
    Zona: 12 colunas
    Importance: 0.000482
  Predicado: background6 > 0.10 (n=49)
    Zona: 12 colunas
    Importance: 0.000512
  Predicado: background6 <= 0.14 (n=92)
    Zona: 12 colunas
    Importance: 0.000479
  Predicado: Ti ka > -0.80 (n=94)
    Zona: 15 colunas
    Importance: 0.028749
  Predicado: Ti ka <= -0.37 (n=51)
    Zona: 15 colunas
    Importance: 0.034777
  Predicado: Ti ka > -0.37 (n=67)
    Zona: 15 colunas
    Importance: 0.030391
  Predicado: Ti ka <= 0.50 (n=72)
    Zona: 15 colunas
    Importance: 0.029758
  Predicado: Ti ka > 0.50 (n=46)
    Zona: 15 colunas
    Importance: 0.036244
  Predicado: Ti ka <= 0.91 (n=94)
    Zona: 15 colunas
    Importance: 0.028967
  Predicado: background7 > -0.16 (n=94)
    Zona: 5 colunas
    Importance: 0.000836
  Predicado: background7 <= -0.09 (n=45)
    Zona: 5 colunas
    Importance: 0.001096
  Predicado: background7 > -0.09 (n=73)
    Zona: 5 colunas
    Importance: 0.000897
  Predicado: background7 <= 0.09 (n=71)
    Zona: 5 colunas
    Importance: 0.000828
  Predicado: background7 > 0.09 (n=47)
    Zona: 5 colunas
    Importance: 0.001191
  Predicado: background7 <= 0.17 (n=94)
    Zona: 5 colunas
    Importance: 0.000780
  Predicado: Ti kb > -0.32 (n=95)
    Zona: 19 colunas
    Importance: 0.004351
  Predicado: Ti kb <= -0.18 (n=52)
    Zona: 19 colunas
    Importance: 0.005165
  Predicado: Ti kb > -0.18 (n=66)
    Zona: 19 colunas
    Importance: 0.004200
  Predicado: Ti kb <= 0.20 (n=69)
    Zona: 19 colunas
    Importance: 0.004387
  Predicado: Ti kb > 0.20 (n=49)
    Zona: 19 colunas
    Importance: 0.004960
  Predicado: Ti kb <= 0.37 (n=93)
    Zona: 19 colunas
    Importance: 0.004251
  Predicado: Cr > -0.17 (n=95)
    Zona: 33 colunas
    Importance: 0.001611
  Predicado: Cr <= -0.13 (n=47)
    Zona: 33 colunas
    Importance: 0.002041
  Predicado: Cr > -0.13 (n=71)
    Zona: 33 colunas
    Importance: 0.001600
  Predicado: Cr <= 0.12 (n=68)
    Zona: 33 colunas
    Importance: 0.001689
  Predicado: Cr > 0.12 (n=50)
    Zona: 33 colunas
    Importance: 0.001893
  Predicado: Cr <= 0.19 (n=93)
    Zona: 33 colunas
    Importance: 0.001607
  Predicado: Mn > -0.35 (n=98)
    Zona: 13 colunas
    Importance: 0.078463
  Predicado: Mn <= -0.23 (n=47)
    Zona: 13 colunas
    Importance: 0.086698
  Predicado: Mn > -0.23 (n=71)
    Zona: 13 colunas
    Importance: 0.083417
  Predicado: Mn <= -0.14 (n=68)
    Zona: 13 colunas
    Importance: 0.070217
  Predicado: Mn > -0.14 (n=50)
    Zona: 13 colunas
    Importance: 0.104453
  Predicado: Mn <= 0.37 (n=94)
    Zona: 13 colunas
    Importance: 0.060867
  Predicado: background8 > -0.12 (n=94)
    Zona: 6 colunas
    Importance: 0.001023
  Predicado: background8 <= -0.07 (n=48)
    Zona: 6 colunas
    Importance: 0.001153
  Predicado: background8 > -0.07 (n=70)
    Zona: 6 colunas
    Importance: 0.001110
  Predicado: background8 <= 0.09 (n=70)
    Zona: 6 colunas
    Importance: 0.000972
  Predicado: background8 > 0.09 (n=48)
    Zona: 6 colunas
    Importance: 0.001353
  Predicado: background8 <= 0.14 (n=96)
    Zona: 6 colunas
    Importance: 0.000960
  Predicado: Fe ka > -1.50 (n=96)
    Zona: 28 colunas
    Importance: 0.043398
  Predicado: Fe ka <= -0.44 (n=43)
    Zona: 28 colunas
    Importance: 0.067371
  Predicado: Fe ka > -0.44 (n=75)
    Zona: 28 colunas
    Importance: 0.046652
  Predicado: Fe ka <= 0.86 (n=70)
    Zona: 28 colunas
    Importance: 0.048341
  Predicado: Fe ka > 0.86 (n=48)
    Zona: 28 colunas
    Importance: 0.062750
  Predicado: Fe ka <= 1.45 (n=95)
    Zona: 28 colunas
    Importance: 0.046472
  Predicado: background9 > -0.11 (n=94)
    Zona: 7 colunas
    Importance: 0.000248
  Predicado: background9 <= -0.08 (n=46)
    Zona: 7 colunas
    Importance: 0.000318
  Predicado: background9 > -0.08 (n=72)
    Zona: 7 colunas
    Importance: 0.000275
  Predicado: background9 <= 0.08 (n=69)
    Zona: 7 colunas
    Importance: 0.000260
  Predicado: background9 > 0.08 (n=49)
    Zona: 7 colunas
    Importance: 0.000337
  Predicado: background9 <= 0.12 (n=96)
    Zona: 7 colunas
    Importance: 0.000252
  Predicado: Fe kb > -0.59 (n=97)
    Zona: 26 colunas
    Importance: 0.010250
  Predicado: Fe kb <= -0.23 (n=46)
    Zona: 26 colunas
    Importance: 0.015135
  Predicado: Fe kb > -0.23 (n=72)
    Zona: 26 colunas
    Importance: 0.010507
  Predicado: Fe kb <= 0.34 (n=70)
    Zona: 26 colunas
    Importance: 0.011550
  Predicado: Fe kb > 0.34 (n=48)
    Zona: 26 colunas
    Importance: 0.013421
  Predicado: Fe kb <= 0.57 (n=94)
    Zona: 26 colunas
    Importance: 0.011127
  Predicado: background10 > -0.13 (n=92)
    Zona: 31 colunas
    Importance: 0.001251
  Predicado: background10 <= -0.10 (n=49)
    Zona: 31 colunas
    Importance: 0.001704
  Predicado: background10 > -0.10 (n=69)
    Zona: 31 colunas
    Importance: 0.001306
  Predicado: background10 <= 0.12 (n=76)
    Zona: 31 colunas
    Importance: 0.001371
  Predicado: background10 > 0.12 (n=42)
    Zona: 31 colunas
    Importance: 0.001653
  Predicado: background10 <= 0.15 (n=94)
    Zona: 31 colunas
    Importance: 0.001446
  Predicado: Cu > -0.13 (n=90)
    Zona: 15 colunas
    Importance: 0.001915
  Predicado: Cu <= -0.10 (n=50)
    Zona: 15 colunas
    Importance: 0.002413
  Predicado: Cu > -0.10 (n=68)
    Zona: 15 colunas
    Importance: 0.001964
  Predicado: Cu <= 0.10 (n=69)
    Zona: 15 colunas
    Importance: 0.002028
  Predicado: Cu > 0.10 (n=49)
    Zona: 15 colunas
    Importance: 0.002333
  Predicado: Cu <= 0.15 (n=95)
    Zona: 15 colunas
    Importance: 0.001875
  Predicado: background11 > -0.15 (n=93)
    Zona: 125 colunas
    Importance: 0.005032
  Predicado: background11 <= -0.12 (n=43)
    Zona: 125 colunas
    Importance: 0.007695
  Predicado: background11 > -0.12 (n=75)
    Zona: 125 colunas
    Importance: 0.004913
  Predicado: background11 <= 0.14 (n=77)
    Zona: 125 colunas
    Importance: 0.005716
  Predicado: background11 > 0.14 (n=41)
    Zona: 125 colunas
    Importance: 0.006323
  Predicado: background11 <= 0.19 (n=97)
    Zona: 125 colunas
    Importance: 0.005626
  Predicado: Fe ka + Ti ka > -0.13 (n=91)
    Zona: 23 colunas
    Importance: 0.001225
  Predicado: Fe ka + Ti ka <= -0.11 (n=46)
    Zona: 23 colunas
    Importance: 0.001685
  Predicado: Fe ka + Ti ka > -0.11 (n=72)
    Zona: 23 colunas
    Importance: 0.001281
  Predicado: Fe ka + Ti ka <= 0.12 (n=74)
    Zona: 23 colunas
    Importance: 0.001353
  Predicado: Fe ka + Ti ka > 0.12 (n=44)
    Zona: 23 colunas
    Importance: 0.001582
  Predicado: Fe ka + Ti ka <= 0.16 (n=97)
    Zona: 23 colunas
    Importance: 0.001348
  Predicado: background12 > -0.14 (n=95)
    Zona: 71 colunas
    Importance: 0.004135
  Predicado: background12 <= -0.11 (n=52)
    Zona: 71 colunas
    Importance: 0.005072
  Predicado: background12 > -0.11 (n=66)
    Zona: 71 colunas
    Importance: 0.003976
  Predicado: background12 <= 0.13 (n=75)
    Zona: 71 colunas
    Importance: 0.004417
  Predicado: background12 > 0.13 (n=43)
    Zona: 71 colunas
    Importance: 0.004531
  Predicado: background12 <= 0.15 (n=90)
    Zona: 71 colunas
    Importance: 0.004288
  Predicado: sum Fe > -0.20 (n=95)
    Zona: 28 colunas
    Importance: 0.003040
  Predicado: sum Fe <= -0.11 (n=45)
    Zona: 28 colunas
    Importance: 0.004437
  Predicado: sum Fe > -0.11 (n=73)
    Zona: 28 colunas
    Importance: 0.003201
  Predicado: sum Fe <= 0.15 (n=66)
    Zona: 28 colunas
    Importance: 0.003404
  Predicado: sum Fe > 0.15 (n=52)
    Zona: 28 colunas
    Importance: 0.004013
  Predicado: sum Fe <= 0.20 (n=93)
    Zona: 28 colunas
    Importance: 0.003219
  Predicado: background13 > -0.15 (n=95)
    Zona: 96 colunas
    Importance: 0.001955
  Predicado: background13 <= 0.11 (n=50)
    Zona: 96 colunas
    Importance: 0.001835
  Predicado: background13 > 0.11 (n=68)
    Zona: 96 colunas
    Importance: 0.002149
  Predicado: background13 <= 0.14 (n=68)
    Zona: 96 colunas
    Importance: 0.001724
  Predicado: background13 > 0.14 (n=50)
    Zona: 96 colunas
    Importance: 0.002412
  Predicado: background13 <= 0.18 (n=93)
    Zona: 96 colunas
    Importance: 0.001811

[Bag_2] Processando 182 predicados...
  Predicado: background1 > -0.11 (n=96)
    Zona: 17 colunas
    Importance: 0.000396
  Predicado: background1 <= -0.07 (n=50)
    Zona: 17 colunas
    Importance: 0.000380
  Predicado: background1 > -0.07 (n=68)
    Zona: 17 colunas
    Importance: 0.000412
  Predicado: background1 <= 0.09 (n=74)
    Zona: 17 colunas
    Importance: 0.000375
  Predicado: background1 > 0.09 (n=44)
    Zona: 17 colunas
    Importance: 0.000439
  Predicado: background1 <= 0.11 (n=90)
    Zona: 17 colunas
    Importance: 0.000394
  Predicado: Al > -0.22 (n=96)
    Zona: 15 colunas
    Importance: 0.006732
  Predicado: Al <= -0.12 (n=44)
    Zona: 15 colunas
    Importance: 0.009534
  Predicado: Al > -0.12 (n=74)
    Zona: 15 colunas
    Importance: 0.007351
  Predicado: Al <= 0.16 (n=71)
    Zona: 15 colunas
    Importance: 0.007092
  Predicado: Al > 0.16 (n=47)
    Zona: 15 colunas
    Importance: 0.009786
  Predicado: Al <= 0.22 (n=92)
    Zona: 15 colunas
    Importance: 0.006695
  Predicado: Si > -0.38 (n=94)
    Zona: 12 colunas
    Importance: 0.062811
  Predicado: Si <= -0.20 (n=49)
    Zona: 12 colunas
    Importance: 0.089398
  Predicado: Si > -0.20 (n=69)
    Zona: 12 colunas
    Importance: 0.068549
  Predicado: Si <= 0.16 (n=70)
    Zona: 12 colunas
    Importance: 0.067774
  Predicado: Si > 0.16 (n=48)
    Zona: 12 colunas
    Importance: 0.090963
  Predicado: Si <= 0.37 (n=94)
    Zona: 12 colunas
    Importance: 0.059656
  Predicado: P > -0.16 (n=91)
    Zona: 13 colunas
    Importance: 0.004802
  Predicado: P <= -0.13 (n=44)
    Zona: 13 colunas
    Importance: 0.004251
  Predicado: P > -0.13 (n=74)
    Zona: 13 colunas
    Importance: 0.005193
  Predicado: P <= 0.12 (n=66)
    Zona: 13 colunas
    Importance: 0.003671
  Predicado: P > 0.12 (n=52)
    Zona: 13 colunas
    Importance: 0.006328
  Predicado: P <= 0.22 (n=95)
    Zona: 13 colunas
    Importance: 0.003664
  Predicado: background2 > -0.09 (n=95)
    Zona: 5 colunas
    Importance: 0.000327
  Predicado: background2 <= -0.06 (n=42)
    Zona: 5 colunas
    Importance: 0.000425
  Predicado: background2 > -0.06 (n=76)
    Zona: 5 colunas
    Importance: 0.000326
  Predicado: background2 <= 0.06 (n=67)
    Zona: 5 colunas
    Importance: 0.000349
  Predicado: background2 > 0.06 (n=51)
    Zona: 5 colunas
    Importance: 0.000377
  Predicado: background2 <= 0.10 (n=95)
    Zona: 5 colunas
    Importance: 0.000341
  Predicado: S > -0.13 (n=98)
    Zona: 13 colunas
    Importance: 0.001966
  Predicado: S <= -0.09 (n=52)
    Zona: 13 colunas
    Importance: 0.002248
  Predicado: S > -0.09 (n=66)
    Zona: 13 colunas
    Importance: 0.002021
  Predicado: S <= 0.09 (n=72)
    Zona: 13 colunas
    Importance: 0.001894
  Predicado: S > 0.09 (n=46)
    Zona: 13 colunas
    Importance: 0.002476
  Predicado: S <= 0.14 (n=95)
    Zona: 13 colunas
    Importance: 0.001765
  Predicado: background3 > -0.09 (n=95)
    Zona: 6 colunas
    Importance: 0.000151
  Predicado: background3 <= -0.06 (n=42)
    Zona: 6 colunas
    Importance: 0.000188
  Predicado: background3 > -0.06 (n=76)
    Zona: 6 colunas
    Importance: 0.000154
  Predicado: background3 <= 0.06 (n=66)
    Zona: 6 colunas
    Importance: 0.000152
  Predicado: background3 > 0.06 (n=52)
    Zona: 6 colunas
    Importance: 0.000184
  Predicado: background3 <= 0.09 (n=93)
    Zona: 6 colunas
    Importance: 0.000161
  Predicado: Rh L + Ar > -0.15 (n=99)
    Zona: 28 colunas
    Importance: 0.002183
  Predicado: Rh L + Ar <= -0.08 (n=40)
    Zona: 28 colunas
    Importance: 0.002291
  Predicado: Rh L + Ar > -0.08 (n=78)
    Zona: 28 colunas
    Importance: 0.002299

,Predicate_pert_Seed_0,Predicate_pert_Seed_1,Predicate_pert_Seed_2,Predicate_pert_Seed_3
0,Ca ka > -0.22,Ca ka <= -0.47,Ca ka > -0.22,Ca ka > -0.22
1,Ca ka <= -0.47,Ca ka > -0.47,Ca ka <= -0.47,Ca ka <= -0.47
2,Ca ka > -0.47,Ca ka > -0.72,Ca ka > -0.47,Ca ka > -0.47
3,Ca ka > -0.72,Ca ka > -0.22,Ca ka > -0.72,Ca ka > -0.72
4,Ca ka <= -0.22,Ca ka <= -0.22,Ca ka <= -0.22,Ca ka <= -0.22
...,...,...,...,...
190,NaN,background3 <= 0.06,background3 <= 0.09,background3 > -0.09
191,NaN,Class_A,background3 > -0.09,Class_A
192,NaN,Class_B,background3 <= 0.06,Class_B
193,NaN,NaN,Class_A,NaN
194,NaN,NaN,Class_B,NaN

In [16]:
all_results_pert[0]['pert_results_dict']['Bag_9']

                Predicate  Perturbation
0           Ca ka > -0.22      0.187443
1           Ca ka > -0.47      0.139642
2          Ca ka <= -0.47      0.135000
3           Ca ka > -0.72      0.132471
4          Ca ka <= -0.22      0.107187
..                    ...           ...
178  background3 <= -0.06      0.000179
179   background3 > -0.06      0.000162
180   background3 <= 0.09      0.000159
181   background3 > -0.09      0.000156
182   background3 <= 0.06      0.000148

[183 rows x 2 columns]

In [17]:
# Somar LRCs de predicados equivalentes entre diferentes seeds
lrc_combined_list = []

for seed in random_seeds:
    lrc_df = lrc_pert_by_seed[seed].copy()
    lrc_combined_list.append(lrc_df) # o append adiciona o dataframe ao final da lista

# Concatenar todos os dataframes
lrc_all_seeds = pd.concat(lrc_combined_list, ignore_index=True) 

# Agrupar por predicado (Node) e somar as LRCs, mantendo Zone, Threshold e Operator
lrc_summed_df = lrc_all_seeds.groupby('Node').agg({ # o .agg pode ser usado para aplicar múltiplas funções de agregação
    'Local_Reaching_Centrality': 'mean', # sum = somando as LRCs, poderia ser média ou outro agregado
    'Zone': 'first',
    'Threshold': 'first',
    'Operator': 'first'
}).reset_index()

# Ordenar pelo valor de LRC somado (maior para menor)
lrc_summed_df = lrc_summed_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
# vamoss pegar so os valore sunicos de lrc_summed_df baseado na zona espectral
lrc_summed_unique_df_pert = lrc_summed_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
lrc_summed_unique_df_pert = lrc_summed_unique_df_pert.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
lrc_summed_unique_df_pert

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator
0,Ca ka > -0.22,9.904303,Ca ka,-0.22,>
1,Mn > -0.14,6.032667,Mn,-0.14,>
2,Si > 0.16,5.371795,Si,0.16,>
3,Fe ka > 0.86,3.517102,Fe ka,0.86,>
4,Ti ka > 0.50,2.034826,Ti ka,0.50,>
5,Fe kb <= -0.23,1.007098,Fe kb,-0.23,<=
6,K > -0.02,0.474513,K,-0.02,>
7,Ca kb <= -0.20,0.462217,Ca kb,-0.20,<=
8,Al > 0.16,0.446962,Al,0.16,>
9,background11 <= -0.12,0.293365,background11,-0.12,<=
10,P > 0.12,0.274772,P,0.12,>
11,Ti kb <= -0.18,0.222172,Ti kb,-0.18,<=
12,sum Fe > 0.20,0.202745,sum Fe,0.20,>
13,background12 > 0.13,0.201061,background12,0.13,>
14,Cu > 0.15,0.096725,Cu,0.15,>
15,Rh L + Ar > 0.14,0.076626,Rh L + Ar,0.14,>
16,background13 > 0.14,0.066643,background13,0.14,>
17,S > 0.09,0.065251,S,0.09,>
18,Cr > -0.17,0.064070,Cr,-0.17,>
19,background7 > 0.17,0.062150,background7,0.17,>
20,Fe ka + Ti ka <= -0.13,0.059581,Fe ka + Ti ka,-0.13,<=
21,background10 > 0.12,0.057147,background10,0.12,>
22,background8 > 0.09,0.043461,background8,0.09,>
23,background4 > 0.08,0.013379,background4,0.08,>
24,background6 <= -0.08,0.009516,background6,-0.08,<=
25,background5 > 0.07,0.007733,background5,0.07,>
26,background1 <= 0.09,0.007591,background1,0.09,<=
27,background2 > -0.06,0.007178,background2,-0.06,>
28,background9 > 0.08,0.006260,background9,0.08,>
29,background3 > 0.06,0.001044,background3,0.06,>
30,Class_A,0.000000,None,None,None

In [18]:
import numpy as np

max_len = max(
    len(vip_scores_unique_df['Zone']),
    len(reg_vet_unique_df['Zone']),
    len(shap_unique_df['Zone']),
    len(lrc_summed_unique_df_pert['Zone']),
    len(lrc_summed_unique_df_cov['Zone'])
)

def pad_list(lst, length):
    return list(lst) + [None] * (length - len(lst))

features_importance = pd.DataFrame({
    'Vip': pad_list(vip_scores_unique_df['Zone'], max_len),
    'Reg_coef': pad_list(reg_vet_unique_df['Zone'], max_len),
    'Shap': pad_list(shap_unique_df['Zone'], max_len),
    'LRC_perturbation' : pad_list(lrc_summed_unique_df_pert['Zone'], max_len),
    'LRC_covariance' : pad_list(lrc_summed_unique_df_cov['Zone'], max_len),
})

features_importance.to_csv('feature_importance.csv', index=False, sep=';')
features_importance

,Vip,Reg_coef,Shap,LRC_perturbation,LRC_covariance
0,Ca ka,Si,Ca ka,Ca ka,Ca ka
1,Fe ka,Mn,Mn,Mn,Fe ka
2,Mn,Ca ka,Si,Si,Mn
3,Si,Ti ka,Fe ka,Fe ka,Fe kb
4,Fe kb,P,Ti ka,Ti ka,Ca kb
5,Ti ka,Fe ka,Al,Fe kb,Si
6,Ca kb,Al,Fe kb,K,Ti ka
7,Al,Ca kb,P,Ca kb,K
8,K,background11,K,Al,Al
9,sum Fe,background8,background12,background11,Ti kb
10,P,K,Fe ka + Ti ka,P,P
11,Ti kb,Rh L + Ar,background11,Ti kb,sum Fe
12,background8,sum Fe,background13,sum Fe,background13
13,background11,Ti kb,background1,background12,Cr
14,Cr,background4,sum Fe,Cu,background9
15,Rh L + Ar,S,background5,Rh L + Ar,background11
16,S,background10,Cu,background13,Cu
17,background4,Fe kb,Ca kb,S,background6
18,background13,background12,Rh L + Ar,Cr,background7
19,background12,Cu,background4,background7,S
20,background10,Cr,background6,Fe ka + Ti ka,background8
21,background7,background13,background7,background10,Fe ka + Ti ka
22,Cu,background7,Ti kb,background8,background12
23,Fe ka + Ti ka,Fe ka + Ti ka,S,background4,Rh L + Ar
24,background9,background2,background3,background6,background1
25,background2,background1,background2,background5,background10
26,background5,background6,background10,background1,None
27,background1,background5,Cr,background2,None
28,background6,background3,background9,background9,None
29,background3,background9,background8,background3,None
30,None,None,None,None,None

In [19]:
# RBO (Rank-Biased Overlap) para comparar rankings
import rbo
rbo_results = {}
reference_list = [x for x in features_importance['Vip'].tolist() if x is not None]
methods = ['Reg_coef', 'Shap', 'LRC_covariance', 'LRC_perturbation']
for method in methods:
    compare_list = [x for x in features_importance[method].tolist() if x is not None]
    # Truncate both lists to the same length (minimum of both)
    min_len = min(len(reference_list), len(compare_list))
    ref_trunc = reference_list[:min_len]
    cmp_trunc = compare_list[:min_len]
    score = rbo.RankingSimilarity(ref_trunc, cmp_trunc).rbo(p=0.7, k=10)
    rbo_results[method] = score
rbo_results = pd.DataFrame(list(rbo_results.items()), columns=['Method','RBO_Score'])
rbo_results.insert(0, 'Reference', 'Vip')
rbo_results.sort_values(by='RBO_Score', ascending=False, inplace=True)
rbo_results.to_csv('rbo_rank.csv', index=False, sep=';')
rbo_results

  Reference            Method  RBO_Score
2       Vip    LRC_covariance   0.918919
3       Vip  LRC_perturbation   0.794005
1       Vip              Shap   0.782470
0       Vip          Reg_coef   0.329164