## Loading data

In [1]:
# Importing the necessary libraries
import pandas as pd
import numpy as np
import kennard_stone as ks
pd.options.plotting.backend = 'plotly'  # setting plotly as the backend for pandas plotting

# Add parent directory to sys.path so local module 'synthetic' (one level up) can be imported
import sys
from pathlib import Path # for path manipulations
parent_dir = Path.cwd().parent.parent.resolve() # move two levels up from current working directory
if str(parent_dir) not in sys.path: # check to avoid duplicates
    sys.path.insert(0, str(parent_dir)) # insert at the start of sys.path to prioritize local modules

# Loading a soil spectral dataset based on X-ray fluorescence (XRF)
data_complete = pd.read_csv(f'{parent_dir}/XRF_databases/soil/plsda/soil.csv', sep=';') # local copy of Toledo 2022 dataset (os ... indica para omitir o caminho longo)
data = data_complete.loc[:, '1':'15']

# Split dataset by class and create calibration/prediction sets using Kennard-Stone (as in original pipeline)
data_A = data_complete[data_complete['Class'] == 'A'].reset_index(drop=True)
data_B = data_complete[data_complete['Class'] == 'B'].reset_index(drop=True)

# splitting the data into calibration and prediction sets by kennard-stone algorithm
XA_cal, XA_pred = ks.train_test_split(data_A.loc[:, '1':'15'], test_size=0.30)  # class A
XA_cal = XA_cal.reset_index(drop=True)
XA_pred = XA_pred.reset_index(drop=True)

XB_cal, XB_pred = ks.train_test_split(data_B.loc[:, '1':'15'], test_size=0.30)  # class B
XB_cal = XB_cal.reset_index(drop=True)
XB_pred = XB_pred.reset_index(drop=True)

Xcalclass = pd.concat([XA_cal, XB_cal], axis=0).reset_index(drop=True)  # concatenating both classes
Xpredclass = pd.concat([XA_pred, XB_pred], axis=0).reset_index(drop=True)
ycalclass = pd.Series(['A']*XA_cal.shape[0] + ['B']*XB_cal.shape[0])  # target for calibration set
ypredclass = pd.Series(['A']*XA_pred.shape[0] + ['B']*XB_pred.shape[0])  # target for prediction set

# preprocessings
import preprocessings as prepr  # preprocessing methods for XRF data

Xcalclass_prep, mean_calclass, mean_calclass_poisson  = prepr.poisson(Xcalclass, mc=True)
Xpredclass_prep = ((Xpredclass/np.sqrt(mean_calclass)) - mean_calclass_poisson)

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-01-28 13:53:39,770 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-01-28 13:53:39,817 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-01-28 13:53:39,873 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-01-28 13:53:39,894 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

In [2]:
from modeling import svm_optimized

svm_model = svm_optimized(Xcalclass_prep, ycalclass, Xpredclass_prep, ypredclass, aim='classification', kernel='rbf')
svm_model[0]

,Model,Accuracy Cal,Sensitivity Cal,Specificity Cal,CM Cal,Accuracy Pred,Sensitivity Pred,Specificity Pred,CM Pred
0,SVC,0.905405,0.915493,0.896104,"[[69, 8], [6, 65]]",0.875,0.967742,0.787879,"[[26, 7], [1, 30]]"

In [3]:
svm_model[4]

          SVC
0    0.003830
1    0.010471
2    0.061753
3    0.025430
4    0.126280
..        ...
143  0.830477
144  0.928583
145  0.855555
146  0.583762
147  0.833374

[148 rows x 1 columns]

In [4]:
# calculando a covariancia entre cada variável espectral e a predição do modelo SVM
cov_scores = []
y_pred = svm_model[4]['SVC'].values # using the continuous predictions from SVM, extracting as 1D array
for col in Xcalclass_prep.columns:
    x_values = Xcalclass_prep[col].values
    covariance = np.cov(x_values, y_pred)[0, 1] # covariance between x and y
    cov_scores.append(covariance)
cov_scores_df = pd.DataFrame(cov_scores, index=Xcalclass_prep.columns, columns=['Covariance'])
cov_scores_df = np.abs(cov_scores_df)
cov_scores_df.plot()

In [5]:
X_sv = svm_model[3].support_vectors_            # shape (n_SV, n_features)
alpha_dual = svm_model[3].dual_coef_.ravel()    # shape (n_SV,)

# Calculando os coeficientes p usando os vetores de suporte e os multiplicadores de Lagrange
pvetor = pd.DataFrame({'energia' : Xcalclass.columns,
                       'importance': (X_sv.T) @ alpha_dual})
pvetor['importance'] = np.abs(pvetor['importance'])
pvetor['importance'].plot()

In [6]:
# establishing spectral cuts based on expert knowledge of XRF spectra
spectral_cuts = [
('background1', 1.0, 1.33),
('Al', 1.33, 1.63),
('Si', 1.63, 1.86),
('P', 1.86, 2.10),
('background2', 2.10, 2.19),
('S', 2.19, 2.44),
('background3', 2.44, 2.55),
('Rh L + Ar', 2.55, 3.10),
('background4', 3.10, 3.21),
('K', 3.21, 3.42),
('background5', 3.42, 3.53),
('Ca ka', 3.53, 3.84),
('Ca kb', 3.84, 4.14),
('background6', 4.14, 4.37),
('Ti ka', 4.37, 4.66),
('background7', 4.66, 4.75),
('Ti kb', 4.75, 5.12),
('Cr', 5.12, 5.77),
('Mn', 5.77, 6.02),
('background8', 6.02, 6.13),
('Fe ka', 6.13, 6.68),
('background9', 6.68, 6.80),
('Fe kb', 6.80, 7.30),
('background10', 7.30, 7.91),
('Cu', 7.91, 8.20),
('background11', 8.20, 10.69),
('Fe ka + Ti ka', 10.69, 11.14),
('background12', 11.14, 12.55),
('sum Fe' , 12.55, 13.1),
('background13', 13.1, 15.0)
]

import explaining as exp
spectral_zones_class = exp.extract_spectral_zones(Xcalclass_prep, spectral_cuts)
zone_sums_df = exp.aggregate_spectral_zones(spectral_zones_class, aggregator='extreme')
predicates_quantiles = exp.predicates_by_quantiles(zone_sums_df, [0.2, 0.4, 0.6, 0.8])
co_occurrence_matrix_df = predicates_quantiles[2]
predicate_info_dict = exp.create_predicate_info_dict(
    predicates_df=predicates_quantiles[0],
    predicate_indicator_df=predicates_quantiles[1],
    zone_aggregated_df=zone_sums_df,
    y_predicted_numeric=y_pred
)

## Pvector and SHAP

In [7]:
# VIP scores por energia
pvector_df = pd.DataFrame({
    'energy': pvetor['energia'],
    'Pvector': pvetor['importance'].values
})
pvector_df = pvector_df.sort_values(by='Pvector', ascending=False).reset_index(drop=True)
energy_to_zone_vip = {}
for zone_name, start, end in spectral_cuts:
    for e in pvector_df['energy']:
        ef = float(e)
        if start <= ef <= end:
            energy_to_zone_vip[e] = zone_name
pvector_df['Zone'] = pvector_df['energy'].map(energy_to_zone_vip)
pvector_unique_df = pvector_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
#shap_unique_df = pd.read_csv('shap_soil.csv', sep=';') # loading previously saved shap_unique_df
pvector_unique_df

   energy    Pvector           Zone
0     3.7  23.102109          Ca ka
1     6.4  10.628126          Fe ka
2       4   5.196616          Ca kb
3    1.74   4.627687             Si
4    7.02   4.258682          Fe kb
5    4.58   3.192161          Ti ka
6    5.94   2.212679             Mn
7    12.8   2.124654         sum Fe
8    1.46   1.983680             Al
9    5.22   1.949057             Cr
10   2.02   1.817727              P
11   2.32   1.564280              S
12   12.4   1.552919   background12
13   9.38   1.541141   background11
14  13.36   1.445970   background13
15    3.2   1.366254    background4
16   7.54   1.345350   background10
17   8.04   1.330263             Cu
18   3.06   1.222940      Rh L + Ar
19   4.72   1.198949    background7
20   5.02   1.195406          Ti kb
21   10.9   1.034279  Fe ka + Ti ka
22   6.76   1.021199    background9
23    2.1   0.981706    background2
24   4.34   0.918934    background6
25   6.04   0.889038    background8
26   3.26   0.832679              K
27   3.52   0.831842    background5
28      1   0.727195    background1
29   2.48   0.267478    background3

In [26]:
pvector_df = pd.DataFrame({
    'energy': pvetor['energia'],
    'Pvector': pvetor['importance'].values
})
pvector_df.sort_values(by='Pvector', ascending=False, inplace=True)#.reset_index(drop=True)
energy_to_zone_vip = {}
for zone_name, start, end in spectral_cuts:
    for e in pvector_df['energy']:
        ef = float(e)
        if start <= ef <= end:
            energy_to_zone_vip[e] = zone_name
pvector_df['Zone'] = pvector_df['energy'].map(energy_to_zone_vip)
pvector_unique_df = pvector_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
#pvector_unique_df = pvector_unique_df.sort_values(by='Pvector', ascending=False).reset_index(drop=True)
shap_unique_df = pd.read_csv('shap_soil.csv', sep=';') # loading previously saved shap_unique_df
pvector_unique_df

   energy    Pvector           Zone
0     3.7  23.102109          Ca ka
1     6.4  10.628126          Fe ka
2       4   5.196616          Ca kb
3    1.74   4.627687             Si
4    7.02   4.258682          Fe kb
5    4.58   3.192161          Ti ka
6    5.94   2.212679             Mn
7    12.8   2.124654         sum Fe
8    1.46   1.983680             Al
9    5.22   1.949057             Cr
10   2.02   1.817727              P
11   2.32   1.564280              S
12   12.4   1.552919   background12
13   9.38   1.541141   background11
14  13.36   1.445970   background13
15    3.2   1.366254    background4
16   7.54   1.345350   background10
17   8.04   1.330263             Cu
18   3.06   1.222940      Rh L + Ar
19   4.72   1.198949    background7
20   5.02   1.195406          Ti kb
21   10.9   1.034279  Fe ka + Ti ka
22   6.76   1.021199    background9
23    2.1   0.981706    background2
24   4.34   0.918934    background6
25   6.04   0.889038    background8
26   3.26   0.832679              K
27   3.52   0.831842    background5
28      1   0.727195    background1
29   2.48   0.267478    background3

# **bagging - covariance**

In [9]:
import explaining as exp

# LISTA DE SEMENTES A TESTAR
random_seeds = [0, 1, 2, 3]

all_results_cov = {}
training_samples = len(Xcalclass)

# LOOP: PROCESSAR CADA SEMENTE
y_predicted_numeric = pd.Series(y_pred) # predições numéricas do modelo

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando semente: {seed}")
    print(f"{'='*70}\n")
    # Bagging
    bags_result_seed = exp.bagging_predicates(
        zone_sums_df=zone_sums_df,
        y_predicted_numeric=y_predicted_numeric,
        predicates_df=predicates_quantiles[0],
        n_bags=10,
        #n_predicates_per_bag=40,
        n_samples_per_bag=int(training_samples*0.8), # 80 % da base para amostrar (convertido para int)
        min_samples_per_predicate=int(training_samples*0.2), # 20 % da base para limitar (convertido para int)
        replace=False,
        sample_bagging=True,
        predicate_bagging=False,
        random_seed=seed
    )
    
    # Inserir classe prevista
    for bag_name, pred_dict in bags_result_seed.items(): # iterando sobre cada bag
        for pred_rule, df_info in pred_dict.items():
            df_info['Class_Predicted'] = np.where(df_info['Predicted_Y'] >= 0.5, 'A', 'B') # binarizando com threshold 0.5, A = eut, B = dist
    
    # Calcular MI
    cov_results_dict_seed = exp.calculate_predicate_metrics(
        bags_result=bags_result_seed,
        metric='covariance', # covariance ou mutual_information
        threshold=0.01, # threshold para cortar predicados irrelevantes
        n_neighbors=5
    )
    
    # Salvar no dicionário principal
    all_results_cov[seed] = {
        'bags_result': bags_result_seed,
        'cov_results_dict': cov_results_dict_seed
    }

# CONSTRUÇÃO DE GRAFOS PARA MÚLTIPLAS SEMENTES (LOOP EXTERNO)
# Dicionário para armazenar grafos
graphs_by_seed = {}

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando Grafo - Semente: {seed}")
    print(f"{'='*70}\n")
    # Construir grafo para esta semente
    DG = exp.build_predicate_graphv2(
        bags_result=all_results_cov[seed]['bags_result'],
        predicate_ranking_dict=all_results_cov[seed]['cov_results_dict'],
        metric_column='Covariance',  # ou 'Covariance' se mudar a métrica
        random_state=seed,
        show_details=True
    )
    # Armazenar grafo
    graphs_by_seed[seed] = DG

# Calcular LRC usando a função pronta do explaining.py
lrc_cov_by_seed = {}
for seed in random_seeds:
    DG = graphs_by_seed[seed]
    lrc_cov_df_seed = exp.calculate_lrc_single_graph(DG, predicates_quantiles[0])
    lrc_cov_df_seed['Seed'] = seed  # Adicionar coluna com a semente
    lrc_cov_by_seed[seed] = lrc_cov_df_seed

# junando todas as colunas 'Node' de lrc_by_seed em um único dataframe
lrc_cov_all_seeds_df = pd.DataFrame()
for seed in random_seeds:
    lrc_cov_df_seed = lrc_cov_by_seed[seed].rename(columns={'Node': f'Predicate_Cov_Seed_{seed}'})
    lrc_cov_all_seeds_df = pd.concat([lrc_cov_all_seeds_df, lrc_cov_df_seed[[f'Predicate_Cov_Seed_{seed}']]], axis=1)

# vamos filtrar lrc_by_seed em cada semente para manter apenas as zonas espectrais únicas com maior LRC em um mesmo dataframe
lrc_cov_unique_by_seed = {}
for seed, lrc_df in lrc_cov_by_seed.items():
    lrc_cov_unique_df = lrc_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
    lrc_cov_unique_df = lrc_cov_unique_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
    lrc_cov_unique_by_seed[seed] = lrc_cov_unique_df

lrc_cov_all_seeds_df # exibindo o dataframe consolidado com predicados de todas as sementes

======================================================================
Processando semente: 0
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 183 | Descartados: 57
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 182 | Descartados: 58
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 181 | Descartados: 59
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 183 | Descartados: 57
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 183 | Descartados: 57
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 181 | Descartados: 59
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 180 | Descartados: 60
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 181 | Descartados: 59
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 183 | Descartados: 57
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 181 | Descartados: 59
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando semente: 1
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 184 | Descartados: 56
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 183 | Descartados: 57
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 186 | Descartados: 54
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 181 | Descartados: 59
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 181 | Descartados: 59
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 184 | Descartados: 56
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 180 | Descartados: 60
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 182 | Descartados: 58
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 182 | Descartados: 58
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 181 | Descartados: 59
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando semente: 2
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 180 | Descartados: 60
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 183 | Descartados: 57
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 184 | Descartados: 56
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 184 | Descartados: 56
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 184 | Descartados: 56
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 183 | Descartados: 57
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 182 | Descartados: 58
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 183 | Descartados: 57
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 181 | Descartados: 59
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 184 | Descartados: 56
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando semente: 3
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 183 | Descartados: 57
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 180 | Descartados: 60
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 183 | Descartados: 57
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 184 | Descartados: 56
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 182 | Descartados: 58
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 182 | Descartados: 58
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 184 | Descartados: 56
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 181 | Descartados: 59
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 182 | Descartados: 58
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 183 | Descartados: 57
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando Grafo - Semente: 0
======================================================================


Total de pares bidirecionais encontrados: 73
Removida aresta Fe ka <= 1.45 -> Ca ka > -0.72 (peso 0.2303)
Mantida aresta Ca ka > -0.72 -> Fe ka <= 1.45 (peso 1.6775)

======================================================================

Removida aresta Fe ka > -1.50 -> Fe ka <= 1.45 (peso 0.3467)
Mantida aresta Fe ka <= 1.45 -> Fe ka > -1.50 (peso 0.5714)

======================================================================

Removida aresta Fe ka > -1.50 -> Ca ka > -0.47 (peso 0.1689)
Mantida aresta Ca ka > -0.47 -> Fe ka > -1.50 (peso 0.6328)

======================================================================

Removida aresta Ca ka > -0.47 -> Fe ka <= 0.86 (peso 0.3046)
Mantida aresta Fe ka <= 0.86 -> Ca ka > -0.47 (peso 0.4835)

======================================================================

Removida aresta Ca ka <= 0.58 -> Fe ka <= 0.86 (peso 0.1254)
Mantida aresta Fe ka <= 0.86 -> Ca ka <= 0.58 (peso 0.7299)

======================================================================

Removida aresta Fe ka > -0.44 -> Fe ka <= 0.86 (peso 0.1004)
Mantida aresta Fe ka <= 0.86 -> Fe ka > -0.44 (peso 0.1222)

======================================================================

Removida aresta Ca ka <= 0.58 -> Ca ka > -0.47 (peso 0.1360)
Mantida aresta Ca ka > -0.47 -> Ca ka <= 0.58 (peso 0.4347)

======================================================================

Removida aresta Mn > -0.35 -> Fe ka > -0.44 (peso 0.0853)
Mantida aresta Fe ka > -0.44 -> Mn > -0.35 (peso 0.2106)

======================================================================

Removida aresta Fe kb <= 0.57 -> Ti ka > 0.50 (peso 0.0739)
Mantida aresta Ti ka > 0.50 -> Fe kb <= 0.57 (peso 0.1532)

======================================================================

Removida aresta Si > -0.38 -> Ti ka > 0.50 (peso 0.0771)
Mantida aresta Ti ka > 0.50 -> Si > -0.38 (peso 0.1411)

======================================================================

Removida aresta Ti ka > 0.50 -> Fe kb > -0.59 (peso 0.0632)
Mantida aresta Fe kb > -0.59 -> Ti ka > 0.50 (peso 0.0729)

======================================================================

Removida aresta Mn > -0.35 -> Fe kb > -0.59 (peso 0.0719)
Mantida aresta Fe kb > -0.59 -> Mn > -0.35 (peso 0.0725)

======================================================================

Removida aresta Fe kb <= 0.57 -> Ti ka > -0.80 (peso 0.0666)
Mantida aresta Ti ka > -0.80 -> Fe kb <= 0.57 (peso 0.1536)

======================================================================

Removida aresta Ca kb > -0.20 -> Ti ka > -0.80 (peso 0.0606)
Mantida aresta Ti ka > -0.80 -> Ca kb > -0.20 (peso 0.0668)

======================================================================

Removida aresta Mn > -0.23 -> Fe kb <= 0.57 (peso 0.0681)
Mantida aresta Fe kb <= 0.57 -> Mn > -0.23 (peso 0.0787)

======================================================================

Removida aresta Fe kb <= 0.57 -> Ti ka > -0.37 (peso 0.0772)
Mantida aresta Ti ka > -0.37 -> Fe kb <= 0.57 (peso 0.0791)

======================================================================

Removida aresta Si > -0.38 -> Fe ka > 0.86 (peso 0.0713)
Mantida aresta Fe ka > 0.86 -> Si > -0.38 (peso 0.1461)

======================================================================

Removida aresta Fe kb > -0.59 -> Fe ka > 0.86 (peso 0.0813)
Mantida aresta Fe ka > 0.86 -> Fe kb > -0.59 (peso 0.1458)

======================================================================

Removida aresta K > -0.21 -> Fe ka > 0.86 (peso 0.0490)
Mantida aresta Fe ka > 0.86 -> K > -0.21 (peso 0.0547)

======================================================================

Removida aresta Fe ka > 0.86 -> Mn > -0.23 (peso 0.0472)
Mantida aresta Mn > -0.23 -> Fe ka > 0.86 (peso 0.1438)

======================================================================

Removida aresta Fe kb > -0.23 -> Ti ka > -0.37 (peso 0.0620)
Mantida aresta Ti ka > -0.37 -> Fe kb > -0.23 (peso 0.1140)

======================================================================

Removida aresta Fe kb <= 0.34 -> Fe kb > -0.59 (peso 0.0645)
Mantida aresta Fe kb > -0.59 -> Fe kb <= 0.34 (peso 0.0647)

======================================================================

Removida aresta Mn > -0.23 -> Fe kb > -0.23 (peso 0.0582)
Mantida aresta Fe kb > -0.23 -> Mn > -0.23 (peso 0.1043)

======================================================================

Removida aresta Mn > -0.23 -> Ca kb > -0.15 (peso 0.0469)
Mantida aresta Ca kb > -0.15 -> Mn > -0.23 (peso 0.0508)

======================================================================

Removida aresta Fe kb <= 0.34 -> Fe kb > -0.23 (peso 0.0539)
Mantida aresta Fe kb > -0.23 -> Fe kb <= 0.34 (peso 0.0553)

======================================================================

Removida aresta K > -0.21 -> Fe kb > -0.23 (peso 0.0529)
Mantida aresta Fe kb > -0.23 -> K > -0.21 (peso 0.0548)

======================================================================

Removida aresta Fe kb > -0.23 -> Si > -0.20 (peso 0.0505)
Mantida aresta Si > -0.20 -> Fe kb > -0.23 (peso 0.1091)

======================================================================

Removida aresta Ca kb > -0.20 -> Fe kb <= 0.34 (peso 0.0551)
Mantida aresta Fe kb <= 0.34 -> Ca kb > -0.20 (peso 0.2500)

======================================================================

Removida aresta Ca kb > -0.20 -> Fe ka <= -0.44 (peso 0.0505)
Mantida aresta Fe ka <= -0.44 -> Ca kb > -0.20 (peso 0.0645)

======================================================================

Removida aresta K > -0.21 -> Ca kb > -0.20 (peso 0.0507)
Mantida aresta Ca kb > -0.20 -> K > -0.21 (peso 0.0633)

======================================================================

Removida aresta K > -0.21 -> Fe kb <= 0.34 (peso 0.0542)
Mantida aresta Fe kb <= 0.34 -> K > -0.21 (peso 0.0546)

======================================================================

Removida aresta K > -0.21 -> Si > -0.20 (peso 0.0491)
Mantida aresta Si > -0.20 -> K > -0.21 (peso 0.1003)

======================================================================

Removida aresta K > -0.21 -> Ca ka > -0.22 (peso 0.0477)
Mantida aresta Ca ka > -0.22 -> K > -0.21 (peso 0.0519)

======================================================================

Removida aresta Ca ka <= -0.22 -> K > -0.15 (peso 0.0431)
Mantida aresta K > -0.15 -> Ca ka <= -0.22 (peso 0.1222)

======================================================================

Removida aresta Al <= 0.22 -> Ca ka <= -0.22 (peso 0.0334)
Mantida aresta Ca ka <= -0.22 -> Al <= 0.22 (peso 0.0736)

======================================================================

Removida aresta Ti kb > -0.18 -> Al <= 0.22 (peso 0.0392)
Mantida aresta Al <= 0.22 -> Ti kb > -0.18 (peso 0.1028)

======================================================================

Removida aresta Ti kb > -0.18 -> Ca kb <= 0.20 (peso 0.0330)
Mantida aresta Ca kb <= 0.20 -> Ti kb > -0.18 (peso 0.0353)

======================================================================

Removida aresta P > -0.16 -> Ti kb > -0.18 (peso 0.0318)
Mantida aresta Ti kb > -0.18 -> P > -0.16 (peso 0.0350)

======================================================================

Removida aresta Ca kb <= 0.20 -> Al <= 0.22 (peso 0.0364)
Mantida aresta Al <= 0.22 -> Ca kb <= 0.20 (peso 0.0747)

======================================================================

Removida aresta P > -0.16 -> Al <= 0.22 (peso 0.0301)
Mantida aresta Al <= 0.22 -> P > -0.16 (peso 0.0340)

======================================================================

Removida aresta Ca kb > -0.15 -> K > -0.15 (peso 0.0458)
Mantida aresta K > -0.15 -> Ca kb > -0.15 (peso 0.1689)

======================================================================

Removida aresta Si > 0.16 -> Ca kb > -0.15 (peso 0.0343)
Mantida aresta Ca kb > -0.15 -> Si > 0.16 (peso 0.0364)

======================================================================

Removida aresta Si > 0.16 -> Ti ka <= 0.50 (peso 0.0229)
Mantida aresta Ti ka <= 0.50 -> Si > 0.16 (peso 0.0348)

======================================================================

Removida aresta Si > 0.16 -> Fe kb <= -0.23 (peso 0.0294)
Mantida aresta Fe kb <= -0.23 -> Si > 0.16 (peso 0.0319)

======================================================================

Removida aresta Si > 0.16 -> Ca kb <= 0.20 (peso 0.0321)
Mantida aresta Ca kb <= 0.20 -> Si > 0.16 (peso 0.0648)

======================================================================

Removida aresta Fe ka <= -0.44 -> Al > -0.22 (peso 0.0354)
Mantida aresta Al > -0.22 -> Fe ka <= -0.44 (peso 0.0378)

======================================================================

Removida aresta Al > -0.22 -> Ca kb <= 0.20 (peso 0.0335)
Mantida aresta Ca kb <= 0.20 -> Al > -0.22 (peso 0.0368)

======================================================================

Removida aresta sum Fe <= 0.20 -> Al > -0.22 (peso 0.0384)
Mantida aresta Al > -0.22 -> sum Fe <= 0.20 (peso 0.0669)

======================================================================

Removida aresta Ca kb <= 0.20 -> Fe kb > 0.34 (peso 0.0330)
Mantida aresta Fe kb > 0.34 -> Ca kb <= 0.20 (peso 0.0375)

======================================================================

Removida aresta background13 <= 0.14 -> Mn > -0.14 (peso 0.0204)
Mantida aresta Mn > -0.14 -> background13 <= 0.14 (peso 0.0231)

======================================================================

Removida aresta sum Fe <= 0.20 -> Al <= 0.16 (peso 0.0278)
Mantida aresta Al <= 0.16 -> sum Fe <= 0.20 (peso 0.0293)

======================================================================

Removida aresta Fe kb <= -0.23 -> Mn <= 0.37 (peso 0.0173)
Mantida aresta Mn <= 0.37 -> Fe kb <= -0.23 (peso 0.0283)

======================================================================

Removida aresta P > -0.16 -> Cr <= 0.19 (peso 0.0252)
Mantida aresta Cr <= 0.19 -> P > -0.16 (peso 0.0264)

======================================================================

Removida aresta Mn <= 0.37 -> background13 <= 0.18 (peso 0.0172)
Mantida aresta background13 <= 0.18 -> Mn <= 0.37 (peso 0.0243)

======================================================================

Removida aresta Cr > -0.17 -> P <= 0.22 (peso 0.0237)
Mantida aresta P <= 0.22 -> Cr > -0.17 (peso 0.0252)

======================================================================

Removida aresta Cr <= 0.19 -> Al > -0.12 (peso 0.0229)
Mantida aresta Al > -0.12 -> Cr <= 0.19 (peso 0.0244)

======================================================================

Removida aresta Cr <= 0.19 -> sum Fe <= 0.15 (peso 0.0242)
Mantida aresta sum Fe <= 0.15 -> Cr <= 0.19 (peso 0.0270)

======================================================================

Removida aresta Al <= 0.16 -> Cr <= 0.19 (peso 0.0239)
Mantida aresta Cr <= 0.19 -> Al <= 0.16 (peso 0.0506)

======================================================================

Removida aresta Ti kb > 0.20 -> Al <= 0.16 (peso 0.0243)
Mantida aresta Al <= 0.16 -> Ti kb > 0.20 (peso 0.0484)

======================================================================

Removida aresta Ti kb > 0.20 -> Cr > -0.17 (peso 0.0207)
Mantida aresta Cr > -0.17 -> Ti kb > 0.20 (peso 0.0249)

======================================================================

Removida aresta Cr > -0.17 -> sum Fe <= 0.15 (peso 0.0185)
Mantida aresta sum Fe <= 0.15 -> Cr > -0.17 (peso 0.0223)

======================================================================

Removida aresta Cr > -0.17 -> sum Fe > -0.20 (peso 0.0218)
Mantida aresta sum Fe > -0.20 -> Cr > -0.17 (peso 0.0241)

======================================================================

Removida aresta K > -0.02 -> Cr > -0.17 (peso 0.0191)
Mantida aresta Cr > -0.17 -> K > -0.02 (peso 0.0194)

======================================================================

Removida aresta sum Fe > -0.20 -> P > -0.13 (peso 0.0213)
Mantida aresta P > -0.13 -> sum Fe > -0.20 (peso 0.0228)

======================================================================

Removida aresta Cr <= 0.12 -> sum Fe > -0.20 (peso 0.0178)
Mantida aresta sum Fe > -0.20 -> Cr <= 0.12 (peso 0.0187)

======================================================================

Removida aresta K <= 0.21 -> background13 <= 0.14 (peso 0.0183)
Mantida aresta background13 <= 0.14 -> K <= 0.21 (peso 0.0216)

======================================================================

Removida aresta K > -0.02 -> background13 <= 0.18 (peso 0.0182)
Mantida aresta background13 <= 0.18 -> K > -0.02 (peso 0.0183)

======================================================================

Removida aresta Ti ka <= 0.50 -> Ti kb <= 0.37 (peso 0.0124)
Mantida aresta Ti kb <= 0.37 -> Ti ka <= 0.50 (peso 0.0175)

======================================================================

Removida aresta Si <= 0.37 -> P > -0.13 (peso 0.0312)
Mantida aresta P > -0.13 -> Si <= 0.37 (peso 0.0358)

======================================================================

Removida aresta background9 <= 0.12 -> Si <= 0.37 (peso 0.0142)
Mantida aresta Si <= 0.37 -> background9 <= 0.12 (peso 0.0147)

======================================================================

Removida aresta background9 <= 0.12 -> Cr > -0.13 (peso 0.0160)
Mantida aresta Cr > -0.13 -> background9 <= 0.12 (peso 0.0288)

======================================================================

Removida aresta Ca kb > -0.07 -> Al > 0.16 (peso 0.0112)
Mantida aresta Al > 0.16 -> Ca kb > -0.07 (peso 0.0118)

======================================================================

Removida aresta Cr > -0.13 -> background13 <= 0.14 (peso 0.0126)
Mantida aresta background13 <= 0.14 -> Cr > -0.13 (peso 0.0147)

======================================================================


======================================================================
RESUMO DO GRAFO CONSTRUÍDO
======================================================================
Total de arestas iniciais: 518
Total de arestas removidas por bidirecionalidade: 73
Arestas bidirecionais restantes: 0
Total de nós predicados: 82
Total de nós terminais: 2
Métrica utilizada para pesos: Covariance


======================================================================
Processando Grafo - Semente: 1
======================================================================


Total de pares bidirecionais encontrados: 77
Removida aresta Fe ka <= 1.45 -> Ca ka > -0.72 (peso 0.2086)
Mantida aresta Ca ka > -0.72 -> Fe ka <= 1.45 (peso 0.9343)

======================================================================

Removida aresta Ca ka > -0.47 -> Fe ka <= 1.45 (peso 0.1428)
Mantida aresta Fe ka <= 1.45 -> Ca ka > -0.47 (peso 0.8326)

======================================================================

Removida aresta Fe ka <= 1.45 -> Fe ka > -1.50 (peso 0.5510)
Mantida aresta Fe ka > -1.50 -> Fe ka <= 1.45 (peso 0.7022)

======================================================================

Removida aresta Ca ka > -0.47 -> Fe ka > -1.50 (peso 0.1659)
Mantida aresta Fe ka > -1.50 -> Ca ka > -0.47 (peso 0.6361)

======================================================================

Removida aresta Fe ka > -0.44 -> Ca ka > -0.47 (peso 0.1215)
Mantida aresta Ca ka > -0.47 -> Fe ka > -0.44 (peso 0.1385)

======================================================================

Removida aresta Fe ka <= 0.86 -> Fe ka > -1.50 (peso 0.1703)
Mantida aresta Fe ka > -1.50 -> Fe ka <= 0.86 (peso 0.3437)


,Predicate_Cov_Seed_0,Predicate_Cov_Seed_1,Predicate_Cov_Seed_2,Predicate_Cov_Seed_3
0,Ca ka > -0.72,Ca ka > -0.72,Ca ka > -0.72,Ca ka > -0.72
1,Fe ka > -1.50,Fe ka <= 1.45,Fe ka <= 1.45,Fe ka <= 1.45
2,Fe ka <= 1.45,Ca ka > -0.47,Fe ka > -1.50,Fe ka > -1.50
3,Fe ka <= 0.86,Fe ka > -1.50,Ca ka > -0.47,Fe ka <= 0.86
4,Ca ka > -0.47,Fe ka <= 0.86,Fe ka <= 0.86,Ca ka > -0.47
...,...,...,...,...
84,NaN,background8 <= 0.09,sum Fe > -0.11,NaN
85,NaN,Ti kb <= -0.18,Class_A,NaN
86,NaN,sum Fe > -0.11,Class_B,NaN
87,NaN,Class_A,NaN,NaN
88,NaN,Class_B,NaN,NaN

In [10]:
# Somar LRCs de predicados equivalentes entre diferentes seeds
lrc_combined_list = []

for seed in random_seeds:
    lrc_df = lrc_cov_by_seed[seed].copy()
    lrc_combined_list.append(lrc_df) # o append adiciona o dataframe ao final da lista

# Concatenar todos os dataframes
lrc_all_seeds = pd.concat(lrc_combined_list, ignore_index=True) 

# Agrupar por predicado (Node) e somar as LRCs, mantendo Zone, Threshold e Operator
lrc_summed_df = lrc_all_seeds.groupby('Node').agg({ # o .agg pode ser usado para aplicar múltiplas funções de agregação
    'Local_Reaching_Centrality': 'mean', # sum = somando as LRCs, poderia ser média ou outro agregado
    'Zone': 'first',
    'Threshold': 'first',
    'Operator': 'first'
}).reset_index()

# Ordenar pelo valor de LRC somado (maior para menor)
lrc_summed_df = lrc_summed_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
# vamoss pegar so os valore sunicos de lrc_summed_df baseado na zona espectral
lrc_summed_unique_df_cov = lrc_summed_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
#lrc_summed_unique_df_cov = lrc_summed_unique_df_cov.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
lrc_summed_unique_df_cov

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator
0,Ca ka > -0.72,8.987641,Ca ka,-0.72,>
1,Fe ka <= 1.45,6.273448,Fe ka,1.45,<=
2,Mn > -0.35,1.631088,Mn,-0.35,>
3,Fe kb <= 0.57,1.420573,Fe kb,0.57,<=
4,Ti ka > 0.50,1.375891,Ti ka,0.50,>
5,Si > -0.38,1.284130,Si,-0.38,>
6,Ca kb > -0.20,1.264919,Ca kb,-0.20,>
7,K > -0.21,1.013481,K,-0.21,>
8,Al <= 0.22,0.851438,Al,0.22,<=
9,Ti kb > -0.18,0.742334,Ti kb,-0.18,>
10,P > -0.16,0.733612,P,-0.16,>
11,sum Fe <= 0.20,0.724890,sum Fe,0.20,<=
12,Cr <= 0.19,0.642514,Cr,0.19,<=
13,background13 <= 0.18,0.581976,background13,0.18,<=
14,background9 <= 0.12,0.559592,background9,0.12,<=
15,background7 > 0.09,0.485781,background7,0.09,>
16,S > 0.09,0.475286,S,0.09,>
17,background12 <= 0.13,0.471209,background12,0.13,<=
18,Cu > -0.10,0.447047,Cu,-0.10,>
19,background10 <= 0.15,0.441726,background10,0.15,<=
20,Rh L + Ar > -0.15,0.441422,Rh L + Ar,-0.15,>
21,background6 <= 0.10,0.438045,background6,0.10,<=
22,background11 <= 0.19,0.425871,background11,0.19,<=
23,background8 <= 0.09,0.393616,background8,0.09,<=
24,Class_B,0.000000,None,None,None

# **Perturbation**

In [11]:
ycalres = np.where(svm_model[1]['SVC'] == 'A', 1, 0)

In [20]:
import explaining as exp

# LISTA DE SEMENTES A TESTAR
random_seeds = [0, 1, 2, 3]

all_results_pert = {}
training_samples = len(Xcalclass)

# LOOP: PROCESSAR CADA SEMENTE
y_predicted_numeric = pd.Series(y_pred) # predições numéricas do modelo

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando semente: {seed}")
    print(f"{'='*70}\n")
    # Bagging
    bags_result_seed = exp.bagging_predicates(
        zone_sums_df=zone_sums_df,
        y_predicted_numeric=y_predicted_numeric,
        predicates_df=predicates_quantiles[0],
        n_bags=10,
        #n_predicates_per_bag=40,
        n_samples_per_bag=int(training_samples*0.8), # 80 % da base para amostrar (convertido para int)
        min_samples_per_predicate=int(training_samples*0.2), # 20 % da base para limitar (convertido para int)
        replace=False,
        sample_bagging=True,
        predicate_bagging=False,
        random_seed=seed
    )
    # Inserir classe prevista
    for bag_name, pred_dict in bags_result_seed.items(): # iterando sobre cada bag
        for pred_rule, df_info in pred_dict.items():
            df_info['Class_Predicted'] = np.where(df_info['Predicted_Y'] >= 0.5, 'A', 'B') # binarizando com threshold 0.5, A = eut, B = dist

    pert_results_seed = exp.calculate_predicate_perturbation(
        estimator=svm_model[3],
        Xcalclass_prep=Xcalclass_prep,
        folds_struct=bags_result_seed,
        predicates_df=predicates_quantiles[0],
        spectral_cuts=spectral_cuts,
        #perturbation_value=0,
        perturbation_mode='mean', # valores entre 'mean' ou 'min'
        stats_source='full', # full indica usar todas as amostras para calcular estatísticas enquanto que 'fold' usa apenas as amostras do fold atual
        #metric='mean_abs_diff',   # Média com sinal (pode ser negativo)
        aim='classification',
        metric='probability_shift', 
        verbose=True
    )

    # Remove todos os valores iguais a zero de todos os bags em perm_results[bag]["Permutation"] e salva como perm_results_thresholded
    # pert_results_seed_thresholded = {}
    # for bag, df in perm_results_seed.items():
    #     # Verifica se é um DataFrame e se a coluna 'Permutation' existe
    #     if isinstance(df, pd.DataFrame) and 'Permutation' in df.columns:
    #         filtered_df = df[df['Permutation'] > 0].copy()
    #         pert_results_seed_thresholded[bag] = filtered_df
    #     else:
    #         # Se não for DataFrame esperado, apenas copia
    #         pert_results_seed_thresholded[bag] = df

    # Salvar no dicionário principal
    all_results_pert[seed] = {
        'bags_result': bags_result_seed,
        'pert_results_dict': pert_results_seed
    }

# CONSTRUÇÃO DE GRAFOS PARA MÚLTIPLAS SEMENTES (LOOP EXTERNO)
# Dicionário para armazenar grafos
graphs_pert_by_seed = {}

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando Grafo - Semente: {seed}")
    print(f"{'='*70}\n")
    # Construir grafo para esta semente
    DG = exp.build_predicate_graphv2(
        bags_result=all_results_pert[seed]['bags_result'],
        predicate_ranking_dict=all_results_pert[seed]['pert_results_dict'],
        metric_column='Perturbation',  # ou 'Covariance' se mudar a métrica
        random_state=seed,
        show_details=True
    )
    # Armazenar grafo
    graphs_pert_by_seed[seed] = DG  

# Calcular LRC usando a função pronta do explaining.py
lrc_pert_by_seed = {}
for seed in random_seeds:
    DG = graphs_pert_by_seed[seed]
    lrc_pert_df_seed = exp.calculate_lrc_single_graph(DG, predicates_quantiles[0])
    lrc_pert_df_seed['Seed'] = seed  # Adicionar coluna com a semente
    lrc_pert_by_seed[seed] = lrc_pert_df_seed

# junando todas as colunas 'Node' de lrc_by_seed em um único dataframe
lrc_pert_all_seeds_df = pd.DataFrame()
for seed in random_seeds:
    lrc_pert_df_seed = lrc_pert_by_seed[seed].rename(columns={'Node': f'Predicate_pert_Seed_{seed}'})
    lrc_pert_all_seeds_df = pd.concat([lrc_pert_all_seeds_df, lrc_pert_df_seed[[f'Predicate_pert_Seed_{seed}']]], axis=1)

# vamos filtrar lrc_by_seed em cada semente para manter apenas as zonas espectrais únicas com maior LRC em um mesmo dataframe
lrc_pert_unique_by_seed = {}
for seed, lrc_df in lrc_pert_by_seed.items():
    lrc_pert_unique_df = lrc_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
    lrc_pert_unique_df = lrc_pert_unique_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
    lrc_pert_unique_by_seed[seed] = lrc_pert_unique_df

lrc_pert_all_seeds_df # exibindo o dataframe consolidado com predicados de todas as sementes

======================================================================
Processando semente: 0
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 183 | Descartados: 57
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 182 | Descartados: 58
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 181 | Descartados: 59
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 183 | Descartados: 57
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 183 | Descartados: 57
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 181 | Descartados: 59
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 180 | Descartados: 60
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 181 | Descartados: 59
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 183 | Descartados: 57
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 181 | Descartados: 59
======================================================================
PERTURBATION IMPORTANCE PARA PREDICADOS
======================================================================
Tipo de tarefa (aim): classification
Modo de perturbação: mean
Fonte das estatísticas: full
Métrica: probability_shift
Total de folds: 10


[Bag_1] Processando 183 predicados...
  Predicado: background1 > -0.11 (n=101)
    Zona: 17 colunas
    Importance: 0.000382
  Predicado: background1 <= -0.07 (n=51)
    Zona: 17 colunas
    Importance: 0.000384
  Predicado: background1 > -0.07 (n=67)
    Zona: 17 colunas
    Importance: 0.000398
  Predicado: background1 <= 0.09 (n=74)
    Zona: 17 colunas
    Importance: 0.000379
  Predicado: background1 > 0.09 (n=44)
    Zona: 17 colunas
    Importance: 0.000414
  Predicado: background1 <= 0.11 (n=89)
    Zona: 17 colunas
    Importance: 0.000376
  Predicado: background1 > 0.11 (n=29)
    Zona: 17 colunas
    Importance: 0.000442
  Predicado: Al > -0.22 (n=94)
    Zona: 15 colunas
    Importance: 0.002917
  Predicado: Al <= -0.12 (n=47)
    Zona: 15 colunas
    Importance: 0.002445
  Predicado: Al > -0.12 (n=71)
    Zona: 15 colunas
    Importance: 0.003129
  Predicado: Al <= 0.16 (n=71)
    Zona: 15 colunas
    Importance: 0.002035
  Predicado: Al > 0.16 (n=47)
    Zona: 15 colunas
    Importance: 0.004098
  Predicado: Al <= 0.22 (n=95)
    Zona: 15 colunas
    Importance: 0.002052
  Predicado: Si > -0.38 (n=94)
    Zona: 12 colunas
    Importance: 0.018612
  Predicado: Si <= -0.20 (n=49)
    Zona: 12 colunas
    Importance: 0.023853
  Predicado: Si > -0.20 (n=69)
    Zona: 12 colunas
    Importance: 0.022522
  Predicado: Si <= 0.16 (n=71)
    Zona: 12 colunas
    Importance: 0.017473
  Predicado: Si > 0.16 (n=47)
    Zona: 12 colunas
    Importance: 0.031537
  Predicado: Si <= 0.37 (n=93)
    Zona: 12 colunas
    Importance: 0.017045
  Predicado: P <= -0.16 (n=30)
    Zona: 13 colunas
    Importance: 0.004261
  Predicado: P > -0.16 (n=88)
    Zona: 13 colunas
    Importance: 0.003971
  Predicado: P <= -0.13 (n=50)
    Zona: 13 colunas
    Importance: 0.004522
  Predicado: P > -0.13 (n=68)
    Zona: 13 colunas
    Importance: 0.003694
  Predicado: P <= 0.12 (n=69)
    Zona: 13 colunas
    Importance: 0.003787
  Predicado: P > 0.12 (n=49)
    Zona: 13 colunas
    Importance: 0.004408
  Predicado: P <= 0.22 (n=93)
    Zona: 13 colunas
    Importance: 0.003484
  Predicado: background2 > -0.09 (n=96)
    Zona: 5 colunas
    Importance: 0.000219
  Predicado: background2 <= -0.06 (n=43)
    Zona: 5 colunas
    Importance: 0.000292
  Predicado: background2 > -0.06 (n=75)
    Zona: 5 colunas
    Importance: 0.000238
  Predicado: background2 <= 0.06 (n=64)
    Zona: 5 colunas
    Importance: 0.000238
  Predicado: background2 > 0.06 (n=54)
    Zona: 5 colunas
    Importance: 0.000282
  Predicado: background2 <= 0.10 (n=94)
    Zona: 5 colunas
    Importance: 0.000226
  Predicado: S > -0.13 (n=98)
    Zona: 13 colunas
    Importance: 0.000966
  Predicado: S <= -0.09 (n=53)
    Zona: 13 colunas
    Importance: 0.002530
  Predicado: S > -0.09 (n=65)
    Zona: 13 colunas
    Importance: 0.000786
  Predicado: S <= 0.09 (n=71)
    Zona: 13 colunas
    Importance: 0.002006
  Predicado: S > 0.09 (n=47)
    Zona: 13 colunas
    Importance: 0.000910
  Predicado: S <= 0.14 (n=98)
    Zona: 13 colunas
    Importance: 0.001689
  Predicado: background3 > -0.09 (n=92)
    Zona: 6 colunas
    Importance: 0.000096
  Predicado: background3 <= -0.06 (n=49)
    Zona: 6 colunas
    Importance: 0.000112
  Predicado: background3 > -0.06 (n=69)
    Zona: 6 colunas
    Importance: 0.000102
  Predicado: background3 <= 0.06 (n=72)
    Zona: 6 colunas
    Importance: 0.000098
  Predicado: background3 > 0.06 (n=46)
    Zona: 6 colunas
    Importance: 0.000120
  Predicado: background3 <= 0.09 (n=97)
    Zona: 6 colunas
    Importance: 0.000105
  Predicado: Rh L + Ar > -0.15 (n=94)
    Zona: 28 colunas
    Importance: 0.001084
  Predicado: Rh L + Ar <= -0.08 (n=50)
    Zona: 28 colunas
    Importance: 0.001845
  Predicado: Rh L + Ar > -0.08 (n=68)
    Zona: 28 colunas
    Importance: 0.001118
  Predicado: Rh L + Ar <= 0.14 (n=76)
    Zona: 28 colunas
    Importance: 0.001523
  Predicado: Rh L + Ar > 0.14 (n=42)
    Zona: 28 colunas
    Importance: 0.001250
  Predicado: Rh L + Ar <= 0.19 (n=99)
    Zona: 28 colunas
    Importance: 0.001427
  Predicado: background4 > -0.10 (n=94)
    Zona: 6 colunas
    Importance: 0.000268
  Predicado: background4 <= -0.06 (n=47)
    Zona: 6 colunas
    Importance: 0.000264
  Predicado: background4 > -0.06 (n=71)
    Zona: 6 colunas
    Importance: 0.000280
  Predicado: background4 <= 0.08 (n=81)
    Zona: 6 colunas
    Importance: 0.000212
  Predicado: background4 > 0.08 (n=37)
    Zona: 6 colunas
    Importance: 0.000408
  Predicado: background4 <= 0.10 (n=98)
    Zona: 6 colunas
    Importance: 0.000243
  Predicado: K > -0.21 (n=92)
    Zona: 11 colunas
    Importance: 0.000929
  Predicado: K <= -0.15 (n=49)
    Zona: 11 colunas
    Importance: 0.001385
  Predicado: K > -0.15 (n=69)
    Zona: 11 colunas
    Importance: 0.000999
  Predicado: K <= -0.02 (n=73)
    Zona: 11 colunas
    Importance: 0.001158
  Predicado: K > -0.02 (n=45)
    Zona: 11 colunas
    Importance: 0.001161
  Predicado: K <= 0.21 (n=96)
    Zona: 11 colunas
    Importance: 0.001211
  Predicado: background5 > -0.10 (n=101)
    Zona: 6 colunas
    Importance: 0.000139
  Predicado: background5 <= -0.05 (n=47)
    Zona: 6 colunas
    Importance: 0.000213
  Predicado: background5 > -0.05 (n=71)
    Zona: 6 colunas
    Importance: 0.000145
  Predicado: background5 <= 0.07 (n=72)
    Zona: 6 colunas
    Importance: 0.000171
  Predicado: background5 > 0.07 (n=46)
    Zona: 6 colunas
    Importance: 0.000173
  Predicado: background5 <= 0.11 (n=98)
    Zona: 6 colunas
    Importance: 0.000169
  Predicado: Ca ka > -0.72 (n=92)
    Zona: 16 colunas
    Importance: 0.174260
  Predicado: Ca ka <= -0.47 (n=49)
    Zona: 16 colunas
    Importance: 0.339033
  Predicado: Ca ka > -0.47 (n=69)
    Zona: 16 colunas
    Importance: 0.135480
  Predicado: Ca ka <= -0.22 (n=72)
    Zona: 16 colunas
    Importance: 0.275729
  Predicado: Ca ka > -0.22 (n=46)
    Zona: 16 colunas
    Importance: 0.132789
  Predicado: Ca ka <= 0.58 (n=94)
    Zona: 16 colunas
    Importance: 0.228411
  Predicado: Ca kb <= -0.20 (n=30)
    Zona: 16 colunas
    Importance: 0.006828
  Predicado: Ca kb > -0.20 (n=88)
    Zona: 16 colunas
    Importance: 0.006028
  Predicado: Ca kb <= -0.15 (n=48)
    Zona: 16 colunas
    Importance: 0.008277
  Predicado: Ca kb > -0.15 (n=70)
    Zona: 16 colunas
    Importance: 0.004829
  Predicado: Ca kb <= -0.07 (n=69)
    Zona: 16 colunas
    Importance: 0.007899
  Predicado: Ca kb > -0.07 (n=49)
    Zona: 16 colunas
    Importance: 0.003884
  Predicado: Ca kb <= 0.20 (n=94)
    Zona: 16 colunas
    Importance: 0.006557
  Predicado: background6 > -0.13 (n=95)
    Zona: 12 colunas
    Importance: 0.000438
  Predicado: background6 <= -0.08 (n=48)
    Zona: 12 colunas
    Importance: 0.000475
  Predicado: background6 > -0.08 (n=70)
    Zona: 12 colunas
    Importance: 0.000469
  Predicado: background6 <= 0.10 (n=69)
    Zona: 12 colunas
    Importance: 0.000447
  Predicado: background6 > 0.10 (n=49)
    Zona: 12 colunas
    Importance: 0.000505
  Predicado: background6 <= 0.14 (n=92)
    Zona: 12 colunas
    Importance: 0.000444
  Predicado: Ti ka > -0.80 (n=94)
    Zona: 15 colunas
    Importance: 0.039046
  Predicado: Ti ka <= -0.37 (n=51)
    Zona: 15 colunas
    Importance: 0.034725
  Predicado: Ti ka > -0.37 (n=67)
    Zona: 15 colunas
    Importance: 0.046687
  Predicado: Ti ka <= 0.50 (n=72)
    Zona: 15 colunas
    Importance: 0.027958
  Predicado: Ti ka > 0.50 (n=46)
    Zona: 15 colunas
    Importance: 0.062739
  Predicado: Ti ka <= 0.91 (n=94)
    Zona: 15 colunas
    Importance: 0.031205
  Predicado: background7 > -0.16 (n=94)
    Zona: 5 colunas
    Importance: 0.000275
  Predicado: background7 <= -0.09 (n=45)
    Zona: 5 colunas
    Importance: 0.000382
  Predicado: background7 > -0.09 (n=73)
    Zona: 5 colunas
    Importance: 0.000278
  Predicado: background7 <= 0.09 (n=71)
    Zona: 5 colunas
    Importance: 0.000334
  Predicado: background7 > 0.09 (n=47)
    Zona: 5 colunas
    Importance: 0.000294
  Predicado: background7 <= 0.17 (n=94)
    Zona: 5 colunas
    Importance: 0.000307
  Predicado: Ti kb > -0.32 (n=95)
    Zona: 19 colunas
    Importance: 0.003792
  Predicado: Ti kb <= -0.18 (n=52)
    Zona: 19 colunas
    Importance: 0.004858
  Predicado: Ti kb > -0.18 (n=66)
    Zona: 19 colunas
    Importance: 0.004757
  Predicado: Ti kb <= 0.20 (n=69)
    Zona: 19 colunas
    Importance: 0.004002
  Predicado: Ti kb > 0.20 (n=49)
    Zona: 19 colunas
    Importance: 0.005926
  Predicado: Ti kb <= 0.37 (n=93)
    Zona: 19 colunas
    Importance: 0.004191
  Predicado: Cr > -0.17 (n=95)
    Zona: 33 colunas
    Importance: 0.001901
  Predicado: Cr <= -0.13 (n=47)
    Zona: 33 colunas
    Importance: 0.003289
  Predicado: Cr > -0.13 (n=71)
    Zona: 33 colunas
    Importance: 0.001752
  Predicado: Cr <= 0.12 (n=68)
    Zona: 33 colunas
    Importance: 0.002577
  Predicado: Cr > 0.12 (n=50)
    Zona: 33 colunas
    Importance: 0.002075
  Predicado: Cr <= 0.19 (n=93)
    Zona: 33 colunas
    Importance: 0.002252
  Predicado: Mn > -0.35 (n=98)
    Zona: 13 colunas
    Importance: 0.013336
  Predicado: Mn <= -0.23 (n=47)
    Zona: 13 colunas
    Importance: 0.016854
  Predicado: Mn > -0.23 (n=71)
    Zona: 13 colunas
    Importance: 0.012983
  Predicado: Mn <= -0.14 (n=68)
    Zona: 13 colunas
    Importance: 0.014026
  Predicado: Mn > -0.14 (n=50)
    Zona: 13 colunas
    Importance: 0.015203
  Predicado: Mn <= 0.37 (n=94)
    Zona: 13 colunas
    Importance: 0.013166
  Predicado: background8 > -0.12 (n=94)
    Zona: 6 colunas
    Importance: 0.000218
  Predicado: background8 <= -0.07 (n=48)
    Zona: 6 colunas
    Importance: 0.000285
  Predicado: background8 > -0.07 (n=70)
    Zona: 6 colunas
    Importance: 0.000216
  Predicado: background8 <= 0.09 (n=70)
    Zona: 6 colunas
    Importance: 0.000236
  Predicado: background8 > 0.09 (n=48)
    Zona: 6 colunas
    Importance: 0.000257
  Predicado: background8 <= 0.14 (n=96)
    Zona: 6 colunas
    Importance: 0.000258
  Predicado: Fe ka > -1.50 (n=96)
    Zona: 28 colunas
    Importance: 0.049340
  Predicado: Fe ka <= -0.44 (n=43)
    Zona: 28 colunas
    Importance: 0.118753
  Predicado: Fe ka > -0.44 (n=75)
    Zona: 28 colunas
    Importance: 0.046618
  Predicado: Fe ka <= 0.86 (n=70)
    Zona: 28 colunas
    Importance: 0.079906
  Predicado: Fe ka > 0.86 (n=48)
    Zona: 28 colunas
    Importance: 0.062693
  Predicado: Fe ka <= 1.45 (n=95)
    Zona: 28 colunas
    Importance: 0.073184
  Predicado: background9 > -0.11 (n=94)
    Zona: 7 colunas
    Importance: 0.000233
  Predicado: background9 <= -0.08 (n=46)
    Zona: 7 colunas
    Importance: 0.000247
  Predicado: background9 > -0.08 (n=72)
    Zona: 7 colunas
    Importance: 0.000253
  Predicado: background9 <= 0.08 (n=69)
    Zona: 7 colunas
    Importance: 0.000230
  Predicado: background9 > 0.08 (n=49)
    Zona: 7 colunas
    Importance: 0.000279
  Predicado: background9 <= 0.12 (n=96)
    Zona: 7 colunas
    Importance: 0.000251
  Predicado: Fe kb > -0.59 (n=97)
    Zona: 26 colunas
    Importance: 0.012360
  Predicado: Fe kb <= -0.23 (n=46)
    Zona: 26 colunas
    Importance: 0.011773
  Predicado: Fe kb > -0.23 (n=72)
    Zona: 26 colunas
    Importance: 0.013539
  Predicado: Fe kb <= 0.34 (n=70)
    Zona: 26 colunas
    Importance: 0.009013
  Predicado: Fe kb > 0.34 (n=48)
    Zona: 26 colunas
    Importance: 0.018447
  Predicado: Fe kb <= 0.57 (n=94)
    Zona: 26 colunas
    Importance: 0.010255
  Predicado: background10 > -0.13 (n=92)
    Zona: 31 colunas
    Importance: 0.000865
  Predicado: background10 <= -0.10 (n=49)
    Zona: 31 colunas
    Importance: 0.001683
  Predicado: background10 > -0.10 (n=69)
    Zona: 31 colunas
    Importance: 0.000908
  Predicado: background10 <= 0.12 (n=76)
    Zona: 31 colunas
    Importance: 0.001289
  Predicado: background10 > 0.12 (n=42)
    Zona: 31 colunas
    Importance: 0.001122
  Predicado: background10 <= 0.15 (n=94)
    Zona: 31 colunas
    Importance: 0.001230
  Predicado: Cu > -0.13 (n=90)
    Zona: 15 colunas
    Importance: 0.001176
  Predicado: Cu <= -0.10 (n=50)
    Zona: 15 colunas
    Importance: 0.001715
  Predicado: Cu > -0.10 (n=68)
    Zona: 15 colunas
    Importance: 0.001183
  Predicado: Cu <= 0.10 (n=69)
    Zona: 15 colunas
    Importance: 0.001313
  Predicado: Cu > 0.10 (n=49)
    Zona: 15 colunas
    Importance: 0.001543
  Predicado: Cu <= 0.15 (n=95)
    Zona: 15 colunas
    Importance: 0.001215
  Predicado: background11 > -0.15 (n=93)
    Zona: 125 colunas
    Importance: 0.003296
  Predicado: background11 <= -0.12 (n=43)
    Zona: 125 colunas
    Importance: 0.004496
  Predicado: background11 > -0.12 (n=75)
    Zona: 125 colunas
    Importance: 0.003140
  Predicado: background11 <= 0.14 (n=77)
    Zona: 125 colunas
    Importance: 0.003529
  Predicado: background11 > 0.14 (n=41)
    Zona: 125 colunas
    Importance: 0.003832
  Predicado: background11 <= 0.19 (n=97)
    Zona: 125 colunas
    Importance: 0.003809
  Predicado: Fe ka + Ti ka > -0.13 (n=91)
    Zona: 23 colunas
    Importance: 0.000594
  Predicado: Fe ka + Ti ka <= -0.11 (n=46)
    Zona: 23 colunas
    Importance: 0.000627
  Predicado: Fe ka + Ti ka > -0.11 (n=72)
    Zona: 23 colunas
    Importance: 0.000581
  Predicado: Fe ka + Ti ka <= 0.12 (n=74)
    Zona: 23 colunas
    Importance: 0.000598
  Predicado: Fe ka + Ti ka > 0.12 (n=44)
    Zona: 23 colunas
    Importance: 0.000600
  Predicado: Fe ka + Ti ka <= 0.16 (n=97)
    Zona: 23 colunas
    Importance: 0.000559
  Predicado: background12 > -0.14 (n=95)
    Zona: 71 colunas
    Importance: 0.002240
  Predicado: background12 <= -0.11 (n=52)
    Zona: 71 colunas
    Importance: 0.002616
  Predicado: background12 > -0.11 (n=66)
    Zona: 71 colunas
    Importance: 0.001979
  Predicado: background12 <= 0.13 (n=75)
    Zona: 71 colunas
    Importance: 0.002187
  Predicado: background12 > 0.13 (n=43)
    Zona: 71 colunas
    Importance: 0.002387
  Predicado: background12 <= 0.15 (n=90)
    Zona: 71 colunas
    Importance: 0.002326
  Predicado: sum Fe > -0.20 (n=95)
    Zona: 28 colunas
    Importance: 0.001447
  Predicado: sum Fe <= -0.11 (n=45)
    Zona: 28 colunas
    Importance: 0.002505
  Predicado: sum Fe > -0.11 (n=73)
    Zona: 28 colunas
    Importance: 0.001270
  Predicado: sum Fe <= 0.15 (n=66)
    Zona: 28 colunas
    Importance: 0.001992
  Predicado: sum Fe > 0.15 (n=52)
    Zona: 28 colunas
    Importance: 0.001423
  Predicado: sum Fe <= 0.20 (n=93)
    Zona: 28 colunas
    Importance: 0.001703
  Predicado: background13 > -0.15 (n=95)
    Zona: 96 colunas
    Importance: 0.002725
  Predicado: background13 <= 0.11 (n=50)
    Zona: 96 colunas
    Importance: 0.001831
  Predicado: background13 > 0.11 (n=68)
    Zona: 96 colunas
    Importance: 0.003110
  Predicado: background13 <= 0.14 (n=68)
    Zona: 96 colunas
    Importance: 0.001963
  Predicado: background13 > 0.14 (n=50)
    Zona: 96 colunas
    Importance: 0.003391
  Predicado: background13 <= 0.18 (n=93)
    Zona: 96 colunas
    Importance: 0.002222

[Bag_2] Processando 182 predicados...
  Predicado: background1 > -0.11 (n=96)
    Zona: 17 colunas
    Importance: 0.000394
  Predicado: background1 <= -0.07 (n=50)
    Zona: 17 colunas
    Importance: 0.000473
  Predicado: background1 > -0.07 (n=68)
    Zona: 17 colunas
    Importance: 0.000383
  Predicado: background1 <= 0.09 (n=74)
    Zona: 17 colunas
    Importance: 0.000434
  Predicado: background1 > 0.09 (n=44)
    Zona: 17 colunas
    Importance: 0.000400
  Predicado: background1 <= 0.11 (n=90)
    Zona: 17 colunas
    Importance: 0.000417
  Predicado: Al > -0.22 (n=96)
    Zona: 15 colunas
    Importance: 0.003095
  Predicado: Al <= -0.12 (n=44)
    Zona: 15 colunas
    Importance: 0.002633
  Predicado: Al > -0.12 (n=74)
    Zona: 15 colunas
    Importance: 0.003219
  Predicado: Al <= 0.16 (n=71)
    Zona: 15 colunas
    Importance: 0.002120
  Predicado: Al > 0.16 (n=47)
    Zona: 15 colunas
    Importance: 0.004332
  Predicado: Al <= 0.22 (n=92)
    Zona: 15 colunas
    Importance: 0.002062
  Predicado: Si > -0.38 (n=94)
    Zona: 12 colunas
    Importance: 0.016532
  Predicado: Si <= -0.20 (n=49)
    Zona: 12 colunas
    Importance: 0.023950
  Predicado: Si > -0.20 (n=69)
    Zona: 12 colunas
    Importance: 0.019790
  Predicado: Si <= 0.16 (n=70)
    Zona: 12 colunas
    Importance: 0.017754
  Predicado: Si > 0.16 (n=48)
    Zona: 12 colunas
    Importance: 0.027008
  Predicado: Si <= 0.37 (n=94)
    Zona: 12 colunas
    Importance: 0.016670
  Predicado: P > -0.16 (n=91)
    Zona: 13 colunas
    Importance: 0.003309
  Predicado: P <= -0.13 (n=44)
    Zona: 13 colunas
    Importance: 0.004593
  Predicado: P > -0.13 (n=74)
    Zona: 13 colunas
    Importance: 0.003100
  Predicado: P <= 0.12 (n=66)
    Zona: 13 colunas
    Importance: 0.003927
  Predicado: P > 0.12 (n=52)
    Zona: 13 colunas
    Importance: 0.003313
  Predicado: P <= 0.22 (n=95)
    Zona: 13 colunas
    Importance: 0.003612
  Predicado: background2 > -0.09 (n=95)
    Zona: 5 colunas
    Importance: 0.000227
  Predicado: background2 <= -0.06 (n=42)
    Zona: 5 colunas
    Importance: 0.000330
  Predicado: background2 > -0.06 (n=76)
    Zona: 5 colunas
    Importance: 0.000237
  Predicado: background2 <= 0.06 (n=67)
    Zona: 5 colunas
    Importance: 0.000264
  Predicado: background2 > 0.06 (n=51)
    Zona: 5 colunas
    Importance: 0.000278
  Predicado: background2 <= 0.10 (n=95)
    Zona: 5 colunas
    Importance: 0.000248
  Predicado: S > -0.13 (n=98)
    Zona: 13 colunas
    Importance: 0.001038
  Predicado: S <= -0.09 (n=52)
    Zona: 13 colunas
    Importance: 0.002654
  Predicado: S > -0.09 (n=66)
    Zona: 13 colunas
    Importance: 0.000756
  Predicado: S <= 0.09 (n=72)
    Zona: 13 colunas
    Importance: 0.002039
  Predicado: S > 0.09 (n=46)
    Zona: 13 colunas
    Importance: 0.000893
  Predicado: S <= 0.14 (n=95)
    Zona: 13 colunas
    Importance: 0.001747
  Predicado: background3 > -0.09 (n=95)
    Zona: 6 colunas
    Importance: 0.000122
  Predicado: background3 <= -0.06 (n=42)
    Zona: 6 colunas
    Importance: 0.000128
  Predicado: background3 > -0.06 (n=76)
    Zona: 6 colunas
    Importance: 0.000128
  Predicado: background3 <= 0.06 (n=66)
    Zona: 6 colunas
    Importance: 0.000108
  Predicado: background3 > 0.06 (n=52)
    Zona: 6 colunas
    Importance: 0.000153
  Predicado: background3 <= 0.09 (n=93)
    Zona: 6 colunas
    Importance: 0.000117
  Predicado: Rh L + Ar > -0.15 (n=99)
    Zona: 28 colunas
    Importance: 0.001182
  Predicado: Rh L + Ar <= -0.08 (n=40)
    Zona: 28 colunas
    Importance: 0.001835
  Predicado: Rh L + Ar > -0.08 (n=78)
    Zona: 28 colunas

,Predicate_pert_Seed_0,Predicate_pert_Seed_1,Predicate_pert_Seed_2,Predicate_pert_Seed_3
0,Ca ka <= -0.47,Ca ka <= -0.47,Ca ka <= -0.47,Ca ka <= -0.47
1,Ca ka <= -0.22,Ca ka <= -0.22,Ca ka <= -0.22,Ca ka <= -0.22
2,Ca ka <= 0.58,Ca ka <= 0.58,Ca ka <= 0.58,Ca ka <= 0.58
3,Ca ka > -0.72,Ca ka > -0.72,Ca ka > -0.72,Ca ka > -0.72
4,Ca ka > -0.47,Ca ka > -0.47,Ca ka > -0.47,Ca ka > -0.47
...,...,...,...,...
190,NaN,background3 > -0.06,background3 > -0.09,background3 <= 0.06
191,NaN,Class_A,background3 > -0.06,Class_A
192,NaN,Class_B,background3 <= 0.06,Class_B
193,NaN,NaN,Class_A,NaN
194,NaN,NaN,Class_B,NaN

In [21]:
all_results_pert[0]['pert_results_dict']['Bag_1']

                Predicate  Perturbation
0          Ca ka <= -0.47      0.339033
1          Ca ka <= -0.22      0.275729
2           Ca ka <= 0.58      0.228411
3           Ca ka > -0.72      0.174260
4           Ca ka > -0.47      0.135480
..                    ...           ...
178  background3 <= -0.06      0.000112
179   background3 <= 0.09      0.000105
180   background3 > -0.06      0.000102
181   background3 <= 0.06      0.000098
182   background3 > -0.09      0.000096

[183 rows x 2 columns]

In [22]:
# Somar LRCs de predicados equivalentes entre diferentes seeds
lrc_combined_list = []

for seed in random_seeds:
    lrc_df = lrc_pert_by_seed[seed].copy()
    lrc_combined_list.append(lrc_df) # o append adiciona o dataframe ao final da lista

# Concatenar todos os dataframes
lrc_all_seeds = pd.concat(lrc_combined_list, ignore_index=True) 

# Agrupar por predicado (Node) e somar as LRCs, mantendo Zone, Threshold e Operator
lrc_summed_df = lrc_all_seeds.groupby('Node').agg({ # o .agg pode ser usado para aplicar múltiplas funções de agregação
    'Local_Reaching_Centrality': 'mean', # sum = somando as LRCs, poderia ser média ou outro agregado
    'Zone': 'first',
    'Threshold': 'first',
    'Operator': 'first'
}).reset_index()

# Ordenar pelo valor de LRC somado (maior para menor)
lrc_summed_df = lrc_summed_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
# vamoss pegar so os valore sunicos de lrc_summed_df baseado na zona espectral
lrc_summed_unique_df_pert = lrc_summed_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
lrc_summed_unique_df_pert = lrc_summed_unique_df_pert.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
lrc_summed_unique_df_pert

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator
0,Ca ka <= -0.47,23.795251,Ca ka,-0.47,<=
1,Fe ka <= 0.86,4.977991,Fe ka,0.86,<=
2,Ti ka > 0.50,3.325698,Ti ka,0.50,>
3,Si > 0.16,1.667675,Si,0.16,>
4,Fe kb > 0.34,1.147021,Fe kb,0.34,>
5,Mn <= -0.23,1.061102,Mn,-0.23,<=
6,Ca kb <= -0.15,0.480893,Ca kb,-0.15,<=
7,Ti kb <= -0.18,0.262239,Ti kb,-0.18,<=
8,P <= -0.13,0.148767,P,-0.13,<=
9,Al > 0.16,0.146360,Al,0.16,>
10,background11 <= -0.12,0.145958,background11,-0.12,<=
11,background13 > 0.11,0.127444,background13,0.11,>
12,Cr <= -0.13,0.121273,Cr,-0.13,<=
13,background12 <= -0.11,0.115835,background12,-0.11,<=
14,sum Fe <= -0.11,0.103234,sum Fe,-0.11,<=
15,S <= -0.09,0.100040,S,-0.09,<=
16,Rh L + Ar <= -0.08,0.097344,Rh L + Ar,-0.08,<=
17,Cu > 0.10,0.095055,Cu,0.10,>
18,K <= -0.21,0.091902,K,-0.21,<=
19,background10 <= -0.10,0.090908,background10,-0.10,<=
20,Fe ka + Ti ka <= -0.11,0.021169,Fe ka + Ti ka,-0.11,<=
21,background6 <= -0.08,0.013542,background6,-0.08,<=
22,background1 <= -0.07,0.010020,background1,-0.07,<=
23,background7 <= -0.09,0.009079,background7,-0.09,<=
24,background4 > 0.08,0.007590,background4,0.08,>
25,background9 > 0.08,0.007436,background9,0.08,>
26,background2 <= -0.06,0.007211,background2,-0.06,<=
27,background8 > 0.09,0.006624,background8,0.09,>
28,background5 <= -0.05,0.006390,background5,-0.05,<=
29,background3 > 0.06,0.002354,background3,0.06,>
30,Class_A,0.000000,None,None,None

In [23]:
lrc_all_seeds

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator,Seed
0,Ca ka <= -0.47,22.935810,Ca ka,-0.47,<=,0
1,Ca ka <= -0.22,18.560374,Ca ka,-0.22,<=,0
2,Ca ka <= 0.58,14.853219,Ca ka,0.58,<=,0
3,Ca ka > -0.72,11.721622,Ca ka,-0.72,>,0
4,Ca ka > -0.47,9.185170,Ca ka,-0.47,>,0
...,...,...,...,...,...,...
766,background5 > -0.10,0.000957,background5,-0.10,>,3
767,background5 > 0.07,0.000945,background5,0.07,>,3
768,background3 <= 0.06,0.000696,background3,0.06,<=,3
769,Class_A,0.000000,None,None,None,3
770,Class_B,0.000000,None,None,None,3

In [34]:
import numpy as np

max_len = max(
    len(pvector_unique_df['Zone']),
    len(shap_unique_df['Zone']),
    len(lrc_summed_unique_df_pert['Zone']),
    len(lrc_summed_unique_df_cov['Zone'])
)

def pad_list(lst, length):
    return list(lst) + [None] * (length - len(lst))

features_importance = pd.DataFrame({
    'SVM_pvector': pad_list(pvector_unique_df['Zone'], max_len),
    'Shap': pad_list(shap_unique_df['Zone'], max_len),
    'LRC_perturbation' : pad_list(lrc_summed_unique_df_pert['Zone'], max_len),
    'LRC_covariance' : pad_list(lrc_summed_unique_df_cov['Zone'], max_len),
})

features_importance.to_csv('feature_importance.csv', index=False, sep=';')
features_importance

      SVM_pvector           Shap LRC_perturbation LRC_covariance
0           Ca ka          Ca ka            Ca ka          Ca ka
1           Fe ka          Fe ka            Fe ka          Fe ka
2           Ca kb          Ti ka            Ti ka             Mn
3              Si             Si               Si          Fe kb
4           Fe kb             Mn            Fe kb          Ti ka
5           Ti ka          Fe kb               Mn             Si
6              Mn             Cu            Ca kb          Ca kb
7          sum Fe   background12            Ti kb              K
8              Al         sum Fe                P             Al
9              Cr              P               Al          Ti kb
10              P   background10     background11              P
11              S             Al     background13         sum Fe
12   background12          Ca kb               Cr             Cr
13   background11   background11     background12   background13
14   background13  Fe ka + Ti ka           sum Fe    background9
15    background4   background13                S    background7
16   background10    background1        Rh L + Ar              S
17             Cu              K               Cu   background12
18      Rh L + Ar    background5                K             Cu
19    background7      Rh L + Ar     background10   background10
20          Ti kb    background4    Fe ka + Ti ka      Rh L + Ar
21  Fe ka + Ti ka    background6      background6    background6
22    background9    background7      background1   background11
23    background2          Ti kb      background7    background8
24    background6              S      background4           None
25    background8    background3      background9           None
26              K    background2      background2           None
27    background5             Cr      background8           None
28    background1    background9      background5           None
29    background3    background8      background3           None
30           None           None             None           None

In [35]:
# RBO (Rank-Biased Overlap) para comparar rankings
import rbo
rbo_results = {}
reference_list = [x for x in features_importance['SVM_pvector'].tolist() if x is not None]
methods = ['Shap', 'LRC_covariance', 'LRC_perturbation']
for method in methods:
    compare_list = [x for x in features_importance[method].tolist() if x is not None]
    # Truncate both lists to the same length (minimum of both)
    min_len = min(len(reference_list), len(compare_list))
    ref_trunc = reference_list[:min_len]
    cmp_trunc = compare_list[:min_len]
    score = rbo.RankingSimilarity(ref_trunc, cmp_trunc).rbo(p=0.7, k=10)
    rbo_results[method] = score
rbo_results = pd.DataFrame(list(rbo_results.items()), columns=['Method','RBO_Score'])
rbo_results.insert(0, 'Reference', 'pvector')
rbo_results.sort_values(by='RBO_Score', ascending=False, inplace=True)
rbo_results.to_csv('rbo_rank.csv', index=False, sep=';')
rbo_results

  Reference            Method  RBO_Score
2   pvector  LRC_perturbation   0.864865
0   pvector              Shap   0.841118
1   pvector    LRC_covariance   0.826656