## Loading data

In [32]:
# Importing the necessary libraries
import pandas as pd
import numpy as np
import kennard_stone as ks
pd.options.plotting.backend = 'plotly'  # setting plotly as the backend for pandas plotting

# Add parent directory to sys.path so local module 'synthetic' (one level up) can be imported
import sys
from pathlib import Path # for path manipulations
parent_dir = Path.cwd().parent.parent.resolve() # move two levels up from current working directory
if str(parent_dir) not in sys.path: # check to avoid duplicates
    sys.path.insert(0, str(parent_dir)) # insert at the start of sys.path to prioritize local modules

# Loading a soil spectral dataset based on X-ray fluorescence (XRF)
data_complete = pd.read_csv(f'{parent_dir}/XRF_databases/forage/plsda/forage.csv', sep=';') # local copy of Toledo 2022 dataset (os ... indica para omitir o caminho longo)
data = data_complete.loc[:, '1.4':'20.81']

# Split dataset by class and create calibration/prediction sets using Kennard-Stone (as in original pipeline)
data_A = data_complete[data_complete['Class'] == 'A'].reset_index(drop=True)
data_B = data_complete[data_complete['Class'] == 'B'].reset_index(drop=True)

# splitting the data into calibration and prediction sets by kennard-stone algorithm
XA_cal, XA_pred = ks.train_test_split(data_A.loc[:, '1.4':'20.81'], test_size=0.30)  # class A
XA_cal = XA_cal.reset_index(drop=True)
XA_pred = XA_pred.reset_index(drop=True)

XB_cal, XB_pred = ks.train_test_split(data_B.loc[:, '1.4':'20.81'], test_size=0.30)  # class B
XB_cal = XB_cal.reset_index(drop=True)
XB_pred = XB_pred.reset_index(drop=True)

Xcalclass = pd.concat([XA_cal, XB_cal], axis=0).reset_index(drop=True)  # concatenating both classes
Xpredclass = pd.concat([XA_pred, XB_pred], axis=0).reset_index(drop=True)
ycalclass = pd.Series(['A']*XA_cal.shape[0] + ['B']*XB_cal.shape[0])  # target for calibration set
ypredclass = pd.Series(['A']*XA_pred.shape[0] + ['B']*XB_pred.shape[0])  # target for prediction set

# preprocessings
import preprocessings as prepr  # preprocessing methods for XRF data

Xcalclass_prep, mean_calclass, mean_calclass_poisson  = prepr.poisson(Xcalclass, mc=True)
Xpredclass_prep = ((Xpredclass/np.sqrt(mean_calclass)) - mean_calclass_poisson)

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning:

'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.

2026-02-02 07:36:49,658 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning:

'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.

2026-02-02 07:36:49,670 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning:

'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning:

'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.

2026-02-02 07:36:49,706 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning:

'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.

2026-02-02 07:36:49,755 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning:

'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.

In [33]:
from modeling import svm_optimized

svm_model = svm_optimized(Xcalclass_prep, ycalclass, Xpredclass_prep, ypredclass, aim='classification', kernel='rbf')
svm_model[0]

,Model,Accuracy Cal,Sensitivity Cal,Specificity Cal,CM Cal,Accuracy Pred,Sensitivity Pred,Specificity Pred,CM Pred
0,SVC,1.0,1.0,1.0,"[[40, 0], [0, 95]]",1.0,1.0,1.0,"[[18, 0], [0, 42]]"

In [34]:
svm_model[4]

          SVC
0    0.007499
1    0.014351
2    0.019990
3    0.003274
4    0.009859
..        ...
130  0.996488
131  0.983934
132  0.995687
133  0.983956
134  0.983933

[135 rows x 1 columns]

In [35]:
# calculando a covariancia entre cada variável espectral e a predição do modelo SVM
cov_scores = []
y_pred = svm_model[4]['SVC'].values # using the continuous predictions from SVM, extracting as 1D array
for col in Xcalclass_prep.columns:
    x_values = Xcalclass_prep[col].values
    covariance = np.cov(x_values, y_pred)[0, 1] # covariance between x and y
    cov_scores.append(covariance)
cov_scores_df = pd.DataFrame(cov_scores, index=Xcalclass_prep.columns, columns=['Covariance'])
cov_scores_df = np.abs(cov_scores_df)
cov_scores_df.plot()

In [36]:
X_sv = svm_model[3].support_vectors_            # shape (n_SV, n_features)
alpha_dual = svm_model[3].dual_coef_.ravel()    # shape (n_SV,)

# Calculando os coeficientes p usando os vetores de suporte e os multiplicadores de Lagrange
pvetor = pd.DataFrame({'energia' : Xcalclass.columns,
                       'importance': (X_sv.T) @ alpha_dual})
pvetor['importance'] = np.abs(pvetor['importance'])
pvetor['importance'].plot()

In [ ]:
# establishing spectral cuts based on expert knowledge of XRF spectra
spectral_cuts = [
('Al', 1.40, 1.63),
('Si', 1.63, 1.86),
('P', 1.86, 2.16),
('S', 2.16, 2.44),
('Rh L + Ar', 2.44, 3.10),
('K', 3.10, 3.46),
('Ca ka', 3.46, 3.86),
('Ca kb', 3.86, 4.16),
('background1', 4.14, 4.37),
('Ti ka', 4.37, 4.66),
('Ti kb', 4.66, 5.08),
('background2', 5.08, 5.72),
('Mn', 5.72, 6.10),
('Fe ka', 6.10, 6.76),
('Fe kb', 6.76, 7.20),
('Ni', 7.20, 7.69),
('background3', 7.69, 13.10),
('sum Fe' , 13.10, 13.63),
('background4', 13.63, 18.0),
('Compton scattering', 18.0, 19.70),
('Rayleight scattering', 19.70, 20.80)
]

import explaining as exp
spectral_zones_class = exp.extract_spectral_zones(Xcalclass_prep, spectral_cuts)
zone_sums_df = exp.aggregate_spectral_zones(spectral_zones_class, aggregator='extreme')
predicates_quantiles = exp.predicates_by_quantiles(zone_sums_df, [0.2, 0.4, 0.6, 0.8])
co_occurrence_matrix_df = predicates_quantiles[2]
predicate_info_dict = exp.create_predicate_info_dict(
    predicates_df=predicates_quantiles[0],
    predicate_indicator_df=predicates_quantiles[1],
    zone_aggregated_df=zone_sums_df,
    y_predicted_numeric=y_pred
)

## Pvector and SHAP

In [40]:
# VIP scores por energia
pvector_df = pd.DataFrame({
    'energy': pvetor['energia'],
    'Pvector': pvetor['importance'].values
})
pvector_df = pvector_df.sort_values(by='Pvector', ascending=False).reset_index(drop=True)
energy_to_zone_vip = {}
for zone_name, start, end in spectral_cuts:
    for e in pvector_df['energy']:
        ef = float(e)
        if start <= ef <= end:
            energy_to_zone_vip[e] = zone_name
pvector_df['Zone'] = pvector_df['energy'].map(energy_to_zone_vip)
pvector_unique_df = pvector_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
#shap_unique_df = pd.read_csv('shap_forage.csv', sep=';') # loading previously saved shap_unique_df
pvector_unique_df

   energy    Pvector                  Zone
0    6.42  29.020377                 Fe ka
1     3.7  21.276746                 Ca ka
2    1.74  20.460692                    Si
3    3.34  12.997443                     K
4    4.02   7.862402                 Ca kb
5    4.52   7.835278                 Ti ka
6    7.08   7.213706                 Fe kb
7    2.62   5.597003             Rh L + Ar
8    1.86   3.167416                     P
9    2.28   2.214821                     S
10  13.41   2.154293                sum Fe
11   1.62   2.151909                    Al
12   4.94   2.032520                 Ti kb
13   7.54   1.425007                    Ni
14   5.92   1.240119                    Mn
15  19.39   1.124331    Compton scattering
16  11.95   1.122248           background3
17  20.31   0.974562  Rayleight scattering
18  15.41   0.831623           background4
19   4.14   0.743773           background1
20   5.12   0.699431           background2
21  20.81   0.005513                   NaN

In [42]:
pvector_df = pd.DataFrame({
    'energy': pvetor['energia'],
    'Pvector': pvetor['importance'].values
})
pvector_df.sort_values(by='Pvector', ascending=False, inplace=True)#.reset_index(drop=True)
energy_to_zone_vip = {}
for zone_name, start, end in spectral_cuts:
    for e in pvector_df['energy']:
        ef = float(e)
        if start <= ef <= end:
            energy_to_zone_vip[e] = zone_name
pvector_df['Zone'] = pvector_df['energy'].map(energy_to_zone_vip)
pvector_unique_df = pvector_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
#pvector_unique_df = pvector_unique_df.sort_values(by='Pvector', ascending=False).reset_index(drop=True)
#shap_unique_df = pd.read_csv('shap_forage.csv', sep=';') # loading previously saved shap_unique_df
pvector_unique_df

   energy    Pvector                  Zone
0    6.42  29.020377                 Fe ka
1     3.7  21.276746                 Ca ka
2    1.74  20.460692                    Si
3    3.34  12.997443                     K
4    4.02   7.862402                 Ca kb
5    4.52   7.835278                 Ti ka
6    7.08   7.213706                 Fe kb
7    2.62   5.597003             Rh L + Ar
8    1.86   3.167416                     P
9    2.28   2.214821                     S
10  13.41   2.154293                sum Fe
11   1.62   2.151909                    Al
12   4.94   2.032520                 Ti kb
13   7.54   1.425007                    Ni
14   5.92   1.240119                    Mn
15  19.39   1.124331    Compton scattering
16  11.95   1.122248           background3
17  20.31   0.974562  Rayleight scattering
18  15.41   0.831623           background4
19   4.14   0.743773           background1
20   5.12   0.699431           background2
21  20.81   0.005513                   NaN

# **bagging - covariance**

In [43]:
import explaining as exp

# LISTA DE SEMENTES A TESTAR
random_seeds = [0, 1, 2, 3]

all_results_cov = {}
training_samples = len(Xcalclass)

# LOOP: PROCESSAR CADA SEMENTE
y_predicted_numeric = pd.Series(y_pred) # predições numéricas do modelo

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando semente: {seed}")
    print(f"{'='*70}\n")
    # Bagging
    bags_result_seed = exp.bagging_predicates(
        zone_sums_df=zone_sums_df,
        y_predicted_numeric=y_predicted_numeric,
        predicates_df=predicates_quantiles[0],
        n_bags=10,
        #n_predicates_per_bag=40,
        n_samples_per_bag=int(training_samples*0.8), # 80 % da base para amostrar (convertido para int)
        min_samples_per_predicate=int(training_samples*0.2), # 20 % da base para limitar (convertido para int)
        replace=False,
        sample_bagging=True,
        predicate_bagging=False,
        random_seed=seed
    )
    
    # Inserir classe prevista
    for bag_name, pred_dict in bags_result_seed.items(): # iterando sobre cada bag
        for pred_rule, df_info in pred_dict.items():
            df_info['Class_Predicted'] = np.where(df_info['Predicted_Y'] >= 0.5, 'A', 'B') # binarizando com threshold 0.5, A = eut, B = dist
    
    # Calcular MI
    cov_results_dict_seed = exp.calculate_predicate_metrics(
        bags_result=bags_result_seed,
        metric='covariance', # covariance ou mutual_information
        threshold=0.01, # threshold para cortar predicados irrelevantes
        n_neighbors=5
    )
    
    # Salvar no dicionário principal
    all_results_cov[seed] = {
        'bags_result': bags_result_seed,
        'cov_results_dict': cov_results_dict_seed
    }

# CONSTRUÇÃO DE GRAFOS PARA MÚLTIPLAS SEMENTES (LOOP EXTERNO)
# Dicionário para armazenar grafos
graphs_by_seed = {}

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando Grafo - Semente: {seed}")
    print(f"{'='*70}\n")
    # Construir grafo para esta semente
    DG = exp.build_predicate_graphv2(
        bags_result=all_results_cov[seed]['bags_result'],
        predicate_ranking_dict=all_results_cov[seed]['cov_results_dict'],
        metric_column='Covariance',  # ou 'Covariance' se mudar a métrica
        random_state=seed,
        show_details=True
    )
    # Armazenar grafo
    graphs_by_seed[seed] = DG

# Calcular LRC usando a função pronta do explaining.py
lrc_cov_by_seed = {}
for seed in random_seeds:
    DG = graphs_by_seed[seed]
    lrc_cov_df_seed = exp.calculate_lrc_single_graph(DG, predicates_quantiles[0])
    lrc_cov_df_seed['Seed'] = seed  # Adicionar coluna com a semente
    lrc_cov_by_seed[seed] = lrc_cov_df_seed

# junando todas as colunas 'Node' de lrc_by_seed em um único dataframe
lrc_cov_all_seeds_df = pd.DataFrame()
for seed in random_seeds:
    lrc_cov_df_seed = lrc_cov_by_seed[seed].rename(columns={'Node': f'Predicate_Cov_Seed_{seed}'})
    lrc_cov_all_seeds_df = pd.concat([lrc_cov_all_seeds_df, lrc_cov_df_seed[[f'Predicate_Cov_Seed_{seed}']]], axis=1)

# vamos filtrar lrc_by_seed em cada semente para manter apenas as zonas espectrais únicas com maior LRC em um mesmo dataframe
lrc_cov_unique_by_seed = {}
for seed, lrc_df in lrc_cov_by_seed.items():
    lrc_cov_unique_df = lrc_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
    lrc_cov_unique_df = lrc_cov_unique_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
    lrc_cov_unique_by_seed[seed] = lrc_cov_unique_df

lrc_cov_all_seeds_df # exibindo o dataframe consolidado com predicados de todas as sementes

======================================================================
Processando semente: 0
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando semente: 1
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 127 | Descartados: 41
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 127 | Descartados: 41
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 127 | Descartados: 41
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando semente: 2
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 128 | Descartados: 40
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 127 | Descartados: 41
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 127 | Descartados: 41
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando semente: 3
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 127 | Descartados: 41
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 127 | Descartados: 41
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando Grafo - Semente: 0
======================================================================


Total de pares bidirecionais encontrados: 96
Removida aresta Fe ka > -0.89 -> Fe ka > -1.49 (peso 0.9112)
Mantida aresta Fe ka > -1.49 -> Fe ka > -0.89 (peso 8.5170)

======================================================================

Removida aresta Si > -0.73 -> Si > -1.10 (peso 1.7142)
Mantida aresta Si > -1.10 -> Si > -0.73 (peso 2.2983)

======================================================================

Removida aresta Si > -1.10 -> Ca ka <= 1.96 (peso 1.1517)
Mantida aresta Ca ka <= 1.96 -> Si > -1.10 (peso 1.7881)

======================================================================

Removida aresta K > -2.69 -> Si > -1.10 (peso 1.1518)
Mantida aresta Si > -1.10 -> K > -2.69 (peso 2.2449)

======================================================================

Removida aresta Si > -0.73 -> Ca ka <= 1.96 (peso 1.1385)
Mantida aresta Ca ka <= 1.96 -> Si > -0.73 (peso 1.7546)

======================================================================

Removida aresta K > -2.69 -> Si > -0.73 (peso 0.5650)
Mantida aresta Si > -0.73 -> K > -2.69 (peso 0.5681)

======================================================================

Removida aresta Ca ka <= 0.86 -> K > -2.69 (peso 0.9132)
Mantida aresta K > -2.69 -> Ca ka <= 0.86 (peso 2.6455)

======================================================================

Removida aresta K <= 2.49 -> Ca ka <= 0.86 (peso 0.5113)
Mantida aresta Ca ka <= 0.86 -> K <= 2.49 (peso 2.3287)

======================================================================

Removida aresta Si > -0.34 -> K <= 2.49 (peso 0.8123)
Mantida aresta K <= 2.49 -> Si > -0.34 (peso 1.7142)

======================================================================

Removida aresta K > -0.94 -> Si > -0.34 (peso 1.5212)
Mantida aresta Si > -0.34 -> K > -0.94 (peso 1.5841)

======================================================================

Removida aresta Ca ka > -2.11 -> K > -0.94 (peso 0.3085)
Mantida aresta K > -0.94 -> Ca ka > -2.11 (peso 0.9858)

======================================================================

Removida aresta Ti ka > -0.34 -> Ca ka > -2.11 (peso 0.2499)
Mantida aresta Ca ka > -2.11 -> Ti ka > -0.34 (peso 0.8220)

======================================================================

Removida aresta Ca ka > -2.11 -> Ti ka > -0.40 (peso 0.2292)
Mantida aresta Ti ka > -0.40 -> Ca ka > -2.11 (peso 0.2592)

======================================================================

Removida aresta Ca ka > -2.11 -> Si <= 1.59 (peso 0.2529)
Mantida aresta Si <= 1.59 -> Ca ka > -2.11 (peso 0.2730)

======================================================================

Removida aresta Ca ka <= -0.97 -> Fe kb > -0.31 (peso 0.2322)
Mantida aresta Fe kb > -0.31 -> Ca ka <= -0.97 (peso 0.4849)

======================================================================

Removida aresta Ti ka > -0.40 -> Ca ka <= -0.97 (peso 0.2389)
Mantida aresta Ca ka <= -0.97 -> Ti ka > -0.40 (peso 0.2456)

======================================================================

Removida aresta Rh L + Ar > -0.13 -> Ca ka <= -0.97 (peso 0.2131)
Mantida aresta Ca ka <= -0.97 -> Rh L + Ar > -0.13 (peso 0.4447)

======================================================================

Removida aresta Fe kb > -0.40 -> Ca ka <= -0.97 (peso 0.2346)
Mantida aresta Ca ka <= -0.97 -> Fe kb > -0.40 (peso 0.2371)

======================================================================

Removida aresta Rh L + Ar > -0.78 -> Ca ka <= -0.97 (peso 0.2176)
Mantida aresta Ca ka <= -0.97 -> Rh L + Ar > -0.78 (peso 0.2332)

======================================================================

Removida aresta Rh L + Ar > -0.42 -> Ca ka <= -0.97 (peso 0.2106)
Mantida aresta Ca ka <= -0.97 -> Rh L + Ar > -0.42 (peso 0.2209)

======================================================================

Removida aresta Ti ka > -0.40 -> Ti ka > -0.34 (peso 0.5253)
Mantida aresta Ti ka > -0.34 -> Ti ka > -0.40 (peso 1.2980)

======================================================================

Removida aresta Si <= 1.59 -> Ti ka > -0.40 (peso 0.2532)
Mantida aresta Ti ka > -0.40 -> Si <= 1.59 (peso 0.2616)

======================================================================

Removida aresta Fe kb > -0.31 -> Ca kb <= 0.69 (peso 0.4504)
Mantida aresta Ca kb <= 0.69 -> Fe kb > -0.31 (peso 0.4830)

======================================================================

Removida aresta Ca kb <= 0.69 -> Fe kb > -0.40 (peso 0.4792)
Mantida aresta Fe kb > -0.40 -> Ca kb <= 0.69 (peso 0.4820)

======================================================================

Removida aresta Si <= 1.59 -> Rh L + Ar > -0.42 (peso 0.3257)
Mantida aresta Rh L + Ar > -0.42 -> Si <= 1.59 (peso 0.6752)

======================================================================

Removida aresta Fe kb > -0.40 -> Rh L + Ar > -0.42 (peso 0.2061)
Mantida aresta Rh L + Ar > -0.42 -> Fe kb > -0.40 (peso 0.2584)

======================================================================

Removida aresta Si <= 1.59 -> Ca kb <= 0.31 (peso 0.1950)
Mantida aresta Ca kb <= 0.31 -> Si <= 1.59 (peso 0.3908)

======================================================================

Removida aresta Si <= 1.59 -> Fe kb > -0.31 (peso 0.1974)
Mantida aresta Fe kb > -0.31 -> Si <= 1.59 (peso 0.2262)

======================================================================

Removida aresta Fe kb > -0.31 -> Fe kb > -0.40 (peso 0.6441)
Mantida aresta Fe kb > -0.40 -> Fe kb > -0.31 (peso 0.6637)

======================================================================

Removida aresta Fe kb > -0.40 -> Ti ka > -0.26 (peso 0.1914)
Mantida aresta Ti ka > -0.26 -> Fe kb > -0.40 (peso 0.2137)

======================================================================

Removida aresta Fe kb > -0.31 -> Rh L + Ar > -0.13 (peso 0.1956)
Mantida aresta Rh L + Ar > -0.13 -> Fe kb > -0.31 (peso 0.2259)

======================================================================

Removida aresta Rh L + Ar > -0.78 -> Rh L + Ar > -0.13 (peso 0.2678)
Mantida aresta Rh L + Ar > -0.13 -> Rh L + Ar > -0.78 (peso 0.3959)

======================================================================

Removida aresta Ti ka > -0.26 -> Ca kb <= 0.31 (peso 0.2011)
Mantida aresta Ca kb <= 0.31 -> Ti ka > -0.26 (peso 0.3810)

======================================================================

Removida aresta Fe kb > -0.23 -> Ca kb <= 0.31 (peso 0.3989)
Mantida aresta Ca kb <= 0.31 -> Fe kb > -0.23 (peso 0.7776)

======================================================================

Removida aresta Ca kb <= 0.31 -> K <= 0.94 (peso 0.1790)
Mantida aresta K <= 0.94 -> Ca kb <= 0.31 (peso 0.4021)

======================================================================

Removida aresta Rh L + Ar > -0.78 -> Ti ka > -0.26 (peso 0.4203)
Mantida aresta Ti ka > -0.26 -> Rh L + Ar > -0.78 (peso 0.5604)

======================================================================

Removida aresta K <= 0.94 -> Rh L + Ar > -0.78 (peso 0.1323)
Mantida aresta Rh L + Ar > -0.78 -> K <= 0.94 (peso 0.1586)

======================================================================

Removida aresta Fe kb > -0.23 -> K <= 0.94 (peso 0.1446)
Mantida aresta K <= 0.94 -> Fe kb > -0.23 (peso 0.3571)

======================================================================

Removida aresta Ca kb > -0.79 -> Fe ka <= 0.50 (peso 0.2119)
Mantida aresta Fe ka <= 0.50 -> Ca kb > -0.79 (peso 0.3576)

======================================================================

Removida aresta Ca kb <= -0.30 -> Fe ka <= 0.50 (peso 0.1887)
Mantida aresta Fe ka <= 0.50 -> Ca kb <= -0.30 (peso 0.3240)

======================================================================

Removida aresta Ca kb <= -0.30 -> Ca kb > -0.79 (peso 0.3018)
Mantida aresta Ca kb > -0.79 -> Ca kb <= -0.30 (peso 0.4256)

======================================================================

Removida aresta K > 0.94 -> Al > -0.33 (peso 0.0740)
Mantida aresta Al > -0.33 -> K > 0.94 (peso 0.1489)

======================================================================

Removida aresta Ti kb > -0.16 -> K > 0.94 (peso 0.0490)
Mantida aresta K > 0.94 -> Ti kb > -0.16 (peso 0.1140)

======================================================================

Removida aresta P > 0.26 -> Al > -0.33 (peso 0.0832)
Mantida aresta Al > -0.33 -> P > 0.26 (peso 0.2458)

======================================================================

Removida aresta P <= 0.51 -> P > 0.26 (peso 0.0649)
Mantida aresta P > 0.26 -> P <= 0.51 (peso 0.1439)

======================================================================

Removida aresta Al <= 0.34 -> P <= 0.51 (peso 0.0504)
Mantida aresta P <= 0.51 -> Al <= 0.34 (peso 0.1157)

======================================================================

Removida aresta Al > -0.17 -> P <= 0.51 (peso 0.0619)
Mantida aresta P <= 0.51 -> Al > -0.17 (peso 0.2548)

======================================================================

Removida aresta P > 0.26 -> Al > -0.17 (peso 0.0643)
Mantida aresta Al > -0.17 -> P > 0.26 (peso 0.1184)

======================================================================

Removida aresta Al <= 0.34 -> P > 0.26 (peso 0.0568)
Mantida aresta P > 0.26 -> Al <= 0.34 (peso 0.0756)

======================================================================

Removida aresta Al > -0.17 -> Al <= 0.34 (peso 0.1168)
Mantida aresta Al <= 0.34 -> Al > -0.17 (peso 0.1242)

======================================================================

Removida aresta Compton scattering > -0.17 -> Al <= 0.34 (peso 0.0597)
Mantida aresta Al <= 0.34 -> Compton scattering > -0.17 (peso 0.2234)

======================================================================

Removida aresta Al <= 0.34 -> Ti kb > -0.16 (peso 0.0540)
Mantida aresta Ti kb > -0.16 -> Al <= 0.34 (peso 0.1031)

======================================================================

Removida aresta Ti kb > -0.16 -> Compton scattering > -0.17 (peso 0.0542)
Mantida aresta Compton scattering > -0.17 -> Ti kb > -0.16 (peso 0.1745)

======================================================================

Removida aresta sum Fe > 0.13 -> Compton scattering > -0.17 (peso 0.0393)
Mantida aresta Compton scattering > -0.17 -> sum Fe > 0.13 (peso 0.0506)

======================================================================

Removida aresta Compton scattering > -0.17 -> Ti kb > -0.13 (peso 0.0522)
Mantida aresta Ti kb > -0.13 -> Compton scattering > -0.17 (peso 0.0953)

======================================================================

Removida aresta K <= -0.94 -> sum Fe > 0.13 (peso 0.0460)
Mantida aresta sum Fe > 0.13 -> K <= -0.94 (peso 0.0943)

======================================================================

Removida aresta Fe kb <= 0.29 -> sum Fe > -0.15 (peso 0.0776)
Mantida aresta sum Fe > -0.15 -> Fe kb <= 0.29 (peso 0.1204)

======================================================================

Removida aresta sum Fe > -0.24 -> Fe kb <= 0.29 (peso 0.0505)
Mantida aresta Fe kb <= 0.29 -> sum Fe > -0.24 (peso 0.0769)

======================================================================

Removida aresta K <= -0.94 -> sum Fe > -0.24 (peso 0.0410)
Mantida aresta sum Fe > -0.24 -> K <= -0.94 (peso 0.0476)

======================================================================

Removida aresta Ti kb > 0.11 -> Compton scattering > 0.14 (peso 0.0277)
Mantida aresta Compton scattering > 0.14 -> Ti kb > 0.11 (peso 0.0358)

======================================================================

Removida aresta sum Fe > -0.24 -> sum Fe > -0.15 (peso 0.0379)
Mantida aresta sum Fe > -0.15 -> sum Fe > -0.24 (peso 0.0422)

======================================================================

Removida aresta sum Fe > -0.24 -> Ti ka <= 0.27 (peso 0.0282)
Mantida aresta Ti ka <= 0.27 -> sum Fe > -0.24 (peso 0.0368)

======================================================================

Removida aresta Mn <= 0.47 -> Ti ka <= 0.27 (peso 0.0387)
Mantida aresta Ti ka <= 0.27 -> Mn <= 0.47 (peso 0.0827)

======================================================================

Removida aresta Ti ka <= 0.27 -> Ca ka > -0.97 (peso 0.0347)
Mantida aresta Ca ka > -0.97 -> Ti ka <= 0.27 (peso 0.0650)

======================================================================

Removida aresta Rayleight scattering > -0.14 -> sum Fe > -0.24 (peso 0.0288)
Mantida aresta sum Fe > -0.24 -> Rayleight scattering > -0.14 (peso 0.0766)

======================================================================

Removida aresta Rayleight scattering > -0.14 -> Ca ka > -0.97 (peso 0.0356)
Mantida aresta Ca ka > -0.97 -> Rayleight scattering > -0.14 (peso 0.0617)

======================================================================

Removida aresta background4 > -0.17 -> Rayleight scattering > -0.02 (peso 0.0599)
Mantida aresta Rayleight scattering > -0.02 -> background4 > -0.17 (peso 0.0602)

======================================================================

Removida aresta background4 > -0.17 -> Mn <= 0.47 (peso 0.0323)
Mantida aresta Mn <= 0.47 -> background4 > -0.17 (peso 0.0925)

======================================================================

Removida aresta Rayleight scattering > -0.02 -> Rayleight scattering > -0.19 (peso 0.0320)
Mantida aresta Rayleight scattering > -0.19 -> Rayleight scattering > -0.02 (peso 0.0961)

======================================================================

Removida aresta Ti kb <= 0.18 -> Rayleight scattering > -0.02 (peso 0.0202)
Mantida aresta Rayleight scattering > -0.02 -> Ti kb <= 0.18 (peso 0.0769)

======================================================================

Removida aresta Rayleight scattering > -0.02 -> Compton scattering > -0.23 (peso 0.0198)
Mantida aresta Compton scattering > -0.23 -> Rayleight scattering > -0.02 (peso 0.0237)

======================================================================

Removida aresta Ti kb > 0.11 -> Compton scattering > -0.23 (peso 0.0226)
Mantida aresta Compton scattering > -0.23 -> Ti kb > 0.11 (peso 0.0387)

======================================================================

Removida aresta Mn > 0.18 -> Compton scattering > -0.23 (peso 0.0246)
Mantida aresta Compton scattering > -0.23 -> Mn > 0.18 (peso 0.0633)

======================================================================

Removida aresta Mn <= 0.47 -> Ti kb > 0.11 (peso 0.0294)
Mantida aresta Ti kb > 0.11 -> Mn <= 0.47 (peso 0.0357)

======================================================================

Removida aresta Mn > 0.18 -> Ti kb <= 0.18 (peso 0.0222)
Mantida aresta Ti kb <= 0.18 -> Mn > 0.18 (peso 0.0243)

======================================================================

Removida aresta background3 > 0.17 -> Ti kb <= 0.18 (peso 0.0241)
Mantida aresta Ti kb <= 0.18 -> background3 > 0.17 (peso 0.0477)

======================================================================

Removida aresta Ti kb <= 0.18 -> S <= 0.29 (peso 0.0250)
Mantida aresta S <= 0.29 -> Ti kb <= 0.18 (peso 0.0514)

======================================================================

Removida aresta background4 > -0.23 -> Ti kb <= 0.18 (peso 0.0236)
Mantida aresta Ti kb <= 0.18 -> background4 > -0.23 (peso 0.0240)

======================================================================

Removida aresta background4 > 0.16 -> background4 > -0.23 (peso 0.0242)
Mantida aresta background4 > -0.23 -> background4 > 0.16 (peso 0.0638)

======================================================================


,Predicate_Cov_Seed_0,Predicate_Cov_Seed_1,Predicate_Cov_Seed_2,Predicate_Cov_Seed_3
0,Fe ka > -1.26,Fe ka > -1.26,Fe ka > -1.26,Fe ka > -1.26
1,Fe ka > -1.49,Fe ka > -1.49,Fe ka > -1.49,Fe ka > -1.49
2,Fe ka > -0.89,Fe ka > -0.89,Fe ka > -0.89,Fe ka > -0.89
3,Si > -1.10,Ca ka <= 1.96,Si > -0.73,Si > -0.73
4,Ca ka <= 1.96,Si > -1.10,Ca ka <= 1.96,Ca ka <= 1.96
...,...,...,...,...
90,Class_A,background3 <= -0.17,S > -0.28,background4 <= -0.23
91,Class_B,Rayleight scattering <= 0.20,Compton scattering <= 0.14,Compton scattering <= -0.17
92,NaN,Ni > 0.17,Class_A,S > -0.28
93,NaN,Class_A,Class_B,Class_A
94,NaN,Class_B,NaN,Class_B

In [44]:
# Somar LRCs de predicados equivalentes entre diferentes seeds
lrc_combined_list = []

for seed in random_seeds:
    lrc_df = lrc_cov_by_seed[seed].copy()
    lrc_combined_list.append(lrc_df) # o append adiciona o dataframe ao final da lista

# Concatenar todos os dataframes
lrc_all_seeds = pd.concat(lrc_combined_list, ignore_index=True) 

# Agrupar por predicado (Node) e somar as LRCs, mantendo Zone, Threshold e Operator
lrc_summed_df = lrc_all_seeds.groupby('Node').agg({ # o .agg pode ser usado para aplicar múltiplas funções de agregação
    'Local_Reaching_Centrality': 'mean', # sum = somando as LRCs, poderia ser média ou outro agregado
    'Zone': 'first',
    'Threshold': 'first',
    'Operator': 'first'
}).reset_index()

# Ordenar pelo valor de LRC somado (maior para menor)
lrc_summed_df = lrc_summed_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
# vamoss pegar so os valore sunicos de lrc_summed_df baseado na zona espectral
lrc_summed_unique_df_cov = lrc_summed_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
#lrc_summed_unique_df_cov = lrc_summed_unique_df_cov.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
lrc_summed_unique_df_cov

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator
0,Fe ka > -1.26,12.187837,Fe ka,-1.26,>
1,Ca ka <= 1.96,5.191885,Ca ka,1.96,<=
2,Si > -0.73,4.751321,Si,-0.73,>
3,K > -2.69,4.551073,K,-2.69,>
4,Ti ka > -0.34,1.632535,Ti ka,-0.34,>
5,Fe kb > -0.40,1.261440,Fe kb,-0.40,>
6,Rh L + Ar > -0.42,1.252663,Rh L + Ar,-0.42,>
7,Ca kb <= 0.31,1.228897,Ca kb,0.31,<=
8,Al > -0.33,0.430643,Al,-0.33,>
9,Ti kb > -0.16,0.384799,Ti kb,-0.16,>
10,P > 0.26,0.369147,P,0.26,>
11,Compton scattering > -0.17,0.323685,Compton scattering,-0.17,>
12,sum Fe > 0.13,0.266156,sum Fe,0.13,>
13,Rayleight scattering > -0.19,0.244020,Rayleight scattering,-0.19,>
14,Mn <= 0.47,0.237152,Mn,0.47,<=
15,background4 > -0.17,0.200430,background4,-0.17,>
16,Ni <= 0.17,0.191110,Ni,0.17,<=
17,S <= 0.29,0.190888,S,0.29,<=
18,background3 > 0.17,0.179017,background3,0.17,>
19,background2 <= 0.16,0.167161,background2,0.16,<=
20,background1 <= 0.15,0.154474,background1,0.15,<=
21,Class_B,0.000000,None,None,None

# **Perturbation**

In [45]:
ycalres = np.where(svm_model[1]['SVC'] == 'A', 1, 0)

In [12]:
import explaining as exp

# LISTA DE SEMENTES A TESTAR
random_seeds = [0, 1, 2, 3]

all_results_pert = {}
training_samples = len(Xcalclass)

# LOOP: PROCESSAR CADA SEMENTE
y_predicted_numeric = pd.Series(y_pred) # predições numéricas do modelo

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando semente: {seed}")
    print(f"{'='*70}\n")
    # Bagging
    bags_result_seed = exp.bagging_predicates(
        zone_sums_df=zone_sums_df,
        y_predicted_numeric=y_predicted_numeric,
        predicates_df=predicates_quantiles[0],
        n_bags=10,
        #n_predicates_per_bag=40,
        n_samples_per_bag=int(training_samples*0.8), # 80 % da base para amostrar (convertido para int)
        min_samples_per_predicate=int(training_samples*0.2), # 20 % da base para limitar (convertido para int)
        replace=False,
        sample_bagging=True,
        predicate_bagging=False,
        random_seed=seed
    )
    # Inserir classe prevista
    for bag_name, pred_dict in bags_result_seed.items(): # iterando sobre cada bag
        for pred_rule, df_info in pred_dict.items():
            df_info['Class_Predicted'] = np.where(df_info['Predicted_Y'] >= 0.5, 'A', 'B') # binarizando com threshold 0.5, A = eut, B = dist

    pert_results_seed = exp.calculate_predicate_perturbation(
        estimator=svm_model[3],
        Xcalclass_prep=Xcalclass_prep,
        folds_struct=bags_result_seed,
        predicates_df=predicates_quantiles[0],
        spectral_cuts=spectral_cuts,
        #perturbation_value=0,
        perturbation_mode='mean', # valores entre 'mean' ou 'min'
        stats_source='full', # full indica usar todas as amostras para calcular estatísticas enquanto que 'fold' usa apenas as amostras do fold atual
        #metric='mean_abs_diff',   # Média com sinal (pode ser negativo)
        aim='classification',
        metric='probability_shift', 
        verbose=True
    )

    # Remove todos os valores iguais a zero de todos os bags em perm_results[bag]["Permutation"] e salva como perm_results_thresholded
    # pert_results_seed_thresholded = {}
    # for bag, df in perm_results_seed.items():
    #     # Verifica se é um DataFrame e se a coluna 'Permutation' existe
    #     if isinstance(df, pd.DataFrame) and 'Permutation' in df.columns:
    #         filtered_df = df[df['Permutation'] > 0].copy()
    #         pert_results_seed_thresholded[bag] = filtered_df
    #     else:
    #         # Se não for DataFrame esperado, apenas copia
    #         pert_results_seed_thresholded[bag] = df

    # Salvar no dicionário principal
    all_results_pert[seed] = {
        'bags_result': bags_result_seed,
        'pert_results_dict': pert_results_seed
    }

# CONSTRUÇÃO DE GRAFOS PARA MÚLTIPLAS SEMENTES (LOOP EXTERNO)
# Dicionário para armazenar grafos
graphs_pert_by_seed = {}

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando Grafo - Semente: {seed}")
    print(f"{'='*70}\n")
    # Construir grafo para esta semente
    DG = exp.build_predicate_graphv2(
        bags_result=all_results_pert[seed]['bags_result'],
        predicate_ranking_dict=all_results_pert[seed]['pert_results_dict'],
        metric_column='Perturbation',  # ou 'Covariance' se mudar a métrica
        random_state=seed,
        show_details=True
    )
    # Armazenar grafo
    graphs_pert_by_seed[seed] = DG  

# Calcular LRC usando a função pronta do explaining.py
lrc_pert_by_seed = {}
for seed in random_seeds:
    DG = graphs_pert_by_seed[seed]
    lrc_pert_df_seed = exp.calculate_lrc_single_graph(DG, predicates_quantiles[0])
    lrc_pert_df_seed['Seed'] = seed  # Adicionar coluna com a semente
    lrc_pert_by_seed[seed] = lrc_pert_df_seed

# junando todas as colunas 'Node' de lrc_by_seed em um único dataframe
lrc_pert_all_seeds_df = pd.DataFrame()
for seed in random_seeds:
    lrc_pert_df_seed = lrc_pert_by_seed[seed].rename(columns={'Node': f'Predicate_pert_Seed_{seed}'})
    lrc_pert_all_seeds_df = pd.concat([lrc_pert_all_seeds_df, lrc_pert_df_seed[[f'Predicate_pert_Seed_{seed}']]], axis=1)

# vamos filtrar lrc_by_seed em cada semente para manter apenas as zonas espectrais únicas com maior LRC em um mesmo dataframe
lrc_pert_unique_by_seed = {}
for seed, lrc_df in lrc_pert_by_seed.items():
    lrc_pert_unique_df = lrc_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
    lrc_pert_unique_df = lrc_pert_unique_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
    lrc_pert_unique_by_seed[seed] = lrc_pert_unique_df

lrc_pert_all_seeds_df # exibindo o dataframe consolidado com predicados de todas as sementes

======================================================================
Processando semente: 0
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 183 | Descartados: 57
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 182 | Descartados: 58
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 181 | Descartados: 59
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 183 | Descartados: 57
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 183 | Descartados: 57
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 181 | Descartados: 59
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 180 | Descartados: 60
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 181 | Descartados: 59
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 183 | Descartados: 57
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 181 | Descartados: 59
======================================================================
PERTURBATION IMPORTANCE PARA PREDICADOS
======================================================================
Tipo de tarefa (aim): classification
Modo de perturbação: mean
Fonte das estatísticas: full
Métrica: probability_shift
Total de folds: 10


[Bag_1] Processando 183 predicados...
  Predicado: background1 > -0.11 (n=101)
    Zona: 17 colunas
    Importance: 0.000387
  Predicado: background1 <= -0.07 (n=51)
    Zona: 17 colunas
    Importance: 0.000395
  Predicado: background1 > -0.07 (n=67)
    Zona: 17 colunas
    Importance: 0.000407
  Predicado: background1 <= 0.09 (n=74)
    Zona: 17 colunas
    Importance: 0.000384
  Predicado: background1 > 0.09 (n=44)
    Zona: 17 colunas
    Importance: 0.000432
  Predicado: background1 <= 0.11 (n=89)
    Zona: 17 colunas
    Importance: 0.000378
  Predicado: background1 > 0.11 (n=29)
    Zona: 17 colunas
    Importance: 0.000475
  Predicado: Al > -0.22 (n=94)
    Zona: 15 colunas
    Importance: 0.002916
  Predicado: Al <= -0.12 (n=47)
    Zona: 15 colunas
    Importance: 0.002568
  Predicado: Al > -0.12 (n=71)
    Zona: 15 colunas
    Importance: 0.003165
  Predicado: Al <= 0.16 (n=71)
    Zona: 15 colunas
    Importance: 0.002112
  Predicado: Al > 0.16 (n=47)
    Zona: 15 colunas
    Importance: 0.004159
  Predicado: Al <= 0.22 (n=95)
    Zona: 15 colunas
    Importance: 0.002116
  Predicado: Si > -0.38 (n=94)
    Zona: 12 colunas
    Importance: 0.019367
  Predicado: Si <= -0.20 (n=49)
    Zona: 12 colunas
    Importance: 0.023727
  Predicado: Si > -0.20 (n=69)
    Zona: 12 colunas
    Importance: 0.023153
  Predicado: Si <= 0.16 (n=71)
    Zona: 12 colunas
    Importance: 0.017424
  Predicado: Si > 0.16 (n=47)
    Zona: 12 colunas
    Importance: 0.032405
  Predicado: Si <= 0.37 (n=93)
    Zona: 12 colunas
    Importance: 0.017037
  Predicado: P <= -0.16 (n=30)
    Zona: 13 colunas
    Importance: 0.004583
  Predicado: P > -0.16 (n=88)
    Zona: 13 colunas
    Importance: 0.003947
  Predicado: P <= -0.13 (n=50)
    Zona: 13 colunas
    Importance: 0.004637
  Predicado: P > -0.13 (n=68)
    Zona: 13 colunas
    Importance: 0.003720
  Predicado: P <= 0.12 (n=69)
    Zona: 13 colunas
    Importance: 0.003867
  Predicado: P > 0.12 (n=49)
    Zona: 13 colunas
    Importance: 0.004448
  Predicado: P <= 0.22 (n=93)
    Zona: 13 colunas
    Importance: 0.003544
  Predicado: background2 > -0.09 (n=96)
    Zona: 5 colunas
    Importance: 0.000225
  Predicado: background2 <= -0.06 (n=43)
    Zona: 5 colunas
    Importance: 0.000299
  Predicado: background2 > -0.06 (n=75)
    Zona: 5 colunas
    Importance: 0.000243
  Predicado: background2 <= 0.06 (n=64)
    Zona: 5 colunas
    Importance: 0.000242
  Predicado: background2 > 0.06 (n=54)
    Zona: 5 colunas
    Importance: 0.000289
  Predicado: background2 <= 0.10 (n=94)
    Zona: 5 colunas
    Importance: 0.000229
  Predicado: S > -0.13 (n=98)
    Zona: 13 colunas
    Importance: 0.001013
  Predicado: S <= -0.09 (n=53)
    Zona: 13 colunas
    Importance: 0.002435
  Predicado: S > -0.09 (n=65)
    Zona: 13 colunas
    Importance: 0.000845
  Predicado: S <= 0.09 (n=71)
    Zona: 13 colunas
    Importance: 0.001944
  Predicado: S > 0.09 (n=47)
    Zona: 13 colunas
    Importance: 0.000978
  Predicado: S <= 0.14 (n=98)
    Zona: 13 colunas
    Importance: 0.001647
  Predicado: background3 > -0.09 (n=92)
    Zona: 6 colunas
    Importance: 0.000098
  Predicado: background3 <= -0.06 (n=49)
    Zona: 6 colunas
    Importance: 0.000115
  Predicado: background3 > -0.06 (n=69)
    Zona: 6 colunas
    Importance: 0.000104
  Predicado: background3 <= 0.06 (n=72)
    Zona: 6 colunas
    Importance: 0.000099
  Predicado: background3 > 0.06 (n=46)
    Zona: 6 colunas
    Importance: 0.000124
  Predicado: background3 <= 0.09 (n=97)
    Zona: 6 colunas
    Importance: 0.000106
  Predicado: Rh L + Ar > -0.15 (n=94)
    Zona: 28 colunas
    Importance: 0.001100
  Predicado: Rh L + Ar <= -0.08 (n=50)
    Zona: 28 colunas
    Importance: 0.001930
  Predicado: Rh L + Ar > -0.08 (n=68)
    Zona: 28 colunas
    Importance: 0.001141
  Predicado: Rh L + Ar <= 0.14 (n=76)
    Zona: 28 colunas
    Importance: 0.001575
  Predicado: Rh L + Ar > 0.14 (n=42)
    Zona: 28 colunas
    Importance: 0.001295
  Predicado: Rh L + Ar <= 0.19 (n=99)
    Zona: 28 colunas
    Importance: 0.001470
  Predicado: background4 > -0.10 (n=94)
    Zona: 6 colunas
    Importance: 0.000252
  Predicado: background4 <= -0.06 (n=47)
    Zona: 6 colunas
    Importance: 0.000269
  Predicado: background4 > -0.06 (n=71)
    Zona: 6 colunas
    Importance: 0.000256
  Predicado: background4 <= 0.08 (n=81)
    Zona: 6 colunas
    Importance: 0.000217
  Predicado: background4 > 0.08 (n=37)
    Zona: 6 colunas
    Importance: 0.000358
  Predicado: background4 <= 0.10 (n=98)
    Zona: 6 colunas
    Importance: 0.000231
  Predicado: K > -0.21 (n=92)
    Zona: 11 colunas
    Importance: 0.000979
  Predicado: K <= -0.15 (n=49)
    Zona: 11 colunas
    Importance: 0.001466
  Predicado: K > -0.15 (n=69)
    Zona: 11 colunas
    Importance: 0.001035
  Predicado: K <= -0.02 (n=73)
    Zona: 11 colunas
    Importance: 0.001207
  Predicado: K > -0.02 (n=45)
    Zona: 11 colunas
    Importance: 0.001225
  Predicado: K <= 0.21 (n=96)
    Zona: 11 colunas
    Importance: 0.001240
  Predicado: background5 > -0.10 (n=101)
    Zona: 6 colunas
    Importance: 0.000145
  Predicado: background5 <= -0.05 (n=47)
    Zona: 6 colunas
    Importance: 0.000215
  Predicado: background5 > -0.05 (n=71)
    Zona: 6 colunas
    Importance: 0.000149
  Predicado: background5 <= 0.07 (n=72)
    Zona: 6 colunas
    Importance: 0.000173
  Predicado: background5 > 0.07 (n=46)
    Zona: 6 colunas
    Importance: 0.000179
  Predicado: background5 <= 0.11 (n=98)
    Zona: 6 colunas
    Importance: 0.000171
  Predicado: Ca ka > -0.72 (n=92)
    Zona: 16 colunas
    Importance: 0.169991
  Predicado: Ca ka <= -0.47 (n=49)
    Zona: 16 colunas
    Importance: 0.323494
  Predicado: Ca ka > -0.47 (n=69)
    Zona: 16 colunas
    Importance: 0.134369
  Predicado: Ca ka <= -0.22 (n=72)
    Zona: 16 colunas
    Importance: 0.262428
  Predicado: Ca ka > -0.22 (n=46)
    Zona: 16 colunas
    Importance: 0.135388
  Predicado: Ca ka <= 0.58 (n=94)
    Zona: 16 colunas
    Importance: 0.217674
  Predicado: Ca kb <= -0.20 (n=30)
    Zona: 16 colunas
    Importance: 0.007843
  Predicado: Ca kb > -0.20 (n=88)
    Zona: 16 colunas
    Importance: 0.006238
  Predicado: Ca kb <= -0.15 (n=48)
    Zona: 16 colunas
    Importance: 0.008996
  Predicado: Ca kb > -0.15 (n=70)
    Zona: 16 colunas
    Importance: 0.005035
  Predicado: Ca kb <= -0.07 (n=69)
    Zona: 16 colunas
    Importance: 0.008355
  Predicado: Ca kb > -0.07 (n=49)
    Zona: 16 colunas
    Importance: 0.004240
  Predicado: Ca kb <= 0.20 (n=94)
    Zona: 16 colunas
    Importance: 0.006886
  Predicado: background6 > -0.13 (n=95)
    Zona: 12 colunas
    Importance: 0.000451
  Predicado: background6 <= -0.08 (n=48)
    Zona: 12 colunas
    Importance: 0.000477
  Predicado: background6 > -0.08 (n=70)
    Zona: 12 colunas
    Importance: 0.000483
  Predicado: background6 <= 0.10 (n=69)
    Zona: 12 colunas
    Importance: 0.000447
  Predicado: background6 > 0.10 (n=49)
    Zona: 12 colunas
    Importance: 0.000527
  Predicado: background6 <= 0.14 (n=92)
    Zona: 12 colunas
    Importance: 0.000444
  Predicado: Ti ka > -0.80 (n=94)
    Zona: 15 colunas
    Importance: 0.039556
  Predicado: Ti ka <= -0.37 (n=51)
    Zona: 15 colunas
    Importance: 0.035265
  Predicado: Ti ka > -0.37 (n=67)
    Zona: 15 colunas
    Importance: 0.047257
  Predicado: Ti ka <= 0.50 (n=72)
    Zona: 15 colunas
    Importance: 0.028284
  Predicado: Ti ka > 0.50 (n=46)
    Zona: 15 colunas
    Importance: 0.063658
  Predicado: Ti ka <= 0.91 (n=94)
    Zona: 15 colunas
    Importance: 0.031376
  Predicado: background7 > -0.16 (n=94)
    Zona: 5 colunas
    Importance: 0.000284
  Predicado: background7 <= -0.09 (n=45)
    Zona: 5 colunas
    Importance: 0.000376
  Predicado: background7 > -0.09 (n=73)
    Zona: 5 colunas
    Importance: 0.000286
  Predicado: background7 <= 0.09 (n=71)
    Zona: 5 colunas
    Importance: 0.000328
  Predicado: background7 > 0.09 (n=47)
    Zona: 5 colunas
    Importance: 0.000308
  Predicado: background7 <= 0.17 (n=94)
    Zona: 5 colunas
    Importance: 0.000305
  Predicado: Ti kb > -0.32 (n=95)
    Zona: 19 colunas
    Importance: 0.003996
  Predicado: Ti kb <= -0.18 (n=52)
    Zona: 19 colunas
    Importance: 0.005136
  Predicado: Ti kb > -0.18 (n=66)
    Zona: 19 colunas
    Importance: 0.004983
  Predicado: Ti kb <= 0.20 (n=69)
    Zona: 19 colunas
    Importance: 0.004228
  Predicado: Ti kb > 0.20 (n=49)
    Zona: 19 colunas
    Importance: 0.006208
  Predicado: Ti kb <= 0.37 (n=93)
    Zona: 19 colunas
    Importance: 0.004347
  Predicado: Cr > -0.17 (n=95)
    Zona: 33 colunas
    Importance: 0.001995
  Predicado: Cr <= -0.13 (n=47)
    Zona: 33 colunas
    Importance: 0.003246
  Predicado: Cr > -0.13 (n=71)
    Zona: 33 colunas
    Importance: 0.001857
  Predicado: Cr <= 0.12 (n=68)
    Zona: 33 colunas
    Importance: 0.002564
  Predicado: Cr > 0.12 (n=50)
    Zona: 33 colunas
    Importance: 0.002201
  Predicado: Cr <= 0.19 (n=93)
    Zona: 33 colunas
    Importance: 0.002278
  Predicado: Mn > -0.35 (n=98)
    Zona: 13 colunas
    Importance: 0.013639
  Predicado: Mn <= -0.23 (n=47)
    Zona: 13 colunas
    Importance: 0.017322
  Predicado: Mn > -0.23 (n=71)
    Zona: 13 colunas
    Importance: 0.013213
  Predicado: Mn <= -0.14 (n=68)
    Zona: 13 colunas
    Importance: 0.014317
  Predicado: Mn > -0.14 (n=50)
    Zona: 13 colunas
    Importance: 0.015574
  Predicado: Mn <= 0.37 (n=94)
    Zona: 13 colunas
    Importance: 0.013394
  Predicado: background8 > -0.12 (n=94)
    Zona: 6 colunas
    Importance: 0.000222
  Predicado: background8 <= -0.07 (n=48)
    Zona: 6 colunas
    Importance: 0.000291
  Predicado: background8 > -0.07 (n=70)
    Zona: 6 colunas
    Importance: 0.000220
  Predicado: background8 <= 0.09 (n=70)
    Zona: 6 colunas
    Importance: 0.000241
  Predicado: background8 > 0.09 (n=48)
    Zona: 6 colunas
    Importance: 0.000259
  Predicado: background8 <= 0.14 (n=96)
    Zona: 6 colunas
    Importance: 0.000260
  Predicado: Fe ka > -1.50 (n=96)
    Zona: 28 colunas
    Importance: 0.049209
  Predicado: Fe ka <= -0.44 (n=43)
    Zona: 28 colunas
    Importance: 0.114576
  Predicado: Fe ka > -0.44 (n=75)
    Zona: 28 colunas
    Importance: 0.046635
  Predicado: Fe ka <= 0.86 (n=70)
    Zona: 28 colunas
    Importance: 0.077337
  Predicado: Fe ka > 0.86 (n=48)
    Zona: 28 colunas
    Importance: 0.062724
  Predicado: Fe ka <= 1.45 (n=95)
    Zona: 28 colunas
    Importance: 0.070955
  Predicado: background9 > -0.11 (n=94)
    Zona: 7 colunas
    Importance: 0.000241
  Predicado: background9 <= -0.08 (n=46)
    Zona: 7 colunas
    Importance: 0.000250
  Predicado: background9 > -0.08 (n=72)
    Zona: 7 colunas
    Importance: 0.000261
  Predicado: background9 <= 0.08 (n=69)
    Zona: 7 colunas
    Importance: 0.000233
  Predicado: background9 > 0.08 (n=49)
    Zona: 7 colunas
    Importance: 0.000292
  Predicado: background9 <= 0.12 (n=96)
    Zona: 7 colunas
    Importance: 0.000255
  Predicado: Fe kb > -0.59 (n=97)
    Zona: 26 colunas
    Importance: 0.012702
  Predicado: Fe kb <= -0.23 (n=46)
    Zona: 26 colunas
    Importance: 0.012350
  Predicado: Fe kb > -0.23 (n=72)
    Zona: 26 colunas
    Importance: 0.013912
  Predicado: Fe kb <= 0.34 (n=70)
    Zona: 26 colunas
    Importance: 0.009477
  Predicado: Fe kb > 0.34 (n=48)
    Zona: 26 colunas
    Importance: 0.018882
  Predicado: Fe kb <= 0.57 (n=94)
    Zona: 26 colunas
    Importance: 0.010461
  Predicado: background10 > -0.13 (n=92)
    Zona: 31 colunas
    Importance: 0.000942
  Predicado: background10 <= -0.10 (n=49)
    Zona: 31 colunas
    Importance: 0.001698
  Predicado: background10 > -0.10 (n=69)
    Zona: 31 colunas
    Importance: 0.000945
  Predicado: background10 <= 0.12 (n=76)
    Zona: 31 colunas
    Importance: 0.001308
  Predicado: background10 > 0.12 (n=42)
    Zona: 31 colunas
    Importance: 0.001166
  Predicado: background10 <= 0.15 (n=94)
    Zona: 31 colunas
    Importance: 0.001264
  Predicado: Cu > -0.13 (n=90)
    Zona: 15 colunas
    Importance: 0.001251
  Predicado: Cu <= -0.10 (n=50)
    Zona: 15 colunas
    Importance: 0.001731
  Predicado: Cu > -0.10 (n=68)
    Zona: 15 colunas
    Importance: 0.001275
  Predicado: Cu <= 0.10 (n=69)
    Zona: 15 colunas
    Importance: 0.001332
  Predicado: Cu > 0.10 (n=49)
    Zona: 15 colunas
    Importance: 0.001660
  Predicado: Cu <= 0.15 (n=95)
    Zona: 15 colunas
    Importance: 0.001233
  Predicado: background11 > -0.15 (n=93)
    Zona: 125 colunas
    Importance: 0.003366
  Predicado: background11 <= -0.12 (n=43)
    Zona: 125 colunas
    Importance: 0.004642
  Predicado: background11 > -0.12 (n=75)
    Zona: 125 colunas
    Importance: 0.003154
  Predicado: background11 <= 0.14 (n=77)
    Zona: 125 colunas
    Importance: 0.003637
  Predicado: background11 > 0.14 (n=41)
    Zona: 125 colunas
    Importance: 0.003808
  Predicado: background11 <= 0.19 (n=97)
    Zona: 125 colunas
    Importance: 0.003812
  Predicado: Fe ka + Ti ka > -0.13 (n=91)
    Zona: 23 colunas
    Importance: 0.000599
  Predicado: Fe ka + Ti ka <= -0.11 (n=46)
    Zona: 23 colunas
    Importance: 0.000642
  Predicado: Fe ka + Ti ka > -0.11 (n=72)
    Zona: 23 colunas
    Importance: 0.000588
  Predicado: Fe ka + Ti ka <= 0.12 (n=74)
    Zona: 23 colunas
    Importance: 0.000599
  Predicado: Fe ka + Ti ka > 0.12 (n=44)
    Zona: 23 colunas
    Importance: 0.000627
  Predicado: Fe ka + Ti ka <= 0.16 (n=97)
    Zona: 23 colunas
    Importance: 0.000568
  Predicado: background12 > -0.14 (n=95)
    Zona: 71 colunas
    Importance: 0.002187
  Predicado: background12 <= -0.11 (n=52)
    Zona: 71 colunas
    Importance: 0.002545
  Predicado: background12 > -0.11 (n=66)
    Zona: 71 colunas
    Importance: 0.002021
  Predicado: background12 <= 0.13 (n=75)
    Zona: 71 colunas
    Importance: 0.002165
  Predicado: background12 > 0.13 (n=43)
    Zona: 71 colunas
    Importance: 0.002405
  Predicado: background12 <= 0.15 (n=90)
    Zona: 71 colunas
    Importance: 0.002317
  Predicado: sum Fe > -0.20 (n=95)
    Zona: 28 colunas
    Importance: 0.001451
  Predicado: sum Fe <= -0.11 (n=45)
    Zona: 28 colunas
    Importance: 0.002680
  Predicado: sum Fe > -0.11 (n=73)
    Zona: 28 colunas
    Importance: 0.001280
  Predicado: sum Fe <= 0.15 (n=66)
    Zona: 28 colunas
    Importance: 0.002106
  Predicado: sum Fe > 0.15 (n=52)
    Zona: 28 colunas
    Importance: 0.001443
  Predicado: sum Fe <= 0.20 (n=93)
    Zona: 28 colunas
    Importance: 0.001799
  Predicado: background13 > -0.15 (n=95)
    Zona: 96 colunas
    Importance: 0.002646
  Predicado: background13 <= 0.11 (n=50)
    Zona: 96 colunas
    Importance: 0.001990
  Predicado: background13 > 0.11 (n=68)
    Zona: 96 colunas
    Importance: 0.002958
  Predicado: background13 <= 0.14 (n=68)
    Zona: 96 colunas
    Importance: 0.002070
  Predicado: background13 > 0.14 (n=50)
    Zona: 96 colunas
    Importance: 0.003197
  Predicado: background13 <= 0.18 (n=93)
    Zona: 96 colunas
    Importance: 0.002213

[Bag_2] Processando 182 predicados...
  Predicado: background1 > -0.11 (n=96)
    Zona: 17 colunas
    Importance: 0.000397
  Predicado: background1 <= -0.07 (n=50)
    Zona: 17 colunas
    Importance: 0.000476
  Predicado: background1 > -0.07 (n=68)
    Zona: 17 colunas
    Importance: 0.000392
  Predicado: background1 <= 0.09 (n=74)
    Zona: 17 colunas
    Importance: 0.000434
  Predicado: background1 > 0.09 (n=44)
    Zona: 17 colunas
    Importance: 0.000416
  Predicado: background1 <= 0.11 (n=90)
    Zona: 17 colunas
    Importance: 0.000417
  Predicado: Al > -0.22 (n=96)
    Zona: 15 colunas
    Importance: 0.003085
  Predicado: Al <= -0.12 (n=44)
    Zona: 15 colunas
    Importance: 0.002734
  Predicado: Al > -0.12 (n=74)
    Zona: 15 colunas
    Importance: 0.003251
  Predicado: Al <= 0.16 (n=71)
    Zona: 15 colunas
    Importance: 0.002181
  Predicado: Al > 0.16 (n=47)
    Zona: 15 colunas
    Importance: 0.004382
  Predicado: Al <= 0.22 (n=92)
    Zona: 15 colunas
    Importance: 0.002112
  Predicado: Si > -0.38 (n=94)
    Zona: 12 colunas
    Importance: 0.016959
  Predicado: Si <= -0.20 (n=49)
    Zona: 12 colunas
    Importance: 0.023479
  Predicado: Si > -0.20 (n=69)
    Zona: 12 colunas
    Importance: 0.020063
  Predicado: Si <= 0.16 (n=70)
    Zona: 12 colunas
    Importance: 0.017470
  Predicado: Si > 0.16 (n=48)
    Zona: 12 colunas
    Importance: 0.027333
  Predicado: Si <= 0.37 (n=94)
    Zona: 12 colunas
    Importance: 0.016490
  Predicado: P > -0.16 (n=91)
    Zona: 13 colunas
    Importance: 0.003344
  Predicado: P <= -0.13 (n=44)
    Zona: 13 colunas
    Importance: 0.004637
  Predicado: P > -0.13 (n=74)
    Zona: 13 colunas
    Importance: 0.003205
  Predicado: P <= 0.12 (n=66)
    Zona: 13 colunas
    Importance: 0.003959
  Predicado: P > 0.12 (n=52)
    Zona: 13 colunas
    Importance: 0.003460
  Predicado: P <= 0.22 (n=95)
    Zona: 13 colunas
    Importance: 0.003618
  Predicado: background2 > -0.09 (n=95)
    Zona: 5 colunas
    Importance: 0.000230
  Predicado: background2 <= -0.06 (n=42)
    Zona: 5 colunas
    Importance: 0.000334
  Predicado: background2 > -0.06 (n=76)
    Zona: 5 colunas
    Importance: 0.000242
  Predicado: background2 <= 0.06 (n=67)
    Zona: 5 colunas
    Importance: 0.000265
  Predicado: background2 > 0.06 (n=51)
    Zona: 5 colunas
    Importance: 0.000287
  Predicado: background2 <= 0.10 (n=95)
    Zona: 5 colunas
    Importance: 0.000251
  Predicado: S > -0.13 (n=98)
    Zona: 13 colunas
    Importance: 0.001071
  Predicado: S <= -0.09 (n=52)
    Zona: 13 colunas
    Importance: 0.002530
  Predicado: S > -0.09 (n=66)
    Zona: 13 colunas
    Importance: 0.000817
  Predicado: S <= 0.09 (n=72)
    Zona: 13 colunas
    Importance: 0.001957
  Predicado: S > 0.09 (n=46)
    Zona: 13 colunas
    Importance: 0.000969
  Predicado: S <= 0.14 (n=95)
    Zona: 13 colunas
    Importance: 0.001685
  Predicado: background3 > -0.09 (n=95)
    Zona: 6 colunas
    Importance: 0.000122
  Predicado: background3 <= -0.06 (n=42)
    Zona: 6 colunas
    Importance: 0.000130
  Predicado: background3 > -0.06 (n=76)
    Zona: 6 colunas
    Importance: 0.000128
  Predicado: background3 <= 0.06 (n=66)
    Zona: 6 colunas
    Importance: 0.000109
  Predicado: background3 > 0.06 (n=52)
    Zona: 6 colunas
    Importance: 0.000154
  Predicado: background3 <= 0.09 (n=93)
    Zona: 6 colunas
    Importance: 0.000117
  Predicado: Rh L + Ar > -0.15 (n=99)
    Zona: 28 colunas
    Importance: 0.001197
  Predicado: Rh L + Ar <= -0.08 (n=40)
    Zona: 28 colunas
    Importance: 0.001897
  Predicado: Rh L + Ar > -0.08 (n=78)
    Zona: 28 colunas

,Predicate_pert_Seed_0,Predicate_pert_Seed_1,Predicate_pert_Seed_2,Predicate_pert_Seed_3
0,Ca ka <= -0.47,Ca ka <= -0.47,Ca ka <= -0.47,Ca ka <= -0.47
1,Ca ka <= -0.22,Ca ka <= -0.22,Ca ka <= -0.22,Ca ka <= -0.22
2,Ca ka <= 0.58,Ca ka <= 0.58,Ca ka <= 0.58,Ca ka <= 0.58
3,Ca ka > -0.72,Ca ka > -0.72,Ca ka > -0.72,Ca ka > -0.72
4,Ca ka > -0.47,Ca ka > -0.47,Ca ka > -0.47,Ca ka > -0.47
...,...,...,...,...
190,NaN,background3 <= 0.06,background3 > -0.06,background3 <= 0.06
191,NaN,Class_A,background3 > -0.09,Class_A
192,NaN,Class_B,background3 <= 0.06,Class_B
193,NaN,NaN,Class_A,NaN
194,NaN,NaN,Class_B,NaN

In [16]:
all_results_pert[0]['pert_results_dict']['Bag_1']

                Predicate  Perturbation
0          Ca ka <= -0.47      0.323494
1          Ca ka <= -0.22      0.262428
2           Ca ka <= 0.58      0.217674
3           Ca ka > -0.72      0.169991
4           Ca ka > -0.22      0.135388
..                    ...           ...
178  background3 <= -0.06      0.000115
179   background3 <= 0.09      0.000106
180   background3 > -0.06      0.000104
181   background3 <= 0.06      0.000099
182   background3 > -0.09      0.000098

[183 rows x 2 columns]

In [17]:
# Somar LRCs de predicados equivalentes entre diferentes seeds
lrc_combined_list = []

for seed in random_seeds:
    lrc_df = lrc_pert_by_seed[seed].copy()
    lrc_combined_list.append(lrc_df) # o append adiciona o dataframe ao final da lista

# Concatenar todos os dataframes
lrc_all_seeds = pd.concat(lrc_combined_list, ignore_index=True) 

# Agrupar por predicado (Node) e somar as LRCs, mantendo Zone, Threshold e Operator
lrc_summed_df = lrc_all_seeds.groupby('Node').agg({ # o .agg pode ser usado para aplicar múltiplas funções de agregação
    'Local_Reaching_Centrality': 'mean', # sum = somando as LRCs, poderia ser média ou outro agregado
    'Zone': 'first',
    'Threshold': 'first',
    'Operator': 'first'
}).reset_index()

# Ordenar pelo valor de LRC somado (maior para menor)
lrc_summed_df = lrc_summed_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
# vamoss pegar so os valore sunicos de lrc_summed_df baseado na zona espectral
lrc_summed_unique_df_pert = lrc_summed_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
lrc_summed_unique_df_pert = lrc_summed_unique_df_pert.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
lrc_summed_unique_df_pert

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator
0,Ca ka <= -0.47,23.137518,Ca ka,-0.47,<=
1,Fe ka <= -0.44,5.901137,Fe ka,-0.44,<=
2,Ti ka > 0.50,3.658269,Ti ka,0.50,>
3,Si > 0.16,1.555471,Si,0.16,>
4,Fe kb > 0.57,1.087388,Fe kb,0.57,>
5,Mn <= -0.14,0.997373,Mn,-0.14,<=
6,Ca kb <= -0.15,0.513383,Ca kb,-0.15,<=
7,Ti kb <= -0.18,0.276142,Ti kb,-0.18,<=
8,background11 <= -0.12,0.167640,background11,-0.12,<=
9,P <= -0.13,0.153454,P,-0.13,<=
10,Al > 0.16,0.143046,Al,0.16,>
11,Cr <= -0.13,0.133234,Cr,-0.13,<=
12,background13 > 0.14,0.131755,background13,0.14,>
13,background12 <= 0.15,0.120666,background12,0.15,<=
14,sum Fe <= -0.11,0.113459,sum Fe,-0.11,<=
15,K <= -0.21,0.106152,K,-0.21,<=
16,Cu > 0.10,0.104042,Cu,0.10,>
17,Rh L + Ar <= 0.14,0.103831,Rh L + Ar,0.14,<=
18,S <= -0.09,0.102976,S,-0.09,<=
19,background10 <= -0.10,0.089960,background10,-0.10,<=
20,Fe ka + Ti ka <= -0.11,0.024104,Fe ka + Ti ka,-0.11,<=
21,background6 <= -0.08,0.015758,background6,-0.08,<=
22,background1 <= 0.09,0.010796,background1,0.09,<=
23,background7 <= -0.09,0.008831,background7,-0.09,<=
24,background9 > 0.08,0.007768,background9,0.08,>
25,background2 <= -0.06,0.007355,background2,-0.06,<=
26,background8 <= -0.07,0.007002,background8,-0.07,<=
27,background4 > 0.08,0.006746,background4,0.08,>
28,background5 <= -0.05,0.005706,background5,-0.05,<=
29,background3 > 0.06,0.000870,background3,0.06,>
30,Class_A,0.000000,None,None,None

In [18]:
lrc_all_seeds

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator,Seed
0,Ca ka <= -0.47,22.154792,Ca ka,-0.47,<=,0
1,Ca ka <= -0.22,17.824585,Ca ka,-0.22,<=,0
2,Ca ka <= 0.58,14.151616,Ca ka,0.58,<=,0
3,Ca ka > -0.72,10.992025,Ca ka,-0.72,>,0
4,Ca ka > -0.47,9.028498,Ca ka,-0.47,>,0
...,...,...,...,...,...,...
766,background3 > -0.09,0.000575,background3,-0.09,>,3
767,background3 > -0.06,0.000572,background3,-0.06,>,3
768,background3 <= 0.06,0.000355,background3,0.06,<=,3
769,Class_A,0.000000,None,None,None,3
770,Class_B,0.000000,None,None,None,3

In [24]:
svm_model[1]['SVC']

0      A
1      A
2      A
3      A
4      A
      ..
143    B
144    B
145    B
146    B
147    B
Name: SVC, Length: 148, dtype: object

In [30]:
# Permutation importance baseado em mudança nas probabilidades previstas (predict_proba)
# Medimos a média da diferença absoluta entre as probabilidades originais e as probabilidades
# obtidas após permutar cada variável. Isso fornece uma métrica contínua de importância.
n_repeats = 10
rng = np.random.RandomState(42)
# Probabilidades base (classe 'B' mapeada para 1)
baseline_proba = svm_model[3].predict_proba(Xcalclass_prep)[:, 1]
importance_list = []
X_arr = Xcalclass_prep.copy()
for col in Xcalclass_prep.columns:
    diffs = []
    for _ in range(n_repeats):
        X_perm = X_arr.copy()
        X_perm[col] = rng.permutation(X_perm[col].values)
        perm_proba = svm_model[3].predict_proba(X_perm)[:, 1]
        diffs.append(np.mean(np.abs(baseline_proba - perm_proba)))
    importance_list.append(np.mean(diffs))

permutation_df = pd.DataFrame({
    'energy': Xcalclass_prep.columns,
    'Permutation_importance_proba': importance_list
})
permutation_df.sort_values(by='Permutation_importance_proba', ascending=False, inplace=True)
energy_to_zone_vip = {}
for zone_name, start, end in spectral_cuts:
    for e in permutation_df['energy']:
        ef = float(e)
        if start <= ef <= end:
            energy_to_zone_vip[e] = zone_name
permutation_df['Zone'] = permutation_df['energy'].map(energy_to_zone_vip)
permutation_unique_df = permutation_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
permutation_unique_df = permutation_unique_df.sort_values(by='Permutation_importance_proba', ascending=False)
permutation_unique_df

   energy  Permutation_importance_proba           Zone
0     3.7                      0.043398          Ca ka
1    6.48                      0.018750          Fe ka
2    4.52                      0.011495          Ti ka
3    1.74                      0.006048             Si
4     5.9                      0.003943             Mn
5    7.02                      0.003289          Fe kb
6    4.02                      0.002340          Ca kb
7    2.02                      0.001289              P
8    4.96                      0.001278          Ti kb
9    1.54                      0.001138             Al
10   2.32                      0.000685              S
11   5.46                      0.000643             Cr
12  12.84                      0.000597         sum Fe
13   3.28                      0.000566              K
14   8.04                      0.000487             Cu
15   4.36                      0.000414    background6
16    3.2                      0.000353    background4
17   9.38                      0.000353   background11
18   7.84                      0.000345   background10
19  13.36                      0.000329   background13
20  11.88                      0.000307   background12
21   4.66                      0.000306    background7
22    2.1                      0.000292    background2
23    2.9                      0.000255      Rh L + Ar
24   10.9                      0.000219  Fe ka + Ti ka
25    1.1                      0.000185    background1
26   3.52                      0.000181    background5
27   6.02                      0.000180    background8
28   6.76                      0.000175    background9
29   2.48                      0.000071    background3

In [33]:
import numpy as np

max_len = max(
    len(pvector_unique_df['Zone']),
    len(shap_unique_df['Zone']),
    len(permutation_unique_df['Zone']),
    len(lrc_summed_unique_df_pert['Zone']),
    len(lrc_summed_unique_df_cov['Zone'])
)

def pad_list(lst, length):
    return list(lst) + [None] * (length - len(lst))

features_importance = pd.DataFrame({
    'SVM_pvector': pad_list(pvector_unique_df['Zone'], max_len),
    'Shap': pad_list(shap_unique_df['Zone'], max_len),
    'Permutation' : pad_list(permutation_unique_df['Zone'], max_len),
    'LRC_perturbation' : pad_list(lrc_summed_unique_df_pert['Zone'], max_len),
    'LRC_covariance' : pad_list(lrc_summed_unique_df_cov['Zone'], max_len),
})

features_importance.to_csv('feature_importance.csv', index=False, sep=';')
features_importance

,SVM_pvector,Shap,Permutation,LRC_perturbation,LRC_covariance
0,Ca ka,Ca ka,Ca ka,Ca ka,Ca ka
1,Fe ka,Fe ka,Fe ka,Fe ka,Fe ka
2,Ca kb,Ti ka,Ti ka,Ti ka,Fe kb
3,Si,Si,Si,Si,Mn
4,Fe kb,Mn,Mn,Fe kb,Ti ka
5,Ti ka,Fe kb,Fe kb,Mn,Si
6,Mn,Cu,Ca kb,Ca kb,Ca kb
7,sum Fe,background12,P,Ti kb,K
8,Al,sum Fe,Ti kb,background11,Al
9,Cr,P,Al,P,P
10,P,background10,S,Al,sum Fe
11,S,Al,Cr,Cr,Ti kb
12,background12,Ca kb,sum Fe,background13,Cr
13,background11,background11,K,background12,background13
14,background13,Fe ka + Ti ka,Cu,sum Fe,background9
15,background4,background13,background6,K,background12
16,background10,background1,background4,Cu,S
17,Cu,K,background11,Rh L + Ar,background7
18,Rh L + Ar,background5,background10,S,background6
19,background7,Rh L + Ar,background13,background10,Cu
20,Ti kb,background4,background12,Fe ka + Ti ka,background8
21,Fe ka + Ti ka,background6,background7,background6,background10
22,background9,background7,background2,background1,background11
23,background2,Ti kb,Rh L + Ar,background7,None
24,background6,S,Fe ka + Ti ka,background9,None
25,background8,background3,background1,background2,None
26,K,background2,background5,background8,None
27,background5,Cr,background8,background4,None
28,background1,background9,background9,background5,None
29,background3,background8,background3,background3,None
30,None,None,None,None,None

In [34]:
import rbo
rbo_comparison = pd.DataFrame(columns=['Method_1', 'Method_2', 'RBO_Score'])
methods = features_importance.columns.tolist()
for i in range(len(methods)):
    for j in range(i + 1, len(methods)):
        method_1 = methods[i]
        method_2 = methods[j]
        # Remove None values from the lists
        list_1 = [x for x in features_importance[method_1].tolist() if x is not None]
        list_2 = [x for x in features_importance[method_2].tolist() if x is not None]
        # Truncate both lists to the same length (minimum of both)
        min_len = min(len(list_1), len(list_2))
        list_1_trunc = list_1[:min_len]
        list_2_trunc = list_2[:min_len]
        rbo_score = rbo.RankingSimilarity(list_1_trunc, list_2_trunc).rbo(p=0.7, k=10)
        rbo_comparison = pd.concat([rbo_comparison, pd.DataFrame({
            'Method_1': [method_1],
            'Method_2': [method_2],
            'RBO_Score': [rbo_score]
        })], ignore_index=True)
rbo_comparison.sort_values(by='RBO_Score', ascending=False, inplace=True)
rbo_comparison.to_csv('rbo_rank.csv', index=False, sep=';')
rbo_comparison

C:\Users\Usuario\AppData\Local\Temp\ipykernel_24720\3097109587.py:16: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

           Method_1          Method_2  RBO_Score
4              Shap       Permutation   0.951137
7       Permutation  LRC_perturbation   0.951126
5              Shap  LRC_perturbation   0.936731
2       SVM_pvector  LRC_perturbation   0.863655
1       SVM_pvector       Permutation   0.850459
8       Permutation    LRC_covariance   0.848754
9  LRC_perturbation    LRC_covariance   0.847544
0       SVM_pvector              Shap   0.841118
6              Shap    LRC_covariance   0.836281
3       SVM_pvector    LRC_covariance   0.826656