## Loading data

In [69]:
# Importing the necessary libraries
import pandas as pd
import numpy as np
import kennard_stone as ks
pd.options.plotting.backend = 'plotly'  # setting plotly as the backend for pandas plotting

# Add parent directory to sys.path so local module 'synthetic' (one level up) can be imported
import sys
from pathlib import Path # for path manipulations
parent_dir = Path.cwd().parent.parent.resolve() # move two levels up from current working directory
if str(parent_dir) not in sys.path: # check to avoid duplicates
    sys.path.insert(0, str(parent_dir)) # insert at the start of sys.path to prioritize local modules

# Loading a soil spectral dataset based on X-ray fluorescence (XRF)
data_complete = pd.read_csv(f'{parent_dir}/XRF_databases/forage/plsda/forage.csv', sep=';') # local copy of Toledo 2022 dataset (os ... indica para omitir o caminho longo)
data = data_complete.loc[:, '1.4':'20.81']

# Split dataset by class and create calibration/prediction sets using Kennard-Stone (as in original pipeline)
data_A = data_complete[data_complete['Class'] == 'A'].reset_index(drop=True)
data_B = data_complete[data_complete['Class'] == 'B'].reset_index(drop=True)

# splitting the data into calibration and prediction sets by kennard-stone algorithm
XA_cal, XA_pred = ks.train_test_split(data_A.loc[:, '1.4':'20.81'], test_size=0.30)  # class A
XA_cal = XA_cal.reset_index(drop=True)
XA_pred = XA_pred.reset_index(drop=True)

XB_cal, XB_pred = ks.train_test_split(data_B.loc[:, '1.4':'20.81'], test_size=0.30)  # class B
XB_cal = XB_cal.reset_index(drop=True)
XB_pred = XB_pred.reset_index(drop=True)

Xcalclass = pd.concat([XA_cal, XB_cal], axis=0).reset_index(drop=True)  # concatenating both classes
Xpredclass = pd.concat([XA_pred, XB_pred], axis=0).reset_index(drop=True)
ycalclass = pd.Series(['A']*XA_cal.shape[0] + ['B']*XB_cal.shape[0])  # target for calibration set
ypredclass = pd.Series(['A']*XA_pred.shape[0] + ['B']*XB_pred.shape[0])  # target for prediction set

# preprocessings
import preprocessings as prepr  # preprocessing methods for XRF data

Xcalclass_prep, mean_calclass, mean_calclass_poisson  = prepr.poisson(Xcalclass, mc=True)
Xpredclass_prep = ((Xpredclass/np.sqrt(mean_calclass)) - mean_calclass_poisson)

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning:

'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.

2026-02-02 08:17:17,402 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning:

'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.

2026-02-02 08:17:17,411 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning:

'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning:

'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.

2026-02-02 08:17:17,435 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning:

'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.

2026-02-02 08:17:17,466 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning:

'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.

In [70]:
from modeling import svm_optimized

svm_model = svm_optimized(Xcalclass_prep, ycalclass, Xpredclass_prep, ypredclass, aim='classification', kernel='rbf')
svm_model[0]

,Model,Accuracy Cal,Sensitivity Cal,Specificity Cal,CM Cal,Accuracy Pred,Sensitivity Pred,Specificity Pred,CM Pred
0,SVC,1.0,1.0,1.0,"[[40, 0], [0, 95]]",1.0,1.0,1.0,"[[18, 0], [0, 42]]"

In [71]:
svm_model[4]

          SVC
0    0.007210
1    0.013846
2    0.019321
3    0.003134
4    0.009493
..        ...
130  0.996541
131  0.984049
132  0.995748
133  0.984071
134  0.984048

[135 rows x 1 columns]

In [72]:
# calculando a covariancia entre cada variável espectral e a predição do modelo SVM
cov_scores = []
y_pred = svm_model[4]['SVC'].values # using the continuous predictions from SVM, extracting as 1D array
for col in Xcalclass_prep.columns:
    x_values = Xcalclass_prep[col].values
    covariance = np.cov(x_values, y_pred)[0, 1] # covariance between x and y
    cov_scores.append(covariance)
cov_scores_df = pd.DataFrame(cov_scores, index=Xcalclass_prep.columns, columns=['Covariance'])
cov_scores_df = np.abs(cov_scores_df)
cov_scores_df.plot()

In [73]:
X_sv = svm_model[3].support_vectors_            # shape (n_SV, n_features)
alpha_dual = svm_model[3].dual_coef_.ravel()    # shape (n_SV,)

# Calculando os coeficientes p usando os vetores de suporte e os multiplicadores de Lagrange
pvetor = pd.DataFrame({'energia' : Xcalclass.columns,
                       'importance': (X_sv.T) @ alpha_dual})
pvetor['importance'] = np.abs(pvetor['importance'])
pvetor['importance'].plot()

In [74]:
# establishing spectral cuts based on expert knowledge of XRF spectra
spectral_cuts = [
('Al', 1.40, 1.63),
('Si', 1.63, 1.86),
('P', 1.86, 2.16),
('S', 2.16, 2.44),
('Rh L + Ar', 2.44, 3.10),
('K', 3.10, 3.46),
('Ca ka', 3.46, 3.86),
('Ca kb', 3.86, 4.16),
('background1', 4.14, 4.37),
('Ti ka', 4.37, 4.66),
('Ti kb', 4.66, 5.08),
('background2', 5.08, 5.72),
('Mn', 5.72, 6.10),
('Fe ka', 6.10, 6.76),
('Fe kb', 6.76, 7.20),
('Ni', 7.20, 7.69),
('background3', 7.69, 13.10),
('sum Fe' , 13.10, 13.63),
('background4', 13.63, 18.0),
('Compton scattering', 18.0, 19.70),
('Rayleight scattering', 19.70, 20.80)
]

import explaining as exp
spectral_zones_class = exp.extract_spectral_zones(Xcalclass_prep, spectral_cuts)
zone_sums_df = exp.aggregate_spectral_zones(spectral_zones_class, aggregator='extreme')
predicates_quantiles = exp.predicates_by_quantiles(zone_sums_df, [0.2, 0.4, 0.6, 0.8])
co_occurrence_matrix_df = predicates_quantiles[2]
predicate_info_dict = exp.create_predicate_info_dict(
    predicates_df=predicates_quantiles[0],
    predicate_indicator_df=predicates_quantiles[1],
    zone_aggregated_df=zone_sums_df,
    y_predicted_numeric=y_pred
)

## Pvector and SHAP

In [75]:
# VIP scores por energia
pvector_df = pd.DataFrame({
    'energy': pvetor['energia'],
    'Pvector': pvetor['importance'].values
})
pvector_df = pvector_df.sort_values(by='Pvector', ascending=False).reset_index(drop=True)
energy_to_zone_vip = {}
for zone_name, start, end in spectral_cuts:
    for e in pvector_df['energy']:
        ef = float(e)
        if start <= ef <= end:
            energy_to_zone_vip[e] = zone_name
pvector_df['Zone'] = pvector_df['energy'].map(energy_to_zone_vip)
pvector_unique_df = pvector_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
#shap_unique_df = pd.read_csv('shap_forage.csv', sep=';') # loading previously saved shap_unique_df
pvector_unique_df

   energy    Pvector                  Zone
0    6.42  29.020377                 Fe ka
1     3.7  21.276746                 Ca ka
2    1.74  20.460692                    Si
3    3.34  12.997443                     K
4    4.02   7.862402                 Ca kb
5    4.52   7.835278                 Ti ka
6    7.08   7.213706                 Fe kb
7    2.62   5.597003             Rh L + Ar
8    1.86   3.167416                     P
9    2.28   2.214821                     S
10  13.41   2.154293                sum Fe
11   1.62   2.151909                    Al
12   4.94   2.032520                 Ti kb
13   7.54   1.425007                    Ni
14   5.92   1.240119                    Mn
15  19.39   1.124331    Compton scattering
16  11.95   1.122248           background3
17  20.31   0.974562  Rayleight scattering
18  15.41   0.831623           background4
19   4.14   0.743773           background1
20   5.12   0.699431           background2
21  20.81   0.005513                   NaN

In [76]:
pvector_df = pd.DataFrame({
    'energy': pvetor['energia'],
    'Pvector': pvetor['importance'].values
})
pvector_df.sort_values(by='Pvector', ascending=False, inplace=True)#.reset_index(drop=True)
energy_to_zone_vip = {}
for zone_name, start, end in spectral_cuts:
    for e in pvector_df['energy']:
        ef = float(e)
        if start <= ef <= end:
            energy_to_zone_vip[e] = zone_name
pvector_df['Zone'] = pvector_df['energy'].map(energy_to_zone_vip)
pvector_unique_df = pvector_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
#pvector_unique_df = pvector_unique_df.sort_values(by='Pvector', ascending=False).reset_index(drop=True)
#shap_unique_df = pd.read_csv('shap_forage.csv', sep=';') # loading previously saved shap_unique_df
pvector_unique_df

   energy    Pvector                  Zone
0    6.42  29.020377                 Fe ka
1     3.7  21.276746                 Ca ka
2    1.74  20.460692                    Si
3    3.34  12.997443                     K
4    4.02   7.862402                 Ca kb
5    4.52   7.835278                 Ti ka
6    7.08   7.213706                 Fe kb
7    2.62   5.597003             Rh L + Ar
8    1.86   3.167416                     P
9    2.28   2.214821                     S
10  13.41   2.154293                sum Fe
11   1.62   2.151909                    Al
12   4.94   2.032520                 Ti kb
13   7.54   1.425007                    Ni
14   5.92   1.240119                    Mn
15  19.39   1.124331    Compton scattering
16  11.95   1.122248           background3
17  20.31   0.974562  Rayleight scattering
18  15.41   0.831623           background4
19   4.14   0.743773           background1
20   5.12   0.699431           background2
21  20.81   0.005513                   NaN

# **bagging - covariance**

In [77]:
import explaining as exp

# LISTA DE SEMENTES A TESTAR
random_seeds = [0, 1, 2, 3]

all_results_cov = {}
training_samples = len(Xcalclass)

# LOOP: PROCESSAR CADA SEMENTE
y_predicted_numeric = pd.Series(y_pred) # predições numéricas do modelo

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando semente: {seed}")
    print(f"{'='*70}\n")
    # Bagging
    bags_result_seed = exp.bagging_predicates(
        zone_sums_df=zone_sums_df,
        y_predicted_numeric=y_predicted_numeric,
        predicates_df=predicates_quantiles[0],
        n_bags=10,
        #n_predicates_per_bag=40,
        n_samples_per_bag=int(training_samples*0.8), # 80 % da base para amostrar (convertido para int)
        min_samples_per_predicate=int(training_samples*0.2), # 20 % da base para limitar (convertido para int)
        replace=False,
        sample_bagging=True,
        predicate_bagging=False,
        random_seed=seed
    )
    
    # Inserir classe prevista
    for bag_name, pred_dict in bags_result_seed.items(): # iterando sobre cada bag
        for pred_rule, df_info in pred_dict.items():
            df_info['Class_Predicted'] = np.where(df_info['Predicted_Y'] >= 0.5, 'A', 'B') # binarizando com threshold 0.5, A = eut, B = dist
    
    # Calcular MI
    cov_results_dict_seed = exp.calculate_predicate_metrics(
        bags_result=bags_result_seed,
        metric='mutual_info', # covariance ou mutual_information
        threshold=0.01, # threshold para cortar predicados irrelevantes
        n_neighbors=5
    )
    
    # Salvar no dicionário principal
    all_results_cov[seed] = {
        'bags_result': bags_result_seed,
        'cov_results_dict': cov_results_dict_seed
    }

# CONSTRUÇÃO DE GRAFOS PARA MÚLTIPLAS SEMENTES (LOOP EXTERNO)
# Dicionário para armazenar grafos
graphs_by_seed = {}

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando Grafo - Semente: {seed}")
    print(f"{'='*70}\n")
    # Construir grafo para esta semente
    DG = exp.build_predicate_graphv2(
        bags_result=all_results_cov[seed]['bags_result'],
        predicate_ranking_dict=all_results_cov[seed]['cov_results_dict'],
        metric_column='Covariance',  # ou 'Covariance' se mudar a métrica
        random_state=seed,
        show_details=True
    )
    # Armazenar grafo
    graphs_by_seed[seed] = DG

# Calcular LRC usando a função pronta do explaining.py
lrc_cov_by_seed = {}
for seed in random_seeds:
    DG = graphs_by_seed[seed]
    lrc_cov_df_seed = exp.calculate_lrc_single_graph(DG, predicates_quantiles[0])
    lrc_cov_df_seed['Seed'] = seed  # Adicionar coluna com a semente
    lrc_cov_by_seed[seed] = lrc_cov_df_seed

# junando todas as colunas 'Node' de lrc_by_seed em um único dataframe
lrc_cov_all_seeds_df = pd.DataFrame()
for seed in random_seeds:
    lrc_cov_df_seed = lrc_cov_by_seed[seed].rename(columns={'Node': f'Predicate_Cov_Seed_{seed}'})
    lrc_cov_all_seeds_df = pd.concat([lrc_cov_all_seeds_df, lrc_cov_df_seed[[f'Predicate_Cov_Seed_{seed}']]], axis=1)

# vamos filtrar lrc_by_seed em cada semente para manter apenas as zonas espectrais únicas com maior LRC em um mesmo dataframe
lrc_cov_unique_by_seed = {}
for seed, lrc_df in lrc_cov_by_seed.items():
    lrc_cov_unique_df = lrc_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
    lrc_cov_unique_df = lrc_cov_unique_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
    lrc_cov_unique_by_seed[seed] = lrc_cov_unique_df

lrc_cov_all_seeds_df # exibindo o dataframe consolidado com predicados de todas as sementes

======================================================================
Processando semente: 0
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Calculando Mutual_Info para Predicados
Métrica: mutual_info
Threshold: 0.01

======================================================================
Processando semente: 1
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 127 | Descartados: 41
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 127 | Descartados: 41
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 127 | Descartados: 41
Calculando Mutual_Info para Predicados
Métrica: mutual_info
Threshold: 0.01

======================================================================
Processando semente: 2
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 128 | Descartados: 40
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 127 | Descartados: 41
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 127 | Descartados: 41

KeyboardInterrupt:

In [ ]:
# Somar LRCs de predicados equivalentes entre diferentes seeds
lrc_combined_list = []

for seed in random_seeds:
    lrc_df = lrc_cov_by_seed[seed].copy()
    lrc_combined_list.append(lrc_df) # o append adiciona o dataframe ao final da lista

# Concatenar todos os dataframes
lrc_all_seeds = pd.concat(lrc_combined_list, ignore_index=True) 

# Agrupar por predicado (Node) e somar as LRCs, mantendo Zone, Threshold e Operator
lrc_summed_df = lrc_all_seeds.groupby('Node').agg({ # o .agg pode ser usado para aplicar múltiplas funções de agregação
    'Local_Reaching_Centrality': 'mean', # sum = somando as LRCs, poderia ser média ou outro agregado
    'Zone': 'first',
    'Threshold': 'first',
    'Operator': 'first'
}).reset_index()

# Ordenar pelo valor de LRC somado (maior para menor)
lrc_summed_df = lrc_summed_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
# vamoss pegar so os valore sunicos de lrc_summed_df baseado na zona espectral
lrc_summed_unique_df_cov = lrc_summed_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
#lrc_summed_unique_df_cov = lrc_summed_unique_df_cov.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
lrc_summed_unique_df_cov

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator
0,Fe ka > -1.26,15.771598,Fe ka,-1.26,>
1,Ca ka <= 1.96,6.795023,Ca ka,1.96,<=
2,Si > -0.73,6.237653,Si,-0.73,>
3,K > -2.69,5.950879,K,-2.69,>
4,Ti ka > -0.34,2.117693,Ti ka,-0.34,>
5,Rh L + Ar > -0.42,1.703880,Rh L + Ar,-0.42,>
6,Fe kb > -0.40,1.650648,Fe kb,-0.40,>
7,Ca kb <= 0.31,1.628369,Ca kb,0.31,<=
8,background43 <= -0.17,0.652483,background43,-0.17,<=
9,Al > -0.33,0.589312,Al,-0.33,>
10,Ti kb > -0.16,0.524561,Ti kb,-0.16,>
11,P > 0.26,0.495354,P,0.26,>
12,Compton scattering > -0.17,0.423259,Compton scattering,-0.17,>
13,sum Fe > 0.13,0.356821,sum Fe,0.13,>
14,background44 > 0.16,0.325216,background44,0.16,>
15,background31 <= -0.11,0.323403,background31,-0.11,<=
16,Rayleight scattering > -0.19,0.314271,Rayleight scattering,-0.19,>
17,Mn <= 0.47,0.311564,Mn,0.47,<=
18,background32 <= 0.21,0.310952,background32,0.21,<=
19,background45 > -0.17,0.285994,background45,-0.17,>
20,background35 <= 0.17,0.281539,background35,0.17,<=
21,background42 > 0.14,0.258286,background42,0.14,>
22,background41 > -0.18,0.257103,background41,-0.18,>
23,Ni <= 0.17,0.248130,Ni,0.17,<=
24,S <= 0.29,0.238797,S,0.29,<=
25,background36 > 0.17,0.223101,background36,0.17,>
26,background34 <= 0.24,0.215441,background34,0.24,<=
27,background33 > -0.21,0.212512,background33,-0.21,>
28,background2 > -0.11,0.194355,background2,-0.11,>
29,background1 <= 0.15,0.189835,background1,0.15,<=
30,Class_A,0.000000,None,None,None

# **Perturbation**

In [ ]:
ycalres = np.where(svm_model[1]['SVC'] == 'A', 1, 0)

In [ ]:
import explaining as exp

# LISTA DE SEMENTES A TESTAR
random_seeds = [0, 1, 2, 3]

all_results_pert = {}
training_samples = len(Xcalclass)

# LOOP: PROCESSAR CADA SEMENTE
y_predicted_numeric = pd.Series(y_pred) # predições numéricas do modelo

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando semente: {seed}")
    print(f"{'='*70}\n")
    # Bagging
    bags_result_seed = exp.bagging_predicates(
        zone_sums_df=zone_sums_df,
        y_predicted_numeric=y_predicted_numeric,
        predicates_df=predicates_quantiles[0],
        n_bags=10,
        #n_predicates_per_bag=40,
        n_samples_per_bag=int(training_samples*0.8), # 80 % da base para amostrar (convertido para int)
        min_samples_per_predicate=int(training_samples*0.2), # 20 % da base para limitar (convertido para int)
        replace=False,
        sample_bagging=True,
        predicate_bagging=False,
        random_seed=seed
    )
    # Inserir classe prevista
    for bag_name, pred_dict in bags_result_seed.items(): # iterando sobre cada bag
        for pred_rule, df_info in pred_dict.items():
            df_info['Class_Predicted'] = np.where(df_info['Predicted_Y'] >= 0.5, 'A', 'B') # binarizando com threshold 0.5, A = eut, B = dist

    pert_results_seed = exp.calculate_predicate_perturbation(
        estimator=svm_model[3],
        Xcalclass_prep=Xcalclass_prep,
        folds_struct=bags_result_seed,
        predicates_df=predicates_quantiles[0],
        spectral_cuts=spectral_cuts,
        #perturbation_value=0,
        perturbation_mode='median', # valores entre 'mean' ou 'min'
        stats_source='full', # full indica usar todas as amostras para calcular estatísticas enquanto que 'fold' usa apenas as amostras do fold atual
        #metric='mean_abs_diff',   # Média com sinal (pode ser negativo)
        aim='classification',
        metric='prediction_change_rate', 
        verbose=True
    )

    # Remove todos os valores iguais a zero de todos os bags em perm_results[bag]["Permutation"] e salva como perm_results_thresholded
    # pert_results_seed_thresholded = {}
    # for bag, df in perm_results_seed.items():
    #     # Verifica se é um DataFrame e se a coluna 'Permutation' existe
    #     if isinstance(df, pd.DataFrame) and 'Permutation' in df.columns:
    #         filtered_df = df[df['Permutation'] > 0].copy()
    #         pert_results_seed_thresholded[bag] = filtered_df
    #     else:
    #         # Se não for DataFrame esperado, apenas copia
    #         pert_results_seed_thresholded[bag] = df

    # Salvar no dicionário principal
    all_results_pert[seed] = {
        'bags_result': bags_result_seed,
        'pert_results_dict': pert_results_seed
    }

# CONSTRUÇÃO DE GRAFOS PARA MÚLTIPLAS SEMENTES (LOOP EXTERNO)
# Dicionário para armazenar grafos
graphs_pert_by_seed = {}

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando Grafo - Semente: {seed}")
    print(f"{'='*70}\n")
    # Construir grafo para esta semente
    DG = exp.build_predicate_graphv2(
        bags_result=all_results_pert[seed]['bags_result'],
        predicate_ranking_dict=all_results_pert[seed]['pert_results_dict'],
        metric_column='Perturbation',  # ou 'Covariance' se mudar a métrica
        random_state=seed,
        show_details=True
    )
    # Armazenar grafo
    graphs_pert_by_seed[seed] = DG  

# Calcular LRC usando a função pronta do explaining.py
lrc_pert_by_seed = {}
for seed in random_seeds:
    DG = graphs_pert_by_seed[seed]
    lrc_pert_df_seed = exp.calculate_lrc_single_graph(DG, predicates_quantiles[0])
    lrc_pert_df_seed['Seed'] = seed  # Adicionar coluna com a semente
    lrc_pert_by_seed[seed] = lrc_pert_df_seed

# junando todas as colunas 'Node' de lrc_by_seed em um único dataframe
lrc_pert_all_seeds_df = pd.DataFrame()
for seed in random_seeds:
    lrc_pert_df_seed = lrc_pert_by_seed[seed].rename(columns={'Node': f'Predicate_pert_Seed_{seed}'})
    lrc_pert_all_seeds_df = pd.concat([lrc_pert_all_seeds_df, lrc_pert_df_seed[[f'Predicate_pert_Seed_{seed}']]], axis=1)

# vamos filtrar lrc_by_seed em cada semente para manter apenas as zonas espectrais únicas com maior LRC em um mesmo dataframe
lrc_pert_unique_by_seed = {}
for seed, lrc_df in lrc_pert_by_seed.items():
    lrc_pert_unique_df = lrc_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
    lrc_pert_unique_df = lrc_pert_unique_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
    lrc_pert_unique_by_seed[seed] = lrc_pert_unique_df

lrc_pert_all_seeds_df # exibindo o dataframe consolidado com predicados de todas as sementes

======================================================================
Processando semente: 0
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 180 | Descartados: 60
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 180 | Descartados: 60
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 180 | Descartados: 60
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 181 | Descartados: 59
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 180 | Descartados: 60
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 180 | Descartados: 60
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 183 | Descartados: 57
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 180 | Descartados: 60
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 180 | Descartados: 60
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 180 | Descartados: 60
======================================================================
PERTURBATION IMPORTANCE PARA PREDICADOS
======================================================================
Tipo de tarefa (aim): classification
Modo de perturbação: median
Fonte das estatísticas: full
Métrica: prediction_change_rate
Total de folds: 10


[Bag_1] Processando 180 predicados...
  Predicado: Al > -0.33 (n=86)
    Zona: 12 colunas
    Importance: 0.000000
  Predicado: Al <= -0.17 (n=44)
    Zona: 12 colunas
    Importance: 0.000000
  Predicado: Al > -0.17 (n=64)
    Zona: 12 colunas
    Importance: 0.000000
  Predicado: Al <= 0.16 (n=65)
    Zona: 12 colunas
    Importance: 0.000000
  Predicado: Al > 0.16 (n=43)
    Zona: 12 colunas
    Importance: 0.000000
  Predicado: Al <= 0.34 (n=87)
    Zona: 12 colunas
    Importance: 0.000000
  Predicado: Si > -1.10 (n=84)
    Zona: 12 colunas
    Importance: 0.047619
  Predicado: Si <= -0.73 (n=45)
    Zona: 12 colunas
    Importance: 0.000000
  Predicado: Si > -0.73 (n=63)
    Zona: 12 colunas
    Importance: 0.063492
  Predicado: Si <= -0.34 (n=65)
    Zona: 12 colunas
    Importance: 0.000000
  Predicado: Si > -0.34 (n=43)
    Zona: 12 colunas
    Importance: 0.093023
  Predicado: Si <= 1.59 (n=85)
    Zona: 12 colunas
    Importance: 0.000000
  Predicado: P > -0.58 (n=90)
    Zona: 16 colunas
    Importance: 0.000000
  Predicado: P <= -0.30 (n=44)
    Zona: 16 colunas
    Importance: 0.000000
  Predicado: P > -0.30 (n=64)
    Zona: 16 colunas
    Importance: 0.000000
  Predicado: P <= 0.26 (n=62)
    Zona: 16 colunas
    Importance: 0.000000
  Predicado: P > 0.26 (n=46)
    Zona: 16 colunas
    Importance: 0.000000
  Predicado: P <= 0.51 (n=84)
    Zona: 16 colunas
    Importance: 0.000000
  Predicado: S > -0.28 (n=86)
    Zona: 15 colunas
    Importance: 0.000000
  Predicado: S <= -0.18 (n=39)
    Zona: 15 colunas
    Importance: 0.000000
  Predicado: S > -0.18 (n=69)
    Zona: 15 colunas
    Importance: 0.000000
  Predicado: S <= 0.14 (n=62)
    Zona: 15 colunas
    Importance: 0.000000
  Predicado: S > 0.14 (n=46)
    Zona: 15 colunas
    Importance: 0.000000
  Predicado: S <= 0.29 (n=85)
    Zona: 15 colunas
    Importance: 0.000000
  Predicado: Rh L + Ar > -0.78 (n=91)
    Zona: 34 colunas
    Importance: 0.000000
  Predicado: Rh L + Ar <= -0.42 (n=36)
    Zona: 34 colunas
    Importance: 0.000000
  Predicado: Rh L + Ar > -0.42 (n=72)
    Zona: 34 colunas
    Importance: 0.000000
  Predicado: Rh L + Ar <= -0.13 (n=63)
    Zona: 34 colunas
    Importance: 0.000000
  Predicado: Rh L + Ar > -0.13 (n=45)
    Zona: 34 colunas
    Importance: 0.000000
  Predicado: Rh L + Ar <= 0.63 (n=89)
    Zona: 34 colunas
    Importance: 0.000000
  Predicado: K > -2.69 (n=87)
    Zona: 19 colunas
    Importance: 0.000000
  Predicado: K <= -0.94 (n=43)
    Zona: 19 colunas
    Importance: 0.000000
  Predicado: K > -0.94 (n=65)
    Zona: 19 colunas
    Importance: 0.000000
  Predicado: K <= 0.94 (n=66)
    Zona: 19 colunas
    Importance: 0.000000
  Predicado: K > 0.94 (n=42)
    Zona: 19 colunas
    Importance: 0.000000
  Predicado: K <= 2.49 (n=86)
    Zona: 19 colunas
    Importance: 0.000000
  Predicado: Ca ka > -2.11 (n=86)
    Zona: 21 colunas
    Importance: 0.000000
  Predicado: Ca ka <= -0.97 (n=45)
    Zona: 21 colunas
    Importance: 0.022222
  Predicado: Ca ka > -0.97 (n=63)
    Zona: 21 colunas
    Importance: 0.000000
  Predicado: Ca ka <= 0.86 (n=67)
    Zona: 21 colunas
    Importance: 0.014925
  Predicado: Ca ka > 0.86 (n=41)
    Zona: 21 colunas
    Importance: 0.000000
  Predicado: Ca ka <= 1.96 (n=87)
    Zona: 21 colunas
    Importance: 0.011494
  Predicado: Ca kb > -0.79 (n=87)
    Zona: 16 colunas
    Importance: 0.000000
  Predicado: Ca kb <= -0.30 (n=44)
    Zona: 16 colunas
    Importance: 0.000000
  Predicado: Ca kb > -0.30 (n=64)
    Zona: 16 colunas
    Importance: 0.000000
  Predicado: Ca kb <= 0.31 (n=67)
    Zona: 16 colunas
    Importance: 0.000000
  Predicado: Ca kb > 0.31 (n=41)
    Zona: 16 colunas
    Importance: 0.000000
  Predicado: Ca kb <= 0.69 (n=86)
    Zona: 16 colunas
    Importance: 0.000000
  Predicado: background1 > -0.14 (n=91)
    Zona: 12 colunas
    Importance: 0.000000
  Predicado: background1 <= -0.09 (n=44)
    Zona: 12 colunas
    Importance: 0.000000
  Predicado: background1 > -0.09 (n=64)
    Zona: 12 colunas
    Importance: 0.000000
  Predicado: background1 <= 0.10 (n=68)
    Zona: 12 colunas
    Importance: 0.000000
  Predicado: background1 > 0.10 (n=40)
    Zona: 12 colunas
    Importance: 0.000000
  Predicado: background1 <= 0.15 (n=89)
    Zona: 12 colunas
    Importance: 0.000000
  Predicado: Ti ka > -0.40 (n=86)
    Zona: 15 colunas
    Importance: 0.000000
  Predicado: Ti ka <= -0.34 (n=43)
    Zona: 15 colunas
    Importance: 0.000000
  Predicado: Ti ka > -0.34 (n=65)
    Zona: 15 colunas
    Importance: 0.000000
  Predicado: Ti ka <= -0.26 (n=65)
    Zona: 15 colunas
    Importance: 0.000000
  Predicado: Ti ka > -0.26 (n=43)
    Zona: 15 colunas
    Importance: 0.000000
  Predicado: Ti ka <= 0.27 (n=87)
    Zona: 15 colunas
    Importance: 0.000000
  Predicado: Ti kb > -0.16 (n=86)
    Zona: 22 colunas
    Importance: 0.000000
  Predicado: Ti kb <= -0.13 (n=43)
    Zona: 22 colunas
    Importance: 0.000000
  Predicado: Ti kb > -0.13 (n=65)
    Zona: 22 colunas
    Importance: 0.000000
  Predicado: Ti kb <= 0.11 (n=66)
    Zona: 22 colunas
    Importance: 0.000000
  Predicado: Ti kb > 0.11 (n=42)
    Zona: 22 colunas
    Importance: 0.000000
  Predicado: Ti kb <= 0.18 (n=89)
    Zona: 22 colunas
    Importance: 0.000000
  Predicado: background2 > -0.15 (n=88)
    Zona: 33 colunas
    Importance: 0.000000
  Predicado: background2 <= -0.11 (n=43)
    Zona: 33 colunas
    Importance: 0.000000
  Predicado: background2 > -0.11 (n=65)
    Zona: 33 colunas
    Importance: 0.000000
  Predicado: background2 <= 0.12 (n=66)
    Zona: 33 colunas
    Importance: 0.000000
  Predicado: background2 > 0.12 (n=42)
    Zona: 33 colunas
    Importance: 0.000000
  Predicado: background2 <= 0.16 (n=91)
    Zona: 33 colunas
    Importance: 0.000000
  Predicado: Mn > -0.52 (n=90)
    Zona: 20 colunas
    Importance: 0.000000
  Predicado: Mn <= -0.21 (n=43)
    Zona: 20 colunas
    Importance: 0.000000
  Predicado: Mn > -0.21 (n=65)
    Zona: 20 colunas
    Importance: 0.000000
  Predicado: Mn <= 0.18 (n=65)
    Zona: 20 colunas
    Importance: 0.000000
  Predicado: Mn > 0.18 (n=43)
    Zona: 20 colunas
    Importance: 0.000000
  Predicado: Mn <= 0.47 (n=89)
    Zona: 20 colunas
    Importance: 0.000000
  Predicado: Fe ka > -1.49 (n=85)
    Zona: 34 colunas
    Importance: 0.000000
  Predicado: Fe ka <= -1.26 (n=42)
    Zona: 34 colunas
    Importance: 0.000000
  Predicado: Fe ka > -1.26 (n=66)
    Zona: 34 colunas
    Importance: 0.000000
  Predicado: Fe ka <= -0.89 (n=63)
    Zona: 34 colunas
    Importance: 0.000000
  Predicado: Fe ka > -0.89 (n=45)
    Zona: 34 colunas
    Importance: 0.000000
  Predicado: Fe ka <= 0.50 (n=87)
    Zona: 34 colunas
    Importance: 0.000000
  Predicado: Fe kb > -0.40 (n=88)
    Zona: 23 colunas
    Importance: 0.000000
  Predicado: Fe kb <= -0.31 (n=41)
    Zona: 23 colunas
    Importance: 0.000000
  Predicado: Fe kb > -0.31 (n=67)
    Zona: 23 colunas
    Importance: 0.000000
  Predicado: Fe kb <= -0.23 (n=67)
    Zona: 23 colunas
    Importance: 0.000000
  Predicado: Fe kb > -0.23 (n=41)
    Zona: 23 colunas
    Importance: 0.000000
  Predicado: Fe kb <= 0.29 (n=87)
    Zona: 23 colunas
    Importance: 0.000000
  Predicado: Ni > -0.26 (n=88)
    Zona: 25 colunas
    Importance: 0.000000
  Predicado: Ni <= -0.19 (n=44)
    Zona: 25 colunas
    Importance: 0.000000
  Predicado: Ni > -0.19 (n=64)
    Zona: 25 colunas
    Importance: 0.000000
  Predicado: Ni <= 0.17 (n=69)
    Zona: 25 colunas
    Importance: 0.000000
  Predicado: Ni > 0.17 (n=39)
    Zona: 25 colunas
    Importance: 0.000000
  Predicado: Ni <= 0.26 (n=92)
    Zona: 25 colunas
    Importance: 0.000000
  Predicado: background31 > -0.18 (n=90)
    Zona: 21 colunas
    Importance: 0.000000
  Predicado: background31 <= -0.11 (n=47)
    Zona: 21 colunas
    Importance: 0.000000
  Predicado: background31 > -0.11 (n=61)
    Zona: 21 colunas
    Importance: 0.000000
  Predicado: background31 <= 0.10 (n=65)
    Zona: 21 colunas
    Importance: 0.000000
  Predicado: background31 > 0.10 (n=43)
    Zona: 21 colunas
    Importance: 0.000000
  Predicado: background31 <= 0.18 (n=90)
    Zona: 21 colunas
    Importance: 0.000000
  Predicado: background32 > -0.20 (n=86)
    Zona: 71 colunas
    Importance: 0.000000
  Predicado: background32 <= -0.14 (n=44)
    Zona: 71 colunas
    Importance: 0.000000
  Predicado: background32 > -0.14 (n=64)
    Zona: 71 colunas
    Importance: 0.000000
  Predicado: background32 <= 0.14 (n=67)
    Zona: 71 colunas
    Importance: 0.000000
  Predicado: background32 > 0.14 (n=41)
    Zona: 71 colunas
    Importance: 0.000000
  Predicado: background32 <= 0.21 (n=88)
    Zona: 71 colunas
    Importance: 0.000000
  Predicado: background33 > -0.21 (n=88)
    Zona: 121 colunas
    Importance: 0.000000
  Predicado: background33 <= -0.15 (n=43)
    Zona: 121 colunas
    Importance: 0.000000
  Predicado: background33 > -0.15 (n=65)
    Zona: 121 colunas
    Importance: 0.000000
  Predicado: background33 <= 0.14 (n=64)
    Zona: 121 colunas
    Importance: 0.000000
  Predicado: background33 > 0.14 (n=44)
    Zona: 121 colunas
    Importance: 0.000000
  Predicado: background33 <= 0.23 (n=88)
    Zona: 121 colunas
    Importance: 0.000000
  Predicado: background34 > -0.21 (n=87)
    Zona: 171 colunas
    Importance: 0.000000
  Predicado: background34 <= -0.17 (n=42)
    Zona: 171 colunas
    Importance: 0.000000
  Predicado: background34 > -0.17 (n=66)
    Zona: 171 colunas
    Importance: 0.000000
  Predicado: background34 <= 0.17 (n=68)
    Zona: 171 colunas
    Importance: 0.000000
  Predicado: background34 > 0.17 (n=40)
    Zona: 171 colunas
    Importance: 0.000000
  Predicado: background34 <= 0.24 (n=90)
    Zona: 171 colunas
    Importance: 0.000000
  Predicado: background35 > -0.24 (n=88)
    Zona: 221 colunas
    Importance: 0.000000
  Predicado: background35 <= -0.17 (n=44)
    Zona: 221 colunas
    Importance: 0.000000
  Predicado: background35 > -0.17 (n=64)
    Zona: 221 colunas
    Importance: 0.000000
  Predicado: background35 <= 0.17 (n=68)
    Zona: 221 colunas
    Importance: 0.000000
  Predicado: background35 > 0.17 (n=40)
    Zona: 221 colunas
    Importance: 0.000000
  Predicado: background35 <= 0.27 (n=87)
    Zona: 221 colunas
    Importance: 0.000000
  Predicado: background36 > -0.24 (n=88)
    Zona: 271 colunas
    Importance: 0.000000
  Predicado: background36 <= -0.17 (n=45)
    Zona: 271 colunas
    Importance: 0.000000
  Predicado: background36 > -0.17 (n=63)
    Zona: 271 colunas
    Importance: 0.000000
  Predicado: background36 <= 0.17 (n=68)
    Zona: 271 colunas
    Importance: 0.000000
  Predicado: background36 > 0.17 (n=40)
    Zona: 271 colunas
    Importance: 0.000000
  Predicado: background36 <= 0.28 (n=88)
    Zona: 271 colunas
    Importance: 0.000000
  Predicado: sum Fe > -0.24 (n=89)
    Zona: 27 colunas
    Importance: 0.000000
  Predicado: sum Fe <= -0.15 (n=45)
    Zona: 27 colunas
    Importance: 0.000000
  Predicado: sum Fe > -0.15 (n=63)
    Zona: 27 colunas
    Importance: 0.000000
  Predicado: sum Fe <= 0.13 (n=70)
    Zona: 27 colunas
    Importance: 0.000000
  Predicado: sum Fe > 0.13 (n=38)
    Zona: 27 colunas
    Importance: 0.000000
  Predicado: sum Fe <= 0.24 (n=88)
    Zona: 27 colunas
    Importance: 0.000000
  Predicado: background41 > -0.18 (n=87)
    Zona: 19 colunas
    Importance: 0.000000
  Predicado: background41 <= -0.13 (n=42)
    Zona: 19 colunas
    Importance: 0.000000
  Predicado: background41 > -0.13 (n=66)
    Zona: 19 colunas
    Importance: 0.000000
  Predicado: background41 <= 0.11 (n=66)
    Zona: 19 colunas
    Importance: 0.000000
  Predicado: background41 > 0.11 (n=42)
    Zona: 19 colunas
    Importance: 0.000000
  Predicado: background41 <= 0.19 (n=89)
    Zona: 19 colunas
    Importance: 0.000000
  Predicado: background42 > -0.22 (n=85)
    Zona: 69 colunas
    Importance: 0.000000
  Predicado: background42 <= -0.17 (n=40)
    Zona: 69 colunas
    Importance: 0.000000
  Predicado: background42 > -0.17 (n=68)
    Zona: 69 colunas
    Importance: 0.000000
  Predicado: background42 <= 0.14 (n=68)
    Zona: 69 colunas
    Importance: 0.000000
  Predicado: background42 > 0.14 (n=40)
    Zona: 69 colunas
    Importance: 0.000000
  Predicado: background42 <= 0.27 (n=90)
    Zona: 69 colunas
    Importance: 0.000000
  Predicado: background43 > -0.23 (n=86)
    Zona: 119 colunas
    Importance: 0.000000
  Predicado: background43 <= -0.17 (n=43)
    Zona: 119 colunas
    Importance: 0.000000
  Predicado: background43 > -0.17 (n=65)
    Zona: 119 colunas
    Importance: 0.000000
  Predicado: background43 <= 0.16 (n=69)
    Zona: 119 colunas
    Importance: 0.000000
  Predicado: background43 > 0.16 (n=39)
    Zona: 119 colunas
    Importance: 0.000000
  Predicado: background43 <= 0.28 (n=90)
    Zona: 119 colunas
    Importance: 0.000000
  Predicado: background44 > -0.23 (n=85)
    Zona: 169 colunas
    Importance: 0.000000
  Predicado: background44 <= -0.17 (n=43)
    Zona: 169 colunas
    Importance: 0.000000
  Predicado: background44 > -0.17 (n=65)
    Zona: 169 colunas
    Importance: 0.000000
  Predicado: background44 <= 0.16 (n=68)
    Zona: 169 colunas
    Importance: 0.000000
  Predicado: background44 > 0.16 (n=40)
    Zona: 169 colunas
    Importance: 0.000000
  Predicado: background44 <= 0.28 (n=90)
    Zona: 169 colunas
    Importance: 0.000000
  Predicado: background45 > -0.23 (n=85)
    Zona: 219 colunas
    Importance: 0.000000
  Predicado: background45 <= -0.17 (n=44)
    Zona: 219 colunas
    Importance: 0.000000
  Predicado: background45 > -0.17 (n=64)
    Zona: 219 colunas
    Importance: 0.000000
  Predicado: background45 <= 0.16 (n=68)
    Zona: 219 colunas
    Importance: 0.000000
  Predicado: background45 > 0.16 (n=40)
    Zona: 219 colunas
    Importance: 0.000000
  Predicado: background45 <= 0.28 (n=90)
    Zona: 219 colunas
    Importance: 0.000000
  Predicado: Compton scattering > -0.23 (n=87)
    Zona: 85 colunas
    Importance: 0.000000
  Predicado: Compton scattering <= -0.17 (n=44)
    Zona: 85 colunas
    Importance: 0.000000
  Predicado: Compton scattering > -0.17 (n=64)
    Zona: 85 colunas
    Importance: 0.000000
  Predicado: Compton scattering <= 0.14 (n=68)
    Zona: 85 colunas
    Importance: 0.000000
  Predicado: Compton scattering > 0.14 (n=40)
    Zona: 85 colunas
    Importance: 0.000000
  Predicado: Compton scattering <= 0.23 (n=87)
    Zona: 85 colunas
    Importance: 0.000000
  Predicado: Rayleight scattering > -0.19 (n=84)
    Zona: 55 colunas
    Importance: 0.000000
  Predicado: Rayleight scattering <= -0.14 (n=41)
    Zona: 55 colunas
    Importance: 0.000000
  Predicado: Rayleight scattering > -0.14 (n=67)
    Zona: 55 colunas
    Importance: 0.000000
  Predicado: Rayleight scattering <= -0.02 (n=68)
    Zona: 55 colunas
    Importance: 0.000000
  Predicado: Rayleight scattering > -0.02 (n=40)
    Zona: 55 colunas
    Importance: 0.000000
  Predicado: Rayleight scattering <= 0.20 (n=89)
    Zona: 55 colunas
    Importance: 0.000000

[Bag_2] Processando 180 predicados...
  Predicado: Al > -0.33 (n=83)
    Zona: 12 colunas
    Importance: 0.000000
  Predicado: Al <= -0.17 (n=46)
    Zona: 12 colunas
    Importance: 0.000000
  Predicado: Al > -0.17 (n=62)
    Zona: 12 colunas
    Importance: 0.000000
  Predicado: Al <= 0.16 (n=63)
    Zona: 12 colunas
    Importance: 0.000000
  Predicado: Al > 0.16 (n=45)
    Zona: 12 colunas
    Importance: 0.000000
  Predicado: Al <= 0.34 (n=86)
    Zona: 12 colunas
    Importance: 0.000000
  Predicado: Si > -1.10 (n=84)
    Zona: 12 colunas
    Importance: 0.035714
  Predicado: Si <= -0.73 (n=47)
    Zona: 12 colunas
    Importance: 0.000000
  Predicado: Si > -0.73 (n=61)
    Zona: 12 colunas
    Importance: 0.049180
  Predicado: Si <= -0.34 (n=68)
    Zona: 12 colunas
    Importance: 0.000000
  Predicado: Si > -0.34 (n=40)
    Zona: 12 colunas
    Importance: 0.075000
  Predicado: Si <= 1.59 (n=87)
    Zona: 12 colunas
    Importance: 0.000000
  Predicado: P > -0.58 (n=87)
    Zona: 16 colunas
    Importance: 0.000000
  Predicado: P <= -0.30 (n=45)
    Zona: 16 colunas
    Importance: 0.000000
  Predicado: P > -0.30 (n=63)
    Zona: 16 colunas
    Importance: 0.000000
  Predicado: P <= 0.26 (n=66)
    Zona: 16 colunas
    Importance: 0.000000
  Predicado: P > 0.26 (n=42)
    Zona: 16 colunas
    Importance: 0.000000
  Predicado: P <= 0.51 (n=87)
    Zona: 16 colunas
    Importance: 0.000000
  Predicado: S > -0.28 (n=87)
    Zona: 15 colunas
    Importance: 0.000000
  Predicado: S <= -0.18 (n=43)
    Zona: 15 colunas
    Importance: 0.000000
  Predicado: S > -0.18 (n=65)
    Zona: 15 colunas
    Importance: 0.000000
  Predicado: S <= 0.14 (n=66)
    Zona: 15 colunas
    Importance: 0.000000
  Predicado: S > 0.14 (n=42)
    Zona: 15 colunas
    Importance: 0.000000
  Predicado: S <= 0.29 (n=87)
    Zona: 15 colunas
    Importance: 0.000000
  Predicado: Rh L + Ar > -0.78 (n=88)
    Zona: 34 colunas
    Importance: 0.000000
  Predicado: Rh L + Ar <= -0.42 (n=42)
    Zona: 34 colunas
    Importance: 0.000000
  Predicado: Rh L + Ar > -0.42 (n=66)
    Zona: 34 colunas
    Importance: 0.000000
  Predicado: Rh L + Ar <= -0.13 (n=66)
    Zona: 34 colunas
    Importance: 0.000000
  Predicado: Rh L + Ar > -0.13 (n=42)
    Zona: 34 colunas
    Importance: 0.000000
  Predicado: Rh L + Ar <= 0.63 (n=90)
    Zona: 34 colunas
    Importance: 0.000000
  Predicado: K > -2.69 (n=84)
    Zona: 19 colunas
    Importance: 0.000000
  Predicado: K <= -0.94 (n=45)
    Zona: 19 colunas
    Importance: 0.000000
  Predicado: K > -0.94 (n=63)
    Zona: 19 colunas
    Importance: 0.000000
  Predicado: K <= 0.94 (n=65)
    Zona: 19 colunas
    Importance: 0.000000
  Predicado: K > 0.94 (n=43)
    Zona: 19 colunas
    Importance: 0.000000
  Predicado: K <= 2.49 (n=87)
    Zona: 19 colunas
    Importance: 0.000000
  Predicado: Ca ka > -2.11 (n=89)
    Zona: 21 colunas
    Importance: 0.000000
  Predicado: Ca ka <= -0.97 (n=40)
    Zona: 21 colunas
    Importance: 0.025000
  Predicado: Ca ka > -0.97 (n=68)
    Zona: 21 colunas
    Importance: 0.000000
  Predicado: Ca ka <= 0.86 (n=66)
    Zona: 21 colunas
    Importance: 0.015152
  Predicado: Ca ka > 0.86 (n=42)
    Zona: 21 colunas
    Importance: 0.000000
  Predicado: Ca ka <= 1.96 (n=87)
    Zona: 21 colunas
    Importance: 0.011494
  Predicado: Ca kb > -0.79 (n=89)
    Zona: 16 colunas
    Importance: 0.000000
  Predicado: Ca kb <= -0.30 (n=41)
    Zona: 16 colunas
    Importance: 0.000000
  Predicado: Ca kb > -0.30 (n=67)
    Zona: 16 colunas
    Importance: 0.000000
  Predicado: Ca kb <= 0.31 (n=67)

KeyboardInterrupt:

In [ ]:
all_results_pert[0]['pert_results_dict']['Bag_1']

                Predicate  Perturbation
0              Si > -0.34      0.155978
1              Si > -0.73      0.106638
2              Si > -1.10      0.080691
3          Ca ka <= -0.97      0.057797
4           Ca ka <= 0.86      0.039698
..                    ...           ...
175  background1 <= -0.09      0.000016
176   background1 <= 0.15      0.000014
177   background1 > -0.09      0.000014
178   background1 > -0.14      0.000013
179   background1 <= 0.10      0.000012

[180 rows x 2 columns]

In [ ]:
# Somar LRCs de predicados equivalentes entre diferentes seeds
lrc_combined_list = []

for seed in random_seeds:
    lrc_df = lrc_pert_by_seed[seed].copy()
    lrc_combined_list.append(lrc_df) # o append adiciona o dataframe ao final da lista

# Concatenar todos os dataframes
lrc_all_seeds = pd.concat(lrc_combined_list, ignore_index=True) 

# Agrupar por predicado (Node) e somar as LRCs, mantendo Zone, Threshold e Operator
lrc_summed_df = lrc_all_seeds.groupby('Node').agg({ # o .agg pode ser usado para aplicar múltiplas funções de agregação
    'Local_Reaching_Centrality': 'mean', # sum = somando as LRCs, poderia ser média ou outro agregado
    'Zone': 'first',
    'Threshold': 'first',
    'Operator': 'first'
}).reset_index()

# Ordenar pelo valor de LRC somado (maior para menor)
lrc_summed_df = lrc_summed_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
# vamoss pegar so os valore sunicos de lrc_summed_df baseado na zona espectral
lrc_summed_unique_df_pert = lrc_summed_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
lrc_summed_unique_df_pert = lrc_summed_unique_df_pert.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
lrc_summed_unique_df_pert

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator
0,Si > -0.34,35.426212,Si,-0.34,>
1,Ca ka <= -0.97,15.325063,Ca ka,-0.97,<=
2,Fe ka > -0.89,5.897840,Fe ka,-0.89,>
3,K > -0.94,1.167211,K,-0.94,>
4,Rh L + Ar > -0.13,1.005956,Rh L + Ar,-0.13,>
5,Ti ka > -0.26,0.879175,Ti ka,-0.26,>
6,Ca kb <= -0.30,0.810652,Ca kb,-0.30,<=
7,Fe kb > -0.23,0.664010,Fe kb,-0.23,>
8,background45 <= -0.23,0.348356,background45,-0.23,<=
9,background44 <= -0.23,0.311519,background44,-0.23,<=
10,background36 <= -0.17,0.205992,background36,-0.17,<=
11,background43 <= -0.23,0.126835,background43,-0.23,<=
12,background34 <= -0.21,0.126690,background34,-0.21,<=
13,background35 <= -0.17,0.122558,background35,-0.17,<=
14,background33 <= -0.21,0.098362,background33,-0.21,<=
15,P > 0.26,0.085667,P,0.26,>
16,Mn <= -0.21,0.078472,Mn,-0.21,<=
17,Compton scattering > 0.14,0.072322,Compton scattering,0.14,>
18,background42 <= -0.22,0.066391,background42,-0.22,<=
19,S > 0.14,0.063570,S,0.14,>
20,Ti kb <= -0.16,0.058260,Ti kb,-0.16,<=
21,background32 <= -0.20,0.053692,background32,-0.20,<=
22,sum Fe > 0.13,0.052960,sum Fe,0.13,>
23,background2 <= -0.11,0.046887,background2,-0.11,<=
24,Ni <= 0.17,0.045781,Ni,0.17,<=
25,Al > 0.16,0.044867,Al,0.16,>
26,Rayleight scattering > -0.02,0.043980,Rayleight scattering,-0.02,>
27,background41 <= -0.13,0.035701,background41,-0.13,<=
28,background31 <= -0.11,0.001930,background31,-0.11,<=
29,background1 <= -0.09,0.000407,background1,-0.09,<=
30,Class_B,0.000000,None,None,None

In [ ]:
lrc_all_seeds

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator,Seed
0,Si > -0.34,41.840824,Si,-0.34,>,0
1,Si > -0.73,31.164016,Si,-0.73,>,0
2,Si > -1.10,24.158209,Si,-1.10,>,0
3,Ca ka <= -0.97,18.775664,Ca ka,-0.97,<=,0
4,Ca ka <= 0.86,13.460118,Ca ka,0.86,<=,0
...,...,...,...,...,...,...
742,background1 <= 0.10,0.000319,background1,0.10,<=,3
743,background1 > -0.09,0.000202,background1,-0.09,>,3
744,background1 > -0.14,0.000095,background1,-0.14,>,3
745,Class_A,0.000000,None,None,None,3
746,Class_B,0.000000,None,None,None,3

In [ ]:
svm_model[1]['SVC']

0      A
1      A
2      A
3      A
4      A
      ..
130    B
131    B
132    B
133    B
134    B
Name: SVC, Length: 135, dtype: object

In [ ]:
# Permutation importance baseado em mudança nas probabilidades previstas (predict_proba)
# Medimos a média da diferença absoluta entre as probabilidades originais e as probabilidades
# obtidas após permutar cada variável. Isso fornece uma métrica contínua de importância.
n_repeats = 10
rng = np.random.RandomState(42)
# Probabilidades base (classe 'B' mapeada para 1)
baseline_proba = svm_model[3].predict_proba(Xcalclass_prep)[:, 1]
importance_list = []
X_arr = Xcalclass_prep.copy()
for col in Xcalclass_prep.columns:
    diffs = []
    for _ in range(n_repeats):
        X_perm = X_arr.copy()
        X_perm[col] = rng.permutation(X_perm[col].values)
        perm_proba = svm_model[3].predict_proba(X_perm)[:, 1]
        diffs.append(np.mean(np.abs(baseline_proba - perm_proba)))
    importance_list.append(np.mean(diffs))

permutation_df = pd.DataFrame({
    'energy': Xcalclass_prep.columns,
    'Permutation_importance_proba': importance_list
})
permutation_df.sort_values(by='Permutation_importance_proba', ascending=False, inplace=True)
energy_to_zone_vip = {}
for zone_name, start, end in spectral_cuts:
    for e in permutation_df['energy']:
        ef = float(e)
        if start <= ef <= end:
            energy_to_zone_vip[e] = zone_name
permutation_df['Zone'] = permutation_df['energy'].map(energy_to_zone_vip)
permutation_unique_df = permutation_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
permutation_unique_df = permutation_unique_df.sort_values(by='Permutation_importance_proba', ascending=False)
permutation_unique_df

   energy  Permutation_importance_proba                  Zone
0    6.42                      0.011613                 Fe ka
1    3.32                      0.005346                     K
2     3.7                      0.005293                 Ca ka
3    1.74                      0.004457                    Si
4    2.62                      0.000852             Rh L + Ar
5    4.02                      0.000572                 Ca kb
6    4.52                      0.000402                 Ti ka
7    7.06                      0.000338                 Fe kb
8       2                      0.000175                     P
9    5.88                      0.000128                    Mn
10    2.3                      0.000100                     S
11   1.56                      0.000060                    Al
12  13.41                      0.000043                sum Fe
13   7.52                      0.000040                    Ni
14   4.96                      0.000035                 Ti kb
15  11.89                      0.000029          background36
16  18.81                      0.000025    Compton scattering
17  15.43                      0.000022          background45
18  20.25                      0.000017  Rayleight scattering
19   4.34                      0.000011           background1
20    5.6                      0.000010           background2
21  20.81                      0.000010                   NaN

In [ ]:
import numpy as np

max_len = max(
    len(pvector_unique_df['Zone']),
    #len(shap_unique_df['Zone']),
    len(permutation_unique_df['Zone']),
    len(lrc_summed_unique_df_pert['Zone']),
    len(lrc_summed_unique_df_cov['Zone'])
)

def pad_list(lst, length):
    return list(lst) + [None] * (length - len(lst))

features_importance = pd.DataFrame({
    'SVM_pvector': pad_list(pvector_unique_df['Zone'], max_len),
    #'Shap': pad_list(shap_unique_df['Zone'], max_len),
    'Permutation' : pad_list(permutation_unique_df['Zone'], max_len),
    'LRC_perturbation' : pad_list(lrc_summed_unique_df_pert['Zone'], max_len),
    'LRC_covariance' : pad_list(lrc_summed_unique_df_cov['Zone'], max_len),
})

#features_importance.to_csv('feature_importance.csv', index=False, sep=';')
features_importance

,SVM_pvector,Permutation,LRC_perturbation,LRC_covariance
0,Fe ka,Fe ka,Si,Fe ka
1,Ca ka,K,Ca ka,Ca ka
2,Si,Ca ka,Fe ka,Si
3,K,Si,K,K
4,Ca kb,Rh L + Ar,Rh L + Ar,Ti ka
5,Ti ka,Ca kb,Ti ka,Rh L + Ar
6,Fe kb,Ti ka,Ca kb,Fe kb
7,Rh L + Ar,Fe kb,Fe kb,Ca kb
8,P,P,background45,background43
9,S,Mn,background44,Al
10,sum Fe,S,background36,Ti kb
11,Al,Al,background43,P
12,Ti kb,sum Fe,background34,Compton scattering
13,Ni,Ni,background35,sum Fe
14,Mn,Ti kb,background33,background44
15,Compton scattering,background36,P,background31
16,background36,Compton scattering,Mn,Rayleight scattering
17,Rayleight scattering,background45,Compton scattering,Mn
18,background45,Rayleight scattering,background42,background32
19,background1,background1,S,background45
20,background2,background2,Ti kb,background35
21,NaN,NaN,background32,background42
22,None,None,sum Fe,background41
23,None,None,background2,Ni
24,None,None,Ni,S
25,None,None,Al,background36
26,None,None,Rayleight scattering,background34
27,None,None,background41,background33
28,None,None,background31,background2
29,None,None,background1,background1
30,None,None,None,None

In [ ]:
import rbo
rbo_comparison = pd.DataFrame(columns=['Method_1', 'Method_2', 'RBO_Score'])
methods = features_importance.columns.tolist()
for i in range(len(methods)):
    for j in range(i + 1, len(methods)):
        method_1 = methods[i]
        method_2 = methods[j]
        # Remove None values from the lists
        list_1 = [x for x in features_importance[method_1].tolist() if x is not None]
        list_2 = [x for x in features_importance[method_2].tolist() if x is not None]
        # Truncate both lists to the same length (minimum of both)
        min_len = min(len(list_1), len(list_2))
        list_1_trunc = list_1[:min_len]
        list_2_trunc = list_2[:min_len]
        rbo_score = rbo.RankingSimilarity(list_1_trunc, list_2_trunc).rbo(p=0.7, k=10)
        rbo_comparison = pd.concat([rbo_comparison, pd.DataFrame({
            'Method_1': [method_1],
            'Method_2': [method_2],
            'RBO_Score': [rbo_score]
        })], ignore_index=True)
rbo_comparison.sort_values(by='RBO_Score', ascending=False, inplace=True)
#rbo_comparison.to_csv('rbo_rank.csv', index=False, sep=';')
rbo_comparison

C:\Users\Usuario\AppData\Local\Temp\ipykernel_16028\823134450.py:16: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

           Method_1          Method_2  RBO_Score
2       SVM_pvector    LRC_covariance   0.939558
0       SVM_pvector       Permutation   0.788690
4       Permutation    LRC_covariance   0.785558
5  LRC_perturbation    LRC_covariance   0.542962
1       SVM_pvector  LRC_perturbation   0.534558
3       Permutation  LRC_perturbation   0.400006