## Loading data

In [1]:
# Importing the necessary libraries
import pandas as pd
import numpy as np
import kennard_stone as ks
pd.options.plotting.backend = 'plotly'  # setting plotly as the backend for pandas plotting

# Add parent directory to sys.path so local module 'synthetic' (one level up) can be imported
import sys
from pathlib import Path # for path manipulations
parent_dir = Path.cwd().parent.parent.resolve() # move two levels up from current working directory
if str(parent_dir) not in sys.path: # check to avoid duplicates
    sys.path.insert(0, str(parent_dir)) # insert at the start of sys.path to prioritize local modules

# Loading a soil spectral dataset based on X-ray fluorescence (XRF)
data_complete = pd.read_csv(f'{parent_dir}/XRF_databases/soil_types/plsda/soil_types.csv', sep=';') # local copy of Toledo and Guarapuava soil datasets
data = data_complete.loc[:, '1':'15']

# Split dataset by class and create calibration/prediction sets using Kennard-Stone (as in original pipeline)
data_A = data_complete[data_complete['Class'] == 'A'].reset_index(drop=True)
data_B = data_complete[data_complete['Class'] == 'B'].reset_index(drop=True)

# splitting the data into calibration and prediction sets by kennard-stone algorithm
XA_cal, XA_pred = ks.train_test_split(data_A.loc[:, '1':'15'], test_size=0.30) # class A
XA_cal = XA_cal.reset_index(drop=True)
XA_pred = XA_pred.reset_index(drop=True)

XB_cal, XB_pred = ks.train_test_split(data_B.loc[:, '1':'15'], test_size=0.30) # class B
XB_cal = XB_cal.reset_index(drop=True)
XB_pred = XB_pred.reset_index(drop=True)

Xcalclass = pd.concat([XA_cal, XB_cal], axis=0).reset_index(drop=True) # concatenating both classes
Xpredclass = pd.concat([XA_pred, XB_pred], axis=0).reset_index(drop=True)
ycalclass = pd.Series(['A']*XA_cal.shape[0] + ['B']*XB_cal.shape[0]) # creating the target variable for calibration set
ypredclass = pd.Series(['A']*XA_pred.shape[0] + ['B']*XB_pred.shape[0]) # creating the target variable for prediction set

# preprocessings
import preprocessings as prepr # preprocessing methods for XRF data

Xcalclass_prep, mean_calclass, mean_calclass_poisson  = prepr.poisson(Xcalclass, mc=True)
Xpredclass_prep = ((Xpredclass/np.sqrt(mean_calclass)) - mean_calclass_poisson)

from modeling import pls_optimized

# performing PLS-DA with optimized latent variables
plsda_results = pls_optimized(Xcalclass_prep, 
                              ycalclass,
                              LVmax=2,
                              Xpred=Xpredclass_prep,
                              ypred=ypredclass,
                              aim='classification',
                              cv=10)
plsda_results[0]


# Convenience references used later
pls_model = plsda_results[3]               # fitted PLS model
vip_scores_mat = plsda_results[4]          # VIP scores matrix (features × LV)
y_pred_cont = plsda_results[5].iloc[:, -1] # continuous predictions for Xcalclass (used for MI/Cov)

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-01-30 05:34:57,290 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-01-30 05:34:57,522 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-01-30 05:34:57,628 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-01-30 05:34:58,003 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

In [2]:
from modeling import svm_optimized

svm_model = svm_optimized(Xcalclass_prep, ycalclass, Xpredclass_prep, ypredclass, aim='classification', kernel='rbf')
svm_model[0]

,Model,Accuracy Cal,Sensitivity Cal,Specificity Cal,CM Cal,Accuracy Pred,Sensitivity Pred,Specificity Pred,CM Pred
0,SVC,1.0,1.0,1.0,"[[247, 0], [0, 254]]",1.0,1.0,1.0,"[[107, 0], [0, 109]]"

In [3]:
svm_model[4]

          SVC
0    0.000288
1    0.001309
2    0.000348
3    0.000824
4    0.003448
..        ...
496  0.981421
497  0.996811
498  0.973922
499  0.990572
500  0.983134

[501 rows x 1 columns]

In [4]:
# calculando a covariancia entre cada variável espectral e a predição do modelo SVM
cov_scores = []
y_pred = svm_model[4]['SVC'].values # using the continuous predictions from SVM, extracting as 1D array
for col in Xcalclass_prep.columns:
    x_values = Xcalclass_prep[col].values
    covariance = np.cov(x_values, y_pred)[0, 1] # covariance between x and y
    cov_scores.append(covariance)
cov_scores_df = pd.DataFrame(cov_scores, index=Xcalclass_prep.columns, columns=['Covariance'])
cov_scores_df = np.abs(cov_scores_df)
cov_scores_df.plot()

In [5]:
X_sv = svm_model[3].support_vectors_            # shape (n_SV, n_features)
alpha_dual = svm_model[3].dual_coef_.ravel()    # shape (n_SV,)

# Calculando os coeficientes p usando os vetores de suporte e os multiplicadores de Lagrange
pvetor = pd.DataFrame({'energia' : Xcalclass.columns,
                       'importance': (X_sv.T) @ alpha_dual})
pvetor['importance'] = np.abs(pvetor['importance'])
pvetor['importance'].plot()

In [6]:
# establishing spectral cuts based on expert knowledge of XRF spectra
spectral_cuts = [
('background1', 1.0, 1.33),
('Al', 1.33, 1.63),
('Si', 1.63, 1.86),
('P', 1.86, 2.19),
('S', 2.19, 2.44),
('background2', 2.44, 2.55),
('Rh L + Ar', 2.55, 3.21),
('K', 3.21, 3.53),
('Ca ka', 3.53, 3.84),
('Ca kb', 3.84, 4.14),
('background3', 4.14, 4.37),
('Ti ka', 4.37, 4.66),
('background4', 4.66, 4.75),
('Ti kb', 4.75, 5.12),
('Cr', 5.12, 5.77),
('Mn', 5.77, 6.13),
('Fe ka', 6.13, 6.80),
('Fe kb', 6.80, 7.30),
('background5', 7.30, 7.91),
('Cu', 7.91, 8.20),
('background6', 8.20, 10.69),
('Fe ka + Ti ka', 10.69, 11.14),
('background7', 11.14, 12.55),
('sum Fe' , 12.55, 13.1),
('background8', 13.1, 15.0)
]

import explaining as exp
spectral_zones_class = exp.extract_spectral_zones(Xcalclass_prep, spectral_cuts)
zone_sums_df = exp.aggregate_spectral_zones(spectral_zones_class, aggregator='extreme')
predicates_quantiles = exp.predicates_by_quantiles(zone_sums_df, [0.2, 0.4, 0.6, 0.8])
co_occurrence_matrix_df = predicates_quantiles[2]
predicate_info_dict = exp.create_predicate_info_dict(
    predicates_df=predicates_quantiles[0],
    predicate_indicator_df=predicates_quantiles[1],
    zone_aggregated_df=zone_sums_df,
    y_predicted_numeric=y_pred_cont
)

## Pvector and SHAP

In [8]:
# VIP scores por energia
pvector_df = pd.DataFrame({
    'energy': pvetor['energia'],
    'Pvector': pvetor['importance'].values
})
pvector_df = pvector_df.sort_values(by='Pvector', ascending=False).reset_index(drop=True)
energy_to_zone_vip = {}
for zone_name, start, end in spectral_cuts:
    for e in pvector_df['energy']:
        ef = float(e)
        if start <= ef <= end:
            energy_to_zone_vip[e] = zone_name
pvector_df['Zone'] = pvector_df['energy'].map(energy_to_zone_vip)
pvector_unique_df = pvector_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
shap_unique_df = pd.read_csv('shap_soil_type.csv', sep=';') # loading previously saved shap_unique_df
pvector_unique_df

   energy    Pvector           Zone
0    6.42  38.467247          Fe ka
1    7.08  13.724904          Fe kb
2    3.34   7.900618              K
3    5.92   4.098178             Mn
4   12.84   3.565848         sum Fe
5    1.74   3.293812             Si
6    2.62   3.265029      Rh L + Ar
7    4.98   2.945963          Ti kb
8    8.06   2.873027             Cu
9     4.5   2.441015          Ti ka
10   4.68   2.126372    background4
11    5.4   2.075143             Cr
12   1.46   2.032300             Al
13   2.04   2.007031              P
14    9.3   1.783696    background6
15  11.16   1.670868    background7
16   7.76   1.515501    background5
17   3.58   1.484005          Ca ka
18  10.74   1.403656  Fe ka + Ti ka
19   2.54   1.390466    background2
20  13.48   1.366407    background8
21   4.12   1.142247          Ca kb
22   4.14   0.737711    background3
23   1.16   0.663877    background1
24   2.38   0.508497              S

# **bagging - covariance**

In [10]:
import explaining as exp

# LISTA DE SEMENTES A TESTAR
random_seeds = [0, 1, 2, 3]

all_results_cov = {}
training_samples = len(Xcalclass)

# LOOP: PROCESSAR CADA SEMENTE
y_predicted_numeric = pd.Series(y_pred) # predições numéricas do modelo

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando semente: {seed}")
    print(f"{'='*70}\n")
    # Bagging
    bags_result_seed = exp.bagging_predicates(
        zone_sums_df=zone_sums_df,
        y_predicted_numeric=y_predicted_numeric,
        predicates_df=predicates_quantiles[0],
        n_bags=10,
        #n_predicates_per_bag=40,
        n_samples_per_bag=int(training_samples*0.8), # 80 % da base para amostrar (convertido para int)
        min_samples_per_predicate=int(training_samples*0.2), # 20 % da base para limitar (convertido para int)
        replace=False,
        sample_bagging=True,
        predicate_bagging=False,
        random_seed=seed
    )
    
    # Inserir classe prevista
    for bag_name, pred_dict in bags_result_seed.items(): # iterando sobre cada bag
        for pred_rule, df_info in pred_dict.items():
            df_info['Class_Predicted'] = np.where(df_info['Predicted_Y'] >= 0.5, 'A', 'B') # binarizando com threshold 0.5, A = eut, B = dist
    
    # Calcular MI
    cov_results_dict_seed = exp.calculate_predicate_metrics(
        bags_result=bags_result_seed,
        metric='covariance', # covariance ou mutual_information
        threshold=0.01, # threshold para cortar predicados irrelevantes
        n_neighbors=5
    )
    
    # Salvar no dicionário principal
    all_results_cov[seed] = {
        'bags_result': bags_result_seed,
        'cov_results_dict': cov_results_dict_seed
    }

# CONSTRUÇÃO DE GRAFOS PARA MÚLTIPLAS SEMENTES (LOOP EXTERNO)
# Dicionário para armazenar grafos
graphs_by_seed = {}

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando Grafo - Semente: {seed}")
    print(f"{'='*70}\n")
    # Construir grafo para esta semente
    DG = exp.build_predicate_graphv2(
        bags_result=all_results_cov[seed]['bags_result'],
        predicate_ranking_dict=all_results_cov[seed]['cov_results_dict'],
        metric_column='Covariance',  # ou 'Covariance' se mudar a métrica
        random_state=seed,
        show_details=True
    )
    # Armazenar grafo
    graphs_by_seed[seed] = DG

# Calcular LRC usando a função pronta do explaining.py
lrc_cov_by_seed = {}
for seed in random_seeds:
    DG = graphs_by_seed[seed]
    lrc_cov_df_seed = exp.calculate_lrc_single_graph(DG, predicates_quantiles[0])
    lrc_cov_df_seed['Seed'] = seed  # Adicionar coluna com a semente
    lrc_cov_by_seed[seed] = lrc_cov_df_seed

# junando todas as colunas 'Node' de lrc_by_seed em um único dataframe
lrc_cov_all_seeds_df = pd.DataFrame()
for seed in random_seeds:
    lrc_cov_df_seed = lrc_cov_by_seed[seed].rename(columns={'Node': f'Predicate_Cov_Seed_{seed}'})
    lrc_cov_all_seeds_df = pd.concat([lrc_cov_all_seeds_df, lrc_cov_df_seed[[f'Predicate_Cov_Seed_{seed}']]], axis=1)

# vamos filtrar lrc_by_seed em cada semente para manter apenas as zonas espectrais únicas com maior LRC em um mesmo dataframe
lrc_cov_unique_by_seed = {}
for seed, lrc_df in lrc_cov_by_seed.items():
    lrc_cov_unique_df = lrc_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
    lrc_cov_unique_df = lrc_cov_unique_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
    lrc_cov_unique_by_seed[seed] = lrc_cov_unique_df

lrc_cov_all_seeds_df # exibindo o dataframe consolidado com predicados de todas as sementes

======================================================================
Processando semente: 0
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando semente: 1
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando semente: 2
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando semente: 3
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando Grafo - Semente: 0
======================================================================


Total de pares bidirecionais encontrados: 117
Removida aresta Fe ka <= 4.61 -> Fe ka > -3.73 (peso 1.5229)
Mantida aresta Fe ka > -3.73 -> Fe ka <= 4.61 (peso 13.7013)

======================================================================

Removida aresta Fe kb <= 1.68 -> Fe kb > -1.37 (peso 1.1074)
Mantida aresta Fe kb > -1.37 -> Fe kb <= 1.68 (peso 4.5126)

======================================================================

Removida aresta Mn <= 0.47 -> sum Fe <= 0.51 (peso 0.1563)
Mantida aresta sum Fe <= 0.51 -> Mn <= 0.47 (peso 1.2572)

======================================================================

Removida aresta Ti ka > -0.84 -> Mn <= 0.47 (peso 0.1557)
Mantida aresta Mn <= 0.47 -> Ti ka > -0.84 (peso 1.2135)

======================================================================

Removida aresta Rh L + Ar > -0.26 -> Si > -0.45 (peso 0.3751)
Mantida aresta Si > -0.45 -> Rh L + Ar > -0.26 (peso 0.3837)

======================================================================

Removida aresta Ti kb > -0.42 -> Rh L + Ar > -0.26 (peso 0.1198)
Mantida aresta Rh L + Ar > -0.26 -> Ti kb > -0.42 (peso 0.2490)

======================================================================

Removida aresta Rh L + Ar > -0.26 -> Ti ka > -0.37 (peso 0.1230)
Mantida aresta Ti ka > -0.37 -> Rh L + Ar > -0.26 (peso 0.5246)

======================================================================

Removida aresta Ti kb > -0.42 -> Si > -0.45 (peso 0.1235)
Mantida aresta Si > -0.45 -> Ti kb > -0.42 (peso 0.3684)

======================================================================

Removida aresta Si > -0.45 -> Rh L + Ar <= 0.36 (peso 0.1287)
Mantida aresta Rh L + Ar <= 0.36 -> Si > -0.45 (peso 0.2449)

======================================================================

Removida aresta Ti kb > -0.42 -> Rh L + Ar <= 0.36 (peso 0.2433)
Mantida aresta Rh L + Ar <= 0.36 -> Ti kb > -0.42 (peso 0.3598)

======================================================================

Removida aresta Mn > -0.33 -> Ti kb > -0.42 (peso 0.2351)
Mantida aresta Ti kb > -0.42 -> Mn > -0.33 (peso 0.3582)

======================================================================

Removida aresta Rh L + Ar <= 0.36 -> Mn > -0.33 (peso 0.2415)
Mantida aresta Mn > -0.33 -> Rh L + Ar <= 0.36 (peso 0.3678)

======================================================================

Removida aresta Rh L + Ar <= 0.36 -> Ti ka > -0.37 (peso 0.2413)
Mantida aresta Ti ka > -0.37 -> Rh L + Ar <= 0.36 (peso 0.2569)

======================================================================

Removida aresta background4 > -0.29 -> Ca ka > -0.82 (peso 0.1047)
Mantida aresta Ca ka > -0.82 -> background4 > -0.29 (peso 0.3210)

======================================================================

Removida aresta sum Fe > -0.27 -> Ca ka > -0.82 (peso 0.0912)
Mantida aresta Ca ka > -0.82 -> sum Fe > -0.27 (peso 0.0938)

======================================================================

Removida aresta Si > -0.25 -> sum Fe > -0.27 (peso 0.1801)
Mantida aresta sum Fe > -0.27 -> Si > -0.25 (peso 0.1876)

======================================================================

Removida aresta Ca ka > -0.82 -> background4 <= 0.35 (peso 0.0905)
Mantida aresta background4 <= 0.35 -> Ca ka > -0.82 (peso 0.1745)

======================================================================

Removida aresta Ti kb <= 0.48 -> background4 <= 0.35 (peso 0.0930)
Mantida aresta background4 <= 0.35 -> Ti kb <= 0.48 (peso 0.1805)

======================================================================

Removida aresta background4 <= 0.35 -> Si > -0.25 (peso 0.1778)
Mantida aresta Si > -0.25 -> background4 <= 0.35 (peso 0.2666)

======================================================================

Removida aresta Si <= 0.51 -> Cr > -0.26 (peso 0.1740)
Mantida aresta Cr > -0.26 -> Si <= 0.51 (peso 0.2546)

======================================================================

Removida aresta Si <= 0.51 -> Ti kb <= 0.48 (peso 0.0838)
Mantida aresta Ti kb <= 0.48 -> Si <= 0.51 (peso 0.0844)

======================================================================

Removida aresta Cu > -0.22 -> Si <= 0.51 (peso 0.1605)
Mantida aresta Si <= 0.51 -> Cu > -0.22 (peso 0.2472)

======================================================================

Removida aresta Si <= 0.51 -> Rh L + Ar > -0.21 (peso 0.0776)
Mantida aresta Rh L + Ar > -0.21 -> Si <= 0.51 (peso 0.1597)

======================================================================

Removida aresta Cr > -0.26 -> Ti kb <= 0.48 (peso 0.0859)
Mantida aresta Ti kb <= 0.48 -> Cr > -0.26 (peso 0.2570)

======================================================================

Removida aresta Rh L + Ar > -0.21 -> Ti kb <= 0.48 (peso 0.0824)
Mantida aresta Ti kb <= 0.48 -> Rh L + Ar > -0.21 (peso 0.1644)

======================================================================

Removida aresta Si > -0.25 -> Ti kb <= 0.48 (peso 0.0883)
Mantida aresta Ti kb <= 0.48 -> Si > -0.25 (peso 0.1704)

======================================================================

Removida aresta Cu > -0.22 -> Si > -0.25 (peso 0.0786)
Mantida aresta Si > -0.25 -> Cu > -0.22 (peso 0.1606)

======================================================================

Removida aresta Cr <= 0.28 -> Cu > -0.22 (peso 0.0795)
Mantida aresta Cu > -0.22 -> Cr <= 0.28 (peso 0.2444)

======================================================================

Removida aresta Ti kb > -0.23 -> Cu <= 0.25 (peso 0.0754)
Mantida aresta Cu <= 0.25 -> Ti kb > -0.23 (peso 0.1486)

======================================================================

Removida aresta background8 > -0.22 -> Ti kb > -0.23 (peso 0.0716)
Mantida aresta Ti kb > -0.23 -> background8 > -0.22 (peso 0.1489)

======================================================================

Removida aresta Ti kb > -0.23 -> Ti ka > 0.45 (peso 0.0745)
Mantida aresta Ti ka > 0.45 -> Ti kb > -0.23 (peso 0.0815)

======================================================================

Removida aresta background8 > -0.22 -> Cu <= 0.25 (peso 0.1489)
Mantida aresta Cu <= 0.25 -> background8 > -0.22 (peso 0.2959)

======================================================================

Removida aresta background8 <= 0.27 -> Cu <= 0.25 (peso 0.0748)
Mantida aresta Cu <= 0.25 -> background8 <= 0.27 (peso 0.2966)

======================================================================

Removida aresta background8 <= 0.27 -> background8 > -0.22 (peso 0.0719)
Mantida aresta background8 > -0.22 -> background8 <= 0.27 (peso 0.4305)

======================================================================

Removida aresta background4 > -0.17 -> Ti ka > 0.45 (peso 0.0643)
Mantida aresta Ti ka > 0.45 -> background4 > -0.17 (peso 0.1315)

======================================================================

Removida aresta Mn <= 0.22 -> background4 > -0.17 (peso 0.0590)
Mantida aresta background4 > -0.17 -> Mn <= 0.22 (peso 0.1884)

======================================================================

Removida aresta Rh L + Ar <= 0.27 -> Ti ka > 0.45 (peso 0.0568)
Mantida aresta Ti ka > 0.45 -> Rh L + Ar <= 0.27 (peso 0.0604)

======================================================================

Removida aresta Mn <= 0.22 -> Ti ka > 0.45 (peso 0.0633)
Mantida aresta Ti ka > 0.45 -> Mn <= 0.22 (peso 0.0635)

======================================================================

Removida aresta Ti ka > 0.45 -> Ca ka > -0.55 (peso 0.0669)
Mantida aresta Ca ka > -0.55 -> Ti ka > 0.45 (peso 0.0688)

======================================================================

Removida aresta Mn <= 0.22 -> Rh L + Ar <= 0.27 (peso 0.0624)
Mantida aresta Rh L + Ar <= 0.27 -> Mn <= 0.22 (peso 0.1214)

======================================================================

Removida aresta sum Fe <= 0.26 -> Rh L + Ar <= 0.27 (peso 0.0578)
Mantida aresta Rh L + Ar <= 0.27 -> sum Fe <= 0.26 (peso 0.1176)

======================================================================

Removida aresta Rh L + Ar <= 0.27 -> Al > -0.27 (peso 0.1098)
Mantida aresta Al > -0.27 -> Rh L + Ar <= 0.27 (peso 0.1676)

======================================================================

Removida aresta sum Fe <= 0.26 -> Mn <= 0.22 (peso 0.1143)
Mantida aresta Mn <= 0.22 -> sum Fe <= 0.26 (peso 0.1171)

======================================================================

Removida aresta Mn <= 0.22 -> Ca ka > -0.55 (peso 0.0585)
Mantida aresta Ca ka > -0.55 -> Mn <= 0.22 (peso 0.0647)

======================================================================

Removida aresta Cr <= 0.17 -> Ti ka <= -0.37 (peso 0.0359)
Mantida aresta Ti ka <= -0.37 -> Cr <= 0.17 (peso 0.0430)

======================================================================

Removida aresta background1 > -0.10 -> Ti ka <= -0.37 (peso 0.0342)
Mantida aresta Ti ka <= -0.37 -> background1 > -0.10 (peso 0.0359)

======================================================================

Removida aresta Ti ka <= -0.37 -> background3 <= 0.18 (peso 0.0338)
Mantida aresta background3 <= 0.18 -> Ti ka <= -0.37 (peso 0.0364)

======================================================================

Removida aresta Ti ka <= -0.37 -> background6 <= 0.18 (peso 0.0274)
Mantida aresta background6 <= 0.18 -> Ti ka <= -0.37 (peso 0.0297)

======================================================================

Removida aresta Ca ka > -0.55 -> background1 > -0.10 (peso 0.0335)
Mantida aresta background1 > -0.10 -> Ca ka > -0.55 (peso 0.0347)

======================================================================

Removida aresta Ca ka > -0.55 -> sum Fe <= 0.26 (peso 0.0571)
Mantida aresta sum Fe <= 0.26 -> Ca ka > -0.55 (peso 0.0612)

======================================================================

Removida aresta sum Fe <= 0.26 -> Al > -0.27 (peso 0.0565)
Mantida aresta Al > -0.27 -> sum Fe <= 0.26 (peso 0.1119)

======================================================================

Removida aresta Al > -0.27 -> Ca ka <= 0.76 (peso 0.0534)
Mantida aresta Ca ka <= 0.76 -> Al > -0.27 (peso 0.0534)

======================================================================

Removida aresta Ca kb <= 0.23 -> Al > -0.27 (peso 0.0535)
Mantida aresta Al > -0.27 -> Ca kb <= 0.23 (peso 0.1034)

======================================================================

Removida aresta Ca kb <= 0.23 -> Ca kb > -0.24 (peso 0.0476)
Mantida aresta Ca kb > -0.24 -> Ca kb <= 0.23 (peso 0.1551)

======================================================================

Removida aresta Ca ka <= 0.76 -> Ca kb > -0.24 (peso 0.0443)
Mantida aresta Ca kb > -0.24 -> Ca ka <= 0.76 (peso 0.0460)

======================================================================

Removida aresta Ca kb > -0.24 -> Cu > -0.16 (peso 0.0514)
Mantida aresta Cu > -0.16 -> Ca kb > -0.24 (peso 0.1456)

======================================================================

Removida aresta Cu > -0.16 -> Ca kb <= 0.23 (peso 0.0507)
Mantida aresta Ca kb <= 0.23 -> Cu > -0.16 (peso 0.0989)

======================================================================

Removida aresta Cu > -0.16 -> Al > -0.14 (peso 0.0978)
Mantida aresta Al > -0.14 -> Cu > -0.16 (peso 0.1948)

======================================================================

Removida aresta Al > -0.14 -> Ca ka > -0.20 (peso 0.0448)
Mantida aresta Ca ka > -0.20 -> Al > -0.14 (peso 0.0477)

======================================================================

Removida aresta Cr <= 0.17 -> Cr > -0.17 (peso 0.0806)
Mantida aresta Cr > -0.17 -> Cr <= 0.17 (peso 0.1186)

======================================================================

Removida aresta Cr > -0.17 -> background3 > -0.16 (peso 0.0794)
Mantida aresta background3 > -0.16 -> Cr > -0.17 (peso 0.1188)

======================================================================

Removida aresta Cr > -0.17 -> Ca ka > -0.20 (peso 0.0377)
Mantida aresta Ca ka > -0.20 -> Cr > -0.17 (peso 0.0848)

======================================================================

Removida aresta background3 > -0.16 -> Ca ka <= 0.76 (peso 0.0394)
Mantida aresta Ca ka <= 0.76 -> background3 > -0.16 (peso 0.0406)

======================================================================

Removida aresta Ti kb <= 0.24 -> Ca ka <= 0.76 (peso 0.0337)
Mantida aresta Ca ka <= 0.76 -> Ti kb <= 0.24 (peso 0.0386)

======================================================================

Removida aresta background3 > -0.16 -> Ti ka <= 0.45 (peso 0.0398)
Mantida aresta Ti ka <= 0.45 -> background3 > -0.16 (peso 0.0802)

======================================================================

Removida aresta background3 > -0.16 -> Cr <= 0.17 (peso 0.0380)
Mantida aresta Cr <= 0.17 -> background3 > -0.16 (peso 0.0761)

======================================================================

Removida aresta Ti kb <= 0.24 -> background3 > -0.16 (peso 0.0398)
Mantida aresta background3 > -0.16 -> Ti kb <= 0.24 (peso 0.0415)

======================================================================

Removida aresta background1 > -0.10 -> Ti ka <= 0.45 (peso 0.0347)
Mantida aresta Ti ka <= 0.45 -> background1 > -0.10 (peso 0.0356)

======================================================================

Removida aresta Ti kb <= 0.24 -> Cr <= 0.17 (peso 0.0403)
Mantida aresta Cr <= 0.17 -> Ti kb <= 0.24 (peso 0.0764)

======================================================================

Removida aresta background1 > -0.10 -> background3 <= 0.18 (peso 0.0341)
Mantida aresta background3 <= 0.18 -> background1 > -0.10 (peso 0.1766)

======================================================================

Removida aresta Ti kb <= 0.24 -> background1 > -0.10 (peso 0.0364)
Mantida aresta background1 > -0.10 -> Ti kb <= 0.24 (peso 0.1014)

======================================================================

Removida aresta background8 > -0.15 -> Ti kb > 0.24 (peso 0.0306)
Mantida aresta Ti kb > 0.24 -> background8 > -0.15 (peso 0.0311)

======================================================================

Removida aresta Cu <= 0.15 -> background8 > -0.15 (peso 0.0304)
Mantida aresta background8 > -0.15 -> Cu <= 0.15 (peso 0.0598)

======================================================================

Removida aresta background7 <= 0.16 -> Ti kb > 0.24 (peso 0.0260)
Mantida aresta Ti kb > 0.24 -> background7 <= 0.16 (peso 0.0889)

======================================================================

Removida aresta K > -0.20 -> background7 <= 0.16 (peso 0.0265)
Mantida aresta background7 <= 0.16 -> K > -0.20 (peso 0.0851)

======================================================================

Removida aresta background4 <= 0.09 -> background7 <= 0.16 (peso 0.0280)
Mantida aresta background7 <= 0.16 -> background4 <= 0.09 (peso 0.0285)

======================================================================

Removida aresta background1 <= 0.12 -> K > -0.20 (peso 0.0307)
Mantida aresta K > -0.20 -> background1 <= 0.12 (peso 0.0582)

======================================================================

Removida aresta background2 > -0.09 -> background7 > -0.15 (peso 0.0284)
Mantida aresta background7 > -0.15 -> background2 > -0.09 (peso 0.0293)

======================================================================

Removida aresta background7 > -0.15 -> Ti kb > 0.24 (peso 0.0275)
Mantida aresta Ti kb > 0.24 -> background7 > -0.15 (peso 0.0545)

======================================================================


,Predicate_Cov_Seed_0,Predicate_Cov_Seed_1,Predicate_Cov_Seed_2,Predicate_Cov_Seed_3
0,Fe ka > -3.73,Fe ka > -3.73,Fe ka > -3.73,Fe ka > -3.73
1,Fe ka <= 4.61,Fe ka <= 4.61,Fe ka <= 4.61,Fe ka <= 4.61
2,Fe ka > -2.42,Fe ka > -2.42,Fe ka > -2.42,Fe ka > -2.42
3,Fe ka <= 2.41,Fe ka <= 2.41,Fe ka <= 2.41,Fe ka <= 2.41
4,Fe kb > -1.37,Fe kb > -1.37,Fe kb > -1.37,Fe kb > -1.37
...,...,...,...,...
98,NaN,Class_B,Ca ka <= -0.20,background2 <= 0.07
99,NaN,NaN,background5 <= 0.12,S > -0.12
100,NaN,NaN,Class_A,Cr > 0.17
101,NaN,NaN,Class_B,Class_A
102,NaN,NaN,NaN,Class_B

In [11]:
# Somar LRCs de predicados equivalentes entre diferentes seeds
lrc_combined_list = []

for seed in random_seeds:
    lrc_df = lrc_cov_by_seed[seed].copy()
    lrc_combined_list.append(lrc_df) # o append adiciona o dataframe ao final da lista

# Concatenar todos os dataframes
lrc_all_seeds = pd.concat(lrc_combined_list, ignore_index=True) 

# Agrupar por predicado (Node) e somar as LRCs, mantendo Zone, Threshold e Operator
lrc_summed_df = lrc_all_seeds.groupby('Node').agg({ # o .agg pode ser usado para aplicar múltiplas funções de agregação
    'Local_Reaching_Centrality': 'mean', # sum = somando as LRCs, poderia ser média ou outro agregado
    'Zone': 'first',
    'Threshold': 'first',
    'Operator': 'first'
}).reset_index()

# Ordenar pelo valor de LRC somado (maior para menor)
lrc_summed_df = lrc_summed_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
# vamoss pegar so os valore sunicos de lrc_summed_df baseado na zona espectral
lrc_summed_unique_df_cov = lrc_summed_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
#lrc_summed_unique_df_cov = lrc_summed_unique_df_cov.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
lrc_summed_unique_df_cov

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator
0,Fe ka > -3.73,17.758351,Fe ka,-3.73,>
1,Fe kb > -1.37,6.949441,Fe kb,-1.37,>
2,Mn > -0.47,2.722146,Mn,-0.47,>
3,sum Fe > -0.41,2.070560,sum Fe,-0.41,>
4,Ti ka > -0.84,1.041595,Ti ka,-0.84,>
5,Si > -0.45,0.838531,Si,-0.45,>
6,Rh L + Ar > -0.26,0.772411,Rh L + Ar,-0.26,>
7,background4 > -0.29,0.727906,background4,-0.29,>
8,background8 > -0.22,0.650439,background8,-0.22,>
9,Ti kb > -0.42,0.631098,Ti kb,-0.42,>
10,Cu <= 0.25,0.605355,Cu,0.25,<=
11,Cr <= 0.28,0.592394,Cr,0.28,<=
12,Ca ka > -0.82,0.412314,Ca ka,-0.82,>
13,Ca kb <= 0.23,0.348366,Ca kb,0.23,<=
14,Al > -0.27,0.328666,Al,-0.27,>
15,background3 > -0.16,0.258762,background3,-0.16,>
16,background1 > -0.10,0.228666,background1,-0.10,>
17,background6 > -0.16,0.221972,background6,-0.16,>
18,K > -0.13,0.220147,K,-0.13,>
19,background2 > -0.09,0.216712,background2,-0.09,>
20,background7 > -0.15,0.215199,background7,-0.15,>
21,P > 0.15,0.177669,P,0.15,>
22,background5 <= 0.16,0.128622,background5,0.16,<=
23,S <= 0.13,0.121192,S,0.13,<=
24,Class_B,0.000000,None,None,None

# **Perturbation**

In [12]:
ycalres = np.where(svm_model[1]['SVC'] == 'A', 1, 0)

In [13]:
import explaining as exp

# LISTA DE SEMENTES A TESTAR
random_seeds = [0, 1, 2, 3]

all_results_pert = {}
training_samples = len(Xcalclass)

# LOOP: PROCESSAR CADA SEMENTE
y_predicted_numeric = pd.Series(y_pred) # predições numéricas do modelo

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando semente: {seed}")
    print(f"{'='*70}\n")
    # Bagging
    bags_result_seed = exp.bagging_predicates(
        zone_sums_df=zone_sums_df,
        y_predicted_numeric=y_predicted_numeric,
        predicates_df=predicates_quantiles[0],
        n_bags=10,
        #n_predicates_per_bag=40,
        n_samples_per_bag=int(training_samples*0.8), # 80 % da base para amostrar (convertido para int)
        min_samples_per_predicate=int(training_samples*0.2), # 20 % da base para limitar (convertido para int)
        replace=False,
        sample_bagging=True,
        predicate_bagging=False,
        random_seed=seed
    )
    # Inserir classe prevista
    for bag_name, pred_dict in bags_result_seed.items(): # iterando sobre cada bag
        for pred_rule, df_info in pred_dict.items():
            df_info['Class_Predicted'] = np.where(df_info['Predicted_Y'] >= 0.5, 'A', 'B') # binarizando com threshold 0.5, A = eut, B = dist

    pert_results_seed = exp.calculate_predicate_perturbation(
        estimator=svm_model[3],
        Xcalclass_prep=Xcalclass_prep,
        folds_struct=bags_result_seed,
        predicates_df=predicates_quantiles[0],
        spectral_cuts=spectral_cuts,
        #perturbation_value=0,
        perturbation_mode='mean', # valores entre 'mean' ou 'min'
        stats_source='full', # full indica usar todas as amostras para calcular estatísticas enquanto que 'fold' usa apenas as amostras do fold atual
        #metric='mean_abs_diff',   # Média com sinal (pode ser negativo)
        aim='classification',
        metric='probability_shift', 
        verbose=True
    )

    # Remove todos os valores iguais a zero de todos os bags em perm_results[bag]["Permutation"] e salva como perm_results_thresholded
    # pert_results_seed_thresholded = {}
    # for bag, df in perm_results_seed.items():
    #     # Verifica se é um DataFrame e se a coluna 'Permutation' existe
    #     if isinstance(df, pd.DataFrame) and 'Permutation' in df.columns:
    #         filtered_df = df[df['Permutation'] > 0].copy()
    #         pert_results_seed_thresholded[bag] = filtered_df
    #     else:
    #         # Se não for DataFrame esperado, apenas copia
    #         pert_results_seed_thresholded[bag] = df

    # Salvar no dicionário principal
    all_results_pert[seed] = {
        'bags_result': bags_result_seed,
        'pert_results_dict': pert_results_seed
    }

# CONSTRUÇÃO DE GRAFOS PARA MÚLTIPLAS SEMENTES (LOOP EXTERNO)
# Dicionário para armazenar grafos
graphs_pert_by_seed = {}

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando Grafo - Semente: {seed}")
    print(f"{'='*70}\n")
    # Construir grafo para esta semente
    DG = exp.build_predicate_graphv2(
        bags_result=all_results_pert[seed]['bags_result'],
        predicate_ranking_dict=all_results_pert[seed]['pert_results_dict'],
        metric_column='Perturbation',  # ou 'Covariance' se mudar a métrica
        random_state=seed,
        show_details=True
    )
    # Armazenar grafo
    graphs_pert_by_seed[seed] = DG  

# Calcular LRC usando a função pronta do explaining.py
lrc_pert_by_seed = {}
for seed in random_seeds:
    DG = graphs_pert_by_seed[seed]
    lrc_pert_df_seed = exp.calculate_lrc_single_graph(DG, predicates_quantiles[0])
    lrc_pert_df_seed['Seed'] = seed  # Adicionar coluna com a semente
    lrc_pert_by_seed[seed] = lrc_pert_df_seed

# junando todas as colunas 'Node' de lrc_by_seed em um único dataframe
lrc_pert_all_seeds_df = pd.DataFrame()
for seed in random_seeds:
    lrc_pert_df_seed = lrc_pert_by_seed[seed].rename(columns={'Node': f'Predicate_pert_Seed_{seed}'})
    lrc_pert_all_seeds_df = pd.concat([lrc_pert_all_seeds_df, lrc_pert_df_seed[[f'Predicate_pert_Seed_{seed}']]], axis=1)

# vamos filtrar lrc_by_seed em cada semente para manter apenas as zonas espectrais únicas com maior LRC em um mesmo dataframe
lrc_pert_unique_by_seed = {}
for seed, lrc_df in lrc_pert_by_seed.items():
    lrc_pert_unique_df = lrc_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
    lrc_pert_unique_df = lrc_pert_unique_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
    lrc_pert_unique_by_seed[seed] = lrc_pert_unique_df

lrc_pert_all_seeds_df # exibindo o dataframe consolidado com predicados de todas as sementes

======================================================================
Processando semente: 0
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
======================================================================
PERTURBATION IMPORTANCE PARA PREDICADOS
======================================================================
Tipo de tarefa (aim): classification
Modo de perturbação: mean
Fonte das estatísticas: full
Métrica: probability_shift
Total de folds: 10


[Bag_1] Processando 150 predicados...
  Predicado: background1 > -0.10 (n=323)
    Zona: 17 colunas
    Importance: 0.000013
  Predicado: background1 <= -0.08 (n=144)
    Zona: 17 colunas
    Importance: 0.000026
  Predicado: background1 > -0.08 (n=256)
    Zona: 17 colunas
    Importance: 0.000015
  Predicado: background1 <= 0.09 (n=227)
    Zona: 17 colunas
    Importance: 0.000029
  Predicado: background1 > 0.09 (n=173)
    Zona: 17 colunas
    Importance: 0.000007
  Predicado: background1 <= 0.12 (n=314)
    Zona: 17 colunas
    Importance: 0.000023
  Predicado: Al > -0.27 (n=322)
    Zona: 15 colunas
    Importance: 0.000265
  Predicado: Al <= -0.14 (n=155)
    Zona: 15 colunas
    Importance: 0.000756
  Predicado: Al > -0.14 (n=245)
    Zona: 15 colunas
    Importance: 0.000225
  Predicado: Al <= 0.16 (n=238)
    Zona: 15 colunas
    Importance: 0.000508
  Predicado: Al > 0.16 (n=162)
    Zona: 15 colunas
    Importance: 0.000317
  Predicado: Al <= 0.29 (n=314)
    Zona: 15 colunas
    Importance: 0.000434
  Predicado: Si > -0.45 (n=323)
    Zona: 12 colunas
    Importance: 0.000664
  Predicado: Si <= -0.25 (n=154)
    Zona: 12 colunas
    Importance: 0.000129
  Predicado: Si > -0.25 (n=246)
    Zona: 12 colunas
    Importance: 0.000852
  Predicado: Si <= 0.18 (n=233)
    Zona: 12 colunas
    Importance: 0.000096
  Predicado: Si > 0.18 (n=167)
    Zona: 12 colunas
    Importance: 0.001241
  Predicado: Si <= 0.51 (n=322)
    Zona: 12 colunas
    Importance: 0.000126
  Predicado: P > -0.19 (n=319)
    Zona: 17 colunas
    Importance: 0.000100
  Predicado: P <= -0.13 (n=157)
    Zona: 17 colunas
    Importance: 0.000150
  Predicado: P > -0.13 (n=243)
    Zona: 17 colunas
    Importance: 0.000094
  Predicado: P <= 0.15 (n=239)
    Zona: 17 colunas
    Importance: 0.000117
  Predicado: P > 0.15 (n=161)
    Zona: 17 colunas
    Importance: 0.000116
  Predicado: P <= 0.25 (n=321)
    Zona: 17 colunas
    Importance: 0.000098
  Predicado: S > -0.12 (n=314)
    Zona: 13 colunas
    Importance: 0.000018
  Predicado: S <= -0.09 (n=151)
    Zona: 13 colunas
    Importance: 0.000010
  Predicado: S > -0.09 (n=249)
    Zona: 13 colunas
    Importance: 0.000019
  Predicado: S <= 0.09 (n=246)
    Zona: 13 colunas
    Importance: 0.000009
  Predicado: S > 0.09 (n=154)
    Zona: 13 colunas
    Importance: 0.000027
  Predicado: S <= 0.13 (n=314)
    Zona: 13 colunas
    Importance: 0.000008
  Predicado: background2 > -0.09 (n=321)
    Zona: 6 colunas
    Importance: 0.000011
  Predicado: background2 <= -0.06 (n=164)
    Zona: 6 colunas
    Importance: 0.000005
  Predicado: background2 > -0.06 (n=236)
    Zona: 6 colunas
    Importance: 0.000013
  Predicado: background2 <= 0.07 (n=242)
    Zona: 6 colunas
    Importance: 0.000004
  Predicado: background2 > 0.07 (n=158)
    Zona: 6 colunas
    Importance: 0.000019
  Predicado: background2 <= 0.10 (n=312)
    Zona: 6 colunas
    Importance: 0.000004
  Predicado: Rh L + Ar > -0.26 (n=320)
    Zona: 33 colunas
    Importance: 0.000379
  Predicado: Rh L + Ar <= -0.21 (n=145)
    Zona: 33 colunas
    Importance: 0.000466
  Predicado: Rh L + Ar > -0.21 (n=255)
    Zona: 33 colunas
    Importance: 0.000379
  Predicado: Rh L + Ar <= 0.27 (n=238)
    Zona: 33 colunas
    Importance: 0.000371
  Predicado: Rh L + Ar > 0.27 (n=162)
    Zona: 33 colunas
    Importance: 0.000468
  Predicado: Rh L + Ar <= 0.36 (n=317)
    Zona: 33 colunas
    Importance: 0.000431
  Predicado: K > -0.20 (n=319)
    Zona: 16 colunas
    Importance: 0.001245
  Predicado: K <= -0.13 (n=160)
    Zona: 16 colunas
    Importance: 0.000019
  Predicado: K > -0.13 (n=240)
    Zona: 16 colunas
    Importance: 0.001649
  Predicado: K <= 0.09 (n=243)
    Zona: 16 colunas
    Importance: 0.000017
  Predicado: K > 0.09 (n=157)
    Zona: 16 colunas
    Importance: 0.002513
  Predicado: K <= 0.17 (n=319)
    Zona: 16 colunas
    Importance: 0.000027
  Predicado: Ca ka > -0.82 (n=321)
    Zona: 16 colunas
    Importance: 0.001573
  Predicado: Ca ka <= -0.55 (n=160)
    Zona: 16 colunas
    Importance: 0.000873
  Predicado: Ca ka > -0.55 (n=240)
    Zona: 16 colunas
    Importance: 0.001814
  Predicado: Ca ka <= -0.20 (n=239)
    Zona: 16 colunas
    Importance: 0.000809
  Predicado: Ca ka > -0.20 (n=161)
    Zona: 16 colunas
    Importance: 0.002371
  Predicado: Ca ka <= 0.76 (n=316)
    Zona: 16 colunas
    Importance: 0.000744
  Predicado: Ca kb > -0.24 (n=321)
    Zona: 16 colunas
    Importance: 0.000086
  Predicado: Ca kb <= -0.18 (n=153)
    Zona: 16 colunas
    Importance: 0.000067
  Predicado: Ca kb > -0.18 (n=247)
    Zona: 16 colunas
    Importance: 0.000095
  Predicado: Ca kb <= 0.12 (n=236)
    Zona: 16 colunas
    Importance: 0.000060
  Predicado: Ca kb > 0.12 (n=164)
    Zona: 16 colunas
    Importance: 0.000119
  Predicado: Ca kb <= 0.23 (n=319)
    Zona: 16 colunas
    Importance: 0.000049
  Predicado: background3 > -0.16 (n=329)
    Zona: 12 colunas
    Importance: 0.000042
  Predicado: background3 <= -0.09 (n=160)
    Zona: 12 colunas
    Importance: 0.000056
  Predicado: background3 > -0.09 (n=240)
    Zona: 12 colunas
    Importance: 0.000039
  Predicado: background3 <= 0.12 (n=235)
    Zona: 12 colunas
    Importance: 0.000052
  Predicado: background3 > 0.12 (n=165)
    Zona: 12 colunas
    Importance: 0.000037
  Predicado: background3 <= 0.18 (n=316)
    Zona: 12 colunas
    Importance: 0.000052
  Predicado: Ti ka > -0.84 (n=322)
    Zona: 15 colunas
    Importance: 0.004982
  Predicado: Ti ka <= -0.37 (n=156)
    Zona: 15 colunas
    Importance: 0.006043
  Predicado: Ti ka > -0.37 (n=244)
    Zona: 15 colunas
    Importance: 0.004332
  Predicado: Ti ka <= 0.45 (n=236)
    Zona: 15 colunas
    Importance: 0.004291
  Predicado: Ti ka > 0.45 (n=164)
    Zona: 15 colunas
    Importance: 0.006020
  Predicado: Ti ka <= 0.92 (n=313)
    Zona: 15 colunas
    Importance: 0.004299
  Predicado: background4 > -0.29 (n=320)
    Zona: 5 colunas
    Importance: 0.000030
  Predicado: background4 <= -0.17 (n=153)
    Zona: 5 colunas
    Importance: 0.000055
  Predicado: background4 > -0.17 (n=247)
    Zona: 5 colunas
    Importance: 0.000027
  Predicado: background4 <= 0.09 (n=235)
    Zona: 5 colunas
    Importance: 0.000052
  Predicado: background4 > 0.09 (n=165)
    Zona: 5 colunas
    Importance: 0.000017
  Predicado: background4 <= 0.35 (n=315)
    Zona: 5 colunas
    Importance: 0.000043
  Predicado: Ti kb > -0.42 (n=321)
    Zona: 19 colunas
    Importance: 0.000287
  Predicado: Ti kb <= -0.23 (n=158)
    Zona: 19 colunas
    Importance: 0.000345
  Predicado: Ti kb > -0.23 (n=242)
    Zona: 19 colunas
    Importance: 0.000261
  Predicado: Ti kb <= 0.24 (n=236)
    Zona: 19 colunas
    Importance: 0.000317
  Predicado: Ti kb > 0.24 (n=164)
    Zona: 19 colunas
    Importance: 0.000262
  Predicado: Ti kb <= 0.48 (n=318)
    Zona: 19 colunas
    Importance: 0.000324
  Predicado: Cr > -0.26 (n=321)
    Zona: 33 colunas
    Importance: 0.000270
  Predicado: Cr <= -0.17 (n=155)
    Zona: 33 colunas
    Importance: 0.000207
  Predicado: Cr > -0.17 (n=245)
    Zona: 33 colunas
    Importance: 0.000253
  Predicado: Cr <= 0.17 (n=233)
    Zona: 33 colunas
    Importance: 0.000288
  Predicado: Cr > 0.17 (n=167)
    Zona: 33 colunas
    Importance: 0.000161
  Predicado: Cr <= 0.28 (n=312)
    Zona: 33 colunas
    Importance: 0.000285
  Predicado: Mn > -0.47 (n=322)
    Zona: 18 colunas
    Importance: 0.000536
  Predicado: Mn <= -0.33 (n=153)
    Zona: 18 colunas
    Importance: 0.000592
  Predicado: Mn > -0.33 (n=247)
    Zona: 18 colunas
    Importance: 0.000527
  Predicado: Mn <= 0.22 (n=235)
    Zona: 18 colunas
    Importance: 0.000593
  Predicado: Mn > 0.22 (n=165)
    Zona: 18 colunas
    Importance: 0.000493
  Predicado: Mn <= 0.47 (n=315)
    Zona: 18 colunas
    Importance: 0.000493
  Predicado: Fe ka > -3.73 (n=320)
    Zona: 34 colunas
    Importance: 0.226111
  Predicado: Fe ka <= -2.42 (n=157)
    Zona: 34 colunas
    Importance: 0.570945
  Predicado: Fe ka > -2.42 (n=243)
    Zona: 34 colunas
    Importance: 0.177902
  Predicado: Fe ka <= 2.41 (n=238)
    Zona: 34 colunas
    Importance: 0.408325
  Predicado: Fe ka > 2.41 (n=162)
    Zona: 34 colunas
    Importance: 0.220291
  Predicado: Fe ka <= 4.61 (n=316)
    Zona: 34 colunas
    Importance: 0.344748
  Predicado: Fe kb > -1.37 (n=320)
    Zona: 26 colunas
    Importance: 0.002196
  Predicado: Fe kb <= -0.88 (n=158)
    Zona: 26 colunas
    Importance: 0.004587
  Predicado: Fe kb > -0.88 (n=242)
    Zona: 26 colunas
    Importance: 0.002192
  Predicado: Fe kb <= 0.90 (n=237)
    Zona: 26 colunas
    Importance: 0.003711
  Predicado: Fe kb > 0.90 (n=163)
    Zona: 26 colunas
    Importance: 0.002304
  Predicado: Fe kb <= 1.68 (n=315)
    Zona: 26 colunas
    Importance: 0.003092
  Predicado: background5 > -0.15 (n=329)
    Zona: 31 colunas
    Importance: 0.000148
  Predicado: background5 <= -0.10 (n=159)
    Zona: 31 colunas
    Importance: 0.000181
  Predicado: background5 > -0.10 (n=241)
    Zona: 31 colunas
    Importance: 0.000180
  Predicado: background5 <= 0.12 (n=230)
    Zona: 31 colunas
    Importance: 0.000140
  Predicado: background5 > 0.12 (n=170)
    Zona: 31 colunas
    Importance: 0.000235
  Predicado: background5 <= 0.16 (n=317)
    Zona: 31 colunas
    Importance: 0.000144
  Predicado: Cu > -0.22 (n=322)
    Zona: 15 colunas
    Importance: 0.000222
  Predicado: Cu <= -0.16 (n=151)
    Zona: 15 colunas
    Importance: 0.000173
  Predicado: Cu > -0.16 (n=249)
    Zona: 15 colunas
    Importance: 0.000242
  Predicado: Cu <= 0.15 (n=233)
    Zona: 15 colunas
    Importance: 0.000173
  Predicado: Cu > 0.15 (n=167)
    Zona: 15 colunas
    Importance: 0.000276
  Predicado: Cu <= 0.25 (n=316)
    Zona: 15 colunas
    Importance: 0.000158
  Predicado: background6 > -0.16 (n=314)
    Zona: 125 colunas
    Importance: 0.000796
  Predicado: background6 <= -0.13 (n=163)
    Zona: 125 colunas
    Importance: 0.001084
  Predicado: background6 > -0.13 (n=237)
    Zona: 125 colunas
    Importance: 0.000864
  Predicado: background6 <= 0.14 (n=248)
    Zona: 125 colunas
    Importance: 0.000751
  Predicado: background6 > 0.14 (n=152)
    Zona: 125 colunas
    Importance: 0.001283
  Predicado: background6 <= 0.18 (n=319)
    Zona: 125 colunas
    Importance: 0.000718
  Predicado: Fe ka + Ti ka > -0.15 (n=317)
    Zona: 23 colunas
    Importance: 0.000150
  Predicado: Fe ka + Ti ka <= -0.11 (n=149)
    Zona: 23 colunas
    Importance: 0.000214
  Predicado: Fe ka + Ti ka > -0.11 (n=251)
    Zona: 23 colunas
    Importance: 0.000121
  Predicado: Fe ka + Ti ka <= 0.13 (n=245)
    Zona: 23 colunas
    Importance: 0.000154
  Predicado: Fe ka + Ti ka > 0.13 (n=155)
    Zona: 23 colunas
    Importance: 0.000159
  Predicado: Fe ka + Ti ka <= 0.17 (n=319)
    Zona: 23 colunas
    Importance: 0.000151
  Predicado: background7 > -0.15 (n=326)
    Zona: 71 colunas
    Importance: 0.000283
  Predicado: background7 <= -0.12 (n=152)
    Zona: 71 colunas
    Importance: 0.000454
  Predicado: background7 > -0.12 (n=248)
    Zona: 71 colunas
    Importance: 0.000336
  Predicado: background7 <= 0.12 (n=244)
    Zona: 71 colunas
    Importance: 0.000309
  Predicado: background7 > 0.12 (n=156)
    Zona: 71 colunas
    Importance: 0.000492
  Predicado: background7 <= 0.16 (n=321)
    Zona: 71 colunas
    Importance: 0.000277
  Predicado: sum Fe > -0.41 (n=320)
    Zona: 28 colunas
    Importance: 0.000140
  Predicado: sum Fe <= -0.27 (n=155)
    Zona: 28 colunas
    Importance: 0.000216
  Predicado: sum Fe > -0.27 (n=245)
    Zona: 28 colunas
    Importance: 0.000145
  Predicado: sum Fe <= 0.26 (n=235)
    Zona: 28 colunas
    Importance: 0.000198
  Predicado: sum Fe > 0.26 (n=165)
    Zona: 28 colunas
    Importance: 0.000135
  Predicado: sum Fe <= 0.51 (n=320)
    Zona: 28 colunas
    Importance: 0.000163
  Predicado: background8 > -0.22 (n=324)
    Zona: 96 colunas
    Importance: 0.000097
  Predicado: background8 <= -0.15 (n=151)
    Zona: 96 colunas
    Importance: 0.000086
  Predicado: background8 > -0.15 (n=249)
    Zona: 96 colunas
    Importance: 0.000083
  Predicado: background8 <= 0.16 (n=232)
    Zona: 96 colunas
    Importance: 0.000102
  Predicado: background8 > 0.16 (n=168)
    Zona: 96 colunas
    Importance: 0.000060
  Predicado: background8 <= 0.27 (n=323)
    Zona: 96 colunas
    Importance: 0.000098

[Bag_2] Processando 150 predicados...
  Predicado: background1 > -0.10 (n=313)
    Zona: 17 colunas
    Importance: 0.000005
  Predicado: background1 <= -0.08 (n=155)
    Zona: 17 colunas
    Importance: 0.000024
  Predicado: background1 > -0.08 (n=245)
    Zona: 17 colunas
    Importance: 0.000006
  Predicado: background1 <= 0.09 (n=242)
    Zona: 17 colunas
    Importance: 0.000017
  Predicado: background1 > 0.09 (n=158)
    Zona: 17 colunas
    Importance: 0.000007
  Predicado: background1 <= 0.12 (n=320)
    Zona: 17 colunas
    Importance: 0.000014
  Predicado: Al > -0.27 (n=320)
    Zona: 15 colunas
    Importance: 0.000293
  Predicado: Al <= -0.14 (n=166)
    Zona: 15 colunas
    Importance: 0.000670
  Predicado: Al > -0.14 (n=234)
    Zona: 15 colunas
    Importance: 0.000271
  Predicado: Al <= 0.16 (n=249)
    Zona: 15 colunas
    Importance: 0.000461
  Predicado: Al > 0.16 (n=151)
    Zona: 15 colunas
    Importance: 0.000396
  Predicado: Al <= 0.29 (n=320)
    Zona: 15 colunas
    Importance: 0.000419
  Predicado: Si > -0.45 (n=322)
    Zona: 12 colunas
    Importance: 0.000715
  Predicado: Si <= -0.25 (n=164)
    Zona: 12 colunas
    Importance: 0.000146
  Predicado: Si > -0.25 (n=236)
    Zona: 12 colunas
    Importance: 0.000928
  Predicado: Si <= 0.18 (n=244)
    Zona: 12 colunas
    Importance: 0.000119
  Predicado: Si > 0.18 (n=156)
    Zona: 12 colunas
    Importance: 0.001371
  Predicado: Si <= 0.51 (n=321)
    Zona: 12 colunas
    Importance: 0.000143
  Predicado: P > -0.19 (n=326)
    Zona: 17 colunas
    Importance: 0.000093
  Predicado: P <= -0.13 (n=155)
    Zona: 17 colunas
    Importance: 0.000166
  Predicado: P > -0.13 (n=245)
    Zona: 17 colunas
    Importance: 0.000090
  Predicado: P <= 0.15 (n=238)
    Zona: 17 colunas
    Importance: 0.000122
  Predicado: P > 0.15 (n=162)
    Zona: 17 colunas
    Importance: 0.000115
  Predicado: P <= 0.25 (n=315)
    Zona: 17 colunas
    Importance: 0.000105
  Predicado: S > -0.12 (n=315)
    Zona: 13 colunas
    Importance: 0.000009
  Predicado: S <= -0.09 (n=155)
    Zona: 13 colunas
    Importance: 0.000010
  Predicado: S > -0.09 (n=245)
    Zona: 13 colunas
    Importance: 0.000009
  Predicado: S <= 0.09 (n=248)
    Zona: 13 colunas
    Importance: 0.000008
  Predicado: S > 0.09 (n=152)
    Zona: 13 colunas
    Importance: 0.000010
  Predicado: S <= 0.13 (n=317)
    Zona: 13 colunas
    Importance: 0.000008
  Predicado: background2 > -0.09 (n=320)
    Zona: 6 colunas
    Importance: 0.000011
  Predicado: background2 <= -0.06 (n=163)
    Zona: 6 colunas
    Importance: 0.000005
  Predicado: background2 > -0.06 (n=237)
    Zona: 6 colunas
    Importance: 0.000013
  Predicado: background2 <= 0.07 (n=252)
    Zona: 6 colunas
    Importance: 0.000004
  Predicado: background2 > 0.07 (n=148)
    Zona: 6 colunas
    Importance: 0.000020
  Predicado: background2 <= 0.10 (n=318)
    Zona: 6 colunas
    Importance: 0.000004
  Predicado: Rh L + Ar > -0.26 (n=312)
    Zona: 33 colunas
    Importance: 0.000388
  Predicado: Rh L + Ar <= -0.21 (n=154)
    Zona: 33 colunas
    Importance: 0.000505
  Predicado: Rh L + Ar > -0.21 (n=246)
    Zona: 33 colunas
    Importance: 0.000363
  Predicado: Rh L + Ar <= 0.27 (n=243)
    Zona: 33 colunas
    Importance: 0.000404
  Predicado: Rh L + Ar > 0.27 (n=157)
    Zona: 33 colunas
    Importance: 0.000438
  Predicado: Rh L + Ar <= 0.36 (n=320)
    Zona: 33 colunas
    Importance: 0.000433
  Predicado: K > -0.20 (n=317)
    Zona: 16 colunas
    Importance: 0.001243
  Predicado: K <= -0.13 (n=155)
    Zona: 16 colunas
    Importance: 0.000023
  Predicado: K > -0.13 (n=245)
    Zona: 16 colunas
    Importance: 0.001602
  Predicado: K <= 0.09 (n=240)
    Zona: 16 colunas
    Importance: 0.000020
  Predicado: K > 0.09 (n=160)
    Zona: 16 colunas
    Importance: 0.002446
  Predicado: K <= 0.17 (n=315)
    Zona: 16 colunas
    Importance: 0.000020
  Predicado: Ca ka > -0.82 (n=324)
    Zona: 16 colunas
    Importance: 0.001497
  Predicado: Ca ka <= -0.55 (n=152)
    Zona: 16 colunas
    Importance: 0.000960
  Predicado: Ca ka > -0.55 (n=248)
    Zona: 16 colunas
    Importance: 0.001683
  Predicado: Ca ka <= -0.20 (n=233)
    Zona: 16 colunas
    Importance: 0.000856
  Predicado: Ca ka > -0.20 (n=167)
    Zona: 16 colunas
    Importance: 0.002178
  Predicado: Ca ka <= 0.76 (n=315)
    Zona: 16 colunas
    Importance: 0.000717
  Predicado: Ca kb > -0.24 (n=316)
    Zona: 16 colunas
    Importance: 0.000070
  Predicado: Ca kb <= -0.18 (n=151)
    Zona: 16 colunas
    Importance: 0.000071
  Predicado: Ca kb > -0.18 (n=249)
    Zona: 16 colunas
    Importance: 0.000072
  Predicado: Ca kb <= 0.12 (n=240)
    Zona: 16 colunas
    Importance: 0.000052
  Predicado: Ca kb > 0.12 (n=160)
    Zona: 16 colunas
    Importance: 0.000102
  Predicado: Ca kb <= 0.23 (n=319)
    Zona: 16 colunas
    Importance: 0.000043
  Predicado: background3 > -0.16 (n=325)
    Zona: 12 colunas
    Importance: 0.000035
  Predicado: background3 <= -0.09 (n=170)
    Zona: 12 colunas
    Importance: 0.000053
  Predicado: background3 > -0.09 (n=230)
    Zona: 12 colunas
    Importance: 0.000029
  Predicado: background3 <= 0.12 (n=245)
    Zona: 12 colunas
    Importance: 0.000040
  Predicado: background3 > 0.12 (n=155)
    Zona: 12 colunas
    Importance: 0.000037
  Predicado: background3 <= 0.18 (n=324)
    Zona: 12 colunas
    Importance: 0.000044
  Predicado: Ti ka > -0.84 (n=322)
    Zona: 15 colunas
    Importance: 0.005213
  Predicado: Ti ka <= -0.37 (n=163)
    Zona: 15 colunas
    Importance: 0.006214
  Predicado: Ti ka > -0.37 (n=237)
    Zona: 15 colunas
    Importance: 0.004575
  Predicado: Ti ka <= 0.45 (n=238)
    Zona: 15 colunas
    Importance: 0.004557
  Predicado: Ti ka > 0.45 (n=162)
    Zona: 15 colunas
    Importance: 0.006251
  Predicado: Ti ka <= 0.92 (n=317)
    Zona: 15 colunas
    Importance: 0.004549
  Predicado: background4 > -0.29 (n=317)
    Zona: 5 colunas
    Importance: 0.000053
  Predicado: background4 <= -0.17 (n=162)
    Zona: 5 colunas
    Importance: 0.000100
  Predicado: background4 > -0.17 (n=238)
    Zona: 5 colunas
    Importance: 0.000027
  Predicado: background4 <= 0.09 (n=246)
    Zona: 5 colunas
    Importance: 0.000081
  Predicado: background4 > 0.09 (n=154)
    Zona: 5 colunas

,Predicate_pert_Seed_0,Predicate_pert_Seed_1,Predicate_pert_Seed_2,Predicate_pert_Seed_3
0,Fe ka <= -2.42,Fe ka <= -2.42,Fe ka <= -2.42,Fe ka <= -2.42
1,Fe ka <= 2.41,Fe ka <= 2.41,Fe ka <= 2.41,Fe ka <= 2.41
2,Fe ka <= 4.61,Fe ka <= 4.61,Fe ka <= 4.61,Fe ka <= 4.61
3,Fe ka > -3.73,Fe ka > -3.73,Fe ka > -3.73,Fe ka > -3.73
4,Fe ka > 2.41,Fe ka > 2.41,Fe ka > 2.41,Fe ka > 2.41
...,...,...,...,...
147,background2 <= -0.06,background2 <= -0.06,background8 <= -0.15,background2 <= -0.06
148,background2 <= 0.10,background2 <= 0.10,background2 <= 0.10,background2 <= 0.10
149,background2 <= 0.07,background2 <= 0.07,background2 <= 0.07,background2 <= 0.07
150,Class_A,Class_A,Class_A,Class_A
151,Class_B,Class_B,Class_B,Class_B

In [14]:
all_results_pert[0]['pert_results_dict']['Bag_1']

                Predicate  Perturbation
0          Fe ka <= -2.42      0.570945
1           Fe ka <= 2.41      0.408325
2           Fe ka <= 4.61      0.344748
3           Fe ka > -3.73      0.226111
4            Fe ka > 2.41      0.220291
..                    ...           ...
145             S <= 0.13      0.000008
146    background1 > 0.09      0.000007
147  background2 <= -0.06      0.000005
148   background2 <= 0.10      0.000004
149   background2 <= 0.07      0.000004

[150 rows x 2 columns]

In [15]:
# Somar LRCs de predicados equivalentes entre diferentes seeds
lrc_combined_list = []

for seed in random_seeds:
    lrc_df = lrc_pert_by_seed[seed].copy()
    lrc_combined_list.append(lrc_df) # o append adiciona o dataframe ao final da lista

# Concatenar todos os dataframes
lrc_all_seeds = pd.concat(lrc_combined_list, ignore_index=True) 

# Agrupar por predicado (Node) e somar as LRCs, mantendo Zone, Threshold e Operator
lrc_summed_df = lrc_all_seeds.groupby('Node').agg({ # o .agg pode ser usado para aplicar múltiplas funções de agregação
    'Local_Reaching_Centrality': 'mean', # sum = somando as LRCs, poderia ser média ou outro agregado
    'Zone': 'first',
    'Threshold': 'first',
    'Operator': 'first'
}).reset_index()

# Ordenar pelo valor de LRC somado (maior para menor)
lrc_summed_df = lrc_summed_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
# vamoss pegar so os valore sunicos de lrc_summed_df baseado na zona espectral
lrc_summed_unique_df_pert = lrc_summed_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
lrc_summed_unique_df_pert = lrc_summed_unique_df_pert.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
lrc_summed_unique_df_pert

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator
0,Fe ka <= -2.42,36.954984,Fe ka,-2.42,<=
1,Ti ka <= -0.37,0.441751,Ti ka,-0.37,<=
2,Fe kb <= 0.90,0.288124,Fe kb,0.90,<=
3,Ca ka > -0.55,0.180563,Ca ka,-0.55,>
4,K > 0.09,0.180399,K,0.09,>
5,background6 > 0.14,0.100959,background6,0.14,>
6,background3 > 0.12,0.090403,background3,0.12,>
7,Si > 0.18,0.083742,Si,0.18,>
8,Ca kb <= 0.23,0.075052,Ca kb,0.23,<=
9,background8 > 0.16,0.072511,background8,0.16,>
10,background4 > -0.29,0.071500,background4,-0.29,>
11,Mn <= -0.33,0.067904,Mn,-0.33,<=
12,Al <= -0.14,0.059360,Al,-0.14,<=
13,Rh L + Ar <= -0.21,0.045669,Rh L + Ar,-0.21,<=
14,background7 > 0.12,0.044935,background7,0.12,>
15,S > -0.09,0.042092,S,-0.09,>
16,Ti kb > 0.24,0.041001,Ti kb,0.24,>
17,sum Fe <= -0.27,0.039180,sum Fe,-0.27,<=
18,Cr > -0.17,0.037625,Cr,-0.17,>
19,background1 > -0.10,0.037383,background1,-0.10,>
20,background5 > 0.12,0.037061,background5,0.12,>
21,background2 > 0.07,0.036776,background2,0.07,>
22,Cu > 0.15,0.034985,Cu,0.15,>
23,Fe ka + Ti ka <= -0.11,0.032993,Fe ka + Ti ka,-0.11,<=
24,P <= -0.13,0.027658,P,-0.13,<=
25,Class_B,0.000000,None,None,None

In [16]:
lrc_all_seeds

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator,Seed
0,Fe ka <= -2.42,21.531541,Fe ka,-2.42,<=,0
1,Fe ka <= 2.41,14.977370,Fe ka,2.41,<=,0
2,Fe ka <= 4.61,10.180175,Fe ka,4.61,<=,0
3,Fe ka > -3.73,6.352588,Fe ka,-3.73,>,0
4,Fe ka > 2.41,3.820291,Fe ka,2.41,>,0
...,...,...,...,...,...,...
603,background2 <= -0.06,0.000023,background2,-0.06,<=,3
604,background2 <= 0.10,0.000014,background2,0.10,<=,3
605,background2 <= 0.07,0.000007,background2,0.07,<=,3
606,Class_A,0.000000,None,None,None,3
607,Class_B,0.000000,None,None,None,3

In [21]:
# Permutation importance baseado em mudança nas probabilidades previstas (predict_proba)
# Medimos a média da diferença absoluta entre as probabilidades originais e as probabilidades
# obtidas após permutar cada variável. Isso fornece uma métrica contínua de importância.
n_repeats = 10
rng = np.random.RandomState(42)
# Probabilidades base (classe 'B' mapeada para 1)
baseline_proba = svm_model[3].predict_proba(Xcalclass_prep)[:, 1]
importance_list = []
X_arr = Xcalclass_prep.copy()
for col in Xcalclass_prep.columns:
    diffs = []
    for _ in range(n_repeats):
        X_perm = X_arr.copy()
        X_perm[col] = rng.permutation(X_perm[col].values)
        perm_proba = svm_model[3].predict_proba(X_perm)[:, 1]
        diffs.append(np.mean(np.abs(baseline_proba - perm_proba)))
    importance_list.append(np.mean(diffs))

permutation_df = pd.DataFrame({
    'energy': Xcalclass_prep.columns,
    'Permutation_importance_proba': importance_list
})
permutation_df.sort_values(by='Permutation_importance_proba', ascending=False, inplace=True)
energy_to_zone_vip = {}
for zone_name, start, end in spectral_cuts:
    for e in permutation_df['energy']:
        ef = float(e)
        if start <= ef <= end:
            energy_to_zone_vip[e] = zone_name
permutation_df['Zone'] = permutation_df['energy'].map(energy_to_zone_vip)
permutation_unique_df = permutation_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
permutation_unique_df = permutation_unique_df.sort_values(by='Permutation_importance_proba', ascending=False)
permutation_unique_df

   energy  Permutation_importance_proba           Zone
0    6.42                      0.013186          Fe ka
1    4.52                      0.000848          Ti ka
2    7.08                      0.000757          Fe kb
3     3.7                      0.000560          Ca ka
4    3.32                      0.000190              K
5    5.92                      0.000185             Mn
6    1.48                      0.000123             Al
7    1.74                      0.000112             Si
8     4.9                      0.000067          Ti kb
9    2.62                      0.000063      Rh L + Ar
10   8.04                      0.000057             Cu
11  12.84                      0.000051         sum Fe
12   5.22                      0.000037             Cr
13   2.02                      0.000032              P
14   4.66                      0.000031    background4
15   4.36                      0.000028    background3
16   4.02                      0.000025          Ca kb
17   10.9                      0.000022  Fe ka + Ti ka
18   9.16                      0.000022    background6
19  11.74                      0.000020    background7
20   7.34                      0.000019    background5
21   2.54                      0.000016    background2
22  13.72                      0.000013    background8
23   1.14                      0.000007    background1
24    2.3                      0.000007              S

In [22]:
import numpy as np

max_len = max(
    len(pvector_unique_df['Zone']),
    len(shap_unique_df['Zone']),
    len(permutation_unique_df['Zone']),
    len(lrc_summed_unique_df_pert['Zone']),
    len(lrc_summed_unique_df_cov['Zone'])
)

def pad_list(lst, length):
    return list(lst) + [None] * (length - len(lst))

features_importance = pd.DataFrame({
    'SVM_pvector': pad_list(pvector_unique_df['Zone'], max_len),
    'Shap': pad_list(shap_unique_df['Zone'], max_len),
    'Permutation' : pad_list(permutation_unique_df['Zone'], max_len),
    'LRC_perturbation' : pad_list(lrc_summed_unique_df_pert['Zone'], max_len),
    'LRC_covariance' : pad_list(lrc_summed_unique_df_cov['Zone'], max_len),
})

features_importance.to_csv('feature_importance.csv', index=False, sep=';')
features_importance

,SVM_pvector,Shap,Permutation,LRC_perturbation,LRC_covariance
0,Fe ka,Fe ka,Fe ka,Fe ka,Fe ka
1,Fe kb,Ti ka,Ti ka,Ti ka,Fe kb
2,K,Ca ka,Fe kb,Fe kb,Mn
3,Mn,Fe kb,Ca ka,Ca ka,sum Fe
4,sum Fe,background6,K,K,Ti ka
5,Si,Al,Mn,background6,Si
6,Rh L + Ar,background8,Al,background3,Rh L + Ar
7,Ti kb,sum Fe,Si,Si,background4
8,Cu,Cr,Ti kb,Ca kb,background8
9,Ti ka,background7,Rh L + Ar,background8,Ti kb
10,background4,P,Cu,background4,Cu
11,Cr,S,sum Fe,Mn,Cr
12,Al,background5,Cr,Al,Ca ka
13,P,Ti kb,P,Rh L + Ar,Ca kb
14,background6,Ca kb,background4,background7,Al
15,background7,Fe ka + Ti ka,background3,S,background3
16,background5,background2,Ca kb,Ti kb,background1
17,Ca ka,Mn,Fe ka + Ti ka,sum Fe,background6
18,Fe ka + Ti ka,Cu,background6,Cr,K
19,background2,background4,background7,background1,background2
20,background8,Rh L + Ar,background5,background5,background7
21,Ca kb,background1,background2,background2,P
22,background3,background3,background8,Cu,background5
23,background1,K,background1,Fe ka + Ti ka,S
24,S,Si,S,P,None
25,None,None,None,None,None

In [23]:
import rbo
rbo_comparison = pd.DataFrame(columns=['Method_1', 'Method_2', 'RBO_Score'])
methods = features_importance.columns.tolist()
for i in range(len(methods)):
    for j in range(i + 1, len(methods)):
        method_1 = methods[i]
        method_2 = methods[j]
        # Remove None values from the lists
        list_1 = [x for x in features_importance[method_1].tolist() if x is not None]
        list_2 = [x for x in features_importance[method_2].tolist() if x is not None]
        # Truncate both lists to the same length (minimum of both)
        min_len = min(len(list_1), len(list_2))
        list_1_trunc = list_1[:min_len]
        list_2_trunc = list_2[:min_len]
        rbo_score = rbo.RankingSimilarity(list_1_trunc, list_2_trunc).rbo(p=0.7, k=10)
        rbo_comparison = pd.concat([rbo_comparison, pd.DataFrame({
            'Method_1': [method_1],
            'Method_2': [method_2],
            'RBO_Score': [rbo_score]
        })], ignore_index=True)
rbo_comparison.sort_values(by='RBO_Score', ascending=False, inplace=True)
rbo_comparison.to_csv('rbo_rank.csv', index=False, sep=';')
rbo_comparison

C:\Users\Usuario\AppData\Local\Temp\ipykernel_17228\3097109587.py:16: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

           Method_1          Method_2  RBO_Score
7       Permutation  LRC_perturbation   0.936481
5              Shap  LRC_perturbation   0.868065
4              Shap       Permutation   0.858451
3       SVM_pvector    LRC_covariance   0.854813
1       SVM_pvector       Permutation   0.688106
8       Permutation    LRC_covariance   0.684974
2       SVM_pvector  LRC_perturbation   0.664097
9  LRC_perturbation    LRC_covariance   0.664097
6              Shap    LRC_covariance   0.617019
0       SVM_pvector              Shap   0.581025