In [38]:
# Importing the necessary libraries
import pandas as pd
import numpy as np
import kennard_stone as ks
pd.options.plotting.backend = 'plotly'  # setting plotly as the backend for pandas plotting

# Add parent directory to sys.path so local module 'synthetic' (one level up) can be imported
import sys
from pathlib import Path # for path manipulations
parent_dir = Path.cwd().parent.parent.resolve() # move two levels up from current working directory
if str(parent_dir) not in sys.path: # check to avoid duplicates
    sys.path.insert(0, str(parent_dir)) # insert at the start of sys.path to prioritize local modules

# Loading a soil spectral dataset based on X-ray fluorescence (XRF)
data_complete = pd.read_csv(f'{parent_dir}/VNIR_databases/soil/plsda/soil_vnir.csv', sep=';') # local copy of Toledo 2022 dataset (os ... indica para omitir o caminho longo)
data = data_complete.loc[:, '400':'2498']


data_A = data_complete[data_complete['Class'] == 'A'].reset_index(drop=True)
data_B = data_complete[data_complete['Class'] == 'B'].reset_index(drop=True)

# splitting the data into calibration and prediction sets by kennard-stone algorithm
XA_cal, XA_pred = ks.train_test_split(data_A.loc[:, '400':'2498'], test_size=0.30) # class A
XA_cal = XA_cal.reset_index(drop=True)
XA_pred = XA_pred.reset_index(drop=True)

XB_cal, XB_pred = ks.train_test_split(data_B.loc[:, '400':'2498'], test_size=0.30) # class B
XB_cal = XB_cal.reset_index(drop=True)
XB_pred = XB_pred.reset_index(drop=True)

Xcalclass = pd.concat([XA_cal, XB_cal], axis=0).reset_index(drop=True) # concatenating both classes
Xpredclass = pd.concat([XA_pred, XB_pred], axis=0).reset_index(drop=True)
ycalclass = pd.Series(['A']*XA_cal.shape[0] + ['B']*XB_cal.shape[0]) # creating the target variable for calibration set
ypredclass = pd.Series(['A']*XA_pred.shape[0] + ['B']*XB_pred.shape[0]) # creating the target variable for prediction set

# preprocessings
import preprocessings as prepr # preprocessing methods for XRF data

# vamos converter os espectros de reflectância para absorbância
#Xcalclass = np.log10(1 / Xcalclass)
#Xpredclass = np.log10(1 / Xpredclass)

# savitzky-golay smoothing on the vnir spectra
from scipy.signal import savgol_filter
# Xcalclass_prep = pd.DataFrame(savgol_filter(Xcalclass, window_length=11, polyorder=3, deriv=0, axis=1), columns=Xcalclass.columns)
# Xpredclass_prep = pd.DataFrame(savgol_filter(Xpredclass, window_length=11, polyorder=3, deriv=0, axis=1), columns=Xpredclass.columns)
Xcalclass_prep, mean_calclass  = prepr.mc(Xcalclass)
Xpredclass_prep = Xpredclass - mean_calclass

from modeling import pls_optimized

# performing PLS-DA with optimized latent variables
plsda_results = pls_optimized(Xcalclass_prep, 
                              ycalclass,
                              LVmax=4,
                              Xpred=Xpredclass_prep,
                              ypred=ypredclass,
                              aim='classification',
                              cv=10)

# Convenience references used later
pls_model = plsda_results[3]               # fitted PLS model
vip_scores_mat = plsda_results[4]          # VIP scores matrix (features × LV)
y_pred_cont = plsda_results[5].iloc[:, -1] # continuous predictions for Xcalclass (used for MI/Cov)

# plotando o vip scores rapidamente
vip_scores_mat.T.plot()

2026-01-22 16:02:08,423 - kennard_stone.utils._pairwise:114[INFO] - Calculating pairwise distances using scikit-learn.

2026-01-22 16:02:08,429 - kennard_stone.utils._pairwise:114[INFO] - Calculating pairwise distances using scikit-learn.

2026-01-22 16:02:08,501 - kennard_stone.utils._pairwise:114[INFO] - Calculating pairwise distances using scikit-learn.

2026-01-22 16:02:08,504 - kennard_stone.utils._pairwise:114[INFO] - Calculating pairwise distances using scikit-learn.

In [39]:
import permutation as perm
spectral_cuts = [(str(start), start, start + 20) for start in range(400, 2500, 20)]
# Função para calcular importância de regiões espectrais por perturbação

# Aplicando a função aos dados
perturbation_importance_df = perm.spectral_perturbation_importance(
    model=pls_model,
    X=Xcalclass_prep,
    y_pred_original=y_pred_cont.values,
    spectral_cuts=spectral_cuts,
    perturbation_value=np.std(y_pred_cont)*(100),  # valor de perturbação
    metric='mean_diff'  # escolha: 'mean_abs_diff', 'mean_diff', 'mean_relative_dev'
 )

# Visualizando os resultados
perturbation_importance_df

     Zone  Start   End  Importance  Abs_Importance  N_Features
0     720    720   740   11.727946       11.727946          11
1     700    700   720   11.481680       11.481680          11
2     740    740   760   11.306711       11.306711          11
3     680    680   700   10.609007       10.609007          11
4     760    760   780   10.374556       10.374556          11
..    ...    ...   ...         ...             ...         ...
100  2020   2020  2040    0.866445        0.866445          11
101  1160   1160  1180   -0.726349        0.726349          11
102  2140   2140  2160    0.177111        0.177111          11
103  1140   1140  1160    0.135413        0.135413          11
104   460    460   480   -0.036287        0.036287          11

[105 rows x 6 columns]

# **VIP and SHAP**

In [35]:
import numpy as np
import pandas as pd

# vip
vip_scores_df = pd.DataFrame({
    'energy' : plsda_results[4].T.index,
    'VIP_Score' : plsda_results[4].T.iloc[:,0].values
})
vip_scores_df = vip_scores_df.sort_values(by='VIP_Score', ascending=False).reset_index(drop=True)

# vamos gerar uma nova coluna em vip_scores_df com o nome da zona espectral correspondente de acordo com a lista spectral_cuts
energy_to_zone_vip = {} # dicionário para mapear energia para zona espectral
for zone_name, start, end in spectral_cuts: # iterando sobre cada zona espectral (que tem nome, início e fim)
	for i in vip_scores_df['energy']: # iterando sobre cada valor de energia no vip_scores_df
		i_float = float(i)
		if start <= i_float <= end:
			energy_to_zone_vip[i] = zone_name
vip_scores_df['Zone'] = vip_scores_df['energy'].map(energy_to_zone_vip) # a funcao map funciona como um buscador que substitui os valores de 'energy' pelos valores correspondentes no dicionário energy_to_zone_vip

# vamos filtrar vip_scores_df para manter apenas as zonas espectrais únicas com maior VIP score
vip_scores_unique_df = vip_scores_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
vip_scores_unique_df = vip_scores_unique_df.sort_values(by='VIP_Score', ascending=False).reset_index(drop=True)

# reg vet
reg_vet = pd.DataFrame(plsda_results[3].coef_, columns=plsda_results[3].feature_names_in_) # creating a DataFrame with regression coefficients
reg_vet = reg_vet.T
reg_vet.insert(0, 'energy', reg_vet.index) # adding energy column
reg_vet = reg_vet.reset_index(drop=True)
reg_vet.columns = ['energy', 'Reg_coef'] # renaming
reg_vet['Abs_Reg_coef'] = reg_vet['Reg_coef'].abs() # adding absolute value column
reg_vet = reg_vet.sort_values(by='Abs_Reg_coef', ascending=False).reset_index(drop=True) # sorting by absolute value

# gerando uma nova coluna em reg_vet com o nome da zona espectral correspondente de acordo com a lista spectral_cuts
energy_to_zone_reg = {} # dicionário para mapear energia para zona espectral
for zone_name, start, end in spectral_cuts: # iterando sobre cada zona espectral (que tem nome, início e fim)
    for i in reg_vet['energy']: # iterando sobre cada valor de energia no reg_vet
        i_float = float(i)
        if start <= i_float <= end:
            energy_to_zone_reg[i] = zone_name
reg_vet['Zone'] = reg_vet['energy'].map(energy_to_zone_reg) # a funcao map funciona como um buscador que substitui os valores de 'energy' pelos valores correspondentes no dicionário energy_to_zone_reg
reg_vet

# vamos filtrar reg_vet para manter apenas as zonas espectrais únicas com maior valor absoluto do coeficiente de regressão
reg_vet_unique_df = reg_vet.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
reg_vet_unique_df = reg_vet_unique_df.sort_values(by='Abs_Reg_coef', ascending=False).reset_index(drop=True)
shap_unique_df = pd.read_csv('shap_soil_vnir.csv', sep=';') # loading previously saved shap_unique_df

In [36]:
vip_scores_unique_df

    energy  VIP_Score  Zone
0      732   2.124840   720
1      740   2.115541   740
2      718   2.097244   700
3      760   2.023045   760
4      698   1.982863   680
..     ...        ...   ...
100   1860   0.555505  1860
101   1258   0.545316  1240
102   1180   0.528402  1180
103   1238   0.517629  1220
104   1200   0.503248  1200

[105 rows x 3 columns]

In [22]:
# vamos utilizar a permutation do sklearn para realizar uma permutacao no modelo plsda
from sklearn.inspection import permutation_importance
perm_importance = permutation_importance(pls_model, 
                                           Xcalclass_prep, 
                                           y_pred_cont,
                                           n_repeats=5,
                                           random_state=0,
                                           scoring='neg_mean_absolute_error',
                                           n_jobs=30)
# pegando as importancias
perm_importances_values = pd.Series(perm_importance.importances_mean, index=Xcalclass_prep.columns)

# vip
perm_df = pd.DataFrame({
    'energy' : plsda_results[4].T.index,
    'Perm' : perm_importance.importances_mean
})
perm_df = perm_df.sort_values(by='Perm', ascending=False).reset_index(drop=True)

# vamos gerar uma nova coluna em vip_scores_df com o nome da zona espectral correspondente de acordo com a lista spectral_cuts
energy_to_zone_perm = {} # dicionário para mapear energia para zona espectral
for zone_name, start, end in spectral_cuts: # iterando sobre cada zona espectral (que tem nome, início e fim)
	for i in perm_df['energy']: # iterando sobre cada valor de energia no vip_scores_df
		i_float = float(i)
		if start <= i_float <= end:
			energy_to_zone_perm[i] = zone_name
perm_df['Zone'] = perm_df['energy'].map(energy_to_zone_perm) # a funcao map funciona como um buscador que substitui os valores de 'energy' pelos valores correspondentes no dicionário energy_to_zone_vip

# vamos filtrar vip_scores_df para manter apenas as zonas espectrais únicas com maior VIP score
perm_unique_df = perm_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
perm_unique_df = perm_unique_df.sort_values(by='Perm', ascending=False).reset_index(drop=True)
perm_unique_df

   energy      Perm  Zone
0     740  0.002448   700
1     750  0.002411   750
2     698  0.001969   650
3    1410  0.001873  1400
4    1382  0.001841  1350
5    1554  0.001822  1550
6    1548  0.001817  1500
7    1600  0.001804  1600
8    2206  0.001737  2200
9    1650  0.001723  1650
10   1498  0.001704  1450
11    548  0.001623   500
12    800  0.001622   800
13    550  0.001621   550
14   2180  0.001596  2150
15   1700  0.001576  1700
16   1348  0.001571  1300
17   1028  0.001566  1000
18   1916  0.001545  1900
19   1050  0.001506  1050
20    998  0.001472   950
21   1750  0.001409  1750
22   1800  0.001276  1800
23   1100  0.001263  1100
24   1298  0.001234  1250
25   1850  0.001131  1850
26   1950  0.001129  1950
27   2466  0.001101  2450
28   2424  0.001087  2400
29    948  0.001009   900
30    850  0.000873   850
31    648  0.000862   600
32    498  0.000799   450
33   1248  0.000765  1200
34   2288  0.000676  2250
35   2300  0.000654  2300
36   2000  0.000604  2000
37   1150  0.000579  1150
38   2398  0.000547  2350
39   2056  0.000490  2050
40   2100  0.000427  2100
41    424  0.000291   400

# **bagging - covariance**

In [ ]:
import explaining as exp
spectral_zones_class = exp.extract_spectral_zones(Xcalclass_prep, spectral_cuts)
zone_sums_df = exp.aggregate_spectral_zones(spectral_zones_class, aggregator='extreme')
predicates_quantiles = exp.predicates_by_quantiles(zone_sums_df, [0.2, 0.4, 0.6, 0.8])
co_occurrence_matrix_df = predicates_quantiles[2]
predicate_info_dict = exp.create_predicate_info_dict(
    predicates_df=predicates_quantiles[0],
    predicate_indicator_df=predicates_quantiles[1],
    zone_aggregated_df=zone_sums_df,
    y_predicted_numeric=y_pred_cont
)

# LISTA DE SEMENTES A TESTAR
random_seeds = [0, 1, 2]

all_results_cov = {}
training_samples = len(Xcalclass)

# LOOP: PROCESSAR CADA SEMENTE
y_predicted_numeric = plsda_results[5].iloc[:, -1] # predições numéricas do modelo

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando semente: {seed}")
    print(f"{'='*70}\n")
    # Bagging
    bags_result_seed = exp.bagging_predicates(
        zone_sums_df=zone_sums_df,
        y_predicted_numeric=y_predicted_numeric,
        predicates_df=predicates_quantiles[0],
        n_bags=20,
        #n_predicates_per_bag=40,
        n_samples_per_bag=int(training_samples*0.5), # 80 % da base para amostrar (convertido para int)
        min_samples_per_predicate=int(training_samples*0.2), # 20 % da base para limitar (convertido para int)
        replace=False,
        sample_bagging=True,
        predicate_bagging=False,
        random_seed=seed
    )
    # Inserir classe prevista
    for bag_name, pred_dict in bags_result_seed.items(): # iterando sobre cada bag
        for pred_rule, df_info in pred_dict.items():
            df_info['Class_Predicted'] = np.where(df_info['Predicted_Y'] >= 0.5, 'A', 'B') # binarizando com threshold 0.5, A = eut, B = dist
    # Calcular MI
    cov_results_dict_seed = exp.calculate_predicate_metrics(
        bags_result=bags_result_seed,
        metric='covariance', # covariance ou mutual_information
        threshold=0.001, # threshold para cortar predicados irrelevantes
        n_neighbors=5
    )
    # Salvar no dicionário principal
    all_results_cov[seed] = {
        'bags_result': bags_result_seed,
        'cov_results_dict': cov_results_dict_seed
    }

# CONSTRUÇÃO DE GRAFOS PARA MÚLTIPLAS SEMENTES (LOOP EXTERNO)
# Dicionário para armazenar grafos
graphs_by_seed = {}

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando Grafo - Semente: {seed}")
    print(f"{'='*70}\n")
    # Construir grafo para esta semente
    DG = exp.build_predicate_graph(
        bags_result=all_results_cov[seed]['bags_result'],
        mi_results_dict=all_results_cov[seed]['cov_results_dict'],
        co_occurrence_matrix_df=co_occurrence_matrix_df,
        predicates_df=predicates_quantiles[0],
        random_state=seed,
        show_details=True
    )
    # Armazenar grafo
    graphs_by_seed[seed] = DG  

# Calcular LRC usando a função pronta do explaining.py
lrc_cov_by_seed = {}
for seed in random_seeds:
    DG = graphs_by_seed[seed]
    lrc_cov_df_seed = exp.calculate_lrc_single_graph(DG, predicates_quantiles[0])
    lrc_cov_df_seed['Seed'] = seed  # Adicionar coluna com a semente
    lrc_cov_by_seed[seed] = lrc_cov_df_seed

# junando todas as colunas 'Node' de lrc_by_seed em um único dataframe
lrc_cov_all_seeds_df = pd.DataFrame()
for seed in random_seeds:
    lrc_cov_df_seed = lrc_cov_by_seed[seed].rename(columns={'Node': f'Predicate_Cov_Seed_{seed}'})
    lrc_cov_all_seeds_df = pd.concat([lrc_cov_all_seeds_df, lrc_cov_df_seed[[f'Predicate_Cov_Seed_{seed}']]], axis=1)

# vamos filtrar lrc_by_seed em cada semente para manter apenas as zonas espectrais únicas com maior LRC em um mesmo dataframe
lrc_cov_unique_by_seed = {}
for seed, lrc_df in lrc_cov_by_seed.items():
    lrc_cov_unique_df = lrc_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
    lrc_cov_unique_df = lrc_cov_unique_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
    lrc_cov_unique_by_seed[seed] = lrc_cov_unique_df

lrc_cov_all_seeds_df # exibindo o dataframe consolidado com predicados de todas as sementes

======================================================================
Processando semente: 0
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 109 | Descartados: 59
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 106 | Descartados: 62
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 101 | Descartados: 67
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 104 | Descartados: 64
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 101 | Descartados: 67
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 107 | Descartados: 61
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 105 | Descartados: 63
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 104 | Descartados: 64
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 105 | Descartados: 63
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 101 | Descartados: 67
Bag_11 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 111 | Descartados: 57
Bag_12 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 106 | Descartados: 62
Bag_13 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 102 | Descartados: 66
Bag_14 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 105 | Descartados: 63
Bag_15 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 111 | Descartados: 57
Bag_16 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 109 | Descartados: 59
Bag_17 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 107 | Descartados: 61
Bag_18 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 111 | Descartados: 57
Bag_19 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 109 | Descartados: 59
Bag_20 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 104 | Descartados: 64
Calculando Mutual_Info para Predicados
Métrica: mutual_info
Threshold: 0.001

======================================================================
Processando semente: 1
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 109 | Descartados: 59
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 110 | Descartados: 58
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 109 | Descartados: 59
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 113 | Descartados: 55
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 112 | Descartados: 56
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 106 | Descartados: 62
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 106 | Descartados: 62
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 104 | Descartados: 64
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 104 | Descartados: 64
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 112 | Descartados: 56
Bag_11 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 103 | Descartados: 65
Bag_12 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 110 | Descartados: 58
Bag_13 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 111 | Descartados: 57
Bag_14 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 103 | Descartados: 65
Bag_15 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 116 | Descartados: 52
Bag_16 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 110 | Descartados: 58
Bag_17 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 105 | Descartados: 63
Bag_18 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 101 | Descartados: 67
Bag_19 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 112 | Descartados: 56
Bag_20 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 107 | Descartados: 61
Calculando Mutual_Info para Predicados
Métrica: mutual_info
Threshold: 0.001

======================================================================
Processando semente: 2
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 107 | Descartados: 61
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 95 | Descartados: 73
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 116 | Descartados: 52
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 101 | Descartados: 67
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 110 | Descartados: 58
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 107 | Descartados: 61
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 106 | Descartados: 62
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 100 | Descartados: 68
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 107 | Descartados: 61
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 111 | Descartados: 57
Bag_11 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 113 | Descartados: 55
Bag_12 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 104 | Descartados: 64
Bag_13 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 105 | Descartados: 63
Bag_14 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 106 | Descartados: 62
Bag_15 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 102 | Descartados: 66
Bag_16 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 112 | Descartados: 56
Bag_17 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 111 | Descartados: 57
Bag_18 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 103 | Descartados: 65
Bag_19 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 108 | Descartados: 60
Bag_20 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 101 | Descartados: 67
Calculando Mutual_Info para Predicados
Métrica: mutual_info
Threshold: 0.001

======================================================================
Processando Grafo - Semente: 0
======================================================================


Total de pares bidirecionais encontrados: 128
Removida aresta 1600 > -0.04 -> 1700 > -0.04 (peso 225.0)
Mantida aresta 1700 > -0.04 -> 1600 > -0.04 (peso 1125.0)

======================================================================

Removida aresta 1600 > -0.04 -> 1500 > -0.02 (peso 181.0)
Mantida aresta 1500 > -0.02 -> 1600 > -0.04 (peso 362.0)

======================================================================

Removida aresta 1400 > -0.01 -> 1600 > -0.04 (peso 155.0)
Mantida aresta 1600 > -0.04 -> 1400 > -0.01 (peso 465.0)

======================================================================

Removida aresta 1200 > -0.01 -> 1600 > -0.04 (peso 161.0)
Mantida aresta 1600 > -0.04 -> 1200 > -0.01 (peso 322.0)

======================================================================

Empate! Removida aresta 1900 > -0.01 -> 1600 > -0.04 (peso 154.0)
Mantida aresta 1600 > -0.04 -> 1900 > -0.01 (peso 154.0)

======================================================================

Removida aresta 1700 > -0.04 -> 1800 > -0.02 (peso 179.0)
Mantida aresta 1800 > -0.02 -> 1700 > -0.04 (peso 358.0)

======================================================================

Removida aresta 1700 > -0.04 -> 1900 > -0.04 (peso 221.0)
Mantida aresta 1900 > -0.04 -> 1700 > -0.04 (peso 663.0)

======================================================================

Empate! Removida aresta 1100 > -0.01 -> 1700 > -0.04 (peso 164.0)
Mantida aresta 1700 > -0.04 -> 1100 > -0.01 (peso 164.0)

======================================================================

Empate! Removida aresta 1300 > -0.01 -> 1700 > -0.04 (peso 155.0)
Mantida aresta 1700 > -0.04 -> 1300 > -0.01 (peso 155.0)

======================================================================

Removida aresta 2300 > 0.01 -> 2200 > 0.01 (peso 116.0)
Mantida aresta 2200 > 0.01 -> 2300 > 0.01 (peso 232.0)

======================================================================

Empate! Removida aresta 2400 > -0.02 -> 2200 > 0.01 (peso 120.0)
Mantida aresta 2200 > 0.01 -> 2400 > -0.02 (peso 120.0)

======================================================================

Removida aresta 1300 > -0.03 -> 1600 > -0.01 (peso 156.0)
Mantida aresta 1600 > -0.01 -> 1300 > -0.03 (peso 312.0)

======================================================================

Empate! Removida aresta 1600 > -0.01 -> 900 > 0.01 (peso 107.0)
Mantida aresta 900 > 0.01 -> 1600 > -0.01 (peso 107.0)

======================================================================

Empate! Removida aresta 1100 > 0.01 -> 1600 > -0.01 (peso 108.0)
Mantida aresta 1600 > -0.01 -> 1100 > 0.01 (peso 108.0)

======================================================================

Empate! Removida aresta 1700 > -0.01 -> 1800 > -0.02 (peso 153.0)
Mantida aresta 1800 > -0.02 -> 1700 > -0.01 (peso 153.0)

======================================================================

Empate! Removida aresta 1400 > -0.04 -> 1700 > -0.01 (peso 153.0)
Mantida aresta 1700 > -0.01 -> 1400 > -0.04 (peso 153.0)

======================================================================

Empate! Removida aresta 1500 > -0.02 -> 1700 > -0.01 (peso 153.0)
Mantida aresta 1700 > -0.01 -> 1500 > -0.02 (peso 153.0)

======================================================================

Empate! Removida aresta 1700 > -0.01 -> 1800 > 0.01 (peso 113.0)
Mantida aresta 1800 > 0.01 -> 1700 > -0.01 (peso 113.0)

======================================================================

Removida aresta 1500 > -0.02 -> 1300 > -0.03 (peso 181.0)
Mantida aresta 1300 > -0.03 -> 1500 > -0.02 (peso 362.0)

======================================================================

Empate! Removida aresta 1300 > -0.01 -> 1300 > -0.03 (peso 155.0)
Mantida aresta 1300 > -0.03 -> 1300 > -0.01 (peso 155.0)

======================================================================

Empate! Removida aresta 1400 > -0.01 -> 1300 > -0.03 (peso 155.0)
Mantida aresta 1300 > -0.03 -> 1400 > -0.01 (peso 155.0)

======================================================================

Removida aresta 1300 > -0.03 -> 2300 > -0.04 (peso 191.0)
Mantida aresta 2300 > -0.04 -> 1300 > -0.03 (peso 382.0)

======================================================================

Empate! Removida aresta 1900 > -0.04 -> 1500 > -0.02 (peso 181.0)
Mantida aresta 1500 > -0.02 -> 1900 > -0.04 (peso 181.0)

======================================================================

Empate! Removida aresta 1400 > -0.04 -> 1500 > -0.02 (peso 362.0)
Mantida aresta 1500 > -0.02 -> 1400 > -0.04 (peso 362.0)

======================================================================

Removida aresta 1500 > -0.02 -> 1500 > -0.04 (peso 181.0)
Mantida aresta 1500 > -0.04 -> 1500 > -0.02 (peso 362.0)

======================================================================

Empate! Removida aresta 1500 > -0.02 -> 900 > -0.01 (peso 166.0)
Mantida aresta 900 > -0.01 -> 1500 > -0.02 (peso 166.0)

======================================================================

Removida aresta 1500 > -0.04 -> 1800 > -0.04 (peso 218.0)
Mantida aresta 1800 > -0.04 -> 1500 > -0.04 (peso 654.0)

======================================================================

Empate! Removida aresta 1800 > -0.04 -> 1600 <= 0.04 (peso 172.0)
Mantida aresta 1600 <= 0.04 -> 1800 > -0.04 (peso 172.0)

======================================================================

Empate! Removida aresta 1800 > -0.04 -> 1200 > -0.03 (peso 200.0)
Mantida aresta 1200 > -0.03 -> 1800 > -0.04 (peso 200.0)

======================================================================

Removida aresta 1800 > -0.04 -> 600 <= -0.01 (peso 64.0)
Mantida aresta 600 <= -0.01 -> 1800 > -0.04 (peso 128.0)

======================================================================

Empate! Removida aresta 1900 > -0.01 -> 2400 > 0.01 (peso 113.0)
Mantida aresta 2400 > 0.01 -> 1900 > -0.01 (peso 113.0)

======================================================================

Empate! Removida aresta 2100 > -0.04 -> 1500 > -0.04 (peso 212.0)
Mantida aresta 1500 > -0.04 -> 2100 > -0.04 (peso 212.0)

======================================================================

Removida aresta 1500 > -0.04 -> 1200 > -0.01 (peso 161.0)
Mantida aresta 1200 > -0.01 -> 1500 > -0.04 (peso 322.0)

======================================================================

Removida aresta 1500 > -0.04 -> 1400 > -0.04 (peso 229.0)
Mantida aresta 1400 > -0.04 -> 1500 > -0.04 (peso 458.0)

======================================================================

Removida aresta 1200 > -0.03 -> 1000 > -0.01 (peso 172.0)
Mantida aresta 1000 > -0.01 -> 1200 > -0.03 (peso 344.0)

======================================================================

Empate! Removida aresta 2400 > -0.04 -> 1000 > -0.01 (peso 162.0)
Mantida aresta 1000 > -0.01 -> 2400 > -0.04 (peso 162.0)

======================================================================

Empate! Removida aresta 900 > 0.01 -> 1000 > -0.01 (peso 109.0)
Mantida aresta 1000 > -0.01 -> 900 > 0.01 (peso 109.0)

======================================================================

Empate! Removida aresta 1800 <= 0.04 -> 1000 > -0.01 (peso 123.0)
Mantida aresta 1000 > -0.01 -> 1800 <= 0.04 (peso 123.0)

======================================================================

Empate! Removida aresta 1000 > -0.01 -> 1100 > -0.03 (peso 172.0)
Mantida aresta 1100 > -0.03 -> 1000 > -0.01 (peso 172.0)

======================================================================

Empate! Removida aresta 1100 > -0.03 -> 1200 > -0.03 (peso 209.0)
Mantida aresta 1200 > -0.03 -> 1100 > -0.03 (peso 209.0)

======================================================================

Empate! Removida aresta 1200 > -0.03 -> 1700 > 0.01 (peso 106.0)
Mantida aresta 1700 > 0.01 -> 1200 > -0.03 (peso 106.0)

======================================================================

Empate! Removida aresta 1100 > 0.01 -> 1200 > -0.03 (peso 108.0)
Mantida aresta 1200 > -0.03 -> 1100 > 0.01 (peso 108.0)

======================================================================

Empate! Removida aresta 1200 > -0.03 -> 1300 <= 0.01 (peso 99.0)
Mantida aresta 1300 <= 0.01 -> 1200 > -0.03 (peso 99.0)

======================================================================

Removida aresta 1300 > -0.01 -> 1100 > -0.03 (peso 155.0)
Mantida aresta 1100 > -0.03 -> 1300 > -0.01 (peso 310.0)

======================================================================

Removida aresta 1100 > -0.01 -> 1100 > -0.03 (peso 164.0)
Mantida aresta 1100 > -0.03 -> 1100 > -0.01 (peso 328.0)

======================================================================

Empate! Removida aresta 2000 > -0.04 -> 1100 > -0.03 (peso 198.0)
Mantida aresta 1100 > -0.03 -> 2000 > -0.04 (peso 198.0)

======================================================================

Removida aresta 1400 > -0.01 -> 1300 > -0.01 (peso 154.0)
Mantida aresta 1300 > -0.01 -> 1400 > -0.01 (peso 308.0)

======================================================================

Empate! Removida aresta 1400 <= 0.04 -> 1300 > -0.01 (peso 106.0)
Mantida aresta 1300 > -0.01 -> 1400 <= 0.04 (peso 106.0)

======================================================================

Empate! Removida aresta 1400 > -0.01 -> 1100 > -0.01 (peso 153.0)
Mantida aresta 1100 > -0.01 -> 1400 > -0.01 (peso 153.0)

======================================================================

Removida aresta 2300 > -0.02 -> 2200 > -0.04 (peso 174.0)
Mantida aresta 2200 > -0.04 -> 2300 > -0.02 (peso 522.0)

======================================================================

Empate! Removida aresta 2300 > -0.02 -> 2100 > -0.04 (peso 174.0)
Mantida aresta 2100 > -0.04 -> 2300 > -0.02 (peso 174.0)

======================================================================

Empate! Removida aresta 1900 > 0.01 -> 2300 > -0.02 (peso 113.0)
Mantida aresta 2300 > -0.02 -> 1900 > 0.01 (peso 113.0)

======================================================================

Empate! Removida aresta 1800 > -0.02 -> 1100 > -0.01 (peso 154.0)
Mantida aresta 1100 > -0.01 -> 1800 > -0.02 (peso 154.0)

======================================================================

Empate! Removida aresta 2000 > -0.04 -> 1800 > -0.02 (peso 179.0)
Mantida aresta 1800 > -0.02 -> 2000 > -0.04 (peso 179.0)

======================================================================

Empate! Removida aresta 1100 > -0.01 -> 1600 <= -0.01 (peso 13.0)
Mantida aresta 1600 <= -0.01 -> 1100 > -0.01 (peso 13.0)

======================================================================

Empate! Removida aresta 1200 > -0.01 -> 1400 > -0.04 (peso 161.0)
Mantida aresta 1400 > -0.04 -> 1200 > -0.01 (peso 161.0)

======================================================================

Empate! Removida aresta 2100 > 0.01 -> 1900 > -0.01 (peso 117.0)
Mantida aresta 1900 > -0.01 -> 2100 > 0.01 (peso 117.0)

======================================================================

Removida aresta 1900 > -0.04 -> 1900 > -0.01 (peso 154.0)
Mantida aresta 1900 > -0.01 -> 1900 > -0.04 (peso 308.0)

======================================================================

Empate! Removida aresta 2200 > -0.02 -> 1900 > -0.01 (peso 153.0)
Mantida aresta 1900 > -0.01 -> 2200 > -0.02 (peso 153.0)

======================================================================

Empate! Removida aresta 600 <= 0.02 -> 1900 > -0.01 (peso 92.0)
Mantida aresta 1900 > -0.01 -> 600 <= 0.02 (peso 92.0)

======================================================================

Empate! Removida aresta 1600 <= 0.04 -> 500 > 0.02 (peso 87.0)
Mantida aresta 500 > 0.02 -> 1600 <= 0.04 (peso 87.0)

======================================================================

Removida aresta 1200 > -0.01 -> 1000 > -0.03 (peso 161.0)
Mantida aresta 1000 > -0.03 -> 1200 > -0.01 (peso 322.0)

======================================================================

Empate! Removida aresta 1000 > -0.03 -> 1700 <= -0.01 (peso 64.0)
Mantida aresta 1700 <= -0.01 -> 1000 > -0.03 (peso 64.0)

======================================================================

Empate! Removida aresta 1200 > -0.01 -> 1600 <= 0.04 (peso 112.0)
Mantida aresta 1600 <= 0.04 -> 1200 > -0.01 (peso 112.0)

======================================================================

Empate! Removida aresta 600 <= 0.01 -> 1200 > -0.01 (peso 53.0)
Mantida aresta 1200 > -0.01 -> 600 <= 0.01 (peso 53.0)

======================================================================

Empate! Removida aresta 1900 > -0.04 -> 2100 > 0.01 (peso 117.0)
Mantida aresta 2100 > 0.01 -> 1900 > -0.04 (peso 117.0)

======================================================================

Removida aresta 1900 > -0.04 -> 2000 > -0.04 (peso 223.0)
Mantida aresta 2000 > -0.04 -> 1900 > -0.04 (peso 446.0)

======================================================================

Empate! Removida aresta 800 <= 0.01 -> 2000 > -0.01 (peso 48.0)
Mantida aresta 2000 > -0.01 -> 800 <= 0.01 (peso 48.0)

======================================================================

Empate! Removida aresta 2000 > -0.04 -> 2000 > -0.01 (peso 155.0)
Mantida aresta 2000 > -0.01 -> 2000 > -0.04 (peso 155.0)

======================================================================

Empate! Removida aresta 2000 > -0.01 -> 700 <= 0.01 (peso 55.0)
Mantida aresta 700 <= 0.01 -> 2000 > -0.01 (peso 55.0)

======================================================================

Empate! Removida aresta 400 > 0.02 -> 1700 <= 0.01 (peso 66.0)
Mantida aresta 1700 <= 0.01 -> 400 > 0.02 (peso 66.0)

======================================================================

Removida aresta 2200 > -0.02 -> 2400 > -0.02 (peso 167.0)
Mantida aresta 2400 > -0.02 -> 2200 > -0.02 (peso 334.0)

======================================================================

Removida aresta 600 <= 0.02 -> 2200 > -0.02 (peso 110.0)
Mantida aresta 2200 > -0.02 -> 600 <= 0.02 (peso 220.0)

======================================================================

Empate! Removida aresta 2200 > -0.02 -> 900 > -0.03 (peso 169.0)

/home/jvribeiro/.local/lib/python3.10/site-packages/networkx/algorithms/centrality/reaching.py:193: RuntimeWarning:

divide by zero encountered in scalar divide

Processando LRC do grafo...

/home/jvribeiro/.local/lib/python3.10/site-packages/networkx/algorithms/centrality/reaching.py:193: RuntimeWarning:

divide by zero encountered in scalar divide

Processando LRC do grafo...

/home/jvribeiro/.local/lib/python3.10/site-packages/networkx/algorithms/centrality/reaching.py:193: RuntimeWarning:

divide by zero encountered in scalar divide

    Predicate_Cov_Seed_0 Predicate_Cov_Seed_1 Predicate_Cov_Seed_2
0           1700 > -0.04         1500 > -0.04         1500 > -0.04
1           1900 > -0.04         1800 > -0.02         1300 > -0.01
2           800 <= -0.01         1400 > -0.01         1400 > -0.04
3           2000 > -0.04         1700 > -0.04         1500 > -0.02
4            1800 > 0.01         1600 > -0.04         1600 > -0.04
..                   ...                  ...                  ...
118          700 > -0.01        2100 <= -0.02              Class_A
119          1100 > 0.01        2400 <= -0.02              Class_B
120         700 <= -0.01         800 <= -0.01                  NaN
121              Class_A              Class_A                  NaN
122              Class_B              Class_B                  NaN

[123 rows x 3 columns]

In [11]:
from permutation import calculate_predicate_metrics_permutation

# LISTA DE SEMENTES A TESTAR
random_seeds = [0]

all_results_perm = {}
training_samples = len(Xcalclass)

# LOOP: PROCESSAR CADA SEMENTE
y_predicted_numeric = plsda_results[5].iloc[:, -1] # predições numéricas do modelo

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando semente: {seed}")
    print(f"{'='*70}\n")
    # Bagging
    bags_result_seed = exp.bagging_predicates(
        zone_sums_df=zone_sums_df,
        y_predicted_numeric=y_predicted_numeric,
        predicates_df=predicates_quantiles[0],
        n_bags=20,
        #n_predicates_per_bag=40,
        n_samples_per_bag=int(training_samples*0.5), # 80 % da base para amostrar (convertido para int)
        min_samples_per_predicate=int(training_samples*0.2), # 20 % da base para limitar (convertido para int)
        replace=False,
        sample_bagging=True,
        predicate_bagging=False,
        random_seed=seed
    )
    # Inserir classe prevista
    for bag_name, pred_dict in bags_result_seed.items(): # iterando sobre cada bag
        for pred_rule, df_info in pred_dict.items():
            df_info['Class_Predicted'] = np.where(df_info['Predicted_Y'] >= 0.5, 'A', 'B') # binarizando com threshold 0.5, A = eut, B = dist

    perm_results_seed = calculate_predicate_metrics_permutation(
        estimator=pls_model,
        Xcalclass_prep=Xcalclass_prep,
        y_calclass=ycalclass,
        folds_struct=bags_result_seed,
        predicates_df=predicates_quantiles[0],
        spectral_cuts=spectral_cuts,
        scoring='accuracy',
        task_type='classification',
        n_repeats=5,  # Usar 10-20 em produção para resultados mais estáveis
        random_state=0,
        n_jobs=33, # se usar 22 significa que vai usar 22 núcleos do processador em paralelo
        verbose=True,
        save_detailed_results=True
    )

    # Remove todos os valores iguais a zero de todos os bags em perm_results[bag]["Permutation"] e salva como perm_results_thresholded
    perm_results_seed_thresholded = {}
    for bag, df in perm_results_seed.items():
        # Verifica se é um DataFrame e se a coluna 'Permutation' existe
        if isinstance(df, pd.DataFrame) and 'Permutation' in df.columns:
            filtered_df = df[df['Permutation'] > 0].copy()
            perm_results_seed_thresholded[bag] = filtered_df
        else:
            # Se não for DataFrame esperado, apenas copia
            perm_results_seed_thresholded[bag] = df

    # Salvar no dicionário principal
    all_results_perm[seed] = {
        'bags_result': bags_result_seed,
        'perm_results_dict': perm_results_seed_thresholded
    }

# CONSTRUÇÃO DE GRAFOS PARA MÚLTIPLAS SEMENTES (LOOP EXTERNO)
# Dicionário para armazenar grafos
graphs_perm_by_seed = {}

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando Grafo - Semente: {seed}")
    print(f"{'='*70}\n")
    # Construir grafo para esta semente
    DG = exp.build_predicate_graph(
        bags_result=all_results_perm[seed]['bags_result'],
        mi_results_dict=all_results_perm[seed]['perm_results_dict'],
        co_occurrence_matrix_df=co_occurrence_matrix_df,
        predicates_df=predicates_quantiles[0],
        random_state=seed,
        show_details=True
    )
    # Armazenar grafo
    graphs_perm_by_seed[seed] = DG  

# Calcular LRC usando a função pronta do explaining.py
lrc_perm_by_seed = {}
for seed in random_seeds:
    DG = graphs_perm_by_seed[seed]
    lrc_perm_df_seed = exp.calculate_lrc_single_graph(DG, predicates_quantiles[0])
    lrc_perm_df_seed['Seed'] = seed  # Adicionar coluna com a semente
    lrc_perm_by_seed[seed] = lrc_perm_df_seed

# junando todas as colunas 'Node' de lrc_by_seed em um único dataframe
lrc_perm_all_seeds_df = pd.DataFrame()
for seed in random_seeds:
    lrc_perm_df_seed = lrc_perm_by_seed[seed].rename(columns={'Node': f'Predicate_perm_Seed_{seed}'})
    lrc_perm_all_seeds_df = pd.concat([lrc_perm_all_seeds_df, lrc_perm_df_seed[[f'Predicate_perm_Seed_{seed}']]], axis=1)

# vamos filtrar lrc_by_seed em cada semente para manter apenas as zonas espectrais únicas com maior LRC em um mesmo dataframe
lrc_perm_unique_by_seed = {}
for seed, lrc_df in lrc_perm_by_seed.items():
    lrc_perm_unique_df = lrc_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
    lrc_perm_unique_df = lrc_perm_unique_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
    lrc_perm_unique_by_seed[seed] = lrc_perm_unique_df

lrc_perm_all_seeds_df # exibindo o dataframe consolidado com predicados de todas as sementes

======================================================================
Processando semente: 0
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 109 | Descartados: 59
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 106 | Descartados: 62
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 101 | Descartados: 67
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 104 | Descartados: 64
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 101 | Descartados: 67
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 107 | Descartados: 61
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 105 | Descartados: 63
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 104 | Descartados: 64
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 105 | Descartados: 63
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 101 | Descartados: 67
Bag_11 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 111 | Descartados: 57
Bag_12 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 106 | Descartados: 62
Bag_13 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 102 | Descartados: 66
Bag_14 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 105 | Descartados: 63
Bag_15 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 111 | Descartados: 57
Bag_16 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 109 | Descartados: 59
Bag_17 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 107 | Descartados: 61
Bag_18 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 111 | Descartados: 57
Bag_19 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 109 | Descartados: 59
Bag_20 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 104 | Descartados: 64
======================================================================
PERMUTATION IMPORTANCE PARA PREDICADOS
======================================================================
Tipo de tarefa: classification
Métrica de scoring: accuracy
Número de repetições: 5
Random state: 0
Total de folds: 20


[Bag_1] Processando 109 predicados...
  Predicado: 400 > -0.05 (n=110)
    Zona: 51 colunas
    Usando permutação manual do bloco
    Tipo de tarefa: classification
    Predições baseline: (array(['A', 'B'], dtype='<U1'), array([  1, 109]))
    y_true: (array(['A', 'B'], dtype=object), array([96, 14]))
    Baseline score: 0.1364
    Rep 1: permuted_score=0.1364, importance=0.0000
    Rep 2: permuted_score=0.1364, importance=0.0000
    Rep 3: permuted_score=0.1364, importance=0.0000
    Importance: 0.000000 ± 0.000000
  Predicado: 400 <= -0.02 (n=55)
    Zona: 51 colunas
    Usando permutação manual do bloco
    Tipo de tarefa: classification
    Predições baseline: (array(['B'], dtype='<U1'), array([55]))
    y_true: (array(['A', 'B'], dtype=object), array([48,  7]))
    Baseline score: 0.1273
    Rep 1: permuted_score=0.1273, importance=0.0000
    Rep 2: permuted_score=0.1273, importance=0.0000
    Rep 3: permuted_score=0.1273, importance=0.0000
    Importance: 0.000000 ± 0.000000
  Predicado: 400 > -0.02 (n=82)
    Zona: 51 colunas
    Usando permutação manual do bloco
    Tipo de tarefa: classification
    Predições baseline: (array(['A', 'B'], dtype='<U1'), array([ 1, 81]))
    y_true: (array(['A', 'B'], dtype=object), array([70, 12]))
    Baseline score: 0.1585
    Rep 1: permuted_score=0.1585, importance=0.0000
    Rep 2: permuted_score=0.1585, importance=0.0000
    Rep 3: permuted_score=0.1585, importance=0.0000
    Importance: 0.000000 ± 0.000000
  Predicado: 400 <= 0.02 (n=76)
    Zona: 51 colunas
    Usando permutação manual do bloco
    Tipo de tarefa: classification
    Predições baseline: (array(['A', 'B'], dtype='<U1'), array([ 1, 75]))
    y_true: (array(['A', 'B'], dtype=object), array([67,  9]))
    Baseline score: 0.1316
    Rep 1: permuted_score=0.1316, importance=0.0000
    Rep 2: permuted_score=0.1316, importance=0.0000
    Rep 3: permuted_score=0.1316, importance=0.0000
    Importance: 0.000000 ± 0.000000
  Predicado: 400 > 0.02 (n=61)
    Zona: 51 colunas
    Usando permutação manual do bloco
    Tipo de tarefa: classification
    Predições baseline: (array(['B'], dtype='<U1'), array([61]))
    y_true: (array(['A', 'B'], dtype=object), array([51, 10]))
    Baseline score: 0.1639
    Rep 1: permuted_score=0.1639, importance=0.0000
    Rep 2: permuted_score=0.1639, importance=0.0000
    Rep 3: permuted_score=0.1639, importance=0.0000
    Importance: 0.000000 ± 0.000000
  Predicado: 400 <= 0.05 (n=114)
    Zona: 51 colunas
    Usando permutação manual do bloco
    Tipo de tarefa: classification
    Predições baseline: (array(['A', 'B'], dtype='<U1'), array([  1, 113]))
    y_true: (array(['A', 'B'], dtype=object), array([103,  11]))
    Baseline score: 0.1053
    Rep 1: permuted_score=0.1053, importance=0.0000
    Rep 2: permuted_score=0.1053, importance=0.0000
    Rep 3: permuted_score=0.1053, importance=0.0000
    Importance: 0.000000 ± 0.000000
  Predicado: 500 > -0.05 (n=109)
    Zona: 51 colunas
    Usando permutação manual do bloco
    Tipo de tarefa: classification
    Predições baseline: (array(['A', 'B'], dtype='<U1'), array([  1, 108]))
    y_true: (array(['A', 'B'], dtype=object), array([94, 15]))
    Baseline score: 0.1468
    Rep 1: permuted_score=0.1468, importance=0.0000
    Rep 2: permuted_score=0.1376, importance=0.0092
    Rep 3: permuted_score=0.1468, importance=0.0000
    Importance: 0.001835 ± 0.003670
  Predicado: 500 > -0.02 (n=86)
    Zona: 51 colunas
    Usando permutação manual do bloco
    Tipo de tarefa: classification
    Predições baseline: (array(['A', 'B'], dtype='<U1'), array([ 1, 85]))
    y_true: (array(['A', 'B'], dtype=object), array([74, 12]))
    Baseline score: 0.1512
    Rep 1: permuted_score=0.1512, importance=0.0000
    Rep 2: permuted_score=0.1512, importance=0.0000
    Rep 3: permuted_score=0.1512, importance=0.0000
    Importance: 0.000000 ± 0.000000
  Predicado: 500 <= 0.02 (n=74)
    Zona: 51 colunas
    Usando permutação manual do bloco
    Tipo de tarefa: classification
    Predições baseline: (array(['A', 'B'], dtype='<U1'), array([ 1, 73]))
    y_true: (array(['A', 'B'], dtype=object), array([65,  9]))
    Baseline score: 0.1351
    Rep 1: permuted_score=0.1216, importance=0.0135
    Rep 2: permuted_score=0.1216, importance=0.0135
    Rep 3: permuted_score=0.1081, importance=0.0270
    Importance: 0.016216 ± 0.005405
  Predicado: 500 > 0.02 (n=63)
    Zona: 51 colunas
    Usando permutação manual do bloco
    Tipo de tarefa: classification
    Predições baseline: (array(['B'], dtype='<U1'), array([63]))
    y_true: (array(['A', 'B'], dtype=object), array([53, 10]))
    Baseline score: 0.1587
    Rep 1: permuted_score=0.1587, importance=0.0000
    Rep 2: permuted_score=0.1587, importance=0.0000
    Rep 3: permuted_score=0.1587, importance=0.0000
    Importance: 0.000000 ± 0.000000
  Predicado: 500 <= 0.05 (n=115)
    Zona: 51 colunas
    Usando permutação manual do bloco
    Tipo de tarefa: classification
    Predições baseline: (array(['A', 'B'], dtype='<U1'), array([  1, 114]))
    y_true: (array(['A', 'B'], dtype=object), array([104,  11]))
    Baseline score: 0.1043
    Rep 1: permuted_score=0.0870, importance=0.0174
    Rep 2: permuted_score=0.1043, importance=0.0000
    Rep 3: permuted_score=0.0957, importance=0.0087
    Importance: 0.001739 ± 0.010141
  Predicado: 600 > -0.03 (n=112)
    Zona: 51 colunas
    Usando permutação manual do bloco
    Tipo de tarefa: classification
    Predições baseline: (array(['A', 'B'], dtype='<U1'), array([  1, 111]))
    y_true: (array(['A', 'B'], dtype=object), array([97, 15]))
    Baseline score: 0.1429
    Rep 1: permuted_score=0.1429, importance=0.0000
    Rep 2: permuted_score=0.1429, importance=0.0000
    Rep 3: permuted_score=0.1339, importance=0.0089
    Importance: 0.005357 ± 0.004374
  Predicado: 600 <= -0.01 (n=61)
    Zona: 51 colunas
    Usando permutação manual do bloco
    Tipo de tarefa: classification
    Predições baseline: (array(['B'], dtype='<U1'), array([61]))
    y_true: (array(['A', 'B'], dtype=object), array([53,  8]))
    Baseline score: 0.1311
    Rep 1: permuted_score=0.1311, importance=0.0000
    Rep 2: permuted_score=0.1148, importance=0.0164
    Rep 3: permuted_score=0.1311, importance=0.0000
    Importance: 0.003279 ± 0.006557
  Predicado: 600 > -0.01 (n=76)
    Zona: 51 colunas
    Usando permutação manual do bloco
    Tipo de tarefa: classification
    Predições baseline: (array(['A', 'B'], dtype='<U1'), array([ 1, 75]))
    y_true: (array(['A', 'B'], dtype=object), array([65, 11]))
    Baseline score: 0.1579
    Rep 1: permuted_score=0.1447, importance=0.0132
    Rep 2: permuted_score=0.1579, importance=0.0000
    Rep 3: permuted_score=0.1447, importance=0.0132
    Importance: 0.007895 ± 0.006446
  Predicado: 600 <= 0.01 (n=76)
    Zona: 51 colunas
    Usando permutação manual do bloco
    Tipo de tarefa: classification
    Predições baseline: (array(['A', 'B'], dtype='<U1'), array([ 1, 75]))
    y_true: (array(['A', 'B'], dtype=object), array([65, 11]))
    Baseline score: 0.1579
    Rep 1: permuted_score=0.1579, importance=0.0000
    Rep 2: permuted_score=0.1579, importance=0.0000
    Rep 3: permuted_score=0.1579, importance=0.0000
    Importance: 0.002632 ± 0.005263
  Predicado: 600 > 0.01 (n=61)
    Zona: 51 colunas
    Usando permutação manual do bloco
    Tipo de tarefa: classification
    Predições baseline: (array(['B'], dtype='<U1'), array([61]))
    y_true: (array(['A', 'B'], dtype=object), array([53,  8]))
    Baseline score: 0.1311
    Rep 1: permuted_score=0.1311, importance=0.0000
    Rep 2: permuted_score=0.1311, importance=0.0000
    Rep 3: permuted_score=0.1311, importance=0.0000
    Importance: 0.000000 ± 0.000000
  Predicado: 600 <= 0.02 (n=99)
    Zona: 51 colunas
    Usando permutação manual do bloco
    Tipo de tarefa: classification
    Predições baseline: (array(['A', 'B'], dtype='<U1'), array([ 1, 98]))
    y_true: (array(['A', 'B'], dtype=object), array([86, 13]))
    Baseline score: 0.1414
    Rep 1: permuted_score=0.1414, importance=0.0000
    Rep 2: permuted_score=0.1313, importance=0.0101
    Rep 3: permuted_score=0.1313, importance=0.0101
    Importance: 0.004040 ± 0.004948
  Predicado: 700 > -0.02 (n=96)
    Zona: 51 colunas
    Usando permutação manual do bloco
    Tipo de tarefa: classification
    Predições baseline: (array(['A', 'B'], dtype='<U1'), array([ 1, 95]))
    y_true: (array(['A', 'B'], dtype=object), array([83, 13]))
    Baseline score: 0.1458
    Rep 1: permuted_score=0.1458, importance=0.0000
    Rep 2: permuted_score=0.1354, importance=0.0104
    Rep 3: permuted_score=0.1458, importance=0.0000
    Importance: 0.002083 ± 0.007795
  Predicado: 700 <= -0.01 (n=57)
    Zona: 51 colunas
    Usando permutação manual do bloco
    Tipo de tarefa: classification
    Predições baseline: (array(['B'], dtype='<U1'), array([57]))
    y_true: (array(['A', 'B'], dtype=object), array([49,  8]))
    Baseline score: 0.1404
    Rep 1: permuted_score=0.1404, importance=0.0000
    Rep 2: permuted_score=0.1404, importance=0.0000
    Rep 3: permuted_score=0.1228, importance=0.0175
    Importance: 0.003509 ± 0.007018
  Predicado: 700 > -0.01 (n=80)
    Zona: 51 colunas
    Usando permutação manual do bloco
    Tipo de tarefa: classification
    Predições baseline: (array(['A', 'B'], dtype='<U1'), array([ 1, 79]))
    y_true: (array(['A', 'B'], dtype=object), array([69, 11]))
    Baseline score: 0.1500
    Rep 1: permuted_score=0.1250, importance=0.0250
    Rep 2: permuted_score=0.1250, importance=0.0250
    Rep 3: permuted_score=0.1375, importance=0.0125
    Importance: 0.015000 ± 0.009354
  Predicado: 700 <= 0.01 (n=79)
    Zona: 51 colunas
    Usando permutação manual do bloco
    Tipo de tarefa: classification
    Predições baseline: (array(['A', 'B'], dtype='<U1'), array([ 1, 78]))
    y_true: (array(['A', 'B'], dtype=object), array([67, 12]))
    Baseline score: 0.1646
    Rep 1: permuted_score=0.1772, importance=-0.0127
    Rep 2: permuted_score=0.1646, importance=0.0000
    Rep 3: permuted_score=0.1392, importance=0.0253
    Importance: 0.002532 ± 0.014762
  Predicado: 700 > 0.01 (n=58)
    Zona: 51 colunas
    Usando permutação manual do bloco
    Tipo de tarefa: classification
    Predições baseline: (array(['B'], dtype='<U1'), array([58]))
    y_true: (array(['A', 'B'], dtype=object), array([51,  7]))
    Baseline score: 0.1207
    Rep 1: permuted_score=0.1207, importance=0.0000
    Rep 2: permuted_score=0.1207, importance=0.0000
    Rep 3: permuted_score=0.1207, importance=0.0000
    Importance: 0.000000 ± 0.000000
  Predicado: 700 <= 0.03 (n=120)
    Zona: 51 colunas
    Usando permutação manual do bloco
    Tipo de tarefa: classification
    Predições baseline: (array(['A', 'B'], dtype='<U1'), array([  1, 119]))
    y_true: (array(['A', 'B'], dtype=object), array([103,  17]))
    Baseline score: 0.1500
    Rep 1: permuted_score=0.1500, importance=0.0000
    Rep 2: permuted_score=0.1250, importance=0.0250
    Rep 3: permuted_score=0.1667, importance=-0.0167
    Importance: 0.000000 ± 0.013944
  Predicado: 800 > -0.02 (n=95)
    Zona: 51 colunas
    Usando permutação manual do bloco
    Tipo de tarefa: classification
    Predições baseline: (array(['A', 'B'], dtype='<U1'), array([ 1, 94]))
    y_true: (array(['A', 'B'], dtype=object), array([81, 14]))
    Baseline score: 0.1579
    Rep 1: permuted_score=0.1579, importance=0.0000
    Rep 2: permuted_score=0.1368, importance=0.0211
    Rep 3: permuted_score=0.1474, importance=0.0105
    Importance: 0.008421 ± 0.007877
  Predicado: 800 <= -0.01 (n=60)
    Zona: 51 colunas
    Usando permutação manual do bloco
    Tipo de tarefa: classification
    Predições baseline: (array(['B'], dtype='<U1'), array([60]))
    y_true: (array(['A', 'B'], dtype=object), array([53,  7]))
    Baseline score: 0.1167
    Rep 1: permuted_score=0.1167, importance=0.0000
    Rep 2: permuted_score=0.1167, importance=0.0000
    Rep 3: permuted_score=0.1167, importance=0.0000
    Importance: 0.000000 ± 0.000000
  Predicado: 800 > -0.01 (n=77)
    Zona: 51 colunas
    Usando permutação manual do bloco
    Tipo de tarefa: classification
    Predições baseline: (array(['A', 'B'], dtype='<U1'), array([ 1, 76]))
    y_true: (array(['A', 'B'], dtype=object), array([65, 12]))
    Baseline score: 0.1688
    Rep 1: permuted_score=0.1688, importance=0.0000
    Rep 2: permuted_score=0.1688, importance=0.0000
    Rep 3: permuted_score=0.1688, importance=0.0000
    Importance: 0.002597 ± 0.005195
  Predicado: 800 <= 0.01 (n=79)
    Zona: 51 colunas
    Usando permutação manual do bloco
    Tipo de tarefa: classification
    Predições baseline: (array(['B'], dtype='<U1'), array([79]))
    y_true: (array(['A', 'B'], dtype=object), array([69, 10]))
    Baseline score: 0.1266
    Rep 1: permuted_score=0.1266, importance=0.0000
    Rep 2: permuted_score=0.1392, importance=-0.0127
    Rep 3: permuted_score=0.1266, importance=0.0000
    Importance: -0.002532 ± 0.005063
  Predicado: 800 > 0.01 (n=58)
    Zona: 51 colunas
    Usando permutação manual do bloco
    Tipo de tarefa: classification
    Predições baseline: (array(['A', 'B'], dtype='<U1'), array([ 1, 57]))
    y_true: (array(['A', 'B'], dtype=object), array([49,  9]))
    Baseline score: 0.1724
    Rep 1: permuted_score=0.1724, importance=0.0000
    Rep 2: permuted_score=0.1724, importance=0.0000
    Rep 3: permuted_score=0.1724, importance=0.0000
    Importance: 0.000000 ± 0.000000
  Predicado: 800 <= 0.03 (n=121)
    Zona: 51 colunas
    Usando permutação manual do bloco
    Tipo de tarefa: classification
    Predições baseline: (array(['A', 'B'], dtype='<U1'), array([  1, 120]))
    y_true: (array(['A', 'B'], dtype=object), array([106,  15]))
    Baseline score: 0.1322
    Rep 1: permuted_score=0.1322, importance=0.0000
    Rep 2: permuted_score=0.1322, importance=0.0000
    Rep 3: permuted_score=0.1322, importance=0.0000
    Importance: 0.000000 ± 0.000000
  Predicado: 900 > -0.03 (n=107)
    Zona: 51 colunas
    Usando permutação manual do bloco
    Tipo de tarefa: classification
    Predições baseline: (array(['A', 'B'], dtype='<U1'), array([  1, 106]))
    y_true: (array(['A', 'B'], dtype=object), array([91, 16]))
    Baseline score: 0.1589
    Rep 1: permuted_score=0.1495, importance=0.0093
    Rep 2: permuted_score=0.1589, importance=0.0000
    Rep 3: permuted_score=0.1589, importance=0.0000
    Importance: 0.003738 ± 0.004578
  Predicado: 900 <= -0.01 (n=60)
    Zona: 51 colunas
    Usando permutação manual do bloco
    Tipo de tarefa: classification
    Predições baseline: (array(['B'], dtype='<U1'), array([60]))
    y_true: (array(['A', 'B'], dtype=object), array([55,  5]))
    Baseline score: 0.0833
    Rep 1: permuted_score=0.0833, importance=0.0000
    Rep 2: permuted_score=0.0833, importance=0.0000
    Rep 3: permuted_score=0.0833, importance=0.0000
    Importance: 0.000000 ± 0.000000
  Predicado: 900 > -0.01 (n=77)
    Zona: 51 colunas
    Usando permutação manual do bloco
    Tipo de tarefa: classification
    Predições baseline: (array(['A', 'B'], dtype='<U1'), array([ 1, 76]))
    y_true: (array(['A', 'B'], dtype=object), array([63, 14]))
    Baseline score: 0.1948
    Rep 1: permuted_score=0.1948, importance=0.0000
    Rep 2: permuted_score=0.1948, importance=0.0000
    Rep 3: permuted_score=0.1948, importance=0.0000
    Importance: 0.002597 ± 0.005195
  Predicado: 900 <= 0.01 (n=88)
    Zona: 51 colunas
    Usando permutação manual do bloco
    Tipo de tarefa: classification
    Predições baseline: (array(['B'], dtype='<U1'), array([88]))
    y_true: (array(['A', 'B'], dtype=object), array([78, 10]))
    Baseline score: 0.1136
    Rep 1: permuted_score=0.1136, importance=0.0000
    Rep 2: permuted_score=0.1136, importance=0.0000
    Rep 3: permuted_score=0.1136, importance=0.0000
    Importance: 0.000000 ± 0.000000
  Predicado: 900 <= 0.03 (n=118)
    Zona: 51 colunas
    Usando permutação manual do bloco
    Tipo de tarefa: classification
    Predições baseline: (array(['A', 'B'], dtype='<U1'), array([  1, 117]))
    y_true: (array(['A', 'B'], dtype=object), array([104,  14]))
    Baseline score: 0.1271
    Rep 1: permuted_score=0.1186, importance=0.0085
    Rep 2: permuted_score=0.1186, importance=0.0085
    Rep 3: permuted_score=0.1271, importance=0.0000
    Importance: 0.003390 ± 0.004152
  Predicado: 1000 > -0.03 (n=100)
    Zona: 51 colunas
    Usando permutação manual do bloco
    Tipo de tarefa: classification
    Predições baseline: (array(['A', 'B'], dtype='<U1'), array([ 1, 99]))
    y_true: (array(['A', 'B'], dtype=object), array([84, 16]))
    Baseline score: 0.1700
    Rep 1: permuted_score=0.1600, importance=0.0100
    Rep 2: permuted_score=0.1700, importance=0.0000
    Rep 3: permuted_score=0.1600, importance=0.0100
    Importance: 0.004000 ± 0.004899
  Predicado: 1000 <= -0.01 (n=57)
    Zona: 51 colunas
    Usando permutação manual do bloco
    Tipo de tarefa: classification
    Predições baseline: (array(['B'], dtype='<U1'), array([57]))
    y_true: (array(['A', 'B'], dtype=object), array([52,  5]))
    Baseline score: 0.0877
    Rep 1: permuted_score=0.0877, importance=0.0000
    Rep 2: permuted_score=0.0702, importance=0.0175
    Rep 3: permuted_score=0.0877, importance=0.0000
    Importance: 0.003509 ± 0.007018
  Predicado: 1000 > -0.01 (n=80)
    Zona: 51 colunas
    Usando permutação manual do bloco
    Tipo de tarefa: classification
    Predições baseline: (array(['A', 'B'], dtype='<U1'), array([ 1, 79]))
    y_true: (array(['A', 'B'], dtype=object), array([66, 14]))
    Baseline score: 0.1875
    Rep 1: permuted_score=0.1875, importance=0.0000
    Rep 2: permuted_score=0.1875, importance=0.0000
    Rep 3: permuted_score=0.1875, importance=0.0000
    Importance: 0.000000 ± 0.000000
  Predicado: 1000 <= 0.01 (n=91)
    Zona: 51 colunas

/home/jvribeiro/.local/lib/python3.10/site-packages/networkx/algorithms/centrality/reaching.py:193: RuntimeWarning:

divide by zero encountered in scalar divide

   Predicate_perm_Seed_0
0           1000 > -0.03
1           1300 <= 0.04
2           1600 > -0.04
3           1700 > -0.04
4           1700 <= 0.04
..                   ...
75           1400 > 0.01
76         1000 <= -0.01
77          800 <= -0.01
78               Class_A
79               Class_B

[80 rows x 1 columns]

In [11]:
all_results_perm[0]['perm_results_dict']['Bag_10']

         Predicate  Permutation
0      700 <= 0.03     0.093772
1      700 <= 0.01     0.076931
2     1500 > -0.04     0.065917
3     1500 <= 0.04     0.065281
4      700 > -0.02     0.064055
..             ...          ...
96    1100 <= 0.03     0.001475
97   1100 <= -0.01     0.001230
98    1100 <= 0.01     0.001228
99    1100 > -0.03     0.001146
100   1100 > -0.01     0.001019

[101 rows x 2 columns]

# **Perturbation**

In [37]:
from permutation import calculate_predicate_metrics_permutation
import explaining as exp
spectral_zones_class = exp.extract_spectral_zones(Xcalclass_prep, spectral_cuts)
zone_sums_df = exp.aggregate_spectral_zones(spectral_zones_class, aggregator='sum')
predicates_quantiles = exp.predicates_by_quantiles(zone_sums_df, [0.2, 0.4, 0.6, 0.8])
co_occurrence_matrix_df = predicates_quantiles[2]
predicate_info_dict = exp.create_predicate_info_dict(
    predicates_df=predicates_quantiles[0],
    predicate_indicator_df=predicates_quantiles[1],
    zone_aggregated_df=zone_sums_df,
    y_predicted_numeric=y_pred_cont
)

# LISTA DE SEMENTES A TESTAR
random_seeds = [0]

all_results_pert = {}
training_samples = len(Xcalclass)

# LOOP: PROCESSAR CADA SEMENTE
y_predicted_numeric = plsda_results[5].iloc[:, -1] # predições numéricas do modelo

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando semente: {seed}")
    print(f"{'='*70}\n")
    # Bagging
    bags_result_seed = exp.bagging_predicates(
        zone_sums_df=zone_sums_df,
        y_predicted_numeric=y_predicted_numeric,
        predicates_df=predicates_quantiles[0],
        n_bags=10,
        #n_predicates_per_bag=40,
        n_samples_per_bag=int(training_samples*0.8), # 80 % da base para amostrar (convertido para int)
        min_samples_per_predicate=int(training_samples*0.2), # 20 % da base para limitar (convertido para int)
        replace=False,
        sample_bagging=True,
        predicate_bagging=False,
        random_seed=seed
    )
    # Inserir classe prevista
    for bag_name, pred_dict in bags_result_seed.items(): # iterando sobre cada bag
        for pred_rule, df_info in pred_dict.items():
            df_info['Class_Predicted'] = np.where(df_info['Predicted_Y'] >= 0.5, 'A', 'B') # binarizando com threshold 0.5, A = eut, B = dist

    pert_results_seed = perm.calculate_predicate_perturbation(
        estimator=pls_model,
        Xcalclass_prep=Xcalclass_prep,
        folds_struct=bags_result_seed,
        predicates_df=predicates_quantiles[0],
        spectral_cuts=spectral_cuts,
        perturbation_value=np.mean(y_predicted_numeric)*1000,
        metric='mean_relative_dev',   # Média com sinal (pode ser negativo)
        verbose=True
    )

    # Remove todos os valores iguais a zero de todos os bags em perm_results[bag]["Permutation"] e salva como perm_results_thresholded
    # pert_results_seed_thresholded = {}
    # for bag, df in perm_results_seed.items():
    #     # Verifica se é um DataFrame e se a coluna 'Permutation' existe
    #     if isinstance(df, pd.DataFrame) and 'Permutation' in df.columns:
    #         filtered_df = df[df['Permutation'] > 0].copy()
    #         pert_results_seed_thresholded[bag] = filtered_df
    #     else:
    #         # Se não for DataFrame esperado, apenas copia
    #         pert_results_seed_thresholded[bag] = df

    # Salvar no dicionário principal
    all_results_pert[seed] = {
        'bags_result': bags_result_seed,
        'pert_results_dict': pert_results_seed
    }

# CONSTRUÇÃO DE GRAFOS PARA MÚLTIPLAS SEMENTES (LOOP EXTERNO)
# Dicionário para armazenar grafos
graphs_pert_by_seed = {}

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando Grafo - Semente: {seed}")
    print(f"{'='*70}\n")
    # Construir grafo para esta semente
    DG = exp.build_predicate_graph(
        bags_result=all_results_pert[seed]['bags_result'],
        mi_results_dict=all_results_pert[seed]['pert_results_dict'],
        co_occurrence_matrix_df=co_occurrence_matrix_df,
        predicates_df=predicates_quantiles[0],
        random_state=seed,
        show_details=True
    )
    # Armazenar grafo
    graphs_pert_by_seed[seed] = DG  

# Calcular LRC usando a função pronta do explaining.py
lrc_pert_by_seed = {}
for seed in random_seeds:
    DG = graphs_pert_by_seed[seed]
    lrc_pert_df_seed = exp.calculate_lrc_single_graph(DG, predicates_quantiles[0])
    lrc_pert_df_seed['Seed'] = seed  # Adicionar coluna com a semente
    lrc_pert_by_seed[seed] = lrc_pert_df_seed

# junando todas as colunas 'Node' de lrc_by_seed em um único dataframe
lrc_pert_all_seeds_df = pd.DataFrame()
for seed in random_seeds:
    lrc_pert_df_seed = lrc_pert_by_seed[seed].rename(columns={'Node': f'Predicate_pert_Seed_{seed}'})
    lrc_pert_all_seeds_df = pd.concat([lrc_pert_all_seeds_df, lrc_pert_df_seed[[f'Predicate_pert_Seed_{seed}']]], axis=1)

# vamos filtrar lrc_by_seed em cada semente para manter apenas as zonas espectrais únicas com maior LRC em um mesmo dataframe
lrc_pert_unique_by_seed = {}
for seed, lrc_df in lrc_pert_by_seed.items():
    lrc_pert_unique_df = lrc_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
    lrc_pert_unique_df = lrc_pert_unique_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
    lrc_pert_unique_by_seed[seed] = lrc_pert_unique_df

lrc_pert_all_seeds_df # exibindo o dataframe consolidado com predicados de todas as sementes

======================================================================
Processando semente: 0
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 630 | Descartados: 210
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 630 | Descartados: 210
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 630 | Descartados: 210
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 630 | Descartados: 210
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 630 | Descartados: 210
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 630 | Descartados: 210
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 630 | Descartados: 210
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 630 | Descartados: 210
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 630 | Descartados: 210
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 630 | Descartados: 210
======================================================================
PERTURBATION IMPORTANCE PARA PREDICADOS
======================================================================
Valor de perturbação: 145.4545454545454
Métrica: mean_relative_dev
Total de folds: 10


[Bag_1] Processando 630 predicados...
  Predicado: 400 > -0.10 (n=174)
    Zona: 11 colunas
    Importance: 320.740355
  Predicado: 400 <= -0.03 (n=92)
    Zona: 11 colunas
    Importance: 313.339257
  Predicado: 400 > -0.03 (n=128)
    Zona: 11 colunas
    Importance: 302.732161
  Predicado: 400 <= 0.03 (n=135)
    Zona: 11 colunas
    Importance: 215.525786
  Predicado: 400 > 0.03 (n=85)
    Zona: 11 colunas
    Importance: 452.717026
  Predicado: 400 <= 0.09 (n=176)
    Zona: 11 colunas
    Importance: 351.064595
  Predicado: 420 > -0.13 (n=178)
    Zona: 11 colunas
    Importance: 252.871826
  Predicado: 420 <= -0.05 (n=94)
    Zona: 11 colunas
    Importance: 162.878741
  Predicado: 420 > -0.05 (n=126)
    Zona: 11 colunas
    Importance: 315.099157
  Predicado: 420 <= 0.03 (n=127)
    Zona: 11 colunas
    Importance: 195.121707
  Predicado: 420 > 0.03 (n=93)
    Zona: 11 colunas
    Importance: 325.082136
  Predicado: 420 <= 0.11 (n=174)
    Zona: 11 colunas
    Importance: 278.884819
  Predicado: 440 > -0.14 (n=175)
    Zona: 11 colunas
    Importance: 7.349408
  Predicado: 440 <= -0.07 (n=89)
    Zona: 11 colunas
    Importance: 4.784612
  Predicado: 440 > -0.07 (n=131)
    Zona: 11 colunas
    Importance: 8.448890
  Predicado: 440 <= 0.04 (n=133)
    Zona: 11 colunas
    Importance: 5.403244
  Predicado: 440 > 0.04 (n=87)
    Zona: 11 colunas
    Importance: 9.356364
  Predicado: 440 <= 0.11 (n=173)
    Zona: 11 colunas
    Importance: 7.838813
  Predicado: 460 > -0.15 (n=174)
    Zona: 11 colunas
    Importance: -278.806591
  Predicado: 460 <= -0.07 (n=90)
    Zona: 11 colunas
    Importance: -178.350151
  Predicado: 460 > -0.07 (n=130)
    Zona: 11 colunas
    Importance: -321.406328
  Predicado: 460 <= 0.03 (n=129)
    Zona: 11 colunas
    Importance: -208.026221
  Predicado: 460 > 0.03 (n=91)
    Zona: 11 colunas
    Importance: -340.647844
  Predicado: 460 <= 0.12 (n=176)
    Zona: 11 colunas
    Importance: -291.375504
  Predicado: 480 > -0.15 (n=174)
    Zona: 11 colunas
    Importance: -612.496849
  Predicado: 480 <= -0.07 (n=91)
    Zona: 11 colunas
    Importance: -391.828763
  Predicado: 480 > -0.07 (n=129)
    Zona: 11 colunas
    Importance: -708.992321
  Predicado: 480 <= 0.03 (n=130)
    Zona: 11 colunas
    Importance: -609.494663
  Predicado: 480 > 0.03 (n=90)
    Zona: 11 colunas
    Importance: -532.023563
  Predicado: 480 <= 0.12 (n=175)
    Zona: 11 colunas
    Importance: -643.420532
  Predicado: 500 > -0.15 (n=180)
    Zona: 11 colunas
    Importance: -1027.999932
  Predicado: 500 <= -0.07 (n=89)
    Zona: 11 colunas
    Importance: -662.522220
  Predicado: 500 > -0.07 (n=131)
    Zona: 11 colunas
    Importance: -1206.492800
  Predicado: 500 <= 0.03 (n=129)
    Zona: 11 colunas
    Importance: -1033.045690
  Predicado: 500 > 0.03 (n=91)
    Zona: 11 colunas
    Importance: -920.353191
  Predicado: 500 <= 0.12 (n=176)
    Zona: 11 colunas
    Importance: -1094.521722
  Predicado: 520 > -0.13 (n=173)
    Zona: 11 colunas
    Importance: -1949.500434
  Predicado: 520 <= -0.06 (n=90)
    Zona: 11 colunas
    Importance: -967.247273
  Predicado: 520 > -0.06 (n=130)
    Zona: 11 colunas
    Importance: -1759.301808
  Predicado: 520 <= 0.03 (n=132)
    Zona: 11 colunas
    Importance: -1471.040549
  Predicado: 520 > 0.03 (n=88)
    Zona: 11 colunas
    Importance: -1381.637921
  Predicado: 520 <= 0.12 (n=174)
    Zona: 11 colunas
    Importance: -1576.485645
  Predicado: 540 > -0.12 (n=175)
    Zona: 11 colunas
    Importance: -2061.439654
  Predicado: 540 <= -0.05 (n=90)
    Zona: 11 colunas
    Importance: -1183.471352
  Predicado: 540 > -0.05 (n=130)
    Zona: 11 colunas
    Importance: -2150.824242
  Predicado: 540 <= 0.02 (n=130)
    Zona: 11 colunas
    Importance: -1822.989729
  Predicado: 540 > 0.02 (n=90)
    Zona: 11 colunas
    Importance: -1657.010093
  Predicado: 540 <= 0.10 (n=172)
    Zona: 11 colunas
    Importance: -1760.137751
  Predicado: 560 > -0.10 (n=178)
    Zona: 11 colunas
    Importance: -1910.883968
  Predicado: 560 <= -0.03 (n=91)
    Zona: 11 colunas
    Importance: -1112.702102
  Predicado: 560 > -0.03 (n=129)
    Zona: 11 colunas
    Importance: -2100.364379
  Predicado: 560 <= 0.02 (n=132)
    Zona: 11 colunas
    Importance: -1906.912168
  Predicado: 560 > 0.02 (n=88)
    Zona: 11 colunas
    Importance: -1369.210114
  Predicado: 560 <= 0.08 (n=173)
    Zona: 11 colunas
    Importance: -1743.903585
  Predicado: 580 > -0.09 (n=179)
    Zona: 11 colunas
    Importance: -1201.388497
  Predicado: 580 <= -0.03 (n=85)
    Zona: 11 colunas
    Importance: -924.087138
  Predicado: 580 > -0.03 (n=135)
    Zona: 11 colunas
    Importance: -1171.607270
  Predicado: 580 <= 0.01 (n=124)
    Zona: 11 colunas
    Importance: -690.087833
  Predicado: 580 > 0.01 (n=96)
    Zona: 11 colunas
    Importance: -1574.411426
  Predicado: 580 <= 0.07 (n=175)
    Zona: 11 colunas
    Importance: -1151.116360
  Predicado: 600 > -0.09 (n=181)
    Zona: 11 colunas
    Importance: -199.806442
  Predicado: 600 <= -0.03 (n=87)
    Zona: 11 colunas
    Importance: -141.972928
  Predicado: 600 > -0.03 (n=133)
    Zona: 11 colunas
    Importance: -236.699320
  Predicado: 600 <= 0.01 (n=124)
    Zona: 11 colunas
    Importance: -145.963573
  Predicado: 600 > 0.01 (n=96)
    Zona: 11 colunas
    Importance: -268.053867
  Predicado: 600 <= 0.07 (n=170)
    Zona: 11 colunas
    Importance: -197.658565
  Predicado: 620 > -0.09 (n=181)
    Zona: 11 colunas
    Importance: 561.150283
  Predicado: 620 <= -0.04 (n=81)
    Zona: 11 colunas
    Importance: 383.923910
  Predicado: 620 > -0.04 (n=139)
    Zona: 11 colunas
    Importance: 670.193284
  Predicado: 620 <= 0.02 (n=128)
    Zona: 11 colunas
    Importance: 453.324186
  Predicado: 620 > 0.02 (n=92)
    Zona: 11 colunas
    Importance: 719.882688
  Predicado: 620 <= 0.08 (n=169)
    Zona: 11 colunas
    Importance: 565.496847
  Predicado: 640 > -0.09 (n=177)
    Zona: 11 colunas
    Importance: 1152.890361
  Predicado: 640 <= -0.04 (n=87)
    Zona: 11 colunas
    Importance: 797.715768
  Predicado: 640 > -0.04 (n=133)
    Zona: 11 colunas
    Importance: 1367.857174
  Predicado: 640 <= 0.02 (n=129)
    Zona: 11 colunas
    Importance: 876.096111
  Predicado: 640 > 0.02 (n=91)
    Zona: 11 colunas
    Importance: 1519.888766
  Predicado: 640 <= 0.09 (n=168)
    Zona: 11 colunas
    Importance: 1384.353818
  Predicado: 660 > -0.10 (n=181)
    Zona: 11 colunas
    Importance: 1605.657993
  Predicado: 660 <= -0.04 (n=89)
    Zona: 11 colunas
    Importance: 1083.157584
  Predicado: 660 > -0.04 (n=131)
    Zona: 11 colunas
    Importance: 2003.836935
  Predicado: 660 <= 0.02 (n=128)
    Zona: 11 colunas
    Importance: 1307.162879
  Predicado: 660 > 0.02 (n=92)
    Zona: 11 colunas
    Importance: 2082.465380
  Predicado: 660 <= 0.09 (n=172)
    Zona: 11 colunas
    Importance: 1965.371546
  Predicado: 680 > -0.10 (n=175)
    Zona: 11 colunas
    Importance: 2113.062736
  Predicado: 680 <= -0.05 (n=85)
    Zona: 11 colunas
    Importance: 1422.217131
  Predicado: 680 > -0.05 (n=135)
    Zona: 11 colunas
    Importance: 2464.293331
  Predicado: 680 <= 0.02 (n=124)
    Zona: 11 colunas
    Importance: 1726.247094
  Predicado: 680 > 0.02 (n=96)
    Zona: 11 colunas
    Importance: 2494.931418
  Predicado: 680 <= 0.10 (n=175)
    Zona: 11 colunas
    Importance: 2604.189446
  Predicado: 700 > -0.11 (n=180)
    Zona: 11 colunas
    Importance: 2316.940998
  Predicado: 700 <= -0.05 (n=86)
    Zona: 11 colunas
    Importance: 1646.693720
  Predicado: 700 > -0.05 (n=134)
    Zona: 11 colunas
    Importance: 2840.959416
  Predicado: 700 <= 0.03 (n=125)
    Zona: 11 colunas
    Importance: 1990.015480
  Predicado: 700 > 0.03 (n=95)
    Zona: 11 colunas
    Importance: 2879.497753
  Predicado: 700 <= 0.10 (n=171)
    Zona: 11 colunas
    Importance: 2345.203924
  Predicado: 720 > -0.11 (n=177)
    Zona: 11 colunas
    Importance: 2413.982724
  Predicado: 720 <= -0.05 (n=90)
    Zona: 11 colunas
    Importance: 1522.047410
  Predicado: 720 > -0.05 (n=130)
    Zona: 11 colunas
    Importance: 3200.857599
  Predicado: 720 <= 0.03 (n=125)
    Zona: 11 colunas
    Importance: 2095.016214
  Predicado: 720 > 0.03 (n=95)
    Zona: 11 colunas
    Importance: 3065.460295
  Predicado: 720 <= 0.10 (n=168)
    Zona: 11 colunas
    Importance: 2586.965647
  Predicado: 740 > -0.12 (n=180)
    Zona: 11 colunas
    Importance: 2293.307266
  Predicado: 740 <= -0.05 (n=90)
    Zona: 11 colunas
    Importance: 1482.390777
  Predicado: 740 > -0.05 (n=130)
    Zona: 11 colunas
    Importance: 3117.448711
  Predicado: 740 <= 0.03 (n=124)
    Zona: 11 colunas
    Importance: 2103.109372
  Predicado: 740 > 0.03 (n=96)
    Zona: 11 colunas
    Importance: 2894.770210
  Predicado: 740 <= 0.11 (n=175)
    Zona: 11 colunas
    Importance: 2446.446473
  Predicado: 760 > -0.12 (n=178)
    Zona: 11 colunas
    Importance: 2067.730363
  Predicado: 760 <= -0.05 (n=89)
    Zona: 11 colunas
    Importance: 1333.947288
  Predicado: 760 > -0.05 (n=131)
    Zona: 11 colunas
    Importance: 2810.758833
  Predicado: 760 <= 0.03 (n=124)
    Zona: 11 colunas
    Importance: 1878.144179
  Predicado: 760 > 0.03 (n=96)
    Zona: 11 colunas
    Importance: 2646.258725
  Predicado: 760 <= 0.11 (n=176)
    Zona: 11 colunas
    Importance: 2203.129078
  Predicado: 780 > -0.12 (n=179)
    Zona: 11 colunas
    Importance: 2001.441238
  Predicado: 780 <= -0.05 (n=88)
    Zona: 11 colunas
    Importance: 1197.277063
  Predicado: 780 > -0.05 (n=132)
    Zona: 11 colunas
    Importance: 2341.940188
  Predicado: 780 <= 0.03 (n=126)
    Zona: 11 colunas
    Importance: 1607.567117
  Predicado: 780 > 0.03 (n=94)
    Zona: 11 colunas
    Importance: 2254.713080
  Predicado: 780 <= 0.10 (n=169)
    Zona: 11 colunas
    Importance: 1752.392758
  Predicado: 800 > -0.12 (n=183)
    Zona: 11 colunas
    Importance: 1617.892283
  Predicado: 800 <= -0.05 (n=86)
    Zona: 11 colunas
    Importance: 1024.109042
  Predicado: 800 > -0.05 (n=134)
    Zona: 11 colunas
    Importance: 1849.418789
  Predicado: 800 <= 0.03 (n=122)
    Zona: 11 colunas
    Importance: 1055.391147
  Predicado: 800 > 0.03 (n=98)
    Zona: 11 colunas
    Importance: 2113.650769
  Predicado: 800 <= 0.10 (n=169)
    Zona: 11 colunas
    Importance: 1522.507409
  Predicado: 820 > -0.11 (n=180)
    Zona: 11 colunas
    Importance: 1281.914618
  Predicado: 820 <= -0.05 (n=81)
    Zona: 11 colunas
    Importance: 1003.691346
  Predicado: 820 > -0.05 (n=139)
    Zona: 11 colunas
    Importance: 1322.633674
  Predicado: 820 <= 0.03 (n=124)
    Zona: 11 colunas
    Importance: 845.098329
  Predicado: 820 > 0.03 (n=96)
    Zona: 11 colunas
    Importance: 1670.342572
  Predicado: 820 <= 0.10 (n=172)
    Zona: 11 colunas
    Importance: 1168.390612
  Predicado: 840 > -0.11 (n=182)
    Zona: 11 colunas
    Importance: 988.919282
  Predicado: 840 <= -0.04 (n=89)
    Zona: 11 colunas
    Importance: 645.325697
  Predicado: 840 > -0.04 (n=131)
    Zona: 11 colunas
    Importance: 1171.872507
  Predicado: 840 <= 0.03 (n=125)
    Zona: 11 colunas
    Importance: 672.600131
  Predicado: 840 > 0.03 (n=95)
    Zona: 11 colunas
    Importance: 1335.518623
  Predicado: 840 <= 0.10 (n=172)
    Zona: 11 colunas
    Importance: 936.295345
  Predicado: 860 > -0.10 (n=177)
    Zona: 11 colunas
    Importance: 847.470089
  Predicado: 860 <= -0.04 (n=88)
    Zona: 11 colunas
    Importance: 566.284665
  Predicado: 860 > -0.04 (n=132)
    Zona: 11 colunas
    Importance: 974.358821
  Predicado: 860 <= 0.03 (n=126)
    Zona: 11 colunas
    Importance: 563.061449
  Predicado: 860 > 0.03 (n=94)
    Zona: 11 colunas
    Importance: 1143.645450
  Predicado: 860 <= 0.10 (n=175)
    Zona: 11 colunas
    Importance: 859.804919
  Predicado: 880 > -0.11 (n=182)
    Zona: 11 colunas
    Importance: 798.388480
  Predicado: 880 <= -0.04 (n=87)
    Zona: 11 colunas
    Importance: 605.722848
  Predicado: 880 > -0.04 (n=133)
    Zona: 11 colunas
    Importance: 853.838966
  Predicado: 880 <= 0.03 (n=125)
    Zona: 11 colunas
    Importance: 474.986701
  Predicado: 880 > 0.03 (n=95)
    Zona: 11 colunas
    Importance: 1125.106659
  Predicado: 880 <= 0.10 (n=173)
    Zona: 11 colunas
    Importance: 689.217947
  Predicado: 900 > -0.11 (n=178)
    Zona: 11 colunas
    Importance: 815.537267
  Predicado: 900 <= -0.04 (n=87)
    Zona: 11 colunas
    Importance: 625.022021
  Predicado: 900 > -0.04 (n=133)
    Zona: 11 colunas
    Importance: 881.041023
  Predicado: 900 <= 0.03 (n=125)
    Zona: 11 colunas
    Importance: 490.120547
  Predicado: 900 > 0.03 (n=95)
    Zona: 11 colunas
    Importance: 1160.950563
  Predicado: 900 <= 0.11 (n=175)
    Zona: 11 colunas
    Importance: 755.718291
  Predicado: 920 > -0.11 (n=178)
    Zona: 11 colunas
    Importance: 908.853654
  Predicado: 920 <= -0.04 (n=84)
    Zona: 11 colunas
    Importance: 724.253271
  Predicado: 920 > -0.04 (n=136)
    Zona: 11 colunas
    Importance: 952.666197
  Predicado: 920 <= 0.03 (n=124)
    Zona: 11 colunas
    Importance: 530.907739
  Predicado: 920 > 0.03 (n=96)
    Zona: 11 colunas
    Importance: 1297.576228
  Predicado: 920 <= 0.12 (n=177)
    Zona: 11 colunas
    Importance: 854.116915
  Predicado: 940 > -0.12 (n=180)
    Zona: 11 colunas
    Importance: 1008.444382
  Predicado: 940 <= -0.04 (n=84)
    Zona: 11 colunas
    Importance: 834.199395
  Predicado: 940 > -0.04 (n=136)
    Zona: 11 colunas
    Importance: 1085.222146
  Predicado: 940 <= 0.03 (n=125)
    Zona: 11 colunas
    Importance: 754.713373
  Predicado: 940 > 0.03 (n=95)
    Zona: 11 colunas
    Importance: 1298.145151
  Predicado: 940 <= 0.12 (n=174)
    Zona: 11 colunas
    Importance: 840.151424
  Predicado: 960 > -0.12 (n=177)
    Zona: 11 colunas
    Importance: 1186.030245
  Predicado: 960 <= -0.04 (n=84)
    Zona: 11 colunas
    Importance: 981.182286
  Predicado: 960 > -0.04 (n=136)
    Zona: 11 colunas
    Importance: 1214.068761
  Predicado: 960 <= 0.03 (n=125)
    Zona: 11 colunas
    Importance: 872.625210
  Predicado: 960 > 0.03 (n=95)
    Zona: 11 colunas
    Importance: 1457.415919
  Predicado: 960 <= 0.13 (n=174)
    Zona: 11 colunas
    Importance: 955.447047
  Predicado: 980 > -0.13 (n=180)
    Zona: 11 colunas
    Importance: 1294.611268
  Predicado: 980 <= -0.04 (n=83)
    Zona: 11 colunas
    Importance: 1085.720937
  Predicado: 980 > -0.04 (n=137)
    Zona: 11 colunas
    Importance: 1326.203264
  Predicado: 980 <= 0.03 (n=126)
    Zona: 11 colunas
    Importance: 950.296561
  Predicado: 980 > 0.03 (n=94)
    Zona: 11 colunas
    Importance: 1617.737428
  Predicado: 980 <= 0.14 (n=175)
    Zona: 11 colunas
    Importance: 1047.884343
  Predicado: 1000 > -0.14 (n=181)
    Zona: 11 colunas
    Importance: 1364.042591
  Predicado: 1000 <= -0.04 (n=86)
    Zona: 11 colunas
    Importance: 1124.615395
  Predicado: 1000 > -0.04 (n=134)
    Zona: 11 colunas
    Importance: 1383.952196
  Predicado: 1000 <= 0.04 (n=130)
    Zona: 11 colunas
    Importance: 1103.554036
  Predicado: 1000 > 0.04 (n=90)
    Zona: 11 colunas
    Importance: 1541.161039
  Predicado: 1000 <= 0.14 (n=173)
    Zona: 11 colunas
    Importance: 1087.502362
  Predicado: 1020 > -0.14 (n=180)
    Zona: 11 colunas
    Importance: 1340.620923
  Predicado: 1020 <= -0.04 (n=83)
    Zona: 11 colunas
    Importance: 1110.078948
  Predicado: 1020 > -0.04 (n=137)
    Zona: 11 colunas
    Importance: 1349.535148
  Predicado: 1020 <= 0.04 (n=130)
    Zona: 11 colunas
    Importance: 1088.231830
  Predicado: 1020 > 0.04 (n=90)
    Zona: 11 colunas
    Importance: 1506.141446
  Predicado: 1020 <= 0.15 (n=175)
    Zona: 11 colunas
    Importance: 1069.942775
  Predicado: 1040 > -0.15 (n=181)
    Zona: 11 colunas
    Importance: 1237.580592
  Predicado: 1040 <= -0.04 (n=84)
    Zona: 11 colunas
    Importance: 1026.373120
  Predicado: 1040 > -0.04 (n=136)
    Zona: 11 colunas
    Importance: 1261.736966
  Predicado: 1040 <= 0.04 (n=129)
    Zona: 11 colunas
    Importance: 1033.472985
  Predicado: 1040 > 0.04 (n=91)
    Zona: 11 colunas
    Importance: 1368.061037
  Predicado: 1040 <= 0.16 (n=175)
    Zona: 11 colunas
    Importance: 995.745265
  Predicado: 1060 > -0.16 (n=182)
    Zona: 11 colunas
    Importance: 1091.511547
  Predicado: 1060 <= -0.04 (n=87)
    Zona: 11 colunas
    Importance: 922.661273
  Predicado: 1060 > -0.04 (n=133)
    Zona: 11 colunas
    Importance: 1111.800195
  Predicado: 1060 <= 0.04 (n=129)
    Zona: 11 colunas
    Importance: 914.537041
  Predicado: 1060 > 0.04 (n=91)
    Zona: 11 colunas
    Importance: 1210.611850
  Predicado: 1060 <= 0.16 (n=174)
    Zona: 11 colunas
    Importance: 817.413999
  Predicado: 1080 > -0.16 (n=180)
    Zona: 11 colunas
    Importance: 928.987110
  Predicado: 1080 <= -0.05 (n=83)
    Zona: 11 colunas
    Importance: 773.145840
  Predicado: 1080 > -0.05 (n=137)
    Zona: 11 colunas
    Importance: 942.718588
  Predicado: 1080 <= 0.04 (n=126)
    Zona: 11 colunas
    Importance: 805.863185
  Predicado: 1080 > 0.04 (n=94)
    Zona: 11 colunas
    Importance: 976.433936
  Predicado: 1080 <= 0.17 (n=176)
    Zona: 11 colunas
    Importance: 688.441294
  Predicado: 1100 > -0.17 (n=182)
    Zona: 11 colunas
    Importance: 858.973120
  Predicado: 1100 <= -0.05 (n=83)
    Zona: 11 colunas
    Importance: 718.015743
  Predicado: 1100 > -0.05 (n=137)
    Zona: 11 colunas
    Importance: 875.490878
  Predicado: 1100 <= 0.04 (n=124)
    Zona: 11 colunas
    Importance: 688.470449
  Predicado: 1100 > 0.04 (n=96)
    Zona: 11 colunas
    Importance: 980.908555
  Predicado: 1100 <= 0.17 (n=174)
    Zona: 11 colunas
    Importance: 639.958503
  Predicado: 1120 > -0.17 (n=180)
    Zona: 11 colunas
    Importance: 639.317354
  Predicado: 1120 <= -0.05 (n=87)
    Zona: 11 colunas
    Importance: 531.841548
  Predicado: 1120 > -0.05 (n=133)
    Zona: 11 colunas
    Importance: 652.427780
  Predicado: 1120 <= 0.05 (n=132)
    Zona: 11 colunas
    Importance: 541.990046
  Predicado: 1120 > 0.05 (n=88)
    Zona: 11 colunas
    Importance: 698.868448
  Predicado: 1120 <= 0.17 (n=174)
    Zona: 11 colunas
    Importance: 474.230805
  Predicado: 1140 > -0.17 (n=179)
    Zona: 11 colunas
    Importance: 418.262445
  Predicado: 1140 <= -0.05 (n=87)
    Zona: 11 colunas
    Importance: 346.471260
  Predicado: 1140 > -0.05 (n=133)
    Zona: 11 colunas
    Importance: 425.026179
  Predicado: 1140 <= 0.05 (n=129)
    Zona: 11 colunas
    Importance: 365.761797
  Predicado: 1140 > 0.05 (n=91)
    Zona: 11 colunas
    Importance: 433.936369
  Predicado: 1140 <= 0.18 (n=175)
    Zona: 11 colunas
    Importance: 308.001462
  Predicado: 1160 > -0.18 (n=181)
    Zona: 11 colunas
    Importance: 196.166140

/home/jvribeiro/.local/lib/python3.10/site-packages/networkx/algorithms/centrality/reaching.py:193: RuntimeWarning:

divide by zero encountered in scalar divide

    Predicate_pert_Seed_0
0            2380 <= 0.07
1            1540 > -0.05
2           1540 <= -0.05
3            2100 <= 0.07
4            1360 > -0.19
..                    ...
627         1760 <= -0.05
628          440 <= -0.07
629           440 <= 0.04
630               Class_A
631               Class_B

[632 rows x 1 columns]

In [8]:
all_results_pert[0]['pert_results_dict']['Bag_1']

         Predicate  Perturbation
0      700 > -0.12   7311.393654
1       700 > 0.06   6740.986302
2      750 > -0.12   6362.040985
3       750 > 0.07   6029.978795
4      700 <= 0.25   5634.802451
..             ...           ...
247   1150 <= 0.44    261.624487
248   2100 <= 0.17    245.696162
249  2200 <= -0.15    244.062280
250   2200 <= 0.44    242.394453
251   2200 <= 0.17    219.048170

[252 rows x 2 columns]

In [20]:
predicates_quantiles[0]['rule']

0      400 <= -0.27
1       400 > -0.27
2      400 <= -0.11
3       400 > -0.11
4       400 <= 0.07
           ...
331    2450 > -0.16
332    2450 <= 0.18
333     2450 > 0.18
334    2450 <= 0.44
335     2450 > 0.44
Name: rule, Length: 336, dtype: object

In [22]:
from collections import defaultdict

# 1. Coletar posições de cada predicado em cada bag
positions_dict = defaultdict(list)

for bag_num in range(1, 11):
    bag_name = f'Bag_{bag_num}'
    bag_df = all_results_pert[0]['pert_results_dict'][bag_name]
    
    for position, predicate in enumerate(bag_df['Predicate'], start=1):
        positions_dict[predicate].append(position)

# 2. Calcular média e número de aparições
results = []
for predicate, positions in positions_dict.items():
    results.append({
        'Predicate': predicate,
        'Mean_Position': np.mean(positions),
        'Appearances': len(positions),
        'Zone' : predicates_quantiles[0].loc[predicates_quantiles[0]['rule'] == predicate, 'zone'].values[0]
    })

# 3. Ordenar: menor posição média primeiro, mais aparições em caso de empate
ranking_df = pd.DataFrame(results).sort_values(
    by=['Mean_Position', 'Appearances'], 
    ascending=[True, False]
).reset_index(drop=True)

# 4. Lista final ordenada
lista_ordenada = ranking_df['Predicate'].tolist()
ranking_df

         Predicate  Mean_Position  Appearances  Zone
0      700 > -0.12            2.2           10   700
1      700 <= 0.25            3.6           10   700
2       700 > 0.06            3.7           10   700
3      750 > -0.12            5.7           10   750
4       750 > 0.07            6.8           10   750
..             ...            ...          ...   ...
247  2200 <= -0.15          246.3           10  2200
248   2200 > -0.15          246.9           10  2200
249   1150 <= 0.44          247.0           10  1150
250   2100 <= 0.17          247.5           10  2100
251   2200 <= 0.17          249.7           10  2200

[252 rows x 4 columns]

In [24]:
ranking_unique_df = ranking_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
ranking_unique_df['Zone']

0      700
1      750
2      550
3      650
4      800
5      500
6     1350
7     1550
8      950
9     1600
10    1000
11    1500
12    1400
13    1650
14    1450
15     900
16    1700
17    1050
18     850
19    1300
20    1750
21    1800
22    2150
23    1900
24    1250
25    2450
26    1100
27    2400
28    1950
29     600
30     450
31    1850
32    2000
33    1200
34     400
35    2050
36    2300
37    2250
38    2350
39    2100
40    1150
41    2200
Name: Zone, dtype: object

In [12]:
DG_fold = exp.build_fold_predicate_graph(
    bags_result=all_results_pert[0]['bags_result'],
    mi_results_dict=all_results_pert[0]['pert_results_dict'],
    predicates_df=predicates_quantiles[0],  # DataFrame com metadados dos predicados
    random_state=42,                    # Semente para reprodutibilidade
    show_details=True,                  # Mostra detalhes da resolução
    normalize_weights=True,            # False = peso inteiro | True = peso [1/k, 1]
    weight_mode='cooccurrence',         # 'ranking' ou 'cooccurrence'
    co_occurrence_matrix=co_occurrence_matrix_df,  # Necessário se weight_mode='cooccurrence'
    apply_confidence_multiplier=True,    # True = peso × score | False = só co-ocorrência
    accumulate_cooccurrence_weights=False 
)

# Calcula LRC para cada nó e compõe DataFrame
lrc_df_fold = exp.calculate_lrc_single_graph(DG_fold, predicates_quantiles[0])
# Seleciona apenas uma ocorrência por zona (maior LRC)
lrc_ks_unique_df_fold = lrc_df_fold.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
lrc_df_fold

 AVISO: normalize_weights=True ignorado em weight_mode='cooccurrence'
   (Pesos de co-ocorrência representam contagens reais de amostras)

============================================================
CONSTRUÇÃO DO GRAFO DE PREDICADOS
Modo de peso: COOCCURRENCE
Fonte: Matriz de co-ocorrência global
Sub-estratégia: NÃO-ACUMULATIVA (peso fixo da matriz)
============================================================

Folds processados: 10
Arestas criadas (antes de resolver bidirecionais): 2103

============================================================
RESOLUÇÃO DE ARESTAS BIDIRECIONAIS
============================================================
Total de pares bidirecionais encontrados: 209
Critério de desempate: SCORE DE CONFIANÇA (soma dos ranks invertidos)
(Peso de co-ocorrência global é simétrico, então usamos score para decidir direção)

[700 > -0.12 ↔ 750 > 0.07]
  ✗ Removida: 700 > -0.12 → 750 > 0.07 (score=250.00, peso=110.00)
  ✓ Mantida:  750 > 0.07 → 700 > -0.12 (score=502.00, peso=110.00)

[700 > -0.12 ↔ 700 <= 0.25]
  ✗ Removida: 700 <= 0.25 → 700 > -0.12 (score=503.00, peso=115.00)
  ✓ Mantida:  700 > -0.12 → 700 <= 0.25 (score=504.00, peso=115.00)

[700 > 0.06 ↔ 700 <= 0.25]
  ✗ Removida: 700 <= 0.25 → 700 > 0.06 (score=251.00, peso=61.00)
  ✓ Mantida:  700 > 0.06 → 700 <= 0.25 (score=252.00, peso=61.00)

[700 > 0.06 ↔ 550 > 0.04]
  ✗ Removida: 700 > 0.06 → 550 > 0.04 (score=250.00, peso=63.00)
  ✓ Mantida:  550 > 0.04 → 700 > 0.06 (score=499.00, peso=63.00)

[750 > -0.12 ↔ 650 > 0.04]  EMPATE (score=249.00)
  ✗ Removida (aleatório): 750 > -0.12 → 650 > 0.04
  ✓ Mantida:  650 > 0.04 → 750 > -0.12

[750 > -0.12 ↔ 700 > -0.26]
  ✗ Removida: 700 > -0.26 → 750 > -0.12 (score=247.00, peso=164.00)
  ✓ Mantida:  750 > -0.12 → 700 > -0.26 (score=738.00, peso=164.00)

[750 > -0.12 ↔ 650 <= 0.21]
  ✗ Removida: 750 > -0.12 → 650 <= 0.21 (score=247.00, peso=107.00)
  ✓ Mantida:  650 <= 0.21 → 750 > -0.12 (score=492.00, peso=107.00)

[750 > 0.07 ↔ 700 > -0.26]
  ✗ Removida: 750 > 0.07 → 700 > -0.26 (score=249.00, peso=110.00)
  ✓ Mantida:  700 > -0.26 → 750 > 0.07 (score=489.00, peso=110.00)

[700 <= 0.25 ↔ 700 > -0.26]
  ✗ Removida: 700 <= 0.25 → 700 > -0.26 (score=248.00, peso=169.00)
  ✓ Mantida:  700 > -0.26 → 700 <= 0.25 (score=495.00, peso=169.00)

[700 <= 0.25 ↔ 750 > -0.28]
  ✗ Removida: 750 > -0.28 → 700 <= 0.25 (score=245.00, peso=169.00)
  ✓ Mantida:  700 <= 0.25 → 750 > -0.28 (score=246.00, peso=169.00)

[700 > -0.26 ↔ 650 > 0.04]
  ✗ Removida: 700 > -0.26 → 650 > 0.04 (score=244.00, peso=112.00)
  ✓ Mantida:  650 > 0.04 → 700 > -0.26 (score=248.00, peso=112.00)

[700 <= 0.06 ↔ 650 > -0.11]
  ✗ Removida: 650 > -0.11 → 700 <= 0.06 (score=240.00, peso=55.00)
  ✓ Mantida:  700 <= 0.06 → 650 > -0.11 (score=242.00, peso=55.00)

[650 <= 0.21 ↔ 750 <= 0.25]
  ✗ Removida: 750 <= 0.25 → 650 <= 0.21 (score=488.00, peso=209.00)
  ✓ Mantida:  650 <= 0.21 → 750 <= 0.25 (score=492.00, peso=209.00)

[650 <= 0.21 ↔ 500 > 0.06]
  ✗ Removida: 650 <= 0.21 → 500 > 0.06 (score=244.00, peso=83.00)
  ✓ Mantida:  500 > 0.06 → 650 <= 0.21 (score=246.00, peso=83.00)

[650 > 0.04 ↔ 500 > 0.06]  EMPATE (score=243.00)
  ✗ Removida (aleatório): 500 > 0.06 → 650 > 0.04
  ✓ Mantida:  650 > 0.04 → 500 > 0.06

[650 > 0.04 ↔ 750 > -0.28]
  ✗ Removida: 750 > -0.28 → 650 > 0.04 (score=241.00, peso=112.00)
  ✓ Mantida:  650 > 0.04 → 750 > -0.28 (score=242.00, peso=112.00)

[650 > 0.04 ↔ 550 > -0.06]
  ✗ Removida: 550 > -0.06 → 650 > 0.04 (score=238.00, peso=92.00)
  ✓ Mantida:  650 > 0.04 → 550 > -0.06 (score=240.00, peso=92.00)

[650 > -0.11 ↔ 750 > -0.28]
  ✗ Removida: 750 > -0.28 → 650 > -0.11 (score=486.00, peso=167.00)
  ✓ Mantida:  650 > -0.11 → 750 > -0.28 (score=1215.00, peso=167.00)

[550 > -0.06 ↔ 750 <= 0.07]
  ✗ Removida: 750 <= 0.07 → 550 > -0.06 (score=235.00, peso=78.00)
  ✓ Mantida:  550 > -0.06 → 750 <= 0.07 (score=240.00, peso=78.00)

[550 > -0.06 ↔ 800 > 0.07]
  ✗ Removida: 550 > -0.06 → 800 > 0.07 (score=239.00, peso=88.00)
  ✓ Mantida:  800 > 0.07 → 550 > -0.06 (score=240.00, peso=88.00)

[550 > -0.06 ↔ 650 > -0.23]
  ✗ Removida: 650 > -0.23 → 550 > -0.06 (score=237.00, peso=153.00)
  ✓ Mantida:  550 > -0.06 → 650 > -0.23 (score=716.00, peso=153.00)

[750 <= 0.07 ↔ 1500 > -0.47]
  ✗ Removida: 1500 > -0.47 → 750 <= 0.07 (score=202.00, peso=110.00)
  ✓ Mantida:  750 <= 0.07 → 1500 > -0.47 (score=203.00, peso=110.00)

[750 <= 0.07 ↔ 650 > -0.23]
  ✗ Removida: 750 <= 0.07 → 650 > -0.23 (score=236.00, peso=109.00)
  ✓ Mantida:  650 > -0.23 → 750 <= 0.07 (score=473.00, peso=109.00)

[750 <= 0.07 ↔ 550 > -0.23]
  ✗ Removida: 550 > -0.23 → 750 <= 0.07 (score=233.00, peso=115.00)
  ✓ Mantida:  750 <= 0.07 → 550 > -0.23 (score=236.00, peso=115.00)

[650 > -0.23 ↔ 550 > -0.23]
  ✗ Removida: 650 > -0.23 → 550 > -0.23 (score=237.00, peso=195.00)
  ✓ Mantida:  550 > -0.23 → 650 > -0.23 (score=238.00, peso=195.00)

[650 > -0.23 ↔ 1000 > 0.09]
  ✗ Removida: 650 > -0.23 → 1000 > 0.09 (score=237.00, peso=109.00)
  ✓ Mantida:  1000 > 0.09 → 650 > -0.23 (score=239.00, peso=109.00)

[550 > -0.23 ↔ 1000 > 0.09]
  ✗ Removida: 550 > -0.23 → 1000 > 0.09 (score=233.00, peso=100.00)
  ✓ Mantida:  1000 > 0.09 → 550 > -0.23 (score=236.00, peso=100.00)

[500 > -0.14 ↔ 800 > -0.11]
  ✗ Removida: 800 > -0.11 → 500 > -0.14 (score=229.00, peso=113.00)
  ✓ Mantida:  500 > -0.14 → 800 > -0.11 (score=234.00, peso=113.00)

[800 > -0.11 ↔ 550 <= 0.19]  EMPATE (score=230.00)
  ✗ Removida (aleatório): 550 <= 0.19 → 800 > -0.11
  ✓ Mantida:  800 > -0.11 → 550 <= 0.19

[800 > -0.11 ↔ 1000 > 0.09]
  ✗ Removida: 1000 > 0.09 → 800 > -0.11 (score=232.00, peso=110.00)
  ✓ Mantida:  800 > -0.11 → 1000 > 0.09 (score=233.00, peso=110.00)

[800 > -0.11 ↔ 950 <= 0.31]  EMPATE (score=231.00)
  ✗ Removida (aleatório): 950 <= 0.31 → 800 > -0.11
  ✓ Mantida:  800 > -0.11 → 950 <= 0.31

[1550 > 0.17 ↔ 1350 > 0.15]
  ✗ Removida: 1350 > 0.15 → 1550 > 0.17 (score=690.00, peso=105.00)
  ✓ Mantida:  1550 > 0.17 → 1350 > 0.15 (score=933.00, peso=105.00)

[1550 > 0.17 ↔ 500 <= 0.27]
  ✗ Removida: 1550 > 0.17 → 500 <= 0.27 (score=225.00, peso=92.00)
  ✓ Mantida:  500 <= 0.27 → 1550 > 0.17 (score=227.00, peso=92.00)

[1550 > 0.17 ↔ 950 > 0.08]
  ✗ Removida: 950 > 0.08 → 1550 > 0.17 (score=226.00, peso=95.00)
  ✓ Mantida:  1550 > 0.17 → 950 > 0.08 (score=459.00, peso=95.00)

[950 > 0.08 ↔ 1500 > 0.17]
  ✗ Removida: 1500 > 0.17 → 950 > 0.08 (score=233.00, peso=96.00)
  ✓ Mantida:  950 > 0.08 → 1500 > 0.17 (score=452.00, peso=96.00)

[950 > 0.08 ↔ 1600 > 0.16]
  ✗ Removida: 1600 > 0.16 → 950 > 0.08 (score=224.00, peso=94.00)
  ✓ Mantida:  950 > 0.08 → 1600 > 0.16 (score=456.00, peso=94.00)

[700 <= -0.12 ↔ 500 <= 0.27]
  ✗ Removida: 500 <= 0.27 → 700 <= -0.12 (score=224.00, peso=92.00)
  ✓ Mantida:  700 <= -0.12 → 500 <= 0.27 (score=226.00, peso=92.00)

[1000 > 0.09 ↔ 1600 > 0.16]
  ✗ Removida: 1600 > 0.16 → 1000 > 0.09 (score=227.00, peso=95.00)
  ✓ Mantida:  1000 > 0.09 → 1600 > 0.16 (score=228.00, peso=95.00)

[1000 > 0.09 ↔ 1500 > 0.17]  EMPATE (score=226.00)
  ✗ Removida (aleatório): 1000 > 0.09 → 1500 > 0.17
  ✓ Mantida:  1500 > 0.17 → 1000 > 0.09

[1600 > 0.16 ↔ 1500 > 0.17]
  ✗ Removida: 1500 > 0.17 → 1600 > 0.16 (score=452.00, peso=106.00)
  ✓ Mantida:  1600 > 0.16 → 1500 > 0.17 (score=913.00, peso=106.00)

[1600 > 0.16 ↔ 500 <= 0.27]
  ✗ Removida: 500 <= 0.27 → 1600 > 0.16 (score=225.00, peso=91.00)
  ✓ Mantida:  1600 > 0.16 → 500 <= 0.27 (score=227.00, peso=91.00)

[650 <= 0.04 ↔ 950 <= 0.31]
  ✗ Removida: 650 <= 0.04 → 950 <= 0.31 (score=177.00, peso=160.00)
  ✓ Mantida:  950 <= 0.31 → 650 <= 0.04 (score=224.00, peso=160.00)

[500 <= 0.27 ↔ 550 <= 0.19]
  ✗ Removida: 550 <= 0.19 → 500 <= 0.27 (score=222.00, peso=211.00)
  ✓ Mantida:  500 <= 0.27 → 550 <= 0.19 (score=224.00, peso=211.00)

[500 <= 0.27 ↔ 800 > -0.26]
  ✗ Removida: 800 > -0.26 → 500 <= 0.27 (score=215.00, peso=171.00)
  ✓ Mantida:  500 <= 0.27 → 800 > -0.26 (score=446.00, peso=171.00)

[500 > -0.32 ↔ 1000 > -0.09]
  ✗ Removida: 1000 > -0.09 → 500 > -0.32 (score=224.00, peso=142.00)
  ✓ Mantida:  500 > -0.32 → 1000 > -0.09 (score=446.00, peso=142.00)

[500 > -0.32 ↔ 1450 > 0.16]
  ✗ Removida: 500 > -0.32 → 1450 > 0.16 (score=214.00, peso=96.00)
  ✓ Mantida:  1450 > 0.16 → 500 > -0.32 (score=222.00, peso=96.00)

[1000 > -0.09 ↔ 1400 > 0.15]
  ✗ Removida: 1400 > 0.15 → 1000 > -0.09 (score=226.00, peso=110.00)
  ✓ Mantida:  1000 > -0.09 → 1400 > 0.15 (score=435.00, peso=110.00)

[1400 > 0.15 ↔ 500 > 0.06]
  ✗ Removida: 500 > 0.06 → 1400 > 0.15 (score=221.00, peso=46.00)
  ✓ Mantida:  1400 > 0.15 → 500 > 0.06 (score=229.00, peso=46.00)

[1650 > 0.15 ↔ 1000 > -0.34]
  ✗ Removida: 1000 > -0.34 → 1650 > 0.15 (score=214.00, peso=111.00)
  ✓ Mantida:  1650 > 0.15 → 1000 > -0.34 (score=216.00, peso=111.00)

[1650 > 0.15 ↔ 1450 > 0.16]
  ✗ Removida: 1450 > 0.16 → 1650 > 0.15 (score=374.00, peso=106.00)
  ✓ Mantida:  1650 > 0.15 → 1450 > 0.16 (score=647.00, peso=106.00)

[1650 > 0.15 ↔ 900 > 0.08]
  ✗ Removida: 900 > 0.08 → 1650 > 0.15 (score=209.00, peso=94.00)
  ✓ Mantida:  1650 > 0.15 → 900 > 0.08 (score=216.00, peso=94.00)

[1000 > -0.34 ↔ 1450 > 0.16]
  ✗ Removida: 1450 > 0.16 → 1000 > -0.34 (score=213.00, peso=110.00)
  ✓ Mantida:  1000 > -0.34 → 1450 > 0.16 (score=433.00, peso=110.00)

[1000 > -0.34 ↔ 950 > -0.09]
  ✗ Removida: 1000 > -0.34 → 950 > -0.09 (score=212.00, peso=165.00)
  ✓ Mantida:  950 > -0.09 → 1000 > -0.34 (score=214.00, peso=165.00)

[900 > 0.08 ↔ 950 > -0.09]
  ✗ Removida: 950 > -0.09 → 900 > 0.08 (score=429.00, peso=109.00)
  ✓ Mantida:  900 > 0.08 → 950 > -0.09 (score=644.00, peso=109.00)

[800 <= 0.24 ↔ 950 > -0.09]  EMPATE (score=211.00)
  ✗ Removida (aleatório): 800 <= 0.24 → 950 > -0.09
  ✓ Mantida:  950 > -0.09 → 800 <= 0.24

[1700 > 0.16 ↔ 1350 > -0.45]
  ✗ Removida: 1350 > -0.45 → 1700 > 0.16 (score=205.00, peso=110.00)
  ✓ Mantida:  1700 > 0.16 → 1350 > -0.45 (score=209.00, peso=110.00)

[950 > -0.30 ↔ 1350 > -0.45]
  ✗ Removida: 1350 > -0.45 → 950 > -0.30 (score=202.00, peso=214.00)
  ✓ Mantida:  950 > -0.30 → 1350 > -0.45 (score=619.00, peso=214.00)

[950 > -0.30 ↔ 1500 > -0.47]
  ✗ Removida: 1500 > -0.47 → 950 > -0.30 (score=406.00, peso=213.00)
  ✓ Mantida:  950 > -0.30 → 1500 > -0.47 (score=408.00, peso=213.00)

[950 > -0.30 ↔ 1550 > -0.47]
  ✗ Removida: 950 > -0.30 → 1550 > -0.47 (score=201.00, peso=212.00)
  ✓ Mantida:  1550 > -0.47 → 950 > -0.30 (score=410.00, peso=212.00)

[1350 > -0.45 ↔ 1550 > -0.47]
  ✗ Removida: 1550 > -0.47 → 1350 > -0.45 (score=199.00, peso=217.00)
  ✓ Mantida:  1350 > -0.45 → 1550 > -0.47 (score=819.00, peso=217.00)

[1350 > -0.45 ↔ 1900 > 0.16]  EMPATE (score=206.00)
  ✗ Removida (aleatório): 1350 > -0.45 → 1900 > 0.16
  ✓ Mantida:  1900 > 0.16 → 1350 > -0.45

[1600 > -0.48 ↔ 850 > 0.07]  EMPATE (score=201.00)
  ✗ Removida (aleatório): 850 > 0.07 → 1600 > -0.48
  ✓ Mantida:  1600 > -0.48 → 850 > 0.07

[850 > 0.07 ↔ 1750 > 0.15]
  ✗ Removida: 1750 > 0.15 → 850 > 0.07 (score=199.00, peso=89.00)
  ✓ Mantida:  850 > 0.07 → 1750 > 0.15 (score=419.00, peso=89.00)

[850 > 0.07 ↔ 1350 > -0.13]
  ✗ Removida: 1350 > -0.13 → 850 > 0.07 (score=208.00, peso=107.00)
  ✓ Mantida:  850 > 0.07 → 1350 > -0.13 (score=212.00, peso=107.00)

[1350 <= -0.13 ↔ 1400 > -0.45]
  ✗ Removida: 1350 <= -0.13 → 1400 > -0.45 (score=197.00, peso=55.00)
  ✓ Mantida:  1400 > -0.45 → 1350 <= -0.13 (score=391.00, peso=55.00)

[1350 <= -0.13 ↔ 1550 <= -0.11]
  ✗ Removida: 1350 <= -0.13 → 1550 <= -0.11 (score=197.00, peso=108.00)
  ✓ Mantida:  1550 <= -0.11 → 1350 <= -0.13 (score=198.00, peso=108.00)

[1750 > 0.15 ↔ 1350 > -0.13]
  ✗ Removida: 1750 > 0.15 → 1350 > -0.13 (score=398.00, peso=109.00)
  ✓ Mantida:  1350 > -0.13 → 1750 > 0.15 (score=411.00, peso=109.00)

[1750 > 0.15 ↔ 1550 <= -0.11]
  ✗ Removida: 1750 > 0.15 → 1550 <= -0.11 (score=195.00, peso=0.00)
  ✓ Mantida:  1550 <= -0.11 → 1750 > 0.15 (score=196.00, peso=0.00)

[1000 <= -0.09 ↔ 1550 <= -0.11]
  ✗ Removida: 1550 <= -0.11 → 1000 <= -0.09 (score=157.00, peso=100.00)
  ✓ Mantida:  1000 <= -0.09 → 1550 <= -0.11 (score=602.00, peso=100.00)

[1000 <= -0.09 ↔ 1100 > -0.11]
  ✗ Removida: 1000 <= -0.09 → 1100 > -0.11 (score=151.00, peso=9.00)
  ✓ Mantida:  1100 > -0.11 → 1000 <= -0.09 (score=162.00, peso=9.00)

[1500 <= -0.11 ↔ 800 <= 0.07]
  ✗ Removida: 1500 <= -0.11 → 800 <= 0.07 (score=170.00, peso=105.00)
  ✓ Mantida:  800 <= 0.07 → 1500 <= -0.11 (score=316.00, peso=105.00)

[1550 > -0.11 ↔ 1050 > -0.37]
  ✗ Removida: 1550 > -0.11 → 1050 > -0.37 (score=185.00, peso=165.00)
  ✓ Mantida:  1050 > -0.37 → 1550 > -0.11 (score=189.00, peso=165.00)

[1050 > -0.10 ↔ 950 <= -0.09]
  ✗ Removida: 950 <= -0.09 → 1050 > -0.10 (score=180.00, peso=7.00)
  ✓ Mantida:  1050 > -0.10 → 950 <= -0.09 (score=182.00, peso=7.00)

[1650 > -0.47 ↔ 1450 > -0.46]
  ✗ Removida: 1450 > -0.46 → 1650 > -0.47 (score=191.00, peso=215.00)
  ✓ Mantida:  1650 > -0.47 → 1450 > -0.46 (score=375.00, peso=215.00)

[1650 > -0.47 ↔ 1650 > -0.10]
  ✗ Removida: 1650 > -0.47 → 1650 > -0.10 (score=190.00, peso=164.00)
  ✓ Mantida:  1650 > -0.10 → 1650 > -0.47 (score=192.00, peso=164.00)

[1450 > -0.46 ↔ 1050 > -0.37]
  ✗ Removida: 1450 > -0.46 → 1050 > -0.37 (score=375.00, peso=217.00)
  ✓ Mantida:  1050 > -0.37 → 1450 > -0.46 (score=568.00, peso=217.00)

[1800 > 0.15 ↔ 1400 <= -0.12]  EMPATE (score=182.00)
  ✗ Removida (aleatório): 1400 <= -0.12 → 1800 > 0.15
  ✓ Mantida:  1800 > 0.15 → 1400 <= -0.12

[1400 <= -0.12 ↔ 1000 <= 0.34]
  ✗ Removida: 1400 <= -0.12 → 1000 <= 0.34 (score=177.00, peso=110.00)
  ✓ Mantida:  1000 <= 0.34 → 1400 <= -0.12 (score=213.00, peso=110.00)

[950 <= -0.09 ↔ 1100 > -0.40]
  ✗ Removida: 1100 > -0.40 → 950 <= -0.09 (score=146.00, peso=54.00)
  ✓ Mantida:  950 <= -0.09 → 1100 > -0.40 (score=149.00, peso=54.00)

[950 <= -0.09 ↔ 1050 <= -0.10]
  ✗ Removida: 1050 <= -0.10 → 950 <= -0.09 (score=171.00, peso=103.00)
  ✓ Mantida:  950 <= -0.09 → 1050 <= -0.10 (score=215.00, peso=103.00)

[1400 > -0.12 ↔ 900 > -0.09]
  ✗ Removida: 900 > -0.09 → 1400 > -0.12 (score=196.00, peso=151.00)
  ✓ Mantida:  1400 > -0.12 → 900 > -0.09 (score=306.00, peso=151.00)

[2150 > 0.18 ↔ 1450 > -0.12]
  ✗ Removida: 1450 > -0.12 → 2150 > 0.18 (score=170.00, peso=107.00)
  ✓ Mantida:  2150 > 0.18 → 1450 > -0.12 (score=523.00, peso=107.00)

[2150 > 0.18 ↔ 1650 > -0.10]
  ✗ Removida: 2150 > 0.18 → 1650 > -0.10 (score=110.00, peso=109.00)
  ✓ Mantida:  1650 > -0.10 → 2150 > 0.18 (score=182.00, peso=109.00)

[1650 <= -0.10 ↔ 800 <= 0.07]
  ✗ Removida: 1650 <= -0.10 → 800 <= 0.07 (score=168.00, peso=105.00)
  ✓ Mantida:  800 <= 0.07 → 1650 <= -0.10 (score=169.00, peso=105.00)

[1650 > -0.10 ↔ 1700 > -0.47]
  ✗ Removida: 1650 > -0.10 → 1700 > -0.47 (score=170.00, peso=164.00)
  ✓ Mantida:  1700 > -0.47 → 1650 > -0.10 (score=177.00, peso=164.00)

[1650 > -0.10 ↔ 1700 <= -0.11]
  ✗ Removida: 1700 <= -0.11 → 1650 > -0.10 (score=163.00, peso=2.00)
  ✓ Mantida:  1650 > -0.10 → 1700 <= -0.11 (score=167.00, peso=2.00)

[1700 > -0.47 ↔ 1700 > -0.11]  EMPATE (score=180.00)
  ✗ Removida (aleatório): 1700 > -0.11 → 1700 > -0.47
  ✓ Mantida:  1700 > -0.47 → 1700 > -0.11

[550 <= -0.06 ↔ 500 <= -0.14]
  ✗ Removida: 500 <= -0.14 → 550 <= -0.06 (score=39.00, peso=98.00)
  ✓ Mantida:  550 <= -0.06 → 500 <= -0.14 (score=88.00, peso=98.00)

[550 <= -0.06 ↔ 850 > -0.25]
  ✗ Removida: 850 > -0.25 → 550 <= -0.06 (score=168.00, peso=76.00)
  ✓ Mantida:  550 <= -0.06 → 850 > -0.25 (score=169.00, peso=76.00)

[1300 > -0.46 ↔ 950 <= 0.08]
  ✗ Removida: 950 <= 0.08 → 1300 > -0.46 (score=166.00, peso=109.00)
  ✓ Mantida:  1300 > -0.46 → 950 <= 0.08 (score=169.00, peso=109.00)

[1300 > -0.46 ↔ 1700 > -0.11]
  ✗ Removida: 1300 > -0.46 → 1700 > -0.11 (score=176.00, peso=166.00)
  ✓ Mantida:  1700 > -0.11 → 1300 > -0.46 (score=179.00, peso=166.00)

[800 <= 0.07 ↔ 1300 <= -0.14]
  ✗ Removida: 800 <= 0.07 → 1300 <= -0.14 (score=163.00, peso=103.00)
  ✓ Mantida:  1300 <= -0.14 → 800 <= 0.07 (score=175.00, peso=103.00)

[800 <= 0.07 ↔ 900 > -0.27]
  ✗ Removida: 800 <= 0.07 → 900 > -0.27 (score=154.00, peso=106.00)
  ✓ Mantida:  900 > -0.27 → 800 <= 0.07 (score=162.00, peso=106.00)

[800 <= 0.07 ↔ 1700 <= -0.11]
  ✗ Removida: 1700 <= -0.11 → 800 <= 0.07 (score=136.00, peso=103.00)
  ✓ Mantida:  800 <= 0.07 → 1700 <= -0.11 (score=208.00, peso=103.00)

[1500 <= 0.45 ↔ 1050 <= 0.10]
  ✗ Removida: 1500 <= 0.45 → 1050 <= 0.10 (score=294.00, peso=167.00)
  ✓ Mantida:  1050 <= 0.10 → 1500 <= 0.45 (score=329.00, peso=167.00)

[1500 <= 0.45 ↔ 1750 > -0.47]
  ✗ Removida: 1750 > -0.47 → 1500 <= 0.45 (score=152.00, peso=163.00)
  ✓ Mantida:  1500 <= 0.45 → 1750 > -0.47 (score=153.00, peso=163.00)

[1500 <= 0.45 ↔ 850 > -0.25]
  ✗ Removida: 850 > -0.25 → 1500 <= 0.45 (score=154.00, peso=164.00)
  ✓ Mantida:  1500 <= 0.45 → 850 > -0.25 (score=155.00, peso=164.00)

[900 > -0.27 ↔ 1750 > -0.47]
  ✗ Removida: 1750 > -0.47 → 900 > -0.27 (score=305.00, peso=211.00)
  ✓ Mantida:  900 > -0.27 → 1750 > -0.47 (score=482.00, peso=211.00)

[1350 <= 0.42 ↔ 800 <= -0.11]
  ✗ Removida: 1350 <= 0.42 → 800 <= -0.11 (score=151.00, peso=110.00)
  ✓ Mantida:  800 <= -0.11 → 1350 <= 0.42 (score=202.00, peso=110.00)

[1350 <= 0.42 ↔ 1300 <= 0.15]
  ✗ Removida: 1300 <= 0.15 → 1350 <= 0.42 (score=112.00, peso=166.00)
  ✓ Mantida:  1350 <= 0.42 → 1300 <= 0.15 (score=121.00, peso=166.00)

[800 <= -0.11 ↔ 1250 > 0.14]
  ✗ Removida: 800 <= -0.11 → 1250 > 0.14 (score=152.00, peso=5.00)
  ✓ Mantida:  1250 > 0.14 → 800 <= -0.11 (score=159.00, peso=5.00)

[1900 > -0.44 ↔ 850 > -0.25]
  ✗ Removida: 850 > -0.25 → 1900 > -0.44 (score=271.00, peso=209.00)
  ✓ Mantida:  1900 > -0.44 → 850 > -0.25 (score=317.00, peso=209.00)

[850 > -0.25 ↔ 2450 <= 0.44]
  ✗ Removida: 2450 <= 0.44 → 850 > -0.25 (score=151.00, peso=165.00)
  ✓ Mantida:  850 > -0.25 → 2450 <= 0.44 (score=157.00, peso=165.00)

[1900 > -0.13 ↔ 2150 > -0.45]
  ✗ Removida: 2150 > -0.45 → 1900 > -0.13 (score=123.00, peso=164.00)
  ✓ Mantida:  1900 > -0.13 → 2150 > -0.45 (score=137.00, peso=164.00)

[1900 > -0.13 ↔ 1100 > 0.10]
  ✗ Removida: 1900 > -0.13 → 1100 > 0.10 (score=133.00, peso=109.00)
  ✓ Mantida:  1100 > 0.10 → 1900 > -0.13 (score=175.00, peso=109.00)

[1400 <= 0.42 ↔ 1800 <= -0.12]
  ✗ Removida: 1800 <= -0.12 → 1400 <= 0.42 (score=110.00, peso=108.00)
  ✓ Mantida:  1400 <= 0.42 → 1800 <= -0.12 (score=267.00, peso=108.00)

[1350 <= 0.15 ↔ 1500 <= 0.17]  EMPATE (score=288.00)
  ✗ Removida (aleatório): 1350 <= 0.15 → 1500 <= 0.17
  ✓ Mantida:  1500 <= 0.17 → 1350 <= 0.15

[1650 <= 0.46 ↔ 1450 <= 0.16]
  ✗ Removida: 1650 <= 0.46 → 1450 <= 0.16 (score=110.00, peso=165.00)
  ✓ Mantida:  1450 <= 0.16 → 1650 <= 0.46 (score=130.00, peso=165.00)

[1650 <= 0.46 ↔ 2150 > -0.45]
  ✗ Removida: 2150 > -0.45 → 1650 <= 0.46 (score=131.00, peso=164.00)
  ✓ Mantida:  1650 <= 0.46 → 2150 > -0.45 (score=271.00, peso=164.00)

[1800 > -0.47 ↔ 1050 <= 0.39]
  ✗ Removida: 1050 <= 0.39 → 1800 > -0.47 (score=139.00, peso=165.00)
  ✓ Mantida:  1800 > -0.47 → 1050 <= 0.39 (score=285.00, peso=165.00)

[1050 <= 0.39 ↔ 1450 <= 0.44]
  ✗ Removida: 1050 <= 0.39 → 1450 <= 0.44 (score=103.00, peso=213.00)
  ✓ Mantida:  1450 <= 0.44 → 1050 <= 0.39 (score=169.00, peso=213.00)

[1750 <= -0.11 ↔ 1900 <= -0.13]  EMPATE (score=144.00)
  ✗ Removida (aleatório): 1900 <= -0.13 → 1750 <= -0.11
  ✓ Mantida:  1750 <= -0.11 → 1900 <= -0.13

[1900 <= 0.44 ↔ 2150 <= -0.13]
  ✗ Removida: 1900 <= 0.44 → 2150 <= -0.13 (score=107.00, peso=112.00)
  ✓ Mantida:  2150 <= -0.13 → 1900 <= 0.44 (score=128.00, peso=112.00)

[1550 <= 0.17 ↔ 1400 <= 0.15]
  ✗ Removida: 1400 <= 0.15 → 1550 <= 0.17 (score=131.00, peso=162.00)
  ✓ Mantida:  1550 <= 0.17 → 1400 <= 0.15 (score=254.00, peso=162.00)

[2150 > -0.45 ↔ 1450 <= 0.44]
  ✗ Removida: 2150 > -0.45 → 1450 <= 0.44 (score=132.00, peso=164.00)
  ✓ Mantida:  1450 <= 0.44 → 2150 > -0.45 (score=140.00, peso=164.00)

[1450 <= 0.44 ↔ 450 > 0.08]
  ✗ Removida: 1450 <= 0.44 → 450 > 0.08 (score=104.00, peso=87.00)
  ✓ Mantida:  450 > 0.08 → 1450 <= 0.44 (score=136.00, peso=87.00)

[1450 <= 0.44 ↔ 2150 <= -0.13]

/home/jvribeiro/.local/lib/python3.10/site-packages/networkx/algorithms/centrality/reaching.py:193: RuntimeWarning:

divide by zero encountered in scalar divide

              Node  Local_Reaching_Centrality  Zone Threshold Operator
0       650 > 0.04                   4.334175   650      0.04        >
1      650 > -0.11                   4.251586   650     -0.11        >
2     1350 > -0.45                   3.682559  1350     -0.45        >
3       500 > 0.06                   3.679895   500      0.06        >
4     1750 > -0.47                   3.648994  1750     -0.47        >
..             ...                        ...   ...       ...      ...
249   2350 > -0.15                   0.934691  2350     -0.15        >
250   450 <= -0.16                   0.922739   450     -0.16       <=
251  1150 <= -0.12                   0.887386  1150     -0.12       <=
252        Class_A                   0.000000  None      None     None
253        Class_B                   0.000000  None      None     None

[254 rows x 5 columns]

In [33]:
import numpy as np

max_len = max(
    len(vip_scores_unique_df['Zone']),
    len(reg_vet_unique_df['Zone']),
    len(shap_unique_df['Zone']),
    #len(lrc_cov_unique_df['Zone']),
    len(lrc_pert_unique_df['Zone'])
)

def pad_list(lst, length):
    return list(lst) + [None] * (length - len(lst))

features_importance = pd.DataFrame({
    'Vip': pad_list(vip_scores_unique_df['Zone'], max_len),
    'Reg_coef': pad_list(reg_vet_unique_df['Zone'], max_len),
    'Shap': pad_list(shap_unique_df['Zone'].astype(str), max_len),
    'Ranking' : pad_list(ranking_unique_df['Zone'], max_len)
})

# for seed, lrc_unique_df in lrc_cov_unique_by_seed.items():
#     features_importance[f'LRC_cov_{seed}'] = pad_list(lrc_unique_df['Zone'].iloc[:10].tolist(), max_len)

# for seed, lrc_unique_df in lrc_pert_unique_by_seed.items():
#     features_importance[f'LRC_pert_{seed}'] = pad_list(lrc_unique_df['Zone'].iloc[:10].tolist(), max_len)

# vamos exportar o df features_importance para um arquivo excel onde vamos nomear a sheet de acordo com as comparacoes feitas
#features_importance.to_excel('features_importance_soil_vnir.xlsx', index=False, sheet_name='Perm')
features_importance.head(20)

     Vip Reg_coef  Shap Ranking
0    700      700   700     700
1    750      750   500     750
2    650      650   650     550
3    800      550   550     650
4    600      500  1600     800
5    500      800  1350     500
6    550     1000   750    1350
7    450      950  1500    1550
8    400     1400  2450     950
9    850     1050  1400    1600
10   950     1350  1550    1000
11  1000      600  1650    1500
12  2450     1550  1450    1400
13   900     1500  1700    1650
14  2400     1600   600    1450
15  1050     2200  1300     900
16  2350     1450  2400    1700
17  2300     1650  1750    1050
18  1100      900  1250     850
19  2250     1300   900    1300

In [32]:
# RBO (Rank-Biased Overlap) para comparar rankings
import rbo
rbo_results = {}
reference_list = [x for x in features_importance['Vip'].tolist() if x is not None]
methods = ['Reg_coef', 'Shap', 'Ranking'] #+ [f'LRC_cov_{seed}' for seed in random_seeds] + [f'LRC_perm_{seed}' for seed in random_seeds]
for method in methods:
    compare_list = [x for x in features_importance[method].tolist() if x is not None]
    # Truncate both lists to the same length (minimum of both)
    min_len = min(len(reference_list), len(compare_list))
    ref_trunc = reference_list[:min_len]
    cmp_trunc = compare_list[:min_len]
    score = rbo.RankingSimilarity(ref_trunc, cmp_trunc).rbo(p=0.7, k=10)
    rbo_results[method] = score
rbo_results = pd.DataFrame(list(rbo_results.items()), columns=['Method','RBO_Score'])
rbo_results.insert(0, 'Reference', 'Vip')
rbo_results.sort_values(by='RBO_Score', ascending=False, inplace=True)
#rbo_results.to_excel('rbo_soil_vnir.xlsx', index=False, sheet_name='perm')
rbo_results

  Reference    Method  RBO_Score
0       Vip  Reg_coef   0.886986
2       Vip   Ranking   0.852392
1       Vip      Shap   0.664785