## Loading data

In [6]:
# Importing the necessary libraries
import pandas as pd
import numpy as np
import kennard_stone as ks
pd.options.plotting.backend = 'plotly'  # setting plotly as the backend for pandas plotting

# Add parent directory to sys.path so local module 'synthetic' (one level up) can be imported
import sys
from pathlib import Path # for path manipulations
parent_dir = Path.cwd().parent.parent.resolve() # move two levels up from current working directory
if str(parent_dir) not in sys.path: # check to avoid duplicates
    sys.path.insert(0, str(parent_dir)) # insert at the start of sys.path to prioritize local modules

# Loading a soil spectral dataset based on X-ray fluorescence (XRF)
data_complete = pd.read_csv(f'{parent_dir}/XRF_databases/soil_types/plsda/soil_types.csv', sep=';') # local copy of Toledo and Guarapuava soil datasets
data = data_complete.loc[:, '1':'15']

# Split dataset by class and create calibration/prediction sets using Kennard-Stone (as in original pipeline)
data_A = data_complete[data_complete['Class'] == 'A'].reset_index(drop=True)
data_B = data_complete[data_complete['Class'] == 'B'].reset_index(drop=True)

# splitting the data into calibration and prediction sets by kennard-stone algorithm
XA_cal, XA_pred = ks.train_test_split(data_A.loc[:, '1':'15'], test_size=0.30) # class A
XA_cal = XA_cal.reset_index(drop=True)
XA_pred = XA_pred.reset_index(drop=True)

XB_cal, XB_pred = ks.train_test_split(data_B.loc[:, '1':'15'], test_size=0.30) # class B
XB_cal = XB_cal.reset_index(drop=True)
XB_pred = XB_pred.reset_index(drop=True)

Xcalclass = pd.concat([XA_cal, XB_cal], axis=0).reset_index(drop=True) # concatenating both classes
Xpredclass = pd.concat([XA_pred, XB_pred], axis=0).reset_index(drop=True)
ycalclass = pd.Series(['A']*XA_cal.shape[0] + ['B']*XB_cal.shape[0]) # creating the target variable for calibration set
ypredclass = pd.Series(['A']*XA_pred.shape[0] + ['B']*XB_pred.shape[0]) # creating the target variable for prediction set

# preprocessings
import preprocessings as prepr # preprocessing methods for XRF data

Xcalclass_prep, mean_calclass, mean_calclass_poisson  = prepr.poisson(Xcalclass, mc=True)
Xpredclass_prep = ((Xpredclass/np.sqrt(mean_calclass)) - mean_calclass_poisson)

from modeling import pls_optimized

# performing PLS-DA with optimized latent variables
plsda_results = pls_optimized(Xcalclass_prep, 
                              ycalclass,
                              LVmax=2,
                              Xpred=Xpredclass_prep,
                              ypred=ypredclass,
                              aim='classification',
                              cv=10)
plsda_results[0]


# Convenience references used later
pls_model = plsda_results[3]               # fitted PLS model
vip_scores_mat = plsda_results[4]          # VIP scores matrix (features × LV)
y_pred_cont = plsda_results[5].iloc[:, -1] # continuous predictions for Xcalclass (used for MI/Cov)

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning:

'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.

2026-01-26 07:16:43,033 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning:

'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.

2026-01-26 07:16:43,274 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning:

'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning:

'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.

2026-01-26 07:16:43,357 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning:

'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.

2026-01-26 07:16:43,596 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning:

'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.

In [7]:
# plotando o vip scores rapidamente
vip_scores_mat.T.plot()

In [8]:
# calculando a covariancia entre cada variável espectral e a predição do modelo PLS-DA
cov_scores = []
y_pred = plsda_results[5].iloc[:,-1].values # using the continuous predictions from LV=3
for col in Xcalclass_prep.columns:
    x_values = Xcalclass_prep[col].values
    covariance = np.cov(x_values, y_pred)[0, 1] # covariance between x and y
    cov_scores.append(covariance)
cov_scores_df = pd.DataFrame(cov_scores, index=Xcalclass_prep.columns, columns=['Covariance'])
cov_scores_df = np.abs(cov_scores_df)
cov_scores_df.plot()

In [9]:
# establishing spectral cuts based on expert knowledge of XRF spectra
spectral_cuts = [
('background1', 1.0, 1.33),
('Al', 1.33, 1.63),
('Si', 1.63, 1.86),
('P', 1.86, 2.19),
('S', 2.19, 2.44),
('background2', 2.44, 2.55),
('Rh L + Ar', 2.55, 3.21),
('K', 3.21, 3.53),
('Ca ka', 3.53, 3.84),
('Ca kb', 3.84, 4.14),
('background3', 4.14, 4.37),
('Ti ka', 4.37, 4.66),
('background4', 4.66, 4.75),
('Ti kb', 4.75, 5.12),
('Cr', 5.12, 5.77),
('Mn', 5.77, 6.13),
('Fe ka', 6.13, 6.80),
('Fe kb', 6.80, 7.30),
('background5', 7.30, 7.91),
('Cu', 7.91, 8.20),
('background6', 8.20, 10.69),
('Fe ka + Ti ka', 10.69, 11.14),
('background7', 11.14, 12.55),
('sum Fe' , 12.55, 13.1),
('background8', 13.1, 15.0)
]

import explaining as exp
spectral_zones_class = exp.extract_spectral_zones(Xcalclass_prep, spectral_cuts)
zone_sums_df = exp.aggregate_spectral_zones(spectral_zones_class, aggregator='extreme')
predicates_quantiles = exp.predicates_by_quantiles(zone_sums_df, [0.2, 0.4, 0.6, 0.8])
co_occurrence_matrix_df = predicates_quantiles[2]
predicate_info_dict = exp.create_predicate_info_dict(
    predicates_df=predicates_quantiles[0],
    predicate_indicator_df=predicates_quantiles[1],
    zone_aggregated_df=zone_sums_df,
    y_predicted_numeric=y_pred_cont
)

## VIP, Regression Coefficients e SHAP (como no original)

In [10]:
# VIP scores por energia
vip_scores_df = pd.DataFrame({
    'energy': vip_scores_mat.T.index,
    'VIP_Score': vip_scores_mat.T.iloc[:,0].values
})
vip_scores_df = vip_scores_df.sort_values(by='VIP_Score', ascending=False).reset_index(drop=True)
energy_to_zone_vip = {}
for zone_name, start, end in spectral_cuts:
    for e in vip_scores_df['energy']:
        ef = float(e)
        if start <= ef <= end:
            energy_to_zone_vip[e] = zone_name
vip_scores_df['Zone'] = vip_scores_df['energy'].map(energy_to_zone_vip)
vip_scores_unique_df = vip_scores_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
vip_scores_unique_df = vip_scores_unique_df.sort_values(by='VIP_Score', ascending=False).reset_index(drop=True)

# Coeficientes de regressão do PLS
reg_vet = pd.DataFrame(pls_model.coef_, columns=pls_model.feature_names_in_).T
reg_vet.insert(0, 'energy', reg_vet.index)
reg_vet = reg_vet.reset_index(drop=True)
reg_vet.columns = ['energy','Reg_coef']
reg_vet['Abs_Reg_coef'] = reg_vet['Reg_coef'].abs()
reg_vet = reg_vet.sort_values(by='Abs_Reg_coef', ascending=False).reset_index(drop=True)
energy_to_zone_reg = {}
for zone_name, start, end in spectral_cuts:
    for e in reg_vet['energy']:
        ef = float(e)
        if start <= ef <= end:
            energy_to_zone_reg[e] = zone_name
reg_vet['Zone'] = reg_vet['energy'].map(energy_to_zone_reg)
reg_vet_unique_df = reg_vet.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
reg_vet_unique_df = reg_vet_unique_df.sort_values(by='Abs_Reg_coef', ascending=False).reset_index(drop=True)

# vamos agora extrair as variaveis mais importantes atraves do método SHAP
# import shap

# # Para PLSRegression, usamos KernelExplainer porque não há explainer dedicado muito rápido
# explainer_pls = shap.KernelExplainer(plsda_results[3].predict, Xcalclass_prep)
# shap_values_pls = explainer_pls(Xcalclass_prep)

# shap_global_importance = pd.DataFrame({
#     'energy': Xpredclass_prep.columns,
#     'Mean_Abs_SHAP': np.abs(shap_values_pls.values).mean(axis=0)}) # tomando a importancia global como a media dos valores absolutos dos valores SHAP para cada feature
# shap_global_importance.sort_values(by='Mean_Abs_SHAP', ascending=False, inplace=True)

# # vamos gerar uma nova coluna em shap_global_importance com o nome da zona espectral correspondente de acordo com a lista spectral_cuts
# energy_to_zone_shap = {}
# for zone_name, start, end in spectral_cuts:
#     for i in shap_global_importance['energy']:
#         i_float = float(i)
#         if start <= i_float <= end:
#             energy_to_zone_shap[i] = zone_name
# shap_global_importance['Zone'] = shap_global_importance['energy'].map(energy_to_zone_shap)

# # agora vamos filtrar shap_global_importance para manter apenas as zonas espectrais únicas com maior SHAP score
# shap_unique_df = shap_global_importance.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
# shap_unique_df = shap_unique_df.sort_values(by='Mean_Abs_SHAP', ascending=False).reset_index(drop=True)
# shap_unique_df.to_csv('shap_bank_notes.csv', index=False, sep=';')
shap_unique_df = pd.read_csv('shap_soil_types.csv', sep=';') # loading previously saved shap_unique_df

# **bagging - covariance**

In [25]:
import explaining as exp

# LISTA DE SEMENTES A TESTAR
random_seeds = [0, 1, 2, 3]

all_results_cov = {}
training_samples = len(Xcalclass)

# LOOP: PROCESSAR CADA SEMENTE
y_predicted_numeric = plsda_results[5].iloc[:, -1] # predições numéricas do modelo

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando semente: {seed}")
    print(f"{'='*70}\n")
    # Bagging
    bags_result_seed = exp.bagging_predicates(
        zone_sums_df=zone_sums_df,
        y_predicted_numeric=y_predicted_numeric,
        predicates_df=predicates_quantiles[0],
        n_bags=10,
        #n_predicates_per_bag=40,
        n_samples_per_bag=int(training_samples*0.8), # 80 % da base para amostrar (convertido para int)
        min_samples_per_predicate=int(training_samples*0.2), # 20 % da base para limitar (convertido para int)
        replace=False,
        sample_bagging=True,
        predicate_bagging=False,
        random_seed=seed
    )
    # Inserir classe prevista
    for bag_name, pred_dict in bags_result_seed.items(): # iterando sobre cada bag
        for pred_rule, df_info in pred_dict.items():
            df_info['Class_Predicted'] = np.where(df_info['Predicted_Y'] >= 0.5, 'A', 'B') # binarizando com threshold 0.5, A = eut, B = dist
    # Calcular MI
    cov_results_dict_seed = exp.calculate_predicate_metrics(
        bags_result=bags_result_seed,
        metric='covariance', # covariance ou mutual_information
        threshold=0.01, # threshold para cortar predicados irrelevantes
        n_neighbors=5
    )
    # Salvar no dicionário principal
    all_results_cov[seed] = {
        'bags_result': bags_result_seed,
        'cov_results_dict': cov_results_dict_seed
    }

# CONSTRUÇÃO DE GRAFOS PARA MÚLTIPLAS SEMENTES (LOOP EXTERNO)
# Dicionário para armazenar grafos
graphs_by_seed = {}

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando Grafo - Semente: {seed}")
    print(f"{'='*70}\n")
    # Construir grafo para esta semente
    DG = exp.build_predicate_graphv2(
        bags_result=all_results_cov[seed]['bags_result'],
        predicate_ranking_dict=all_results_cov[seed]['cov_results_dict'],
        metric_column='Covariance',  # ou 'Covariance' se mudar a métrica
        random_state=seed,
        show_details=True
    )
    # Armazenar grafo
    graphs_by_seed[seed] = DG

# Calcular LRC usando a função pronta do explaining.py
lrc_cov_by_seed = {}
for seed in random_seeds:
    DG = graphs_by_seed[seed]
    lrc_cov_df_seed = exp.calculate_lrc_single_graph(DG, predicates_quantiles[0])
    lrc_cov_df_seed['Seed'] = seed  # Adicionar coluna com a semente
    lrc_cov_by_seed[seed] = lrc_cov_df_seed

# junando todas as colunas 'Node' de lrc_by_seed em um único dataframe
lrc_cov_all_seeds_df = pd.DataFrame()
for seed in random_seeds:
    lrc_cov_df_seed = lrc_cov_by_seed[seed].rename(columns={'Node': f'Predicate_Cov_Seed_{seed}'})
    lrc_cov_all_seeds_df = pd.concat([lrc_cov_all_seeds_df, lrc_cov_df_seed[[f'Predicate_Cov_Seed_{seed}']]], axis=1)

# vamos filtrar lrc_by_seed em cada semente para manter apenas as zonas espectrais únicas com maior LRC em um mesmo dataframe
lrc_cov_unique_by_seed = {}
for seed, lrc_df in lrc_cov_by_seed.items():
    lrc_cov_unique_df = lrc_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
    lrc_cov_unique_df = lrc_cov_unique_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
    lrc_cov_unique_by_seed[seed] = lrc_cov_unique_df

lrc_cov_all_seeds_df # exibindo o dataframe consolidado com predicados de todas as sementes

======================================================================
Processando semente: 0
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando semente: 1
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando semente: 2
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando semente: 3
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando Grafo - Semente: 0
======================================================================


Total de pares bidirecionais encontrados: 138
Removida aresta Fe ka > -3.73 -> Fe ka <= 4.61 (peso 5.5530)
Mantida aresta Fe ka <= 4.61 -> Fe ka > -3.73 (peso 8.2825)

======================================================================

Removida aresta Fe kb > -1.37 -> Fe kb <= 1.68 (peso 2.0518)
Mantida aresta Fe kb <= 1.68 -> Fe kb > -1.37 (peso 3.0809)

======================================================================

Removida aresta Mn <= 0.47 -> sum Fe > -0.41 (peso 0.1507)
Mantida aresta sum Fe > -0.41 -> Mn <= 0.47 (peso 0.3077)

======================================================================

Removida aresta Ti ka > -0.84 -> sum Fe > -0.41 (peso 0.3148)
Mantida aresta sum Fe > -0.41 -> Ti ka > -0.84 (peso 0.6123)

======================================================================

Removida aresta sum Fe <= 0.51 -> Mn <= 0.47 (peso 0.5894)
Mantida aresta Mn <= 0.47 -> sum Fe <= 0.51 (peso 0.7385)

======================================================================

Removida aresta Mn <= 0.47 -> Ti ka > -0.84 (peso 0.1495)
Mantida aresta Ti ka > -0.84 -> Mn <= 0.47 (peso 0.3011)

======================================================================

Removida aresta Ti ka > -0.84 -> sum Fe <= 0.51 (peso 0.2949)
Mantida aresta sum Fe <= 0.51 -> Ti ka > -0.84 (peso 0.4370)

======================================================================

Removida aresta Ca ka > -0.82 -> Ti ka > -0.37 (peso 0.3771)
Mantida aresta Ti ka > -0.37 -> Ca ka > -0.82 (peso 0.4984)

======================================================================

Removida aresta Ti ka > -0.37 -> Ca ka > -0.55 (peso 0.1297)
Mantida aresta Ca ka > -0.55 -> Ti ka > -0.37 (peso 0.2569)

======================================================================

Removida aresta Rh L + Ar <= 0.36 -> Ca ka > -0.55 (peso 0.2233)
Mantida aresta Ca ka > -0.55 -> Rh L + Ar <= 0.36 (peso 0.2354)

======================================================================

Removida aresta Ti kb > -0.42 -> Rh L + Ar <= 0.36 (peso 0.1103)
Mantida aresta Rh L + Ar <= 0.36 -> Ti kb > -0.42 (peso 0.2212)

======================================================================

Removida aresta Rh L + Ar <= 0.36 -> Mn > -0.33 (peso 0.2188)
Mantida aresta Mn > -0.33 -> Rh L + Ar <= 0.36 (peso 0.2257)

======================================================================

Removida aresta Fe ka <= -2.42 -> Rh L + Ar <= 0.36 (peso 0.1129)
Mantida aresta Rh L + Ar <= 0.36 -> Fe ka <= -2.42 (peso 0.2214)

======================================================================

Removida aresta Ca ka > -0.55 -> Ca ka > -0.20 (peso 0.1366)
Mantida aresta Ca ka > -0.20 -> Ca ka > -0.55 (peso 0.1371)

======================================================================

Removida aresta Mn > -0.33 -> Ti kb > -0.42 (peso 0.1078)
Mantida aresta Ti kb > -0.42 -> Mn > -0.33 (peso 0.2120)

======================================================================

Removida aresta Fe ka <= -2.42 -> Ti kb > -0.42 (peso 0.1038)
Mantida aresta Ti kb > -0.42 -> Fe ka <= -2.42 (peso 0.2124)

======================================================================

Removida aresta Ti kb > -0.42 -> Ti kb <= 0.48 (peso 0.1034)
Mantida aresta Ti kb <= 0.48 -> Ti kb > -0.42 (peso 0.1068)

======================================================================

Removida aresta Mn > -0.33 -> Si > -0.45 (peso 0.1046)
Mantida aresta Si > -0.45 -> Mn > -0.33 (peso 0.3209)

======================================================================

Removida aresta Mn > -0.33 -> Fe ka <= -2.42 (peso 0.1043)
Mantida aresta Fe ka <= -2.42 -> Mn > -0.33 (peso 0.1068)

======================================================================

Removida aresta Rh L + Ar > -0.26 -> Fe ka <= -2.42 (peso 0.2126)
Mantida aresta Fe ka <= -2.42 -> Rh L + Ar > -0.26 (peso 0.2155)

======================================================================

Removida aresta Ca ka > -0.20 -> Rh L + Ar > -0.26 (peso 0.1039)
Mantida aresta Rh L + Ar > -0.26 -> Ca ka > -0.20 (peso 0.3180)

======================================================================

Removida aresta Si > -0.45 -> Ca ka > -0.20 (peso 0.1043)
Mantida aresta Ca ka > -0.20 -> Si > -0.45 (peso 0.2121)

======================================================================

Removida aresta Si > -0.45 -> Fe ka <= -2.42 (peso 0.1053)
Mantida aresta Fe ka <= -2.42 -> Si > -0.45 (peso 0.1077)

======================================================================

Removida aresta Si <= 0.51 -> Fe ka <= -2.42 (peso 0.1008)
Mantida aresta Fe ka <= -2.42 -> Si <= 0.51 (peso 0.1025)

======================================================================

Removida aresta background4 > -0.29 -> Si <= 0.51 (peso 0.0952)
Mantida aresta Si <= 0.51 -> background4 > -0.29 (peso 0.2875)

======================================================================

Removida aresta Ti kb <= 0.48 -> Si <= 0.51 (peso 0.0979)
Mantida aresta Si <= 0.51 -> Ti kb <= 0.48 (peso 0.3917)

======================================================================

Removida aresta Si <= 0.51 -> sum Fe > -0.27 (peso 0.0933)
Mantida aresta sum Fe > -0.27 -> Si <= 0.51 (peso 0.0958)

======================================================================

Removida aresta Si <= 0.51 -> background4 <= 0.35 (peso 0.0950)
Mantida aresta background4 <= 0.35 -> Si <= 0.51 (peso 0.0955)

======================================================================

Removida aresta background4 > -0.29 -> Ti kb <= 0.48 (peso 0.0933)
Mantida aresta Ti kb <= 0.48 -> background4 > -0.29 (peso 0.4798)

======================================================================

Removida aresta background4 <= 0.35 -> sum Fe > -0.27 (peso 0.1828)
Mantida aresta sum Fe > -0.27 -> background4 <= 0.35 (peso 0.3658)

======================================================================

Removida aresta Cr > -0.26 -> sum Fe > -0.27 (peso 0.0882)
Mantida aresta sum Fe > -0.27 -> Cr > -0.26 (peso 0.3613)

======================================================================

Removida aresta background8 <= 0.27 -> Cu <= 0.25 (peso 0.1488)
Mantida aresta Cu <= 0.25 -> background8 <= 0.27 (peso 0.2185)

======================================================================

Removida aresta background8 > -0.22 -> Cu > -0.22 (peso 0.0723)
Mantida aresta Cu > -0.22 -> background8 > -0.22 (peso 0.3574)

======================================================================

Removida aresta Cu > -0.22 -> background8 <= 0.27 (peso 0.1420)
Mantida aresta background8 <= 0.27 -> Cu > -0.22 (peso 0.1422)

======================================================================

Removida aresta background8 <= 0.27 -> background8 > -0.22 (peso 0.1378)
Mantida aresta background8 > -0.22 -> background8 <= 0.27 (peso 0.2135)

======================================================================

Removida aresta background8 > -0.22 -> Ti ka > 0.45 (peso 0.0693)
Mantida aresta Ti ka > 0.45 -> background8 > -0.22 (peso 0.0720)

======================================================================

Removida aresta Ti kb > -0.23 -> Rh L + Ar > -0.21 (peso 0.1330)
Mantida aresta Rh L + Ar > -0.21 -> Ti kb > -0.23 (peso 0.2627)

======================================================================

Removida aresta Ca kb > -0.24 -> Rh L + Ar > -0.21 (peso 0.0574)
Mantida aresta Rh L + Ar > -0.21 -> Ca kb > -0.24 (peso 0.1339)

======================================================================

Removida aresta Si > -0.25 -> Rh L + Ar > -0.21 (peso 0.0669)
Mantida aresta Rh L + Ar > -0.21 -> Si > -0.25 (peso 0.1253)

======================================================================

Removida aresta Mn <= 0.22 -> Ti kb > -0.23 (peso 0.0611)
Mantida aresta Ti kb > -0.23 -> Mn <= 0.22 (peso 0.2583)

======================================================================

Removida aresta Ti ka > 0.45 -> Ti kb > -0.23 (peso 0.0656)
Mantida aresta Ti kb > -0.23 -> Ti ka > 0.45 (peso 0.1235)

======================================================================

Removida aresta Mn <= 0.22 -> Ca kb > -0.24 (peso 0.0594)
Mantida aresta Ca kb > -0.24 -> Mn <= 0.22 (peso 0.0599)

======================================================================

Removida aresta Si > -0.25 -> Mn <= 0.22 (peso 0.1250)
Mantida aresta Mn <= 0.22 -> Si > -0.25 (peso 0.2470)

======================================================================

Removida aresta Al > -0.27 -> Mn <= 0.22 (peso 0.0570)
Mantida aresta Mn <= 0.22 -> Al > -0.27 (peso 0.0604)

======================================================================

Removida aresta Rh L + Ar <= 0.27 -> Ca kb > -0.24 (peso 0.0587)
Mantida aresta Ca kb > -0.24 -> Rh L + Ar <= 0.27 (peso 0.1739)

======================================================================

Removida aresta Ca kb > -0.24 -> background4 > -0.17 (peso 0.0559)
Mantida aresta background4 > -0.17 -> Ca kb > -0.24 (peso 0.1104)

======================================================================

Removida aresta Rh L + Ar <= 0.27 -> Al > -0.27 (peso 0.0589)
Mantida aresta Al > -0.27 -> Rh L + Ar <= 0.27 (peso 0.1142)

======================================================================

Removida aresta background4 > -0.17 -> Rh L + Ar <= 0.27 (peso 0.1091)
Mantida aresta Rh L + Ar <= 0.27 -> background4 > -0.17 (peso 0.1131)

======================================================================

Removida aresta Ca kb <= 0.23 -> Rh L + Ar <= 0.27 (peso 0.0518)
Mantida aresta Rh L + Ar <= 0.27 -> Ca kb <= 0.23 (peso 0.1610)

======================================================================

Removida aresta Rh L + Ar <= 0.27 -> sum Fe <= 0.26 (peso 0.0537)
Mantida aresta sum Fe <= 0.26 -> Rh L + Ar <= 0.27 (peso 0.0592)

======================================================================

Removida aresta Al > -0.27 -> Si > -0.25 (peso 0.1145)
Mantida aresta Si > -0.25 -> Al > -0.27 (peso 0.1241)

======================================================================

Removida aresta sum Fe <= 0.26 -> background4 > -0.17 (peso 0.1098)
Mantida aresta background4 > -0.17 -> sum Fe <= 0.26 (peso 0.1129)

======================================================================

Removida aresta background4 > -0.17 -> Ca kb <= 0.23 (peso 0.0526)
Mantida aresta Ca kb <= 0.23 -> background4 > -0.17 (peso 0.0534)

======================================================================

Removida aresta Ti ka <= 0.92 -> Ti ka > 0.45 (peso 0.0489)
Mantida aresta Ti ka > 0.45 -> Ti ka <= 0.92 (peso 0.0556)

======================================================================

Removida aresta Ti kb <= 0.24 -> Ca kb <= 0.23 (peso 0.0991)
Mantida aresta Ca kb <= 0.23 -> Ti kb <= 0.24 (peso 0.0994)

======================================================================

Removida aresta Ti ka <= -0.37 -> K > 0.09 (peso 0.0298)
Mantida aresta K > 0.09 -> Ti ka <= -0.37 (peso 0.0504)

======================================================================

Removida aresta background2 <= 0.10 -> Ti ka <= -0.37 (peso 0.0215)
Mantida aresta Ti ka <= -0.37 -> background2 <= 0.10 (peso 0.0468)

======================================================================

Removida aresta Cr > -0.17 -> Cr <= 0.17 (peso 0.0433)
Mantida aresta Cr <= 0.17 -> Cr > -0.17 (peso 0.0446)

======================================================================

Removida aresta Cr > -0.17 -> Al > -0.14 (peso 0.0894)
Mantida aresta Al > -0.14 -> Cr > -0.17 (peso 0.1366)

======================================================================

Removida aresta Ca kb > -0.18 -> Cr > -0.17 (peso 0.0937)
Mantida aresta Cr > -0.17 -> Ca kb > -0.18 (peso 0.0945)

======================================================================

Removida aresta Ti kb <= 0.24 -> Ca kb > -0.18 (peso 0.0434)
Mantida aresta Ca kb > -0.18 -> Ti kb <= 0.24 (peso 0.0473)

======================================================================

Removida aresta Ca kb > -0.18 -> Al > -0.14 (peso 0.0429)
Mantida aresta Al > -0.14 -> Ca kb > -0.18 (peso 0.0872)

======================================================================

Removida aresta Fe kb <= -0.88 -> Ca kb > -0.18 (peso 0.0368)
Mantida aresta Ca kb > -0.18 -> Fe kb <= -0.88 (peso 0.0794)

======================================================================

Removida aresta Al > -0.14 -> Cu > -0.16 (peso 0.0855)
Mantida aresta Cu > -0.16 -> Al > -0.14 (peso 0.0857)

======================================================================

Removida aresta Al > -0.14 -> background3 <= 0.18 (peso 0.0427)
Mantida aresta background3 <= 0.18 -> Al > -0.14 (peso 0.0427)

======================================================================

Removida aresta background3 > -0.16 -> Cu > -0.16 (peso 0.0405)
Mantida aresta Cu > -0.16 -> background3 > -0.16 (peso 0.1660)

======================================================================

Removida aresta Cu > -0.16 -> Fe kb <= -0.88 (peso 0.0387)
Mantida aresta Fe kb <= -0.88 -> Cu > -0.16 (peso 0.0791)

======================================================================

Removida aresta Cr <= 0.17 -> background3 > -0.16 (peso 0.1232)
Mantida aresta background3 > -0.16 -> Cr <= 0.17 (peso 0.1261)

======================================================================

Removida aresta Ti ka <= 0.92 -> background3 > -0.16 (peso 0.0405)
Mantida aresta background3 > -0.16 -> Ti ka <= 0.92 (peso 0.0419)

======================================================================

Removida aresta background3 <= 0.18 -> Cr <= 0.17 (peso 0.0803)
Mantida aresta Cr <= 0.17 -> background3 <= 0.18 (peso 0.0851)

======================================================================

Removida aresta Fe kb <= -0.88 -> background3 <= 0.18 (peso 0.0386)
Mantida aresta background3 <= 0.18 -> Fe kb <= -0.88 (peso 0.0763)

======================================================================

Removida aresta Ti ka <= 0.92 -> background3 <= 0.18 (peso 0.0404)
Mantida aresta background3 <= 0.18 -> Ti ka <= 0.92 (peso 0.0410)

======================================================================

Removida aresta Al <= 0.29 -> Ca ka <= 0.76 (peso 0.0355)
Mantida aresta Ca ka <= 0.76 -> Al <= 0.29 (peso 0.0370)

======================================================================

Removida aresta Ca ka <= 0.76 -> background8 > -0.15 (peso 0.0338)
Mantida aresta background8 > -0.15 -> Ca ka <= 0.76 (peso 0.0348)

======================================================================

Removida aresta Al <= 0.29 -> Fe kb <= -0.88 (peso 0.0357)
Mantida aresta Fe kb <= -0.88 -> Al <= 0.29 (peso 0.0753)

======================================================================

Removida aresta Al <= 0.29 -> Ti ka <= 0.92 (peso 0.0310)
Mantida aresta Ti ka <= 0.92 -> Al <= 0.29 (peso 0.0341)

======================================================================

Removida aresta background4 <= 0.09 -> Al <= 0.29 (peso 0.0356)
Mantida aresta Al <= 0.29 -> background4 <= 0.09 (peso 0.0681)

======================================================================

Removida aresta Al <= 0.29 -> background8 <= 0.16 (peso 0.0371)
Mantida aresta background8 <= 0.16 -> Al <= 0.29 (peso 0.0645)

======================================================================

Removida aresta Al <= 0.29 -> Cu <= 0.15 (peso 0.0340)
Mantida aresta Cu <= 0.15 -> Al <= 0.29 (peso 0.0344)

======================================================================

Removida aresta background8 > -0.15 -> background4 <= 0.09 (peso 0.0347)

,Predicate_Cov_Seed_0,Predicate_Cov_Seed_1,Predicate_Cov_Seed_2,Predicate_Cov_Seed_3
0,Fe ka > -3.73,Fe ka > -3.73,Fe ka > -3.73,Fe ka <= 4.61
1,Fe ka <= 4.61,Fe ka <= 4.61,Fe ka <= 4.61,Fe ka > -3.73
2,Fe ka > -2.42,Fe ka > -2.42,Fe ka > -2.42,Fe ka > -2.42
3,Fe ka <= 2.41,Fe ka <= 2.41,Fe ka <= 2.41,Fe ka <= 2.41
4,Fe kb > -1.37,Fe kb <= 1.68,Fe kb > -1.37,Fe kb > -1.37
...,...,...,...,...
105,Ca ka <= -0.55,background4 <= -0.17,S <= 0.13,Fe ka + Ti ka <= -0.11
106,Fe ka + Ti ka <= 0.13,P <= 0.25,P > -0.19,Fe ka + Ti ka <= 0.13
107,Class_A,S > -0.09,Class_A,Cr <= -0.17
108,Class_B,Class_A,Class_B,Class_A
109,NaN,Class_B,NaN,Class_B

In [15]:
all_results_cov[0]['cov_results_dict']['Bag_5']

                 Predicate  Covariance
0            Fe ka <= 4.61    1.338195
1            Fe ka > -3.73    1.313949
2            Fe ka > -2.42    0.763178
3            Fe ka <= 2.41    0.610588
4            Fe kb <= 1.68    0.503311
..                     ...         ...
92               Al > 0.16    0.011069
93  Fe ka + Ti ka <= -0.11    0.011044
94             Mn <= -0.33    0.010717
95     background2 <= 0.07    0.010398
96           sum Fe > 0.26    0.010180

[97 rows x 2 columns]

In [16]:
# Somar LRCs de predicados equivalentes entre diferentes seeds
lrc_combined_list = []

for seed in random_seeds:
    lrc_df = lrc_cov_by_seed[seed].copy()
    lrc_combined_list.append(lrc_df) # o append adiciona o dataframe ao final da lista

# Concatenar todos os dataframes
lrc_all_seeds = pd.concat(lrc_combined_list, ignore_index=True) 

# Agrupar por predicado (Node) e somar as LRCs, mantendo Zone, Threshold e Operator
lrc_summed_df = lrc_all_seeds.groupby('Node').agg({ # o .agg pode ser usado para aplicar múltiplas funções de agregação
    'Local_Reaching_Centrality': 'mean', # sum = somando as LRCs, poderia ser média ou outro agregado
    'Zone': 'first',
    'Threshold': 'first',
    'Operator': 'first'
}).reset_index()

# Ordenar pelo valor de LRC somado (maior para menor)
lrc_summed_df = lrc_summed_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
# vamoss pegar so os valore sunicos de lrc_summed_df baseado na zona espectral
lrc_summed_unique_df_cov = lrc_summed_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
lrc_summed_unique_df_cov = lrc_summed_unique_df_cov.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
lrc_summed_unique_df_cov

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator
0,Fe ka > -3.73,13.733030,Fe ka,-3.73,>
1,Fe kb > -1.37,5.059772,Fe kb,-1.37,>
2,Mn > -0.47,1.839092,Mn,-0.47,>
3,sum Fe > -0.41,1.743143,sum Fe,-0.41,>
4,Ti ka > -0.84,1.469125,Ti ka,-0.84,>
5,Ca ka > -0.82,1.193031,Ca ka,-0.82,>
6,background4 > -0.29,1.144435,background4,-0.29,>
7,Rh L + Ar <= 0.36,1.066647,Rh L + Ar,0.36,<=
8,Ti kb > -0.42,1.045407,Ti kb,-0.42,>
9,Si > -0.45,1.019421,Si,-0.45,>
10,Cr <= 0.28,0.873572,Cr,0.28,<=
11,Cu <= 0.25,0.739556,Cu,0.25,<=
12,background8 > -0.22,0.690094,background8,-0.22,>
13,Al > -0.27,0.538662,Al,-0.27,>
14,Ca kb > -0.24,0.470632,Ca kb,-0.24,>
15,background3 > -0.16,0.381692,background3,-0.16,>
16,background1 > -0.10,0.351268,background1,-0.10,>
17,K > 0.09,0.319947,K,0.09,>
18,background2 > -0.09,0.287193,background2,-0.09,>
19,background7 > -0.15,0.252737,background7,-0.15,>
20,background6 <= 0.18,0.235261,background6,0.18,<=
21,P > 0.15,0.218932,P,0.15,>
22,S > -0.12,0.212900,S,-0.12,>
23,Fe ka + Ti ka <= -0.11,0.194804,Fe ka + Ti ka,-0.11,<=
24,Class_A,0.000000,None,None,None

# **Perturbation**

In [17]:
import explaining as exp

# LISTA DE SEMENTES A TESTAR
random_seeds = [0, 1, 2, 3]

all_results_pert = {}
training_samples = len(Xcalclass)

# LOOP: PROCESSAR CADA SEMENTE
y_predicted_numeric = plsda_results[5].iloc[:, -1] # predições numéricas do modelo

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando semente: {seed}")
    print(f"{'='*70}\n")
    # Bagging
    bags_result_seed = exp.bagging_predicates(
        zone_sums_df=zone_sums_df,
        y_predicted_numeric=y_predicted_numeric,
        predicates_df=predicates_quantiles[0],
        n_bags=10,
        #n_predicates_per_bag=40,
        n_samples_per_bag=int(training_samples*0.8), # 80 % da base para amostrar (convertido para int)
        min_samples_per_predicate=int(training_samples*0.2), # 20 % da base para limitar (convertido para int)
        replace=False,
        sample_bagging=True,
        predicate_bagging=False,
        random_seed=seed
    )
    # Inserir classe prevista
    for bag_name, pred_dict in bags_result_seed.items(): # iterando sobre cada bag
        for pred_rule, df_info in pred_dict.items():
            df_info['Class_Predicted'] = np.where(df_info['Predicted_Y'] >= 0.5, 'A', 'B') # binarizando com threshold 0.5, A = eut, B = dist

    pert_results_seed = exp.calculate_predicate_perturbation(
        estimator=pls_model,
        Xcalclass_prep=Xcalclass_prep,
        folds_struct=bags_result_seed,
        predicates_df=predicates_quantiles[0],
        spectral_cuts=spectral_cuts,
        #perturbation_value=0,
        perturbation_mode='mean', # valores entre 'mean' ou 'min'
        stats_source='full', # full indica usar todas as amostras para calcular estatísticas enquanto que 'fold' usa apenas as amostras do fold atual
        metric='mean_abs_diff',   # Média com sinal (pode ser negativo)
        verbose=True
    )

    # Remove todos os valores iguais a zero de todos os bags em perm_results[bag]["Permutation"] e salva como perm_results_thresholded
    # pert_results_seed_thresholded = {}
    # for bag, df in perm_results_seed.items():
    #     # Verifica se é um DataFrame e se a coluna 'Permutation' existe
    #     if isinstance(df, pd.DataFrame) and 'Permutation' in df.columns:
    #         filtered_df = df[df['Permutation'] > 0].copy()
    #         pert_results_seed_thresholded[bag] = filtered_df
    #     else:
    #         # Se não for DataFrame esperado, apenas copia
    #         pert_results_seed_thresholded[bag] = df

    # Salvar no dicionário principal
    all_results_pert[seed] = {
        'bags_result': bags_result_seed,
        'pert_results_dict': pert_results_seed
    }

# CONSTRUÇÃO DE GRAFOS PARA MÚLTIPLAS SEMENTES (LOOP EXTERNO)
# Dicionário para armazenar grafos
graphs_pert_by_seed = {}

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando Grafo - Semente: {seed}")
    print(f"{'='*70}\n")
    # Construir grafo para esta semente
    DG = exp.build_predicate_graphv2(
        bags_result=all_results_pert[seed]['bags_result'],
        predicate_ranking_dict=all_results_pert[seed]['pert_results_dict'],
        metric_column='Perturbation',  # ou 'Covariance' se mudar a métrica
        random_state=seed,
        show_details=True
    )
    # Armazenar grafo
    graphs_pert_by_seed[seed] = DG  

# Calcular LRC usando a função pronta do explaining.py
lrc_pert_by_seed = {}
for seed in random_seeds:
    DG = graphs_pert_by_seed[seed]
    lrc_pert_df_seed = exp.calculate_lrc_single_graph(DG, predicates_quantiles[0])
    lrc_pert_df_seed['Seed'] = seed  # Adicionar coluna com a semente
    lrc_pert_by_seed[seed] = lrc_pert_df_seed

# junando todas as colunas 'Node' de lrc_by_seed em um único dataframe
lrc_pert_all_seeds_df = pd.DataFrame()
for seed in random_seeds:
    lrc_pert_df_seed = lrc_pert_by_seed[seed].rename(columns={'Node': f'Predicate_pert_Seed_{seed}'})
    lrc_pert_all_seeds_df = pd.concat([lrc_pert_all_seeds_df, lrc_pert_df_seed[[f'Predicate_pert_Seed_{seed}']]], axis=1)

# vamos filtrar lrc_by_seed em cada semente para manter apenas as zonas espectrais únicas com maior LRC em um mesmo dataframe
lrc_pert_unique_by_seed = {}
for seed, lrc_df in lrc_pert_by_seed.items():
    lrc_pert_unique_df = lrc_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
    lrc_pert_unique_df = lrc_pert_unique_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
    lrc_pert_unique_by_seed[seed] = lrc_pert_unique_df

lrc_pert_all_seeds_df # exibindo o dataframe consolidado com predicados de todas as sementes

======================================================================
Processando semente: 0
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
======================================================================
PERTURBATION IMPORTANCE PARA PREDICADOS
======================================================================
Modo de perturbação: mean
Fonte das estatísticas: full
Métrica: mean_abs_diff
Total de folds: 10


[Bag_1] Processando 150 predicados...
  Predicado: background1 > -0.10 (n=323)
    Zona: 17 colunas
    Importance: 0.000031
  Predicado: background1 <= -0.08 (n=144)
    Zona: 17 colunas
    Importance: 0.000033
  Predicado: background1 > -0.08 (n=256)
    Zona: 17 colunas
    Importance: 0.000031
  Predicado: background1 <= 0.09 (n=227)
    Zona: 17 colunas
    Importance: 0.000028
  Predicado: background1 > 0.09 (n=173)
    Zona: 17 colunas
    Importance: 0.000036
  Predicado: background1 <= 0.12 (n=314)
    Zona: 17 colunas
    Importance: 0.000029
  Predicado: Al > -0.27 (n=322)
    Zona: 15 colunas
    Importance: 0.003753
  Predicado: Al <= -0.14 (n=155)
    Zona: 15 colunas
    Importance: 0.005283
  Predicado: Al > -0.14 (n=245)
    Zona: 15 colunas
    Importance: 0.003925
  Predicado: Al <= 0.16 (n=238)
    Zona: 15 colunas
    Importance: 0.003795
  Predicado: Al > 0.16 (n=162)
    Zona: 15 colunas
    Importance: 0.005415
  Predicado: Al <= 0.29 (n=314)
    Zona: 15 colunas
    Importance: 0.003632
  Predicado: Si > -0.45 (n=323)
    Zona: 12 colunas
    Importance: 0.001785
  Predicado: Si <= -0.25 (n=154)
    Zona: 12 colunas
    Importance: 0.002421
  Predicado: Si > -0.25 (n=246)
    Zona: 12 colunas
    Importance: 0.001845
  Predicado: Si <= 0.18 (n=233)
    Zona: 12 colunas
    Importance: 0.001756
  Predicado: Si > 0.18 (n=167)
    Zona: 12 colunas
    Importance: 0.002501
  Predicado: Si <= 0.51 (n=322)
    Zona: 12 colunas
    Importance: 0.001622
  Predicado: P > -0.19 (n=319)
    Zona: 17 colunas
    Importance: 0.000773
  Predicado: P <= -0.13 (n=157)
    Zona: 17 colunas
    Importance: 0.000759
  Predicado: P > -0.13 (n=243)
    Zona: 17 colunas
    Importance: 0.000839
  Predicado: P <= 0.15 (n=239)
    Zona: 17 colunas
    Importance: 0.000629
  Predicado: P > 0.15 (n=161)
    Zona: 17 colunas
    Importance: 0.001073
  Predicado: P <= 0.25 (n=321)
    Zona: 17 colunas
    Importance: 0.000642
  Predicado: S > -0.12 (n=314)
    Zona: 13 colunas
    Importance: 0.000085
  Predicado: S <= -0.09 (n=151)
    Zona: 13 colunas
    Importance: 0.000095
  Predicado: S > -0.09 (n=249)
    Zona: 13 colunas
    Importance: 0.000089
  Predicado: S <= 0.09 (n=246)
    Zona: 13 colunas
    Importance: 0.000076
  Predicado: S > 0.09 (n=154)
    Zona: 13 colunas
    Importance: 0.000116
  Predicado: S <= 0.13 (n=314)
    Zona: 13 colunas
    Importance: 0.000075
  Predicado: background2 > -0.09 (n=321)
    Zona: 6 colunas
    Importance: 0.000070
  Predicado: background2 <= -0.06 (n=164)
    Zona: 6 colunas
    Importance: 0.000080
  Predicado: background2 > -0.06 (n=236)
    Zona: 6 colunas
    Importance: 0.000072
  Predicado: background2 <= 0.07 (n=242)
    Zona: 6 colunas
    Importance: 0.000065
  Predicado: background2 > 0.07 (n=158)
    Zona: 6 colunas
    Importance: 0.000091
  Predicado: background2 <= 0.10 (n=312)
    Zona: 6 colunas
    Importance: 0.000063
  Predicado: Rh L + Ar > -0.26 (n=320)
    Zona: 33 colunas
    Importance: 0.003651
  Predicado: Rh L + Ar <= -0.21 (n=145)
    Zona: 33 colunas
    Importance: 0.004243
  Predicado: Rh L + Ar > -0.21 (n=255)
    Zona: 33 colunas
    Importance: 0.003648
  Predicado: Rh L + Ar <= 0.27 (n=238)
    Zona: 33 colunas
    Importance: 0.003440
  Predicado: Rh L + Ar > 0.27 (n=162)
    Zona: 33 colunas
    Importance: 0.004486
  Predicado: Rh L + Ar <= 0.36 (n=317)
    Zona: 33 colunas
    Importance: 0.003490
  Predicado: K > -0.20 (n=319)
    Zona: 16 colunas
    Importance: 0.001625
  Predicado: K <= -0.13 (n=160)
    Zona: 16 colunas
    Importance: 0.001793
  Predicado: K > -0.13 (n=240)
    Zona: 16 colunas
    Importance: 0.001763
  Predicado: K <= 0.09 (n=243)
    Zona: 16 colunas
    Importance: 0.001356
  Predicado: K > 0.09 (n=157)
    Zona: 16 colunas
    Importance: 0.002423
  Predicado: K <= 0.17 (n=319)
    Zona: 16 colunas
    Importance: 0.001178
  Predicado: Ca ka > -0.82 (n=321)
    Zona: 16 colunas
    Importance: 0.048085
  Predicado: Ca ka <= -0.55 (n=160)
    Zona: 16 colunas
    Importance: 0.050555
  Predicado: Ca ka > -0.55 (n=240)
    Zona: 16 colunas
    Importance: 0.050480
  Predicado: Ca ka <= -0.20 (n=239)
    Zona: 16 colunas
    Importance: 0.041545
  Predicado: Ca ka > -0.20 (n=161)
    Zona: 16 colunas
    Importance: 0.063818
  Predicado: Ca ka <= 0.76 (n=316)
    Zona: 16 colunas
    Importance: 0.035719
  Predicado: Ca kb > -0.24 (n=321)
    Zona: 16 colunas
    Importance: 0.002487
  Predicado: Ca kb <= -0.18 (n=153)
    Zona: 16 colunas
    Importance: 0.002921
  Predicado: Ca kb > -0.18 (n=247)
    Zona: 16 colunas
    Importance: 0.002557
  Predicado: Ca kb <= 0.12 (n=236)
    Zona: 16 colunas
    Importance: 0.002234
  Predicado: Ca kb > 0.12 (n=164)
    Zona: 16 colunas
    Importance: 0.003361
  Predicado: Ca kb <= 0.23 (n=319)
    Zona: 16 colunas
    Importance: 0.001927
  Predicado: background3 > -0.16 (n=329)
    Zona: 12 colunas
    Importance: 0.000362
  Predicado: background3 <= -0.09 (n=160)
    Zona: 12 colunas
    Importance: 0.000509
  Predicado: background3 > -0.09 (n=240)
    Zona: 12 colunas
    Importance: 0.000385
  Predicado: background3 <= 0.12 (n=235)
    Zona: 12 colunas
    Importance: 0.000388
  Predicado: background3 > 0.12 (n=165)
    Zona: 12 colunas
    Importance: 0.000501
  Predicado: background3 <= 0.18 (n=316)
    Zona: 12 colunas
    Importance: 0.000379
  Predicado: Ti ka > -0.84 (n=322)
    Zona: 15 colunas
    Importance: 0.038365
  Predicado: Ti ka <= -0.37 (n=156)
    Zona: 15 colunas
    Importance: 0.056723
  Predicado: Ti ka > -0.37 (n=244)
    Zona: 15 colunas
    Importance: 0.040763
  Predicado: Ti ka <= 0.45 (n=236)
    Zona: 15 colunas
    Importance: 0.041191
  Predicado: Ti ka > 0.45 (n=164)
    Zona: 15 colunas
    Importance: 0.055328
  Predicado: Ti ka <= 0.92 (n=313)
    Zona: 15 colunas
    Importance: 0.038388
  Predicado: background4 > -0.29 (n=320)
    Zona: 5 colunas
    Importance: 0.000109
  Predicado: background4 <= -0.17 (n=153)
    Zona: 5 colunas
    Importance: 0.000140
  Predicado: background4 > -0.17 (n=247)
    Zona: 5 colunas
    Importance: 0.000114
  Predicado: background4 <= 0.09 (n=235)
    Zona: 5 colunas
    Importance: 0.000104
  Predicado: background4 > 0.09 (n=165)
    Zona: 5 colunas
    Importance: 0.000152
  Predicado: background4 <= 0.35 (n=315)
    Zona: 5 colunas
    Importance: 0.000100
  Predicado: Ti kb > -0.42 (n=321)
    Zona: 19 colunas
    Importance: 0.003932
  Predicado: Ti kb <= -0.23 (n=158)
    Zona: 19 colunas
    Importance: 0.005416
  Predicado: Ti kb > -0.23 (n=242)
    Zona: 19 colunas
    Importance: 0.004226
  Predicado: Ti kb <= 0.24 (n=236)
    Zona: 19 colunas
    Importance: 0.004096
  Predicado: Ti kb > 0.24 (n=164)
    Zona: 19 colunas
    Importance: 0.005560
  Predicado: Ti kb <= 0.48 (n=318)
    Zona: 19 colunas
    Importance: 0.003930
  Predicado: Cr > -0.26 (n=321)
    Zona: 33 colunas
    Importance: 0.000967
  Predicado: Cr <= -0.17 (n=155)
    Zona: 33 colunas
    Importance: 0.001204
  Predicado: Cr > -0.17 (n=245)
    Zona: 33 colunas
    Importance: 0.000997
  Predicado: Cr <= 0.17 (n=233)
    Zona: 33 colunas
    Importance: 0.001164
  Predicado: Cr > 0.17 (n=167)
    Zona: 33 colunas
    Importance: 0.000956
  Predicado: Cr <= 0.28 (n=312)
    Zona: 33 colunas
    Importance: 0.001121
  Predicado: Mn > -0.47 (n=322)
    Zona: 18 colunas
    Importance: 0.012002
  Predicado: Mn <= -0.33 (n=153)
    Zona: 18 colunas
    Importance: 0.013853
  Predicado: Mn > -0.33 (n=247)
    Zona: 18 colunas
    Importance: 0.012230
  Predicado: Mn <= 0.22 (n=235)
    Zona: 18 colunas
    Importance: 0.010738
  Predicado: Mn > 0.22 (n=165)
    Zona: 18 colunas
    Importance: 0.015859
  Predicado: Mn <= 0.47 (n=315)
    Zona: 18 colunas
    Importance: 0.009643
  Predicado: Fe ka > -3.73 (n=320)
    Zona: 34 colunas
    Importance: 0.336465
  Predicado: Fe ka <= -2.42 (n=157)
    Zona: 34 colunas
    Importance: 0.419044
  Predicado: Fe ka > -2.42 (n=243)
    Zona: 34 colunas
    Importance: 0.344605
  Predicado: Fe ka <= 2.41 (n=238)
    Zona: 34 colunas
    Importance: 0.327425
  Predicado: Fe ka > 2.41 (n=162)
    Zona: 34 colunas
    Importance: 0.441986
  Predicado: Fe ka <= 4.61 (n=316)
    Zona: 34 colunas
    Importance: 0.333821
  Predicado: Fe kb > -1.37 (n=320)
    Zona: 26 colunas
    Importance: 0.041090
  Predicado: Fe kb <= -0.88 (n=158)
    Zona: 26 colunas
    Importance: 0.051664
  Predicado: Fe kb > -0.88 (n=242)
    Zona: 26 colunas
    Importance: 0.042071
  Predicado: Fe kb <= 0.90 (n=237)
    Zona: 26 colunas
    Importance: 0.040300
  Predicado: Fe kb > 0.90 (n=163)
    Zona: 26 colunas
    Importance: 0.053945
  Predicado: Fe kb <= 1.68 (n=315)
    Zona: 26 colunas
    Importance: 0.041152
  Predicado: background5 > -0.15 (n=329)
    Zona: 31 colunas
    Importance: 0.001207
  Predicado: background5 <= -0.10 (n=159)
    Zona: 31 colunas
    Importance: 0.001624
  Predicado: background5 > -0.10 (n=241)
    Zona: 31 colunas
    Importance: 0.001288
  Predicado: background5 <= 0.12 (n=230)
    Zona: 31 colunas
    Importance: 0.001259
  Predicado: background5 > 0.12 (n=170)
    Zona: 31 colunas
    Importance: 0.001641
  Predicado: background5 <= 0.16 (n=317)
    Zona: 31 colunas
    Importance: 0.001214
  Predicado: Cu > -0.22 (n=322)
    Zona: 15 colunas
    Importance: 0.001461
  Predicado: Cu <= -0.16 (n=151)
    Zona: 15 colunas
    Importance: 0.001709
  Predicado: Cu > -0.16 (n=249)
    Zona: 15 colunas
    Importance: 0.001489
  Predicado: Cu <= 0.15 (n=233)
    Zona: 15 colunas
    Importance: 0.001399
  Predicado: Cu > 0.15 (n=167)
    Zona: 15 colunas
    Importance: 0.001814
  Predicado: Cu <= 0.25 (n=316)
    Zona: 15 colunas
    Importance: 0.001394
  Predicado: background6 > -0.16 (n=314)
    Zona: 125 colunas
    Importance: 0.005668
  Predicado: background6 <= -0.13 (n=163)
    Zona: 125 colunas
    Importance: 0.007296
  Predicado: background6 > -0.13 (n=237)
    Zona: 125 colunas
    Importance: 0.005994
  Predicado: background6 <= 0.14 (n=248)
    Zona: 125 colunas
    Importance: 0.005489
  Predicado: background6 > 0.14 (n=152)
    Zona: 125 colunas
    Importance: 0.008213
  Predicado: background6 <= 0.18 (n=319)
    Zona: 125 colunas
    Importance: 0.005517
  Predicado: Fe ka + Ti ka > -0.15 (n=317)
    Zona: 23 colunas
    Importance: 0.000987
  Predicado: Fe ka + Ti ka <= -0.11 (n=149)
    Zona: 23 colunas
    Importance: 0.001415
  Predicado: Fe ka + Ti ka > -0.11 (n=251)
    Zona: 23 colunas
    Importance: 0.001010
  Predicado: Fe ka + Ti ka <= 0.13 (n=245)
    Zona: 23 colunas
    Importance: 0.001056
  Predicado: Fe ka + Ti ka > 0.13 (n=155)
    Zona: 23 colunas
    Importance: 0.001328
  Predicado: Fe ka + Ti ka <= 0.17 (n=319)
    Zona: 23 colunas
    Importance: 0.001057
  Predicado: background7 > -0.15 (n=326)
    Zona: 71 colunas
    Importance: 0.002417
  Predicado: background7 <= -0.12 (n=152)
    Zona: 71 colunas
    Importance: 0.003077
  Predicado: background7 > -0.12 (n=248)
    Zona: 71 colunas
    Importance: 0.002438
  Predicado: background7 <= 0.12 (n=244)
    Zona: 71 colunas
    Importance: 0.002322
  Predicado: background7 > 0.12 (n=156)
    Zona: 71 colunas
    Importance: 0.003242
  Predicado: background7 <= 0.16 (n=321)
    Zona: 71 colunas
    Importance: 0.002320
  Predicado: sum Fe > -0.41 (n=320)
    Zona: 28 colunas
    Importance: 0.003371
  Predicado: sum Fe <= -0.27 (n=155)
    Zona: 28 colunas
    Importance: 0.004052
  Predicado: sum Fe > -0.27 (n=245)
    Zona: 28 colunas
    Importance: 0.003425
  Predicado: sum Fe <= 0.26 (n=235)
    Zona: 28 colunas
    Importance: 0.003212
  Predicado: sum Fe > 0.26 (n=165)
    Zona: 28 colunas
    Importance: 0.004318
  Predicado: sum Fe <= 0.51 (n=320)
    Zona: 28 colunas
    Importance: 0.003220
  Predicado: background8 > -0.22 (n=324)
    Zona: 96 colunas
    Importance: 0.000565
  Predicado: background8 <= -0.15 (n=151)
    Zona: 96 colunas
    Importance: 0.000452
  Predicado: background8 > -0.15 (n=249)
    Zona: 96 colunas
    Importance: 0.000557
  Predicado: background8 <= 0.16 (n=232)
    Zona: 96 colunas
    Importance: 0.000536
  Predicado: background8 > 0.16 (n=168)
    Zona: 96 colunas
    Importance: 0.000492
  Predicado: background8 <= 0.27 (n=323)
    Zona: 96 colunas
    Importance: 0.000541

[Bag_2] Processando 150 predicados...
  Predicado: background1 > -0.10 (n=313)
    Zona: 17 colunas
    Importance: 0.000032
  Predicado: background1 <= -0.08 (n=155)
    Zona: 17 colunas
    Importance: 0.000033
  Predicado: background1 > -0.08 (n=245)
    Zona: 17 colunas
    Importance: 0.000032
  Predicado: background1 <= 0.09 (n=242)
    Zona: 17 colunas
    Importance: 0.000029
  Predicado: background1 > 0.09 (n=158)
    Zona: 17 colunas
    Importance: 0.000039
  Predicado: background1 <= 0.12 (n=320)
    Zona: 17 colunas
    Importance: 0.000029
  Predicado: Al > -0.27 (n=320)
    Zona: 15 colunas
    Importance: 0.003699
  Predicado: Al <= -0.14 (n=166)
    Zona: 15 colunas
    Importance: 0.005154
  Predicado: Al > -0.14 (n=234)
    Zona: 15 colunas
    Importance: 0.003860
  Predicado: Al <= 0.16 (n=249)
    Zona: 15 colunas
    Importance: 0.003756
  Predicado: Al > 0.16 (n=151)
    Zona: 15 colunas
    Importance: 0.005454
  Predicado: Al <= 0.29 (n=320)
    Zona: 15 colunas
    Importance: 0.003577
  Predicado: Si > -0.45 (n=322)
    Zona: 12 colunas
    Importance: 0.001832
  Predicado: Si <= -0.25 (n=164)
    Zona: 12 colunas
    Importance: 0.002335
  Predicado: Si > -0.25 (n=236)
    Zona: 12 colunas
    Importance: 0.001908
  Predicado: Si <= 0.18 (n=244)
    Zona: 12 colunas
    Importance: 0.001720
  Predicado: Si > 0.18 (n=156)
    Zona: 12 colunas
    Importance: 0.002649
  Predicado: Si <= 0.51 (n=321)
    Zona: 12 colunas
    Importance: 0.001619
  Predicado: P > -0.19 (n=326)
    Zona: 17 colunas
    Importance: 0.000792
  Predicado: P <= -0.13 (n=155)
    Zona: 17 colunas
    Importance: 0.000731
  Predicado: P > -0.13 (n=245)
    Zona: 17 colunas
    Importance: 0.000876
  Predicado: P <= 0.15 (n=238)
    Zona: 17 colunas
    Importance: 0.000603
  Predicado: P > 0.15 (n=162)
    Zona: 17 colunas
    Importance: 0.001139
  Predicado: P <= 0.25 (n=315)
    Zona: 17 colunas
    Importance: 0.000620
  Predicado: S > -0.12 (n=315)
    Zona: 13 colunas
    Importance: 0.000086
  Predicado: S <= -0.09 (n=155)
    Zona: 13 colunas
    Importance: 0.000101
  Predicado: S > -0.09 (n=245)
    Zona: 13 colunas
    Importance: 0.000091
  Predicado: S <= 0.09 (n=248)
    Zona: 13 colunas
    Importance: 0.000081
  Predicado: S > 0.09 (n=152)
    Zona: 13 colunas
    Importance: 0.000118
  Predicado: S <= 0.13 (n=317)
    Zona: 13 colunas
    Importance: 0.000078
  Predicado: background2 > -0.09 (n=320)
    Zona: 6 colunas
    Importance: 0.000072
  Predicado: background2 <= -0.06 (n=163)
    Zona: 6 colunas
    Importance: 0.000082
  Predicado: background2 > -0.06 (n=237)
    Zona: 6 colunas
    Importance: 0.000074
  Predicado: background2 <= 0.07 (n=252)
    Zona: 6 colunas
    Importance: 0.000065
  Predicado: background2 > 0.07 (n=148)
    Zona: 6 colunas
    Importance: 0.000099
  Predicado: background2 <= 0.10 (n=318)
    Zona: 6 colunas
    Importance: 0.000064
  Predicado: Rh L + Ar > -0.26 (n=312)
    Zona: 33 colunas
    Importance: 0.003689
  Predicado: Rh L + Ar <= -0.21 (n=154)
    Zona: 33 colunas
    Importance: 0.004342
  Predicado: Rh L + Ar > -0.21 (n=246)
    Zona: 33 colunas
    Importance: 0.003685
  Predicado: Rh L + Ar <= 0.27 (n=243)
    Zona: 33 colunas
    Importance: 0.003567
  Predicado: Rh L + Ar > 0.27 (n=157)
    Zona: 33 colunas
    Importance: 0.004511
  Predicado: Rh L + Ar <= 0.36 (n=320)
    Zona: 33 colunas
    Importance: 0.003577
  Predicado: K > -0.20 (n=317)
    Zona: 16 colunas
    Importance: 0.001627
  Predicado: K <= -0.13 (n=155)
    Zona: 16 colunas
    Importance: 0.001852
  Predicado: K > -0.13 (n=245)
    Zona: 16 colunas
    Importance: 0.001748
  Predicado: K <= 0.09 (n=240)
    Zona: 16 colunas
    Importance: 0.001370
  Predicado: K > 0.09 (n=160)
    Zona: 16 colunas
    Importance: 0.002416
  Predicado: K <= 0.17 (n=315)
    Zona: 16 colunas
    Importance: 0.001193
  Predicado: Ca ka > -0.82 (n=324)
    Zona: 16 colunas
    Importance: 0.046870
  Predicado: Ca ka <= -0.55 (n=152)
    Zona: 16 colunas
    Importance: 0.050909
  Predicado: Ca ka > -0.55 (n=248)
    Zona: 16 colunas
    Importance: 0.048446
  Predicado: Ca ka <= -0.20 (n=233)
    Zona: 16 colunas
    Importance: 0.040946
  Predicado: Ca ka > -0.20 (n=167)
    Zona: 16 colunas
    Importance: 0.061151
  Predicado: Ca ka <= 0.76 (n=315)
    Zona: 16 colunas
    Importance: 0.034626
  Predicado: Ca kb > -0.24 (n=316)
    Zona: 16 colunas
    Importance: 0.002455
  Predicado: Ca kb <= -0.18 (n=151)
    Zona: 16 colunas
    Importance: 0.002989
  Predicado: Ca kb > -0.18 (n=249)
    Zona: 16 colunas
    Importance: 0.002504
  Predicado: Ca kb <= 0.12 (n=240)
    Zona: 16 colunas
    Importance: 0.002227
  Predicado: Ca kb > 0.12 (n=160)
    Zona: 16 colunas
    Importance: 0.003377
  Predicado: Ca kb <= 0.23 (n=319)
    Zona: 16 colunas
    Importance: 0.001951
  Predicado: background3 > -0.16 (n=325)
    Zona: 12 colunas
    Importance: 0.000353
  Predicado: background3 <= -0.09 (n=170)
    Zona: 12 colunas
    Importance: 0.000512
  Predicado: background3 > -0.09 (n=230)
    Zona: 12 colunas
    Importance: 0.000375
  Predicado: background3 <= 0.12 (n=245)
    Zona: 12 colunas
    Importance: 0.000398
  Predicado: background3 > 0.12 (n=155)
    Zona: 12 colunas
    Importance: 0.000489
  Predicado: background3 <= 0.18 (n=324)
    Zona: 12 colunas
    Importance: 0.000386
  Predicado: Ti ka > -0.84 (n=322)
    Zona: 15 colunas
    Importance: 0.039023
  Predicado: Ti ka <= -0.37 (n=163)
    Zona: 15 colunas
    Importance: 0.055885
  Predicado: Ti ka > -0.37 (n=237)
    Zona: 15 colunas
    Importance: 0.041958
  Predicado: Ti ka <= 0.45 (n=238)
    Zona: 15 colunas
    Importance: 0.041922
  Predicado: Ti ka > 0.45 (n=162)
    Zona: 15 colunas
    Importance: 0.056024
  Predicado: Ti ka <= 0.92 (n=317)
    Zona: 15 colunas
    Importance: 0.039254
  Predicado: background4 > -0.29 (n=317)
    Zona: 5 colunas
    Importance: 0.000107
  Predicado: background4 <= -0.17 (n=162)
    Zona: 5 colunas
    Importance: 0.000138
  Predicado: background4 > -0.17 (n=238)
    Zona: 5 colunas
    Importance: 0.000112
  Predicado: background4 <= 0.09 (n=246)
    Zona: 5 colunas
    Importance: 0.000103
  Predicado: background4 > 0.09 (n=154)
    Zona: 5 colunas
    Importance: 0.000154

,Predicate_pert_Seed_0,Predicate_pert_Seed_1,Predicate_pert_Seed_2,Predicate_pert_Seed_3
0,Fe ka > 2.41,Fe ka > 2.41,Fe ka > 2.41,Fe ka > 2.41
1,Fe ka <= -2.42,Fe ka <= -2.42,Fe ka <= -2.42,Fe ka <= -2.42
2,Fe ka <= 4.61,Fe ka > -2.42,Fe ka <= 4.61,Fe ka > -2.42
3,Fe ka <= 2.41,Fe ka <= 4.61,Fe ka > -2.42,Fe ka <= 4.61
4,Fe ka > -2.42,Fe ka > -3.73,Fe ka <= 2.41,Fe ka <= 2.41
...,...,...,...,...
147,background1 > -0.10,background1 > -0.10,background1 > -0.10,background1 > -0.10
148,background1 <= 0.12,background1 <= 0.12,background1 <= 0.12,background1 <= 0.12
149,background1 <= 0.09,background1 <= 0.09,background1 <= 0.09,background1 <= 0.09
150,Class_A,Class_A,Class_A,Class_A
151,Class_B,Class_B,Class_B,Class_B

In [21]:
all_results_pert[0]['pert_results_dict']['Bag_3']

                Predicate  Perturbation
0            Fe ka > 2.41      0.429836
1          Fe ka <= -2.42      0.422959
2           Fe ka > -2.42      0.337764
3           Fe ka <= 4.61      0.333920
4           Fe ka > -3.73      0.330447
..                    ...           ...
145  background1 <= -0.08      0.000034
146   background1 > -0.08      0.000032
147   background1 > -0.10      0.000031
148   background1 <= 0.12      0.000029
149   background1 <= 0.09      0.000029

[150 rows x 2 columns]

In [22]:
# Somar LRCs de predicados equivalentes entre diferentes seeds
lrc_combined_list = []

for seed in random_seeds:
    lrc_df = lrc_pert_by_seed[seed].copy()
    lrc_combined_list.append(lrc_df) # o append adiciona o dataframe ao final da lista

# Concatenar todos os dataframes
lrc_all_seeds = pd.concat(lrc_combined_list, ignore_index=True) 

# Agrupar por predicado (Node) e somar as LRCs, mantendo Zone, Threshold e Operator
lrc_summed_df = lrc_all_seeds.groupby('Node').agg({ # o .agg pode ser usado para aplicar múltiplas funções de agregação
    'Local_Reaching_Centrality': 'mean', # sum = somando as LRCs, poderia ser média ou outro agregado
    'Zone': 'first',
    'Threshold': 'first',
    'Operator': 'first'
}).reset_index()

# Ordenar pelo valor de LRC somado (maior para menor)
lrc_summed_df = lrc_summed_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
# vamoss pegar so os valore sunicos de lrc_summed_df baseado na zona espectral
lrc_summed_unique_df_pert = lrc_summed_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
lrc_summed_unique_df_pert = lrc_summed_unique_df_pert.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
lrc_summed_unique_df_pert

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator
0,Fe ka > 2.41,7.901735,Fe ka,2.41,>
1,Ca ka > -0.20,1.592955,Ca ka,-0.20,>
2,Ti ka <= -0.37,1.422183,Ti ka,-0.37,<=
3,Fe kb > 0.90,1.339633,Fe kb,0.90,>
4,Mn > 0.22,0.485447,Mn,0.22,>
5,background6 > 0.14,0.219735,background6,0.14,>
6,Ti kb <= -0.23,0.149024,Ti kb,-0.23,<=
7,Al <= -0.14,0.140966,Al,-0.14,<=
8,Rh L + Ar > 0.27,0.130032,Rh L + Ar,0.27,>
9,sum Fe > 0.26,0.114112,sum Fe,0.26,>
10,Ca kb > 0.12,0.086124,Ca kb,0.12,>
11,background7 > 0.12,0.065205,background7,0.12,>
12,Si > 0.18,0.046243,Si,0.18,>
13,K > 0.09,0.037583,K,0.09,>
14,Cu > -0.16,0.035615,Cu,-0.16,>
15,background5 > 0.12,0.034345,background5,0.12,>
16,Fe ka + Ti ka <= -0.11,0.030085,Fe ka + Ti ka,-0.11,<=
17,Cr <= -0.17,0.026239,Cr,-0.17,<=
18,P > 0.15,0.016205,P,0.15,>
19,background8 > -0.22,0.008517,background8,-0.22,>
20,background3 <= -0.09,0.004960,background3,-0.09,<=
21,background4 > 0.09,0.001741,background4,0.09,>
22,S > 0.09,0.001285,S,0.09,>
23,background2 > 0.07,0.000861,background2,0.07,>
24,background1 > 0.09,0.000159,background1,0.09,>
25,Class_B,0.000000,None,None,None

In [23]:
import numpy as np

max_len = max(
    len(vip_scores_unique_df['Zone']),
    len(reg_vet_unique_df['Zone']),
    len(shap_unique_df['Zone']),
    len(lrc_summed_unique_df_pert['Zone']),
    len(lrc_summed_unique_df_cov['Zone'])
)

def pad_list(lst, length):
    return list(lst) + [None] * (length - len(lst))

features_importance = pd.DataFrame({
    'Vip': pad_list(vip_scores_unique_df['Zone'], max_len),
    'Reg_coef': pad_list(reg_vet_unique_df['Zone'], max_len),
    'Shap': pad_list(shap_unique_df['Zone'], max_len),
    'LRC_perturbation' : pad_list(lrc_summed_unique_df_pert['Zone'], max_len),
    'LRC_covariance' : pad_list(lrc_summed_unique_df_cov['Zone'], max_len),
})

features_importance.to_csv('feature_importance.csv', index=False, sep=';')
features_importance

,Vip,Reg_coef,Shap,LRC_perturbation,LRC_covariance
0,Fe ka,Fe ka,Fe ka,Fe ka,Fe ka
1,Fe kb,Ca ka,Ca ka,Ca ka,Fe kb
2,Ti ka,Ti ka,Ti ka,Ti ka,Mn
3,Ca ka,Fe kb,Mn,Fe kb,sum Fe
4,Mn,Mn,Fe kb,Mn,Ti ka
5,sum Fe,Al,Al,background6,Ca ka
6,Ti kb,Rh L + Ar,background6,Ti kb,background4
7,Al,Ca kb,Fe ka + Ti ka,Al,Rh L + Ar
8,Si,K,background7,Rh L + Ar,Ti kb
9,background4,Ti kb,background8,sum Fe,Si
10,Cr,Cu,background1,Ca kb,Cr
11,Rh L + Ar,background6,sum Fe,background7,Cu
12,Cu,sum Fe,Rh L + Ar,Si,background8
13,Ca kb,Cr,K,K,Al
14,background8,P,Cu,Cu,Ca kb
15,K,background3,Ca kb,background5,background3
16,background3,background7,background3,Fe ka + Ti ka,background1
17,P,background5,Si,Cr,K
18,background6,Fe ka + Ti ka,S,P,background2
19,Fe ka + Ti ka,background2,background2,background8,background7
20,background7,Si,P,background3,background6
21,background5,background8,background5,background4,P
22,background2,S,Ti kb,S,S
23,background1,background4,Cr,background2,Fe ka + Ti ka
24,S,background1,background4,background1,None
25,None,None,None,None,None

In [24]:
# RBO (Rank-Biased Overlap) para comparar rankings
import rbo
rbo_results = {}
reference_list = [x for x in features_importance['Vip'].tolist() if x is not None]
methods = ['Reg_coef', 'Shap', 'LRC_covariance', 'LRC_perturbation']
for method in methods:
    compare_list = [x for x in features_importance[method].tolist() if x is not None]
    # Truncate both lists to the same length (minimum of both)
    min_len = min(len(reference_list), len(compare_list))
    ref_trunc = reference_list[:min_len]
    cmp_trunc = compare_list[:min_len]
    score = rbo.RankingSimilarity(ref_trunc, cmp_trunc).rbo(p=0.7, k=10)
    rbo_results[method] = score
rbo_results = pd.DataFrame(list(rbo_results.items()), columns=['Method','RBO_Score'])
rbo_results.insert(0, 'Reference', 'Vip')
rbo_results.sort_values(by='RBO_Score', ascending=False, inplace=True)
rbo_results.to_csv('rbo_rank.csv', index=False, sep=';')
rbo_results

  Reference            Method  RBO_Score
2       Vip    LRC_covariance   0.840624
3       Vip  LRC_perturbation   0.794954
0       Vip          Reg_coef   0.783692
1       Vip              Shap   0.756756