## Loading data

In [1]:
# Importing the necessary libraries
import pandas as pd
import numpy as np
import kennard_stone as ks
pd.options.plotting.backend = 'plotly'  # setting plotly as the backend for pandas plotting

# Add parent directory to sys.path so local module 'synthetic' (one level up) can be imported
import sys
from pathlib import Path # for path manipulations
parent_dir = Path.cwd().parent.parent.resolve() # move two levels up from current working directory
if str(parent_dir) not in sys.path: # check to avoid duplicates
    sys.path.insert(0, str(parent_dir)) # insert at the start of sys.path to prioritize local modules

# Loading a soil spectral dataset based on X-ray fluorescence (XRF)
data_complete = pd.read_csv(f'{parent_dir}/XRF_databases/soil_types/plsda/soil_types.csv', sep=';') # local copy of Toledo and Guarapuava soil datasets
data = data_complete.loc[:, '1':'15']

# Split dataset by class and create calibration/prediction sets using Kennard-Stone (as in original pipeline)
data_A = data_complete[data_complete['Class'] == 'A'].reset_index(drop=True)
data_B = data_complete[data_complete['Class'] == 'B'].reset_index(drop=True)

# splitting the data into calibration and prediction sets by kennard-stone algorithm
XA_cal, XA_pred = ks.train_test_split(data_A.loc[:, '1':'15'], test_size=0.30) # class A
XA_cal = XA_cal.reset_index(drop=True)
XA_pred = XA_pred.reset_index(drop=True)

XB_cal, XB_pred = ks.train_test_split(data_B.loc[:, '1':'15'], test_size=0.30) # class B
XB_cal = XB_cal.reset_index(drop=True)
XB_pred = XB_pred.reset_index(drop=True)

Xcalclass = pd.concat([XA_cal, XB_cal], axis=0).reset_index(drop=True) # concatenating both classes
Xpredclass = pd.concat([XA_pred, XB_pred], axis=0).reset_index(drop=True)
ycalclass = pd.Series(['A']*XA_cal.shape[0] + ['B']*XB_cal.shape[0]) # creating the target variable for calibration set
ypredclass = pd.Series(['A']*XA_pred.shape[0] + ['B']*XB_pred.shape[0]) # creating the target variable for prediction set

# preprocessings
import preprocessings as prepr # preprocessing methods for XRF data

Xcalclass_prep, mean_calclass, mean_calclass_poisson  = prepr.poisson(Xcalclass, mc=True)
Xpredclass_prep = ((Xpredclass/np.sqrt(mean_calclass)) - mean_calclass_poisson)

from modeling import pls_optimized

# performing PLS-DA with optimized latent variables
plsda_results = pls_optimized(Xcalclass_prep, 
                              ycalclass,
                              LVmax=2,
                              Xpred=Xpredclass_prep,
                              ypred=ypredclass,
                              aim='classification',
                              cv=10)
plsda_results[0]


# Convenience references used later
pls_model = plsda_results[3]               # fitted PLS model
vip_scores_mat = plsda_results[4]          # VIP scores matrix (features × LV)
y_pred_cont = plsda_results[5].iloc[:, -1] # continuous predictions for Xcalclass (used for MI/Cov)

2026-01-25 18:10:24,327 - kennard_stone.utils._pairwise:114[INFO] - Calculating pairwise distances using scikit-learn.

2026-01-25 18:10:24,332 - kennard_stone.utils._pairwise:114[INFO] - Calculating pairwise distances using scikit-learn.

2026-01-25 18:10:24,408 - kennard_stone.utils._pairwise:114[INFO] - Calculating pairwise distances using scikit-learn.

2026-01-25 18:10:24,413 - kennard_stone.utils._pairwise:114[INFO] - Calculating pairwise distances using scikit-learn.

In [2]:
# plotando o vip scores rapidamente
vip_scores_mat.T.plot()

In [3]:
# calculando a covariancia entre cada variável espectral e a predição do modelo PLS-DA
cov_scores = []
y_pred = plsda_results[5].iloc[:,-1].values # using the continuous predictions from LV=3
for col in Xcalclass_prep.columns:
    x_values = Xcalclass_prep[col].values
    covariance = np.cov(x_values, y_pred)[0, 1] # covariance between x and y
    cov_scores.append(covariance)
cov_scores_df = pd.DataFrame(cov_scores, index=Xcalclass_prep.columns, columns=['Covariance'])
cov_scores_df = np.abs(cov_scores_df)
cov_scores_df.plot()

In [4]:
# establishing spectral cuts based on expert knowledge of XRF spectra
spectral_cuts = [
('background1', 1.0, 1.33),
('Al', 1.33, 1.63),
('Si', 1.63, 1.86),
('P', 1.86, 2.19),
('S', 2.19, 2.44),
('background2', 2.44, 2.55),
('Rh L + Ar', 2.55, 3.21),
('K', 3.21, 3.53),
('Ca ka', 3.53, 3.84),
('Ca kb', 3.84, 4.14),
('background3', 4.14, 4.37),
('Ti ka', 4.37, 4.66),
('background4', 4.66, 4.75),
('Ti kb', 4.75, 5.12),
('Cr', 5.12, 5.77),
('Mn', 5.77, 6.13),
('Fe ka', 6.13, 6.80),
('Fe kb', 6.80, 7.30),
('background5', 7.30, 7.91),
('Cu', 7.91, 8.20),
('background6', 8.20, 10.69),
('Fe ka + Ti ka', 10.69, 11.14),
('background7', 11.14, 12.55),
('sum Fe' , 12.55, 13.1),
('background8', 13.1, 15.0)
]

import explaining as exp
spectral_zones_class = exp.extract_spectral_zones(Xcalclass_prep, spectral_cuts)
zone_sums_df = exp.aggregate_spectral_zones(spectral_zones_class, aggregator='extreme')
predicates_quantiles = exp.predicates_by_quantiles(zone_sums_df, [0.2, 0.4, 0.6, 0.8])
co_occurrence_matrix_df = predicates_quantiles[2]
predicate_info_dict = exp.create_predicate_info_dict(
    predicates_df=predicates_quantiles[0],
    predicate_indicator_df=predicates_quantiles[1],
    zone_aggregated_df=zone_sums_df,
    y_predicted_numeric=y_pred_cont
)

## VIP, Regression Coefficients e SHAP (como no original)

In [5]:
# VIP scores por energia
vip_scores_df = pd.DataFrame({
    'energy': vip_scores_mat.T.index,
    'VIP_Score': vip_scores_mat.T.iloc[:,0].values
})
vip_scores_df = vip_scores_df.sort_values(by='VIP_Score', ascending=False).reset_index(drop=True)
energy_to_zone_vip = {}
for zone_name, start, end in spectral_cuts:
    for e in vip_scores_df['energy']:
        ef = float(e)
        if start <= ef <= end:
            energy_to_zone_vip[e] = zone_name
vip_scores_df['Zone'] = vip_scores_df['energy'].map(energy_to_zone_vip)
vip_scores_unique_df = vip_scores_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
vip_scores_unique_df = vip_scores_unique_df.sort_values(by='VIP_Score', ascending=False).reset_index(drop=True)

# Coeficientes de regressão do PLS
reg_vet = pd.DataFrame(pls_model.coef_, columns=pls_model.feature_names_in_).T
reg_vet.insert(0, 'energy', reg_vet.index)
reg_vet = reg_vet.reset_index(drop=True)
reg_vet.columns = ['energy','Reg_coef']
reg_vet['Abs_Reg_coef'] = reg_vet['Reg_coef'].abs()
reg_vet = reg_vet.sort_values(by='Abs_Reg_coef', ascending=False).reset_index(drop=True)
energy_to_zone_reg = {}
for zone_name, start, end in spectral_cuts:
    for e in reg_vet['energy']:
        ef = float(e)
        if start <= ef <= end:
            energy_to_zone_reg[e] = zone_name
reg_vet['Zone'] = reg_vet['energy'].map(energy_to_zone_reg)
reg_vet_unique_df = reg_vet.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
reg_vet_unique_df = reg_vet_unique_df.sort_values(by='Abs_Reg_coef', ascending=False).reset_index(drop=True)

# vamos agora extrair as variaveis mais importantes atraves do método SHAP
# import shap

# # Para PLSRegression, usamos KernelExplainer porque não há explainer dedicado muito rápido
# explainer_pls = shap.KernelExplainer(plsda_results[3].predict, Xcalclass_prep)
# shap_values_pls = explainer_pls(Xcalclass_prep)

# shap_global_importance = pd.DataFrame({
#     'energy': Xpredclass_prep.columns,
#     'Mean_Abs_SHAP': np.abs(shap_values_pls.values).mean(axis=0)}) # tomando a importancia global como a media dos valores absolutos dos valores SHAP para cada feature
# shap_global_importance.sort_values(by='Mean_Abs_SHAP', ascending=False, inplace=True)

# # vamos gerar uma nova coluna em shap_global_importance com o nome da zona espectral correspondente de acordo com a lista spectral_cuts
# energy_to_zone_shap = {}
# for zone_name, start, end in spectral_cuts:
#     for i in shap_global_importance['energy']:
#         i_float = float(i)
#         if start <= i_float <= end:
#             energy_to_zone_shap[i] = zone_name
# shap_global_importance['Zone'] = shap_global_importance['energy'].map(energy_to_zone_shap)

# # agora vamos filtrar shap_global_importance para manter apenas as zonas espectrais únicas com maior SHAP score
# shap_unique_df = shap_global_importance.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
# shap_unique_df = shap_unique_df.sort_values(by='Mean_Abs_SHAP', ascending=False).reset_index(drop=True)
# shap_unique_df.to_csv('shap_bank_notes.csv', index=False, sep=';')
shap_unique_df = pd.read_csv('shap_soil_types.csv', sep=';') # loading previously saved shap_unique_df

# **bagging - covariance**

In [6]:
import explaining as exp

# LISTA DE SEMENTES A TESTAR
random_seeds = [0, 1, 2, 3]

all_results_cov = {}
training_samples = len(Xcalclass)

# LOOP: PROCESSAR CADA SEMENTE
y_predicted_numeric = plsda_results[5].iloc[:, -1] # predições numéricas do modelo

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando semente: {seed}")
    print(f"{'='*70}\n")
    # Bagging
    bags_result_seed = exp.bagging_predicates(
        zone_sums_df=zone_sums_df,
        y_predicted_numeric=y_predicted_numeric,
        predicates_df=predicates_quantiles[0],
        n_bags=10,
        #n_predicates_per_bag=40,
        n_samples_per_bag=int(training_samples*0.8), # 80 % da base para amostrar (convertido para int)
        min_samples_per_predicate=int(training_samples*0.2), # 20 % da base para limitar (convertido para int)
        replace=False,
        sample_bagging=True,
        predicate_bagging=False,
        random_seed=seed
    )
    # Inserir classe prevista
    for bag_name, pred_dict in bags_result_seed.items(): # iterando sobre cada bag
        for pred_rule, df_info in pred_dict.items():
            df_info['Class_Predicted'] = np.where(df_info['Predicted_Y'] >= 0.5, 'A', 'B') # binarizando com threshold 0.5, A = eut, B = dist
    # Calcular MI
    cov_results_dict_seed = exp.calculate_predicate_metrics(
        bags_result=bags_result_seed,
        metric='covariance', # covariance ou mutual_information
        threshold=0.01, # threshold para cortar predicados irrelevantes
        n_neighbors=5
    )
    # Salvar no dicionário principal
    all_results_cov[seed] = {
        'bags_result': bags_result_seed,
        'cov_results_dict': cov_results_dict_seed
    }

# CONSTRUÇÃO DE GRAFOS PARA MÚLTIPLAS SEMENTES (LOOP EXTERNO)
# Dicionário para armazenar grafos
graphs_by_seed = {}

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando Grafo - Semente: {seed}")
    print(f"{'='*70}\n")
    # Construir grafo para esta semente
    DG = exp.build_predicate_graph(
        bags_result=all_results_cov[seed]['bags_result'],
        mi_results_dict=all_results_cov[seed]['cov_results_dict'],
        co_occurrence_matrix_df=co_occurrence_matrix_df,
        predicates_df=predicates_quantiles[0],
        random_state=seed,
        show_details=True
    )
    # Armazenar grafo
    graphs_by_seed[seed] = DG  

# Calcular LRC usando a função pronta do explaining.py
lrc_cov_by_seed = {}
for seed in random_seeds:
    DG = graphs_by_seed[seed]
    lrc_cov_df_seed = exp.calculate_lrc_single_graph(DG, predicates_quantiles[0])
    lrc_cov_df_seed['Seed'] = seed  # Adicionar coluna com a semente
    lrc_cov_by_seed[seed] = lrc_cov_df_seed

# junando todas as colunas 'Node' de lrc_by_seed em um único dataframe
lrc_cov_all_seeds_df = pd.DataFrame()
for seed in random_seeds:
    lrc_cov_df_seed = lrc_cov_by_seed[seed].rename(columns={'Node': f'Predicate_Cov_Seed_{seed}'})
    lrc_cov_all_seeds_df = pd.concat([lrc_cov_all_seeds_df, lrc_cov_df_seed[[f'Predicate_Cov_Seed_{seed}']]], axis=1)

# vamos filtrar lrc_by_seed em cada semente para manter apenas as zonas espectrais únicas com maior LRC em um mesmo dataframe
lrc_cov_unique_by_seed = {}
for seed, lrc_df in lrc_cov_by_seed.items():
    lrc_cov_unique_df = lrc_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
    lrc_cov_unique_df = lrc_cov_unique_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
    lrc_cov_unique_by_seed[seed] = lrc_cov_unique_df

lrc_cov_all_seeds_df # exibindo o dataframe consolidado com predicados de todas as sementes

======================================================================
Processando semente: 0
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando semente: 1
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando semente: 2
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando semente: 3
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando Grafo - Semente: 0
======================================================================


Total de pares bidirecionais encontrados: 138
Removida aresta Fe ka > -3.73 -> Fe ka <= 4.61 (peso 1196.0)
Mantida aresta Fe ka <= 4.61 -> Fe ka > -3.73 (peso 1794.0)

======================================================================

Removida aresta Fe kb > -1.37 -> Fe kb <= 1.68 (peso 1200.0)
Mantida aresta Fe kb <= 1.68 -> Fe kb > -1.37 (peso 1800.0)

======================================================================

Removida aresta Mn <= 0.47 -> sum Fe > -0.41 (peso 300.0)
Mantida aresta sum Fe > -0.41 -> Mn <= 0.47 (peso 600.0)

======================================================================

Removida aresta Ti ka > -0.84 -> sum Fe > -0.41 (peso 702.0)
Mantida aresta sum Fe > -0.41 -> Ti ka > -0.84 (peso 1404.0)

======================================================================

Removida aresta sum Fe <= 0.51 -> Mn <= 0.47 (peso 1376.0)
Mantida aresta Mn <= 0.47 -> sum Fe <= 0.51 (peso 1720.0)

======================================================================

Removida aresta Mn <= 0.47 -> Ti ka > -0.84 (peso 317.0)
Mantida aresta Ti ka > -0.84 -> Mn <= 0.47 (peso 634.0)

======================================================================

Removida aresta Ti ka > -0.84 -> sum Fe <= 0.51 (peso 626.0)
Mantida aresta sum Fe <= 0.51 -> Ti ka > -0.84 (peso 939.0)

======================================================================

Removida aresta Ca ka > -0.82 -> Ti ka > -0.37 (peso 702.0)
Mantida aresta Ti ka > -0.37 -> Ca ka > -0.82 (peso 936.0)

======================================================================

Removida aresta Ti ka > -0.37 -> Ca ka > -0.55 (peso 174.0)
Mantida aresta Ca ka > -0.55 -> Ti ka > -0.37 (peso 348.0)

======================================================================

Empate! Removida aresta Ca ka > -0.55 -> Rh L + Ar <= 0.36 (peso 460.0)
Mantida aresta Rh L + Ar <= 0.36 -> Ca ka > -0.55 (peso 460.0)

======================================================================

Removida aresta Ti kb > -0.42 -> Rh L + Ar <= 0.36 (peso 299.0)
Mantida aresta Rh L + Ar <= 0.36 -> Ti kb > -0.42 (peso 598.0)

======================================================================

Empate! Removida aresta Mn > -0.33 -> Rh L + Ar <= 0.36 (peso 396.0)
Mantida aresta Rh L + Ar <= 0.36 -> Mn > -0.33 (peso 396.0)

======================================================================

Removida aresta Fe ka <= -2.42 -> Rh L + Ar <= 0.36 (peso 199.0)
Mantida aresta Rh L + Ar <= 0.36 -> Fe ka <= -2.42 (peso 398.0)

======================================================================

Empate! Removida aresta Ca ka > -0.20 -> Ca ka > -0.55 (peso 200.0)
Mantida aresta Ca ka > -0.55 -> Ca ka > -0.20 (peso 200.0)

======================================================================

Removida aresta Mn > -0.33 -> Ti kb > -0.42 (peso 283.0)
Mantida aresta Ti kb > -0.42 -> Mn > -0.33 (peso 566.0)

======================================================================

Removida aresta Fe ka <= -2.42 -> Ti kb > -0.42 (peso 112.0)
Mantida aresta Ti kb > -0.42 -> Fe ka <= -2.42 (peso 224.0)

======================================================================

Empate! Removida aresta Ti kb <= 0.48 -> Ti kb > -0.42 (peso 299.0)
Mantida aresta Ti kb > -0.42 -> Ti kb <= 0.48 (peso 299.0)

======================================================================

Removida aresta Mn > -0.33 -> Si > -0.45 (peso 284.0)
Mantida aresta Si > -0.45 -> Mn > -0.33 (peso 852.0)

======================================================================

Empate! Removida aresta Mn > -0.33 -> Fe ka <= -2.42 (peso 32.0)
Mantida aresta Fe ka <= -2.42 -> Mn > -0.33 (peso 32.0)

======================================================================

Empate! Removida aresta Fe ka <= -2.42 -> Rh L + Ar > -0.26 (peso 206.0)
Mantida aresta Rh L + Ar > -0.26 -> Fe ka <= -2.42 (peso 206.0)

======================================================================

Removida aresta Ca ka > -0.20 -> Rh L + Ar > -0.26 (peso 171.0)
Mantida aresta Rh L + Ar > -0.26 -> Ca ka > -0.20 (peso 513.0)

======================================================================

Removida aresta Si > -0.45 -> Ca ka > -0.20 (peso 169.0)
Mantida aresta Ca ka > -0.20 -> Si > -0.45 (peso 338.0)

======================================================================

Empate! Removida aresta Si > -0.45 -> Fe ka <= -2.42 (peso 121.0)
Mantida aresta Fe ka <= -2.42 -> Si > -0.45 (peso 121.0)

======================================================================

Empate! Removida aresta Fe ka <= -2.42 -> Si <= 0.51 (peso 198.0)
Mantida aresta Si <= 0.51 -> Fe ka <= -2.42 (peso 198.0)

======================================================================

Removida aresta background4 > -0.29 -> Si <= 0.51 (peso 299.0)
Mantida aresta Si <= 0.51 -> background4 > -0.29 (peso 897.0)

======================================================================

Removida aresta Ti kb <= 0.48 -> Si <= 0.51 (peso 358.0)
Mantida aresta Si <= 0.51 -> Ti kb <= 0.48 (peso 1432.0)

======================================================================

Empate! Removida aresta sum Fe > -0.27 -> Si <= 0.51 (peso 203.0)
Mantida aresta Si <= 0.51 -> sum Fe > -0.27 (peso 203.0)

======================================================================

Empate! Removida aresta Si <= 0.51 -> background4 <= 0.35 (peso 347.0)
Mantida aresta background4 <= 0.35 -> Si <= 0.51 (peso 347.0)

======================================================================

Removida aresta background4 > -0.29 -> Ti kb <= 0.48 (peso 300.0)
Mantida aresta Ti kb <= 0.48 -> background4 > -0.29 (peso 1500.0)

======================================================================

Removida aresta background4 <= 0.35 -> sum Fe > -0.27 (peso 402.0)
Mantida aresta sum Fe > -0.27 -> background4 <= 0.35 (peso 804.0)

======================================================================

Removida aresta Cr > -0.26 -> sum Fe > -0.27 (peso 303.0)
Mantida aresta sum Fe > -0.27 -> Cr > -0.26 (peso 1212.0)

======================================================================

Removida aresta background8 <= 0.27 -> Cu <= 0.25 (peso 714.0)
Mantida aresta Cu <= 0.25 -> background8 <= 0.27 (peso 1071.0)

======================================================================

Removida aresta background8 > -0.22 -> Cu > -0.22 (peso 376.0)
Mantida aresta Cu > -0.22 -> background8 > -0.22 (peso 1880.0)

======================================================================

Empate! Removida aresta background8 <= 0.27 -> Cu > -0.22 (peso 616.0)
Mantida aresta Cu > -0.22 -> background8 <= 0.27 (peso 616.0)

======================================================================

Removida aresta background8 <= 0.27 -> background8 > -0.22 (peso 616.0)
Mantida aresta background8 > -0.22 -> background8 <= 0.27 (peso 924.0)

======================================================================

Empate! Removida aresta Ti ka > 0.45 -> background8 > -0.22 (peso 201.0)
Mantida aresta background8 > -0.22 -> Ti ka > 0.45 (peso 201.0)

======================================================================

Removida aresta Ti kb > -0.23 -> Rh L + Ar > -0.21 (peso 510.0)
Mantida aresta Rh L + Ar > -0.21 -> Ti kb > -0.23 (peso 1020.0)

======================================================================

Removida aresta Ca kb > -0.24 -> Rh L + Ar > -0.21 (peso 277.0)
Mantida aresta Rh L + Ar > -0.21 -> Ca kb > -0.24 (peso 554.0)

======================================================================

Removida aresta Si > -0.25 -> Rh L + Ar > -0.21 (peso 242.0)
Mantida aresta Rh L + Ar > -0.21 -> Si > -0.25 (peso 484.0)

======================================================================

Removida aresta Mn <= 0.22 -> Ti kb > -0.23 (peso 119.0)
Mantida aresta Ti kb > -0.23 -> Mn <= 0.22 (peso 476.0)

======================================================================

Removida aresta Ti ka > 0.45 -> Ti kb > -0.23 (peso 191.0)
Mantida aresta Ti kb > -0.23 -> Ti ka > 0.45 (peso 382.0)

======================================================================

Empate! Removida aresta Ca kb > -0.24 -> Mn <= 0.22 (peso 209.0)
Mantida aresta Mn <= 0.22 -> Ca kb > -0.24 (peso 209.0)

======================================================================

Removida aresta Si > -0.25 -> Mn <= 0.22 (peso 244.0)
Mantida aresta Mn <= 0.22 -> Si > -0.25 (peso 488.0)

======================================================================

Empate! Removida aresta Al > -0.27 -> Mn <= 0.22 (peso 230.0)
Mantida aresta Mn <= 0.22 -> Al > -0.27 (peso 230.0)

======================================================================

Removida aresta Rh L + Ar <= 0.27 -> Ca kb > -0.24 (peso 208.0)
Mantida aresta Ca kb > -0.24 -> Rh L + Ar <= 0.27 (peso 624.0)

======================================================================

Removida aresta Ca kb > -0.24 -> background4 > -0.17 (peso 271.0)
Mantida aresta background4 > -0.17 -> Ca kb > -0.24 (peso 542.0)

======================================================================

Removida aresta Rh L + Ar <= 0.27 -> Al > -0.27 (peso 238.0)
Mantida aresta Al > -0.27 -> Rh L + Ar <= 0.27 (peso 476.0)

======================================================================

Empate! Removida aresta Rh L + Ar <= 0.27 -> background4 > -0.17 (peso 220.0)
Mantida aresta background4 > -0.17 -> Rh L + Ar <= 0.27 (peso 220.0)

======================================================================

Removida aresta Ca kb <= 0.23 -> Rh L + Ar <= 0.27 (peso 261.0)
Mantida aresta Rh L + Ar <= 0.27 -> Ca kb <= 0.23 (peso 783.0)

======================================================================

Empate! Removida aresta Rh L + Ar <= 0.27 -> sum Fe <= 0.26 (peso 260.0)
Mantida aresta sum Fe <= 0.26 -> Rh L + Ar <= 0.27 (peso 260.0)

======================================================================

Empate! Removida aresta Al > -0.27 -> Si > -0.25 (peso 554.0)
Mantida aresta Si > -0.25 -> Al > -0.27 (peso 554.0)

======================================================================

Empate! Removida aresta sum Fe <= 0.26 -> background4 > -0.17 (peso 202.0)
Mantida aresta background4 > -0.17 -> sum Fe <= 0.26 (peso 202.0)

======================================================================

Empate! Removida aresta Ca kb <= 0.23 -> background4 > -0.17 (peso 231.0)
Mantida aresta background4 > -0.17 -> Ca kb <= 0.23 (peso 231.0)

======================================================================

Empate! Removida aresta Ti ka <= 0.92 -> Ti ka > 0.45 (peso 100.0)
Mantida aresta Ti ka > 0.45 -> Ti ka <= 0.92 (peso 100.0)

======================================================================

Empate! Removida aresta Ti kb <= 0.24 -> Ca kb <= 0.23 (peso 510.0)
Mantida aresta Ca kb <= 0.23 -> Ti kb <= 0.24 (peso 510.0)

======================================================================

Removida aresta Ti ka <= -0.37 -> K > 0.09 (peso 48.0)
Mantida aresta K > 0.09 -> Ti ka <= -0.37 (peso 96.0)

======================================================================

Removida aresta background2 <= 0.10 -> Ti ka <= -0.37 (peso 161.0)
Mantida aresta Ti ka <= -0.37 -> background2 <= 0.10 (peso 322.0)

======================================================================

Empate! Removida aresta Cr <= 0.17 -> Cr > -0.17 (peso 96.0)
Mantida aresta Cr > -0.17 -> Cr <= 0.17 (peso 96.0)

======================================================================

Removida aresta Cr > -0.17 -> Al > -0.14 (peso 460.0)
Mantida aresta Al > -0.14 -> Cr > -0.17 (peso 690.0)

======================================================================

Empate! Removida aresta Cr > -0.17 -> Ca kb > -0.18 (peso 440.0)
Mantida aresta Ca kb > -0.18 -> Cr > -0.17 (peso 440.0)

======================================================================

Empate! Removida aresta Ca kb > -0.18 -> Ti kb <= 0.24 (peso 153.0)
Mantida aresta Ti kb <= 0.24 -> Ca kb > -0.18 (peso 153.0)

======================================================================

Removida aresta Ca kb > -0.18 -> Al > -0.14 (peso 188.0)
Mantida aresta Al > -0.14 -> Ca kb > -0.18 (peso 376.0)

======================================================================

Removida aresta Fe kb <= -0.88 -> Ca kb > -0.18 (peso 84.0)
Mantida aresta Ca kb > -0.18 -> Fe kb <= -0.88 (peso 168.0)

======================================================================

Empate! Removida aresta Al > -0.14 -> Cu > -0.16 (peso 462.0)
Mantida aresta Cu > -0.16 -> Al > -0.14 (peso 462.0)

======================================================================

Empate! Removida aresta background3 <= 0.18 -> Al > -0.14 (peso 212.0)
Mantida aresta Al > -0.14 -> background3 <= 0.18 (peso 212.0)

======================================================================

Removida aresta background3 > -0.16 -> Cu > -0.16 (peso 292.0)
Mantida aresta Cu > -0.16 -> background3 > -0.16 (peso 1168.0)

======================================================================

Removida aresta Cu > -0.16 -> Fe kb <= -0.88 (peso 34.0)
Mantida aresta Fe kb <= -0.88 -> Cu > -0.16 (peso 68.0)

======================================================================

Empate! Removida aresta background3 > -0.16 -> Cr <= 0.17 (peso 642.0)
Mantida aresta Cr <= 0.17 -> background3 > -0.16 (peso 642.0)

======================================================================

Empate! Removida aresta Ti ka <= 0.92 -> background3 > -0.16 (peso 305.0)
Mantida aresta background3 > -0.16 -> Ti ka <= 0.92 (peso 305.0)

======================================================================

Empate! Removida aresta Cr <= 0.17 -> background3 <= 0.18 (peso 572.0)
Mantida aresta background3 <= 0.18 -> Cr <= 0.17 (peso 572.0)

======================================================================

Removida aresta Fe kb <= -0.88 -> background3 <= 0.18 (peso 196.0)
Mantida aresta background3 <= 0.18 -> Fe kb <= -0.88 (peso 392.0)

======================================================================

Empate! Removida aresta background3 <= 0.18 -> Ti ka <= 0.92 (peso 361.0)
Mantida aresta Ti ka <= 0.92 -> background3 <= 0.18 (peso 361.0)

======================================================================

Empate! Removida aresta Ca ka <= 0.76 -> Al <= 0.29 (peso 301.0)
Mantida aresta Al <= 0.29 -> Ca ka <= 0.76 (peso 301.0)

======================================================================

Empate! Removida aresta background8 > -0.15 -> Ca ka <= 0.76 (peso 246.0)
Mantida aresta Ca ka <= 0.76 -> background8 > -0.15 (peso 246.0)

======================================================================

Removida aresta Al <= 0.29 -> Fe kb <= -0.88 (peso 197.0)
Mantida aresta Fe kb <= -0.88 -> Al <= 0.29 (peso 394.0)

======================================================================

Empate! Removida aresta Al <= 0.29 -> Ti ka <= 0.92 (peso 342.0)
Mantida aresta Ti ka <= 0.92 -> Al <= 0.29 (peso 342.0)

======================================================================

Removida aresta background4 <= 0.09 -> Al <= 0.29 (peso 284.0)
Mantida aresta Al <= 0.29 -> background4 <= 0.09 (peso 568.0)

======================================================================

Removida aresta Al <= 0.29 -> background8 <= 0.16 (peso 277.0)
Mantida aresta background8 <= 0.16 -> Al <= 0.29 (peso 554.0)

======================================================================

Empate! Removida aresta Cu <= 0.15 -> Al <= 0.29 (peso 276.0)
Mantida aresta Al <= 0.29 -> Cu <= 0.15 (peso 276.0)


/home/jvribeiro/.local/lib/python3.10/site-packages/networkx/algorithms/centrality/reaching.py:193: RuntimeWarning:

divide by zero encountered in scalar divide

/home/jvribeiro/.local/lib/python3.10/site-packages/networkx/algorithms/centrality/reaching.py:193: RuntimeWarning:

divide by zero encountered in scalar divide

/home/jvribeiro/.local/lib/python3.10/site-packages/networkx/algorithms/centrality/reaching.py:193: RuntimeWarning:

divide by zero encountered in scalar divide

Processando LRC do grafo...

Processando LRC do grafo...

/home/jvribeiro/.local/lib/python3.10/site-packages/networkx/algorithms/centrality/reaching.py:193: RuntimeWarning:

divide by zero encountered in scalar divide

,Predicate_Cov_Seed_0,Predicate_Cov_Seed_1,Predicate_Cov_Seed_2,Predicate_Cov_Seed_3
0,Fe ka <= 4.61,Fe ka > -3.73,Fe ka <= 4.61,Fe ka > -3.73
1,Fe ka > -3.73,Fe ka <= 4.61,Fe ka <= 2.41,Fe ka <= 4.61
2,Fe ka <= 2.41,Fe kb <= 0.90,Fe ka > -3.73,Fe ka <= 2.41
3,Fe ka > -2.42,Fe ka <= 2.41,Fe ka > -2.42,Fe ka > -2.42
4,Fe kb <= 1.68,Fe kb > -1.37,Fe kb <= 1.68,Fe kb <= 1.68
...,...,...,...,...
105,Ca ka <= -0.55,Fe ka + Ti ka <= -0.11,S <= 0.13,Fe ka + Ti ka <= 0.13
106,Fe ka + Ti ka <= 0.13,Fe ka + Ti ka <= 0.17,Fe ka + Ti ka <= -0.11,Fe ka + Ti ka <= -0.11
107,Class_A,S > -0.09,Class_A,Cr <= -0.17
108,Class_B,Class_A,Class_B,Class_A
109,NaN,Class_B,NaN,Class_B

In [7]:
all_results_cov[0]['cov_results_dict']['Bag_10']

                 Predicate  Covariance
0            Fe ka > -3.73    1.400208
1            Fe ka <= 4.61    1.346370
2            Fe ka > -2.42    0.814747
3            Fe ka <= 2.41    0.578946
4            Fe kb > -1.37    0.518028
..                     ...         ...
95     background6 <= 0.14    0.010689
96             Mn <= -0.33    0.010681
97  Fe ka + Ti ka <= -0.11    0.010511
98         sum Fe <= -0.27    0.010471
99               Al > 0.16    0.010181

[100 rows x 2 columns]

In [8]:
from collections import defaultdict

# Coletar posições de cada predicado em cada seed do lrc_pert_all_seeds_df
positions_dict_lrc = defaultdict(list)

# Iterar sobre cada coluna do dataframe lrc_pert_all_seeds_df
for col in lrc_cov_all_seeds_df.columns:
    # Pegar os predicados da coluna (não-nulos)
    predicates_in_seed = lrc_cov_all_seeds_df[col].dropna().tolist()
    
    # Para cada predicado, guardar sua posição (1-based)
    for position, predicate in enumerate(predicates_in_seed, start=1):
        positions_dict_lrc[predicate].append(position)

# Calcular média e número de aparições
results_lrc = []
for predicate, positions in positions_dict_lrc.items():
    zone_row = predicates_quantiles[0].loc[predicates_quantiles[0]['rule'] == predicate, 'zone']
    zone_value = zone_row.values[0] if not zone_row.empty else None
    results_lrc.append({
        'Predicate': predicate,
        'Mean_Position': np.mean(positions),
        'Appearances': len(positions),
        'Zone': zone_value
    })

# Ordenar: menor posição média primeiro, mais aparições em caso de empate
ranking_lrc_cov_df = pd.DataFrame(results_lrc).sort_values(
    by=['Mean_Position', 'Appearances'], 
    ascending=[True, False]
).reset_index(drop=True)

# Lista final ordenada
lista_ordenada_lrc = ranking_lrc_cov_df['Predicate'].tolist()
ranking_lrc_cov_df

                 Predicate  Mean_Position  Appearances           Zone
0            Fe ka <= 4.61           1.50            4          Fe ka
1            Fe ka > -3.73           1.75            4          Fe ka
2            Fe ka <= 2.41           3.00            4          Fe ka
3            Fe ka > -2.42           4.50            4          Fe ka
4            Fe kb <= 1.68           5.50            4          Fe kb
..                     ...            ...          ...            ...
108         Ca ka <= -0.55         106.00            1          Ca ka
109  Fe ka + Ti ka <= 0.13         106.50            2  Fe ka + Ti ka
110              S > -0.09         108.00            1              S
111                Class_A         108.50            4           None
112                Class_B         109.50            4           None

[113 rows x 4 columns]

In [9]:
ranking_cov_lrc_unique_df = ranking_lrc_cov_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
ranking_cov_lrc_unique_df['Zone']

0             Fe ka
1             Fe kb
2                Mn
3            sum Fe
4                Cr
5             Ti ka
6         Rh L + Ar
7             Ti kb
8                Si
9       background4
10               Cu
11            Ca ka
12      background8
13               Al
14      background1
15      background3
16            Ca kb
17      background7
18      background2
19                K
20      background6
21                P
22                S
23    Fe ka + Ti ka
24             None
Name: Zone, dtype: object

# **Perturbation**

In [10]:
import explaining as exp

# LISTA DE SEMENTES A TESTAR
random_seeds = [0, 1, 2, 3]

all_results_pert = {}
training_samples = len(Xcalclass)

# LOOP: PROCESSAR CADA SEMENTE
y_predicted_numeric = plsda_results[5].iloc[:, -1] # predições numéricas do modelo

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando semente: {seed}")
    print(f"{'='*70}\n")
    # Bagging
    bags_result_seed = exp.bagging_predicates(
        zone_sums_df=zone_sums_df,
        y_predicted_numeric=y_predicted_numeric,
        predicates_df=predicates_quantiles[0],
        n_bags=10,
        #n_predicates_per_bag=40,
        n_samples_per_bag=int(training_samples*0.8), # 80 % da base para amostrar (convertido para int)
        min_samples_per_predicate=int(training_samples*0.2), # 20 % da base para limitar (convertido para int)
        replace=False,
        sample_bagging=True,
        predicate_bagging=False,
        random_seed=seed
    )
    # Inserir classe prevista
    for bag_name, pred_dict in bags_result_seed.items(): # iterando sobre cada bag
        for pred_rule, df_info in pred_dict.items():
            df_info['Class_Predicted'] = np.where(df_info['Predicted_Y'] >= 0.5, 'A', 'B') # binarizando com threshold 0.5, A = eut, B = dist

    pert_results_seed = exp.calculate_predicate_perturbation(
        estimator=pls_model,
        Xcalclass_prep=Xcalclass_prep,
        folds_struct=bags_result_seed,
        predicates_df=predicates_quantiles[0],
        spectral_cuts=spectral_cuts,
        perturbation_value=0,
        metric='mean_relative_dev',   # Média com sinal (pode ser negativo)
        verbose=True
    )

    # Remove todos os valores iguais a zero de todos os bags em perm_results[bag]["Permutation"] e salva como perm_results_thresholded
    # pert_results_seed_thresholded = {}
    # for bag, df in perm_results_seed.items():
    #     # Verifica se é um DataFrame e se a coluna 'Permutation' existe
    #     if isinstance(df, pd.DataFrame) and 'Permutation' in df.columns:
    #         filtered_df = df[df['Permutation'] > 0].copy()
    #         pert_results_seed_thresholded[bag] = filtered_df
    #     else:
    #         # Se não for DataFrame esperado, apenas copia
    #         pert_results_seed_thresholded[bag] = df

    # Salvar no dicionário principal
    all_results_pert[seed] = {
        'bags_result': bags_result_seed,
        'pert_results_dict': pert_results_seed
    }

# CONSTRUÇÃO DE GRAFOS PARA MÚLTIPLAS SEMENTES (LOOP EXTERNO)
# Dicionário para armazenar grafos
graphs_pert_by_seed = {}

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando Grafo - Semente: {seed}")
    print(f"{'='*70}\n")
    # Construir grafo para esta semente
    DG = exp.build_predicate_graph(
        bags_result=all_results_pert[seed]['bags_result'],
        mi_results_dict=all_results_pert[seed]['pert_results_dict'],
        co_occurrence_matrix_df=co_occurrence_matrix_df,
        predicates_df=predicates_quantiles[0],
        random_state=seed,
        show_details=True
    )
    # Armazenar grafo
    graphs_pert_by_seed[seed] = DG  

# Calcular LRC usando a função pronta do explaining.py
lrc_pert_by_seed = {}
for seed in random_seeds:
    DG = graphs_pert_by_seed[seed]
    lrc_pert_df_seed = exp.calculate_lrc_single_graph(DG, predicates_quantiles[0])
    lrc_pert_df_seed['Seed'] = seed  # Adicionar coluna com a semente
    lrc_pert_by_seed[seed] = lrc_pert_df_seed

# junando todas as colunas 'Node' de lrc_by_seed em um único dataframe
lrc_pert_all_seeds_df = pd.DataFrame()
for seed in random_seeds:
    lrc_pert_df_seed = lrc_pert_by_seed[seed].rename(columns={'Node': f'Predicate_pert_Seed_{seed}'})
    lrc_pert_all_seeds_df = pd.concat([lrc_pert_all_seeds_df, lrc_pert_df_seed[[f'Predicate_pert_Seed_{seed}']]], axis=1)

# vamos filtrar lrc_by_seed em cada semente para manter apenas as zonas espectrais únicas com maior LRC em um mesmo dataframe
lrc_pert_unique_by_seed = {}
for seed, lrc_df in lrc_pert_by_seed.items():
    lrc_pert_unique_df = lrc_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
    lrc_pert_unique_df = lrc_pert_unique_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
    lrc_pert_unique_by_seed[seed] = lrc_pert_unique_df

lrc_pert_all_seeds_df # exibindo o dataframe consolidado com predicados de todas as sementes

======================================================================
Processando semente: 0
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 150 | Descartados: 50
======================================================================
PERTURBATION IMPORTANCE PARA PREDICADOS
======================================================================
Valor de perturbação: 0
Métrica: mean_relative_dev
Total de folds: 10


[Bag_1] Processando 150 predicados...
  Predicado: background1 > -0.10 (n=323)
    Zona: 17 colunas
    Importance: 0.000270
  Predicado: background1 <= -0.08 (n=144)
    Zona: 17 colunas
    Importance: -0.000031
  Predicado: background1 > -0.08 (n=256)
    Zona: 17 colunas
    Importance: 0.000349
  Predicado: background1 <= 0.09 (n=227)
    Zona: 17 colunas
    Importance: -0.000016
  Predicado: background1 > 0.09 (n=173)
    Zona: 17 colunas
    Importance: 0.000511
  Predicado: background1 <= 0.12 (n=314)
    Zona: 17 colunas
    Importance: 0.000043
  Predicado: Al > -0.27 (n=322)
    Zona: 15 colunas
    Importance: -0.022958
  Predicado: Al <= -0.14 (n=155)
    Zona: 15 colunas
    Importance: 0.097606
  Predicado: Al > -0.14 (n=245)
    Zona: 15 colunas
    Importance: -0.035876
  Predicado: Al <= 0.16 (n=238)
    Zona: 15 colunas
    Importance: 0.063394
  Predicado: Al > 0.16 (n=162)
    Zona: 15 colunas
    Importance: -0.054003
  Predicado: Al <= 0.29 (n=314)
    Zona: 15 colunas
    Importance: 0.048530
  Predicado: Si > -0.45 (n=323)
    Zona: 12 colunas
    Importance: 0.053922
  Predicado: Si <= -0.25 (n=154)
    Zona: 12 colunas
    Importance: -0.002156
  Predicado: Si > -0.25 (n=246)
    Zona: 12 colunas
    Importance: 0.070779
  Predicado: Si <= 0.18 (n=233)
    Zona: 12 colunas
    Importance: -0.000957
  Predicado: Si > 0.18 (n=167)
    Zona: 12 colunas
    Importance: 0.103608
  Predicado: Si <= 0.51 (n=322)
    Zona: 12 colunas
    Importance: -0.001746
  Predicado: P > -0.19 (n=319)
    Zona: 17 colunas
    Importance: 0.006717
  Predicado: P <= -0.13 (n=157)
    Zona: 17 colunas
    Importance: 0.002147
  Predicado: P > -0.13 (n=243)
    Zona: 17 colunas
    Importance: 0.008950
  Predicado: P <= 0.15 (n=239)
    Zona: 17 colunas
    Importance: 0.003138
  Predicado: P > 0.15 (n=161)
    Zona: 17 colunas
    Importance: 0.010944
  Predicado: P <= 0.25 (n=321)
    Zona: 17 colunas
    Importance: 0.007283
  Predicado: S > -0.12 (n=314)
    Zona: 13 colunas
    Importance: 0.000516
  Predicado: S <= -0.09 (n=151)
    Zona: 13 colunas
    Importance: -0.000256
  Predicado: S > -0.09 (n=249)
    Zona: 13 colunas
    Importance: 0.000715
  Predicado: S <= 0.09 (n=246)
    Zona: 13 colunas
    Importance: -0.000262
  Predicado: S > 0.09 (n=154)
    Zona: 13 colunas
    Importance: 0.001323
  Predicado: S <= 0.13 (n=314)
    Zona: 13 colunas
    Importance: 0.000052
  Predicado: background2 > -0.09 (n=321)
    Zona: 6 colunas
    Importance: 0.000443
  Predicado: background2 <= -0.06 (n=164)
    Zona: 6 colunas
    Importance: -0.000093
  Predicado: background2 > -0.06 (n=236)
    Zona: 6 colunas
    Importance: 0.000586
  Predicado: background2 <= 0.07 (n=242)
    Zona: 6 colunas
    Importance: 0.000058
  Predicado: background2 > 0.07 (n=158)
    Zona: 6 colunas
    Importance: 0.000690
  Predicado: background2 <= 0.10 (n=312)
    Zona: 6 colunas
    Importance: 0.000070
  Predicado: Rh L + Ar > -0.26 (n=320)
    Zona: 33 colunas
    Importance: 0.053457
  Predicado: Rh L + Ar <= -0.21 (n=145)
    Zona: 33 colunas
    Importance: -0.004392
  Predicado: Rh L + Ar > -0.21 (n=255)
    Zona: 33 colunas
    Importance: 0.068101
  Predicado: Rh L + Ar <= 0.27 (n=238)
    Zona: 33 colunas
    Importance: -0.003709
  Predicado: Rh L + Ar > 0.27 (n=162)
    Zona: 33 colunas
    Importance: 0.108713
  Predicado: Rh L + Ar <= 0.36 (n=317)
    Zona: 33 colunas
    Importance: -0.001358
  Predicado: K > -0.20 (n=319)
    Zona: 16 colunas
    Importance: 0.054365
  Predicado: K <= -0.13 (n=160)
    Zona: 16 colunas
    Importance: -0.007171
  Predicado: K > -0.13 (n=240)
    Zona: 16 colunas
    Importance: 0.072757
  Predicado: K <= 0.09 (n=243)
    Zona: 16 colunas
    Importance: -0.004673
  Predicado: K > 0.09 (n=157)
    Zona: 16 colunas
    Importance: 0.111145
  Predicado: K <= 0.17 (n=319)
    Zona: 16 colunas
    Importance: -0.003562
  Predicado: Ca ka > -0.82 (n=321)
    Zona: 16 colunas
    Importance: 0.711221
  Predicado: Ca ka <= -0.55 (n=160)
    Zona: 16 colunas
    Importance: -0.083696
  Predicado: Ca ka > -0.55 (n=240)
    Zona: 16 colunas
    Importance: 0.947552
  Predicado: Ca ka <= -0.20 (n=239)
    Zona: 16 colunas
    Importance: -0.127472
  Predicado: Ca ka > -0.20 (n=161)
    Zona: 16 colunas
    Importance: 1.518553
  Predicado: Ca ka <= 0.76 (n=316)
    Zona: 16 colunas
    Importance: -0.098781
  Predicado: Ca kb > -0.24 (n=321)
    Zona: 16 colunas
    Importance: 0.047686
  Predicado: Ca kb <= -0.18 (n=153)
    Zona: 16 colunas
    Importance: -0.005808
  Predicado: Ca kb > -0.18 (n=247)
    Zona: 16 colunas
    Importance: 0.063692
  Predicado: Ca kb <= 0.12 (n=236)
    Zona: 16 colunas
    Importance: -0.003567
  Predicado: Ca kb > 0.12 (n=164)
    Zona: 16 colunas
    Importance: 0.095641
  Predicado: Ca kb <= 0.23 (n=319)
    Zona: 16 colunas
    Importance: -0.001058
  Predicado: background3 > -0.16 (n=329)
    Zona: 12 colunas
    Importance: -0.010981
  Predicado: background3 <= -0.09 (n=160)
    Zona: 12 colunas
    Importance: 0.000435
  Predicado: background3 > -0.09 (n=240)
    Zona: 12 colunas
    Importance: -0.015128
  Predicado: background3 <= 0.12 (n=235)
    Zona: 12 colunas
    Importance: 0.000329
  Predicado: background3 > 0.12 (n=165)
    Zona: 12 colunas
    Importance: -0.022052
  Predicado: background3 <= 0.18 (n=316)
    Zona: 12 colunas
    Importance: -0.000250
  Predicado: Ti ka > -0.84 (n=322)
    Zona: 15 colunas
    Importance: -1.515575
  Predicado: Ti ka <= -0.37 (n=156)
    Zona: 15 colunas
    Importance: 0.069416
  Predicado: Ti ka > -0.37 (n=244)
    Zona: 15 colunas
    Importance: -1.957968
  Predicado: Ti ka <= 0.45 (n=236)
    Zona: 15 colunas
    Importance: 0.046843
  Predicado: Ti ka > 0.45 (n=164)
    Zona: 15 colunas
    Importance: -2.914452
  Predicado: Ti ka <= 0.92 (n=313)
    Zona: 15 colunas
    Importance: -0.105839
  Predicado: background4 > -0.29 (n=320)
    Zona: 5 colunas
    Importance: -0.002217
  Predicado: background4 <= -0.17 (n=153)
    Zona: 5 colunas
    Importance: 0.000151
  Predicado: background4 > -0.17 (n=247)
    Zona: 5 colunas
    Importance: -0.002909
  Predicado: background4 <= 0.09 (n=235)
    Zona: 5 colunas
    Importance: 0.000059
  Predicado: background4 > 0.09 (n=165)
    Zona: 5 colunas
    Importance: -0.004299
  Predicado: background4 <= 0.35 (n=315)
    Zona: 5 colunas
    Importance: -0.000328
  Predicado: Ti kb > -0.42 (n=321)
    Zona: 19 colunas
    Importance: -0.126079
  Predicado: Ti kb <= -0.23 (n=158)
    Zona: 19 colunas
    Importance: 0.008395
  Predicado: Ti kb > -0.23 (n=242)
    Zona: 19 colunas
    Importance: -0.170059
  Predicado: Ti kb <= 0.24 (n=236)
    Zona: 19 colunas
    Importance: 0.005843
  Predicado: Ti kb > 0.24 (n=164)
    Zona: 19 colunas
    Importance: -0.251262
  Predicado: Ti kb <= 0.48 (n=318)
    Zona: 19 colunas
    Importance: 0.001495
  Predicado: Cr > -0.26 (n=321)
    Zona: 33 colunas
    Importance: -0.009424
  Predicado: Cr <= -0.17 (n=155)
    Zona: 33 colunas
    Importance: 0.000864
  Predicado: Cr > -0.17 (n=245)
    Zona: 33 colunas
    Importance: -0.012458
  Predicado: Cr <= 0.17 (n=233)
    Zona: 33 colunas
    Importance: 0.000962
  Predicado: Cr > 0.17 (n=167)
    Zona: 33 colunas
    Importance: -0.018817
  Predicado: Cr <= 0.28 (n=312)
    Zona: 33 colunas
    Importance: -0.008067
  Predicado: Mn > -0.47 (n=322)
    Zona: 18 colunas
    Importance: 0.386466
  Predicado: Mn <= -0.33 (n=153)
    Zona: 18 colunas
    Importance: -0.014036
  Predicado: Mn > -0.33 (n=247)
    Zona: 18 colunas
    Importance: 0.507602
  Predicado: Mn <= 0.22 (n=235)
    Zona: 18 colunas
    Importance: -0.010603
  Predicado: Mn > 0.22 (n=165)
    Zona: 18 colunas
    Importance: 0.761951
  Predicado: Mn <= 0.47 (n=315)
    Zona: 18 colunas
    Importance: 0.014183
  Predicado: Fe ka > -3.73 (n=320)
    Zona: 34 colunas
    Importance: 4.809383
  Predicado: Fe ka <= -2.42 (n=157)
    Zona: 34 colunas
    Importance: -0.418634
  Predicado: Fe ka > -2.42 (n=243)
    Zona: 34 colunas
    Importance: 6.440885
  Predicado: Fe ka <= 2.41 (n=238)
    Zona: 34 colunas
    Importance: -0.308004
  Predicado: Fe ka > 2.41 (n=162)
    Zona: 34 colunas
    Importance: 9.708114
  Predicado: Fe ka <= 4.61 (n=316)
    Zona: 34 colunas
    Importance: 1.506948
  Predicado: Fe kb > -1.37 (n=320)
    Zona: 26 colunas
    Importance: 0.579031
  Predicado: Fe kb <= -0.88 (n=158)
    Zona: 26 colunas
    Importance: -0.051506
  Predicado: Fe kb > -0.88 (n=242)
    Zona: 26 colunas
    Importance: 0.778998
  Predicado: Fe kb <= 0.90 (n=237)
    Zona: 26 colunas
    Importance: -0.038066
  Predicado: Fe kb > 0.90 (n=163)
    Zona: 26 colunas
    Importance: 1.161970
  Predicado: Fe kb <= 1.68 (n=315)
    Zona: 26 colunas
    Importance: 0.648281
  Predicado: background5 > -0.15 (n=329)
    Zona: 31 colunas
    Importance: 0.009060
  Predicado: background5 <= -0.10 (n=159)
    Zona: 31 colunas
    Importance: 0.019302
  Predicado: background5 > -0.10 (n=241)
    Zona: 31 colunas
    Importance: -0.004015
  Predicado: background5 <= 0.12 (n=230)
    Zona: 31 colunas
    Importance: 0.014800
  Predicado: background5 > 0.12 (n=170)
    Zona: 31 colunas
    Importance: -0.007663
  Predicado: background5 <= 0.16 (n=317)
    Zona: 31 colunas
    Importance: 0.010187
  Predicado: Cu > -0.22 (n=322)
    Zona: 15 colunas
    Importance: 0.013743
  Predicado: Cu <= -0.16 (n=151)
    Zona: 15 colunas
    Importance: -0.001596
  Predicado: Cu > -0.16 (n=249)
    Zona: 15 colunas
    Importance: 0.018139
  Predicado: Cu <= 0.15 (n=233)
    Zona: 15 colunas
    Importance: 0.007681
  Predicado: Cu > 0.15 (n=167)
    Zona: 15 colunas
    Importance: 0.014887
  Predicado: Cu <= 0.25 (n=316)
    Zona: 15 colunas
    Importance: 0.009122
  Predicado: background6 > -0.16 (n=314)
    Zona: 125 colunas
    Importance: 0.001961
  Predicado: background6 <= -0.13 (n=163)
    Zona: 125 colunas
    Importance: 0.122167
  Predicado: background6 > -0.13 (n=237)
    Zona: 125 colunas
    Importance: -0.009667
  Predicado: background6 <= 0.14 (n=248)
    Zona: 125 colunas
    Importance: 0.079160
  Predicado: background6 > 0.14 (n=152)
    Zona: 125 colunas
    Importance: -0.013222
  Predicado: background6 <= 0.18 (n=319)
    Zona: 125 colunas
    Importance: 0.057569
  Predicado: Fe ka + Ti ka > -0.15 (n=317)
    Zona: 23 colunas
    Importance: -0.016320
  Predicado: Fe ka + Ti ka <= -0.11 (n=149)
    Zona: 23 colunas
    Importance: -0.000226
  Predicado: Fe ka + Ti ka > -0.11 (n=251)
    Zona: 23 colunas
    Importance: -0.020828
  Predicado: Fe ka + Ti ka <= 0.13 (n=245)
    Zona: 23 colunas
    Importance: -0.000491
  Predicado: Fe ka + Ti ka > 0.13 (n=155)
    Zona: 23 colunas
    Importance: -0.033169
  Predicado: Fe ka + Ti ka <= 0.17 (n=319)
    Zona: 23 colunas
    Importance: -0.000158
  Predicado: background7 > -0.15 (n=326)
    Zona: 71 colunas
    Importance: -0.003045
  Predicado: background7 <= -0.12 (n=152)
    Zona: 71 colunas
    Importance: 0.010358
  Predicado: background7 > -0.12 (n=248)
    Zona: 71 colunas
    Importance: -0.000360
  Predicado: background7 <= 0.12 (n=244)
    Zona: 71 colunas
    Importance: 0.010451
  Predicado: background7 > 0.12 (n=156)
    Zona: 71 colunas
    Importance: -0.006826
  Predicado: background7 <= 0.16 (n=321)
    Zona: 71 colunas
    Importance: 0.005400
  Predicado: sum Fe > -0.41 (n=320)
    Zona: 28 colunas
    Importance: 0.046985
  Predicado: sum Fe <= -0.27 (n=155)
    Zona: 28 colunas
    Importance: -0.004077
  Predicado: sum Fe > -0.27 (n=245)
    Zona: 28 colunas
    Importance: 0.062459
  Predicado: sum Fe <= 0.26 (n=235)
    Zona: 28 colunas
    Importance: -0.002196
  Predicado: sum Fe > 0.26 (n=165)
    Zona: 28 colunas
    Importance: 0.092040
  Predicado: sum Fe <= 0.51 (n=320)
    Zona: 28 colunas
    Importance: 0.050655
  Predicado: background8 > -0.22 (n=324)
    Zona: 96 colunas
    Importance: 0.002865
  Predicado: background8 <= -0.15 (n=151)
    Zona: 96 colunas
    Importance: -0.000213
  Predicado: background8 > -0.15 (n=249)
    Zona: 96 colunas
    Importance: 0.003801
  Predicado: background8 <= 0.16 (n=232)
    Zona: 96 colunas
    Importance: -0.000055
  Predicado: background8 > 0.16 (n=168)
    Zona: 96 colunas
    Importance: 0.005519
  Predicado: background8 <= 0.27 (n=323)
    Zona: 96 colunas
    Importance: -0.000436

[Bag_2] Processando 150 predicados...
  Predicado: background1 > -0.10 (n=313)
    Zona: 17 colunas
    Importance: 0.000131
  Predicado: background1 <= -0.08 (n=155)
    Zona: 17 colunas
    Importance: -0.000038
  Predicado: background1 > -0.08 (n=245)
    Zona: 17 colunas
    Importance: 0.000176
  Predicado: background1 <= 0.09 (n=242)
    Zona: 17 colunas
    Importance: -0.000022
  Predicado: background1 > 0.09 (n=158)
    Zona: 17 colunas
    Importance: 0.000269
  Predicado: background1 <= 0.12 (n=320)
    Zona: 17 colunas
    Importance: 0.000109
  Predicado: Al > -0.27 (n=320)
    Zona: 15 colunas
    Importance: -0.019278
  Predicado: Al <= -0.14 (n=166)
    Zona: 15 colunas
    Importance: 0.087715
  Predicado: Al > -0.14 (n=234)
    Zona: 15 colunas
    Importance: -0.029680
  Predicado: Al <= 0.16 (n=249)
    Zona: 15 colunas
    Importance: 0.058355
  Predicado: Al > 0.16 (n=151)
    Zona: 15 colunas
    Importance: -0.045794
  Predicado: Al <= 0.29 (n=320)
    Zona: 15 colunas
    Importance: 0.030372
  Predicado: Si > -0.45 (n=322)
    Zona: 12 colunas
    Importance: 0.048553
  Predicado: Si <= -0.25 (n=164)
    Zona: 12 colunas
    Importance: -0.002849
  Predicado: Si > -0.25 (n=236)
    Zona: 12 colunas
    Importance: 0.066622
  Predicado: Si <= 0.18 (n=244)
    Zona: 12 colunas
    Importance: -0.001533
  Predicado: Si > 0.18 (n=156)
    Zona: 12 colunas
    Importance: 0.100189
  Predicado: Si <= 0.51 (n=321)
    Zona: 12 colunas
    Importance: -0.003079
  Predicado: P > -0.19 (n=326)
    Zona: 17 colunas
    Importance: 0.001529
  Predicado: P <= -0.13 (n=155)
    Zona: 17 colunas
    Importance: 0.000172
  Predicado: P > -0.13 (n=245)
    Zona: 17 colunas
    Importance: 0.002910
  Predicado: P <= 0.15 (n=238)
    Zona: 17 colunas
    Importance: 0.000498
  Predicado: P > 0.15 (n=162)
    Zona: 17 colunas
    Importance: 0.003834
  Predicado: P <= 0.25 (n=315)
    Zona: 17 colunas
    Importance: 0.002526
  Predicado: S > -0.12 (n=315)
    Zona: 13 colunas
    Importance: 0.000565
  Predicado: S <= -0.09 (n=155)
    Zona: 13 colunas
    Importance: -0.000085
  Predicado: S > -0.09 (n=245)
    Zona: 13 colunas
    Importance: 0.000799
  Predicado: S <= 0.09 (n=248)
    Zona: 13 colunas
    Importance: -0.000148
  Predicado: S > 0.09 (n=152)
    Zona: 13 colunas
    Importance: 0.001443
  Predicado: S <= 0.13 (n=317)
    Zona: 13 colunas
    Importance: 0.000005
  Predicado: background2 > -0.09 (n=320)
    Zona: 6 colunas
    Importance: -0.000179
  Predicado: background2 <= -0.06 (n=163)
    Zona: 6 colunas
    Importance: -0.000130
  Predicado: background2 > -0.06 (n=237)
    Zona: 6 colunas
    Importance: -0.000241
  Predicado: background2 <= 0.07 (n=252)
    Zona: 6 colunas
    Importance: -0.000105
  Predicado: background2 > 0.07 (n=148)
    Zona: 6 colunas
    Importance: -0.000349
  Predicado: background2 <= 0.10 (n=318)
    Zona: 6 colunas
    Importance: -0.000228
  Predicado: Rh L + Ar > -0.26 (n=312)
    Zona: 33 colunas
    Importance: 0.045446
  Predicado: Rh L + Ar <= -0.21 (n=154)
    Zona: 33 colunas
    Importance: -0.004507
  Predicado: Rh L + Ar > -0.21 (n=246)
    Zona: 33 colunas
    Importance: 0.058740
  Predicado: Rh L + Ar <= 0.27 (n=243)
    Zona: 33 colunas
    Importance: -0.003807
  Predicado: Rh L + Ar > 0.27 (n=157)
    Zona: 33 colunas
    Importance: 0.093510
  Predicado: Rh L + Ar <= 0.36 (n=320)
    Zona: 33 colunas
    Importance: 0.012810
  Predicado: K > -0.20 (n=317)
    Zona: 16 colunas
    Importance: 0.058341
  Predicado: K <= -0.13 (n=155)
    Zona: 16 colunas
    Importance: -0.002629
  Predicado: K > -0.13 (n=245)
    Zona: 16 colunas
    Importance: 0.075679
  Predicado: K <= 0.09 (n=240)
    Zona: 16 colunas
    Importance: -0.001712
  Predicado: K > 0.09 (n=160)
    Zona: 16 colunas
    Importance: 0.115904
  Predicado: K <= 0.17 (n=315)
    Zona: 16 colunas
    Importance: -0.001243
  Predicado: Ca ka > -0.82 (n=324)
    Zona: 16 colunas
    Importance: 0.629841
  Predicado: Ca ka <= -0.55 (n=152)
    Zona: 16 colunas
    Importance: 0.014804
  Predicado: Ca ka > -0.55 (n=248)
    Zona: 16 colunas
    Importance: 0.806799
  Predicado: Ca ka <= -0.20 (n=233)
    Zona: 16 colunas
    Importance: -0.023141
  Predicado: Ca ka > -0.20 (n=167)
    Zona: 16 colunas
    Importance: 1.243882
  Predicado: Ca ka <= 0.76 (n=315)
    Zona: 16 colunas
    Importance: 0.041888
  Predicado: Ca kb > -0.24 (n=316)
    Zona: 16 colunas
    Importance: 0.046214
  Predicado: Ca kb <= -0.18 (n=151)
    Zona: 16 colunas
    Importance: -0.004946
  Predicado: Ca kb > -0.18 (n=249)
    Zona: 16 colunas
    Importance: 0.060033
  Predicado: Ca kb <= 0.12 (n=240)
    Zona: 16 colunas
    Importance: -0.002258
  Predicado: Ca kb > 0.12 (n=160)
    Zona: 16 colunas
    Importance: 0.092146
  Predicado: Ca kb <= 0.23 (n=319)
    Zona: 16 colunas
    Importance: 0.006078
  Predicado: background3 > -0.16 (n=325)
    Zona: 12 colunas
    Importance: -0.009861
  Predicado: background3 <= -0.09 (n=170)
    Zona: 12 colunas
    Importance: 0.000450
  Predicado: background3 > -0.09 (n=230)
    Zona: 12 colunas
    Importance: -0.014034
  Predicado: background3 <= 0.12 (n=245)
    Zona: 12 colunas
    Importance: 0.000310
  Predicado: background3 > 0.12 (n=155)
    Zona: 12 colunas
    Importance: -0.020821
  Predicado: background3 <= 0.18 (n=324)
    Zona: 12 colunas
    Importance: -0.000267
  Predicado: Ti ka > -0.84 (n=322)
    Zona: 15 colunas
    Importance: -1.404099
  Predicado: Ti ka <= -0.37 (n=163)
    Zona: 15 colunas
    Importance: 0.072717
  Predicado: Ti ka > -0.37 (n=237)
    Zona: 15 colunas
    Importance: -1.876284
  Predicado: Ti ka <= 0.45 (n=238)
    Zona: 15 colunas
    Importance: 0.050463
  Predicado: Ti ka > 0.45 (n=162)
    Zona: 15 colunas
    Importance: -2.745905
  Predicado: Ti ka <= 0.92 (n=317)
    Zona: 15 colunas
    Importance: -0.137416
  Predicado: background4 > -0.29 (n=317)
    Zona: 5 colunas
    Importance: -0.002137
  Predicado: background4 <= -0.17 (n=162)
    Zona: 5 colunas
    Importance: 0.000148
  Predicado: background4 > -0.17 (n=238)
    Zona: 5 colunas
    Importance: -0.002886
  Predicado: background4 <= 0.09 (n=246)
    Zona: 5 colunas
    Importance: 0.000061
  Predicado: background4 > 0.09 (n=154)

/home/jvribeiro/.local/lib/python3.10/site-packages/networkx/algorithms/centrality/reaching.py:193: RuntimeWarning:

divide by zero encountered in scalar divide

Processando LRC do grafo...

/home/jvribeiro/.local/lib/python3.10/site-packages/networkx/algorithms/centrality/reaching.py:193: RuntimeWarning:

divide by zero encountered in scalar divide

Processando LRC do grafo...

/home/jvribeiro/.local/lib/python3.10/site-packages/networkx/algorithms/centrality/reaching.py:193: RuntimeWarning:

divide by zero encountered in scalar divide

Processando LRC do grafo...

/home/jvribeiro/.local/lib/python3.10/site-packages/networkx/algorithms/centrality/reaching.py:193: RuntimeWarning:

divide by zero encountered in scalar divide

,Predicate_pert_Seed_0,Predicate_pert_Seed_1,Predicate_pert_Seed_2,Predicate_pert_Seed_3
0,Fe ka > 2.41,Fe ka > 2.41,Fe ka > 2.41,Fe ka > 2.41
1,Fe ka > -2.42,Fe ka > -2.42,Fe ka > -2.42,Fe ka > -2.42
2,Fe ka > -3.73,Fe ka > -3.73,Fe ka > -3.73,Mn > -0.33
3,Ti ka > 0.45,Fe ka <= 4.61,Fe ka <= -2.42,Fe ka > -3.73
4,Ca ka > -0.82,Ti ka > 0.45,Ti ka > 0.45,Ca ka > -0.82
...,...,...,...,...
147,background6 > 0.14,K <= -0.13,background8 > 0.16,background2 > -0.06
148,background1 > 0.09,background3 <= -0.09,Fe ka + Ti ka <= -0.11,background4 > 0.09
149,Ca ka <= -0.55,S > 0.09,S > 0.09,K <= -0.13
150,Class_A,Class_A,Class_A,Class_A
151,Class_B,Class_B,Class_B,Class_B

In [14]:
all_results_pert[0]['pert_results_dict']['Bag_5']

                 Predicate  Perturbation
0             Fe ka > 2.41      7.226374
1            Fe ka > -2.42      4.673912
2            Fe ka > -3.73      3.541518
3             Ti ka > 0.45      2.572715
4            Ti ka > -0.37      1.800190
..                     ...           ...
145    background2 <= 0.10      0.000047
146  Fe ka + Ti ka <= 0.13      0.000045
147    background1 <= 0.12      0.000038
148   background1 <= -0.08      0.000038
149    background1 <= 0.09      0.000022

[150 rows x 2 columns]

In [15]:
from collections import defaultdict

# Coletar posições de cada predicado em cada seed do lrc_pert_all_seeds_df
positions_dict_lrc = defaultdict(list) # o defaultdict cria listas vazias automaticamente

# Iterar sobre cada coluna do dataframe lrc_pert_all_seeds_df
for col in lrc_pert_all_seeds_df.columns:
    # Pegar os predicados da coluna (não-nulos)
    predicates_in_seed = lrc_pert_all_seeds_df[col].dropna().tolist()
    
    # Para cada predicado, guardar sua posição (1-based)
    for position, predicate in enumerate(predicates_in_seed, start=1):
        positions_dict_lrc[predicate].append(position)

# Calcular média e número de aparições
results_lrc = []
for predicate, positions in positions_dict_lrc.items():
    zone_row = predicates_quantiles[0].loc[predicates_quantiles[0]['rule'] == predicate, 'zone']
    zone_value = zone_row.values[0] if not zone_row.empty else None
    results_lrc.append({
        'Predicate': predicate,
        'Mean_Position': np.mean(positions),
        'Appearances': len(positions),
        'Zone': zone_value
    })

# Ordenar: menor posição média primeiro, mais aparições em caso de empate
ranking_lrc_pert_df = pd.DataFrame(results_lrc).sort_values(
    by=['Mean_Position', 'Appearances'], 
    ascending=[True, False]
).reset_index(drop=True)

# Lista final ordenada
lista_ordenada_lrc = ranking_lrc_pert_df['Predicate'].tolist()
ranking_lrc_pert_df

                  Predicate  Mean_Position  Appearances           Zone
0              Fe ka > 2.41           1.00            4          Fe ka
1             Fe ka > -2.42           2.00            4          Fe ka
2             Fe ka > -3.73           3.25            4          Fe ka
3              Ti ka > 0.45           6.75            4          Ti ka
4                Mn > -0.33           6.75            4             Mn
..                      ...            ...          ...            ...
147  Fe ka + Ti ka <= -0.11         138.50            4  Fe ka + Ti ka
148      background1 > 0.09         140.25            4    background1
149              K <= -0.13         146.75            4              K
150                 Class_A         151.00            4           None
151                 Class_B         152.00            4           None

[152 rows x 4 columns]

In [16]:
ranking_pert_lrc_unique_df = ranking_lrc_pert_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
ranking_pert_lrc_unique_df['Zone']

0             Fe ka
1             Ti ka
2                Mn
3             Fe kb
4             Ca ka
5             Ti kb
6     Fe ka + Ti ka
7       background1
8       background2
9                Si
10      background3
11                K
12            Ca kb
13               Cr
14        Rh L + Ar
15      background6
16      background4
17               Cu
18      background5
19                S
20           sum Fe
21               Al
22      background8
23      background7
24                P
25             None
Name: Zone, dtype: object

In [17]:
with pd.ExcelWriter('Perturbation_method.xlsx') as writer:
    # Primeiro: salvar os rankings médios
    ranking_lrc_pert_df.to_excel(writer, sheet_name='Mean_LRC', index=False)
    ranking_pert_lrc_unique_df.to_excel(writer, sheet_name='Mean_LRC_Unique', index=False)
    
    # Segundo: salvar os LRCs por seed
    for seed in random_seeds:
        lrc_pert_by_seed[seed].to_excel(writer, sheet_name=f'LRC_seed_{seed}', index=False)
    
    # Terceiro: salvar os resultados de perturbação por bag e seed
    for seed in random_seeds:
        for bag_name, df in all_results_pert[seed]['pert_results_dict'].items():
            # Criar nome único: seed_0_Bag_1, seed_1_Bag_1, etc.
            sheet_name = f'seed_{seed}_{bag_name}'[:31]  # Excel limita a 31 caracteres
            df.to_excel(writer, sheet_name=sheet_name, index=False)

# **Permutation**

In [18]:
ranking_perm_lrc_unique_df = pd.read_excel('Permutation_method.xlsx', sheet_name='Mean_LRC_Unique')
ranking_perm_lrc_unique_df['Zone']

0             Ca ka
1             Fe ka
2             Ti ka
3             Fe kb
4                Mn
5             Ti kb
6       background6
7                 K
8       background7
9         Rh L + Ar
10           sum Fe
11            Ca kb
12               Al
13               Si
14      background5
15               Cr
16               Cu
17    Fe ka + Ti ka
18                P
19      background3
20      background4
21      background8
22                S
23      background2
24      background1
25              NaN
Name: Zone, dtype: object

In [19]:
import numpy as np

max_len = max(
    len(vip_scores_unique_df['Zone']),
    len(reg_vet_unique_df['Zone']),
    len(shap_unique_df['Zone']),
    len(ranking_pert_lrc_unique_df['Zone']),
    len(ranking_perm_lrc_unique_df['Zone']),
    len(ranking_cov_lrc_unique_df['Zone'])
)

def pad_list(lst, length):
    return list(lst) + [None] * (length - len(lst))

features_importance = pd.DataFrame({
    'Vip': pad_list(vip_scores_unique_df['Zone'], max_len),
    'Reg_coef': pad_list(reg_vet_unique_df['Zone'], max_len),
    'Shap': pad_list(shap_unique_df['Zone'], max_len),
    'LRC_cov' : pad_list(ranking_cov_lrc_unique_df['Zone'], max_len),
    'LRC_pert' : pad_list(ranking_pert_lrc_unique_df['Zone'], max_len),
    'LRC_perm' : pad_list(ranking_perm_lrc_unique_df['Zone'], max_len)
})

features_importance.to_csv('feature_importance.csv', index=False, sep=';')
features_importance

,Vip,Reg_coef,Shap,LRC_cov,LRC_pert,LRC_perm
0,Fe ka,Fe ka,Fe ka,Fe ka,Fe ka,Ca ka
1,Fe kb,Ca ka,Ca ka,Fe kb,Ti ka,Fe ka
2,Ti ka,Ti ka,Ti ka,Mn,Mn,Ti ka
3,Ca ka,Fe kb,Mn,sum Fe,Fe kb,Fe kb
4,Mn,Mn,Fe kb,Cr,Ca ka,Mn
5,sum Fe,Al,Al,Ti ka,Ti kb,Ti kb
6,Ti kb,Rh L + Ar,background6,Rh L + Ar,Fe ka + Ti ka,background6
7,Al,Ca kb,Fe ka + Ti ka,Ti kb,background1,K
8,Si,K,background7,Si,background2,background7
9,background4,Ti kb,background8,background4,Si,Rh L + Ar
10,Cr,Cu,background1,Cu,background3,sum Fe
11,Rh L + Ar,background6,sum Fe,Ca ka,K,Ca kb
12,Cu,sum Fe,Rh L + Ar,background8,Ca kb,Al
13,Ca kb,Cr,K,Al,Cr,Si
14,background8,P,Cu,background1,Rh L + Ar,background5
15,K,background3,Ca kb,background3,background6,Cr
16,background3,background7,background3,Ca kb,background4,Cu
17,P,background5,Si,background7,Cu,Fe ka + Ti ka
18,background6,Fe ka + Ti ka,S,background2,background5,P
19,Fe ka + Ti ka,background2,background2,K,S,background3
20,background7,Si,P,background6,sum Fe,background4
21,background5,background8,background5,P,Al,background8
22,background2,S,Ti kb,S,background8,S
23,background1,background4,Cr,Fe ka + Ti ka,background7,background2
24,S,background1,background4,None,P,background1
25,None,None,None,None,None,NaN

In [20]:
# RBO (Rank-Biased Overlap) para comparar rankings
import rbo
rbo_results = {}
reference_list = [x for x in features_importance['Vip'].tolist() if x is not None]
methods = ['Reg_coef', 'Shap', 'LRC_cov', 'LRC_pert', 'LRC_perm']
for method in methods:
    compare_list = [x for x in features_importance[method].tolist() if x is not None]
    # Truncate both lists to the same length (minimum of both)
    min_len = min(len(reference_list), len(compare_list))
    ref_trunc = reference_list[:min_len]
    cmp_trunc = compare_list[:min_len]
    score = rbo.RankingSimilarity(ref_trunc, cmp_trunc).rbo(p=0.7, k=10)
    rbo_results[method] = score
rbo_results = pd.DataFrame(list(rbo_results.items()), columns=['Method','RBO_Score'])
rbo_results.insert(0, 'Reference', 'Vip')
rbo_results.sort_values(by='RBO_Score', ascending=False, inplace=True)
rbo_results.to_csv('rbo_rank.csv', index=False, sep=';')
rbo_results

  Reference    Method  RBO_Score
2       Vip   LRC_cov   0.811562
0       Vip  Reg_coef   0.783692
3       Vip  LRC_pert   0.763009
1       Vip      Shap   0.756756
4       Vip  LRC_perm   0.487523