# **Model**

# **XRF milk database**

In [4]:
# Importing the necessary libraries
import pandas as pd
import numpy as np
import kennard_stone as ks
pd.options.plotting.backend = 'plotly'  # setting plotly as the backend for pandas plotting

# Add parent directory to sys.path so local module 'synthetic' (one level up) can be imported
import sys
from pathlib import Path # for path manipulations
parent_dir = Path.cwd().parent.parent.resolve() # move two levels up from current working directory
if str(parent_dir) not in sys.path: # check to avoid duplicates
    sys.path.insert(0, str(parent_dir)) # insert at the start of sys.path to prioritize local modules

# Loading a soil spectral dataset based on X-ray fluorescence (XRF)
data_complete = pd.read_csv(f'{parent_dir}/XRF_databases/ecigar/plsda/ecigar.csv', sep=';') # local copy of Toledo 2022 dataset
data = data_complete.loc[:, '0.997':'20.007']
#data.insert(0, 'exCa', data_complete['exCa'])  # inserting the target variable (e.g., exCa (exchangeable calcium))

# Creating a new column 'Class' based on the condition of the samples in the 'Type' column being 'Authentic'
data_A = data_complete[data_complete['Class'] == 'A'].reset_index(drop=True)
data_B = data_complete[data_complete['Class'] == 'B'].reset_index(drop=True)

# splitting the data into calibration and prediction sets by kennard-stone algorithm
XA_cal, XA_pred = ks.train_test_split(data_A.loc[:, '0.997':'20.007'], test_size=0.30) # class A
XA_cal = XA_cal.reset_index(drop=True)
XA_pred = XA_pred.reset_index(drop=True)

XB_cal, XB_pred = ks.train_test_split(data_B.loc[:, '0.997':'20.007'], test_size=0.30) # class B
XB_cal = XB_cal.reset_index(drop=True)
XB_pred = XB_pred.reset_index(drop=True)

Xcalclass = pd.concat([XA_cal, XB_cal], axis=0).reset_index(drop=True) # concatenating both classes
Xpredclass = pd.concat([XA_pred, XB_pred], axis=0).reset_index(drop=True)
ycalclass = pd.Series(['A']*XA_cal.shape[0] + ['B']*XB_cal.shape[0]) # creating the target variable for calibration set
ypredclass = pd.Series(['A']*XA_pred.shape[0] + ['B']*XB_pred.shape[0]) # creating the target variable for prediction set

# preprocessings
import preprocessings as prepr # preprocessing methods for XRF data

Xcalclass_prep, mean_calclass, mean_calclass_poisson  = prepr.poisson(Xcalclass, mc=True)
Xpredclass_prep = ((Xpredclass/np.sqrt(mean_calclass)) - mean_calclass_poisson)

from modeling import pls_optimized

# performing PLS-DA with optimized latent variables
plsda_results = pls_optimized(Xcalclass_prep, 
                              ycalclass,
                              LVmax=3,
                              Xpred=Xpredclass_prep,
                              ypred=ypredclass,
                              aim='classification',
                              cv=10)
plsda_results[0]

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-01-29 09:26:43,092 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-01-29 09:26:43,099 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-01-29 09:26:43,132 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-01-29 09:26:43,135 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

,LVs,Accuracy Cal,Sensitivity Cal,Specificity Cal,CM Cal,Accuracy CV,Sensitivity CV,Specificity CV,CM CV,Accuracy Pred,Sensitivity Pred,Specificity Pred,CM Pred,X Cum Exp Var,Y Cum Exp Var,X Ind Exp Var,Y Ind Exp Var
0,1,0.68,0.333333,0.8750,"[[14, 2], [6, 3]]",0.64,0.222222,0.875,"[[14, 2], [7, 2]]",0.545455,0.00,0.857143,"[[6, 1], [4, 0]]",63.224546,7.669394,63.224546,7.669394
1,2,0.80,0.555556,0.9375,"[[15, 1], [4, 5]]",0.56,0.222222,0.750,"[[12, 4], [7, 2]]",0.818182,0.50,1.000000,"[[7, 0], [2, 2]]",69.628977,19.133399,6.404431,11.464005
2,3,0.84,0.777778,0.8750,"[[14, 2], [2, 7]]",0.56,0.222222,0.750,"[[12, 4], [7, 2]]",0.909091,0.75,1.000000,"[[7, 0], [1, 3]]",88.071593,22.397397,18.442616,3.263998

In [8]:
from modeling import svm_optimized

svm_model = svm_optimized(Xcalclass_prep, ycalclass, Xpredclass_prep, ypredclass, aim='classification', kernel='linear')
svm_model[0]

,Model,Accuracy Cal,Sensitivity Cal,Specificity Cal,CM Cal,Accuracy Pred,Sensitivity Pred,Specificity Pred,CM Pred
0,SVC,1.0,1.0,1.0,"[[16, 0], [0, 9]]",0.818182,1.0,0.714286,"[[5, 2], [0, 4]]"

In [9]:
# calculando a covariancia entre cada variável espectral e a predição do modelo SVM
cov_scores = []
y_pred = svm_model[4]['SVC'].values # using the continuous predictions from SVM, extracting as 1D array

for col in Xcalclass_prep.columns:
    x_values = Xcalclass_prep[col].values
    covariance = np.cov(x_values, y_pred)[0, 1] # covariance between x and y
    cov_scores.append(covariance)
cov_scores_df = pd.DataFrame(cov_scores, index=Xcalclass_prep.columns, columns=['Covariance'])
cov_scores_df = np.abs(cov_scores_df)
cov_scores_df.plot()

In [10]:
X_sv = svm_model[3].support_vectors_            # shape (n_SV, n_features)
alpha_dual = svm_model[3].dual_coef_.ravel()    # shape (n_SV,)

# Calculando os coeficientes p usando os vetores de suporte e os multiplicadores de Lagrange
pvetor = pd.DataFrame({'energia' : Xcalclass.columns,
                       'importance': (X_sv.T) @ alpha_dual})
pvetor['importance'] = np.abs(pvetor['importance'])
pvetor['importance'].plot()

In [18]:
# establishing spectral cuts based on expert knowledge of XRF spectra
spectral_cuts = [
('Si', 0.997, 1.920),
('background1', 1.920, 2.413),
('Cl', 2.413, 2.984),
('background2', 2.984, 3.134),
('K', 3.134, 3.479),
('Ca ka', 3.134, 3.839),
('Ca kb', 3.839, 4.104),
('Ti', 4.104, 4.823),
('background3', 4.823, 6.161),
('Fe ka', 6.161, 6.732),
('Fe kb', 6.732, 7.242),
('Ni', 7.242, 7.712),
('Cu', 7.712, 8.348),
('Zn ka', 8.348, 8.963),
('Ga', 8.963, 9.414),
('Zn kb', 9.414, 9.739),
('background4', 9.739, 10.379),
('Pb La', 10.379, 10.725),
('background5', 10.725, 12.391),
('Pb Lb', 12.391, 12.831),
('background6', 12.831, 15.333),
('Mo compton scattering', 15.333, 17.215),
('Mo rayleigh scattering', 17.215, 17.765),
('background7', 17.765, 20.007),
]

In [19]:
import explaining as exp
spectral_zones_class = exp.extract_spectral_zones(Xcalclass_prep, spectral_cuts)
zone_sums_df = exp.aggregate_spectral_zones(spectral_zones_class, aggregator='extreme')
predicates_quantiles = exp.predicates_by_quantiles(zone_sums_df, [0.2, 0.4, 0.6, 0.8])
co_occurrence_matrix_df = predicates_quantiles[2]
predicate_info_dict = exp.create_predicate_info_dict(
    predicates_df=predicates_quantiles[0],
    predicate_indicator_df=predicates_quantiles[1],
    zone_aggregated_df=zone_sums_df,
    y_predicted_numeric=y_pred
)

## Pvector and SHAP

In [20]:
# VIP scores por energia
pvector_df = pd.DataFrame({
    'energy': pvetor['energia'],
    'Pvector': pvetor['importance'].values
})
pvector_df = pvector_df.sort_values(by='Pvector', ascending=False).reset_index(drop=True)
energy_to_zone_vip = {}
for zone_name, start, end in spectral_cuts:
    for e in pvector_df['energy']:
        ef = float(e)
        if start <= ef <= end:
            energy_to_zone_vip[e] = zone_name
pvector_df['Zone'] = pvector_df['energy'].map(energy_to_zone_vip)
pvector_unique_df = pvector_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
pvector_unique_df = pvector_unique_df.sort_values(by='Pvector', ascending=False).reset_index(drop=True)
pvector_unique_df
#shap_unique_df = pd.read_csv('shap_ecigar.csv', sep=';') # loading previously saved shap_unique_df

    energy   Pvector                    Zone
0    2.013  0.003362             background1
1    9.214  0.003335                      Ga
2   14.132  0.002793             background6
3   17.535  0.002475  Mo rayleigh scattering
4      4.5  0.002465                      Ti
5   20.007  0.002194             background7
6   11.886  0.002009             background5
7    6.346  0.001985                   Fe ka
8    2.959  0.001923                      Cl
9    17.21  0.001835   Mo compton scattering
10   1.833  0.001755                      Si
11   3.324  0.001645                   Ca ka
12  10.274  0.001550             background4
13   5.831  0.001479             background3
14   3.014  0.001379             background2
15  10.565  0.001368                   Pb La
16  12.726  0.001312                   Pb Lb
17   7.332  0.001311                      Ni
18   3.944  0.001234                   Ca kb
19   8.268  0.001206                      Cu
20   6.992  0.001201                   Fe kb
21   8.643  0.001033                   Zn ka
22   9.534  0.000988                   Zn kb

# permutation

In [21]:
# Permutation importance baseado em mudança nas probabilidades previstas (predict_proba)
# Medimos a média da diferença absoluta entre as probabilidades originais e as probabilidades
# obtidas após permutar cada variável. Isso fornece uma métrica contínua de importância.
n_repeats = 10
rng = np.random.RandomState(42)
# Probabilidades base (classe 'B' mapeada para 1)
baseline_proba = svm_model[3].predict_proba(Xcalclass_prep)[:, 1]
importance_list = []
X_arr = Xcalclass_prep.copy()
for col in Xcalclass_prep.columns:
    diffs = []
    for _ in range(n_repeats):
        X_perm = X_arr.copy()
        X_perm[col] = rng.permutation(X_perm[col].values)
        perm_proba = svm_model[3].predict_proba(X_perm)[:, 1]
        diffs.append(np.mean(np.abs(baseline_proba - perm_proba)))
    importance_list.append(np.mean(diffs))

permutation_df = pd.DataFrame({
    'energy': Xcalclass_prep.columns,
    'Permutation_importance_proba': importance_list
})
permutation_df.sort_values(by='Permutation_importance_proba', ascending=False, inplace=True)
energy_to_zone_vip = {}
for zone_name, start, end in spectral_cuts:
    for e in permutation_df['energy']:
        ef = float(e)
        if start <= ef <= end:
            energy_to_zone_vip[e] = zone_name
permutation_df['Zone'] = permutation_df['energy'].map(energy_to_zone_vip)
permutation_unique_df = permutation_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
permutation_unique_df = permutation_unique_df.sort_values(by='Permutation_importance_proba', ascending=False)
permutation_unique_df

    energy  Permutation_importance_proba                    Zone
0    2.663                      0.002749                      Cl
1   17.535                      0.002327  Mo rayleigh scattering
2    17.21                      0.001798   Mo compton scattering
3    1.753                      0.001540                      Si
4    3.324                      0.001254                   Ca ka
5    2.008                      0.000809             background1
6    6.371                      0.000703                   Fe ka
7    9.214                      0.000703                      Ga
8    8.623                      0.000567                   Zn ka
9     17.8                      0.000305             background7
10   8.063                      0.000254                      Cu
11   7.512                      0.000224                      Ni
12  14.132                      0.000194             background6
13   9.534                      0.000181                   Zn kb
14   7.077                      0.000166                   Fe kb
15    4.51                      0.000152                      Ti
16  10.565                      0.000151                   Pb La
17  10.274                      0.000127             background4
18    5.22                      0.000120             background3
19  11.886                      0.000118             background5
20  12.641                      0.000112                   Pb Lb
21   3.944                      0.000083                   Ca kb
22   3.059                      0.000072             background2

In [22]:
permutation_unique_df.to_csv('permutation_ecigar.csv', index=False, sep=';')

# **bagging - covariance**

In [23]:
import explaining as exp

# LISTA DE SEMENTES A TESTAR
random_seeds = [0, 1, 2, 3]

all_results_cov = {}
training_samples = len(Xcalclass)

# LOOP: PROCESSAR CADA SEMENTE
y_predicted_numeric = pd.Series(y_pred) # predições numéricas do modelo

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando semente: {seed}")
    print(f"{'='*70}\n")
    # Bagging
    bags_result_seed = exp.bagging_predicates(
        zone_sums_df=zone_sums_df,
        y_predicted_numeric=y_predicted_numeric,
        predicates_df=predicates_quantiles[0],
        n_bags=10,
        #n_predicates_per_bag=40,
        n_samples_per_bag=int(training_samples*0.8), # 80 % da base para amostrar (convertido para int)
        min_samples_per_predicate=int(training_samples*0.2), # 20 % da base para limitar (convertido para int)
        replace=False,
        sample_bagging=True,
        predicate_bagging=False,
        random_seed=seed
    )
    
    # Inserir classe prevista
    for bag_name, pred_dict in bags_result_seed.items(): # iterando sobre cada bag
        for pred_rule, df_info in pred_dict.items():
            df_info['Class_Predicted'] = np.where(df_info['Predicted_Y'] >= 0.5, 'A', 'B') # binarizando com threshold 0.5, A = eut, B = dist
    
    # Calcular MI
    cov_results_dict_seed = exp.calculate_predicate_metrics(
        bags_result=bags_result_seed,
        metric='covariance', # covariance ou mutual_information
        threshold=0.01, # threshold para cortar predicados irrelevantes
        n_neighbors=5
    )
    
    # Salvar no dicionário principal
    all_results_cov[seed] = {
        'bags_result': bags_result_seed,
        'cov_results_dict': cov_results_dict_seed
    }

# CONSTRUÇÃO DE GRAFOS PARA MÚLTIPLAS SEMENTES (LOOP EXTERNO)
# Dicionário para armazenar grafos
graphs_by_seed = {}

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando Grafo - Semente: {seed}")
    print(f"{'='*70}\n")
    # Construir grafo para esta semente
    DG = exp.build_predicate_graphv2(
        bags_result=all_results_cov[seed]['bags_result'],
        predicate_ranking_dict=all_results_cov[seed]['cov_results_dict'],
        metric_column='Covariance',  # ou 'Covariance' se mudar a métrica
        random_state=seed,
        show_details=True
    )
    # Armazenar grafo
    graphs_by_seed[seed] = DG

# Calcular LRC usando a função pronta do explaining.py
lrc_cov_by_seed = {}
for seed in random_seeds:
    DG = graphs_by_seed[seed]
    lrc_cov_df_seed = exp.calculate_lrc_single_graph(DG, predicates_quantiles[0])
    lrc_cov_df_seed['Seed'] = seed  # Adicionar coluna com a semente
    lrc_cov_by_seed[seed] = lrc_cov_df_seed

# junando todas as colunas 'Node' de lrc_by_seed em um único dataframe
lrc_cov_all_seeds_df = pd.DataFrame()
for seed in random_seeds:
    lrc_cov_df_seed = lrc_cov_by_seed[seed].rename(columns={'Node': f'Predicate_Cov_Seed_{seed}'})
    lrc_cov_all_seeds_df = pd.concat([lrc_cov_all_seeds_df, lrc_cov_df_seed[[f'Predicate_Cov_Seed_{seed}']]], axis=1)

# vamos filtrar lrc_by_seed em cada semente para manter apenas as zonas espectrais únicas com maior LRC em um mesmo dataframe
lrc_cov_unique_by_seed = {}
for seed, lrc_df in lrc_cov_by_seed.items():
    lrc_cov_unique_df = lrc_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
    lrc_cov_unique_df = lrc_cov_unique_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
    lrc_cov_unique_by_seed[seed] = lrc_cov_unique_df

lrc_cov_all_seeds_df # exibindo o dataframe consolidado com predicados de todas as sementes

======================================================================
Processando semente: 0
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 156 | Descartados: 36
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 166 | Descartados: 26
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 158 | Descartados: 34
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 154 | Descartados: 38
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 177 | Descartados: 15
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 144 | Descartados: 48
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 165 | Descartados: 27
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 152 | Descartados: 40
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 153 | Descartados: 39
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 164 | Descartados: 28
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando semente: 1
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 165 | Descartados: 27
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 159 | Descartados: 33
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 165 | Descartados: 27
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 167 | Descartados: 25
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 152 | Descartados: 40
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 168 | Descartados: 24
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 157 | Descartados: 35
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 161 | Descartados: 31
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 166 | Descartados: 26
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 149 | Descartados: 43
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando semente: 2
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 165 | Descartados: 27
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 163 | Descartados: 29
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 146 | Descartados: 46
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 163 | Descartados: 29
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 163 | Descartados: 29
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 157 | Descartados: 35
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 154 | Descartados: 38
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 176 | Descartados: 16
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 145 | Descartados: 47
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 162 | Descartados: 30
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando semente: 3
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 164 | Descartados: 28
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 163 | Descartados: 29
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 146 | Descartados: 46
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 157 | Descartados: 35
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 146 | Descartados: 46
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 152 | Descartados: 40
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 159 | Descartados: 33
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 156 | Descartados: 36
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 168 | Descartados: 24
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 155 | Descartados: 37
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando Grafo - Semente: 0
======================================================================


Total de pares bidirecionais encontrados: 76
Removida aresta Cl > -175.25 -> Cu > -19.02 (peso 1.5992)
Mantida aresta Cu > -19.02 -> Cl > -175.25 (peso 1.6813)

======================================================================

Removida aresta Cl > 94.61 -> Cl > -175.25 (peso 1.7787)
Mantida aresta Cl > -175.25 -> Cl > 94.61 (peso 1.8167)

======================================================================

Removida aresta Mo compton scattering > -67.69 -> Mo rayleigh scattering > -71.50 (peso 1.3297)
Mantida aresta Mo rayleigh scattering > -71.50 -> Mo compton scattering > -67.69 (peso 2.2879)

======================================================================

Removida aresta Mo rayleigh scattering > -71.50 -> Si > 44.53 (peso 1.2339)
Mantida aresta Si > 44.53 -> Mo rayleigh scattering > -71.50 (peso 2.2808)

======================================================================

Removida aresta background2 > -0.23 -> Mo compton scattering > -67.69 (peso 0.0792)
Mantida aresta Mo compton scattering > -67.69 -> background2 > -0.23 (peso 0.1177)

======================================================================

Removida aresta Mo compton scattering > -67.69 -> K > -20.13 (peso 0.4540)
Mantida aresta K > -20.13 -> Mo compton scattering > -67.69 (peso 0.4984)

======================================================================

Removida aresta Ni > -10.42 -> Cl > -159.85 (peso 0.6795)
Mantida aresta Cl > -159.85 -> Ni > -10.42 (peso 0.7349)

======================================================================

Removida aresta Cl > -159.85 -> Mo rayleigh scattering > -10.70 (peso 1.6050)
Mantida aresta Mo rayleigh scattering > -10.70 -> Cl > -159.85 (peso 2.4550)

======================================================================

Removida aresta Ca ka > -20.13 -> K > -20.13 (peso 1.6064)
Mantida aresta K > -20.13 -> Ca ka > -20.13 (peso 2.1883)

======================================================================

Removida aresta K > -20.13 -> Si > -52.01 (peso 0.4430)
Mantida aresta Si > -52.01 -> K > -20.13 (peso 0.5108)

======================================================================

Removida aresta Mo rayleigh scattering > 59.43 -> Ca ka > -20.13 (peso 0.5011)
Mantida aresta Ca ka > -20.13 -> Mo rayleigh scattering > 59.43 (peso 0.5902)

======================================================================

Removida aresta Fe ka > -10.29 -> Fe ka > -24.00 (peso 0.6768)
Mantida aresta Fe ka > -24.00 -> Fe ka > -10.29 (peso 0.7745)

======================================================================

Removida aresta Fe ka > -10.29 -> Ni > -9.77 (peso 0.1589)
Mantida aresta Ni > -9.77 -> Fe ka > -10.29 (peso 0.7033)

======================================================================

Removida aresta Ca ka > -38.25 -> K > -41.92 (peso 0.9360)
Mantida aresta K > -41.92 -> Ca ka > -38.25 (peso 0.9933)

======================================================================

Removida aresta Ca ka > -38.25 -> Ca ka > -41.92 (peso 0.7010)
Mantida aresta Ca ka > -41.92 -> Ca ka > -38.25 (peso 0.9619)

======================================================================

Removida aresta K > -41.92 -> Ca ka > -41.92 (peso 1.4548)
Mantida aresta Ca ka > -41.92 -> K > -41.92 (peso 2.2002)

======================================================================

Removida aresta K > -41.92 -> Zn ka > -28.72 (peso 0.9330)
Mantida aresta Zn ka > -28.72 -> K > -41.92 (peso 0.9990)

======================================================================

Removida aresta Zn ka > -28.72 -> Fe ka > -24.00 (peso 0.7648)
Mantida aresta Fe ka > -24.00 -> Zn ka > -28.72 (peso 1.7171)

======================================================================

Removida aresta Cu > -16.69 -> Cl > -45.57 (peso 2.8037)
Mantida aresta Cl > -45.57 -> Cu > -16.69 (peso 4.4483)

======================================================================

Removida aresta Cu > -17.55 -> Cl > -45.57 (peso 2.3412)
Mantida aresta Cl > -45.57 -> Cu > -17.55 (peso 2.4983)

======================================================================

Removida aresta Mo rayleigh scattering > 59.43 -> Si > -5.56 (peso 0.5011)
Mantida aresta Si > -5.56 -> Mo rayleigh scattering > 59.43 (peso 0.5026)

======================================================================

Removida aresta Si <= -23.93 -> Si > -52.01 (peso 0.0979)
Mantida aresta Si > -52.01 -> Si <= -23.93 (peso 0.1901)

======================================================================

Removida aresta Pb La > -6.83 -> Mo rayleigh scattering <= -10.70 (peso 0.3054)
Mantida aresta Mo rayleigh scattering <= -10.70 -> Pb La > -6.83 (peso 0.3179)

======================================================================

Removida aresta Mo rayleigh scattering <= -10.70 -> Pb Lb > -0.39 (peso 0.4036)
Mantida aresta Pb Lb > -0.39 -> Mo rayleigh scattering <= -10.70 (peso 0.4093)

======================================================================

Removida aresta Si > -5.56 -> Zn ka > -19.93 (peso 0.3299)
Mantida aresta Zn ka > -19.93 -> Si > -5.56 (peso 0.7438)

======================================================================

Removida aresta Zn ka > -19.93 -> Ni > -8.36 (peso 0.3027)
Mantida aresta Ni > -8.36 -> Zn ka > -19.93 (peso 2.3191)

======================================================================

Removida aresta Zn ka > -19.93 -> Zn ka > -24.20 (peso 1.0363)
Mantida aresta Zn ka > -24.20 -> Zn ka > -19.93 (peso 2.2235)

======================================================================

Removida aresta Ni > -8.36 -> Zn ka > -24.20 (peso 1.1472)
Mantida aresta Zn ka > -24.20 -> Ni > -8.36 (peso 3.3874)

======================================================================

Removida aresta Fe kb > -6.60 -> Fe kb > -8.76 (peso 0.2483)
Mantida aresta Fe kb > -8.76 -> Fe kb > -6.60 (peso 0.2636)

======================================================================

Removida aresta Fe kb > -6.60 -> Zn kb > -10.75 (peso 0.2739)
Mantida aresta Zn kb > -10.75 -> Fe kb > -6.60 (peso 0.5538)

======================================================================

Removida aresta Mo compton scattering <= -2.19 -> Mo rayleigh scattering <= -49.79 (peso 0.1949)
Mantida aresta Mo rayleigh scattering <= -49.79 -> Mo compton scattering <= -2.19 (peso 0.2178)

======================================================================

Removida aresta Pb Lb > -5.92 -> Mo rayleigh scattering <= -49.79 (peso 0.2094)
Mantida aresta Mo rayleigh scattering <= -49.79 -> Pb Lb > -5.92 (peso 0.2178)

======================================================================

Removida aresta background6 > 10.84 -> Ga <= 19.13 (peso 0.1261)
Mantida aresta Ga <= 19.13 -> background6 > 10.84 (peso 0.3110)

======================================================================

Removida aresta Pb Lb > -6.37 -> Ga <= 19.13 (peso 0.1389)
Mantida aresta Ga <= 19.13 -> Pb Lb > -6.37 (peso 0.1656)

======================================================================

Removida aresta Ga <= 19.13 -> Mo compton scattering <= -59.88 (peso 0.1403)
Mantida aresta Mo compton scattering <= -59.88 -> Ga <= 19.13 (peso 0.3047)

======================================================================

Removida aresta Pb La > -3.92 -> Ni > -9.77 (peso 0.7016)
Mantida aresta Ni > -9.77 -> Pb La > -3.92 (peso 0.8362)

======================================================================

Removida aresta Ti > 4.28 -> background6 > -9.14 (peso 0.0562)
Mantida aresta background6 > -9.14 -> Ti > 4.28 (peso 0.0756)

======================================================================

Removida aresta background4 > -4.33 -> background6 > -9.14 (peso 0.0498)
Mantida aresta background6 > -9.14 -> background4 > -4.33 (peso 0.0517)

======================================================================

Removida aresta background6 > -9.14 -> Mo compton scattering <= -59.88 (peso 0.0486)
Mantida aresta Mo compton scattering <= -59.88 -> background6 > -9.14 (peso 0.2114)

======================================================================

Removida aresta Mo rayleigh scattering <= 59.43 -> Pb La > -6.83 (peso 0.3582)
Mantida aresta Pb La > -6.83 -> Mo rayleigh scattering <= 59.43 (peso 0.5804)

======================================================================

Removida aresta background1 > -11.63 -> Ca kb > -4.43 (peso 0.0925)
Mantida aresta Ca kb > -4.43 -> background1 > -11.63 (peso 0.1645)

======================================================================

Removida aresta Si <= 44.53 -> background6 > 10.84 (peso 0.0720)
Mantida aresta background6 > 10.84 -> Si <= 44.53 (peso 0.1671)

======================================================================

Removida aresta Pb Lb > -6.37 -> background6 > 10.84 (peso 0.1540)
Mantida aresta background6 > 10.84 -> Pb Lb > -6.37 (peso 0.1673)

======================================================================

Removida aresta background7 > -16.37 -> background1 > -8.67 (peso 0.1112)
Mantida aresta background1 > -8.67 -> background7 > -16.37 (peso 0.1574)

======================================================================

Removida aresta Mo compton scattering > 86.16 -> Ni > -10.42 (peso 0.7059)
Mantida aresta Ni > -10.42 -> Mo compton scattering > 86.16 (peso 0.7083)

======================================================================

Removida aresta background7 > -11.83 -> background7 > -16.37 (peso 0.1197)
Mantida aresta background7 > -16.37 -> background7 > -11.83 (peso 0.1258)

======================================================================

Removida aresta background4 > 5.15 -> Ca kb > -4.43 (peso 0.0671)
Mantida aresta Ca kb > -4.43 -> background4 > 5.15 (peso 0.1793)

======================================================================

Removida aresta Cu > -19.02 -> Mo rayleigh scattering > -10.70 (peso 0.1360)
Mantida aresta Mo rayleigh scattering > -10.70 -> Cu > -19.02 (peso 1.5556)

======================================================================

Removida aresta Si <= -5.56 -> Mo compton scattering <= -59.88 (peso 0.1103)
Mantida aresta Mo compton scattering <= -59.88 -> Si <= -5.56 (peso 0.1278)

======================================================================

Removida aresta Mo compton scattering <= -59.88 -> Si <= -23.93 (peso 0.1086)
Mantida aresta Si <= -23.93 -> Mo compton scattering <= -59.88 (peso 0.1698)

======================================================================

Removida aresta background2 > -0.23 -> Si <= -23.93 (peso 0.1037)
Mantida aresta Si <= -23.93 -> background2 > -0.23 (peso 0.1240)

======================================================================

Removida aresta background2 > -5.49 -> Ca kb > -6.73 (peso 0.0395)
Mantida aresta Ca kb > -6.73 -> background2 > -5.49 (peso 0.1139)

======================================================================

Removida aresta Zn kb > -8.99 -> Zn kb > -7.43 (peso 0.3896)
Mantida aresta Zn kb > -7.43 -> Zn kb > -8.99 (peso 1.2361)

======================================================================

Removida aresta background4 <= 8.23 -> background4 > 5.15 (peso 0.0758)
Mantida aresta background4 > 5.15 -> background4 <= 8.23 (peso 0.1988)

======================================================================

Removida aresta background4 <= 8.23 -> Si <= 44.53 (peso 0.0622)
Mantida aresta Si <= 44.53 -> background4 <= 8.23 (peso 0.0773)

======================================================================

Removida aresta Zn kb > -8.99 -> Ga > -8.73 (peso 0.3778)
Mantida aresta Ga > -8.73 -> Zn kb > -8.99 (peso 0.3892)

======================================================================

Removida aresta Si <= 44.53 -> Ga <= 7.09 (peso 0.0242)
Mantida aresta Ga <= 7.09 -> Si <= 44.53 (peso 0.0377)

======================================================================

Removida aresta background5 > -4.50 -> background6 <= 20.08 (peso 0.0238)
Mantida aresta background6 <= 20.08 -> background5 > -4.50 (peso 0.0371)

======================================================================

Removida aresta Ti > -6.18 -> Ti > -4.74 (peso 0.0310)
Mantida aresta Ti > -4.74 -> Ti > -6.18 (peso 0.1115)

======================================================================

Removida aresta background5 > -5.65 -> Ga <= -8.73 (peso 0.0332)
Mantida aresta Ga <= -8.73 -> background5 > -5.65 (peso 0.0350)

======================================================================

Removida aresta Mo compton scattering <= 86.16 -> background2 > -0.23 (peso 0.0526)
Mantida aresta background2 > -0.23 -> Mo compton scattering <= 86.16 (peso 0.1335)

======================================================================

Removida aresta Ga > -13.34 -> Mo compton scattering <= 86.16 (peso 0.2723)
Mantida aresta Mo compton scattering <= 86.16 -> Ga > -13.34 (peso 0.3112)

======================================================================

Removida aresta Ca ka <= 48.39 -> Pb Lb > -6.37 (peso 0.1557)
Mantida aresta Pb Lb > -6.37 -> Ca ka <= 48.39 (peso 0.1619)

======================================================================

Removida aresta Pb La <= 5.22 -> background6 <= -9.14 (peso 0.0350)
Mantida aresta background6 <= -9.14 -> Pb La <= 5.22 (peso 0.0404)

======================================================================

Removida aresta background2 > 5.59 -> background6 <= -9.14 (peso 0.0337)
Mantida aresta background6 <= -9.14 -> background2 > 5.59 (peso 0.0348)

======================================================================

Removida aresta Fe ka <= 10.08 -> background6 <= -9.14 (peso 0.0353)
Mantida aresta background6 <= -9.14 -> Fe ka <= 10.08 (peso 0.0441)

======================================================================

Removida aresta Pb Lb > 6.53 -> Pb La > -3.92 (peso 0.5834)
Mantida aresta Pb La > -3.92 -> Pb Lb > 6.53 (peso 0.6225)

======================================================================

Removida aresta Ti > -4.74 -> background1 <= -11.63 (peso 0.0358)
Mantida aresta background1 <= -11.63 -> Ti > -4.74 (peso 0.0477)

======================================================================

Removida aresta background2 > 5.59 -> background5 > -5.65 (peso 0.0337)
Mantida aresta background5 > -5.65 -> background2 > 5.59 (peso 0.0340)

======================================================================

Removida aresta Fe kb <= 8.67 -> background5 <= 7.96 (peso 0.0246)
Mantida aresta background5 <= 7.96 -> Fe kb <= 8.67 (peso 0.0913)

======================================================================

Removida aresta Ca ka <= 48.39 -> K <= 48.39 (peso 0.0316)
Mantida aresta K <= 48.39 -> Ca ka <= 48.39 (peso 0.2928)

======================================================================

Removida aresta Ca ka <= -20.13 -> K <= -20.13 (peso 0.1505)
Mantida aresta K <= -20.13 -> Ca ka <= -20.13 (peso 0.2118)

======================================================================

Removida aresta K <= -20.13 -> Ti > 4.28 (peso 0.0274)
Mantida aresta Ti > 4.28 -> K <= -20.13 (peso 0.0371)

======================================================================

Removida aresta background2 <= -4.00 -> background3 <= 4.89 (peso 0.0238)
Mantida aresta background3 <= 4.89 -> background2 <= -4.00 (peso 0.0350)

======================================================================

Removida aresta background2 <= 5.59 -> background4 > -4.33 (peso 0.0396)
Mantida aresta background4 > -4.33 -> background2 <= 5.59 (peso 0.0424)


,Predicate_Cov_Seed_0,Predicate_Cov_Seed_1,Predicate_Cov_Seed_2,Predicate_Cov_Seed_3
0,Cu > -14.20,Cu > -14.20,Cu > -14.20,Cu > -16.69
1,Cu > -16.69,Cu > -16.69,Cu > -16.69,Cu > -14.20
2,background7 > 17.05,Ni > -4.20,Zn ka <= -19.93,Cl > -45.57
3,Cl > -45.57,Cu > -17.55,background2 > 5.59,background7 > -11.83
4,Cu > -17.55,Ni > -8.36,Cu > -17.55,Cu > -17.55
...,...,...,...,...
167,background3 > 4.89,Ca kb <= -0.56,Class_A,Ca kb <= -0.56
168,Ca ka <= -41.92,background5 <= -4.50,Class_B,Pb Lb <= -5.92
169,K <= -41.92,background4 <= -4.33,NaN,Pb La <= -5.66
170,Class_A,Class_A,NaN,Class_A
171,Class_B,Class_B,NaN,Class_B

In [24]:
# Somar LRCs de predicados equivalentes entre diferentes seeds
lrc_combined_list = []

for seed in random_seeds:
    lrc_df = lrc_cov_by_seed[seed].copy()
    lrc_combined_list.append(lrc_df) # o append adiciona o dataframe ao final da lista

# Concatenar todos os dataframes
lrc_all_seeds = pd.concat(lrc_combined_list, ignore_index=True) 

# Agrupar por predicado (Node) e somar as LRCs, mantendo Zone, Threshold e Operator
lrc_summed_df = lrc_all_seeds.groupby('Node').agg({ # o .agg pode ser usado para aplicar múltiplas funções de agregação
    'Local_Reaching_Centrality': 'mean', # sum = somando as LRCs, poderia ser média ou outro agregado
    'Zone': 'first',
    'Threshold': 'first',
    'Operator': 'first'
}).reset_index()

# Ordenar pelo valor de LRC somado (maior para menor)
lrc_summed_df = lrc_summed_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
# vamoss pegar so os valore sunicos de lrc_summed_df baseado na zona espectral
lrc_summed_unique_df_cov = lrc_summed_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
lrc_summed_unique_df_cov = lrc_summed_unique_df_cov.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
lrc_summed_unique_df_cov

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator
0,Cu > -14.20,22.037461,Cu,-14.20,>
1,Cl > -45.57,6.818997,Cl,-45.57,>
2,background7 > 17.05,5.838552,background7,17.05,>
3,Ni > -4.20,5.147954,Ni,-4.20,>
4,Mo rayleigh scattering > -49.79,4.356249,Mo rayleigh scattering,-49.79,>
5,Zn ka > -24.20,3.750557,Zn ka,-24.20,>
6,Mo compton scattering > -2.19,3.457900,Mo compton scattering,-2.19,>
7,background3 > -6.23,3.344926,background3,-6.23,>
8,Ca ka > -41.92,3.284965,Ca ka,-41.92,>
9,Si > 44.53,3.236779,Si,44.53,>
10,Ca kb > -6.73,3.075031,Ca kb,-6.73,>
11,background2 > 5.59,2.893535,background2,5.59,>
12,K > -38.25,2.835300,K,-38.25,>
13,Pb Lb > 6.53,2.715727,Pb Lb,6.53,>
14,Fe ka > -16.96,2.710953,Fe ka,-16.96,>
15,Fe kb > -6.60,2.596668,Fe kb,-6.60,>
16,Pb La > 5.22,2.557105,Pb La,5.22,>
17,background4 <= 5.15,2.287526,background4,5.15,<=
18,Ga > 7.09,2.183377,Ga,7.09,>
19,Ti > 8.03,2.151271,Ti,8.03,>
20,Zn kb > 8.42,2.133014,Zn kb,8.42,>
21,background6 > -11.74,1.913714,background6,-11.74,>
22,background1 > 33.08,1.777500,background1,33.08,>
23,background5 > -4.50,1.346652,background5,-4.50,>
24,Class_A,0.000000,None,None,None

# **Perturbation**

In [25]:
import explaining as exp

# LISTA DE SEMENTES A TESTAR
random_seeds = [0, 1, 2, 3]

all_results_pert = {}
training_samples = len(Xcalclass)

# LOOP: PROCESSAR CADA SEMENTE
y_predicted_numeric = pd.Series(y_pred) # predições numéricas do modelo

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando semente: {seed}")
    print(f"{'='*70}\n")
    # Bagging
    bags_result_seed = exp.bagging_predicates(
        zone_sums_df=zone_sums_df,
        y_predicted_numeric=y_predicted_numeric,
        predicates_df=predicates_quantiles[0],
        n_bags=10,
        #n_predicates_per_bag=40,
        n_samples_per_bag=int(training_samples*0.8), # 80 % da base para amostrar (convertido para int)
        min_samples_per_predicate=int(training_samples*0.2), # 20 % da base para limitar (convertido para int)
        replace=False,
        sample_bagging=True,
        predicate_bagging=False,
        random_seed=seed
    )
    # Inserir classe prevista
    for bag_name, pred_dict in bags_result_seed.items(): # iterando sobre cada bag
        for pred_rule, df_info in pred_dict.items():
            df_info['Class_Predicted'] = np.where(df_info['Predicted_Y'] >= 0.5, 'A', 'B') # binarizando com threshold 0.5, A = eut, B = dist

    pert_results_seed = exp.calculate_predicate_perturbation(
        estimator=svm_model[3],
        Xcalclass_prep=Xcalclass_prep,
        folds_struct=bags_result_seed,
        predicates_df=predicates_quantiles[0],
        spectral_cuts=spectral_cuts,
        #perturbation_value=0,
        perturbation_mode='mean', # valores entre 'mean' ou 'min'
        stats_source='full', # full indica usar todas as amostras para calcular estatísticas enquanto que 'fold' usa apenas as amostras do fold atual
        #metric='mean_abs_diff',   # Média com sinal (pode ser negativo)
        aim='classification',
        metric='probability_shift', 
        verbose=True
    )

    # Remove todos os valores iguais a zero de todos os bags em perm_results[bag]["Permutation"] e salva como perm_results_thresholded
    # pert_results_seed_thresholded = {}
    # for bag, df in perm_results_seed.items():
    #     # Verifica se é um DataFrame e se a coluna 'Permutation' existe
    #     if isinstance(df, pd.DataFrame) and 'Permutation' in df.columns:
    #         filtered_df = df[df['Permutation'] > 0].copy()
    #         pert_results_seed_thresholded[bag] = filtered_df
    #     else:
    #         # Se não for DataFrame esperado, apenas copia
    #         pert_results_seed_thresholded[bag] = df

    # Salvar no dicionário principal
    all_results_pert[seed] = {
        'bags_result': bags_result_seed,
        'pert_results_dict': pert_results_seed
    }

# CONSTRUÇÃO DE GRAFOS PARA MÚLTIPLAS SEMENTES (LOOP EXTERNO)
# Dicionário para armazenar grafos
graphs_pert_by_seed = {}

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando Grafo - Semente: {seed}")
    print(f"{'='*70}\n")
    # Construir grafo para esta semente
    DG = exp.build_predicate_graphv2(
        bags_result=all_results_pert[seed]['bags_result'],
        predicate_ranking_dict=all_results_pert[seed]['pert_results_dict'],
        metric_column='Perturbation',  # ou 'Covariance' se mudar a métrica
        random_state=seed,
        show_details=True
    )
    # Armazenar grafo
    graphs_pert_by_seed[seed] = DG  

# Calcular LRC usando a função pronta do explaining.py
lrc_pert_by_seed = {}
for seed in random_seeds:
    DG = graphs_pert_by_seed[seed]
    lrc_pert_df_seed = exp.calculate_lrc_single_graph(DG, predicates_quantiles[0])
    lrc_pert_df_seed['Seed'] = seed  # Adicionar coluna com a semente
    lrc_pert_by_seed[seed] = lrc_pert_df_seed

# junando todas as colunas 'Node' de lrc_by_seed em um único dataframe
lrc_pert_all_seeds_df = pd.DataFrame()
for seed in random_seeds:
    lrc_pert_df_seed = lrc_pert_by_seed[seed].rename(columns={'Node': f'Predicate_pert_Seed_{seed}'})
    lrc_pert_all_seeds_df = pd.concat([lrc_pert_all_seeds_df, lrc_pert_df_seed[[f'Predicate_pert_Seed_{seed}']]], axis=1)

# vamos filtrar lrc_by_seed em cada semente para manter apenas as zonas espectrais únicas com maior LRC em um mesmo dataframe
lrc_pert_unique_by_seed = {}
for seed, lrc_df in lrc_pert_by_seed.items():
    lrc_pert_unique_df = lrc_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
    lrc_pert_unique_df = lrc_pert_unique_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
    lrc_pert_unique_by_seed[seed] = lrc_pert_unique_df

lrc_pert_all_seeds_df # exibindo o dataframe consolidado com predicados de todas as sementes

======================================================================
Processando semente: 0
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 156 | Descartados: 36
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 166 | Descartados: 26
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 158 | Descartados: 34
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 154 | Descartados: 38
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 177 | Descartados: 15
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 144 | Descartados: 48
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 165 | Descartados: 27
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 152 | Descartados: 40
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 153 | Descartados: 39
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 164 | Descartados: 28
======================================================================
PERTURBATION IMPORTANCE PARA PREDICADOS
======================================================================
Tipo de tarefa (aim): classification
Modo de perturbação: mean
Fonte das estatísticas: full
Métrica: probability_shift
Total de folds: 10


[Bag_1] Processando 156 predicados...
  Predicado: Si <= -52.01 (n=5)
    Zona: 185 colunas
    Importance: 0.006490
  Predicado: Si > -52.01 (n=15)
    Zona: 185 colunas
    Importance: 0.004432
  Predicado: Si <= -23.93 (n=9)
    Zona: 185 colunas
    Importance: 0.005739
  Predicado: Si > -23.93 (n=11)
    Zona: 185 colunas
    Importance: 0.004299
  Predicado: Si <= -5.56 (n=12)
    Zona: 185 colunas
    Importance: 0.004866
  Predicado: Si > -5.56 (n=8)
    Zona: 185 colunas
    Importance: 0.005067
  Predicado: Si <= 44.53 (n=16)
    Zona: 185 colunas
    Importance: 0.004283
  Predicado: background1 <= -16.23 (n=5)
    Zona: 99 colunas
    Importance: 0.008095
  Predicado: background1 > -16.23 (n=15)
    Zona: 99 colunas
    Importance: 0.007705
  Predicado: background1 <= -11.63 (n=10)
    Zona: 99 colunas
    Importance: 0.007596
  Predicado: background1 > -11.63 (n=10)
    Zona: 99 colunas
    Importance: 0.008010
  Predicado: background1 <= -8.67 (n=13)
    Zona: 99 colunas
    Importance: 0.006664
  Predicado: background1 > -8.67 (n=7)
    Zona: 99 colunas
    Importance: 0.009917
  Predicado: background1 <= 33.08 (n=17)
    Zona: 99 colunas
    Importance: 0.006673
  Predicado: Cl > -175.25 (n=17)
    Zona: 115 colunas
    Importance: 0.008370
  Predicado: Cl <= -159.85 (n=7)
    Zona: 115 colunas
    Importance: 0.006653
  Predicado: Cl > -159.85 (n=13)
    Zona: 115 colunas
    Importance: 0.008909
  Predicado: Cl <= -45.57 (n=12)
    Zona: 115 colunas
    Importance: 0.005910
  Predicado: Cl > -45.57 (n=8)
    Zona: 115 colunas
    Importance: 0.011433
  Predicado: Cl <= 94.61 (n=16)
    Zona: 115 colunas
    Importance: 0.004806
  Predicado: background2 <= -5.49 (n=5)
    Zona: 31 colunas
    Importance: 0.000855
  Predicado: background2 > -5.49 (n=15)
    Zona: 31 colunas
    Importance: 0.000630
  Predicado: background2 <= -4.00 (n=9)
    Zona: 31 colunas
    Importance: 0.000652
  Predicado: background2 > -4.00 (n=11)
    Zona: 31 colunas
    Importance: 0.000715
  Predicado: background2 <= -0.23 (n=12)
    Zona: 31 colunas
    Importance: 0.000563
  Predicado: background2 > -0.23 (n=8)
    Zona: 31 colunas
    Importance: 0.000872
  Predicado: background2 <= 5.59 (n=15)
    Zona: 31 colunas
    Importance: 0.000486
  Predicado: background2 > 5.59 (n=5)
    Zona: 31 colunas
    Importance: 0.001289
  Predicado: K <= -41.92 (n=5)
    Zona: 70 colunas
    Importance: 0.015669
  Predicado: K > -41.92 (n=15)
    Zona: 70 colunas
    Importance: 0.016464
  Predicado: K <= -38.25 (n=9)
    Zona: 70 colunas
    Importance: 0.014696
  Predicado: K > -38.25 (n=11)
    Zona: 70 colunas
    Importance: 0.017550
  Predicado: K <= -20.13 (n=13)
    Zona: 70 colunas
    Importance: 0.013278
  Predicado: K > -20.13 (n=7)
    Zona: 70 colunas
    Importance: 0.021813
  Predicado: K <= 48.39 (n=17)
    Zona: 70 colunas
    Importance: 0.012496
  Predicado: Ca ka <= -41.92 (n=5)
    Zona: 142 colunas
    Importance: 0.013667
  Predicado: Ca ka > -41.92 (n=15)
    Zona: 142 colunas
    Importance: 0.014587
  Predicado: Ca ka <= -38.25 (n=9)
    Zona: 142 colunas
    Importance: 0.012615
  Predicado: Ca ka > -38.25 (n=11)
    Zona: 142 colunas
    Importance: 0.015782
  Predicado: Ca ka <= -20.13 (n=13)
    Zona: 142 colunas
    Importance: 0.011473
  Predicado: Ca ka > -20.13 (n=7)
    Zona: 142 colunas
    Importance: 0.019712
  Predicado: Ca ka <= 48.39 (n=17)
    Zona: 142 colunas
    Importance: 0.010809
  Predicado: Ca kb <= -6.73 (n=5)
    Zona: 54 colunas
    Importance: 0.000920
  Predicado: Ca kb > -6.73 (n=15)
    Zona: 54 colunas
    Importance: 0.000654
  Predicado: Ca kb <= -4.43 (n=9)
    Zona: 54 colunas
    Importance: 0.000804
  Predicado: Ca kb > -4.43 (n=11)
    Zona: 54 colunas
    Importance: 0.000653
  Predicado: Ca kb <= -0.56 (n=14)
    Zona: 54 colunas
    Importance: 0.000577
  Predicado: Ca kb > -0.56 (n=6)
    Zona: 54 colunas
    Importance: 0.001055
  Predicado: Ca kb <= 10.41 (n=17)
    Zona: 54 colunas
    Importance: 0.000599
  Predicado: Ti > -6.18 (n=16)
    Zona: 144 colunas
    Importance: 0.001839
  Predicado: Ti <= -4.74 (n=8)
    Zona: 144 colunas
    Importance: 0.001951
  Predicado: Ti > -4.74 (n=12)
    Zona: 144 colunas
    Importance: 0.002067
  Predicado: Ti <= 4.28 (n=11)
    Zona: 144 colunas
    Importance: 0.001610
  Predicado: Ti > 4.28 (n=9)
    Zona: 144 colunas
    Importance: 0.002523
  Predicado: Ti <= 8.03 (n=15)
    Zona: 144 colunas
    Importance: 0.001343
  Predicado: Ti > 8.03 (n=5)
    Zona: 144 colunas
    Importance: 0.004054
  Predicado: background3 <= -6.23 (n=5)
    Zona: 268 colunas
    Importance: 0.000742
  Predicado: background3 > -6.23 (n=15)
    Zona: 268 colunas
    Importance: 0.000526
  Predicado: background3 <= -5.14 (n=9)
    Zona: 268 colunas
    Importance: 0.000533
  Predicado: background3 > -5.14 (n=11)
    Zona: 268 colunas
    Importance: 0.000619
  Predicado: background3 <= 4.89 (n=13)
    Zona: 268 colunas
    Importance: 0.000449
  Predicado: background3 > 4.89 (n=7)
    Zona: 268 colunas
    Importance: 0.000823
  Predicado: background3 <= 10.15 (n=16)
    Zona: 268 colunas
    Importance: 0.000484
  Predicado: Fe ka > -24.00 (n=16)
    Zona: 115 colunas
    Importance: 0.008976
  Predicado: Fe ka <= -16.96 (n=8)
    Zona: 115 colunas
    Importance: 0.007729
  Predicado: Fe ka > -16.96 (n=12)
    Zona: 115 colunas
    Importance: 0.009652
  Predicado: Fe ka <= -10.29 (n=12)
    Zona: 115 colunas
    Importance: 0.006834
  Predicado: Fe ka > -10.29 (n=8)
    Zona: 115 colunas
    Importance: 0.011956
  Predicado: Fe ka <= 10.08 (n=16)
    Zona: 115 colunas
    Importance: 0.005392
  Predicado: Fe kb > -8.76 (n=16)
    Zona: 103 colunas
    Importance: 0.001391
  Predicado: Fe kb <= -6.60 (n=9)
    Zona: 103 colunas
    Importance: 0.001155
  Predicado: Fe kb > -6.60 (n=11)
    Zona: 103 colunas
    Importance: 0.001591
  Predicado: Fe kb <= -4.78 (n=12)
    Zona: 103 colunas
    Importance: 0.001030
  Predicado: Fe kb > -4.78 (n=8)
    Zona: 103 colunas
    Importance: 0.001943
  Predicado: Fe kb <= 8.67 (n=17)
    Zona: 103 colunas
    Importance: 0.000846
  Predicado: Ni > -10.42 (n=16)
    Zona: 95 colunas
    Importance: 0.002613
  Predicado: Ni <= -9.77 (n=8)
    Zona: 95 colunas
    Importance: 0.002584
  Predicado: Ni > -9.77 (n=12)
    Zona: 95 colunas
    Importance: 0.002684
  Predicado: Ni <= -8.36 (n=12)
    Zona: 95 colunas
    Importance: 0.002351
  Predicado: Ni > -8.36 (n=8)
    Zona: 95 colunas
    Importance: 0.003083
  Predicado: Ni <= -4.20 (n=16)
    Zona: 95 colunas
    Importance: 0.002103
  Predicado: Cu > -19.02 (n=16)
    Zona: 128 colunas
    Importance: 0.002104
  Predicado: Cu <= -17.55 (n=9)
    Zona: 128 colunas
    Importance: 0.001821
  Predicado: Cu > -17.55 (n=11)
    Zona: 128 colunas
    Importance: 0.002229
  Predicado: Cu <= -16.69 (n=13)
    Zona: 128 colunas
    Importance: 0.001828
  Predicado: Cu > -16.69 (n=7)
    Zona: 128 colunas
    Importance: 0.002449
  Predicado: Cu <= -14.20 (n=16)
    Zona: 128 colunas
    Importance: 0.001785
  Predicado: Zn ka > -28.72 (n=16)
    Zona: 124 colunas
    Importance: 0.003798
  Predicado: Zn ka <= -24.20 (n=7)
    Zona: 124 colunas
    Importance: 0.003817
  Predicado: Zn ka > -24.20 (n=13)
    Zona: 124 colunas
    Importance: 0.003875
  Predicado: Zn ka <= -19.93 (n=12)
    Zona: 124 colunas
    Importance: 0.003452
  Predicado: Zn ka > -19.93 (n=8)
    Zona: 124 colunas
    Importance: 0.004457
  Predicado: Zn ka <= 17.61 (n=17)
    Zona: 124 colunas
    Importance: 0.003032
  Predicado: Ga > -13.34 (n=17)
    Zona: 91 colunas
    Importance: 0.007967
  Predicado: Ga <= -8.73 (n=8)
    Zona: 91 colunas
    Importance: 0.008939
  Predicado: Ga > -8.73 (n=12)
    Zona: 91 colunas
    Importance: 0.008735
  Predicado: Ga <= 7.09 (n=11)
    Zona: 91 colunas
    Importance: 0.006962
  Predicado: Ga > 7.09 (n=9)
    Zona: 91 colunas
    Importance: 0.011083
  Predicado: Ga <= 19.13 (n=16)
    Zona: 91 colunas
    Importance: 0.006978
  Predicado: Zn kb > -10.75 (n=16)
    Zona: 66 colunas
    Importance: 0.000253
  Predicado: Zn kb <= -8.99 (n=7)
    Zona: 66 colunas
    Importance: 0.000294
  Predicado: Zn kb > -8.99 (n=13)
    Zona: 66 colunas
    Importance: 0.000252
  Predicado: Zn kb <= -7.43 (n=12)
    Zona: 66 colunas
    Importance: 0.000229
  Predicado: Zn kb > -7.43 (n=8)
    Zona: 66 colunas
    Importance: 0.000324
  Predicado: Zn kb <= 8.42 (n=17)
    Zona: 66 colunas
    Importance: 0.000204
  Predicado: background4 > -6.76 (n=17)
    Zona: 129 colunas
    Importance: 0.001158
  Predicado: background4 <= -4.33 (n=7)
    Zona: 129 colunas
    Importance: 0.001421
  Predicado: background4 > -4.33 (n=13)
    Zona: 129 colunas
    Importance: 0.001153
  Predicado: background4 <= 5.15 (n=11)
    Zona: 129 colunas
    Importance: 0.001002
  Predicado: background4 > 5.15 (n=9)
    Zona: 129 colunas
    Importance: 0.001545
  Predicado: background4 <= 8.23 (n=16)
    Zona: 129 colunas
    Importance: 0.000911
  Predicado: Pb La > -6.83 (n=16)
    Zona: 70 colunas
    Importance: 0.000863
  Predicado: Pb La <= -5.66 (n=8)
    Zona: 70 colunas
    Importance: 0.001323
  Predicado: Pb La > -5.66 (n=12)
    Zona: 70 colunas
    Importance: 0.000780
  Predicado: Pb La <= -3.92 (n=12)
    Zona: 70 colunas
    Importance: 0.001068
  Predicado: Pb La > -3.92 (n=8)
    Zona: 70 colunas
    Importance: 0.000890
  Predicado: Pb La <= 5.22 (n=16)
    Zona: 70 colunas
    Importance: 0.000848
  Predicado: background5 <= -5.65 (n=5)
    Zona: 334 colunas
    Importance: 0.004349
  Predicado: background5 > -5.65 (n=15)
    Zona: 334 colunas
    Importance: 0.003385
  Predicado: background5 <= -4.50 (n=8)
    Zona: 334 colunas
    Importance: 0.003815
  Predicado: background5 > -4.50 (n=12)
    Zona: 334 colunas
    Importance: 0.003500
  Predicado: background5 <= -0.81 (n=11)
    Zona: 334 colunas
    Importance: 0.003134
  Predicado: background5 > -0.81 (n=9)
    Zona: 334 colunas
    Importance: 0.004227
  Predicado: background5 <= 7.96 (n=16)
    Zona: 334 colunas
    Importance: 0.002922
  Predicado: Pb Lb > -6.37 (n=16)
    Zona: 89 colunas
    Importance: 0.000371
  Predicado: Pb Lb <= -5.92 (n=8)
    Zona: 89 colunas
    Importance: 0.000531
  Predicado: Pb Lb > -5.92 (n=12)
    Zona: 89 colunas
    Importance: 0.000354
  Predicado: Pb Lb <= -0.39 (n=11)
    Zona: 89 colunas
    Importance: 0.000452
  Predicado: Pb Lb > -0.39 (n=9)
    Zona: 89 colunas
    Importance: 0.000392
  Predicado: Pb Lb <= 6.53 (n=16)
    Zona: 89 colunas
    Importance: 0.000356
  Predicado: background6 > -11.74 (n=16)
    Zona: 501 colunas
    Importance: 0.007179
  Predicado: background6 <= -9.14 (n=8)
    Zona: 501 colunas
    Importance: 0.007819
  Predicado: background6 > -9.14 (n=12)
    Zona: 501 colunas
    Importance: 0.007007
  Predicado: background6 <= 10.84 (n=12)
    Zona: 501 colunas
    Importance: 0.006085
  Predicado: background6 > 10.84 (n=8)
    Zona: 501 colunas
    Importance: 0.009201
  Predicado: background6 <= 20.08 (n=16)
    Zona: 501 colunas
    Importance: 0.005667
  Predicado: Mo compton scattering > -67.69 (n=16)
    Zona: 377 colunas
    Importance: 0.008428
  Predicado: Mo compton scattering <= -59.88 (n=8)
    Zona: 377 colunas
    Importance: 0.006955
  Predicado: Mo compton scattering > -59.88 (n=12)
    Zona: 377 colunas
    Importance: 0.009562
  Predicado: Mo compton scattering <= -2.19 (n=11)
    Zona: 377 colunas
    Importance: 0.006781
  Predicado: Mo compton scattering > -2.19 (n=9)
    Zona: 377 colunas
    Importance: 0.010644
  Predicado: Mo compton scattering <= 86.16 (n=16)
    Zona: 377 colunas
    Importance: 0.006759
  Predicado: Mo rayleigh scattering > -71.50 (n=16)
    Zona: 111 colunas
    Importance: 0.007388
  Predicado: Mo rayleigh scattering <= -49.79 (n=9)
    Zona: 111 colunas
    Importance: 0.005057
  Predicado: Mo rayleigh scattering > -49.79 (n=11)
    Zona: 111 colunas
    Importance: 0.007561
  Predicado: Mo rayleigh scattering <= -10.70 (n=12)
    Zona: 111 colunas
    Importance: 0.006249
  Predicado: Mo rayleigh scattering > -10.70 (n=8)
    Zona: 111 colunas
    Importance: 0.006712
  Predicado: Mo rayleigh scattering <= 59.43 (n=15)
    Zona: 111 colunas
    Importance: 0.005910
  Predicado: Mo rayleigh scattering > 59.43 (n=5)
    Zona: 111 colunas
    Importance: 0.008009
  Predicado: background7 > -16.37 (n=16)
    Zona: 449 colunas
    Importance: 0.011391
  Predicado: background7 <= -11.83 (n=8)
    Zona: 449 colunas
    Importance: 0.001116
  Predicado: background7 > -11.83 (n=12)
    Zona: 449 colunas
    Importance: 0.014959
  Predicado: background7 <= 7.87 (n=11)
    Zona: 449 colunas
    Importance: 0.002659
  Predicado: background7 > 7.87 (n=9)
    Zona: 449 colunas
    Importance: 0.017688
  Predicado: background7 <= 17.05 (n=15)
    Zona: 449 colunas
    Importance: 0.004695
  Predicado: background7 > 17.05 (n=5)
    Zona: 449 colunas
    Importance: 0.023601

[Bag_2] Processando 166 predicados...
  Predicado: Si <= -52.01 (n=5)
    Zona: 185 colunas
    Importance: 0.006490
  Predicado: Si > -52.01 (n=15)
    Zona: 185 colunas
    Importance: 0.006282
  Predicado: Si <= -23.93 (n=10)
    Zona: 185 colunas
    Importance: 0.005628
  Predicado: Si > -23.93 (n=10)
    Zona: 185 colunas
    Importance: 0.007040
  Predicado: Si <= -5.56 (n=13)
    Zona: 185 colunas
    Importance: 0.005041
  Predicado: Si > -5.56 (n=7)
    Zona: 185 colunas
    Importance: 0.008736
  Predicado: Si <= 44.53 (n=16)
    Zona: 185 colunas
    Importance: 0.004497
  Predicado: background1 <= -16.23 (n=5)
    Zona: 99 colunas
    Importance: 0.008095
  Predicado: background1 > -16.23 (n=15)
    Zona: 99 colunas
    Importance: 0.011478
  Predicado: background1 <= -11.63 (n=9)
    Zona: 99 colunas
    Importance: 0.007668
  Predicado: background1 > -11.63 (n=11)
    Zona: 99 colunas
    Importance: 0.013057
  Predicado: background1 <= -8.67 (n=13)
    Zona: 99 colunas
    Importance: 0.006205
  Predicado: background1 > -8.67 (n=7)
    Zona: 99 colunas
    Importance: 0.018854
  Predicado: background1 <= 33.08 (n=16)
    Zona: 99 colunas
    Importance: 0.006325
  Predicado: Cl <= -175.25 (n=5)
    Zona: 115 colunas
    Importance: 0.006630
  Predicado: Cl > -175.25 (n=15)
    Zona: 115 colunas
    Importance: 0.007235
  Predicado: Cl <= -159.85 (n=10)
    Zona: 115 colunas
    Importance: 0.006658
  Predicado: Cl > -159.85 (n=10)
    Zona: 115 colunas
    Importance: 0.007510
  Predicado: Cl <= -45.57 (n=13)
    Zona: 115 colunas
    Importance: 0.006353
  Predicado: Cl > -45.57 (n=7)
    Zona: 115 colunas
    Importance: 0.008440
  Predicado: Cl <= 94.61 (n=16)
    Zona: 115 colunas
    Importance: 0.005325
  Predicado: background2 <= -5.49 (n=5)
    Zona: 31 colunas
    Importance: 0.000855
  Predicado: background2 > -5.49 (n=15)
    Zona: 31 colunas
    Importance: 0.000506
  Predicado: background2 <= -4.00 (n=9)
    Zona: 31 colunas
    Importance: 0.000608
  Predicado: background2 > -4.00 (n=11)
    Zona: 31 colunas
    Importance: 0.000581
  Predicado: background2 <= -0.23 (n=13)
    Zona: 31 colunas
    Importance: 0.000508
  Predicado: background2 > -0.23 (n=7)
    Zona: 31 colunas
    Importance: 0.000752
  Predicado: background2 <= 5.59 (n=16)
    Zona: 31 colunas
    Importance: 0.000439
  Predicado: K > -41.92 (n=16)
    Zona: 70 colunas
    Importance: 0.017633
  Predicado: K <= -38.25 (n=9)
    Zona: 70 colunas
    Importance: 0.014420
  Predicado: K > -38.25 (n=11)
    Zona: 70 colunas
    Importance: 0.019658
  Predicado: K <= -20.13 (n=12)
    Zona: 70 colunas
    Importance: 0.013330
  Predicado: K > -20.13 (n=8)
    Zona: 70 colunas
    Importance: 0.023258
  Predicado: K <= 48.39 (n=15)
    Zona: 70 colunas
    Importance: 0.011954
  Predicado: K > 48.39 (n=5)
    Zona: 70 colunas
    Importance: 0.033343
  Predicado: Ca ka > -41.92 (n=16)
    Zona: 142 colunas
    Importance: 0.015247
  Predicado: Ca ka <= -38.25 (n=9)
    Zona: 142 colunas
    Importance: 0.012440
  Predicado: Ca ka > -38.25 (n=11)
    Zona: 142 colunas
    Importance: 0.017109
  Predicado: Ca ka <= -20.13 (n=12)
    Zona: 142 colunas
    Importance: 0.011653
  Predicado: Ca ka > -20.13 (n=8)
    Zona: 142 colunas
    Importance: 0.020040
  Predicado: Ca ka <= 48.39 (n=15)
    Zona: 142 colunas
    Importance: 0.010430
  Predicado: Ca ka > 48.39 (n=5)
    Zona: 142 colunas
    Importance: 0.028740
  Predicado: Ca kb <= -6.73 (n=5)
    Zona: 54 colunas
    Importance: 0.000920
  Predicado: Ca kb > -6.73 (n=15)
    Zona: 54 colunas
    Importance: 0.000639
  Predicado: Ca kb <= -4.43 (n=8)
    Zona: 54 colunas
    Importance: 0.000810
  Predicado: Ca kb > -4.43 (n=12)
    Zona: 54 colunas
    Importance: 0.000642
  Predicado: Ca kb <= -0.56 (n=12)
    Zona: 54 colunas
    Importance: 0.000600
  Predicado: Ca kb > -0.56 (n=8)
    Zona: 54 colunas
    Importance: 0.000873
  Predicado: Ca kb <= 10.41 (n=16)
    Zona: 54 colunas
    Importance: 0.000556
  Predicado: Ti <= -6.18 (n=5)
    Zona: 144 colunas
    Importance: 0.002668
  Predicado: Ti > -6.18 (n=15)
    Zona: 144 colunas
    Importance: 0.001686
  Predicado: Ti <= -4.74 (n=10)
    Zona: 144 colunas
    Importance: 0.002052
  Predicado: Ti > -4.74 (n=10)
    Zona: 144 colunas
    Importance: 0.001810
  Predicado: Ti <= 4.28 (n=13)
    Zona: 144 colunas
    Importance: 0.001709
  Predicado: Ti > 4.28 (n=7)
    Zona: 144 colunas
    Importance: 0.002345
  Predicado: Ti <= 8.03 (n=17)
    Zona: 144 colunas
    Importance: 0.001539
  Predicado: background3 <= -6.23 (n=5)
    Zona: 268 colunas
    Importance: 0.000742
  Predicado: background3 > -6.23 (n=15)
    Zona: 268 colunas
    Importance: 0.000833
  Predicado: background3 <= -5.14 (n=10)
    Zona: 268 colunas
    Importance: 0.000560
  Predicado: background3 > -5.14 (n=10)
    Zona: 268 colunas
    Importance: 0.001061
  Predicado: background3 <= 4.89 (n=12)
    Zona: 268 colunas
    Importance: 0.000518
  Predicado: background3 > 4.89 (n=8)
    Zona: 268 colunas
    Importance: 0.001250
  Predicado: background3 <= 10.15 (n=16)
    Zona: 268 colunas
    Importance: 0.000651
  Predicado: Fe ka <= -24.00 (n=5)
    Zona: 115 colunas
    Importance: 0.008564
  Predicado: Fe ka > -24.00 (n=15)
    Zona: 115 colunas
    Importance: 0.005116
  Predicado: Fe ka <= -16.96 (n=9)
    Zona: 115 colunas
    Importance: 0.007654
  Predicado: Fe ka > -16.96 (n=11)
    Zona: 115 colunas
    Importance: 0.004608
  Predicado: Fe ka <= -10.29 (n=14)
    Zona: 115 colunas
    Importance: 0.006701
  Predicado: Fe ka > -10.29 (n=6)
    Zona: 115 colunas

,Predicate_pert_Seed_0,Predicate_pert_Seed_1,Predicate_pert_Seed_2,Predicate_pert_Seed_3
0,Fe ka > 10.08,K > 48.39,K > 48.39,K > 48.39
1,K > -20.13,background1 > 33.08,background1 > 33.08,Ca ka > 48.39
2,K > 48.39,Ca ka > 48.39,background7 > 17.05,Ca ka > -20.13
3,K > -38.25,background7 > 17.05,Ca ka > 48.39,background7 > 17.05
4,background1 > 33.08,K > -20.13,K > -20.13,background1 > 33.08
...,...,...,...,...
189,Zn kb <= -10.75,Zn kb > -8.99,Pb Lb <= 6.53,Zn kb <= -10.75
190,Zn kb <= -7.43,Zn kb <= 8.42,Zn kb <= -7.43,Zn kb <= -7.43
191,Zn kb <= 8.42,Class_A,Class_A,Zn kb <= 8.42
192,Class_A,Class_B,Class_B,Class_A
193,Class_B,NaN,NaN,Class_B

In [26]:
all_results_pert[0]['pert_results_dict']['Bag_9']

               Predicate  Perturbation
0    background7 > 17.05      0.023601
1          Fe ka > 10.08      0.021430
2             K > -20.13      0.021031
3         Ca ka > -20.13      0.018558
4     background7 > 7.87      0.018384
..                   ...           ...
148        Zn kb > -8.99      0.000293
149       Zn kb <= -8.99      0.000286
150       Zn kb > -10.75      0.000281
151       Zn kb <= -7.43      0.000224
152        Zn kb <= 8.42      0.000206

[153 rows x 2 columns]

In [27]:
# Somar LRCs de predicados equivalentes entre diferentes seeds
lrc_combined_list = []

for seed in random_seeds:
    lrc_df = lrc_pert_by_seed[seed].copy()
    lrc_combined_list.append(lrc_df) # o append adiciona o dataframe ao final da lista

# Concatenar todos os dataframes
lrc_all_seeds = pd.concat(lrc_combined_list, ignore_index=True) 

# Agrupar por predicado (Node) e somar as LRCs, mantendo Zone, Threshold e Operator
lrc_summed_df = lrc_all_seeds.groupby('Node').agg({ # o .agg pode ser usado para aplicar múltiplas funções de agregação
    'Local_Reaching_Centrality': 'mean', # sum = somando as LRCs, poderia ser média ou outro agregado
    'Zone': 'first',
    'Threshold': 'first',
    'Operator': 'first'
}).reset_index()

# Ordenar pelo valor de LRC somado (maior para menor)
lrc_summed_df = lrc_summed_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
# vamoss pegar so os valore sunicos de lrc_summed_df baseado na zona espectral
lrc_summed_unique_df_pert = lrc_summed_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
lrc_summed_unique_df_pert = lrc_summed_unique_df_pert.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
lrc_summed_unique_df_pert

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator
0,K > 48.39,5.524792,K,48.39,>
1,background1 > 33.08,4.843951,background1,33.08,>
2,Ca ka > 48.39,4.715373,Ca ka,48.39,>
3,background7 > 17.05,4.633477,background7,17.05,>
4,Fe ka > 10.08,3.990992,Fe ka,10.08,>
5,Cl > 94.61,3.871913,Cl,94.61,>
6,Mo compton scattering > 86.16,3.460642,Mo compton scattering,86.16,>
7,Zn ka > 17.61,2.123206,Zn ka,17.61,>
8,Si > 44.53,2.098843,Si,44.53,>
9,Ga <= -13.34,1.989977,Ga,-13.34,<=
10,background6 > 20.08,1.707363,background6,20.08,>
11,Ni > -4.20,1.324462,Ni,-4.20,>
12,Cu > -14.20,1.320216,Cu,-14.20,>
13,Mo rayleigh scattering > -71.50,1.278210,Mo rayleigh scattering,-71.50,>
14,background5 > 7.96,1.023782,background5,7.96,>
15,Ti > 8.03,0.960042,Ti,8.03,>
16,Pb La > 5.22,0.925064,Pb La,5.22,>
17,Fe kb > 8.67,0.863261,Fe kb,8.67,>
18,background4 > 8.23,0.764446,background4,8.23,>
19,background3 > 4.89,0.703244,background3,4.89,>
20,Ca kb > 10.41,0.669476,Ca kb,10.41,>
21,background2 > 5.59,0.665989,background2,5.59,>
22,Pb Lb > 6.53,0.612085,Pb Lb,6.53,>
23,Zn kb > 8.42,0.503102,Zn kb,8.42,>
24,Class_B,0.000000,None,None,None

In [28]:
import numpy as np

max_len = max(
    len(pvector_unique_df['Zone']),
    #len(shap_unique_df['Zone']),
    len(permutation_unique_df['Zone']),
    len(lrc_summed_unique_df_pert['Zone']),
    len(lrc_summed_unique_df_cov['Zone'])
)

def pad_list(lst, length):
    return list(lst) + [None] * (length - len(lst))

features_importance = pd.DataFrame({
    'SVM_pvector': pad_list(pvector_unique_df['Zone'], max_len),
    #'Shap': pad_list(shap_unique_df['Zone'], max_len),
    'Permutation': pad_list(permutation_unique_df['Zone'], max_len),
    'LRC_perturbation' : pad_list(lrc_summed_unique_df_pert['Zone'], max_len),
    'LRC_covariance' : pad_list(lrc_summed_unique_df_cov['Zone'], max_len),
})

features_importance.to_csv('feature_importance.csv', index=False, sep=';')
features_importance

,SVM_pvector,Permutation,LRC_perturbation,LRC_covariance
0,background1,Cl,K,Cu
1,Ga,Mo rayleigh scattering,background1,Cl
2,background6,Mo compton scattering,Ca ka,background7
3,Mo rayleigh scattering,Si,background7,Ni
4,Ti,Ca ka,Fe ka,Mo rayleigh scattering
5,background7,background1,Cl,Zn ka
6,background5,Fe ka,Mo compton scattering,Mo compton scattering
7,Fe ka,Ga,Zn ka,background3
8,Cl,Zn ka,Si,Ca ka
9,Mo compton scattering,background7,Ga,Si
10,Si,Cu,background6,Ca kb
11,Ca ka,Ni,Ni,background2
12,background4,background6,Cu,K
13,background3,Zn kb,Mo rayleigh scattering,Pb Lb
14,background2,Fe kb,background5,Fe ka
15,Pb La,Ti,Ti,Fe kb
16,Pb Lb,Pb La,Pb La,Pb La
17,Ni,background4,Fe kb,background4
18,Ca kb,background3,background4,Ga
19,Cu,background5,background3,Ti
20,Fe kb,Pb Lb,Ca kb,Zn kb
21,Zn ka,Ca kb,background2,background6
22,Zn kb,background2,Pb Lb,background1
23,None,None,Zn kb,background5
24,None,None,None,None

In [30]:
import rbo

rbo_comparison = pd.DataFrame(columns=['Method_1', 'Method_2', 'RBO_Score'])
methods = features_importance.columns.tolist()
for i in range(len(methods)):
    for j in range(i + 1, len(methods)):
        method_1 = methods[i]
        method_2 = methods[j]
        list_1 = features_importance[method_1].tolist()
        list_2 = features_importance[method_2].tolist()
        rbo_score = rbo.RankingSimilarity(list_1, list_2).rbo(p=0.7, k=8)
        rbo_comparison = pd.concat([rbo_comparison, pd.DataFrame({
            'Method_1': [method_1],
            'Method_2': [method_2],
            'RBO_Score': [rbo_score]
        })], ignore_index=True)
rbo_comparison.sort_values(by='RBO_Score', ascending=False, inplace=True)
rbo_comparison.to_csv('rbo_rank.csv', index=False, sep=';')
rbo_comparison

AssertionError: