## Loading data

In [1]:
# generating synthetic spectra with different noise levels
import pandas as pd
import numpy as np
import kennard_stone as ks

# Add parent directory to sys.path so local module 'synthetic' (one level up) can be imported
import sys
from pathlib import Path # for path manipulations
parent_dir = Path.cwd().parent.parent.resolve() # move two levels up from current working directory
if str(parent_dir) not in sys.path: # check to avoid duplicates
    sys.path.insert(0, str(parent_dir)) # insert at the start of sys.path to prioritize local modules

from synthetic import generate_synthetic_spectral_data

config = [
    {
        'nome': 'A',
        'n_amostras': 156,
        'picos': [250, 380, 550, 700, 850],  # 4 picos
        'amp_media': 1.0,
        'amp_std': 0.3,
        'larg_media': 15.0,
        'larg_std': 2.0,
        'ruido_std': 0.04
    },
    {
        'nome': 'B',
        'n_amostras': 146,
        'picos': [50, 250, 380, 550, 850],  # 3 picos (sem pico em 550)
        'amp_media': 1.4,
        'amp_std': 0.5,
        'larg_media': 15.0,
        'larg_std': 1.8,
        'ruido_std': 0.035
    }
]

data_complete = generate_synthetic_spectral_data(
    configuracao_classes=config,
    n_pontos=500,
    x_min=1,
    x_max=1000,
    seed=0
)

import pandas as pd
pd.options.plotting.backend = 'plotly' # setting plotly as the backend for pandas plotting 
data_complete.iloc[:, 1:].T.plot()

In [2]:
# Split dataset by class and create calibration/prediction sets using Kennard-Stone (as in original pipeline)
data_A = data_complete[data_complete['Class'] == 'A'].reset_index(drop=True)
data_B = data_complete[data_complete['Class'] == 'B'].reset_index(drop=True)

# splitting the data into calibration and prediction sets by kennard-stone algorithm
XA_cal, XA_pred = ks.train_test_split(data_A.iloc[:, 1:], test_size=0.30)  # class A
XA_cal = XA_cal.reset_index(drop=True)
XA_pred = XA_pred.reset_index(drop=True)

XB_cal, XB_pred = ks.train_test_split(data_B.iloc[:, 1:], test_size=0.30)  # class B
XB_cal = XB_cal.reset_index(drop=True)
XB_pred = XB_pred.reset_index(drop=True)

Xcalclass = pd.concat([XA_cal, XB_cal], axis=0).reset_index(drop=True)  # concatenating both classes
Xpredclass = pd.concat([XA_pred, XB_pred], axis=0).reset_index(drop=True)
ycalclass = pd.Series(['A']*XA_cal.shape[0] + ['B']*XB_cal.shape[0])  # target for calibration set
ypredclass = pd.Series(['A']*XA_pred.shape[0] + ['B']*XB_pred.shape[0])  # target for prediction set

# Xcalclass_prep = Xcalclass.copy()
# Xpredclass_prep = Xpredclass.copy()

# preprocessings
import preprocessings as prepr  # preprocessing methods
Xcalclass_prep, mean_calclass  = prepr.mc(Xcalclass)
Xpredclass_prep = Xpredclass - mean_calclass

# PLS-DA with optimized latent variables
from modeling import pls_optimized

plsda_results = pls_optimized(
    Xcalclass_prep, 
    ycalclass,
    LVmax=1,
    Xpred=Xpredclass_prep,
    ypred=ypredclass,
    aim='classification',
    cv=10
)

# Convenience references used later
pls_model = plsda_results[3]               # fitted PLS model
vip_scores_mat = plsda_results[4]          # VIP scores matrix (features × LV)
y_pred_cont = plsda_results[5].iloc[:, -1] # continuous predictions for Xcalclass (used for MI/Cov)

# plotando o vip scores rapidamente
vip_scores_mat.T.plot()

2026-01-25 12:17:59,283 - kennard_stone.utils._pairwise:114[INFO] - Calculating pairwise distances using scikit-learn.

2026-01-25 12:17:59,287 - kennard_stone.utils._pairwise:114[INFO] - Calculating pairwise distances using scikit-learn.

2026-01-25 12:17:59,315 - kennard_stone.utils._pairwise:114[INFO] - Calculating pairwise distances using scikit-learn.

2026-01-25 12:17:59,317 - kennard_stone.utils._pairwise:114[INFO] - Calculating pairwise distances using scikit-learn.

In [3]:
# calculando a covariancia entre cada variável espectral e a predição do modelo PLS-DA
cov_scores = []
y_pred = plsda_results[5].iloc[:,-1].values # using the continuous predictions from LV=3
for col in Xcalclass_prep.columns:
    x_values = Xcalclass_prep[col].values
    covariance = np.cov(x_values, y_pred)[0, 1] # covariance between x and y
    cov_scores.append(covariance)
cov_scores_df = pd.DataFrame(cov_scores, index=Xcalclass_prep.columns, columns=['Covariance'])
cov_scores_df = np.abs(cov_scores_df)
cov_scores_df.plot()

In [4]:
spectral_cuts = [
('F1', 1.0, 100.0),
('background1', 100.0, 200.0),
('F2', 200.0, 300.0),
('background2', 300.0, 330.0),
('F3', 330.0, 430.0),
('background3', 430.0, 500.0),
('F4', 500.0, 600.0),
('background4', 600.0, 660.0),
('F5', 660.0, 750.0),
('background5', 750.0, 815.0),
('F6', 815.0, 890.0),
('background6', 890.0, 1000.0)
]

import explaining as exp
spectral_zones_class = exp.extract_spectral_zones(Xcalclass_prep, spectral_cuts)
zone_sums_df = exp.aggregate_spectral_zones(spectral_zones_class, aggregator='extreme')
predicates_quantiles = exp.predicates_by_quantiles(zone_sums_df, [0.2, 0.4, 0.6, 0.8])
co_occurrence_matrix_df = predicates_quantiles[2]
predicate_info_dict = exp.create_predicate_info_dict(
    predicates_df=predicates_quantiles[0],
    predicate_indicator_df=predicates_quantiles[1],
    zone_aggregated_df=zone_sums_df,
    y_predicted_numeric=y_pred_cont
)

## VIP, Regression Coefficients e SHAP (como no original)

In [5]:
# VIP scores por energia
vip_scores_df = pd.DataFrame({
    'energy': vip_scores_mat.T.index,
    'VIP_Score': vip_scores_mat.T.iloc[:,0].values
})
vip_scores_df = vip_scores_df.sort_values(by='VIP_Score', ascending=False).reset_index(drop=True)
energy_to_zone_vip = {}
for zone_name, start, end in spectral_cuts:
    for e in vip_scores_df['energy']:
        ef = float(e)
        if start <= ef <= end:
            energy_to_zone_vip[e] = zone_name
vip_scores_df['Zone'] = vip_scores_df['energy'].map(energy_to_zone_vip)
vip_scores_unique_df = vip_scores_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
vip_scores_unique_df = vip_scores_unique_df.sort_values(by='VIP_Score', ascending=False).reset_index(drop=True)

# Coeficientes de regressão do PLS
reg_vet = pd.DataFrame(pls_model.coef_, columns=pls_model.feature_names_in_).T
reg_vet.insert(0, 'energy', reg_vet.index)
reg_vet = reg_vet.reset_index(drop=True)
reg_vet.columns = ['energy','Reg_coef']
reg_vet['Abs_Reg_coef'] = reg_vet['Reg_coef'].abs()
reg_vet = reg_vet.sort_values(by='Abs_Reg_coef', ascending=False).reset_index(drop=True)
energy_to_zone_reg = {}
for zone_name, start, end in spectral_cuts:
    for e in reg_vet['energy']:
        ef = float(e)
        if start <= ef <= end:
            energy_to_zone_reg[e] = zone_name
reg_vet['Zone'] = reg_vet['energy'].map(energy_to_zone_reg)
reg_vet_unique_df = reg_vet.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
reg_vet_unique_df = reg_vet_unique_df.sort_values(by='Abs_Reg_coef', ascending=False).reset_index(drop=True)

# vamos agora extrair as variaveis mais importantes atraves do método SHAP
# import shap

# # Para PLSRegression, usamos KernelExplainer porque não há explainer dedicado muito rápido
# explainer_pls = shap.KernelExplainer(plsda_results[3].predict, Xcalclass_prep)
# shap_values_pls = explainer_pls(Xcalclass_prep)

# shap_global_importance = pd.DataFrame({
#     'energy': Xpredclass_prep.columns,
#     'Mean_Abs_SHAP': np.abs(shap_values_pls.values).mean(axis=0)}) # tomando a importancia global como a media dos valores absolutos dos valores SHAP para cada feature
# shap_global_importance.sort_values(by='Mean_Abs_SHAP', ascending=False, inplace=True)

# # vamos gerar uma nova coluna em shap_global_importance com o nome da zona espectral correspondente de acordo com a lista spectral_cuts
# energy_to_zone_shap = {}
# for zone_name, start, end in spectral_cuts:
#     for i in shap_global_importance['energy']:
#         i_float = float(i)
#         if start <= i_float <= end:
#             energy_to_zone_shap[i] = zone_name
# shap_global_importance['Zone'] = shap_global_importance['energy'].map(energy_to_zone_shap)

# # agora vamos filtrar shap_global_importance para manter apenas as zonas espectrais únicas com maior SHAP score
# shap_unique_df = shap_global_importance.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
# shap_unique_df = shap_unique_df.sort_values(by='Mean_Abs_SHAP', ascending=False).reset_index(drop=True)
# shap_unique_df.to_csv('shap_bank_notes.csv', index=False, sep=';')
shap_unique_df = pd.read_csv('shap_synthetic.csv', sep=';') # loading previously saved shap_unique_df

# **bagging - covariance**

In [6]:
import explaining as exp

# LISTA DE SEMENTES A TESTAR
random_seeds = [0, 1, 2, 3]

all_results_cov = {}
training_samples = len(Xcalclass)

# LOOP: PROCESSAR CADA SEMENTE
y_predicted_numeric = plsda_results[5].iloc[:, -1] # predições numéricas do modelo

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando semente: {seed}")
    print(f"{'='*70}\n")
    # Bagging
    bags_result_seed = exp.bagging_predicates(
        zone_sums_df=zone_sums_df,
        y_predicted_numeric=y_predicted_numeric,
        predicates_df=predicates_quantiles[0],
        n_bags=10,
        #n_predicates_per_bag=40,
        n_samples_per_bag=int(training_samples*0.8), # 80 % da base para amostrar (convertido para int)
        min_samples_per_predicate=int(training_samples*0.2), # 20 % da base para limitar (convertido para int)
        replace=False,
        sample_bagging=True,
        predicate_bagging=False,
        random_seed=seed
    )
    # Inserir classe prevista
    for bag_name, pred_dict in bags_result_seed.items(): # iterando sobre cada bag
        for pred_rule, df_info in pred_dict.items():
            df_info['Class_Predicted'] = np.where(df_info['Predicted_Y'] >= 0.5, 'A', 'B') # binarizando com threshold 0.5, A = eut, B = dist
    # Calcular MI
    cov_results_dict_seed = exp.calculate_predicate_metrics(
        bags_result=bags_result_seed,
        metric='covariance', # covariance ou mutual_information
        threshold=0.01, # threshold para cortar predicados irrelevantes
        n_neighbors=5
    )
    # Salvar no dicionário principal
    all_results_cov[seed] = {
        'bags_result': bags_result_seed,
        'cov_results_dict': cov_results_dict_seed
    }

# CONSTRUÇÃO DE GRAFOS PARA MÚLTIPLAS SEMENTES (LOOP EXTERNO)
# Dicionário para armazenar grafos
graphs_by_seed = {}

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando Grafo - Semente: {seed}")
    print(f"{'='*70}\n")
    # Construir grafo para esta semente
    DG = exp.build_predicate_graph(
        bags_result=all_results_cov[seed]['bags_result'],
        mi_results_dict=all_results_cov[seed]['cov_results_dict'],
        co_occurrence_matrix_df=co_occurrence_matrix_df,
        predicates_df=predicates_quantiles[0],
        random_state=seed,
        show_details=True
    )
    # Armazenar grafo
    graphs_by_seed[seed] = DG  

# Calcular LRC usando a função pronta do explaining.py
lrc_cov_by_seed = {}
for seed in random_seeds:
    DG = graphs_by_seed[seed]
    lrc_cov_df_seed = exp.calculate_lrc_single_graph(DG, predicates_quantiles[0])
    lrc_cov_df_seed['Seed'] = seed  # Adicionar coluna com a semente
    lrc_cov_by_seed[seed] = lrc_cov_df_seed

# junando todas as colunas 'Node' de lrc_by_seed em um único dataframe
lrc_cov_all_seeds_df = pd.DataFrame()
for seed in random_seeds:
    lrc_cov_df_seed = lrc_cov_by_seed[seed].rename(columns={'Node': f'Predicate_Cov_Seed_{seed}'})
    lrc_cov_all_seeds_df = pd.concat([lrc_cov_all_seeds_df, lrc_cov_df_seed[[f'Predicate_Cov_Seed_{seed}']]], axis=1)

# vamos filtrar lrc_by_seed em cada semente para manter apenas as zonas espectrais únicas com maior LRC em um mesmo dataframe
lrc_cov_unique_by_seed = {}
for seed, lrc_df in lrc_cov_by_seed.items():
    lrc_cov_unique_df = lrc_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
    lrc_cov_unique_df = lrc_cov_unique_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
    lrc_cov_unique_by_seed[seed] = lrc_cov_unique_df

lrc_cov_all_seeds_df # exibindo o dataframe consolidado com predicados de todas as sementes

======================================================================
Processando semente: 0
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 73 | Descartados: 23
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 74 | Descartados: 22
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 74 | Descartados: 22
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 75 | Descartados: 21
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 73 | Descartados: 23
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 74 | Descartados: 22
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 73 | Descartados: 23
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 73 | Descartados: 23
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 74 | Descartados: 22
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 74 | Descartados: 22
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando semente: 1
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 74 | Descartados: 22
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 74 | Descartados: 22
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 75 | Descartados: 21
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 73 | Descartados: 23
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 74 | Descartados: 22
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 74 | Descartados: 22
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 73 | Descartados: 23
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 73 | Descartados: 23
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 74 | Descartados: 22
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 73 | Descartados: 23

Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando semente: 2
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 74 | Descartados: 22
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 74 | Descartados: 22
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 75 | Descartados: 21
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 73 | Descartados: 23
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 73 | Descartados: 23
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 74 | Descartados: 22
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 74 | Descartados: 22
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 74 | Descartados: 22
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 75 | Descartados: 21
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 74 | Descartados: 22
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando semente: 3
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 73 | Descartados: 23
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 73 | Descartados: 23
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 74 | Descartados: 22
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 73 | Descartados: 23
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 74 | Descartados: 22
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 73 | Descartados: 23
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 74 | Descartados: 22
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 73 | Descartados: 23
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 73 | Descartados: 23
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 73 | Descartados: 23
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando Grafo - Semente: 0
======================================================================


Total de pares bidirecionais encontrados: 38
Removida aresta F5 > -0.52 -> F5 <= 0.61 (peso 89.0)
Mantida aresta F5 <= 0.61 -> F5 > -0.52 (peso 801.0)

======================================================================

Empate! Removida aresta F4 > -0.24 -> F2 > -0.45 (peso 306.0)
Mantida aresta F2 > -0.45 -> F4 > -0.24 (peso 306.0)

======================================================================

Removida aresta F2 > -0.45 -> F4 > -0.47 (peso 134.0)
Mantida aresta F4 > -0.47 -> F2 > -0.45 (peso 268.0)

======================================================================

Removida aresta F4 > -0.47 -> F3 > -0.43 (peso 132.0)
Mantida aresta F3 > -0.43 -> F4 > -0.47 (peso 264.0)

======================================================================

Removida aresta F3 > -0.43 -> F6 > -0.42 (peso 268.0)
Mantida aresta F6 > -0.42 -> F3 > -0.43 (peso 536.0)

======================================================================

Removida aresta F2 > -0.23 -> F3 > -0.43 (peso 105.0)
Mantida aresta F3 > -0.43 -> F2 > -0.23 (peso 210.0)

======================================================================

Removida aresta F4 > -0.24 -> F4 > -0.47 (peso 504.0)
Mantida aresta F4 > -0.47 -> F4 > -0.24 (peso 630.0)

======================================================================

Removida aresta F3 > -0.23 -> F6 > -0.42 (peso 106.0)
Mantida aresta F6 > -0.42 -> F3 > -0.23 (peso 424.0)

======================================================================

Removida aresta F6 > 0.13 -> F3 > -0.23 (peso 57.0)
Mantida aresta F3 > -0.23 -> F6 > 0.13 (peso 114.0)

======================================================================

Removida aresta F6 > -0.25 -> F3 > -0.23 (peso 78.0)
Mantida aresta F3 > -0.23 -> F6 > -0.25 (peso 468.0)

======================================================================

Removida aresta F6 > -0.42 -> F2 > -0.23 (peso 106.0)
Mantida aresta F2 > -0.23 -> F6 > -0.42 (peso 212.0)

======================================================================

Removida aresta F6 > 0.13 -> F6 > -0.25 (peso 84.0)
Mantida aresta F6 > -0.25 -> F6 > 0.13 (peso 420.0)

======================================================================

Empate! Removida aresta F6 > -0.25 -> F2 > -0.23 (peso 166.0)
Mantida aresta F2 > -0.23 -> F6 > -0.25 (peso 166.0)

======================================================================

Removida aresta F2 > 0.17 -> F5 <= 0.24 (peso 63.0)
Mantida aresta F5 <= 0.24 -> F2 > 0.17 (peso 126.0)

======================================================================

Empate! Removida aresta F3 <= 0.44 -> F5 <= 0.24 (peso 172.0)
Mantida aresta F5 <= 0.24 -> F3 <= 0.44 (peso 172.0)

======================================================================

Removida aresta F2 > 0.17 -> F3 > 0.14 (peso 40.0)
Mantida aresta F3 > 0.14 -> F2 > 0.17 (peso 160.0)

======================================================================

Removida aresta F2 <= 0.40 -> F3 > 0.14 (peso 60.0)
Mantida aresta F3 > 0.14 -> F2 <= 0.40 (peso 120.0)

======================================================================

Removida aresta F1 > 0.22 -> F3 > 0.14 (peso 51.0)
Mantida aresta F3 > 0.14 -> F1 > 0.22 (peso 102.0)

======================================================================

Removida aresta F4 > 0.18 -> F3 > 0.14 (peso 43.0)
Mantida aresta F3 > 0.14 -> F4 > 0.18 (peso 86.0)

======================================================================

Removida aresta F3 <= 0.44 -> F2 > 0.17 (peso 63.0)
Mantida aresta F2 > 0.17 -> F3 <= 0.44 (peso 252.0)

======================================================================

Empate! Removida aresta F1 > 0.22 -> F2 > 0.17 (peso 53.0)
Mantida aresta F2 > 0.17 -> F1 > 0.22 (peso 53.0)

======================================================================

Removida aresta F4 > 0.18 -> F3 <= 0.44 (peso 58.0)
Mantida aresta F3 <= 0.44 -> F4 > 0.18 (peso 116.0)

======================================================================

Removida aresta F4 > 0.18 -> F1 > 0.22 (peso 106.0)
Mantida aresta F1 > 0.22 -> F4 > 0.18 (peso 159.0)

======================================================================

Removida aresta F1 <= 0.22 -> F4 > 0.18 (peso 31.0)
Mantida aresta F4 > 0.18 -> F1 <= 0.22 (peso 93.0)

======================================================================

Removida aresta F1 <= 0.22 -> F2 <= 0.40 (peso 119.0)
Mantida aresta F2 <= 0.40 -> F1 <= 0.22 (peso 357.0)

======================================================================

Removida aresta F4 <= 0.50 -> F2 <= 0.40 (peso 408.0)
Mantida aresta F2 <= 0.40 -> F4 <= 0.50 (peso 544.0)

======================================================================

Empate! Removida aresta F3 <= 0.14 -> F2 <= 0.17 (peso 83.0)
Mantida aresta F2 <= 0.17 -> F3 <= 0.14 (peso 83.0)

======================================================================

Removida aresta F3 <= 0.14 -> background4 > -0.09 (peso 96.0)
Mantida aresta background4 > -0.09 -> F3 <= 0.14 (peso 480.0)

======================================================================

Removida aresta F3 <= 0.14 -> F6 <= 0.13 (peso 85.0)
Mantida aresta F6 <= 0.13 -> F3 <= 0.14 (peso 170.0)

======================================================================

Removida aresta background4 > -0.09 -> F2 <= 0.17 (peso 99.0)
Mantida aresta F2 <= 0.17 -> background4 > -0.09 (peso 297.0)

======================================================================

Empate! Removida aresta F6 <= 0.13 -> F2 <= 0.17 (peso 174.0)
Mantida aresta F2 <= 0.17 -> F6 <= 0.13 (peso 174.0)

======================================================================

Removida aresta F2 <= 0.17 -> F6 <= 0.42 (peso 226.0)
Mantida aresta F6 <= 0.42 -> F2 <= 0.17 (peso 339.0)

======================================================================

Removida aresta background4 > -0.09 -> F6 <= 0.13 (peso 102.0)
Mantida aresta F6 <= 0.13 -> background4 > -0.09 (peso 510.0)

======================================================================

Removida aresta background4 > -0.07 -> F5 > 0.24 (peso 106.0)
Mantida aresta F5 > 0.24 -> background4 > -0.07 (peso 265.0)

======================================================================

Removida aresta F6 <= -0.25 -> background4 > -0.07 (peso 44.0)
Mantida aresta background4 > -0.07 -> F6 <= -0.25 (peso 88.0)

======================================================================

Empate! Removida aresta background4 > -0.07 -> background6 <= 0.10 (peso 92.0)
Mantida aresta background6 <= 0.10 -> background4 > -0.07 (peso 92.0)

======================================================================

Removida aresta F6 <= -0.25 -> F5 > 0.24 (peso 46.0)
Mantida aresta F5 > 0.24 -> F6 <= -0.25 (peso 92.0)

======================================================================

Removida aresta F6 <= -0.25 -> background6 <= 0.10 (peso 64.0)
Mantida aresta background6 <= 0.10 -> F6 <= -0.25 (peso 128.0)

======================================================================


Total de arestas iniciais: 161
Total de arestas removidas por bidirecionalidade: 38
Arestas bidirecionais restantes: 0
Total de nós predicados: 37
Total de nós terminais: 2


======================================================================
Processando Grafo - Semente: 1
======================================================================


Total de pares bidirecionais encontrados: 43
Removida aresta F5 > -0.52 -> F5 <= 0.61 (peso 89.0)
Mantida aresta F5 <= 0.61 -> F5 > -0.52 (peso 801.0)

======================================================================

Removida aresta F4 > -0.24 -> F4 > -0.47 (peso 252.0)
Mantida aresta F4 > -0.47 -> F4 > -0.24 (peso 756.0)

======================================================================

Empate! Removida aresta F4 > -0.47 -> F6 > -0.42 (peso 135.0)
Mantida aresta F6 > -0.42 -> F4 > -0.47 (peso 135.0)

======================================================================

Empate! Removida aresta F2 > -0.45 -> F4 > -0.47 (peso 134.0)
Mantida aresta F4 > -0.47 -> F2 > -0.45 (peso 134.0)

======================================================================

Removida aresta F3 > -0.43 -> F4 > -0.24 (peso 98.0)
Mantida aresta F4 > -0.24 -> F3 > -0.43 (peso 294.0)

======================================================================

Empate! Removida aresta F4 > -0.24 -> F2 > -0.45 (peso 306.0)
Mantida aresta F2 > -0.45 -> F4 > -0.24 (peso 306.0)

======================================================================

Removida aresta F3 > -0.43 -> F2 > -0.45 (peso 134.0)
Mantida aresta F2 > -0.45 -> F3 > -0.43 (peso 402.0)

======================================================================

Removida aresta F6 > -0.42 -> F3 > -0.43 (peso 134.0)
Mantida aresta F3 > -0.43 -> F6 > -0.42 (peso 402.0)

======================================================================

Removida aresta F6 > 0.13 -> F3 > -0.43 (peso 72.0)
Mantida aresta F3 > -0.43 -> F6 > 0.13 (peso 144.0)

======================================================================

Removida aresta F6 > -0.42 -> F2 > -0.45 (peso 136.0)
Mantida aresta F2 > -0.45 -> F6 > -0.42 (peso 272.0)

======================================================================

Removida aresta F3 > -0.23 -> F6 > -0.42 (peso 106.0)
Mantida aresta F6 > -0.42 -> F3 > -0.23 (peso 212.0)

======================================================================

Removida aresta F3 > -0.23 -> F6 > -0.25 (peso 78.0)
Mantida aresta F6 > -0.25 -> F3 > -0.23 (peso 234.0)

======================================================================

Empate! Removida aresta F3 > -0.23 -> F2 > -0.23 (peso 252.0)
Mantida aresta F2 > -0.23 -> F3 > -0.23 (peso 252.0)

======================================================================

Removida aresta F6 > 0.13 -> F6 > -0.42 (peso 84.0)
Mantida aresta F6 > -0.42 -> F6 > 0.13 (peso 168.0)

======================================================================

Removida aresta F2 > -0.23 -> F6 > 0.13 (peso 60.0)
Mantida aresta F6 > 0.13 -> F2 > -0.23 (peso 120.0)

======================================================================

Removida aresta F6 > -0.25 -> F6 > 0.13 (peso 168.0)
Mantida aresta F6 > 0.13 -> F6 > -0.25 (peso 420.0)

======================================================================

Removida aresta F2 > -0.23 -> F6 > -0.42 (peso 106.0)
Mantida aresta F6 > -0.42 -> F2 > -0.23 (peso 212.0)

======================================================================

Removida aresta F6 > -0.25 -> F2 > -0.23 (peso 83.0)
Mantida aresta F2 > -0.23 -> F6 > -0.25 (peso 166.0)

======================================================================

Removida aresta F5 <= 0.24 -> F3 > 0.14 (peso 201.0)
Mantida aresta F3 > 0.14 -> F5 <= 0.24 (peso 268.0)

======================================================================

Removida aresta F2 > 0.17 -> F3 > 0.14 (peso 80.0)
Mantida aresta F3 > 0.14 -> F2 > 0.17 (peso 120.0)

======================================================================

Empate! Removida aresta F5 <= 0.24 -> F2 > 0.17 (peso 126.0)
Mantida aresta F2 > 0.17 -> F5 <= 0.24 (peso 126.0)

======================================================================

Empate! Removida aresta F5 <= 0.24 -> F4 > 0.18 (peso 69.0)
Mantida aresta F4 > 0.18 -> F5 <= 0.24 (peso 69.0)

======================================================================

Removida aresta F2 > 0.17 -> F1 > 0.22 (peso 53.0)
Mantida aresta F1 > 0.22 -> F2 > 0.17 (peso 106.0)

======================================================================

Removida aresta F3 <= 0.44 -> F2 > 0.17 (peso 63.0)
Mantida aresta F2 > 0.17 -> F3 <= 0.44 (peso 126.0)

======================================================================

Empate! Removida aresta F2 > 0.17 -> F1 <= 0.22 (peso 31.0)
Mantida aresta F1 <= 0.22 -> F2 > 0.17 (peso 31.0)

======================================================================

Removida aresta F1 > 0.22 -> F4 > 0.18 (peso 106.0)
Mantida aresta F4 > 0.18 -> F1 > 0.22 (peso 159.0)

======================================================================

Empate! Removida aresta F1 > 0.22 -> F3 <= 0.44 (peso 114.0)
Mantida aresta F3 <= 0.44 -> F1 > 0.22 (peso 114.0)

======================================================================

Empate! Removida aresta F1 > 0.22 -> F1 <= 0.22 (peso 0.0)
Mantida aresta F1 <= 0.22 -> F1 > 0.22 (peso 0.0)

======================================================================

Removida aresta F2 <= 0.40 -> F1 > 0.22 (peso 49.0)
Mantida aresta F1 > 0.22 -> F2 <= 0.40 (peso 98.0)

======================================================================

Empate! Removida aresta F4 <= 0.50 -> F4 > 0.18 (peso 42.0)
Mantida aresta F4 > 0.18 -> F4 <= 0.50 (peso 42.0)

======================================================================

Empate! Removida aresta F4 > 0.18 -> F2 <= 0.40 (peso 64.0)
Mantida aresta F2 <= 0.40 -> F4 > 0.18 (peso 64.0)

======================================================================

Empate! Removida aresta F4 <= 0.50 -> F3 <= 0.44 (peso 142.0)
Mantida aresta F3 <= 0.44 -> F4 <= 0.50 (peso 142.0)

======================================================================

Removida aresta F4 <= 0.50 -> F2 <= 0.40 (peso 136.0)
Mantida aresta F2 <= 0.40 -> F4 <= 0.50 (peso 816.0)

======================================================================

Removida aresta F6 <= 0.13 -> F2 <= 0.17 (peso 174.0)
Mantida aresta F2 <= 0.17 -> F6 <= 0.13 (peso 261.0)

======================================================================

Empate! Removida aresta F2 <= 0.17 -> F3 <= 0.14 (peso 83.0)
Mantida aresta F3 <= 0.14 -> F2 <= 0.17 (peso 83.0)

======================================================================

Empate! Removida aresta F5 > 0.24 -> F2 <= 0.17 (peso 66.0)
Mantida aresta F2 <= 0.17 -> F5 > 0.24 (peso 66.0)

======================================================================

Removida aresta F2 <= 0.17 -> F6 <= 0.42 (peso 113.0)
Mantida aresta F6 <= 0.42 -> F2 <= 0.17 (peso 226.0)

======================================================================

Removida aresta F6 <= 0.13 -> F6 <= 0.42 (peso 127.0)
Mantida aresta F6 <= 0.42 -> F6 <= 0.13 (peso 889.0)

======================================================================

Removida aresta F6 <= -0.25 -> background4 > -0.09 (peso 134.0)
Mantida aresta background4 > -0.09 -> F6 <= -0.25 (peso 201.0)

======================================================================

Removida aresta F6 <= -0.25 -> background4 > -0.07 (peso 88.0)
Mantida aresta background4 > -0.07 -> F6 <= -0.25 (peso 132.0)

======================================================================

Removida aresta background4 > -0.09 -> F3 <= 0.14 (peso 288.0)
Mantida aresta F3 <= 0.14 -> background4 > -0.09 (peso 480.0)

======================================================================

Empate! Removida aresta F5 > 0.24 -> background4 > -0.07 (peso 159.0)
Mantida aresta background4 > -0.07 -> F5 > 0.24 (peso 159.0)

======================================================================

Removida aresta background6 <= 0.08 -> F5 > 0.24 (peso 48.0)
Mantida aresta F5 > 0.24 -> background6 <= 0.08 (peso 96.0)

======================================================================


Total de arestas iniciais: 165
Total de arestas removidas por bidirecionalidade: 43
Arestas bidirecionais restantes: 0
Total de nós predicados: 38
Total de nós terminais: 2


======================================================================
Processando Grafo - Semente: 2
======================================================================


Total de pares bidirecionais encontrados: 40
Removida aresta F2 > -0.45 -> F4 > -0.47 (peso 402.0)
Mantida aresta F4 > -0.47 -> F2 > -0.45 (peso 536.0)

======================================================================

Empate! Removida aresta F4 > -0.47 -> F4 > -0.24 (peso 252.0)
Mantida aresta F4 > -0.24 -> F4 > -0.47 (peso 252.0)

======================================================================

Empate! Removida aresta F6 > -0.42 -> F4 > -0.24 (peso 208.0)
Mantida aresta F4 > -0.24 -> F6 > -0.42 (peso 208.0)

======================================================================

Removida aresta F6 > -0.42 -> F3 > -0.43 (peso 134.0)
Mantida aresta F3 > -0.43 -> F6 > -0.42 (peso 402.0)

======================================================================

Removida aresta F2 > -0.23 -> F6 > -0.42 (peso 106.0)
Mantida aresta F6 > -0.42 -> F2 > -0.23 (peso 424.0)

======================================================================

Empate! Removida aresta F2 > -0.23 -> F4 > -0.24 (peso 79.0)
Mantida aresta F4 > -0.24 -> F2 > -0.23 (peso 79.0)

======================================================================

Removida aresta F2 > -0.23 -> F3 > -0.43 (peso 105.0)
Mantida aresta F3 > -0.43 -> F2 > -0.23 (peso 210.0)

======================================================================

Empate! Removida aresta F3 > -0.43 -> F6 > -0.25 (peso 103.0)
Mantida aresta F6 > -0.25 -> F3 > -0.43 (peso 103.0)

======================================================================

Empate! Removida aresta F3 > -0.43 -> F6 > 0.13 (peso 72.0)
Mantida aresta F6 > 0.13 -> F3 > -0.43 (peso 72.0)

======================================================================

Removida aresta F3 > -0.23 -> F2 > -0.23 (peso 84.0)
Mantida aresta F2 > -0.23 -> F3 > -0.23 (peso 168.0)

======================================================================

Removida aresta F6 > 0.13 -> F6 > -0.25 (peso 84.0)
Mantida aresta F6 > -0.25 -> F6 > 0.13 (peso 168.0)


/home/jvribeiro/.local/lib/python3.10/site-packages/networkx/algorithms/centrality/reaching.py:193: RuntimeWarning:

divide by zero encountered in scalar divide

/home/jvribeiro/.local/lib/python3.10/site-packages/networkx/algorithms/centrality/reaching.py:193: RuntimeWarning:

divide by zero encountered in scalar divide

/home/jvribeiro/.local/lib/python3.10/site-packages/networkx/algorithms/centrality/reaching.py:193: RuntimeWarning:

divide by zero encountered in scalar divide

/home/jvribeiro/.local/lib/python3.10/site-packages/networkx/algorithms/centrality/reaching.py:193: RuntimeWarning:

divide by zero encountered in scalar divide

,Predicate_Cov_Seed_0,Predicate_Cov_Seed_1,Predicate_Cov_Seed_2,Predicate_Cov_Seed_3
0,F1 > -0.71,F1 > -0.71,F1 > -0.71,F1 > -0.71
1,F1 > -0.69,F1 > -0.69,F1 > -0.69,F1 > -0.69
2,F5 > -0.54,F5 > -0.54,F5 > -0.54,F5 > -0.54
3,F1 <= 0.83,F1 <= 0.83,F1 <= 0.83,F1 <= 0.83
4,F5 <= 0.61,F5 <= 0.61,F5 <= 0.61,F5 <= 0.61
5,F5 > -0.52,F5 > -0.52,F5 > -0.52,F4 > -0.24
6,F6 > -0.42,F2 <= 0.40,F4 > -0.47,F2 > -0.45
7,F2 > -0.45,F1 <= 0.22,F4 > -0.24,F5 > -0.52
8,F3 > -0.23,F4 > -0.47,F2 > -0.45,F2 <= 0.40
9,F6 > -0.25,F3 > -0.43,F3 > -0.43,F6 > -0.42
10,F4 > -0.47,F4 > -0.24,F2 <= 0.40,F4 > -0.47
11,F4 > -0.24,F2 > -0.45,F6 > -0.42,F3 > -0.43
12,F6 > 0.13,F6 > 0.13,F3 > -0.23,F6 > -0.25
13,F2 > -0.23,F5 <= 0.24,F4 > 0.18,F6 > 0.13
14,F3 > -0.43,F1 > 0.22,F3 <= 0.44,F3 > 0.14
15,F1 <= 0.22,F3 > 0.14,F5 <= 0.24,F3 <= 0.44
16,F4 <= 0.50,F4 <= 0.50,F2 > -0.23,F1 > 0.22
17,F3 <= 0.44,F6 > -0.42,F1 > 0.22,F3 > -0.23
18,F2 > 0.17,F6 <= 0.42,F6 > 0.13,F2 > 0.17
19,F2 <= 0.40,F3 <= 0.44,F3 > 0.14,F4 > 0.18
20,F1 > 0.22,F3 > -0.23,F2 > 0.17,F5 <= 0.24
21,F5 <= 0.24,F6 > -0.25,F6 > -0.25,F1 <= 0.22
22,F4 > 0.18,F2 > -0.23,F1 <= 0.22,F2 > -0.23
23,F3 > 0.14,F4 > 0.18,F4 <= 0.50,F4 <= 0.50
24,F6 <= 0.13,F2 > 0.17,F6 <= 0.42,F6 <= 0.42
25,F6 <= 0.42,F2 <= 0.17,F6 <= 0.13,F2 <= 0.17
26,F2 <= 0.17,F3 <= 0.14,F5 > 0.24,F3 <= 0.14
27,background4 > -0.09,F6 <= 0.13,F2 <= 0.17,F6 <= 0.13
28,F4 <= -0.24,F4 <= 0.18,F3 <= 0.14,background4 > -0.09
29,background6 <= 0.08,background4 > -0.07,background4 > -0.09,background4 > -0.07
30,F6 <= -0.25,background6 <= 0.10,background6 <= 0.08,F5 > 0.24
31,F5 > 0.24,background4 > -0.09,F6 <= -0.25,F6 <= -0.25
32,background6 <= 0.10,F4 <= -0.24,background6 <= 0.10,F4 <= -0.24
33,F3 <= 0.14,F6 <= -0.25,background4 > -0.07,F3 <= -0.23
34,background1 <= 0.08,F5 > 0.24,F4 <= -0.24,F2 <= -0.23
35,background4 > -0.07,background6 <= 0.08,F4 <= 0.18,background6 <= 0.10
36,F4 <= 0.18,F2 <= -0.23,F2 <= -0.23,background3 > -0.08
37,Class_A,background3 > -0.08,background3 <= 0.09,background1 <= 0.08
38,Class_B,Class_A,Class_A,Class_A
39,NaN,Class_B,Class_B,Class_B

In [7]:
from collections import defaultdict

# Coletar posições de cada predicado em cada seed do lrc_pert_all_seeds_df
positions_dict_lrc = defaultdict(list)

# Iterar sobre cada coluna do dataframe lrc_pert_all_seeds_df
for col in lrc_cov_all_seeds_df.columns:
    # Pegar os predicados da coluna (não-nulos)
    predicates_in_seed = lrc_cov_all_seeds_df[col].dropna().tolist()
    
    # Para cada predicado, guardar sua posição (1-based)
    for position, predicate in enumerate(predicates_in_seed, start=1):
        positions_dict_lrc[predicate].append(position)

# Calcular média e número de aparições
results_lrc = []
for predicate, positions in positions_dict_lrc.items():
    zone_row = predicates_quantiles[0].loc[predicates_quantiles[0]['rule'] == predicate, 'zone']
    zone_value = zone_row.values[0] if not zone_row.empty else None
    results_lrc.append({
        'Predicate': predicate,
        'Mean_Position': np.mean(positions),
        'Appearances': len(positions),
        'Zone': zone_value
    })

# Ordenar: menor posição média primeiro, mais aparições em caso de empate
ranking_lrc_cov_df = pd.DataFrame(results_lrc).sort_values(
    by=['Mean_Position', 'Appearances'], 
    ascending=[True, False]
).reset_index(drop=True)

# Lista final ordenada
lista_ordenada_lrc = ranking_lrc_cov_df['Predicate'].tolist()
ranking_lrc_cov_df

              Predicate  Mean_Position  Appearances         Zone
0            F1 > -0.71       1.000000            4           F1
1            F1 > -0.69       2.000000            4           F1
2            F5 > -0.54       3.000000            4           F5
3            F1 <= 0.83       4.000000            4           F1
4            F5 <= 0.61       5.000000            4           F5
5            F5 > -0.52       6.500000            4           F5
6            F2 > -0.45       9.000000            4           F2
7            F4 > -0.24       9.250000            4           F4
8            F4 > -0.47       9.500000            4           F4
9            F6 > -0.42      11.750000            4           F6
10           F3 > -0.43      11.750000            4           F3
11           F2 <= 0.40      11.750000            4           F2
12            F6 > 0.13      14.750000            4           F6
13           F3 > -0.23      15.250000            4           F3
14           F6 > -0.25      16.750000            4           F6
15           F1 <= 0.22      17.250000            4           F1
16           F3 <= 0.44      17.250000            4           F3
17            F1 > 0.22      17.750000            4           F1
18           F5 <= 0.24      18.250000            4           F5
19            F3 > 0.14      18.750000            4           F3
20           F2 > -0.23      19.250000            4           F2
21            F4 > 0.18      20.250000            4           F4
22           F4 <= 0.50      20.500000            4           F4
23            F2 > 0.17      21.000000            4           F2
24           F6 <= 0.42      23.750000            4           F6
25           F6 <= 0.13      26.750000            4           F6
26           F2 <= 0.17      26.750000            4           F2
27           F3 <= 0.14      29.250000            4           F3
28  background4 > -0.09      29.750000            4  background4
29            F5 > 0.24      31.250000            4           F5
30          F6 <= -0.25      32.250000            4           F6
31  background6 <= 0.08      32.333333            3  background6
32          F4 <= -0.24      32.500000            4           F4
33  background4 > -0.07      32.500000            4  background4
34  background6 <= 0.10      33.250000            4  background6
35           F4 <= 0.18      34.000000            3           F4
36          F3 <= -0.23      34.000000            1           F3
37          F2 <= -0.23      36.333333            3           F2
38  background1 <= 0.08      36.500000            2  background1
39  background3 > -0.08      37.500000            2  background3
40  background3 <= 0.09      38.000000            1  background3
41              Class_A      38.750000            4         None
42              Class_B      39.750000            4         None

In [9]:
ranking_cov_lrc_unique_df = ranking_lrc_cov_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
ranking_cov_lrc_unique_df['Zone']

0              F1
1              F5
2              F2
3              F4
4              F6
5              F3
6     background4
7     background6
8     background1
9     background3
10           None
Name: Zone, dtype: object

# **Perturbation**

In [10]:
import explaining as exp

# LISTA DE SEMENTES A TESTAR
random_seeds = [0, 1, 2, 3]

all_results_pert = {}
training_samples = len(Xcalclass)

# LOOP: PROCESSAR CADA SEMENTE
y_predicted_numeric = plsda_results[5].iloc[:, -1] # predições numéricas do modelo

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando semente: {seed}")
    print(f"{'='*70}\n")
    # Bagging
    bags_result_seed = exp.bagging_predicates(
        zone_sums_df=zone_sums_df,
        y_predicted_numeric=y_predicted_numeric,
        predicates_df=predicates_quantiles[0],
        n_bags=10,
        #n_predicates_per_bag=40,
        n_samples_per_bag=int(training_samples*0.8), # 80 % da base para amostrar (convertido para int)
        min_samples_per_predicate=int(training_samples*0.2), # 20 % da base para limitar (convertido para int)
        replace=False,
        sample_bagging=True,
        predicate_bagging=False,
        random_seed=seed
    )
    # Inserir classe prevista
    for bag_name, pred_dict in bags_result_seed.items(): # iterando sobre cada bag
        for pred_rule, df_info in pred_dict.items():
            df_info['Class_Predicted'] = np.where(df_info['Predicted_Y'] >= 0.5, 'A', 'B') # binarizando com threshold 0.5, A = eut, B = dist

    pert_results_seed = exp.calculate_predicate_perturbation(
        estimator=pls_model,
        Xcalclass_prep=Xcalclass_prep,
        folds_struct=bags_result_seed,
        predicates_df=predicates_quantiles[0],
        spectral_cuts=spectral_cuts,
        perturbation_value=0,
        metric='mean_relative_dev',   # Média com sinal (pode ser negativo)
        verbose=True
    )

    # Remove todos os valores iguais a zero de todos os bags em perm_results[bag]["Permutation"] e salva como perm_results_thresholded
    # pert_results_seed_thresholded = {}
    # for bag, df in perm_results_seed.items():
    #     # Verifica se é um DataFrame e se a coluna 'Permutation' existe
    #     if isinstance(df, pd.DataFrame) and 'Permutation' in df.columns:
    #         filtered_df = df[df['Permutation'] > 0].copy()
    #         pert_results_seed_thresholded[bag] = filtered_df
    #     else:
    #         # Se não for DataFrame esperado, apenas copia
    #         pert_results_seed_thresholded[bag] = df

    # Salvar no dicionário principal
    all_results_pert[seed] = {
        'bags_result': bags_result_seed,
        'pert_results_dict': pert_results_seed
    }

# CONSTRUÇÃO DE GRAFOS PARA MÚLTIPLAS SEMENTES (LOOP EXTERNO)
# Dicionário para armazenar grafos
graphs_pert_by_seed = {}

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando Grafo - Semente: {seed}")
    print(f"{'='*70}\n")
    # Construir grafo para esta semente
    DG = exp.build_predicate_graph(
        bags_result=all_results_pert[seed]['bags_result'],
        mi_results_dict=all_results_pert[seed]['pert_results_dict'],
        co_occurrence_matrix_df=co_occurrence_matrix_df,
        predicates_df=predicates_quantiles[0],
        random_state=seed,
        show_details=True
    )
    # Armazenar grafo
    graphs_pert_by_seed[seed] = DG  

# Calcular LRC usando a função pronta do explaining.py
lrc_pert_by_seed = {}
for seed in random_seeds:
    DG = graphs_pert_by_seed[seed]
    lrc_pert_df_seed = exp.calculate_lrc_single_graph(DG, predicates_quantiles[0])
    lrc_pert_df_seed['Seed'] = seed  # Adicionar coluna com a semente
    lrc_pert_by_seed[seed] = lrc_pert_df_seed

# junando todas as colunas 'Node' de lrc_by_seed em um único dataframe
lrc_pert_all_seeds_df = pd.DataFrame()
for seed in random_seeds:
    lrc_pert_df_seed = lrc_pert_by_seed[seed].rename(columns={'Node': f'Predicate_pert_Seed_{seed}'})
    lrc_pert_all_seeds_df = pd.concat([lrc_pert_all_seeds_df, lrc_pert_df_seed[[f'Predicate_pert_Seed_{seed}']]], axis=1)

# vamos filtrar lrc_by_seed em cada semente para manter apenas as zonas espectrais únicas com maior LRC em um mesmo dataframe
lrc_pert_unique_by_seed = {}
for seed, lrc_df in lrc_pert_by_seed.items():
    lrc_pert_unique_df = lrc_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
    lrc_pert_unique_df = lrc_pert_unique_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
    lrc_pert_unique_by_seed[seed] = lrc_pert_unique_df

lrc_pert_all_seeds_df # exibindo o dataframe consolidado com predicados de todas as sementes

======================================================================
Processando semente: 0
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 73 | Descartados: 23
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 74 | Descartados: 22
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 74 | Descartados: 22
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 75 | Descartados: 21
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 73 | Descartados: 23
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 74 | Descartados: 22
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 73 | Descartados: 23
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 73 | Descartados: 23
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 74 | Descartados: 22
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 74 | Descartados: 22
======================================================================
PERTURBATION IMPORTANCE PARA PREDICADOS
======================================================================
Valor de perturbação: 0
Métrica: mean_relative_dev
Total de folds: 10


[Bag_1] Processando 73 predicados...
  Predicado: F1 > -0.71 (n=130)
    Zona: 50 colunas
    Importance: 0.717316
  Predicado: F1 <= -0.69 (n=65)
    Zona: 50 colunas
    Importance: 1.225422
  Predicado: F1 > -0.69 (n=103)
    Zona: 50 colunas
    Importance: 0.439466
  Predicado: F1 <= 0.22 (n=100)
    Zona: 50 colunas
    Importance: 1.445913
  Predicado: F1 > 0.22 (n=68)
    Zona: 50 colunas
    Importance: -0.289321
  Predicado: F1 <= 0.83 (n=135)
    Zona: 50 colunas
    Importance: 1.017010
  Predicado: background1 > -0.10 (n=144)
    Zona: 50 colunas
    Importance: 0.000058
  Predicado: background1 <= -0.08 (n=58)
    Zona: 50 colunas
    Importance: 0.000081
  Predicado: background1 > -0.08 (n=110)
    Zona: 50 colunas
    Importance: 0.000019
  Predicado: background1 <= 0.08 (n=90)
    Zona: 50 colunas
    Importance: 0.000054
  Predicado: background1 > 0.08 (n=78)
    Zona: 50 colunas
    Importance: 0.000025
  Predicado: background1 <= 0.10 (n=135)
    Zona: 50 colunas
    Importance: 0.000009
  Predicado: F2 > -0.45 (n=134)
    Zona: 50 colunas
    Importance: -0.062802
  Predicado: F2 <= -0.23 (n=66)
    Zona: 50 colunas
    Importance: 0.502637
  Predicado: F2 > -0.23 (n=102)
    Zona: 50 colunas
    Importance: -0.131211
  Predicado: F2 <= 0.17 (n=101)
    Zona: 50 colunas
    Importance: 0.276022
  Predicado: F2 > 0.17 (n=67)
    Zona: 50 colunas
    Importance: -0.120712
  Predicado: F2 <= 0.40 (n=132)
    Zona: 50 colunas
    Importance: 0.175822
  Predicado: background2 > -0.08 (n=133)
    Zona: 15 colunas
    Importance: -0.000037
  Predicado: background2 <= -0.06 (n=71)
    Zona: 15 colunas
    Importance: 0.000020
  Predicado: background2 > -0.06 (n=97)
    Zona: 15 colunas
    Importance: -0.000051
  Predicado: background2 <= 0.07 (n=108)
    Zona: 15 colunas
    Importance: 0.000011
  Predicado: background2 > 0.07 (n=60)
    Zona: 15 colunas
    Importance: -0.000079
  Predicado: background2 <= 0.08 (n=137)
    Zona: 15 colunas
    Importance: 0.000003
  Predicado: F3 > -0.43 (n=131)
    Zona: 50 colunas
    Importance: -0.015735
  Predicado: F3 <= -0.23 (n=68)
    Zona: 50 colunas
    Importance: 0.503102
  Predicado: F3 > -0.23 (n=100)
    Zona: 50 colunas
    Importance: -0.063548
  Predicado: F3 <= 0.14 (n=106)
    Zona: 50 colunas
    Importance: 0.324124
  Predicado: F3 > 0.14 (n=62)
    Zona: 50 colunas
    Importance: -0.104856
  Predicado: F3 <= 0.44 (n=133)
    Zona: 50 colunas
    Importance: 0.234520
  Predicado: background3 > -0.09 (n=128)
    Zona: 35 colunas
    Importance: 0.000077
  Predicado: background3 <= -0.08 (n=60)
    Zona: 35 colunas
    Importance: 0.000155
  Predicado: background3 > -0.08 (n=108)
    Zona: 35 colunas
    Importance: 0.000036
  Predicado: background3 <= 0.07 (n=100)
    Zona: 35 colunas
    Importance: 0.000079
  Predicado: background3 > 0.07 (n=68)
    Zona: 35 colunas
    Importance: 0.000077
  Predicado: background3 <= 0.09 (n=131)
    Zona: 35 colunas
    Importance: 0.000067
  Predicado: F4 > -0.47 (n=132)
    Zona: 50 colunas
    Importance: -0.056573
  Predicado: F4 <= -0.24 (n=70)
    Zona: 50 colunas
    Importance: 0.027330
  Predicado: F4 > -0.24 (n=98)
    Zona: 50 colunas
    Importance: -0.113129
  Predicado: F4 <= 0.18 (n=102)
    Zona: 50 colunas
    Importance: 0.052671
  Predicado: F4 > 0.18 (n=66)
    Zona: 50 colunas
    Importance: -0.220395
  Predicado: F4 <= 0.50 (n=136)
    Zona: 50 colunas
    Importance: -0.026959
  Predicado: background4 > -0.09 (n=132)
    Zona: 30 colunas
    Importance: -0.000172
  Predicado: background4 <= -0.07 (n=71)
    Zona: 30 colunas
    Importance: 0.000213
  Predicado: background4 > -0.07 (n=97)
    Zona: 30 colunas
    Importance: -0.000139
  Predicado: background4 <= 0.08 (n=108)
    Zona: 30 colunas
    Importance: 0.000059
  Predicado: background4 > 0.08 (n=60)
    Zona: 30 colunas
    Importance: -0.000079
  Predicado: background4 <= 0.09 (n=118)
    Zona: 30 colunas
    Importance: 0.000093
  Predicado: background4 > 0.09 (n=50)
    Zona: 30 colunas
    Importance: -0.000186
  Predicado: F5 > -0.54 (n=135)
    Zona: 45 colunas
    Importance: 0.118524
  Predicado: F5 <= -0.52 (n=61)
    Zona: 45 colunas
    Importance: -0.134979
  Predicado: F5 > -0.52 (n=107)
    Zona: 45 colunas
    Importance: 0.184494
  Predicado: F5 <= 0.24 (n=97)
    Zona: 45 colunas
    Importance: -0.100638
  Predicado: F5 > 0.24 (n=71)
    Zona: 45 colunas
    Importance: 0.299563
  Predicado: F5 <= 0.61 (n=135)
    Zona: 45 colunas
    Importance: 0.412847
  Predicado: background5 > -0.10 (n=141)
    Zona: 32 colunas
    Importance: 0.000060
  Predicado: background5 <= -0.08 (n=66)
    Zona: 32 colunas
    Importance: 0.000208
  Predicado: background5 > -0.08 (n=102)
    Zona: 32 colunas
    Importance: 0.000093
  Predicado: background5 <= 0.08 (n=108)
    Zona: 32 colunas
    Importance: 0.000159
  Predicado: background5 > 0.08 (n=60)
    Zona: 32 colunas
    Importance: 0.000101
  Predicado: background5 <= 0.10 (n=140)
    Zona: 32 colunas
    Importance: 0.000185
  Predicado: F6 > -0.42 (n=133)
    Zona: 38 colunas
    Importance: -0.047369
  Predicado: F6 <= -0.25 (n=68)
    Zona: 38 colunas
    Importance: 0.134253
  Predicado: F6 > -0.25 (n=100)
    Zona: 38 colunas
    Importance: -0.021104
  Predicado: F6 <= 0.13 (n=106)
    Zona: 38 colunas
    Importance: 0.122778
  Predicado: F6 > 0.13 (n=62)
    Zona: 38 colunas
    Importance: -0.096705
  Predicado: F6 <= 0.42 (n=139)
    Zona: 38 colunas
    Importance: 0.079733
  Predicado: background6 > -0.10 (n=130)
    Zona: 55 colunas
    Importance: 0.000016
  Predicado: background6 <= -0.09 (n=60)
    Zona: 55 colunas
    Importance: 0.000247
  Predicado: background6 > -0.09 (n=108)
    Zona: 55 colunas
    Importance: 0.000070
  Predicado: background6 <= 0.08 (n=92)
    Zona: 55 colunas
    Importance: 0.000159
  Predicado: background6 > 0.08 (n=76)
    Zona: 55 colunas
    Importance: 0.000101
  Predicado: background6 <= 0.10 (n=127)
    Zona: 55 colunas
    Importance: 0.000134

[Bag_2] Processando 74 predicados...
  Predicado: F1 > -0.71 (n=133)
    Zona: 50 colunas
    Importance: 0.293081
  Predicado: F1 <= -0.69 (n=61)
    Zona: 50 colunas
    Importance: 0.862117
  Predicado: F1 > -0.69 (n=107)
    Zona: 50 colunas
    Importance: 0.174374
  Predicado: F1 <= 0.22 (n=101)
    Zona: 50 colunas
    Importance: 0.895865
  Predicado: F1 > 0.22 (n=67)
    Zona: 50 colunas
    Importance: -0.287092
  Predicado: F1 <= 0.83 (n=137)
    Zona: 50 colunas
    Importance: 0.606013
  Predicado: background1 > -0.10 (n=142)
    Zona: 50 colunas
    Importance: 0.000027
  Predicado: background1 <= -0.08 (n=59)
    Zona: 50 colunas
    Importance: -0.000020
  Predicado: background1 > -0.08 (n=109)
    Zona: 50 colunas
    Importance: 0.000013
  Predicado: background1 <= 0.08 (n=89)
    Zona: 50 colunas
    Importance: -0.000014
  Predicado: background1 > 0.08 (n=79)
    Zona: 50 colunas
    Importance: 0.000020
  Predicado: background1 <= 0.10 (n=133)
    Zona: 50 colunas
    Importance: -0.000042
  Predicado: F2 > -0.45 (n=132)
    Zona: 50 colunas
    Importance: -0.090101
  Predicado: F2 <= -0.23 (n=69)
    Zona: 50 colunas
    Importance: 0.172021
  Predicado: F2 > -0.23 (n=99)
    Zona: 50 colunas
    Importance: -0.053447
  Predicado: F2 <= 0.17 (n=99)
    Zona: 50 colunas
    Importance: 0.130216
  Predicado: F2 > 0.17 (n=69)
    Zona: 50 colunas
    Importance: -0.091496
  Predicado: F2 <= 0.40 (n=129)
    Zona: 50 colunas
    Importance: 0.081294
  Predicado: background2 > -0.08 (n=135)
    Zona: 15 colunas
    Importance: -0.000030
  Predicado: background2 <= -0.06 (n=73)
    Zona: 15 colunas
    Importance: 0.000023
  Predicado: background2 > -0.06 (n=95)
    Zona: 15 colunas
    Importance: -0.000039
  Predicado: background2 <= 0.07 (n=111)
    Zona: 15 colunas
    Importance: 0.000013
  Predicado: background2 > 0.07 (n=57)
    Zona: 15 colunas
    Importance: -0.000060
  Predicado: background2 <= 0.08 (n=139)
    Zona: 15 colunas
    Importance: 0.000000
  Predicado: F3 > -0.43 (n=136)
    Zona: 50 colunas
    Importance: 0.021295
  Predicado: F3 <= -0.23 (n=64)
    Zona: 50 colunas
    Importance: 0.301131
  Predicado: F3 > -0.23 (n=104)
    Zona: 50 colunas
    Importance: 0.009790
  Predicado: F3 <= 0.14 (n=101)
    Zona: 50 colunas
    Importance: 0.217235
  Predicado: F3 > 0.14 (n=67)
    Zona: 50 colunas
    Importance: -0.024629
  Predicado: F3 <= 0.44 (n=135)
    Zona: 50 colunas
    Importance: 0.174724
  Predicado: background3 > -0.09 (n=129)
    Zona: 35 colunas
    Importance: 0.000036
  Predicado: background3 <= -0.08 (n=57)
    Zona: 35 colunas
    Importance: 0.000137
  Predicado: background3 > -0.08 (n=111)
    Zona: 35 colunas
    Importance: -0.000001
  Predicado: background3 <= 0.07 (n=100)
    Zona: 35 colunas
    Importance: 0.000056
  Predicado: background3 > 0.07 (n=68)
    Zona: 35 colunas
    Importance: 0.000030
  Predicado: background3 <= 0.09 (n=134)
    Zona: 35 colunas
    Importance: 0.000060
  Predicado: F4 > -0.47 (n=135)
    Zona: 50 colunas
    Importance: -0.067004
  Predicado: F4 <= -0.24 (n=62)
    Zona: 50 colunas
    Importance: -0.235013
  Predicado: F4 > -0.24 (n=106)
    Zona: 50 colunas
    Importance: -0.114835
  Predicado: F4 <= 0.18 (n=100)
    Zona: 50 colunas
    Importance: -0.121605
  Predicado: F4 > 0.18 (n=68)
    Zona: 50 colunas
    Importance: -0.214452
  Predicado: F4 <= 0.50 (n=133)
    Zona: 50 colunas
    Importance: -0.158435
  Predicado: background4 > -0.09 (n=131)
    Zona: 30 colunas
    Importance: -0.000133
  Predicado: background4 <= -0.07 (n=68)
    Zona: 30 colunas
    Importance: -0.000124
  Predicado: background4 > -0.07 (n=100)
    Zona: 30 colunas
    Importance: -0.000067
  Predicado: background4 <= 0.08 (n=105)
    Zona: 30 colunas
    Importance: -0.000188
  Predicado: background4 > 0.08 (n=63)
    Zona: 30 colunas
    Importance: 0.000073
  Predicado: background4 <= 0.09 (n=116)
    Zona: 30 colunas
    Importance: -0.000122
  Predicado: background4 > 0.09 (n=52)
    Zona: 30 colunas
    Importance: -0.000019
  Predicado: F5 > -0.54 (n=137)
    Zona: 45 colunas
    Importance: 0.024362
  Predicado: F5 <= -0.52 (n=61)
    Zona: 45 colunas
    Importance: -0.136118
  Predicado: F5 > -0.52 (n=107)
    Zona: 45 colunas
    Importance: 0.068264
  Predicado: F5 <= 0.24 (n=98)
    Zona: 45 colunas
    Importance: -0.085044
  Predicado: F5 > 0.24 (n=70)
    Zona: 45 colunas
    Importance: 0.104789
  Predicado: F5 <= 0.61 (n=134)
    Zona: 45 colunas
    Importance: 0.074976
  Predicado: background5 > -0.10 (n=142)
    Zona: 32 colunas
    Importance: -0.000024
  Predicado: background5 <= -0.08 (n=63)
    Zona: 32 colunas
    Importance: 0.000078
  Predicado: background5 > -0.08 (n=105)
    Zona: 32 colunas
    Importance: 0.000049
  Predicado: background5 <= 0.08 (n=103)
    Zona: 32 colunas
    Importance: 0.000031
  Predicado: background5 > 0.08 (n=65)
    Zona: 32 colunas
    Importance: 0.000106
  Predicado: background5 <= 0.10 (n=138)
    Zona: 32 colunas
    Importance: 0.000090
  Predicado: F6 > -0.42 (n=132)
    Zona: 38 colunas
    Importance: -0.031107
  Predicado: F6 <= -0.25 (n=65)
    Zona: 38 colunas
    Importance: -0.006815
  Predicado: F6 > -0.25 (n=103)
    Zona: 38 colunas
    Importance: -0.044274
  Predicado: F6 <= 0.13 (n=100)
    Zona: 38 colunas
    Importance: 0.011850
  Predicado: F6 > 0.13 (n=68)
    Zona: 38 colunas
    Importance: -0.091002
  Predicado: F6 <= 0.42 (n=133)
    Zona: 38 colunas
    Importance: -0.005520
  Predicado: background6 > -0.10 (n=130)
    Zona: 55 colunas
    Importance: -0.000047
  Predicado: background6 <= -0.09 (n=64)
    Zona: 55 colunas
    Importance: 0.000022
  Predicado: background6 > -0.09 (n=104)
    Zona: 55 colunas
    Importance: -0.000041
  Predicado: background6 <= 0.08 (n=95)
    Zona: 55 colunas
    Importance: 0.000013
  Predicado: background6 > 0.08 (n=73)
    Zona: 55 colunas
    Importance: -0.000056
  Predicado: background6 <= 0.10 (n=126)
    Zona: 55 colunas
    Importance: 0.000013
  Predicado: background6 > 0.10 (n=42)
    Zona: 55 colunas
    Importance: -0.000107

[Bag_3] Processando 74 predicados...
  Predicado: F1 > -0.71 (n=128)
    Zona: 50 colunas
    Importance: 0.385129
  Predicado: F1 <= -0.69 (n=65)
    Zona: 50 colunas
    Importance: 0.670815
  Predicado: F1 > -0.69 (n=103)
    Zona: 50 colunas
    Importance: 0.213894
  Predicado: F1 <= 0.22 (n=103)
    Zona: 50 colunas
    Importance: 0.821920
  Predicado: F1 > 0.22 (n=65)
    Zona: 50 colunas
    Importance: -0.292673
  Predicado: F1 <= 0.83 (n=135)
    Zona: 50 colunas
    Importance: 0.578919
  Predicado: background1 > -0.10 (n=139)
    Zona: 50 colunas
    Importance: 0.000077
  Predicado: background1 <= -0.08 (n=63)
    Zona: 50 colunas
    Importance: 0.000052
  Predicado: background1 > -0.08 (n=105)
    Zona: 50 colunas
    Importance: 0.000047
  Predicado: background1 <= 0.08 (n=91)
    Zona: 50 colunas
    Importance: 0.000061
  Predicado: background1 > 0.08 (n=77)
    Zona: 50 colunas
    Importance: 0.000035
  Predicado: background1 <= 0.10 (n=135)
    Zona: 50 colunas
    Importance: 0.000026
  Predicado: F2 > -0.45 (n=136)
    Zona: 50 colunas
    Importance: -0.059622
  Predicado: F2 <= -0.23 (n=67)
    Zona: 50 colunas
    Importance: 0.304059
  Predicado: F2 > -0.23 (n=101)
    Zona: 50 colunas
    Importance: -0.108183
  Predicado: F2 <= 0.17 (n=104)
    Zona: 50 colunas
    Importance: 0.148951
  Predicado: F2 > 0.17 (n=64)
    Zona: 50 colunas
    Importance: -0.094460
  Predicado: F2 <= 0.40 (n=136)
    Zona: 50 colunas
    Importance: 0.092952
  Predicado: background2 > -0.08 (n=134)
    Zona: 15 colunas
    Importance: -0.000021
  Predicado: background2 <= -0.06 (n=74)
    Zona: 15 colunas
    Importance: -0.000025
  Predicado: background2 > -0.06 (n=94)
    Zona: 15 colunas
    Importance: -0.000034
  Predicado: background2 <= 0.07 (n=111)
    Zona: 15 colunas
    Importance: -0.000018
  Predicado: background2 > 0.07 (n=57)
    Zona: 15 colunas
    Importance: -0.000053
  Predicado: background2 <= 0.08 (n=138)
    Zona: 15 colunas
    Importance: -0.000014
  Predicado: F3 > -0.43 (n=136)
    Zona: 50 colunas
    Importance: -0.029182
  Predicado: F3 <= -0.23 (n=65)
    Zona: 50 colunas
    Importance: 0.211518
  Predicado: F3 > -0.23 (n=103)
    Zona: 50 colunas
    Importance: -0.074401
  Predicado: F3 <= 0.14 (n=103)
    Zona: 50 colunas
    Importance: 0.129255
  Predicado: F3 > 0.14 (n=65)
    Zona: 50 colunas
    Importance: -0.111198
  Predicado: F3 <= 0.44 (n=135)
    Zona: 50 colunas
    Importance: 0.069664
  Predicado: background3 <= -0.09 (n=42)
    Zona: 35 colunas
    Importance: 0.000163
  Predicado: background3 > -0.09 (n=126)
    Zona: 35 colunas
    Importance: 0.000037
  Predicado: background3 <= -0.08 (n=62)
    Zona: 35 colunas
    Importance: 0.000131
  Predicado: background3 > -0.08 (n=106)
    Zona: 35 colunas
    Importance: 0.000032
  Predicado: background3 <= 0.07 (n=96)
    Zona: 35 colunas
    Importance: 0.000074
  Predicado: background3 > 0.07 (n=72)
    Zona: 35 colunas
    Importance: 0.000061
  Predicado: background3 <= 0.09 (n=132)
    Zona: 35 colunas
    Importance: 0.000064
  Predicado: F4 > -0.47 (n=132)
    Zona: 50 colunas
    Importance: -0.092165
  Predicado: F4 <= -0.24 (n=72)
    Zona: 50 colunas
    Importance: 0.011441
  Predicado: F4 > -0.24 (n=96)
    Zona: 50 colunas
    Importance: -0.112674
  Predicado: F4 <= 0.18 (n=108)
    Zona: 50 colunas
    Importance: 0.024932
  Predicado: F4 > 0.18 (n=60)
    Zona: 50 colunas
    Importance: -0.211427
  Predicado: F4 <= 0.50 (n=139)
    Zona: 50 colunas
    Importance: -0.039828
  Predicado: background4 > -0.09 (n=131)
    Zona: 30 colunas
    Importance: -0.000112
  Predicado: background4 <= -0.07 (n=70)
    Zona: 30 colunas
    Importance: 0.000068
  Predicado: background4 > -0.07 (n=98)
    Zona: 30 colunas
    Importance: -0.000037
  Predicado: background4 <= 0.08 (n=106)
    Zona: 30 colunas
    Importance: -0.000042
  Predicado: background4 > 0.08 (n=62)
    Zona: 30 colunas
    Importance: 0.000090
  Predicado: background4 <= 0.09 (n=118)
    Zona: 30 colunas
    Importance: 0.000004
  Predicado: background4 > 0.09 (n=50)
    Zona: 30 colunas
    Importance: 0.000013
  Predicado: F5 > -0.54 (n=140)
    Zona: 45 colunas
    Importance: -0.054941
  Predicado: F5 <= -0.52 (n=61)
    Zona: 45 colunas
    Importance: -0.135389
  Predicado: F5 > -0.52 (n=107)
    Zona: 45 colunas
    Importance: -0.031042
  Predicado: F5 <= 0.24 (n=95)
    Zona: 45 colunas
    Importance: -0.118202
  Predicado: F5 > 0.24 (n=73)
    Zona: 45 colunas
    Importance: -0.004810
  Predicado: F5 <= 0.61 (n=133)
    Zona: 45 colunas
    Importance: 0.396418
  Predicado: background5 > -0.10 (n=140)
    Zona: 32 colunas
    Importance: 0.000004
  Predicado: background5 <= -0.08 (n=70)
    Zona: 32 colunas
    Importance: -0.000118
  Predicado: background5 > -0.08 (n=98)
    Zona: 32 colunas
    Importance: 0.000073
  Predicado: background5 <= 0.08 (n=106)
    Zona: 32 colunas
    Importance: -0.000059
  Predicado: background5 > 0.08 (n=62)
    Zona: 32 colunas
    Importance: 0.000083
  Predicado: background5 <= 0.10 (n=137)
    Zona: 32 colunas
    Importance: 0.000006
  Predicado: F6 > -0.42 (n=131)
    Zona: 38 colunas
    Importance: -0.066032
  Predicado: F6 <= -0.25 (n=63)
    Zona: 38 colunas
    Importance: -0.072582
  Predicado: F6 > -0.25 (n=105)
    Zona: 38 colunas
    Importance: -0.017453
  Predicado: F6 <= 0.13 (n=103)
    Zona: 38 colunas
    Importance: -0.005142
  Predicado: F6 > 0.13 (n=65)
    Zona: 38 colunas
    Importance: -0.090395
  Predicado: F6 <= 0.42 (n=137)
    Zona: 38 colunas
    Importance: -0.026343
  Predicado: background6 > -0.10 (n=129)
    Zona: 55 colunas
    Importance: -0.000064
  Predicado: background6 <= -0.09 (n=65)
    Zona: 55 colunas
    Importance: 0.000208
  Predicado: background6 > -0.09 (n=103)
    Zona: 55 colunas
    Importance: -0.000034
  Predicado: background6 <= 0.08 (n=98)
    Zona: 55 colunas
    Importance: 0.000130
  Predicado: background6 > 0.08 (n=70)
    Zona: 55 colunas
    Importance: -0.000038
  Predicado: background6 <= 0.10 (n=128)
    Zona: 55 colunas
    Importance: 0.000103

[Bag_4] Processando 75 predicados...
  Predicado: F1 > -0.71 (n=129)
    Zona: 50 colunas
    Importance: 0.807971
  Predicado: F1 <= -0.69 (n=68)
    Zona: 50 colunas
    Importance: 1.888922
  Predicado: F1 > -0.69 (n=100)
    Zona: 50 colunas
    Importance: 0.413406
  Predicado: F1 <= 0.22 (n=104)
    Zona: 50 colunas
    Importance: 1.815418
  Predicado: F1 > 0.22 (n=64)
    Zona: 50 colunas

    Importance: -0.574907
  Predicado: F5 <= 0.61 (n=135)
    Zona: 45 colunas
    Importance: 0.133337
  Predicado: background5 > -0.10 (n=139)
    Zona: 32 colunas
    Importance: 0.000021
  Predicado: background5 <= -0.08 (n=68)
    Zona: 32 colunas
    Importance: 0.000219
  Predicado: background5 > -0.08 (n=100)
    Zona: 32 colunas
    Importance: 0.000012
  Predicado: background5 <= 0.08 (n=109)
    Zona: 32 colunas
    Importance: 0.000157
  Predicado: background5 > 0.08 (n=59)
    Zona: 32 colunas
    Importance: -0.000018
  Predicado: background5 <= 0.10 (n=138)
    Zona: 32 colunas
    Importance: 0.000126
  Predicado: F6 > -0.42 (n=134)
    Zona: 38 colunas
    Importance: -0.103117
  Predicado: F6 <= -0.25 (n=62)
    Zona: 38 colunas
    Importance: -0.105934
  Predicado: F6 > -0.25 (n=106)
    Zona: 38 colunas
    Importance: -0.031617
  Predicado: F6 <= 0.13 (n=94)
    Zona: 38 colunas
    Importance: -0.031976
  Predicado: F6 > 0.13 (n=74)
    Zona: 38 colunas
    Importance: -0.093426
  Predicado: F6 <= 0.42 (n=132)
    Zona: 38 colunas
    Importance: -0.053485
  Predicado: background6 > -0.10 (n=128)
    Zona: 55 colunas
    Importance: -0.000074
  Predicado: background6 <= -0.09 (n=63)
    Zona: 55 colunas
    Importance: 0.000130
  Predicado: background6 > -0.09 (n=105)
    Zona: 55 colunas
    Importance: -0.000049
  Predicado: background6 <= 0.08 (n=94)
    Zona: 55 colunas
    Importance: 0.000095
  Predicado: background6 > 0.08 (n=74)
    Zona: 55 colunas
    Importance: -0.000080
  Predicado: background6 <= 0.10 (n=129)
    Zona: 55 colunas
    Importance: 0.000081

[Bag_6] Processando 74 predicados...
  Predicado: F1 > -0.71 (n=133)
    Zona: 50 colunas
    Importance: 0.364040
  Predicado: F1 <= -0.69 (n=59)
    Zona: 50 colunas
    Importance: 0.910497
  Predicado: F1 > -0.69 (n=109)
    Zona: 50 colunas
    Importance: 0.523530
  Predicado: F1 <= 0.22 (n=93)
    Zona: 50 colunas
    Importance: 1.427153
  Predicado: F1 > 0.22 (n=75)
    Zona: 50 colunas
    Importance: -0.292549
  Predicado: F1 <= 0.83 (n=130)
    Zona: 50 colunas
    Importance: 0.962193
  Predicado: background1 > -0.10 (n=138)
    Zona: 50 colunas
    Importance: 0.000055
  Predicado: background1 <= -0.08 (n=66)
    Zona: 50 colunas
    Importance: 0.000059
  Predicado: background1 > -0.08 (n=102)
    Zona: 50 colunas
    Importance: 0.000029
  Predicado: background1 <= 0.08 (n=95)
    Zona: 50 colunas
    Importance: 0.000069
  Predicado: background1 > 0.08 (n=73)
    Zona: 50 colunas
    Importance: 0.000003
  Predicado: background1 <= 0.10 (n=135)
    Zona: 50 colunas
    Importance: 0.000025
  Predicado: F2 > -0.45 (n=133)
    Zona: 50 colunas
    Importance: -0.042538
  Predicado: F2 <= -0.23 (n=61)
    Zona: 50 colunas
    Importance: 0.550639
  Predicado: F2 > -0.23 (n=107)
    Zona: 50 colunas
    Importance: -0.123552
  Predicado: F2 <= 0.17 (n=95)
    Zona: 50 colunas
    Importance: 0.298074
  Predicado: F2 > 0.17 (n=73)
    Zona: 50 colunas
    Importance: -0.108879
  Predicado: F2 <= 0.40 (n=130)
    Zona: 50 colunas
    Importance: 0.180247
  Predicado: background2 > -0.08 (n=133)
    Zona: 15 colunas
    Importance: -0.000018
  Predicado: background2 <= -0.06 (n=72)
    Zona: 15 colunas
    Importance: 0.000015
  Predicado: background2 > -0.06 (n=96)
    Zona: 15 colunas
    Importance: -0.000026
  Predicado: background2 <= 0.07 (n=106)
    Zona: 15 colunas
    Importance: 0.000016
  Predicado: background2 > 0.07 (n=62)
    Zona: 15 colunas
    Importance: -0.000051
  Predicado: background2 <= 0.08 (n=135)
    Zona: 15 colunas
    Importance: 0.000017
  Predicado: F3 > -0.43 (n=133)
    Zona: 50 colunas
    Importance: 0.000699
  Predicado: F3 <= -0.23 (n=62)
    Zona: 50 colunas
    Importance: 0.599958
  Predicado: F3 > -0.23 (n=106)
    Zona: 50 colunas
    Importance: -0.030247
  Predicado: F3 <= 0.14 (n=101)
    Zona: 50 colunas
    Importance: 0.353857
  Predicado: F3 > 0.14 (n=67)
    Zona: 50 colunas
    Importance: -0.026095
  Predicado: F3 <= 0.44 (n=136)
    Zona: 50 colunas
    Importance: 0.278064
  Predicado: background3 <= -0.09 (n=42)
    Zona: 35 colunas
    Importance: 0.000109
  Predicado: background3 > -0.09 (n=126)
    Zona: 35 colunas
    Importance: 0.000044
  Predicado: background3 <= -0.08 (n=61)
    Zona: 35 colunas
    Importance: 0.000148
  Predicado: background3 > -0.08 (n=107)
    Zona: 35 colunas
    Importance: 0.000011
  Predicado: background3 <= 0.07 (n=103)
    Zona: 35 colunas
    Importance: 0.000064
  Predicado: background3 > 0.07 (n=65)
    Zona: 35 colunas
    Importance: 0.000055
  Predicado: background3 <= 0.09 (n=130)
    Zona: 35 colunas
    Importance: 0.000061
  Predicado: F4 > -0.47 (n=137)
    Zona: 50 colunas
    Importance: -0.056304
  Predicado: F4 <= -0.24 (n=67)
    Zona: 50 colunas
    Importance: -0.106479
  Predicado: F4 > -0.24 (n=101)
    Zona: 50 colunas
    Importance: -0.110433
  Predicado: F4 <= 0.18 (n=99)
    Zona: 50 colunas
    Importance: -0.044134
  Predicado: F4 > 0.18 (n=69)
    Zona: 50 colunas
    Importance: -0.201718
  Predicado: F4 <= 0.50 (n=135)
    Zona: 50 colunas
    Importance: -0.098403
  Predicado: background4 > -0.09 (n=129)
    Zona: 30 colunas
    Importance: -0.000012
  Predicado: background4 <= -0.07 (n=77)
    Zona: 30 colunas
    Importance: 0.000166
  Predicado: background4 > -0.07 (n=91)
    Zona: 30 colunas
    Importance: 0.000089
  Predicado: background4 <= 0.08 (n=117)
    Zona: 30 colunas
    Importance: 0.000130
  Predicado: background4 > 0.08 (n=51)
    Zona: 30 colunas
    Importance: 0.000111
  Predicado: background4 <= 0.09 (n=130)
    Zona: 30 colunas
    Importance: 0.000153
  Predicado: F5 > -0.54 (n=133)
    Zona: 45 colunas
    Importance: 0.111133
  Predicado: F5 <= -0.52 (n=66)
    Zona: 45 colunas
    Importance: -0.131968
  Predicado: F5 > -0.52 (n=102)
    Zona: 45 colunas
    Importance: 0.183937
  Predicado: F5 <= 0.24 (n=101)
    Zona: 45 colunas
    Importance: -0.091717
  Predicado: F5 > 0.24 (n=67)
    Zona: 45 colunas
    Importance: 0.288285
  Predicado: F5 <= 0.61 (n=135)
    Zona: 45 colunas
    Importance: 0.390510
  Predicado: background5 > -0.10 (n=139)
    Zona: 32 colunas
    Importance: -0.000001
  Predicado: background5 <= -0.08 (n=70)
    Zona: 32 colunas
    Importance: 0.000121
  Predicado: background5 > -0.08 (n=98)
    Zona: 32 colunas
    Importance: 0.000065
  Predicado: background5 <= 0.08 (n=112)
    Zona: 32 colunas
    Importance: 0.000108
  Predicado: background5 > 0.08 (n=56)
    Zona: 32 colunas
    Importance: 0.000048
  Predicado: background5 <= 0.10 (n=143)
    Zona: 32 colunas
    Importance: 0.000123
  Predicado: F6 > -0.42 (n=136)
    Zona: 38 colunas
    Importance: -0.032296
  Predicado: F6 <= -0.25 (n=64)
    Zona: 38 colunas
    Importance: 0.060528
  Predicado: F6 > -0.25 (n=104)
    Zona: 38 colunas
    Importance: -0.031549
  Predicado: F6 <= 0.13 (n=100)
    Zona: 38 colunas
    Importance: 0.075846
  Predicado: F6 > 0.13 (n=68)
    Zona: 38 colunas
    Importance: -0.102822
  Predicado: F6 <= 0.42 (n=133)
    Zona: 38 colunas
    Importance: 0.036693
  Predicado: background6 <= -0.10 (n=42)
    Zona: 55 colunas
    Importance: 0.000474
  Predicado: background6 > -0.10 (n=126)
    Zona: 55 colunas
    Importance: -0.000089
  Predicado: background6 <= -0.09 (n=62)
    Zona: 55 colunas
    Importance: 0.000256
  Predicado: background6 > -0.09 (n=106)
    Zona: 55 colunas
    Importance: -0.000068
  Predicado: background6 <= 0.08 (n=96)
    Zona: 55 colunas
    Importance: 0.000165
  Predicado: background6 > 0.08 (n=72)
    Zona: 55 colunas
    Importance: -0.000099
  Predicado: background6 <= 0.10 (n=130)
    Zona: 55 colunas
    Importance: 0.000124

[Bag_7] Processando 73 predicados...
  Predicado: F1 > -0.71 (n=132)
    Zona: 50 colunas
    Importance: 0.381485
  Predicado: F1 <= -0.69 (n=66)
    Zona: 50 colunas
    Importance: -0.089439
  Predicado: F1 > -0.69 (n=102)
    Zona: 50 colunas
    Importance: 0.537857
  Predicado: F1 <= 0.22 (n=103)
    Zona: 50 colunas
    Importance: 0.657059
  Predicado: F1 > 0.22 (n=65)
    Zona: 50 colunas
    Importance: -0.287979
  Predicado: F1 <= 0.83 (n=135)
    Zona: 50 colunas
    Importance: 0.453495
  Predicado: background1 > -0.10 (n=141)
    Zona: 50 colunas
    Importance: 0.000073
  Predicado: background1 <= -0.08 (n=60)
    Zona: 50 colunas
    Importance: 0.000102
  Predicado: background1 > -0.08 (n=108)
    Zona: 50 colunas
    Importance: 0.000032
  Predicado: background1 <= 0.08 (n=88)
    Zona: 50 colunas
    Importance: 0.000073
  Predicado: background1 > 0.08 (n=80)
    Zona: 50 colunas
    Importance: 0.000039
  Predicado: background1 <= 0.10 (n=131)
    Zona: 50 colunas
    Importance: 0.000047
  Predicado: F2 > -0.45 (n=136)
    Zona: 50 colunas
    Importance: -0.026025
  Predicado: F2 <= -0.23 (n=67)
    Zona: 50 colunas
    Importance: 0.204035
  Predicado: F2 > -0.23 (n=101)
    Zona: 50 colunas
    Importance: -0.119300
  Predicado: F2 <= 0.17 (n=102)
    Zona: 50 colunas
    Importance: 0.085472
  Predicado: F2 > 0.17 (n=66)
    Zona: 50 colunas
    Importance: -0.107532
  Predicado: F2 <= 0.40 (n=135)
    Zona: 50 colunas
    Importance: 0.032445
  Predicado: background2 > -0.08 (n=133)
    Zona: 15 colunas
    Importance: -0.000026
  Predicado: background2 <= -0.06 (n=70)
    Zona: 15 colunas
    Importance: 0.000012
  Predicado: background2 > -0.06 (n=98)
    Zona: 15 colunas
    Importance: -0.000047
  Predicado: background2 <= 0.07 (n=105)
    Zona: 15 colunas
    Importance: 0.000005
  Predicado: background2 > 0.07 (n=63)
    Zona: 15 colunas
    Importance: -0.000068
  Predicado: background2 <= 0.08 (n=132)
    Zona: 15 colunas
    Importance: -0.000005
  Predicado: F3 > -0.43 (n=136)
    Zona: 50 colunas
    Importance: -0.003698
  Predicado: F3 <= -0.23 (n=64)
    Zona: 50 colunas
    Importance: 0.273325
  Predicado: F3 > -0.23 (n=104)
    Zona: 50 colunas
    Importance: -0.038697
  Predicado: F3 <= 0.14 (n=98)
    Zona: 50 colunas
    Importance: 0.157863
  Predicado: F3 > 0.14 (n=70)
    Zona: 50 colunas
    Importance: -0.028603
  Predicado: F3 <= 0.44 (n=132)
    Zona: 50 colunas
    Importance: 0.129430
  Predicado: background3 > -0.09 (n=130)
    Zona: 35 colunas
    Importance: 0.000005
  Predicado: background3 <= -0.08 (n=56)
    Zona: 35 colunas
    Importance: 0.000098
  Predicado: background3 > -0.08 (n=112)
    Zona: 35 colunas
    Importance: -0.000002
  Predicado: background3 <= 0.07 (n=97)
    Zona: 35 colunas
    Importance: 0.000034
  Predicado: background3 > 0.07 (n=71)
    Zona: 35 colunas
    Importance: 0.000029
  Predicado: background3 <= 0.09 (n=132)
    Zona: 35 colunas
    Importance: 0.000027
  Predicado: F4 > -0.47 (n=135)
    Zona: 50 colunas
    Importance: -0.104640
  Predicado: F4 <= -0.24 (n=67)
    Zona: 50 colunas
    Importance: -0.127261
  Predicado: F4 > -0.24 (n=101)
    Zona: 50 colunas
    Importance: -0.132407
  Predicado: F4 <= 0.18 (n=102)
    Zona: 50 colunas
    Importance: -0.069154
  Predicado: F4 > 0.18 (n=66)
    Zona: 50 colunas
    Importance: -0.224938
  Predicado: F4 <= 0.50 (n=136)
    Zona: 50 colunas
    Importance: -0.120152
  Predicado: background4 > -0.09 (n=134)
    Zona: 30 colunas
    Importance: -0.000085
  Predicado: background4 <= -0.07 (n=70)
    Zona: 30 colunas
    Importance: 0.000176
  Predicado: background4 > -0.07 (n=98)
    Zona: 30 colunas
    Importance: -0.000016
  Predicado: background4 <= 0.08 (n=107)
    Zona: 30 colunas
    Importance: 0.000119
  Predicado: background4 > 0.08 (n=61)
    Zona: 30 colunas
    Importance: -0.000032
  Predicado: background4 <= 0.09 (n=119)
    Zona: 30 colunas
    Importance: 0.000132
  Predicado: background4 > 0.09 (n=49)
    Zona: 30 colunas
    Importance: -0.000101
  Predicado: F5 > -0.54 (n=138)
    Zona: 45 colunas
    Importance: -0.072958
  Predicado: F5 <= -0.52 (n=59)
    Zona: 45 colunas
    Importance: -0.134406
  Predicado: F5 > -0.52 (n=109)
    Zona: 45 colunas
    Importance: -0.056346
  Predicado: F5 <= 0.24 (n=96)
    Zona: 45 colunas
    Importance: -0.108780
  Predicado: F5 > 0.24 (n=72)
    Zona: 45 colunas
    Importance: -0.050400
  Predicado: F5 <= 0.61 (n=130)
    Zona: 45 colunas
    Importance: 0.356435
  Predicado: background5 > -0.10 (n=140)
    Zona: 32 colunas
    Importance: 0.000021
  Predicado: background5 <= -0.08 (n=69)
    Zona: 32 colunas
    Importance: -0.000091
  Predicado: background5 > -0.08 (n=99)
    Zona: 32 colunas
    Importance: 0.000093
  Predicado: background5 <= 0.08 (n=109)
    Zona: 32 colunas
    Importance: -0.000030
  Predicado: background5 > 0.08 (n=59)
    Zona: 32 colunas
    Importance: 0.000106
  Predicado: background5 <= 0.10 (n=143)
    Zona: 32 colunas
    Importance: 0.000034
  Predicado: F6 > -0.42 (n=130)
    Zona: 38 colunas
    Importance: -0.039732
  Predicado: F6 <= -0.25 (n=72)
    Zona: 38 colunas
    Importance: -0.103239
  Predicado: F6 > -0.25 (n=96)
    Zona: 38 colunas
    Importance: -0.027995
  Predicado: F6 <= 0.13 (n=106)
    Zona: 38 colunas
    Importance: -0.034936
  Predicado: F6 > 0.13 (n=62)
    Zona: 38 colunas
    Importance: -0.103508
  Predicado: F6 <= 0.42 (n=138)
    Zona: 38 colunas
    Importance: -0.045255
  Predicado: background6 > -0.10 (n=129)
    Zona: 55 colunas
    Importance: -0.000085
  Predicado: background6 <= -0.09 (n=66)
    Zona: 55 colunas
    Importance: 0.000223
  Predicado: background6 > -0.09 (n=102)
    Zona: 55 colunas
    Importance: -0.000063
  Predicado: background6 <= 0.08 (n=97)
    Zona: 55 colunas
    Importance: 0.000156
  Predicado: background6 > 0.08 (n=71)
    Zona: 55 colunas
    Importance: -0.000096
  Predicado: background6 <= 0.10 (n=127)
    Zona: 55 colunas
    Importance: 0.000110

[Bag_8] Processando 73 predicados...
  Predicado: F1 > -0.71 (n=133)
    Zona: 50 colunas
    Importance: 0.893513
  Predicado: F1 <= -0.69 (n=61)
    Zona: 50 colunas
    Importance: 2.349015
  Predicado: F1 > -0.69 (n=107)
    Zona: 50 colunas
    Importance: 0.179011
  Predicado: F1 <= 0.22 (n=101)
    Zona: 50 colunas
    Importance: 1.800792
  Predicado: F1 > 0.22 (n=67)
    Zona: 50 colunas
    Importance: -0.290088
  Predicado: F1 <= 0.83 (n=134)
    Zona: 50 colunas
    Importance: 1.306351
  Predicado: background1 > -0.10 (n=138)
    Zona: 50 colunas
    Importance: 0.000004
  Predicado: background1 <= -0.08 (n=69)
    Zona: 50 colunas
    Importance: -0.000015
  Predicado: background1 > -0.08 (n=99)
    Zona: 50 colunas
    Importance: -0.000017
  Predicado: background1 <= 0.08 (n=100)
    Zona: 50 colunas
    Importance: 0.000012
  Predicado: background1 > 0.08 (n=68)
    Zona: 50 colunas
    Importance: -0.000058
  Predicado: background1 <= 0.10 (n=137)
    Zona: 50 colunas
    Importance: -0.000027
  Predicado: F2 > -0.45 (n=139)
    Zona: 50 colunas
    Importance: -0.026771
  Predicado: F2 <= -0.23 (n=62)
    Zona: 50 colunas
    Importance: 0.484620
  Predicado: F2 > -0.23 (n=106)
    Zona: 50 colunas
    Importance: -0.060815
  Predicado: F2 <= 0.17 (n=98)
    Zona: 50 colunas
    Importance: 0.315965
  Predicado: F2 > 0.17 (n=70)
    Zona: 50 colunas
    Importance: -0.105207
  Predicado: F2 <= 0.40 (n=129)
    Zona: 50 colunas
    Importance: 0.213108
  Predicado: background2 > -0.08 (n=136)
    Zona: 15 colunas
    Importance: -0.000005
  Predicado: background2 <= -0.06 (n=71)
    Zona: 15 colunas
    Importance: 0.000029
  Predicado: background2 > -0.06 (n=97)
    Zona: 15 colunas
    Importance: -0.000009
  Predicado: background2 <= 0.07 (n=107)
    Zona: 15 colunas
    Importance: 0.000018
  Predicado: background2 > 0.07 (n=61)
    Zona: 15 colunas
    Importance: -0.000012
  Predicado: background2 <= 0.08 (n=137)
    Zona: 15 colunas
    Importance: 0.000019
  Predicado: F3 > -0.43 (n=132)
    Zona: 50 colunas
    Importance: -0.020658
  Predicado: F3 <= -0.23 (n=68)
    Zona: 50 colunas
    Importance: 0.461506
  Predicado: F3 > -0.23 (n=100)
    Zona: 50 colunas
    Importance: -0.057596
  Predicado: F3 <= 0.14 (n=100)
    Zona: 50 colunas
    Importance: 0.331174
  Predicado: F3 > 0.14 (n=68)
    Zona: 50 colunas
    Importance: -0.110215
  Predicado: F3 <= 0.44 (n=135)
    Zona: 50 colunas
    Importance: 0.221318
  Predicado: background3 > -0.09 (n=127)
    Zona: 35 colunas
    Importance: 0.000057
  Predicado: background3 <= -0.08 (n=62)
    Zona: 35 colunas
    Importance: 0.000149
  Predicado: background3 > -0.08 (n=106)
    Zona: 35 colunas
    Importance: 0.000027
  Predicado: background3 <= 0.07 (n=103)
    Zona: 35 colunas
    Importance: 0.000074
  Predicado: background3 > 0.07 (n=65)
    Zona: 35 colunas
    Importance: 0.000068
  Predicado: background3 <= 0.09 (n=138)
    Zona: 35 colunas
    Importance: 0.000058
  Predicado: F4 > -0.47 (n=138)
    Zona: 50 colunas
    Importance: -0.064255
  Predicado: F4 <= -0.24 (n=65)
    Zona: 50 colunas
    Importance: 0.247705
  Predicado: F4 > -0.24 (n=103)
    Zona: 50 colunas
    Importance: -0.112888
  Predicado: F4 <= 0.18 (n=100)
    Zona: 50 colunas
    Importance: 0.181766
  Predicado: F4 > 0.18 (n=68)
    Zona: 50 colunas
    Importance: -0.201517
  Predicado: F4 <= 0.50 (n=132)
    Zona: 50 colunas
    Importance: 0.067750
  Predicado: background4 > -0.09 (n=131)
    Zona: 30 colunas
    Importance: -0.000035
  Predicado: background4 <= -0.07 (n=71)
    Zona: 30 colunas
    Importance: -0.000084
  Predicado: background4 > -0.07 (n=97)
    Zona: 30 colunas
    Importance: 0.000036
  Predicado: background4 <= 0.08 (n=111)
    Zona: 30 colunas
    Importance: -0.000163
  Predicado: background4 > 0.08 (n=57)
    Zona: 30 colunas
    Importance: 0.000274
  Predicado: background4 <= 0.09 (n=122)
    Zona: 30 colunas
    Importance: -0.000111
  Predicado: background4 > 0.09 (n=46)
    Zona: 30 colunas
    Importance: 0.000241
  Predicado: F5 > -0.54 (n=136)
    Zona: 45 colunas
    Importance: 0.327637
  Predicado: F5 <= -0.52 (n=66)
    Zona: 45 colunas
    Importance: -0.133312
  Predicado: F5 > -0.52 (n=102)
    Zona: 45 colunas
    Importance: 0.480751
  Predicado: F5 <= 0.24 (n=98)
    Zona: 45 colunas
    Importance: -0.089625
  Predicado: F5 > 0.24 (n=70)
    Zona: 45 colunas
    Importance: 0.700303
  Predicado: F5 <= 0.61 (n=133)
    Zona: 45 colunas
    Importance: 0.385820
  Predicado: background5 > -0.10 (n=141)
    Zona: 32 colunas
    Importance: -0.000028
  Predicado: background5 <= -0.08 (n=64)
    Zona: 32 colunas
    Importance: 0.000045
  Predicado: background5 > -0.08 (n=104)
    Zona: 32 colunas
    Importance: 0.000032
  Predicado: background5 <= 0.08 (n=104)
    Zona: 32 colunas
    Importance: 0.000010
  Predicado: background5 > 0.08 (n=64)
    Zona: 32 colunas
    Importance: 0.000082
  Predicado: background5 <= 0.10 (n=137)
    Zona: 32 colunas
    Importance: 0.000058
  Predicado: F6 > -0.42 (n=134)
    Zona: 38 colunas
    Importance: -0.035796
  Predicado: F6 <= -0.25 (n=65)
    Zona: 38 colunas
    Importance: 0.073116
  Predicado: F6 > -0.25 (n=103)
    Zona: 38 colunas
    Importance: -0.031427
  Predicado: F6 <= 0.13 (n=100)
    Zona: 38 colunas
    Importance: 0.082520
  Predicado: F6 > 0.13 (n=68)
    Zona: 38 colunas
    Importance: -0.099065
  Predicado: F6 <= 0.42 (n=135)
    Zona: 38 colunas
    Importance: 0.031528
  Predicado: background6 > -0.10 (n=131)
    Zona: 55 colunas
    Importance: -0.000040
  Predicado: background6 <= -0.09 (n=64)
    Zona: 55 colunas
    Importance: 0.000198
  Predicado: background6 > -0.09 (n=104)
    Zona: 55 colunas
    Importance: 0.000003
  Predicado: background6 <= 0.08 (n=94)
    Zona: 55 colunas
    Importance: 0.000122
  Predicado: background6 > 0.08 (n=74)
    Zona: 55 colunas
    Importance: 0.000020
  Predicado: background6 <= 0.10 (n=129)
    Zona: 55 colunas
    Importance: 0.000078

[Bag_9] Processando 74 predicados...
  Predicado: F1 > -0.71 (n=129)
    Zona: 50 colunas

/home/jvribeiro/.local/lib/python3.10/site-packages/networkx/algorithms/centrality/reaching.py:193: RuntimeWarning:

divide by zero encountered in scalar divide

/home/jvribeiro/.local/lib/python3.10/site-packages/networkx/algorithms/centrality/reaching.py:193: RuntimeWarning:

divide by zero encountered in scalar divide

/home/jvribeiro/.local/lib/python3.10/site-packages/networkx/algorithms/centrality/reaching.py:193: RuntimeWarning:

divide by zero encountered in scalar divide

/home/jvribeiro/.local/lib/python3.10/site-packages/networkx/algorithms/centrality/reaching.py:193: RuntimeWarning:

divide by zero encountered in scalar divide

Processando LRC do grafo...

,Predicate_pert_Seed_0,Predicate_pert_Seed_1,Predicate_pert_Seed_2,Predicate_pert_Seed_3
0,F1 <= 0.22,F3 <= 0.14,F4 > -0.47,F1 <= 0.22
1,F1 <= -0.69,F6 > -0.42,F5 <= 0.61,F1 <= 0.83
2,F6 > -0.25,F6 <= 0.42,F1 <= 0.22,F1 <= -0.69
3,F1 <= 0.83,F3 <= 0.44,F2 <= -0.23,F1 > -0.69
4,F6 > -0.42,F6 > -0.25,F3 <= 0.44,background2 <= 0.07
...,...,...,...,...
74,background3 > -0.09,background4 > 0.08,background1 <= -0.08,background3 <= -0.09
75,background1 <= -0.08,background5 <= -0.08,background6 > 0.10,Class_A
76,F5 > 0.61,Class_A,Class_A,Class_B
77,Class_A,Class_B,Class_B,NaN
78,Class_B,NaN,NaN,NaN

In [11]:
from collections import defaultdict

# Coletar posições de cada predicado em cada seed do lrc_pert_all_seeds_df
positions_dict_lrc = defaultdict(list) # o defaultdict cria listas vazias automaticamente

# Iterar sobre cada coluna do dataframe lrc_pert_all_seeds_df
for col in lrc_pert_all_seeds_df.columns:
    # Pegar os predicados da coluna (não-nulos)
    predicates_in_seed = lrc_pert_all_seeds_df[col].dropna().tolist()
    
    # Para cada predicado, guardar sua posição (1-based)
    for position, predicate in enumerate(predicates_in_seed, start=1):
        positions_dict_lrc[predicate].append(position)

# Calcular média e número de aparições
results_lrc = []
for predicate, positions in positions_dict_lrc.items():
    zone_row = predicates_quantiles[0].loc[predicates_quantiles[0]['rule'] == predicate, 'zone']
    zone_value = zone_row.values[0] if not zone_row.empty else None
    results_lrc.append({
        'Predicate': predicate,
        'Mean_Position': np.mean(positions),
        'Appearances': len(positions),
        'Zone': zone_value
    })

# Ordenar: menor posição média primeiro, mais aparições em caso de empate
ranking_lrc_pert_df = pd.DataFrame(results_lrc).sort_values(
    by=['Mean_Position', 'Appearances'], 
    ascending=[True, False]
).reset_index(drop=True)

# Lista final ordenada
lista_ordenada_lrc = ranking_lrc_pert_df['Predicate'].tolist()
ranking_lrc_pert_df

               Predicate  Mean_Position  Appearances         Zone
0             F1 <= 0.22           3.00            4           F1
1            F1 <= -0.69           7.00            4           F1
2             F1 <= 0.83           7.75            4           F1
3             F3 <= 0.44          10.75            4           F3
4             F1 > -0.69          11.50            4           F1
..                   ...            ...          ...          ...
74  background1 <= -0.08          71.75            4  background1
75  background3 <= -0.09          72.50            4  background3
76               Class_A          77.00            4         None
77             F5 > 0.61          77.00            1           F5
78               Class_B          78.00            4         None

[79 rows x 4 columns]

In [12]:
ranking_pert_lrc_unique_df = ranking_lrc_pert_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
ranking_pert_lrc_unique_df['Zone']

0              F1
1              F3
2              F6
3              F4
4              F2
5              F5
6     background1
7     background6
8     background2
9     background4
10    background5
11    background3
12           None
Name: Zone, dtype: object

In [13]:
with pd.ExcelWriter('Perturbation_method.xlsx') as writer:
    # Primeiro: salvar os rankings médios
    ranking_lrc_pert_df.to_excel(writer, sheet_name='Mean_LRC', index=False)
    ranking_pert_lrc_unique_df.to_excel(writer, sheet_name='Mean_LRC_Unique', index=False)
    
    # Segundo: salvar os LRCs por seed
    for seed in random_seeds:
        lrc_pert_by_seed[seed].to_excel(writer, sheet_name=f'LRC_seed_{seed}', index=False)
    
    # Terceiro: salvar os resultados de perturbação por bag e seed
    for seed in random_seeds:
        for bag_name, df in all_results_pert[seed]['pert_results_dict'].items():
            # Criar nome único: seed_0_Bag_1, seed_1_Bag_1, etc.
            sheet_name = f'seed_{seed}_{bag_name}'[:31]  # Excel limita a 31 caracteres
            df.to_excel(writer, sheet_name=sheet_name, index=False)

# **Permutation**

In [14]:
ranking_perm_lrc_unique_df = pd.read_excel('Permutation_method.xlsx', sheet_name='Mean_LRC_Unique')
ranking_perm_lrc_unique_df['Zone']

0              F1
1              F5
2              F4
3     background4
4              F6
5              F3
6              F2
7     background5
8     background6
9     background3
10    background1
11    background2
12            NaN
Name: Zone, dtype: object

In [15]:
import numpy as np

max_len = max(
    len(vip_scores_unique_df['Zone']),
    len(reg_vet_unique_df['Zone']),
    len(shap_unique_df['Zone']),
    len(ranking_pert_lrc_unique_df['Zone']),
    len(ranking_perm_lrc_unique_df['Zone']),
    len(ranking_cov_lrc_unique_df['Zone'])
)

def pad_list(lst, length):
    return list(lst) + [None] * (length - len(lst))

features_importance = pd.DataFrame({
    'Vip': pad_list(vip_scores_unique_df['Zone'], max_len),
    'Reg_coef': pad_list(reg_vet_unique_df['Zone'], max_len),
    'Shap': pad_list(shap_unique_df['Zone'], max_len),
    'LRC_cov' : pad_list(ranking_cov_lrc_unique_df['Zone'], max_len),
    'LRC_pert' : pad_list(ranking_pert_lrc_unique_df['Zone'], max_len),
    'LRC_perm' : pad_list(ranking_perm_lrc_unique_df['Zone'], max_len)
})

features_importance.to_csv('feature_importance.csv', index=False, sep=';')
features_importance

,Vip,Reg_coef,Shap,LRC_cov,LRC_pert,LRC_perm
0,F1,F1,F1,F1,F1,F1
1,F5,F5,F5,F5,F3,F5
2,F4,F4,F3,F2,F6,F4
3,F3,F3,F4,F4,F4,background4
4,F6,F6,F6,F6,F2,F6
5,F2,F2,F2,F3,F5,F3
6,background4,background4,background4,background4,background1,F2
7,background5,background5,background6,background6,background6,background5
8,background6,background6,background5,background1,background2,background6
9,background3,background3,background1,background3,background4,background3
10,background1,background1,background3,None,background5,background1
11,background2,background2,background2,None,background3,background2
12,None,None,None,None,None,NaN

In [16]:
# RBO (Rank-Biased Overlap) para comparar rankings
import rbo
rbo_results = {}
reference_list = [x for x in features_importance['Vip'].tolist() if x is not None]
methods = ['Reg_coef', 'Shap', 'LRC_cov', 'LRC_pert', 'LRC_perm']
for method in methods:
    compare_list = [x for x in features_importance[method].tolist() if x is not None]
    # Truncate both lists to the same length (minimum of both)
    min_len = min(len(reference_list), len(compare_list))
    ref_trunc = reference_list[:min_len]
    cmp_trunc = compare_list[:min_len]
    score = rbo.RankingSimilarity(ref_trunc, cmp_trunc).rbo(p=0.7, k=10)
    rbo_results[method] = score
rbo_results = pd.DataFrame(list(rbo_results.items()), columns=['Method','RBO_Score'])
rbo_results.insert(0, 'Reference', 'Vip')
rbo_results.sort_values(by='RBO_Score', ascending=False, inplace=True)
rbo_results.to_csv('rbo_rank.csv', index=False, sep=';')
rbo_results

  Reference    Method  RBO_Score
0       Vip  Reg_coef   0.971752
4       Vip  LRC_perm   0.923218
1       Vip      Shap   0.918454
2       Vip   LRC_cov   0.876401
3       Vip  LRC_pert   0.711138