## Loading data

In [1]:
# Importing the necessary libraries
import pandas as pd
import numpy as np
import kennard_stone as ks
pd.options.plotting.backend = 'plotly'  # setting plotly as the backend for pandas plotting

# Add parent directory to sys.path so local module 'synthetic' (one level up) can be imported
import sys
from pathlib import Path # for path manipulations
parent_dir = Path.cwd().parent.parent.resolve() # move two levels up from current working directory
if str(parent_dir) not in sys.path: # check to avoid duplicates
    sys.path.insert(0, str(parent_dir)) # insert at the start of sys.path to prioritize local modules

# Loading a soil spectral dataset based on X-ray fluorescence (XRF)
data_complete = pd.read_csv(f'{parent_dir}/XRF_databases/bank_notes/plsda/bank_notes.csv', sep=';') # local copy of Toledo 2022 dataset (os ... indica para omitir o caminho longo)
data = data_complete.loc[:, '1':'26.07']

In [2]:
# Split dataset by class and create calibration/prediction sets using Kennard-Stone (as in original pipeline)
data_A = data_complete[data_complete['Class'] == 'A'].reset_index(drop=True)
data_B = data_complete[data_complete['Class'] == 'B'].reset_index(drop=True)

# splitting the data into calibration and prediction sets by kennard-stone algorithm
XA_cal, XA_pred = ks.train_test_split(data_A.loc[:, '1':'26.07'], test_size=0.30)  # class A
XA_cal = XA_cal.reset_index(drop=True)
XA_pred = XA_pred.reset_index(drop=True)

XB_cal, XB_pred = ks.train_test_split(data_B.loc[:, '1':'26.07'], test_size=0.30)  # class B
XB_cal = XB_cal.reset_index(drop=True)
XB_pred = XB_pred.reset_index(drop=True)

Xcalclass = pd.concat([XA_cal, XB_cal], axis=0).reset_index(drop=True)  # concatenating both classes
Xpredclass = pd.concat([XA_pred, XB_pred], axis=0).reset_index(drop=True)
ycalclass = pd.Series(['A']*XA_cal.shape[0] + ['B']*XB_cal.shape[0])  # target for calibration set
ypredclass = pd.Series(['A']*XA_pred.shape[0] + ['B']*XB_pred.shape[0])  # target for prediction set

# preprocessings
import preprocessings as prepr  # preprocessing methods for XRF data

Xcalclass_prep, mean_calclass, mean_calclass_poisson  = prepr.poisson(Xcalclass, mc=True)
Xpredclass_prep = ((Xpredclass/np.sqrt(mean_calclass)) - mean_calclass_poisson)

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-01-26 06:07:28,999 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-01-26 06:07:29,089 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-01-26 06:07:29,153 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-01-26 06:07:29,204 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

In [3]:
# PLS-DA with optimized latent variables
from modeling import pls_optimized

plsda_results = pls_optimized(
    Xcalclass_prep, 
    ycalclass,
    LVmax=4,
    Xpred=Xpredclass_prep,
    ypred=ypredclass,
    aim='classification',
    cv=10
)

# Convenience references used later
pls_model = plsda_results[3]               # fitted PLS model
vip_scores_mat = plsda_results[4]          # VIP scores matrix (features × LV)
y_pred_cont = plsda_results[5].iloc[:, -1] # continuous predictions for Xcalclass (used for MI/Cov)

# plotando o vip scores rapidamente
vip_scores_mat.T.plot()

In [4]:
# calculando a covariancia entre cada variável espectral e a predição do modelo PLS-DA
cov_scores = []
y_pred = plsda_results[5].iloc[:,-1].values # using the continuous predictions from LV=3
for col in Xcalclass_prep.columns:
    x_values = Xcalclass_prep[col].values
    covariance = np.cov(x_values, y_pred)[0, 1] # covariance between x and y
    cov_scores.append(covariance)
cov_scores_df = pd.DataFrame(cov_scores, index=Xcalclass_prep.columns, columns=['Covariance'])
cov_scores_df = np.abs(cov_scores_df)
cov_scores_df.plot()

In [5]:
# establishing spectral cuts based on expert knowledge of XRF spectra
spectral_cuts = [
('background1', 1.0, 2.74),
('Ar ka + Ag L', 2.76, 3.47),
('Ca ka', 3.5, 3.91),
('Ca kb', 3.93, 4.24),
('Ti ka', 4.26, 4.72),
('Ti kb', 4.75, 5.13),
('background2', 5.16, 6.12),
('Fe ka', 6.15, 6.76),
('Fe kb', 6.79, 7.32),
('background3', 7.35, 7.78),
('Cu ka', 7.81, 8.29),
('Zn ka', 8.29, 8.80),
('Cu kb', 8.80, 9.26),
('Zn kb', 9.26, 10.00),
('background4', 10.00, 21.46),
('Ag ka scattering', 21.49, 22.71),
('background5', 22.74, 24.52),
('background6', 24.55, 26.07),
]

import explaining as exp
spectral_zones_class = exp.extract_spectral_zones(Xcalclass_prep, spectral_cuts)
zone_sums_df = exp.aggregate_spectral_zones(spectral_zones_class, aggregator='extreme')
predicates_quantiles = exp.predicates_by_quantiles(zone_sums_df, [0.2, 0.4, 0.6, 0.8])
co_occurrence_matrix_df = predicates_quantiles[2]
predicate_info_dict = exp.create_predicate_info_dict(
    predicates_df=predicates_quantiles[0],
    predicate_indicator_df=predicates_quantiles[1],
    zone_aggregated_df=zone_sums_df,
    y_predicted_numeric=y_pred_cont
)

## VIP, Regression Coefficients e SHAP (como no original)

In [6]:
# VIP scores por energia
vip_scores_df = pd.DataFrame({
    'energy': vip_scores_mat.T.index,
    'VIP_Score': vip_scores_mat.T.iloc[:,0].values
})
vip_scores_df = vip_scores_df.sort_values(by='VIP_Score', ascending=False).reset_index(drop=True)
energy_to_zone_vip = {}
for zone_name, start, end in spectral_cuts:
    for e in vip_scores_df['energy']:
        ef = float(e)
        if start <= ef <= end:
            energy_to_zone_vip[e] = zone_name
vip_scores_df['Zone'] = vip_scores_df['energy'].map(energy_to_zone_vip)
vip_scores_unique_df = vip_scores_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
vip_scores_unique_df = vip_scores_unique_df.sort_values(by='VIP_Score', ascending=False).reset_index(drop=True)

# Coeficientes de regressão do PLS
reg_vet = pd.DataFrame(pls_model.coef_, columns=pls_model.feature_names_in_).T
reg_vet.insert(0, 'energy', reg_vet.index)
reg_vet = reg_vet.reset_index(drop=True)
reg_vet.columns = ['energy','Reg_coef']
reg_vet['Abs_Reg_coef'] = reg_vet['Reg_coef'].abs()
reg_vet = reg_vet.sort_values(by='Abs_Reg_coef', ascending=False).reset_index(drop=True)
energy_to_zone_reg = {}
for zone_name, start, end in spectral_cuts:
    for e in reg_vet['energy']:
        ef = float(e)
        if start <= ef <= end:
            energy_to_zone_reg[e] = zone_name
reg_vet['Zone'] = reg_vet['energy'].map(energy_to_zone_reg)
reg_vet_unique_df = reg_vet.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
reg_vet_unique_df = reg_vet_unique_df.sort_values(by='Abs_Reg_coef', ascending=False).reset_index(drop=True)
shap_unique_df = pd.read_csv('shap_bank_notes.csv', sep=';') # loading previously saved shap_unique_df

# **bagging - covariance**

In [36]:
import explaining as exp

# LISTA DE SEMENTES A TESTAR
random_seeds = [0, 1, 2, 3]

all_results_cov = {}
training_samples = len(Xcalclass)

# LOOP: PROCESSAR CADA SEMENTE
y_predicted_numeric = plsda_results[5].iloc[:, -1] # predições numéricas do modelo

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando semente: {seed}")
    print(f"{'='*70}\n")
    # Bagging
    bags_result_seed = exp.bagging_predicates(
        zone_sums_df=zone_sums_df,
        y_predicted_numeric=y_predicted_numeric,
        predicates_df=predicates_quantiles[0],
        n_bags=10,
        #n_predicates_per_bag=40,
        n_samples_per_bag=int(training_samples*0.8), # 80 % da base para amostrar (convertido para int)
        min_samples_per_predicate=int(training_samples*0.2), # 20 % da base para limitar (convertido para int)
        replace=False,
        sample_bagging=True,
        predicate_bagging=False,
        random_seed=seed
    )
    # Inserir classe prevista
    for bag_name, pred_dict in bags_result_seed.items(): # iterando sobre cada bag
        for pred_rule, df_info in pred_dict.items():
            df_info['Class_Predicted'] = np.where(df_info['Predicted_Y'] >= 0.5, 'A', 'B') # binarizando com threshold 0.5, A = eut, B = dist
    # Calcular MI
    cov_results_dict_seed = exp.calculate_predicate_metrics(
        bags_result=bags_result_seed,
        metric='covariance', # covariance ou mutual_information
        threshold=0.01, # threshold para cortar predicados irrelevantes
        n_neighbors=5
    )
    # Salvar no dicionário principal
    all_results_cov[seed] = {
        'bags_result': bags_result_seed,
        'cov_results_dict': cov_results_dict_seed
    }

# CONSTRUÇÃO DE GRAFOS PARA MÚLTIPLAS SEMENTES (LOOP EXTERNO)
# Dicionário para armazenar grafos
graphs_by_seed = {}

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando Grafo - Semente: {seed}")
    print(f"{'='*70}\n")
    # Construir grafo para esta semente
    DG = exp.build_predicate_graphv2(
        bags_result=all_results_cov[seed]['bags_result'],
        predicate_ranking_dict=all_results_cov[seed]['cov_results_dict'],
        metric_column='Covariance',  # ou 'Covariance' se mudar a métrica
        random_state=seed,
        show_details=True
    )
    # Armazenar grafo
    graphs_by_seed[seed] = DG

# Calcular LRC usando a função pronta do explaining.py
lrc_cov_by_seed = {}
for seed in random_seeds:
    DG = graphs_by_seed[seed]
    lrc_cov_df_seed = exp.calculate_lrc_single_graph(DG, predicates_quantiles[0])
    lrc_cov_df_seed['Seed'] = seed  # Adicionar coluna com a semente
    lrc_cov_by_seed[seed] = lrc_cov_df_seed

# junando todas as colunas 'Node' de lrc_by_seed em um único dataframe
lrc_cov_all_seeds_df = pd.DataFrame()
for seed in random_seeds:
    lrc_cov_df_seed = lrc_cov_by_seed[seed].rename(columns={'Node': f'Predicate_Cov_Seed_{seed}'})
    lrc_cov_all_seeds_df = pd.concat([lrc_cov_all_seeds_df, lrc_cov_df_seed[[f'Predicate_Cov_Seed_{seed}']]], axis=1)

# vamos filtrar lrc_by_seed em cada semente para manter apenas as zonas espectrais únicas com maior LRC em um mesmo dataframe
lrc_cov_unique_by_seed = {}
for seed, lrc_df in lrc_cov_by_seed.items():
    lrc_cov_unique_df = lrc_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
    lrc_cov_unique_df = lrc_cov_unique_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
    lrc_cov_unique_by_seed[seed] = lrc_cov_unique_df

lrc_cov_all_seeds_df # exibindo o dataframe consolidado com predicados de todas as sementes

======================================================================
Processando semente: 0
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 109 | Descartados: 35
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 109 | Descartados: 35
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 108 | Descartados: 36
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 108 | Descartados: 36
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 108 | Descartados: 36
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 109 | Descartados: 35
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 108 | Descartados: 36
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 108 | Descartados: 36
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 108 | Descartados: 36
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 108 | Descartados: 36
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando semente: 1
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 108 | Descartados: 36
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 108 | Descartados: 36
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 109 | Descartados: 35
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 109 | Descartados: 35
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 108 | Descartados: 36
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 108 | Descartados: 36
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 108 | Descartados: 36
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 109 | Descartados: 35
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 109 | Descartados: 35
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 109 | Descartados: 35
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando semente: 2
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 109 | Descartados: 35
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 108 | Descartados: 36
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 109 | Descartados: 35
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 109 | Descartados: 35
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 108 | Descartados: 36
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 109 | Descartados: 35
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 108 | Descartados: 36
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 109 | Descartados: 35
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 108 | Descartados: 36
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 108 | Descartados: 36
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando semente: 3
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 108 | Descartados: 36
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 109 | Descartados: 35
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 109 | Descartados: 35
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 108 | Descartados: 36
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 109 | Descartados: 35
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 109 | Descartados: 35
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 108 | Descartados: 36
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 108 | Descartados: 36
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 108 | Descartados: 36
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 108 | Descartados: 36
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando Grafo - Semente: 0
======================================================================


Total de pares bidirecionais encontrados: 91
Removida aresta Ca ka > -9.12 -> Ca ka > -11.34 (peso 21.7502)
Mantida aresta Ca ka > -11.34 -> Ca ka > -9.12 (peso 34.3307)

======================================================================

Removida aresta Ca ka > -3.71 -> Fe kb > -3.35 (peso 4.1057)
Mantida aresta Fe kb > -3.35 -> Ca ka > -3.71 (peso 40.7043)

======================================================================

Removida aresta Ti ka > -11.81 -> Ti ka <= 9.71 (peso 9.9205)
Mantida aresta Ti ka <= 9.71 -> Ti ka > -11.81 (peso 16.1432)

======================================================================

Removida aresta Fe kb > -3.54 -> Ti ka > -11.81 (peso 6.4315)
Mantida aresta Ti ka > -11.81 -> Fe kb > -3.54 (peso 15.9185)

======================================================================

Removida aresta Ti ka <= 5.26 -> Fe kb > -3.78 (peso 2.1737)
Mantida aresta Fe kb > -3.78 -> Ti ka <= 5.26 (peso 22.1252)

======================================================================

Removida aresta Ca kb > -4.15 -> Ca kb > -3.42 (peso 8.6143)
Mantida aresta Ca kb > -3.42 -> Ca kb > -4.15 (peso 13.0965)

======================================================================

Removida aresta Cu ka > -4.62 -> Ti kb > -4.43 (peso 2.9282)
Mantida aresta Ti kb > -4.43 -> Cu ka > -4.62 (peso 3.0280)

======================================================================

Removida aresta Ca kb > -2.18 -> Ti kb > -4.43 (peso 2.7924)
Mantida aresta Ti kb > -4.43 -> Ca kb > -2.18 (peso 2.9451)

======================================================================

Removida aresta Ti kb > -4.43 -> Cu ka > -4.31 (peso 1.5091)
Mantida aresta Cu ka > -4.31 -> Ti kb > -4.43 (peso 3.3613)

======================================================================

Removida aresta Cu ka > -4.62 -> Cu ka > -3.81 (peso 1.5553)
Mantida aresta Cu ka > -3.81 -> Cu ka > -4.62 (peso 8.9138)

======================================================================

Removida aresta Ca kb > -2.18 -> Ca ka <= 15.99 (peso 1.2601)
Mantida aresta Ca ka <= 15.99 -> Ca kb > -2.18 (peso 1.2701)

======================================================================

Removida aresta Ca kb > -2.18 -> Cu ka > -4.31 (peso 1.2360)
Mantida aresta Cu ka > -4.31 -> Ca kb > -2.18 (peso 2.9091)

======================================================================

Removida aresta Ti kb <= 5.00 -> Ca kb > -2.18 (peso 5.3563)
Mantida aresta Ca kb > -2.18 -> Ti kb <= 5.00 (peso 5.5289)

======================================================================

Removida aresta Ti kb <= 2.64 -> Ti ka > -3.08 (peso 0.9220)
Mantida aresta Ti ka > -3.08 -> Ti kb <= 2.64 (peso 9.0102)

======================================================================

Removida aresta Cu kb > -1.94 -> Ti ka > 5.26 (peso 1.2568)
Mantida aresta Ti ka > 5.26 -> Cu kb > -1.94 (peso 3.4539)

======================================================================

Removida aresta Cu kb > -1.94 -> Ca kb <= 6.30 (peso 1.1385)
Mantida aresta Ca kb <= 6.30 -> Cu kb > -1.94 (peso 2.2421)

======================================================================

Removida aresta Ca kb <= 6.30 -> Cu kb > 1.49 (peso 0.4179)
Mantida aresta Cu kb > 1.49 -> Ca kb <= 6.30 (peso 0.5341)

======================================================================

Removida aresta Ca kb <= 6.30 -> Ti kb > -2.36 (peso 0.5292)
Mantida aresta Ti kb > -2.36 -> Ca kb <= 6.30 (peso 1.4383)

======================================================================

Removida aresta Cu kb > -2.22 -> Ti kb > -2.36 (peso 1.0062)
Mantida aresta Ti kb > -2.36 -> Cu kb > -2.22 (peso 1.4475)

======================================================================

Removida aresta Ti kb > -2.36 -> Cu kb > 1.49 (peso 0.4461)
Mantida aresta Cu kb > 1.49 -> Ti kb > -2.36 (peso 1.0046)

======================================================================

Removida aresta Cu kb > 1.49 -> Ti ka <= -3.08 (peso 0.8021)
Mantida aresta Ti ka <= -3.08 -> Cu kb > 1.49 (peso 2.2039)

======================================================================

Removida aresta Zn ka > -1.99 -> Zn ka <= 2.74 (peso 0.6692)
Mantida aresta Zn ka <= 2.74 -> Zn ka > -1.99 (peso 1.6055)

======================================================================

Removida aresta Ti kb > 2.64 -> Zn ka <= 2.74 (peso 0.3245)
Mantida aresta Zn ka <= 2.74 -> Ti kb > 2.64 (peso 0.6486)

======================================================================

Removida aresta background5 <= 2.48 -> Ti kb > 2.64 (peso 0.2463)
Mantida aresta Ti kb > 2.64 -> background5 <= 2.48 (peso 0.6053)

======================================================================

Removida aresta background2 <= 2.59 -> Ti kb > 2.64 (peso 0.2340)
Mantida aresta Ti kb > 2.64 -> background2 <= 2.59 (peso 0.4750)

======================================================================

Removida aresta Ti kb > 2.64 -> background4 <= 2.89 (peso 0.2287)
Mantida aresta background4 <= 2.89 -> Ti kb > 2.64 (peso 0.3634)

======================================================================

Removida aresta background5 <= 2.88 -> background5 <= 2.48 (peso 0.4844)
Mantida aresta background5 <= 2.48 -> background5 <= 2.88 (peso 1.2880)

======================================================================

Removida aresta background5 <= 2.48 -> background2 <= 2.59 (peso 0.2434)
Mantida aresta background2 <= 2.59 -> background5 <= 2.48 (peso 0.4981)

======================================================================

Removida aresta background5 <= 2.48 -> background4 <= 2.89 (peso 0.2386)
Mantida aresta background4 <= 2.89 -> background5 <= 2.48 (peso 0.2818)

======================================================================

Removida aresta background5 <= 2.88 -> background2 <= 3.28 (peso 0.4883)
Mantida aresta background2 <= 3.28 -> background5 <= 2.88 (peso 0.5521)

======================================================================

Removida aresta background4 <= 3.24 -> background5 <= 2.88 (peso 0.2238)
Mantida aresta background5 <= 2.88 -> background4 <= 3.24 (peso 0.2976)

======================================================================

Removida aresta Zn ka <= 2.18 -> background2 <= 3.28 (peso 0.2116)
Mantida aresta background2 <= 3.28 -> Zn ka <= 2.18 (peso 0.4502)

======================================================================

Removida aresta background2 > -2.08 -> Zn ka <= 2.18 (peso 0.1991)
Mantida aresta Zn ka <= 2.18 -> background2 > -2.08 (peso 0.4030)

======================================================================

Removida aresta Zn ka <= 2.18 -> background2 <= 2.59 (peso 0.2151)
Mantida aresta background2 <= 2.59 -> Zn ka <= 2.18 (peso 0.2400)

======================================================================

Removida aresta Ag ka scattering <= 2.57 -> background6 > -2.43 (peso 0.1370)
Mantida aresta background6 > -2.43 -> Ag ka scattering <= 2.57 (peso 0.1756)

======================================================================

Removida aresta Ag ka scattering <= 3.08 -> background2 <= 2.59 (peso 0.2047)
Mantida aresta background2 <= 2.59 -> Ag ka scattering <= 3.08 (peso 0.2159)

======================================================================

Removida aresta Ag ka scattering <= 3.08 -> background2 > -2.08 (peso 0.1202)
Mantida aresta background2 > -2.08 -> Ag ka scattering <= 3.08 (peso 0.3365)

======================================================================

Removida aresta background1 <= 2.53 -> Ag ka scattering <= 3.08 (peso 0.1588)
Mantida aresta Ag ka scattering <= 3.08 -> background1 <= 2.53 (peso 0.1772)

======================================================================

Removida aresta background6 <= 2.28 -> background2 > -2.08 (peso 0.2071)
Mantida aresta background2 > -2.08 -> background6 <= 2.28 (peso 0.3649)

======================================================================

Removida aresta background2 > -2.08 -> Ca ka <= -3.71 (peso 0.1902)
Mantida aresta Ca ka <= -3.71 -> background2 > -2.08 (peso 0.1948)

======================================================================

Removida aresta background6 <= 2.28 -> background4 <= 3.24 (peso 0.1468)
Mantida aresta background4 <= 3.24 -> background6 <= 2.28 (peso 0.1651)

======================================================================

Removida aresta Ag ka scattering <= -1.94 -> background6 <= 2.28 (peso 0.1186)
Mantida aresta background6 <= 2.28 -> Ag ka scattering <= -1.94 (peso 0.1197)

======================================================================

Removida aresta background5 > -2.53 -> Ca ka <= -3.71 (peso 0.1696)
Mantida aresta Ca ka <= -3.71 -> background5 > -2.53 (peso 0.1936)

======================================================================

Removida aresta background5 > -2.53 -> Zn ka > -1.46 (peso 0.1215)
Mantida aresta Zn ka > -1.46 -> background5 > -2.53 (peso 0.1365)

======================================================================

Removida aresta background4 <= 2.89 -> Ca ka <= -3.71 (peso 0.1498)
Mantida aresta Ca ka <= -3.71 -> background4 <= 2.89 (peso 0.3607)

======================================================================

Removida aresta background4 <= 2.89 -> background4 <= 3.54 (peso 0.1904)
Mantida aresta background4 <= 3.54 -> background4 <= 2.89 (peso 0.2489)

======================================================================

Removida aresta background4 <= 3.24 -> background4 <= 3.54 (peso 0.2954)
Mantida aresta background4 <= 3.54 -> background4 <= 3.24 (peso 0.3036)

======================================================================

Removida aresta Zn ka > -1.46 -> Ag ka scattering <= -1.94 (peso 0.1222)
Mantida aresta Ag ka scattering <= -1.94 -> Zn ka > -1.46 (peso 0.2667)

======================================================================

Removida aresta Zn ka > -1.46 -> background6 > -2.43 (peso 0.1216)
Mantida aresta background6 > -2.43 -> Zn ka > -1.46 (peso 0.1311)

======================================================================

Removida aresta Zn ka > -1.46 -> background2 <= 2.16 (peso 0.1312)
Mantida aresta background2 <= 2.16 -> Zn ka > -1.46 (peso 0.1369)

======================================================================

Removida aresta background3 <= 1.70 -> Ag ka scattering <= -1.94 (peso 0.1074)
Mantida aresta Ag ka scattering <= -1.94 -> background3 <= 1.70 (peso 0.1193)

======================================================================

Removida aresta background3 <= 1.70 -> Ti kb <= -2.36 (peso 0.1075)
Mantida aresta Ti kb <= -2.36 -> background3 <= 1.70 (peso 0.1101)

======================================================================

Removida aresta background1 <= 2.22 -> Ti kb <= -2.36 (peso 0.1075)
Mantida aresta Ti kb <= -2.36 -> background1 <= 2.22 (peso 0.1105)

======================================================================

Removida aresta Ag ka scattering > -2.84 -> Ti kb <= -2.36 (peso 0.1176)
Mantida aresta Ti kb <= -2.36 -> Ag ka scattering > -2.84 (peso 0.1904)

======================================================================

Removida aresta Ti kb <= -2.36 -> background1 > -2.42 (peso 0.1061)
Mantida aresta background1 > -2.42 -> Ti kb <= -2.36 (peso 0.1171)

======================================================================

Removida aresta background1 <= 3.00 -> background6 > -2.43 (peso 0.1299)
Mantida aresta background6 > -2.43 -> background1 <= 3.00 (peso 0.1432)

======================================================================

Removida aresta Ca ka <= -9.12 -> background6 <= 2.71 (peso 0.0951)
Mantida aresta background6 <= 2.71 -> Ca ka <= -9.12 (peso 0.0988)

======================================================================

Removida aresta Ca ka <= -9.12 -> Cu ka <= -2.19 (peso 0.0768)
Mantida aresta Cu ka <= -2.19 -> Ca ka <= -9.12 (peso 0.0872)

======================================================================

Removida aresta background2 <= 2.16 -> background6 <= 2.71 (peso 0.0524)
Mantida aresta background6 <= 2.71 -> background2 <= 2.16 (peso 0.0909)

======================================================================

Removida aresta background2 <= 2.16 -> background6 <= 3.20 (peso 0.0845)
Mantida aresta background6 <= 3.20 -> background2 <= 2.16 (peso 0.1009)

======================================================================

Removida aresta background6 <= 3.20 -> background3 <= 2.47 (peso 0.0293)
Mantida aresta background3 <= 2.47 -> background6 <= 3.20 (peso 0.0637)

======================================================================

Removida aresta background4 > -3.06 -> background1 > -2.42 (peso 0.0758)
Mantida aresta background1 > -2.42 -> background4 > -3.06 (peso 0.0800)

======================================================================

Removida aresta background1 > -2.42 -> Cu kb <= 2.72 (peso 0.0654)
Mantida aresta Cu kb <= 2.72 -> background1 > -2.42 (peso 0.1630)

======================================================================

Removida aresta background1 <= 3.00 -> background1 <= 2.53 (peso 0.1691)
Mantida aresta background1 <= 2.53 -> background1 <= 3.00 (peso 0.1862)

======================================================================

Removida aresta Cu ka <= -2.19 -> Zn kb <= 1.87 (peso 0.0730)
Mantida aresta Zn kb <= 1.87 -> Cu ka <= -2.19 (peso 0.0926)

======================================================================

Removida aresta background3 <= 2.47 -> Cu ka <= -2.19 (peso 0.0606)
Mantida aresta Cu ka <= -2.19 -> background3 <= 2.47 (peso 0.0664)

======================================================================

Removida aresta Zn kb <= 1.87 -> Cu kb <= 2.72 (peso 0.0384)
Mantida aresta Cu kb <= 2.72 -> Zn kb <= 1.87 (peso 0.0652)

======================================================================

Removida aresta Cu kb <= 2.72 -> Ar ka + Ag L <= 2.08 (peso 0.0611)
Mantida aresta Ar ka + Ag L <= 2.08 -> Cu kb <= 2.72 (peso 0.0729)

======================================================================

Removida aresta Cu kb <= 2.72 -> Ca kb <= -2.18 (peso 0.0547)
Mantida aresta Ca kb <= -2.18 -> Cu kb <= 2.72 (peso 0.0613)

======================================================================

Removida aresta Ar ka + Ag L <= 2.47 -> Fe ka <= -9.80 (peso 0.0107)
Mantida aresta Fe ka <= -9.80 -> Ar ka + Ag L <= 2.47 (peso 0.0177)

======================================================================

Removida aresta background5 <= 2.03 -> Ag ka scattering > 2.57 (peso 0.0157)
Mantida aresta Ag ka scattering > 2.57 -> background5 <= 2.03 (peso 0.0328)

======================================================================

Removida aresta background4 > 3.24 -> Ar ka + Ag L > -1.64 (peso 0.0295)
Mantida aresta Ar ka + Ag L > -1.64 -> background4 > 3.24 (peso 0.0441)

======================================================================

Removida aresta background3 > 2.09 -> Zn ka > 2.18 (peso 0.0367)
Mantida aresta Zn ka > 2.18 -> background3 > 2.09 (peso 0.0445)

======================================================================

Removida aresta background3 <= 2.47 -> background3 > 2.09 (peso 0.0349)
Mantida aresta background3 > 2.09 -> background3 <= 2.47 (peso 0.0528)

======================================================================

Removida aresta Zn ka > 2.18 -> Cu ka <= -3.81 (peso 0.0304)
Mantida aresta Cu ka <= -3.81 -> Zn ka > 2.18 (peso 0.0398)

======================================================================


,Predicate_Cov_Seed_0,Predicate_Cov_Seed_1,Predicate_Cov_Seed_2,Predicate_Cov_Seed_3
0,Fe ka > -9.53,Fe ka > -9.53,Fe ka > -9.53,Fe ka > -9.53
1,Fe ka > -9.80,Fe ka > -9.80,Fe ka > -9.80,Fe ka > -9.80
2,Ca ka > -11.34,Fe ka > -10.00,Fe ka > -10.00,Fe ka > -10.00
3,Fe ka > -10.00,Ca ka > -9.12,Ca ka > -9.12,Ca ka > -11.34
4,Ca ka > -9.12,Fe kb > -3.14,Ca ka > -11.34,Ca ka > -9.12
...,...,...,...,...
106,Cu ka <= -4.31,background1 > 2.22,Cu kb <= -1.94,Fe ka <= -10.00
107,Class_A,Fe ka <= -10.00,Class_A,Class_A
108,Class_B,Cu ka <= -4.31,Class_B,Class_B
109,NaN,Class_A,NaN,NaN
110,NaN,Class_B,NaN,NaN

In [49]:
all_results_cov[0]['cov_results_dict']['Bag_8']

             Predicate  Covariance
0        Fe ka > -9.53   12.909682
1        Fe ka > -9.80    8.967254
2       Fe ka > -10.00    7.678736
3       Ca ka > -11.34    5.814477
4        Ca ka > -9.12    5.694856
..                 ...         ...
91      Cu kb <= -1.94    0.013838
92      Fe kb <= -3.54    0.013433
93      Fe ka <= -9.25    0.013134
94      Fe ka <= -9.80    0.011385
95  background1 > 2.53    0.010963

[96 rows x 2 columns]

In [37]:
# Somar LRCs de predicados equivalentes entre diferentes seeds
lrc_combined_list = []

for seed in random_seeds:
    lrc_df = lrc_cov_by_seed[seed].copy()
    lrc_combined_list.append(lrc_df) # o append adiciona o dataframe ao final da lista

# Concatenar todos os dataframes
lrc_all_seeds = pd.concat(lrc_combined_list, ignore_index=True) 

# Agrupar por predicado (Node) e somar as LRCs, mantendo Zone, Threshold e Operator
lrc_summed_df = lrc_all_seeds.groupby('Node').agg({ # o .agg pode ser usado para aplicar múltiplas funções de agregação
    'Local_Reaching_Centrality': 'mean', # sum = somando as LRCs, poderia ser média ou outro agregado
    'Zone': 'first',
    'Threshold': 'first',
    'Operator': 'first'
}).reset_index()

# Ordenar pelo valor de LRC somado (maior para menor)
lrc_summed_df = lrc_summed_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
# vamoss pegar so os valore sunicos de lrc_summed_df baseado na zona espectral
lrc_summed_unique_df_cov = lrc_summed_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
lrc_summed_unique_df_cov = lrc_summed_unique_df_cov.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
lrc_summed_unique_df_cov

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator
0,Fe ka > -9.53,19.009694,Fe ka,-9.53,>
1,Ca ka > -9.12,8.492395,Ca ka,-9.12,>
2,Fe kb > -3.35,7.490101,Fe kb,-3.35,>
3,Ti ka <= 9.71,5.126727,Ti ka,9.71,<=
4,Ca kb > -3.42,3.485165,Ca kb,-3.42,>
5,Cu ka > -3.81,2.499811,Cu ka,-3.81,>
6,Ti kb <= 5.00,2.206161,Ti kb,5.00,<=
7,Cu kb > -1.94,0.498706,Cu kb,-1.94,>
8,Zn ka <= 2.74,0.240208,Zn ka,2.74,<=
9,background5 <= 2.48,0.211577,background5,2.48,<=
10,background2 <= 3.28,0.185693,background2,3.28,<=
11,background4 <= 2.89,0.143628,background4,2.89,<=
12,Ag ka scattering <= 2.57,0.123694,Ag ka scattering,2.57,<=
13,background6 > -2.43,0.115348,background6,-2.43,>
14,background1 <= 2.22,0.102486,background1,2.22,<=
15,background3 <= 1.70,0.094217,background3,1.70,<=
16,Ar ka + Ag L <= 2.08,0.088462,Ar ka + Ag L,2.08,<=
17,Zn kb <= 1.87,0.086885,Zn kb,1.87,<=
18,Class_B,0.000000,None,None,None

# **Perturbation**

In [38]:
import explaining as exp

# LISTA DE SEMENTES A TESTAR
random_seeds = [0, 1, 2, 3]

all_results_pert = {}
training_samples = len(Xcalclass)

# LOOP: PROCESSAR CADA SEMENTE
y_predicted_numeric = plsda_results[5].iloc[:, -1] # predições numéricas do modelo

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando semente: {seed}")
    print(f"{'='*70}\n")
    # Bagging
    bags_result_seed = exp.bagging_predicates(
        zone_sums_df=zone_sums_df,
        y_predicted_numeric=y_predicted_numeric,
        predicates_df=predicates_quantiles[0],
        n_bags=10,
        #n_predicates_per_bag=40,
        n_samples_per_bag=int(training_samples*0.8), # 80 % da base para amostrar (convertido para int)
        min_samples_per_predicate=int(training_samples*0.2), # 20 % da base para limitar (convertido para int)
        replace=False,
        sample_bagging=True,
        predicate_bagging=False,
        random_seed=seed
    )
    # Inserir classe prevista
    for bag_name, pred_dict in bags_result_seed.items(): # iterando sobre cada bag
        for pred_rule, df_info in pred_dict.items():
            df_info['Class_Predicted'] = np.where(df_info['Predicted_Y'] >= 0.5, 'A', 'B') # binarizando com threshold 0.5, A = eut, B = dist

    pert_results_seed = exp.calculate_predicate_perturbation(
        estimator=pls_model,
        Xcalclass_prep=Xcalclass_prep,
        folds_struct=bags_result_seed,
        predicates_df=predicates_quantiles[0],
        spectral_cuts=spectral_cuts,
        #perturbation_value=0,
        perturbation_mode='mean', # valores entre 'mean' ou 'min'
        stats_source='full', # full indica usar todas as amostras para calcular estatísticas enquanto que 'fold' usa apenas as amostras do fold atual
        metric='mean_abs_diff',   # Média com sinal (pode ser negativo)
        verbose=True
    )

    # Remove todos os valores iguais a zero de todos os bags em perm_results[bag]["Permutation"] e salva como perm_results_thresholded
    # pert_results_seed_thresholded = {}
    # for bag, df in perm_results_seed.items():
    #     # Verifica se é um DataFrame e se a coluna 'Permutation' existe
    #     if isinstance(df, pd.DataFrame) and 'Permutation' in df.columns:
    #         filtered_df = df[df['Permutation'] > 0].copy()
    #         pert_results_seed_thresholded[bag] = filtered_df
    #     else:
    #         # Se não for DataFrame esperado, apenas copia
    #         pert_results_seed_thresholded[bag] = df

    # Salvar no dicionário principal
    all_results_pert[seed] = {
        'bags_result': bags_result_seed,
        'pert_results_dict': pert_results_seed
    }

# CONSTRUÇÃO DE GRAFOS PARA MÚLTIPLAS SEMENTES (LOOP EXTERNO)
# Dicionário para armazenar grafos
graphs_pert_by_seed = {}

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando Grafo - Semente: {seed}")
    print(f"{'='*70}\n")
    # Construir grafo para esta semente
    DG = exp.build_predicate_graphv2(
        bags_result=all_results_pert[seed]['bags_result'],
        predicate_ranking_dict=all_results_pert[seed]['pert_results_dict'],
        metric_column='Perturbation',  # ou 'Covariance' se mudar a métrica
        random_state=seed,
        show_details=True
    )
    # Armazenar grafo
    graphs_pert_by_seed[seed] = DG  

# Calcular LRC usando a função pronta do explaining.py
lrc_pert_by_seed = {}
for seed in random_seeds:
    DG = graphs_pert_by_seed[seed]
    lrc_pert_df_seed = exp.calculate_lrc_single_graph(DG, predicates_quantiles[0])
    lrc_pert_df_seed['Seed'] = seed  # Adicionar coluna com a semente
    lrc_pert_by_seed[seed] = lrc_pert_df_seed

# junando todas as colunas 'Node' de lrc_by_seed em um único dataframe
lrc_pert_all_seeds_df = pd.DataFrame()
for seed in random_seeds:
    lrc_pert_df_seed = lrc_pert_by_seed[seed].rename(columns={'Node': f'Predicate_pert_Seed_{seed}'})
    lrc_pert_all_seeds_df = pd.concat([lrc_pert_all_seeds_df, lrc_pert_df_seed[[f'Predicate_pert_Seed_{seed}']]], axis=1)

# vamos filtrar lrc_by_seed em cada semente para manter apenas as zonas espectrais únicas com maior LRC em um mesmo dataframe
lrc_pert_unique_by_seed = {}
for seed, lrc_df in lrc_pert_by_seed.items():
    lrc_pert_unique_df = lrc_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
    lrc_pert_unique_df = lrc_pert_unique_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
    lrc_pert_unique_by_seed[seed] = lrc_pert_unique_df

lrc_pert_all_seeds_df # exibindo o dataframe consolidado com predicados de todas as sementes

======================================================================
Processando semente: 0
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 109 | Descartados: 35
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 109 | Descartados: 35
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 108 | Descartados: 36
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 108 | Descartados: 36
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 108 | Descartados: 36
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 109 | Descartados: 35
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 108 | Descartados: 36
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 108 | Descartados: 36
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 108 | Descartados: 36
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 108 | Descartados: 36
======================================================================
PERTURBATION IMPORTANCE PARA PREDICADOS
======================================================================
Modo de perturbação: mean
Fonte das estatísticas: full
Métrica: mean_abs_diff
Total de folds: 10


[Bag_1] Processando 109 predicados...
  Predicado: background1 > -2.42 (n=186)
    Zona: 69 colunas
    Importance: 0.000815
  Predicado: background1 <= 2.22 (n=86)
    Zona: 69 colunas
    Importance: 0.000792
  Predicado: background1 > 2.22 (n=141)
    Zona: 69 colunas
    Importance: 0.000823
  Predicado: background1 <= 2.53 (n=137)
    Zona: 69 colunas
    Importance: 0.000802
  Predicado: background1 > 2.53 (n=90)
    Zona: 69 colunas
    Importance: 0.000825
  Predicado: background1 <= 3.00 (n=180)
    Zona: 69 colunas
    Importance: 0.000812
  Predicado: Ar ka + Ag L > -2.22 (n=184)
    Zona: 29 colunas
    Importance: 0.000593
  Predicado: Ar ka + Ag L <= -1.64 (n=93)
    Zona: 29 colunas
    Importance: 0.000652
  Predicado: Ar ka + Ag L > -1.64 (n=134)
    Zona: 29 colunas
    Importance: 0.000594
  Predicado: Ar ka + Ag L <= 2.08 (n=136)
    Zona: 29 colunas
    Importance: 0.000605
  Predicado: Ar ka + Ag L > 2.08 (n=91)
    Zona: 29 colunas
    Importance: 0.000637
  Predicado: Ar ka + Ag L <= 2.47 (n=181)
    Zona: 29 colunas
    Importance: 0.000588
  Predicado: Ca ka > -11.34 (n=185)
    Zona: 17 colunas
    Importance: 0.079126
  Predicado: Ca ka <= -9.12 (n=89)
    Zona: 17 colunas
    Importance: 0.078207
  Predicado: Ca ka > -9.12 (n=138)
    Zona: 17 colunas
    Importance: 0.080574
  Predicado: Ca ka <= -3.71 (n=132)
    Zona: 17 colunas
    Importance: 0.064870
  Predicado: Ca ka > -3.71 (n=95)
    Zona: 17 colunas
    Importance: 0.100177
  Predicado: Ca ka <= 15.99 (n=181)
    Zona: 17 colunas
    Importance: 0.057551
  Predicado: Ca kb > -4.15 (n=185)
    Zona: 13 colunas
    Importance: 0.009610
  Predicado: Ca kb <= -3.42 (n=89)
    Zona: 13 colunas
    Importance: 0.009202
  Predicado: Ca kb > -3.42 (n=138)
    Zona: 13 colunas
    Importance: 0.009970
  Predicado: Ca kb <= -2.18 (n=134)
    Zona: 13 colunas
    Importance: 0.007612
  Predicado: Ca kb > -2.18 (n=93)
    Zona: 13 colunas
    Importance: 0.012632
  Predicado: Ca kb <= 6.30 (n=181)
    Zona: 13 colunas
    Importance: 0.007045
  Predicado: Ti ka > -11.81 (n=180)
    Zona: 19 colunas
    Importance: 0.226750
  Predicado: Ti ka <= -3.08 (n=93)
    Zona: 19 colunas
    Importance: 0.303326
  Predicado: Ti ka > -3.08 (n=134)
    Zona: 19 colunas
    Importance: 0.216423
  Predicado: Ti ka <= 5.26 (n=137)
    Zona: 19 colunas
    Importance: 0.224001
  Predicado: Ti ka > 5.26 (n=90)
    Zona: 19 colunas
    Importance: 0.294687
  Predicado: Ti ka <= 9.71 (n=182)
    Zona: 19 colunas
    Importance: 0.215724
  Predicado: Ti kb > -4.43 (n=186)
    Zona: 16 colunas
    Importance: 0.033638
  Predicado: Ti kb <= -2.36 (n=91)
    Zona: 16 colunas
    Importance: 0.042978
  Predicado: Ti kb > -2.36 (n=136)
    Zona: 16 colunas
    Importance: 0.031784
  Predicado: Ti kb <= 2.64 (n=137)
    Zona: 16 colunas
    Importance: 0.031696
  Predicado: Ti kb > 2.64 (n=90)
    Zona: 16 colunas
    Importance: 0.043237
  Predicado: Ti kb <= 5.00 (n=179)
    Zona: 16 colunas
    Importance: 0.028886
  Predicado: background2 > -2.08 (n=185)
    Zona: 39 colunas
    Importance: 0.001723
  Predicado: background2 <= 2.16 (n=89)
    Zona: 39 colunas
    Importance: 0.001397
  Predicado: background2 > 2.16 (n=138)
    Zona: 39 colunas
    Importance: 0.001861
  Predicado: background2 <= 2.59 (n=133)
    Zona: 39 colunas
    Importance: 0.001339
  Predicado: background2 > 2.59 (n=94)
    Zona: 39 colunas
    Importance: 0.002159
  Predicado: background2 <= 3.28 (n=182)
    Zona: 39 colunas
    Importance: 0.001460
  Predicado: Fe ka <= -10.00 (n=58)
    Zona: 25 colunas
    Importance: 0.007131
  Predicado: Fe ka > -10.00 (n=169)
    Zona: 25 colunas
    Importance: 0.014950
  Predicado: Fe ka <= -9.80 (n=90)
    Zona: 25 colunas
    Importance: 0.007127
  Predicado: Fe ka > -9.80 (n=137)
    Zona: 25 colunas
    Importance: 0.016779
  Predicado: Fe ka <= -9.53 (n=138)
    Zona: 25 colunas
    Importance: 0.007041
  Predicado: Fe ka > -9.53 (n=89)
    Zona: 25 colunas
    Importance: 0.022118
  Predicado: Fe ka <= -9.25 (n=182)
    Zona: 25 colunas
    Importance: 0.007002
  Predicado: Fe kb > -3.78 (n=195)
    Zona: 22 colunas
    Importance: 0.003024
  Predicado: Fe kb <= -3.54 (n=84)
    Zona: 22 colunas
    Importance: 0.001593
  Predicado: Fe kb > -3.54 (n=143)
    Zona: 22 colunas
    Importance: 0.003549
  Predicado: Fe kb <= -3.35 (n=134)
    Zona: 22 colunas
    Importance: 0.001571
  Predicado: Fe kb > -3.35 (n=93)
    Zona: 22 colunas
    Importance: 0.004632
  Predicado: Fe kb <= -3.14 (n=174)
    Zona: 22 colunas
    Importance: 0.001558
  Predicado: background3 > -1.63 (n=179)
    Zona: 18 colunas
    Importance: 0.000318
  Predicado: background3 <= 1.70 (n=90)
    Zona: 18 colunas
    Importance: 0.000320
  Predicado: background3 > 1.70 (n=137)
    Zona: 18 colunas
    Importance: 0.000316
  Predicado: background3 <= 2.09 (n=129)
    Zona: 18 colunas
    Importance: 0.000305
  Predicado: background3 > 2.09 (n=98)
    Zona: 18 colunas
    Importance: 0.000333
  Predicado: background3 <= 2.47 (n=178)
    Zona: 18 colunas
    Importance: 0.000310
  Predicado: Cu ka > -4.62 (n=182)
    Zona: 20 colunas
    Importance: 0.043381
  Predicado: Cu ka <= -4.31 (n=84)
    Zona: 20 colunas
    Importance: 0.027292
  Predicado: Cu ka > -4.31 (n=143)
    Zona: 20 colunas
    Importance: 0.048028
  Predicado: Cu ka <= -3.81 (n=133)
    Zona: 20 colunas
    Importance: 0.026313
  Predicado: Cu ka > -3.81 (n=94)
    Zona: 20 colunas
    Importance: 0.060221
  Predicado: Cu ka <= -2.19 (n=179)
    Zona: 20 colunas
    Importance: 0.024200
  Predicado: Zn ka > -1.99 (n=186)
    Zona: 21 colunas
    Importance: 0.000833
  Predicado: Zn ka <= -1.46 (n=86)
    Zona: 21 colunas
    Importance: 0.000793
  Predicado: Zn ka > -1.46 (n=141)
    Zona: 21 colunas
    Importance: 0.000885
  Predicado: Zn ka <= 2.18 (n=133)
    Zona: 21 colunas
    Importance: 0.000705
  Predicado: Zn ka > 2.18 (n=94)
    Zona: 21 colunas
    Importance: 0.001056
  Predicado: Zn ka <= 2.74 (n=183)
    Zona: 21 colunas
    Importance: 0.000690
  Predicado: Cu kb > -2.22 (n=188)
    Zona: 19 colunas
    Importance: 0.002187
  Predicado: Cu kb <= -1.94 (n=94)
    Zona: 19 colunas
    Importance: 0.001480
  Predicado: Cu kb > -1.94 (n=133)
    Zona: 19 colunas
    Importance: 0.002522
  Predicado: Cu kb <= 1.49 (n=135)
    Zona: 19 colunas
    Importance: 0.001377
  Predicado: Cu kb > 1.49 (n=92)
    Zona: 19 colunas
    Importance: 0.003137
  Predicado: Cu kb <= 2.72 (n=180)
    Zona: 19 colunas
    Importance: 0.001274
  Predicado: Zn kb > -2.02 (n=183)
    Zona: 30 colunas
    Importance: 0.000466
  Predicado: Zn kb <= 1.87 (n=92)
    Zona: 30 colunas
    Importance: 0.000445
  Predicado: Zn kb > 1.87 (n=135)
    Zona: 30 colunas
    Importance: 0.000482
  Predicado: Zn kb <= 2.27 (n=136)
    Zona: 30 colunas
    Importance: 0.000438
  Predicado: Zn kb > 2.27 (n=91)
    Zona: 30 colunas
    Importance: 0.000511
  Predicado: Zn kb <= 2.73 (n=180)
    Zona: 30 colunas
    Importance: 0.000441
  Predicado: background4 > -3.06 (n=185)
    Zona: 451 colunas
    Importance: 0.006458
  Predicado: background4 <= 2.89 (n=93)
    Zona: 451 colunas
    Importance: 0.007468
  Predicado: background4 > 2.89 (n=134)
    Zona: 451 colunas
    Importance: 0.006203
  Predicado: background4 <= 3.24 (n=138)
    Zona: 451 colunas
    Importance: 0.007279
  Predicado: background4 > 3.24 (n=89)
    Zona: 451 colunas
    Importance: 0.005856
  Predicado: background4 <= 3.54 (n=181)
    Zona: 451 colunas
    Importance: 0.007022
  Predicado: Ag ka scattering > -2.84 (n=185)
    Zona: 49 colunas
    Importance: 0.012221
  Predicado: Ag ka scattering <= -1.94 (n=87)
    Zona: 49 colunas
    Importance: 0.017129
  Predicado: Ag ka scattering > -1.94 (n=140)
    Zona: 49 colunas
    Importance: 0.013821
  Predicado: Ag ka scattering <= 2.57 (n=131)
    Zona: 49 colunas
    Importance: 0.014423
  Predicado: Ag ka scattering > 2.57 (n=96)
    Zona: 49 colunas
    Importance: 0.015998
  Predicado: Ag ka scattering <= 3.08 (n=178)
    Zona: 49 colunas
    Importance: 0.013796
  Predicado: background5 > -2.53 (n=183)
    Zona: 71 colunas
    Importance: 0.001249
  Predicado: background5 <= 2.03 (n=84)
    Zona: 71 colunas
    Importance: 0.001266
  Predicado: background5 > 2.03 (n=143)
    Zona: 71 colunas
    Importance: 0.001353
  Predicado: background5 <= 2.48 (n=131)
    Zona: 71 colunas
    Importance: 0.001256
  Predicado: background5 > 2.48 (n=96)
    Zona: 71 colunas
    Importance: 0.001410
  Predicado: background5 <= 2.88 (n=179)
    Zona: 71 colunas
    Importance: 0.001258
  Predicado: background6 > -2.43 (n=181)
    Zona: 61 colunas
    Importance: 0.004528
  Predicado: background6 <= 2.28 (n=89)
    Zona: 61 colunas
    Importance: 0.005971
  Predicado: background6 > 2.28 (n=138)
    Zona: 61 colunas
    Importance: 0.005027
  Predicado: background6 <= 2.71 (n=137)
    Zona: 61 colunas
    Importance: 0.005515
  Predicado: background6 > 2.71 (n=90)
    Zona: 61 colunas
    Importance: 0.005217
  Predicado: background6 <= 3.20 (n=182)
    Zona: 61 colunas
    Importance: 0.005279

[Bag_2] Processando 109 predicados...
  Predicado: background1 > -2.42 (n=184)
    Zona: 69 colunas
    Importance: 0.000763
  Predicado: background1 <= 2.22 (n=88)
    Zona: 69 colunas
    Importance: 0.000761
  Predicado: background1 > 2.22 (n=139)
    Zona: 69 colunas
    Importance: 0.000785
  Predicado: background1 <= 2.53 (n=136)
    Zona: 69 colunas
    Importance: 0.000779
  Predicado: background1 > 2.53 (n=91)
    Zona: 69 colunas
    Importance: 0.000770
  Predicado: background1 <= 3.00 (n=178)
    Zona: 69 colunas
    Importance: 0.000780
  Predicado: Ar ka + Ag L > -2.22 (n=182)
    Zona: 29 colunas
    Importance: 0.000599
  Predicado: Ar ka + Ag L <= -1.64 (n=95)
    Zona: 29 colunas
    Importance: 0.000602
  Predicado: Ar ka + Ag L > -1.64 (n=132)
    Zona: 29 colunas
    Importance: 0.000619
  Predicado: Ar ka + Ag L <= 2.08 (n=143)
    Zona: 29 colunas
    Importance: 0.000592
  Predicado: Ar ka + Ag L > 2.08 (n=84)
    Zona: 29 colunas
    Importance: 0.000646
  Predicado: Ar ka + Ag L <= 2.47 (n=184)
    Zona: 29 colunas
    Importance: 0.000567
  Predicado: Ca ka > -11.34 (n=185)
    Zona: 17 colunas
    Importance: 0.078905
  Predicado: Ca ka <= -9.12 (n=85)
    Zona: 17 colunas
    Importance: 0.078451
  Predicado: Ca ka > -9.12 (n=142)
    Zona: 17 colunas
    Importance: 0.079980
  Predicado: Ca ka <= -3.71 (n=130)
    Zona: 17 colunas
    Importance: 0.063999
  Predicado: Ca ka > -3.71 (n=97)
    Zona: 17 colunas
    Importance: 0.100058
  Predicado: Ca ka <= 15.99 (n=179)
    Zona: 17 colunas
    Importance: 0.055799
  Predicado: Ca kb > -4.15 (n=184)
    Zona: 13 colunas
    Importance: 0.009611
  Predicado: Ca kb <= -3.42 (n=87)
    Zona: 13 colunas
    Importance: 0.009225
  Predicado: Ca kb > -3.42 (n=140)
    Zona: 13 colunas
    Importance: 0.009940
  Predicado: Ca kb <= -2.18 (n=133)
    Zona: 13 colunas
    Importance: 0.007522
  Predicado: Ca kb > -2.18 (n=94)
    Zona: 13 colunas
    Importance: 0.012699
  Predicado: Ca kb <= 6.30 (n=179)
    Zona: 13 colunas
    Importance: 0.006857
  Predicado: Ti ka > -11.81 (n=177)
    Zona: 19 colunas
    Importance: 0.220622
  Predicado: Ti ka <= -3.08 (n=94)
    Zona: 19 colunas
    Importance: 0.305593
  Predicado: Ti ka > -3.08 (n=133)
    Zona: 19 colunas
    Importance: 0.208867
  Predicado: Ti ka <= 5.26 (n=140)
    Zona: 19 colunas
    Importance: 0.225298
  Predicado: Ti ka > 5.26 (n=87)
    Zona: 19 colunas
    Importance: 0.286935
  Predicado: Ti ka <= 9.71 (n=183)
    Zona: 19 colunas
    Importance: 0.214755
  Predicado: Ti kb > -4.43 (n=182)
    Zona: 16 colunas
    Importance: 0.032155
  Predicado: Ti kb <= -2.36 (n=94)
    Zona: 16 colunas
    Importance: 0.042822
  Predicado: Ti kb > -2.36 (n=133)
    Zona: 16 colunas
    Importance: 0.030173
  Predicado: Ti kb <= 2.64 (n=138)
    Zona: 16 colunas
    Importance: 0.031722
  Predicado: Ti kb > 2.64 (n=89)
    Zona: 16 colunas
    Importance: 0.041130
  Predicado: Ti kb <= 5.00 (n=183)
    Zona: 16 colunas
    Importance: 0.028672
  Predicado: background2 > -2.08 (n=184)
    Zona: 39 colunas
    Importance: 0.001644
  Predicado: background2 <= 2.16 (n=92)
    Zona: 39 colunas
    Importance: 0.001415
  Predicado: background2 > 2.16 (n=135)
    Zona: 39 colunas
    Importance: 0.001761
  Predicado: background2 <= 2.59 (n=135)
    Zona: 39 colunas
    Importance: 0.001314
  Predicado: background2 > 2.59 (n=92)
    Zona: 39 colunas
    Importance: 0.002071
  Predicado: background2 <= 3.28 (n=182)
    Zona: 39 colunas
    Importance: 0.001392
  Predicado: Fe ka <= -10.00 (n=56)
    Zona: 25 colunas
    Importance: 0.007150
  Predicado: Fe ka > -10.00 (n=171)
    Zona: 25 colunas
    Importance: 0.014593
  Predicado: Fe ka <= -9.80 (n=83)
    Zona: 25 colunas
    Importance: 0.007109
  Predicado: Fe ka > -9.80 (n=144)
    Zona: 25 colunas
    Importance: 0.016012
  Predicado: Fe ka <= -9.53 (n=134)
    Zona: 25 colunas
    Importance: 0.007027
  Predicado: Fe ka > -9.53 (n=93)
    Zona: 25 colunas
    Importance: 0.021012
  Predicado: Fe ka <= -9.25 (n=185)
    Zona: 25 colunas
    Importance: 0.006988
  Predicado: Fe kb > -3.78 (n=191)
    Zona: 22 colunas
    Importance: 0.003006
  Predicado: Fe kb <= -3.54 (n=85)
    Zona: 22 colunas
    Importance: 0.001574
  Predicado: Fe kb > -3.54 (n=142)
    Zona: 22 colunas
    Importance: 0.003510
  Predicado: Fe kb <= -3.35 (n=139)
    Zona: 22 colunas
    Importance: 0.001556
  Predicado: Fe kb > -3.35 (n=88)
    Zona: 22 colunas
    Importance: 0.004727
  Predicado: Fe kb <= -3.14 (n=177)
    Zona: 22 colunas
    Importance: 0.001538
  Predicado: background3 > -1.63 (n=180)
    Zona: 18 colunas
    Importance: 0.000305
  Predicado: background3 <= 1.70 (n=92)
    Zona: 18 colunas
    Importance: 0.000320
  Predicado: background3 > 1.70 (n=135)
    Zona: 18 colunas
    Importance: 0.000306
  Predicado: background3 <= 2.09 (n=133)
    Zona: 18 colunas
    Importance: 0.000303
  Predicado: background3 > 2.09 (n=94)
    Zona: 18 colunas
    Importance: 0.000323
  Predicado: background3 <= 2.47 (n=179)
    Zona: 18 colunas
    Importance: 0.000303
  Predicado: Cu ka > -4.62 (n=183)
    Zona: 20 colunas
    Importance: 0.040339
  Predicado: Cu ka <= -4.31 (n=93)
    Zona: 20 colunas
    Importance: 0.027224
  Predicado: Cu ka > -4.31 (n=134)
    Zona: 20 colunas
    Importance: 0.045471
  Predicado: Cu ka <= -3.81 (n=136)
    Zona: 20 colunas
    Importance: 0.026311
  Predicado: Cu ka > -3.81 (n=91)
    Zona: 20 colunas
    Importance: 0.055458
  Predicado: Cu ka <= -2.19 (n=181)
    Zona: 20 colunas
    Importance: 0.024268
  Predicado: Zn ka > -1.99 (n=181)
    Zona: 21 colunas
    Importance: 0.000856
  Predicado: Zn ka <= -1.46 (n=90)
    Zona: 21 colunas
    Importance: 0.000755
  Predicado: Zn ka > -1.46 (n=137)
    Zona: 21 colunas
    Importance: 0.000905
  Predicado: Zn ka <= 2.18 (n=134)
    Zona: 21 colunas
    Importance: 0.000704
  Predicado: Zn ka > 2.18 (n=93)
    Zona: 21 colunas
    Importance: 0.001050
  Predicado: Zn ka <= 2.74 (n=181)
    Zona: 21 colunas
    Importance: 0.000700
  Predicado: Cu kb > -2.22 (n=191)
    Zona: 19 colunas
    Importance: 0.002050
  Predicado: Cu kb <= -1.94 (n=88)
    Zona: 19 colunas
    Importance: 0.001479
  Predicado: Cu kb > -1.94 (n=139)
    Zona: 19 colunas
    Importance: 0.002307
  Predicado: Cu kb <= 1.49 (n=135)
    Zona: 19 colunas
    Importance: 0.001359
  Predicado: Cu kb > 1.49 (n=92)
    Zona: 19 colunas
    Importance: 0.002906
  Predicado: Cu kb <= 2.72 (n=182)
    Zona: 19 colunas
    Importance: 0.001254
  Predicado: Zn kb > -2.02 (n=180)
    Zona: 30 colunas
    Importance: 0.000466
  Predicado: Zn kb <= 1.87 (n=92)
    Zona: 30 colunas
    Importance: 0.000422
  Predicado: Zn kb > 1.87 (n=135)
    Zona: 30 colunas
    Importance: 0.000491
  Predicado: Zn kb <= 2.27 (n=133)
    Zona: 30 colunas
    Importance: 0.000414
  Predicado: Zn kb > 2.27 (n=94)
    Zona: 30 colunas
    Importance: 0.000532
  Predicado: Zn kb <= 2.73 (n=181)
    Zona: 30 colunas
    Importance: 0.000424
  Predicado: background4 > -3.06 (n=181)
    Zona: 451 colunas
    Importance: 0.006158
  Predicado: background4 <= 2.89 (n=91)
    Zona: 451 colunas
    Importance: 0.007857
  Predicado: background4 > 2.89 (n=136)
    Zona: 451 colunas
    Importance: 0.005748
  Predicado: background4 <= 3.24 (n=138)
    Zona: 451 colunas
    Importance: 0.007283
  Predicado: background4 > 3.24 (n=89)
    Zona: 451 colunas
    Importance: 0.005524
  Predicado: background4 <= 3.54 (n=182)
    Zona: 451 colunas
    Importance: 0.006893
  Predicado: Ag ka scattering > -2.84 (n=183)
    Zona: 49 colunas
    Importance: 0.011619
  Predicado: Ag ka scattering <= -1.94 (n=96)
    Zona: 49 colunas
    Importance: 0.016930
  Predicado: Ag ka scattering > -1.94 (n=131)
    Zona: 49 colunas
    Importance: 0.013506
  Predicado: Ag ka scattering <= 2.57 (n=138)
    Zona: 49 colunas
    Importance: 0.014694
  Predicado: Ag ka scattering > 2.57 (n=89)
    Zona: 49 colunas
    Importance: 0.015356
  Predicado: Ag ka scattering <= 3.08 (n=178)
    Zona: 49 colunas
    Importance: 0.014051
  Predicado: background5 > -2.53 (n=182)
    Zona: 71 colunas
    Importance: 0.001230
  Predicado: background5 <= 2.03 (n=93)
    Zona: 71 colunas
    Importance: 0.001218
  Predicado: background5 > 2.03 (n=134)
    Zona: 71 colunas
    Importance: 0.001300
  Predicado: background5 <= 2.48 (n=138)
    Zona: 71 colunas
    Importance: 0.001231
  Predicado: background5 > 2.48 (n=89)
    Zona: 71 colunas
    Importance: 0.001321
  Predicado: background5 <= 2.88 (n=183)
    Zona: 71 colunas
    Importance: 0.001220
  Predicado: background6 > -2.43 (n=183)
    Zona: 61 colunas
    Importance: 0.004427
  Predicado: background6 <= 2.28 (n=84)
    Zona: 61 colunas
    Importance: 0.006080
  Predicado: background6 > 2.28 (n=143)
    Zona: 61 colunas
    Importance: 0.004816
  Predicado: background6 <= 2.71 (n=134)
    Zona: 61 colunas
    Importance: 0.005488
  Predicado: background6 > 2.71 (n=93)
    Zona: 61 colunas
    Importance: 0.004990
  Predicado: background6 <= 3.20 (n=181)
    Zona: 61 colunas
    Importance: 0.005197

[Bag_3] Processando 108 predicados...
  Predicado: background1 > -2.42 (n=186)
    Zona: 69 colunas
    Importance: 0.000842
  Predicado: background1 <= 2.22 (n=89)
    Zona: 69 colunas
    Importance: 0.000817
  Predicado: background1 > 2.22 (n=138)
    Zona: 69 colunas
    Importance: 0.000838
  Predicado: background1 <= 2.53 (n=138)
    Zona: 69 colunas
    Importance: 0.000807

,Predicate_pert_Seed_0,Predicate_pert_Seed_1,Predicate_pert_Seed_2,Predicate_pert_Seed_3
0,Ti ka <= -3.08,Ti ka <= -3.08,Ti ka <= -3.08,Ti ka <= -3.08
1,Ti ka > 5.26,Ti ka > 5.26,Ti ka > 5.26,Ti ka > 5.26
2,Ti ka <= 5.26,Ti ka <= 5.26,Ti ka > -11.81,Ti ka > -11.81
3,Ti ka > -11.81,Ti ka > -11.81,Ti ka <= 5.26,Ti ka <= 9.71
4,Ti ka <= 9.71,Ti ka <= 9.71,Ti ka > -3.08,Ti ka <= 5.26
...,...,...,...,...
107,background3 <= 2.47,background3 <= 2.47,background3 > -1.63,background3 > -1.63
108,background3 <= 2.09,background3 <= 1.70,background3 <= 2.09,background3 <= 2.09
109,Class_A,background3 <= 2.09,Class_A,Class_A
110,Class_B,Class_A,Class_B,Class_B
111,NaN,Class_B,NaN,NaN

In [51]:
all_results_pert[0]['pert_results_dict']['Bag_5']

               Predicate  Perturbation
0         Ti ka <= -3.08      0.300986
1           Ti ka > 5.26      0.286842
2         Ti ka > -11.81      0.222137
3          Ti ka <= 5.26      0.218508
4          Ti ka > -3.08      0.212503
..                   ...           ...
103   background3 > 1.70      0.000304
104  background3 <= 1.70      0.000301
105  background3 > -1.63      0.000298
106  background3 <= 2.47      0.000294
107  background3 <= 2.09      0.000286

[108 rows x 2 columns]

In [39]:
# Somar LRCs de predicados equivalentes entre diferentes seeds
lrc_combined_list = []

for seed in random_seeds:
    lrc_df = lrc_pert_by_seed[seed].copy()
    lrc_combined_list.append(lrc_df) # o append adiciona o dataframe ao final da lista

# Concatenar todos os dataframes
lrc_all_seeds = pd.concat(lrc_combined_list, ignore_index=True) 

# Agrupar por predicado (Node) e somar as LRCs, mantendo Zone, Threshold e Operator
lrc_summed_df = lrc_all_seeds.groupby('Node').agg({ # o .agg pode ser usado para aplicar múltiplas funções de agregação
    'Local_Reaching_Centrality': 'mean', # sum = somando as LRCs, poderia ser média ou outro agregado
    'Zone': 'first',
    'Threshold': 'first',
    'Operator': 'first'
}).reset_index()

# Ordenar pelo valor de LRC somado (maior para menor)
lrc_summed_df = lrc_summed_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
# vamoss pegar so os valore sunicos de lrc_summed_df baseado na zona espectral
lrc_summed_unique_df_pert = lrc_summed_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
lrc_summed_unique_df_pert = lrc_summed_unique_df_pert.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
lrc_summed_unique_df_pert

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator
0,Ti ka <= -3.08,6.234661,Ti ka,-3.08,<=
1,Ca ka > -3.71,1.961756,Ca ka,-3.71,>
2,Cu ka > -3.81,1.250916,Cu ka,-3.81,>
3,Ti kb <= -2.36,1.061949,Ti kb,-2.36,<=
4,Fe ka > -9.53,0.434244,Fe ka,-9.53,>
5,Ag ka scattering <= -1.94,0.361012,Ag ka scattering,-1.94,<=
6,Ca kb > -2.18,0.311781,Ca kb,-2.18,>
7,background4 <= 2.89,0.183743,background4,2.89,<=
8,Fe kb > -3.14,0.151283,Fe kb,-3.14,>
9,background6 <= 2.28,0.138226,background6,2.28,<=
10,Cu kb > 1.49,0.063611,Cu kb,1.49,>
11,background2 > 2.59,0.047582,background2,2.59,>
12,background5 > 2.48,0.017582,background5,2.48,>
13,Zn ka > 2.18,0.013184,Zn ka,2.18,>
14,background1 <= 2.53,0.007559,background1,2.53,<=
15,Ar ka + Ag L > 2.08,0.005478,Ar ka + Ag L,2.08,>
16,Zn kb > 2.27,0.004213,Zn kb,2.27,>
17,background3 > 2.09,0.000958,background3,2.09,>
18,Class_A,0.000000,None,None,None

In [43]:
import numpy as np

max_len = max(
    len(vip_scores_unique_df['Zone']),
    len(reg_vet_unique_df['Zone']),
    len(shap_unique_df['Zone']),
    len(lrc_summed_unique_df_pert['Zone']),
    len(lrc_summed_unique_df_cov['Zone'])
)

def pad_list(lst, length):
    return list(lst) + [None] * (length - len(lst))

features_importance = pd.DataFrame({
    'Vip': pad_list(vip_scores_unique_df['Zone'], max_len),
    'Reg_coef': pad_list(reg_vet_unique_df['Zone'], max_len),
    'Shap': pad_list(shap_unique_df['Zone'], max_len),
    'LRC_perturbation' : pad_list(lrc_summed_unique_df_pert['Zone'], max_len),
    'LRC_covariance' : pad_list(lrc_summed_unique_df_cov['Zone'], max_len),
})

features_importance.to_csv('feature_importance.csv', index=False, sep=';')
features_importance

,Vip,Reg_coef,Shap,LRC_perturbation,LRC_covariance
0,Fe ka,Ti ka,Ti ka,Ti ka,Fe ka
1,Ca ka,Ti kb,Ca ka,Ca ka,Ca ka
2,Ti ka,Ag ka scattering,Cu ka,Cu ka,Fe kb
3,Cu ka,Ca ka,Fe ka,Ti kb,Ti ka
4,Fe kb,Cu ka,Ti kb,Fe ka,Ca kb
5,Ca kb,background6,Ag ka scattering,Ag ka scattering,Cu ka
6,Ti kb,Ca kb,background6,Ca kb,Ti kb
7,Ag ka scattering,Cu kb,Ar ka + Ag L,background4,Cu kb
8,background6,background4,background4,Fe kb,Zn ka
9,Cu kb,background2,background5,background6,background5
10,background4,Ar ka + Ag L,background1,Cu kb,background2
11,Zn ka,Zn kb,background2,background2,background4
12,background2,background5,Ca kb,background5,Ag ka scattering
13,Ar ka + Ag L,Fe ka,Fe kb,Zn ka,background6
14,background5,background1,background3,background1,background1
15,Zn kb,Zn ka,Zn ka,Ar ka + Ag L,background3
16,background1,background3,Cu kb,Zn kb,Ar ka + Ag L
17,background3,Fe kb,Zn kb,background3,Zn kb
18,None,None,None,None,None

In [44]:
# RBO (Rank-Biased Overlap) para comparar rankings
import rbo
rbo_results = {}
reference_list = [x for x in features_importance['Vip'].tolist() if x is not None]
methods = ['Reg_coef', 'Shap', 'LRC_covariance', 'LRC_perturbation']
for method in methods:
    compare_list = [x for x in features_importance[method].tolist() if x is not None]
    # Truncate both lists to the same length (minimum of both)
    min_len = min(len(reference_list), len(compare_list))
    ref_trunc = reference_list[:min_len]
    cmp_trunc = compare_list[:min_len]
    score = rbo.RankingSimilarity(ref_trunc, cmp_trunc).rbo(p=0.7, k=10)
    rbo_results[method] = score
rbo_results = pd.DataFrame(list(rbo_results.items()), columns=['Method','RBO_Score'])
rbo_results.insert(0, 'Reference', 'Vip')
rbo_results.sort_values(by='RBO_Score', ascending=False, inplace=True)
rbo_results.to_csv('rbo_rank.csv', index=False, sep=';')
rbo_results

  Reference            Method  RBO_Score
2       Vip    LRC_covariance   0.873269
1       Vip              Shap   0.462804
3       Vip  LRC_perturbation   0.449552
0       Vip          Reg_coef   0.235755